"""Polity 02 stages 4-6."""

STAGES_C = [
    {
        "n": 4,
        "kind": "core",
        "title": "COMPOSITION LEDGER — 389 PLANNED → 299 AFTER PARTITION, WITH THE CATEGORY LOGIC INTACT",
        "pills": [
            {"t": "389 planned", "c": "amber"},
            {"t": "292 + 4 + 93", "c": "cyan"},
            {"t": "Partition re-fixes strength", "c": "red"},
            {"t": "299 = 229 + 70", "c": "green"},
            {"t": "211 = attendance only", "c": "teal"},
            {"t": "284 = signatories only", "c": "yellow"},
        ],
        "blocks": [
            {"type": "replace",
             "before": {"h": "PLANNED COMPOSITION UNDER THE CABINET MISSION SCHEME", "c": "amber", "items": [
                 "**389** total planned strength.",
                 "**292** — eleven **Governors' provinces**.",
                 "**4** — **Chief Commissioners' provinces**, one each.",
                 "**93** — **princely states**, representatives to be nominated by rulers.",
                 "Provincial seats split among **Muslim, Sikh and General** categories in proportion to population.",
                 "The 93 princely-state seats were **initially unfilled** because the states stayed away.",
             ]},
             "after": {"h": "SANCTIONED STRENGTH AFTER PARTITION", "c": "green", "items": [
                 "**299** total sanctioned strength.",
                 "**229** — **provincial** representatives.",
                 "**70** — **princely-state** representatives.",
                 "Members from areas that went to Pakistan ceased to sit in this Assembly.",
                 "The body became **smaller and considerably more homogeneous**, which sharpened the later charge of Congress dominance.",
                 "This — not 389 — is the strength against which the working Assembly must be described.",
             ]},
             "arrow": "PARTITION 1947",
             "note": "Partition did not merely subtract members: it removed the principal political counterweight inside the Assembly, and thereby changed both the arithmetic and the character of the deliberation that produced the final text."},
            {"type": "matrix", "c": "red", "title": "THE FIVE-METRIC BOX — EACH NUMBER WITH ITS OWN DENOMINATOR (OPEN LEGITIMACY ANSWERS WITH THIS)",
             "widths": [0.11, 0.30, 0.34, 0.25],
             "headers": ["FIGURE", "WHAT IT COUNTS", "EXACT MEANING", "THE MISREADING TO KILL"],
             "rows": [
                 ["**389**", "Original **planned** strength", "Design ceiling under the Cabinet Mission scheme: 296 British India + 93 princely states.", "'389 members attended the first meeting.'"],
                 ["**296**", "British India **allocation / election frame**", "292 Governors' provinces + 4 Chief Commissioners' provinces — the seats actually contested in 1946.", "Treating 296 as a body that ever sat as such."],
                 ["**211**", "**Attendance** on 9 December 1946", "Members present at the first sitting amid the Muslim League boycott.", "'The Assembly's strength was 211.'"],
                 ["**299**", "**Post-Partition sanctioned strength**", "229 provincial + 70 princely-state seats — the working Assembly.", "'299 members signed the Constitution.'"],
                 ["**284**", "**Signatories** on 24 January 1950", "Members who actually appended signatures, after adoption.", "'284 was the post-Partition strength.'"],
             ]},
            {"type": "cols", "cols": [
                {"h": "WHAT PARTITION CHANGED", "c": "red", "items": [
                    "**Strength**: 389 → **299**.",
                    "**Internal balance**: the principal opposition bloc left, leaving Congress arithmetically preponderant.",
                    "**Agenda**: separate electorates and the grouping scheme lost their political basis; the Assembly moved decisively towards a **strong Union**.",
                ]},
                {"h": "WHAT PARTITION DID NOT CHANGE", "c": "cyan", "items": [
                    "The **selection method** of the sitting members — they had been chosen under the 1946 scheme and were not re-elected.",
                    "The **committee structure** already at work since December 1946–January 1947.",
                    "The **normative compass** already fixed by the Objectives Resolution adopted on **22 January 1947**.",
                ]},
                {"h": "HOW TO USE THIS IN AN ANSWER", "c": "teal", "items": [
                    "Never answer 'how representative was the Assembly?' with **one number**. Use **selection method, social range, political dominance, boycott and post-Partition change together**.",
                    "Congress dominance was **arithmetically real** — concede it; then show Congress functioned as a **broad coalition** and that the Assembly included non-Congress experts and diverse social voices.",
                    "Sequence: numbers → mechanism → concession → compensating evidence → qualified verdict.",
                ]},
            ]},
            {"type": "answer", "label": "ANSWER-GRABBING LINE — METRIC DISCIPLINE:",
             "text": "Planned strength, election frame, attendance, post-Partition strength and signatures are **five different denominators**: 389 describes a scheme, 296 an allocation, 211 a single day's attendance, 299 the working Assembly and 284 the act of signing — and no legitimacy argument survives their conflation."},
        ],
    },
    {
        "n": 5,
        "kind": "core",
        "title": "ELECTIONS OF JULY–AUGUST 1946 AND THE LEGITIMACY NUANCE",
        "pills": [
            {"t": "Congress 208", "c": "cyan"},
            {"t": "Muslim League 73", "c": "green"},
            {"t": "Others & independents 15", "c": "teal"},
            {"t": "93 princely seats unfilled", "c": "magenta"},
            {"t": "League boycott of first sitting", "c": "red"},
            {"t": "Dominance real, not decisive", "c": "yellow"},
        ],
        "blocks": [
            {"type": "matrix", "c": "cyan", "title": "RESULT OF THE 1946 ELECTIONS FOR THE 296 BRITISH INDIAN SEATS",
             "widths": [0.26, 0.13, 0.35, 0.26],
             "headers": ["GROUP", "SEATS", "WHAT IT MEANT INSIDE THE ASSEMBLY", "WHAT IT DID NOT MEAN"],
             "rows": [
                 ["**Indian National Congress**", "**208**", "A commanding bloc that could carry any proposal it united behind.", "Not a monolith — Congress functioned as a **broad coalition** of ideological strands."],
                 ["**Muslim League**", "**73**", "The principal counterweight; **boycotted** the first meeting and pressed for a separate constituent body.", "Not an absent voice by design — its withdrawal was political, not structural exclusion."],
                 ["**Smaller groups and independents**", "**15**", "Carried non-Congress expertise and minority positions into the debates.", "Not decorative — several were given decisive drafting and committee roles."],
                 ["**Princely states**", "**93**", "Seats **initially unfilled**: the states stayed away at the outset.", "Not a boycott by election — these seats were to be filled by **nomination**."],
             ]},
            {"type": "panels", "mid": "VERSUS", "mid2": "Both sides must appear in a Mains answer; the reply is evidence-led, not defensive",
             "panels": [
                 {"h": "THE CHARGE — DOMINANCE COMPROMISED THE BODY", "c": "red", "sub": "State it fully; a suppressed objection loses marks",
                  "items": [
                      "Congress held **208 of 296** contested seats and, after Partition, an even larger share of a smaller house.",
                      "The **Muslim League boycott** meant the largest opposing political formation was absent from the opening deliberations.",
                      "The electorate behind the provincial legislators was the **restricted franchise** of the period, not the Indian people.",
                      "**93** princely-state representatives entered by **nomination**, adding an unelected element.",
                  ]},
                 {"h": "THE EVIDENCE-LED REPLY", "c": "green", "sub": "Concede the arithmetic, contest the inference",
                  "items": [
                      "Congress dominance was **arithmetically real**, but Congress operated as a **broad coalition** containing conservative, socialist, Gandhian and liberal strands that argued openly against one another.",
                      "The Assembly deliberately seated **non-Congress experts** — Ambedkar and Alladi Krishnaswami Ayyar among them — in the most decisive drafting positions.",
                      "Every clause passed through **clause-by-clause scrutiny**, public comment and thousands of amendments — dominance did not remove contestation.",
                      "The body's **output** extended political equality to every adult Indian, which no restricted electorate had demanded of it.",
                  ]},
             ]},
            {"type": "band", "label": "CALIBRATION →", "c": "yellow", "outline": True,
             "text": "The honest position is neither 'a Congress body' nor 'a fully representative parliament'. It is that a **numerically dominant party** used a **deliberative machinery** it did not fully control — committees, an independent constitutional adviser, a Drafting Committee led by a political outsider, public comment and recorded debate — and produced a text more democratic than its own electorate."},
            {"type": "answer", "label": "ANSWER-GRABBING LINE — LEGITIMACY COMPENSATION:",
             "text": "By constitutionalising **universal adult franchise**, the Assembly prospectively widened political equality **far beyond the restricted electorate through which it had been formed**."},
        ],
    },
    {
        "n": 6,
        "kind": "core",
        "title": "FIRST SITTING, 9 DECEMBER 1946 — OFFICERS, SECRETARIAT AND THE PRODUCTION CHAIN",
        "pills": [
            {"t": "9 Dec 1946 — first sitting", "c": "amber"},
            {"t": "211 attended", "c": "teal"},
            {"t": "Sinha temporary President", "c": "yellow"},
            {"t": "Prasad permanent, 11 Dec 1946", "c": "cyan"},
            {"t": "B.N. Rau Constitutional Adviser", "c": "magenta"},
            {"t": "Institution, not a gathering", "c": "green"},
        ],
        "blocks": [
            {"type": "hub", "centre_w": 0.30,
             "centre": {"t": "THE ASSEMBLY AS AN INSTITUTION",
                        "s": "First sitting **9 December 1946** in the Constitution Hall, New Delhi  •  **211** members attended amid the **Muslim League boycott**  •  offices and a secretariat, not merely an assembly of famous leaders",
                        "c": "yellow"},
             "spokes": [
                 {"h": "TEMPORARY PRESIDENT", "n": "Dr Sachchidananda Sinha", "s": "The oldest member; presided at the opening following the French practice.", "c": "amber"},
                 {"h": "PERMANENT PRESIDENT — elected 11 December 1946", "n": "Dr Rajendra Prasad", "s": "Presided over the constituent deliberations throughout.", "c": "cyan"},
                 {"h": "VICE-PRESIDENTS", "n": "H.C. Mukherjee  ·  V.T. Krishnamachari", "s": "Assisted the presidency and presided in the President's absence.", "c": "teal"},
                 {"h": "CONSTITUTIONAL ADVISER", "n": "Sir B.N. Rau", "s": "Research, comparative advice and the initial constitutional-adviser draft.", "c": "magenta"},
                 {"h": "SECRETARY", "n": "H.V.R. Iyengar", "s": "Ran the Assembly secretariat that serviced every committee.", "c": "green"},
                 {"h": "CHIEF DRAFTSMAN", "n": "S.N. Mukerjee", "s": "Technical legislative drafting of the constitutional text.", "c": "white"},
             ]},
            {"type": "cols", "cols": [
                {"h": "WHY ROLE DIFFERENTIATION IS ITSELF THE ANSWER", "c": "cyan", "items": [
                    "**Secretariat and drafting expertise converted political settlements into administrable text.** A leader-only narrative misses this production chain entirely.",
                    "Three distinct competences were separated: **political authority** (President and committees), **comparative expertise** (Constitutional Adviser) and **legal form** (Chief Draftsman and Drafting Committee).",
                    "This separation is what makes 'distributed authorship' a defensible thesis rather than a slogan.",
                ]},
                {"h": "THE DUAL CAPACITY AFTER INDEPENDENCE", "c": "amber", "items": [
                    "After 15 August 1947 the same body held **two distinct capacities**.",
                    "As the **constituent body** framing the Constitution, it was presided over by **Dr Rajendra Prasad**.",
                    "As the **Dominion legislature** making ordinary law, it was presided over by **G.V. Mavlankar**.",
                    "The two capacities met on different days with different agendas — a favourite Prelims discriminator.",
                ]},
                {"h": "OFFICER TRAPS", "c": "red", "items": [
                    "**Wrong:** Rajendra Prasad was the temporary President.  **Correct:** **Sachchidananda Sinha** was temporary; Prasad was elected permanent President.",
                    "**Wrong:** B.N. Rau chaired the Drafting Committee.  **Correct:** **Ambedkar** chaired it; **Rau was Constitutional Adviser**.",
                    "**Wrong:** the Vice-President of the Assembly later became Vice-President of India.  **Correct:** the offices are unconnected; do not transfer titles.",
                    "**Wrong:** Mavlankar presided over constitution-making.  **Correct:** he presided over the **legislative** capacity only.",
                ]},
            ]},
            {"type": "band", "label": "BRIDGE TO VALUES →", "c": "magenta", "outline": True,
             "text": "Within four days of the first sitting the Assembly turned from constituting itself to declaring what it stood for. On **13 December 1946** Jawaharlal Nehru moved the **Objectives Resolution** — the document that fixed the Constitution's normative compass **before** its clauses were settled."},
        ],
    },
]
