"""Polity 02 — Making of the Constitution: assembled bespoke design content.

Generation g8 (first Carvaka-standard generation for Polity 02).
Authored manually against the canonical learner-v2 Markdown; no content is
re-used from the Polity 01 g9 package.
"""

from spec_header import OWNER, ADV_OWNER, PKG_OWNER, HEADER, FOOTER
from spec_a import STAGES_A
from spec_b import STAGES_B
from spec_c import STAGES_C
from spec_d import STAGES_D
from spec_e import STAGES_E
from spec_f import STAGES_F
from spec_g import STAGES_G
from spec_h import STAGES_H

STAGES = (STAGES_A + STAGES_B + STAGES_C + STAGES_D +
          STAGES_E + STAGES_F + STAGES_G + STAGES_H)

MUST_SHOW = [
    "M.N. Roy",
    "1934",
    "1935",
    "1938",
    "August Offer",
    "Cripps",
    "Cabinet Mission",
    "one seat per million",
    "Governors' provinces",
    "Chief Commissioners' provinces",
    "292",
    "296",
    "93",
    "389",
    "Muslim, Sikh and General",
    "proportional representation through the single transferable vote",
    "nominated by the rulers",
    "indirectly elected",
    "208",
    "73",
    "15",
    "211",
    "9 December 1946",
    "299",
    "229",
    "70",
    "284",
    "24 January 1950",
    "Sachchidananda Sinha",
    "Rajendra Prasad",
    "11 December 1946",
    "H.C. Mukherjee",
    "V.T. Krishnamachari",
    "B.N. Rau",
    "Constitutional Adviser",
    "H.V.R. Iyengar",
    "S.N. Mukerjee",
    "G.V. Mavlankar",
    "Objectives Resolution",
    "13 December 1946",
    "22 January 1947",
    "Preamble",
    "42nd Amendment",
    "1976",
    "Indian Independence Act 1947",
    "Union Powers Committee",
    "Union Constitution Committee",
    "States Committee",
    "Provincial Constitution Committee",
    "Advisory Committee",
    "J.B. Kripalani",
    "Minorities Sub-Committee",
    "Gopinath Bardoloi",
    "A.V. Thakkar",
    "Rules of Procedure",
    "Steering Committee",
    "Drafting Committee",
    "B.R. Ambedkar",
    "29 August 1947",
    "N. Gopalaswami Ayyangar",
    "Alladi Krishnaswami Ayyar",
    "K.M. Munshi",
    "Mohammad Saadulla",
    "B.L. Mitter",
    "D.P. Khaitan",
    "N. Madhava Rau",
    "T.T. Krishnamachari",
    "141",
    "October 1947",
    "February 1948",
    "October 1948",
    "4 November 1948",
    "15 November 1948",
    "17 October 1949",
    "14–26 November 1949",
    "26 November 1949",
    "26 January 1950",
    "395 Articles",
    "8 Schedules",
    "Article 394",
    "Articles 5–9",
    "60",
    "324",
    "366",
    "367",
    "379",
    "393",
    "395",
    "Abolition of Privy Council Jurisdiction Act 1949",
    "2 years 11 months 18 days",
    "11 sessions",
    "114",
    "Rs 64",
    "sixty countries",
    "22 July 1947",
    "May 1949",
    "provisional Parliament",
    "Purna Swaraj",
    "elephant",
    "Prem Behari Narain Raizada",
    "Nandalal Bose",
    "Beohar Rammanohar Sinha",
    "58th Amendment",
    "Samvidhan Divas",
    "7,653",
    "2,473",
    "Constituent Assembly Debates",
    "Congress Experts Committee",
    "8 July 1946",
    "Krishna Kripalani",
    "Hansa Mehta",
    "Dakshayani Velayudhan",
    "Begum Aizaz Rasul",
    "Durgabai Deshmukh",
    "Rajkumari Amrit Kaur",
    "Naziruddin Ahmed",
    "Government of India Act 1935",
]
