"""Polity 02 stages 15-16 and the subordinate enrichment band."""

STAGES_H = [
    {
        "n": 15,
        "kind": "core",
        "title": "BORROWED PROVISIONS AS ADAPTATION, NOT COPYING — SOURCE → FEATURE → INDIAN TRANSFORMATION",
        "pills": [
            {"t": "Comparative study ≠ copying", "c": "cyan"},
            {"t": "Select · modify · integrate", "c": "teal"},
            {"t": "1935 Act = administrative source", "c": "amber"},
            {"t": "Not the democratic source", "c": "red"},
            {"t": "Continuity + rupture", "c": "magenta"},
            {"t": "No one-feature-one-country lists", "c": "yellow"},
        ],
        "blocks": [
            {"type": "adapt", "h1": "SOURCE FAMILY", "h2": "OFTEN-ASSOCIATED FEATURE", "h3": "INDIAN ADAPTATION — WHAT ACTUALLY CHANGED",
             "rows": [
                 {"src": "UNITED KINGDOM", "c": "cyan",
                  "dev": "Parliamentary government, cabinet responsibility and rule-of-law traditions.",
                  "ind": "Placed under a **written and supreme Constitution** with **judicially enforceable rights** — the opposite of an unwritten, parliamentary-sovereign order."},
                 {"src": "UNITED STATES", "c": "teal",
                  "dev": "Fundamental rights and judicial review / federal devices.",
                  "ind": "A **parliamentary rather than presidential executive**, and rights written with **detailed limits and exceptions** rather than open-textured guarantees."},
                 {"src": "IRELAND", "c": "green",
                  "dev": "Directive Principles of State Policy.",
                  "ind": "**Non-justiciable goals integrated with enforceable rights**, so that social aims and legal remedies sit in one instrument."},
                 {"src": "CANADA", "c": "magenta",
                  "dev": "A federation with a strong centre.",
                  "ind": "**Distinct Union and State lists** operating in the **Indian emergency and integration context** created by Partition and princely accession."},
                 {"src": "GOVERNMENT OF INDIA ACT 1935", "c": "amber",
                  "dev": "Federal-administrative machinery, offices and legislative lists.",
                  "ind": "**Democratised, rights-bound and placed under popular sovereignty** — the machinery survived, but its **source of authority was replaced**."},
             ]},
            {"type": "cols", "cols": [
                {"h": "THE TEST OF ADAPTATION", "c": "teal", "items": [
                    "**Borrowing is a technique, not a verdict.** The correct test is whether an institution was **selected, modified and integrated** to meet Indian conditions.",
                    "Adaptation must be demonstrated through **changed function**, not asserted.",
                    "Three secure examples of synthesis: **parliamentary government under a written supreme Constitution**; **enforceable rights alongside Directive Principles**; **a federation with a strong Union**.",
                    "The framers studied constitutional experience from **about sixty countries** — breadth of study is itself evidence of selection rather than transplant.",
                ]},
                {"h": "CONTINUITY AND RUPTURE — THE SHARPEST FRAME", "c": "magenta", "items": [
                    "The Constitution combined **continuity of institutions with rupture in legitimacy**.",
                    "**Continuity:** colonial offices, lists and administrative machinery were retained where useful — the 1935 Act supplied an inheritance the new state could actually run.",
                    "**Rupture:** authority was **relocated to the people** and to **universal adult citizenship**; the same machinery now answered to a different sovereign.",
                    "This is why 'the Constitution simply reproduced the 1935 Act' is wrong: it **transformed source, rights, accountability and citizenship**.",
                ]},
                {"h": "BORROWING TRAPS", "c": "red", "items": [
                    "**Wrong:** a borrowed device is necessarily unsuitable.  **Correct:** suitability depends on **adaptation and integration**.",
                    "**Wrong:** the 1935 Act was the democratic source of the Constitution.  **Correct:** it was an **administrative source only**.",
                    "**[LIMIT] Avoid unverified one-feature-one-country lists.** Many ideas have **multiple lineages**; use only securely established associations and **explain the adaptation**.",
                    "In Mains, present this as a **three-column source–feature–adaptation table**, never as a memorised list.",
                ]},
            ]},
            {"type": "band", "label": "SEQUENCE OF THE COMPARATIVE WORK →", "c": "amber", "outline": True,
             "text": "**Before 1947** the 1935 Act provided an administrative inheritance  →  **1946–48** B.N. Rau and the committees studied comparative models  →  **1948–49** the Assembly **selected, modified and integrated** the devices during the readings. Comparative learning was therefore **filtered through Indian problems** at a definite stage of the process, not imported wholesale at the start."},
            {"type": "answer", "label": "ANSWER-GRABBING LINE — BORROWING AS ADAPTATION:",
             "text": "The charge of borrowing mistakes a **method for a verdict**: the framers selected devices from about sixty constitutional systems and from the 1935 Act's machinery, but **changed their function** — parliamentary government was placed under a supreme written text, rights were made enforceable, and colonial administration was **re-founded on popular sovereignty**."},
        ],
    },
    {
        "n": 16,
        "kind": "core",
        "title": "SYNTHESIS — THE ANSWER SPINE, PYQ ROUTES AND THE GRADED VERDICT",
        "pills": [
            {"t": "Demand → scheme → sovereignty → text", "c": "cyan"},
            {"t": "Claim · evidence · significance · limit", "c": "teal"},
            {"t": "4 routed Prelims demands", "c": "amber"},
            {"t": "No direct Mains PYQ found locally", "c": "red"},
            {"t": "Relevance is institutional design", "c": "magenta"},
            {"t": "End with a graded verdict", "c": "green"},
        ],
        "blocks": [
            {"type": "chain", "per_row": 3, "items": [
                {"t": "1934–1946 — THE DEMAND", "s": "Roy's idea, Congress demand, adult-franchise standard, British concessions in stages", "c": "amber"},
                {"t": "1946 — THE SCHEME", "s": "Cabinet Mission Plan supplies allocation, electorate and voting method: 292 + 4 + 93 = 389", "c": "cyan"},
                {"t": "1946 — THE BODY", "s": "Indirect election plus nomination; first sitting 9 December; Objectives Resolution fixes the values", "c": "teal"},
                {"t": "1947 — SOVEREIGNTY", "s": "Independence Act removes external subordination; Partition re-fixes strength at 299", "c": "yellow"},
                {"t": "1947–1949 — DELIBERATION", "s": "Committees, adviser draft, Drafting Committee, public comment, three readings, amendments", "c": "magenta"},
                {"t": "1949–1950 — THE TEXT", "s": "Adopted 26 Nov 1949, signed 24 Jan 1950, commenced 26 Jan 1950 under Article 394", "c": "green"},
            ]},
            {"type": "row", "gap": 40, "children": [
                {"w": 0.62, "block": {"type": "matrix", "c": "cyan", "title": "DEMAND → ANSWER SPINE → EVIDENCE MINIMUM",
                                      "widths": [0.24, 0.44, 0.32],
                                      "headers": ["QUESTION DEMAND", "ANSWER SPINE", "EVIDENCE MINIMUM"],
                                      "rows": [
                                          ["**How representative?**", "Method → composition → inclusion → defects → verdict", "**389/299**, indirect election, boycott, universal franchise"],
                                          ["**Who made it?**", "Rau → committees → Drafting Committee → Assembly", "**Named roles and dates**"],
                                          ["**Borrowed?**", "Source → adaptation → Indian problem → limitation", "**Three secure examples**"],
                                          ["**Why durable?**", "Values → committee bargaining → legal coherence → legitimacy limits", "Objectives Resolution, readings, criticism/reply"],
                                          ["**Current relevance**", "Design principles for plural bargaining and institutional restraint", "**No forced daily-news peg required**"],
                                      ]}},
                {"w": 0.38, "block": {"type": "cols", "cols": [
                    {"h": "MARK-BAND ARCHITECTURE", "c": "teal", "items": [
                        "**Prelims** — identify **dates, roles, selection method and metrics**; nothing else is being tested.",
                        "**10 marks** — one claim, **three evidence units**, one qualification.",
                        "**15 marks** — **process plus debate plus balanced verdict**.",
                        "**20 marks** — **origins, composition, mechanisms, criticism/reply and legacy**.",
                        "Every paragraph: **claim → named institutional evidence → significance → limitation/qualification**.",
                        "**Current relevance lies in method** — public reasons, committee scrutiny, opposition channels, federal negotiation, rights constraints and clear transition rules — **not** in claiming that a present controversy reproduces 1946–49.",
                    ]},
                ]}},
            ]},
            {"type": "matrix", "c": "amber", "title": "LOCALLY ROUTED PRELIMS PYQ DEMANDS — WITH HONEST PROVENANCE STATUS",
             "widths": [0.14, 0.34, 0.16, 0.36],
             "headers": ["PYQ", "DEMAND", "MODEL ANSWER", "PROVENANCE STATUS"],
             "rows": [
                 ["**2021 GS-I Q93**", "Exact constitutional status of India on 26 January 1950.", "**B — A Sovereign Democratic Republic**", "Exact Set-A paper held locally; **official key unavailable**. Text-supported: 'socialist' and 'secular' came only in **1976**."],
                 ["**2023 GS-I Q85**", "Constitution Day on 26 November, and the claim that the Drafting Committee was set up on 26 November 1949.", "**C — Statement I correct, Statement II incorrect**", "Exact paper held locally; **official key unavailable**. The Drafting Committee was appointed **29 August 1947**."],
                 ["**2024 GS-I Q61**", "Provisional President of the Constituent Assembly before Dr Rajendra Prasad.", "**D — Dr Sachchidananda Sinha**", "**Official Set-A question and official Set-A key held locally.** The one fully keyed item."],
                 ["**2026 GS-I Q55**", "Whether any Article supplies the short title, the repeals and the commencement date.", "**D — no correct statement**", "Exact Set-A paper held locally. The repository key is **provisional and says B**, which conflicts with **Articles 393–395**. The conflict is disclosed, not resolved."],
             ]},
            {"type": "cols", "gap": 40, "cols": [
                {"h": "HIGH-YIELD TRAP SWEEP — THE TEN THAT DECIDE MARKS", "c": "red", "items": [
                    "**1** Directly elected → **indirectly elected**, and partly **nominated**.",
                    "**2** 389 as a working strength → **299** after Partition; **211** was one day's attendance.",
                    "**3** 284 as the post-Partition strength → **284 signed**; **299** was the strength.",
                    "**4** August Offer created the Assembly → it accepted a **principle**; the **Cabinet Mission** supplied the scheme.",
                    "**5** Rajendra Prasad temporary President → **Sachchidananda Sinha** was temporary.",
                    "**6** B.N. Rau chaired the Drafting Committee → he was **Constitutional Adviser**.",
                    "**7** Patel chaired the Fundamental Rights Sub-Committee → **J.B. Kripalani** did.",
                    "**8** Drafting Committee appointed 26 November 1949 → **29 August 1947**.",
                    "**9** The whole Constitution commenced on adoption → only **specified provisions**; the rest on **26 January 1950**.",
                    "**10** 'Socialist' and 'secular' in the 1949 Preamble → inserted by the **42nd Amendment, 1976**.",
                ]},
                {"h": "PROVENANCE DISCIPLINE — WHAT MAY AND MAY NOT BE CLAIMED", "c": "yellow", "items": [
                    "**[LIMIT] No direct Mains PYQ on the making process was found in the locally audited GS-I/GS-II corpus.** None is invented, and **cross-owned applications must not be relabelled as direct PYQs**.",
                    "**Wrong:** a practice Mains question is a PYQ.  **Correct:** label original practice **honestly**.",
                    "**Wrong:** current relevance requires a recent headline.  **Correct:** **static institutional relevance can be genuine and sufficient**.",
                    "**Wrong:** quote a critic for effect.  **Correct:** **do not reproduce an exact quotation unless its wording has been independently verified**; a source-owned criticism may be **paraphrased without quotation marks**.",
                    "Where an official key is unavailable or provisional, **say so** — a text-supported answer is not an official-key claim.",
                ]},
            ]},
            {"type": "answer", "label": "ANSWER-GRABBING LINE — FINAL VERDICT:",
             "text": "The Constituent Assembly was **neither perfectly representative nor merely colonial**: it earned **qualified founding legitimacy** by converting a constrained origin into an **inclusive, deliberative and universally democratic constitutional order**."},
            {"type": "band", "label": "END OF CORE →", "c": "green", "outline": True,
             "text": "The seventeen-stage core is now complete: **demand → Cabinet Mission scheme → indirect election → composition → first sitting and officers → Objectives Resolution → sovereignty 1947 → committees → Rau versus the Drafting Committee → drafts and readings → adoption, signing and commencement → dashboard → criticism and reply → adaptation → synthesis**. Everything below this line is **subordinate enrichment**: it adds source depth and refinement but is **unnecessary for a competent core answer**."},
        ],
    },
    {
        "n": 17,
        "kind": "extra",
        "title": "SUBORDINATE ENRICHMENT — OPTIONAL ADVANCED DEPTH, ONLY AFTER THE CORE IS SECURE",
        "pills": [
            {"t": "Congress Experts Committee 8 Jul 1946", "c": "grey"},
            {"t": "Plural voices, verified only", "c": "grey"},
            {"t": "Labels are not evidence", "c": "grey"},
            {"t": "Paraphrase, never quote unverified", "c": "grey"},
            {"t": "Keep denominators distinct", "c": "grey"},
        ],
        "blocks": [
            {"type": "row", "gap": 40, "children": [
                {"w": 0.5, "block": {"type": "cols", "cols": [
                    {"h": "PRE-ASSEMBLY PREPARATION — CONGRESS EXPERTS COMMITTEE", "c": "grey", "items": [
                        "Congress appointed an **Experts Committee on 8 July 1946 under Jawaharlal Nehru** to prepare constitutional material **before the Assembly met**.",
                        "Members included **Asaf Ali, K.M. Munshi, N. Gopalaswami Ayyangar, K.T. Shah, D.R. Gadgil, Humayun Kabir and K. Santhanam**; **Krishna Kripalani** served as convener.",
                        "It shows that formal Assembly committees **did not begin from a blank slate**: nationalist constitutional preparation preceded the first sitting.",
                        "**[LIMIT]** Use as enrichment only. It must **not displace the Cabinet Mission composition or the Assembly committee map** in a core answer.",
                    ]},
                ]}},
                {"w": 0.5, "block": {"type": "cols", "cols": [
                    {"h": "PLURAL VOICES — VERIFIED PARTICIPATION, NOT DECORATION", "c": "grey", "items": [
                        "**Gandhi was not a member.** Political and moral influence is **not** institutional membership.",
                        "**Hansa Mehta** — equality and women's-status interventions.  **Dakshayani Velayudhan** — Dalit woman member who opposed untouchability and pressed social transformation.",
                        "**Begum Aizaz Rasul** — Muslim woman member who **opposed separate electorates**.  **Durgabai Deshmukh** and **Rajkumari Amrit Kaur** — social reform, language, welfare and rights.",
                        "**[LIMIT]** Social presence was **real but not equal or proportionate**; do not convert a list of communities into proof of perfect representation, and **do not invent quotations**.",
                    ]},
                ]}},
            ]},
            {"type": "matrix", "c": "grey", "title": "ADVANCED ITEMS AND THE HANDLING RULE FOR EACH",
             "widths": [0.26, 0.38, 0.36],
             "headers": ["ITEM", "SOURCE-OWNED CONTENT", "HANDLING RULE"],
             "rows": [
                 ["**Chair memory map**", "Nehru — Union Powers, Union Constitution, States. Patel — Provincial Constitution and the parent Advisory Committee. Rajendra Prasad — Rules of Procedure and Steering.", "**Always name the committee** rather than relying on a count; chairmanship identifies **responsibility, not sole authorship**."],
                 ["**'Drifting Committee'**", "**Naziruddin Ahmed** used the expression in criticising delay; British political critics emphasised post-Partition religious imbalance.", "**Paraphrase without quotation marks.** Answer with institutional evidence — 1947 sovereignty, committee scrutiny, universal-franchise output — not counter-quotation."],
                 ["**'Father of the Constitution'**", "Textbooks commonly describe Ambedkar so, because of his Drafting Committee leadership and defence of the Draft.", "A **label, not analytical evidence**. It must not replace the distributed-authorship chain."],
                 ["**'Modern Manu'**", "The label appears in some textbook treatments.", "**Not analytical evidence**; do not deploy it as an argument."],
                 ["**Drafting intensity**", "About **sixty** constitutions studied; Drafting Committee **141 days**; Draft debated **114 days**; **7,653** amendments proposed and **2,473** moved or disposed.", "**Keep denominators distinct**: committee days, plenary debate days, proposed amendments and moved amendments are **not interchangeable**."],
                 ["**Living-Constitution refinement**", "Strict originalism is difficult because a multi-member Assembly had **plural intentions** and enacted wording often embodied **compromise**. **Maneka Gandhi** shows rights doctrine developing beyond the narrowest historical choice; **Kesavananda Bharati** shows an implied identity limit on amendment.", "**A living Constitution is not an untethered Constitution** — text, structure, precedent and reasoned justification constrain development."],
             ]},
            {"type": "band", "label": "ENRICHMENT CAUTION →", "c": "grey", "outline": True, "fill": True,
             "text": "This band is **deliberately visually subordinate**. It adds source depth and refinement but is **unnecessary for a competent core answer**. If time in the examination hall is short, everything above the END OF CORE line is sufficient; nothing in this band should be written at the cost of the dates, denominators, role distinctions and criticism–reply structure established in the numbered core."},
        ],
    },
]
