"""Polity 03 stages 15-17: independent constitutional bodies · emergency mode switch ·
third tier and constitutionalised cooperatives."""

STAGES_F = [
    {
        "n": 15, "kind": "core",
        "title": "INDEPENDENT CONSTITUTIONAL BODIES \u2014 INTEGRITY FUNCTIONS PLACED OUTSIDE ORDINARY EXECUTIVE CONTROL",
        "pills": [
            {"t": "ELECTION COMMISSION \u2014 ARTICLE 324", "c": "cyan"},
            {"t": "CAG \u2014 'GUARDIAN OF THE PUBLIC PURSE'", "c": "teal"},
            {"t": "UPSC AND STATE PSCs", "c": "amber"},
            {"t": "FINANCE COMMISSION", "c": "green"},
            {"t": "TENURE \u00b7 FIXED CONDITIONS \u00b7 CHARGED EXPENDITURE", "c": "yellow"},
            {"t": "NOT EVERY 'COMMISSION' IS CONSTITUTIONAL", "c": "red"},
        ],
        "blocks": [
            {"type": "constel",
             "l_fn": "CONSTITUTIONAL FUNCTION", "l_ind": "INDEPENDENCE DEVICE",
             "core": {"t": "INTEGRITY FUNCTIONS",
                      "s": "Created or protected **by the Constitution itself**, so their **existence and independence do not depend on the government of the day**"},
             "bodies": [
                 {"t": "ELECTION COMMISSION", "art": "ARTICLE 324", "c": "cyan",
                  "fn": "**Superintendence, direction and control** of elections \u2014 the institutional guarantee that universal adult franchise is exercised through **free and fair** elections.",
                  "ind": "**Constitutional status** plus protected **tenure and conditions of service**."},
                 {"t": "COMPTROLLER AND AUDITOR-GENERAL", "art": "GUARDIAN OF THE PUBLIC PURSE", "c": "teal",
                  "fn": "**Audits Union and State accounts**; the reports are what make **legislative financial accountability** possible after money is spent.",
                  "ind": "**Security of tenure**; salary and administrative expenses are **charged**, not voted."},
                 {"t": "UNION AND STATE PUBLIC SERVICE COMMISSIONS", "art": "MERIT RECRUITMENT", "c": "amber",
                  "fn": "Conduct examinations and advise on service matters, insulating **public employment from patronage**.",
                  "ind": "**Fixed conditions of service** and removal only in the **constitutionally specified manner**."},
                 {"t": "FINANCE COMMISSION", "art": "FISCAL FEDERALISM", "c": "green",
                  "fn": "Recommends the **distribution of taxes and the principles of grants** between the Union and the States \u2014 the fiscal hinge of cooperative federalism.",
                  "ind": "**Constitutionally mandated** periodic constitution and **independent recommendation**."},
             ]},
            {"type": "matrix", "c": "yellow",
             "title": "THE INDEPENDENCE DEVICES \u2014 AND WHAT EACH ONE DOES NOT DO",
             "headers": ["DEVICE", "HOW IT OPERATES", "WHAT IT DOES NOT DO"],
             "widths": [0.24, 0.38, 0.38],
             "rows": [
                 ["**Constitutional status**", "The body's existence rests on the **Constitution**, not on an ordinary statute or executive order", "It does **not** place the body outside constitutional accountability"],
                 ["**Security of tenure**", "Removal only in the **specified manner**, not at executive pleasure", "It does **not** immunise decisions from **judicial review**"],
                 ["**Fixed service conditions**", "Conditions cannot be varied to the holder's disadvantage after appointment", "It does **not** guarantee adequate **capacity or resources**"],
                 ["**Charged expenditure**", "Salaries and expenses are **charged** on the Consolidated Fund and not subject to the annual vote", "It does **not** exempt the body from **reporting and transparency**"],
             ]},
            {"type": "band", "label": "LIMIT \u2014 CLASSIFICATION AND ACCOUNTABILITY", "c": "red", "outline": True,
             "text": "**WRONG:** every body called a 'commission' is a constitutional body \u2014 **CORRECT:** many important bodies are **statutory or executive**, and the exam repeatedly tests that classification. **WRONG:** independence means freedom from accountability \u2014 **CORRECT:** functional independence must coexist with **transparency, reasoned decisions and review**. The detailed composition, appointment and powers of each body belong to their **owner topics**; here they matter as a **system-level feature** that disperses integrity functions."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 CONSTITUTIONAL BODIES:",
             "text": "Independent constitutional bodies **disperse integrity functions outside ordinary executive control**, but functional independence must coexist with **transparency, reasons and review**."},
        ],
    },
    {
        "n": 16, "kind": "core",
        "title": "EMERGENCY PROVISIONS \u2014 A CONSTITUTIONAL SWITCH BETWEEN NORMAL AND EXCEPTION MODE",
        "pills": [
            {"t": "FEDERAL \u2192 UNITARY, TEMPORARILY", "c": "yellow"},
            {"t": "WITHOUT ANY FORMAL AMENDMENT", "c": "amber"},
            {"t": "ARTICLES 352 \u00b7 356 \u00b7 355 \u00b7 365 \u00b7 360", "c": "cyan"},
            {"t": "44th AMENDMENT \u2014 'ARMED REBELLION'", "c": "teal"},
            {"t": "ARTICLES 20 AND 21 PROTECTED", "c": "green"},
            {"t": "EXCEPTION \u2260 SUSPENSION OF THE CONSTITUTION", "c": "red"},
        ],
        "blocks": [
            {"type": "switch",
             "normal": {"h": "NORMAL MODE \u2014 FEDERAL DISTRIBUTION", "c": "cyan", "items": [
                 "Union and State governments operate in their **own constitutional spheres** with distributed legislative and executive power.",
                 "Fundamental Rights operate with their **ordinary constitutional restrictions**.",
                 "The State executive is responsible to its **own elected legislature**.",
                 "Financial powers of the Union and the States follow the **normal constitutional scheme**.",
                 "Rights are enforced in the ordinary way through **Articles 32 and 226**.",
                 "Any centralising reach must be traced to an **express constitutional provision**, not to convenience.",
             ]},
             "exception": {"h": "EXCEPTION MODE \u2014 TEMPORARY CENTRALISATION", "c": "red", "items": [
                 "The system can **behave in a unitary way** \u2014 and it does so **without any formal amendment of the Constitution**.",
                 "The Union acquires **enlarged directive, legislative or financial reach** according to the provision invoked.",
                 "Rights operate under the **emergency regime of the relevant Articles** \u2014 but the Constitution itself is **not suspended**.",
                 "**Time limits, approval requirements and judicial review** are the constitutional conditions attached to the exception.",
                 "The switch is **a mode of operation, not a new constitution** \u2014 temporary and reversible by design.",
                 "**Article 356** is read **with Article 355**, so the exception operates **within a constitutional frame** rather than at large.",
             ]},
             "triggers": [
                 "ARTICLE 352 \u2014 war, external aggression or armed rebellion",
                 "ARTICLE 356 \u2014 failure of constitutional machinery in a State, read with Article 355",
                 "ARTICLE 365 \u2014 failure to comply with directions of the Union",
                 "ARTICLE 360 \u2014 financial emergency",
             ],
             "ret": "**RETURN PATH:** a proclamation is **temporary by design** \u2014 approval requirements, prescribed durations, revocation and **judicial review of the proclamation** are the routes back to normal mode. **Emergency provisions do not authorise permanent unitary rule or extra-constitutional government.**"},
            {"type": "matrix", "c": "amber",
             "title": "THE FOUR TRIGGER ARTICLES \u2014 GROUND, EFFECT, CONTROL",
             "headers": ["ARTICLE", "GROUND", "SYSTEM EFFECT", "CONTROL"],
             "widths": [0.13, 0.30, 0.31, 0.26],
             "rows": [
                 ["**Article 352**", "**War, external aggression or armed rebellion**", "National emergency \u2014 the widest centralising reach", "Approval and duration conditions; **Articles 20 and 21 protected**"],
                 ["**Article 356**", "**Failure of constitutional machinery** in a State, read with **Article 355**", "President's rule \u2014 State government functions taken over", "Proclamation is **reviewable**; time limits apply"],
                 ["**Article 365**", "**Non-compliance with directions** of the Union", "Supplies a ground on which failure of machinery may be held", "Cannot be used as a routine substitute for federal bargaining"],
                 ["**Article 360**", "**Financial emergency**", "Union directions on financial matters", "Constitutional conditions and review continue to apply"],
             ]},
            {"type": "cols", "gap": 40, "cols": [
                {"h": "44th AMENDMENT \u2014 WHAT IT TIGHTENED", "c": "green", "items": [
                    "Replaced **'internal disturbance'** with **'armed rebellion'** as a ground under Article 352 \u2014 a narrower, harder threshold.",
                    "Protected **Articles 20 and 21** from suspension under **Article 359**, so the right to life and protection in respect of conviction survive the emergency.",
                    "The direction of the reform was to make the **exception harder to invoke and less destructive of rights**.",
                ]},
                {"h": "WHY THIS IS A 'SALIENT FEATURE'", "c": "cyan", "items": [
                    "It shows that the Constitution **anticipated crisis** and located the response **inside** the constitutional order.",
                    "It is the clearest proof that **federal form and centralising operation coexist** in the same document.",
                    "It converts a political emergency into a **legally conditioned, reviewable and time-bound** state of affairs.",
                ]},
                {"h": "THE THREE EMERGENCY TRAPS", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "emergency suspends the Constitution."},
                    {"k": "CORRECT:", "kc": "green", "v": "it **alters the operation** of specified provisions under **constitutional conditions**."},
                    {"k": "WRONG:", "kc": "red", "v": "all Fundamental Rights can be suspended."},
                    {"k": "CORRECT:", "kc": "green", "v": "**Articles 20 and 21** are protected after the **44th Amendment**."},
                    {"k": "WRONG:", "kc": "red", "v": "a proclamation is beyond judicial scrutiny."},
                    {"k": "CORRECT:", "kc": "green", "v": "it is **reviewable**."},
                ]},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 EMERGENCY:",
             "text": "Emergency provisions permit **temporary constitutional centralisation for crisis management**, but they do **not authorise permanent unitary rule or extra-constitutional government**."},
        ],
    },
    {
        "n": 17, "kind": "core",
        "title": "THE THIRD TIER AND CONSTITUTIONALISED COOPERATIVES \u2014 DEMOCRACY BELOW THE STATE",
        "pills": [
            {"t": "73rd AMENDMENT, 1992 \u2014 PART IX + 11th SCHEDULE", "c": "cyan"},
            {"t": "74th AMENDMENT, 1992 \u2014 PART IX-A + 12th SCHEDULE", "c": "teal"},
            {"t": "A THIRD TIER FOUND IN NO OTHER CONSTITUTION", "c": "yellow"},
            {"t": "FUNCTIONS \u00b7 FUNDS \u00b7 FUNCTIONARIES", "c": "amber"},
            {"t": "97th AMENDMENT, 2011 \u2014 COOPERATIVES", "c": "magenta"},
            {"t": "NEVER SAY THE WHOLE 97th WAS STRUCK DOWN", "c": "red"},
        ],
        "blocks": [
            {"type": "chain", "per_row": 5, "items": [
                {"t": "ORIGINAL CONSTITUTION", "s": "Local self-government existed only as a directive on the organisation of village panchayats \u2014 an aspiration, not a guaranteed tier", "c": "dim"},
                {"t": "73rd AMENDMENT, 1992", "s": "Panchayats constitutionalised through Part IX and the Eleventh Schedule", "c": "cyan"},
                {"t": "74th AMENDMENT, 1992", "s": "Municipalities constitutionalised through Part IX-A and the Twelfth Schedule", "c": "teal"},
                {"t": "A DISTINCTIVE FEATURE", "s": "A constitutionally guaranteed third tier of this kind is not found in any other constitution", "c": "yellow"},
                {"t": "THE REAL TEST", "s": "Constitutional status guarantees existence and elections; effective devolution still requires functions, funds and functionaries", "c": "amber"},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 THIRD TIER:",
             "text": "The **73rd and 74th Amendments** deepened democracy by **constitutionalising a third tier**, yet real decentralisation still depends on **functions, funds and functionaries**."},
            {"type": "matrix", "c": "magenta",
             "title": "97th AMENDMENT, 2011 \u2014 WHAT SURVIVES AND WHAT DOES NOT",
             "headers": ["PROVISION", "WHAT IT DID", "STATUS AFTER THE JUDGMENT"],
             "widths": [0.26, 0.36, 0.38],
             "rows": [
                 ["**Article 19(1)(c)**", "Made the **right to form cooperative societies** an express fundamental freedom", "**Survives** \u2014 unaffected by the ruling"],
                 ["**Article 43-B**", "Added a **Directive Principle** on voluntary formation, autonomous functioning, democratic control and professional management", "**Survives** \u2014 unaffected by the ruling"],
                 ["**Part IX-B (Articles 243-ZH to 243-ZT)**", "Supplied a constitutional framework for the governance of cooperative societies", "In **Union of India v. Rajendra N. Shah (2021)** it was held invalid **for State cooperative societies** for want of **State ratification**"],
                 ["**Multi-State cooperatives**", "The framework as it applies to the **multi-State field**", "**Operative** \u2014 the Union's competence over multi-State societies is not disturbed"],
             ]},
            {"type": "band", "label": "PRECISION CONTROL \u2014 THE MOST COMMON ERROR ON THIS STAGE", "c": "red", "outline": True,
             "text": "**Never say the whole 97th Amendment was struck down.** The judgment turned on the **federal amendment procedure**: a change affecting the **State legislative field** required **ratification by the States**. **Article 19(1)(c), Article 43-B and the multi-State field survive.** This is also a clean illustration of the earlier amendment stage \u2014 the **ratification requirement is a real federal safeguard**, not a formality."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 COOPERATIVES:",
             "text": "The cooperative-society provisions **constitutionalise voluntary and democratic association**, while **federal competence limits Part IX-B's operation for State cooperatives**."},
        ],
    },
]
