"""Polity 03 stages 6-8: parliamentary accountability loop · sovereignty balance ·
separation through overlap and reciprocal checks."""

STAGES_C = [
    {
        "n": 6, "kind": "core",
        "title": "PARLIAMENTARY GOVERNMENT \u2014 THE UNBROKEN LOOP OF RESPONSIBLE EXECUTIVE POWER",
        "pills": [
            {"t": "AT THE UNION AND IN THE STATES", "c": "cyan"},
            {"t": "NOMINAL HEAD + REAL EXECUTIVE", "c": "teal"},
            {"t": "COLLECTIVE RESPONSIBILITY", "c": "yellow"},
            {"t": "FUSION \u2260 ABSENCE OF CHECKS", "c": "red"},
            {"t": "PARLIAMENT NOT SOVEREIGN LIKE WESTMINSTER", "c": "magenta"},
            {"t": "CONFIDENCE OF THE LOWER HOUSE", "c": "amber"},
        ],
        "blocks": [
            {"type": "loop",
             "nodes": [
                 {"t": "THE ELECTORATE", "c": "cyan",
                  "s": "Citizens choose representatives at periodic elections. This is where the **authorisation** of all executive power begins."},
                 {"t": "THE ELECTED LOWER HOUSE", "c": "teal",
                  "s": "Lok Sabha at the Union and the Legislative Assembly in a State. It **sustains or removes the ministry** and scrutinises it through questions, debates, committees and budget control."},
                 {"t": "THE ADMINISTRATION", "c": "amber",
                  "s": "Executive action carried out under **ministerial direction**, and answerable back through the same chain that authorised it."},
                 {"t": "THE COUNCIL OF MINISTERS", "c": "green",
                  "s": "The **real executive**, led by the **Prime Minister or Chief Minister**, working with a **nominal constitutional head** and **collectively responsible** to the elected lower House."},
             ],
             "centre": {"t": "WHERE THE LOOP GOES SLACK", "items": [
                 "**Confidence:** the government survives only while it retains **lower-House support**; a presidential executive by contrast has an **independently fixed tenure**.",
                 "**Collective responsibility:** the Council **stands or falls together** before the lower House.",
                 "**Fusion:** ministers normally sit in the legislature \u2014 but fusion is **not the absence of checks**.",
                 "**Risk:** a large majority and party discipline can weaken scrutiny; coalitions and the **anti-defection law** change the incentives.",
             ]}},
            {"type": "matrix", "c": "teal",
             "title": "FOUR MECHANISMS, FOUR RISKS \u2014 THE PAIRING IS THE ANSWER",
             "headers": ["FEATURE", "MECHANISM", "RISK / QUALIFICATION"],
             "widths": [0.22, 0.40, 0.38],
             "rows": [
                 ["**Dual executive**", "President or Governor as **formal head**; PM/CM-led Council as **real executive**", "Discretion exists only in **constitutionally bounded situations**"],
                 ["**Collective responsibility**", "The Council stands or falls together before the lower House", "A large majority and party discipline can **weaken scrutiny**"],
                 ["**Fusion**", "Ministers normally sit in the legislature", "Fusion is **not** the absence of checks"],
                 ["**Confidence**", "Government requires **lower-House support**", "Coalitions and the **anti-defection law** affect incentives"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "INDIA IS NOT WESTMINSTER", "c": "magenta", "items": [
                    "**LIMIT:** the Indian Parliament is **not sovereign like Westminster**. Written limits, federal competence, **Fundamental Rights, judicial review and basic structure** constrain it.",
                    "Core parliamentary features: **nominal and real executives, majority leadership, collective responsibility, ministerial membership of the legislature, PM/CM leadership and possible dissolution of the lower House**.",
                    "**Responsible government** links executive **survival** to legislative **confidence** \u2014 that is the whole distinction from a presidential separation.",
                ]},
                {"h": "TWO TRAPS AND ONE OFFICE CAUTION", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "fusion means there is no separation of powers."},
                    {"k": "CORRECT:", "kc": "green", "v": "parliamentary fusion coexists with **judicial review and institutional checks**."},
                    {"k": "WRONG:", "kc": "red", "v": "responsible government guarantees effective scrutiny."},
                    {"k": "CORRECT:", "kc": "green", "v": "party majorities and anti-defection incentives may **reduce deliberative accountability**."},
                    "**LIMIT:** do not call the President merely ceremonial in every context \u2014 the office has constitutional powers, generally exercised on **ministerial aid and advice** subject to specified text and conventions.",
                ]},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 RESPONSIBLE EXECUTIVE:",
             "text": "Parliamentary government makes the executive **continuously responsible to the elected lower House**, although **disciplined majorities can turn legislative confidence into executive dominance**."},
        ],
    },
    {
        "n": 7, "kind": "core",
        "title": "NEITHER PARLIAMENT NOR THE COURT IS SOVEREIGN \u2014 THE INDIAN SYNTHESIS",
        "pills": [
            {"t": "BRITISH IDEA: A POWERFUL PARLIAMENT", "c": "cyan"},
            {"t": "AMERICAN IDEA: JUDICIAL REVIEW", "c": "teal"},
            {"t": "BOTH PLACED INSIDE A WRITTEN, SUPREME CONSTITUTION", "c": "yellow"},
            {"t": "ARTICLE 368 = CONSTITUENT POWER", "c": "amber"},
            {"t": "ARTICLES 13 \u00b7 32 \u00b7 226 = ENFORCEABLE LIMITS", "c": "magenta"},
            {"t": "'JUDICIAL SUPREMACY' IS SHORTHAND, NOT THE ANSWER", "c": "red"},
        ],
        "blocks": [
            {"type": "balance",
             "left": {"h": "PARLIAMENT'S POWERS", "c": "cyan", "items": [
                 "Legislates **within constitutional competence** \u2014 a majority **cannot validate an unconstitutional law**.",
                 "Exercises **constituent power** to amend under **Article 368**.",
                 "Borrowed from the **British idea of a powerful Parliament**, but without parliamentary sovereignty.",
                 "Its powers are **conferred by the Constitution**, not inherent \u2014 which is why competence and procedure remain testable.",
             ]},
             "right": {"h": "JUDICIAL REVIEW", "c": "teal", "items": [
                 "**Articles 13, 32 and 226** make constitutional limits **enforceable**.",
                 "Courts may **invalidate unconstitutional action** \u2014 but review does **not** make courts an unlimited sovereign.",
                 "Borrowed from the **American idea of judicial review**, but exercised on text, structure, precedent and jurisdiction.",
                 "The **basic-structure limit** keeps the two powers in **equilibrium rather than in a hierarchy**.",
             ]},
             "fulcrum": {"t": "THE SUPREME CONSTITUTION",
                         "s": "Both powers are **conferred by** and **answerable to** the same written text"}},
            {"type": "matrix", "c": "yellow",
             "title": "FOUR DIMENSIONS THAT DECIDE THE CLOSE OPTION",
             "headers": ["DIMENSION", "THE INDIAN POSITION", "CLOSE-OPTION CONTROL"],
             "widths": [0.20, 0.42, 0.38],
             "rows": [
                 ["**Ordinary legislation**", "Parliament legislates within constitutional competence", "A majority **cannot validate an unconstitutional law**"],
                 ["**Constituent power**", "Parliament may amend under **Article 368**", "The **basic-structure limit** prevents destructive amendment"],
                 ["**Judicial review**", "Courts may invalidate unconstitutional action", "Review does **not** make courts an unlimited sovereign"],
                 ["**Article 21**", "The text says **'procedure established by law'**", "**Maneka Gandhi** requires **fair, just and reasonable** procedure; India did **not** copy the entire US model wholesale"],
             ]},
            {"type": "band", "label": "LIMIT \u2014 EXAM-SAFE FORMULATION", "c": "red", "outline": True,
             "text": "**'Judicial supremacy' is textbook shorthand.** The exam-safe formulation is **constitutional supremacy enforced partly through judicial review**. The synthesis exists precisely to prevent **two absolutes**: Westminster-style parliamentary sovereignty and court-centred government. **WRONG:** Parliament is sovereign because it can amend the Constitution \u2014 **CORRECT:** the amending power is **constitutionally conferred and basic-structure limited**."},
            {"type": "answer", "label": "ANALYTICAL TRANSITION \u2014 SOVEREIGNTY QUESTION:",
             "text": "India combines **Parliament's broad legislative and constituent powers** with **judicial review under a supreme Constitution**, making **neither Parliament nor the judiciary sovereign** in the British or American sense."},
        ],
    },
    {
        "n": 8, "kind": "core",
        "title": "SEPARATION OF FUNCTIONS, NOT OF ORGANS \u2014 OVERLAP LEGITIMISED BY RECIPROCAL CHECKS",
        "pills": [
            {"t": "NO STRICT MONTESQUIEU SEPARATION", "c": "red"},
            {"t": "FUNCTIONS DIFFERENTIATED, ORGANS NOT ISOLATED", "c": "yellow"},
            {"t": "ARTICLE 50 \u2014 A DPSP, NOT A RIGHT", "c": "amber"},
            {"t": "ARTICLES 121/211 \u00b7 122/212 \u00b7 123/213", "c": "cyan"},
            {"t": "RAM JAWAYA KAPUR (1955)", "c": "teal"},
            {"t": "DIRECT OWNER \u2014 2019 GS-II Q1", "c": "magenta"},
        ],
        "blocks": [
            {"type": "overlap",
             "zone_h": "THE FOUR CONSTITUTIONAL OVERLAP ZONES \u2014 LEGITIMATE ONLY WHILE RECIPROCAL CHECKS SURVIVE",
             "organs": [
                 {"h": "LEGISLATURE", "c": "cyan", "items": [
                     "Holds the executive accountable through **confidence, questions, debates, committees and the budget process.**",
                     "Exercises **constituent power under Article 368**.",
                     "**Articles 122 and 212** protect the **procedural autonomy** of legislatures \u2014 but substantive constitutional illegality remains reviewable within doctrine.",
                 ]},
                 {"h": "EXECUTIVE", "c": "amber", "items": [
                     "**Initiates most legislation** and may issue **ordinances under Articles 123 and 213** \u2014 a temporary, conditioned law-making power.",
                     "Survives only while it holds legislative confidence.",
                     "**Article 50** directs **separation of the judiciary from the executive** in the public services of the State.",
                 ]},
                 {"h": "JUDICIARY", "c": "teal", "items": [
                     "Reviews legality through **Articles 13, 32 and 226** and supplies **remedies**.",
                     "**Frames procedural rules** and exercises **contempt power**.",
                     "**Articles 121 and 211** limit legislative discussion of judges' conduct except in the removal process \u2014 this does **not** immunise judgments from criticism.",
                 ]},
             ],
             "zones": [
                 {"t": "EXECUTIVE LAW-MAKING", "c": "amber",
                  "s": "**Ordinances, Articles 123 and 213** \u2014 temporary and conditioned"},
                 {"t": "LEGISLATIVE CONSTITUENT POWER", "c": "cyan",
                  "s": "**Article 368** \u2014 broad, but basic-structure bounded"},
                 {"t": "JUDICIAL RULE-MAKING", "c": "teal",
                  "s": "Courts **frame rules** and punish **contempt**"},
                 {"t": "REVIEW AND REMEDIES", "c": "magenta",
                  "s": "**Articles 13, 32 and 226** \u2014 constitutional, not judicial government"},
             ]},
            {"type": "matrix", "c": "cyan",
             "title": "FIVE CONSTITUTIONAL MARKERS \u2014 AND THE QUALIFICATION EACH ONE CARRIES",
             "headers": ["CONSTITUTIONAL MARKER", "WHAT IT PROTECTS", "QUALIFICATION"],
             "widths": [0.22, 0.40, 0.38],
             "rows": [
                 ["**Article 50**", "Separation of the judiciary from the executive in the public services of the State", "A **DPSP**, not by itself a directly enforceable right"],
                 ["**Articles 121 and 211**", "Limits legislative discussion of judges' conduct except in the removal process", "Does **not** immunise judgments from criticism"],
                 ["**Articles 122 and 212**", "Procedural autonomy of legislatures", "Substantive constitutional illegality **remains reviewable** within doctrine"],
                 ["**Articles 123 and 213**", "Executive ordinance law-making", "**Temporary, conditioned** legislative power"],
                 ["**Articles 13, 32 and 226**", "Judicial review and remedies", "Review is **constitutional**, not judicial government"],
             ]},
            {"type": "band", "label": "CASE ANCHORS FOR THE 2019 GS-II DEMAND", "c": "yellow", "outline": True,
             "text": "**Ram Jawaya Kapur (1955)** recognised that the Constitution does **not contemplate a rigid separation**, though functions are sufficiently differentiated. **Kesavananda Bharati (1973)** and **Indira Nehru Gandhi v. Raj Narain (1975)** anchor separation and review **within basic-structure reasoning**. The working test: does the overlap **preserve each organ's constitutionally assigned core and its accountability**? **LIMIT:** judicial independence is **not** judicial supremacy, and legislative privilege is **not** a zone of total immunity."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 SEPARATION OF POWERS:",
             "text": "India **separates core functions without isolating organs**; constitutional overlaps are legitimate **only when reciprocal checks prevent concentration of power**."},
        ],
    },
]
