"""Polity 03 stages 18-20: asymmetry and plural accommodation · continuity, transformation
and constitutional morality · tensions, trade-offs and the graded verdict."""

STAGES_G = [
    {
        "n": 18, "kind": "core",
        "title": "ASYMMETRY AND PLURAL ACCOMMODATION \u2014 INTEGRATION THROUGH DIFFERENTIATION, NOT COERCED UNIFORMITY",
        "pills": [
            {"t": "FIFTH AND SIXTH SCHEDULE ARRANGEMENTS", "c": "cyan"},
            {"t": "SPECIAL PROVISIONS FOR STATES AND REGIONS", "c": "teal"},
            {"t": "OFFICIAL-LANGUAGE FRAMEWORK", "c": "amber"},
            {"t": "THERE IS NO NATIONAL LANGUAGE", "c": "red"},
            {"t": "ARTICLES 29 AND 30 \u2014 CULTURAL AND EDUCATIONAL RIGHTS", "c": "magenta"},
            {"t": "ASYMMETRY \u2260 INEQUALITY", "c": "yellow"},
        ],
        "blocks": [
            {"type": "panels", "mid": "AND",
             "mid2": "Differentiation is the integration strategy, not a departure from it",
             "panels": [
                 {"h": "TERRITORIAL AND TRIBAL DIFFERENTIATION", "c": "cyan",
                  "sub": "Different histories and administrative realities are given different constitutional treatment",
                  "items": [
                      "**Special provisions for particular States and regions** respond to distinctive historical, developmental and administrative circumstances.",
                      "**Fifth Schedule** arrangements govern the administration and control of **Scheduled Areas and Scheduled Tribes**.",
                      "**Sixth Schedule** arrangements provide **autonomous district and regional administration** in the specified tribal areas.",
                      "**Affirmative representation** and protective measures address **historical exclusion** rather than creating new privilege.",
                  ]},
                 {"h": "CULTURAL AND LINGUISTIC ACCOMMODATION", "c": "teal",
                  "sub": "Plurality is protected inside a single constitutional framework",
                  "items": [
                      "An **official-language framework** manages a multilingual polity \u2014 **the Constitution does not create a national language**.",
                      "**Articles 29 and 30** protect the **cultural and educational rights** of minorities, including the right to establish and administer educational institutions.",
                      "Accommodation is a **constitutional method of integration**: unity is pursued **through recognition**, not through erasure of difference.",
                      "**LIMIT:** the detailed schemes belong to the federalism, tribal-administration and minority-rights topics.",
                  ]},
             ]},
            {"type": "matrix", "c": "amber",
             "title": "FOUR ASYMMETRY DEVICES \u2014 WHAT EACH ACCOMMODATES AND THE CONTROL IT CARRIES",
             "headers": ["DEVICE", "WHAT IT ACCOMMODATES", "EXAM CONTROL"],
             "widths": [0.24, 0.38, 0.38],
             "rows": [
                 ["**Special State/region provisions**", "Distinct historical and developmental circumstances", "Differentiation is **constitutionally authorised**, not an exception to equality"],
                 ["**Fifth and Sixth Schedules**", "Scheduled Areas, Scheduled Tribes and autonomous tribal administration", "Two **different schemes** \u2014 do not merge them into one"],
                 ["**Official-language framework**", "A genuinely multilingual polity", "**No national language** is declared by the Constitution"],
                 ["**Cultural and educational rights**", "Minority language, script and culture", "Group protection **within** individual equality, not against it"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "ARTICLE 370 AND JAMMU & KASHMIR \u2014 THE EXACT, DATED POSITION", "c": "magenta", "items": [
                    "The **Supreme Court judgment of 11 December 2023** **upheld the 2019 constitutional changes** relating to **Article 370**.",
                    "The Court **directed restoration of statehood at the earliest**, **without fixing a deadline**.",
                    "**Official material continues to describe Jammu and Kashmir as a Union Territory with a legislature.**",
                    "**Write it as a dated position.** Undated present-tense claims about status are the single most common error on this sub-point.",
                ]},
                {"h": "THE THREE ASYMMETRY TRAPS", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "Hindi is the national language of India."},
                    {"k": "CORRECT:", "kc": "green", "v": "the Constitution provides an **official-language framework**; **no national language** is declared."},
                    {"k": "WRONG:", "kc": "red", "v": "asymmetry violates equality."},
                    {"k": "CORRECT:", "kc": "green", "v": "differentiated treatment of **differently situated regions and groups** is a recognised constitutional method."},
                    {"k": "WRONG:", "kc": "red", "v": "the Fifth and Sixth Schedules do the same job."},
                    {"k": "CORRECT:", "kc": "green", "v": "they are **distinct schemes** for different areas and forms of administration."},
                ]},
            ]},
            {"type": "band", "label": "WHY THIS IS A SYSTEM-LEVEL FEATURE", "c": "yellow", "outline": True,
             "text": "Asymmetry is the point at which **federalism, rights and identity meet**. A uniform template imposed on radically unlike regions would have produced **either secessionary pressure or authoritarian enforcement**. The Constitution instead treats **differentiated arrangements as instruments of integration** \u2014 which is why this feature must be argued as **accommodation**, never as concession or appeasement."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 ASYMMETRY:",
             "text": "Constitutional asymmetry uses **differentiated territorial, tribal, cultural and linguistic arrangements** to pursue **integration through accommodation rather than coerced uniformity**."},
        ],
    },
    {
        "n": 19, "kind": "core",
        "title": "CONTINUITY AND TRANSFORMATION \u2014 COLONIAL MACHINERY, REPUBLICAN LEGITIMACY, CONSTITUTIONAL MORALITY",
        "pills": [
            {"t": "MACHINERY RETAINED", "c": "amber"},
            {"t": "LEGITIMACY TRANSFORMED", "c": "green"},
            {"t": "GOVERNMENT OF INDIA ACT, 1935", "c": "cyan"},
            {"t": "AMBEDKAR VIA GEORGE GROTE", "c": "magenta"},
            {"t": "NOT PERSONAL JUDICIAL MORALITY", "c": "red"},
            {"t": "DIRECT OWNER \u2014 2021 GS-II Q1", "c": "yellow"},
        ],
        "blocks": [
            {"type": "replace", "arrow": "SAME MACHINERY, DIFFERENT SOURCE AND ENDS OF AUTHORITY",
             "before": {"h": "WHAT WAS CARRIED FORWARD \u2014 ADMINISTRATIVE CONTINUITY", "c": "amber", "items": [
                 "The **Government of India Act, 1935** supplied a large part of the **administrative and federal machinery**, which is one reason for the Constitution's length.",
                 "**Executive structures, service traditions and administrative-law patterns** continued into the republic.",
                 "Continuity was a **deliberate governing choice**: a new state could not simultaneously invent every institution and administer a partitioned subcontinent.",
                 "This is the factual basis of the criticism that the Constitution is a **carry-over of colonial law**.",
             ]},
             "after": {"h": "WHAT WAS TRANSFORMED \u2014 REPUBLICAN LEGITIMACY", "c": "green", "items": [
                 "**Popular sovereignty** replaced imperial authority as the **source** of all public power.",
                 "**Universal adult franchise** replaced a restricted, communal electorate.",
                 "**Justiciable Fundamental Rights** replaced statutory concessions revocable by the sovereign legislature.",
                 "**Responsible government** replaced administration accountable outward to an imperial authority.",
             ]},
             "note": "The correct formulation is that **institutional form persisted while constitutional legitimacy changed**. **WRONG:** the Constitution is merely a continuation of colonial law \u2014 **CORRECT:** it **retained machinery but replaced the source and ends of authority**. Continuity explains **capacity**; transformation explains **legitimacy**. An answer that states only one half is incomplete."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 CONTINUITY AND TRANSFORMATION:",
             "text": "The Constitution **retained administrative machinery from colonial rule** but **transformed its legitimacy** through **popular sovereignty, rights, universal franchise and responsible government**."},
            {"type": "matrix", "c": "magenta",
             "title": "CONSTITUTIONAL MORALITY \u2014 SOURCE, CONTENT, TEXTUAL ANCHOR, JUDICIAL USE",
             "headers": ["ELEMENT", "EXACT POSITION", "WHY IT CONTROLS THE ANSWER"],
             "widths": [0.22, 0.40, 0.38],
             "rows": [
                 ["**Origin**", "**Ambedkar** invoked the idea in the Constituent Assembly, drawing on **George Grote**", "Naming the source converts a vague phrase into a **traceable constitutional idea**"],
                 ["**Content**", "**Fidelity to constitutional forms, values and procedures**, and **self-restraint** by those who hold power", "It disciplines **how** power is used, not merely **whether** it is authorised"],
                 ["**Textual anchor**", "The **Preamble** and **Articles 14, 15, 19, 21 and 25**", "Anchoring prevents the concept from floating free of the text"],
                 ["**Judicial use**", "**Navtej Singh Johar (2018)**, **Indian Young Lawyers Association (2018)** and **Government of NCT of Delhi v. Union of India (2018)**", "The 2021 GS-II question asks for the concept **with judicial decisions**"],
             ]},
            {"type": "band", "label": "LIMIT \u2014 THE CRITICISM YOU MUST CONCEDE AND ANSWER", "c": "red", "outline": True,
             "text": "The standard objection is that constitutional morality can become **a label for judicial preference**. The disciplined reply: it must be argued **through constitutional text, structure and precedent**, and it applies to **legislators, executives and citizens**, not to judges alone. **WRONG:** constitutional morality means personal moral views of judges \u2014 **CORRECT:** it means **fidelity to constitutional values and restraint**, reasoned from the Constitution itself."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 CONSTITUTIONAL MORALITY:",
             "text": "Constitutional morality is **fidelity to constitutional forms, values and restraint**; it must discipline power **through text and structure** rather than become a **label for personal preference**."},
        ],
    },
    {
        "n": 20, "kind": "core",
        "title": "TENSIONS AND TRADE-OFFS \u2014 SIX FAULT LINES AND THE GRADED VERDICT THEY DEMAND",
        "pills": [
            {"t": "STRENGTH AND FAILURE MODE ARE THE SAME DESIGN", "c": "yellow"},
            {"t": "TENSION \u2260 DESIGN FAILURE", "c": "cyan"},
            {"t": "CONCEDE \u00b7 QUALIFY \u00b7 EVALUATE", "c": "teal"},
            {"t": "NO UNQUALIFIED PRAISE", "c": "red"},
            {"t": "NO WHOLESALE CONDEMNATION", "c": "red"},
            {"t": "THIS IS THE MAINS-SCORING STAGE", "c": "magenta"},
        ],
        "blocks": [
            {"type": "tension",
             "h_l": "DESIGN STRENGTH", "h_v": "THE FAULT LINE", "h_r": "FAILURE MODE / CRITICISM",
             "rows": [
                 {"c": "cyan", "v": "FEDERALISM vs CENTRALISATION",
                  "l": "Centralising devices give the Union **crisis capacity and national coordination**.",
                  "r": "The same devices can **erode State autonomy** when used routinely rather than exceptionally."},
                 {"c": "teal", "v": "LIBERTY vs SOCIAL REFORM",
                  "l": "Rights plus Directive Principles allow **reform-oriented regulation** of an unequal society.",
                  "r": "Reform can **overreach into protected freedoms** if restrictions are not justified."},
                 {"c": "amber", "v": "ACCOUNTABILITY vs EXECUTIVE DOMINANCE",
                  "l": "Responsible government makes the executive **continuously answerable** to the elected House.",
                  "r": "**Disciplined majorities** can convert confidence into **executive dominance** and thin scrutiny."},
                 {"c": "green", "v": "DETAIL vs COMPLEXITY",
                  "l": "Written detail **reduces uncertainty** and constitutionalises administration.",
                  "r": "Length and amendment traffic breed **complexity, litigation and technicality**."},
                 {"c": "magenta", "v": "REVIEW vs DEMOCRATIC LEGITIMACY",
                  "l": "Judicial review makes constitutional limits **enforceable** against transient majorities.",
                  "r": "Expansive review invites the charge of **displacing elected decision-making**."},
                 {"c": "yellow", "v": "UNIFORMITY vs ASYMMETRY",
                  "l": "Asymmetric arrangements **accommodate** deep regional and cultural difference.",
                  "r": "Differentiation can be attacked as **inconsistency** or become a bargaining instrument."},
             ]},
            {"type": "matrix", "c": "red",
             "title": "CRITICISM \u2192 COUNTER \u2192 RESIDUAL CONCERN \u2014 THE THREE-MOVE STRUCTURE THAT EARNS THE MARKS",
             "headers": ["CRITICISM", "CONSTITUTIONAL COUNTER", "RESIDUAL CONCERN"],
             "widths": [0.30, 0.36, 0.34],
             "rows": [
                 ["**Too long and too detailed**", "Detail **constitutionalises diversity and administration** and reduces uncertainty", "Complexity and frequent amendment raise **accessibility costs**"],
                 ["**Merely borrowed**", "Devices were **selected, adapted and rejected** to serve Indian conditions", "Adaptation must be demonstrated with **examples**, not asserted"],
                 ["**Not truly federal**", "Two governments, division of powers and a supreme written text remain **federal in form**", "**Routine** use of centralising devices weakens practice"],
                 ["**Colonial continuity**", "Legitimacy was transformed by **sovereignty, rights and franchise**", "Retained machinery can carry **authoritarian administrative habits**"],
                 ["**Judicial overreach**", "Review is the mechanism that makes **written limits enforceable**", "The **boundary with policy choice** is genuinely contested"],
                 ["**Rights under-delivered**", "Rights are **justiciable** and remedies are constitutionally guaranteed", "**Access, delay and capacity** limit real enjoyment"],
             ]},
            {"type": "band", "label": "THE GRADED VERDICT \u2014 HOW TO CLOSE A CRITICAL QUESTION", "c": "yellow", "outline": True,
             "text": "Neither **unqualified praise** nor **wholesale condemnation** scores. The examiner rewards: **state the design intention \u2192 concede the demonstrated failure mode \u2192 identify the constitutional mechanism that answers it \u2192 name the residual concern that survives.** A tension is evidence of a **plural society being governed constitutionally**; it becomes a failure only when one side of the trade-off **stops being contestable**."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 CRITICAL EVALUATION:",
             "text": "The Constitution's tensions are **not design failures by definition**; they become failures when **central capacity defeats federalism, majority rule defeats rights or institutional independence escapes accountability**."},
        ],
    },
]
