"""Polity 03 stage 21: synthesis - feature interaction web, answer spine, PYQ routes."""

STAGES_H = [
    {
        "n": 21, "kind": "core",
        "title": "SYNTHESIS \u2014 HOW THE FEATURES INTERACT, THE ANSWER SPINE AND THE PYQ ROUTES",
        "pills": [
            {"t": "FEATURES ARE A SYSTEM, NOT A LIST", "c": "yellow"},
            {"t": "INTERACTION IS THE MARK-CARRYING MOVE", "c": "cyan"},
            {"t": "2019 GS-II Q1 \u00b7 SEPARATION OF POWERS", "c": "magenta"},
            {"t": "2021 GS-II Q1 \u00b7 CONSTITUTIONAL MORALITY", "c": "magenta"},
            {"t": "DATE EVERY CHANGING POSITION", "c": "amber"},
            {"t": "CLOSE ON A GRADED VERDICT", "c": "teal"},
        ],
        "blocks": [
            {"type": "web", "h_pair": "FEATURE PAIR \u2014 THE INTERACTION",
             "h_out": "WHAT THE INTERACTION PRODUCES",
             "rows": [
                 {"a": "WRITTEN DETAIL", "b": "FEDERALISM", "c": "cyan",
                  "t": "Detail **constitutionalises the distribution of powers**, so Centre\u2013State disputes become **justiciable questions** instead of purely political ones."},
                 {"a": "FEDERAL FORM", "b": "EMERGENCY", "c": "red",
                  "t": "One document supplies **normal federal distribution** and a **temporary unitary mode** \u2014 which is why **federal form** and **centralising operation** must be answered as **two different questions**."},
                 {"a": "PARLIAMENTARY GOVERNMENT", "b": "JUDICIAL REVIEW", "c": "teal",
                  "t": "**Fusion** of executive and legislature is checked by **enforceable constitutional limits**, so **political responsibility and legal validity** operate together \u2014 neither Parliament nor the court is sovereign."},
                 {"a": "FUNDAMENTAL RIGHTS", "b": "DIRECTIVE PRINCIPLES", "c": "green",
                  "t": "**Harmony** \u2014 affirmed in **Minerva Mills (1980)** \u2014 converts liberty and social transformation into a **single reform-compatible programme** rather than rival claims."},
                 {"a": "UNIVERSAL FRANCHISE", "b": "SECULARISM", "c": "amber",
                  "t": "**Equal political membership** plus **principled state engagement** is how a deeply plural society sustains **equal citizenship** without a state religion or a wall of separation."},
                 {"a": "AMENDMENT POWER", "b": "BASIC STRUCTURE", "c": "yellow",
                  "t": "**Adaptability with entrenchment** \u2014 constitutional change remains possible while **constitutional destruction** does not; this is the hinge between rigidity and flexibility."},
                 {"a": "SINGLE CITIZENSHIP", "b": "ASYMMETRY", "c": "magenta",
                  "t": "Common legal membership coexists with **differentiated territorial, tribal and linguistic arrangements** \u2014 integration achieved **through accommodation**."},
             ]},
            {"type": "chain", "per_row": 5, "items": [
                {"t": "1 \u00b7 OPEN", "s": "Define a salient feature as a system-level characteristic produced by interaction of provisions, institutions, values and practice", "c": "cyan"},
                {"t": "2 \u00b7 CLASSIFY", "s": "Group by function: form and length \u00b7 power distribution \u00b7 rights and duties \u00b7 institutions \u00b7 adaptability", "c": "teal"},
                {"t": "3 \u00b7 EVIDENCE", "s": "Name Articles, Parts, Schedules, amendments and cases precisely \u2014 vague praise scores nothing", "c": "green"},
                {"t": "4 \u00b7 DISTINGUISH", "s": "Written \u2260 rigid \u00b7 lengthy \u2260 verbose \u00b7 borrowed \u2260 copied \u00b7 federal form \u2260 centralising operation", "c": "amber"},
                {"t": "5 \u00b7 INTERACT", "s": "Show at least one feature pair working together \u2014 this is the difference between a list and an argument", "c": "yellow"},
                {"t": "6 \u00b7 CONCEDE", "s": "State the criticism in its strongest form, not a weakened version", "c": "magenta"},
                {"t": "7 \u00b7 COUNTER", "s": "Give the constitutional mechanism that answers it", "c": "cyan"},
                {"t": "8 \u00b7 RESIDUAL", "s": "Name the concern that still survives the counter", "c": "teal"},
                {"t": "9 \u00b7 DATE", "s": "Attach dates to changing positions \u2014 amendments, judgments and status questions", "c": "amber"},
                {"t": "10 \u00b7 CLOSE", "s": "End on the graded verdict: adapted architecture whose success depends on morality and institutions", "c": "green"},
            ]},
            {"type": "matrix", "c": "magenta",
             "title": "VERIFIED PYQ ROUTES \u2014 WHICH STAGE OWNS THE QUESTION AND WHAT THE ANSWER MOVE IS",
             "headers": ["QUESTION", "DEMAND", "OWNER STAGE", "THE ANSWER MOVE"],
             "widths": [0.20, 0.28, 0.18, 0.34],
             "rows": [
                 ["**Mains 2019 GS-II Q1** \u00b7 10 marks \u00b7 150 words", "Strict separation of powers is not workable; checks and balances are essential", "**Stage 8**", "**Ram Jawaya Kapur (1955)** \u2192 four overlap zones \u2192 Articles 50, 121/211, 122/212, 123/213, 13/32/226 \u2192 reciprocal checks test"],
                 ["**Mains 2021 GS-II Q1** \u00b7 10 marks \u00b7 150 words", "Constitutional morality, illustrated with judicial decisions", "**Stage 19**", "**Ambedkar via George Grote** \u2192 Preamble and Articles 14, 15, 19, 21, 25 \u2192 **Navtej Singh Johar**, **Indian Young Lawyers Association**, **NCT of Delhi** (all 2018) \u2192 concede the preference objection"],
                 ["**Prelims 2020 Q7**", "Constitutional government \u2014 what it means", "**Stage 9**", "Reasoned answer: constitutional government means **limited government**. **Official key not held locally.**"],
                 ["**Prelims 2023 Q33**", "The chief purpose of having a Constitution", "**Stage 9**", "Reasoned answer: it **defines and limits the powers of government**. **Official key not held locally.**"],
                 ["**Prelims 2024 GS-I Q74**", "Match Parts of the Constitution with subject matter", "**Stages 16\u201317**", "**Officially verified Set-A answer: D** \u2014 **Part IX-A** Municipalities, **Part XVIII** Emergency Provisions, **Part XX** Amendment"],
                 ["**Prelims 2018 Q40 and Q45 \u00b7 2021 Q87, Q90 and Q94 \u00b7 2023 Q84**", "Feature-classification and provision-matching questions routed to this topic", "**Stages 2\u201316**", "Routed by stage; **no option text is reconstructed from memory** \u2014 verify against an official paper before quoting options"],
             ]},
            {"type": "cols", "gap": 38, "cols": [
                {"h": "PRELIMS DISCRIMINATORS \u2014 MEMORISE THE PAIRS", "c": "cyan", "items": [
                    "**Concurrent List \u2192 Australia** \u00b7 **Fundamental Duties \u2192 USSR** \u00b7 **DPSP \u2192 Ireland**.",
                    "**'Procedure established by law' \u2192 Japan** \u00b7 **amendment procedure and Rajya Sabha election \u2192 South Africa**.",
                    "**Suspension of Fundamental Rights during Emergency \u2192 Weimar**.",
                    "**'Socialist', 'secular' and 'integrity' \u2192 42nd Amendment, 1976**.",
                    "**Voting age 21 \u2192 18 \u2192 61st Amendment, 1988**, operating **from 1989**.",
                ]},
                {"h": "MAINS PARAGRAPH TEMPLATE \u2014 FOUR SENTENCES", "c": "teal", "items": [
                    "**Sentence 1** \u2014 name the feature and its **system-level function**.",
                    "**Sentence 2** \u2014 supply the **exact constitutional evidence**: Article, Part, Schedule, amendment or case.",
                    "**Sentence 3** \u2014 state the **qualification or trade-off** that a strong answer must concede.",
                    "**Sentence 4** \u2014 close with the **controlled answer line** for that stage.",
                ]},
                {"h": "NEVER WRITE THESE \u2014 AUTOMATIC MARK LOSS", "c": "red", "items": [
                    "**'Federation'** appears in the constitutional text \u2014 it does not; **Article 1** says **'Union of States'**.",
                    "**Every amendment** requires State ratification \u2014 only the specified federal matters do.",
                    "India follows a **strict separation of powers**.",
                    "**DPSP are irrelevant** because they are non-justiciable.",
                    "Indian secularism means **total State withdrawal** from religion.",
                    "**Hindi is the national language**.",
                    "The **whole 97th Amendment** was struck down.",
                    "A **single unqualified present-day total** of Articles, Parts or Schedules without a date.",
                ]},
            ]},
            {"type": "answer", "label": "FINAL ANSWER-GRABBING LINE \u2014 USE OR ADAPT IN ANY SALIENT-FEATURES QUESTION:",
             "text": "The Indian Constitution is a **carefully adapted architecture of authority, restraint, representation and transformation** whose success depends as much on **constitutional morality and institutions** as on text."},
            {"type": "band", "label": "SOURCE INTEGRITY", "c": "yellow", "outline": True,
             "text": "Every figure, Article, amendment number, case name and date on this poster is taken from the canonical **Polity 03 learner-v2 teaching session**. Where the session records a **dated** position \u2014 the Article count snapshot, the **106th Amendment** commencement, the **Article 370** judgment and the status of Jammu and Kashmir \u2014 the date is printed with the fact. Where an official answer key is **not held locally**, that is stated instead of asserting a key. **Nothing on this poster is reconstructed from memory.**"},
        ],
    },
]
