"""Polity 03 stages 9-11: constitutional supremacy keystone · integrated judiciary ·
rights, directive principles and duties."""

STAGES_D = [
    {
        "n": 9, "kind": "pivot",
        "title": "KEYSTONE \u2014 CONSTITUTIONAL SUPREMACY, RULE OF LAW AND LIMITED GOVERNMENT",
        "pills": [
            {"t": "THE FEATURE THAT MAKES EVERY OTHER FEATURE BINDING", "c": "yellow"},
            {"t": "COMPETENCE \u00b7 PROCEDURE \u00b7 RIGHTS", "c": "yellow"},
            {"t": "NOT BRITISH PARLIAMENTARY SOVEREIGNTY", "c": "red"},
            {"t": "RULE OF LAW \u2260 RULE BY ANY ENACTED LAW", "c": "red"},
            {"t": "LIMITED \u2260 WEAK GOVERNMENT", "c": "amber"},
            {"t": "ARTICLES 13 \u00b7 32 \u00b7 226 \u00b7 368", "c": "cyan"},
        ],
        "blocks": [
            {"type": "triangle",
             "apex": {"t": "THE CONSTITUTION \u2014 SUPERIOR SOURCE OF ALL PUBLIC AUTHORITY", "c": "yellow",
                      "s": "Every organ must be able to **trace and justify** its power under the Constitution. This is the keystone of the whole flow: it converts the other salient features from **descriptions** into **legally binding constraints**. Constitutional government both **creates** power and **restrains** it."},
             "base": [
                 {"t": "TEST 1 \u00b7 COMPETENCE", "c": "cyan",
                  "s": "Was the organ **constitutionally empowered** to act at all? Competence is **allocated, not assumed** \u2014 and a parliamentary majority is democratic evidence, **not a waiver of constitutional limits**."},
                 {"t": "TEST 2 \u00b7 FAIR PROCEDURE", "c": "teal",
                  "s": "**Article 21** says **'procedure established by law'**. After **Maneka Gandhi** the procedure must be **fair, just and reasonable** \u2014 but do not claim India simply copied the entire American substantive-due-process model."},
                 {"t": "TEST 3 \u00b7 ENFORCEABLE RIGHTS", "c": "magenta",
                  "s": "**Articles 13, 32 and 226** are the central **review and remedy anchors**; **Article 368** gives broad amendment power subject to the **basic-structure limit**."},
             ]},
            {"type": "matrix", "c": "yellow",
             "title": "FOUR IDEAS, FOUR TESTS, FOUR EXAM DISTINCTIONS",
             "headers": ["IDEA", "CORE TEST", "EXAM DISTINCTION"],
             "widths": [0.24, 0.42, 0.34],
             "rows": [
                 ["**Constitutional supremacy**", "Can every organ **trace and justify** its power under the Constitution?", "Different from **British parliamentary sovereignty**"],
                 ["**Rule of law**", "Is power **authorised, non-arbitrary and equally applied**?", "**Not** rule by any enacted law"],
                 ["**Limited government**", "Are **competence, procedure and rights** enforceable limits?", "**Elections alone do not create constitutionalism**"],
                 ["**Judicial review**", "Can unconstitutional action be **invalidated or corrected**?", "Review is **not policy administration**"],
             ]},
            {"type": "cols", "gap": 40, "cols": [
                {"h": "DICEY, ADAPTED TO INDIA", "c": "cyan", "items": [
                    "Dicey's classic elements: **supremacy of regular law over arbitrary power**, **equality before law**, and a legal spirit in which **courts protect rights**.",
                    "India's **written rights and remedies** alter the British setting but preserve the **anti-arbitrariness core**.",
                ]},
                {"h": "LAW AND LIBERTY ARE NOT OPPOSITES", "c": "teal", "items": [
                    "**General, prospective and reviewable law** can create **ordered liberty** by restraining arbitrary coercion.",
                    "Institutions need **sufficient capacity to govern**, yet must stay within jurisdiction, follow fair procedure and justify restrictions.",
                ]},
                {"h": "THE TWO KEYSTONE TRAPS", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "rule of law means any action backed by statute is valid."},
                    {"k": "CORRECT:", "kc": "green", "v": "the law **and its application** must satisfy constitutional competence and rights."},
                    {"k": "WRONG:", "kc": "red", "v": "limited government means weak government."},
                    {"k": "CORRECT:", "kc": "green", "v": "it means **legally bounded** government with adequate constitutional capacity."},
                ]},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 THE KEYSTONE LINE:",
             "text": "Constitutional supremacy converts **political power into legally bounded authority**: every organ must show **competence, fair procedure and respect for enforceable rights**."},
        ],
    },
    {
        "n": 10, "kind": "core",
        "title": "AN INTEGRATED AND INDEPENDENT JUDICIARY \u2014 ONE HIERARCHY, TWO BODIES OF LAW",
        "pills": [
            {"t": "INTEGRATED DESPITE FEDERALISM", "c": "yellow"},
            {"t": "NOT A DUAL COURT SYSTEM LIKE THE US", "c": "red"},
            {"t": "SUPREME COURT \u2192 HIGH COURTS \u2192 SUBORDINATE COURTS", "c": "cyan"},
            {"t": "CHARGED EXPENDITURE \u00b7 SECURITY OF TENURE", "c": "teal"},
            {"t": "INDEPENDENCE \u2260 JUDICIAL SUPREMACY", "c": "red"},
            {"t": "WRITS UNDER ARTICLES 32 AND 226", "c": "magenta"},
        ],
        "blocks": [
            {"type": "pyramid",
             "tiers": [
                 {"t": "SUPREME COURT", "c": "yellow",
                  "s": "**Apex court \u00b7 federal court \u00b7 final appellate court \u00b7 protector of Fundamental Rights \u00b7 guardian of constitutional boundaries.**"},
                 {"t": "HIGH COURTS", "c": "cyan",
                  "s": "**Constitutionally significant** within one integrated hierarchy \u2014 the trap is to think an integrated judiciary means States have no High Courts. They issue **writs within constitutional jurisdiction**."},
                 {"t": "SUBORDINATE COURTS", "c": "teal",
                  "s": "The **same** hierarchy administers **both Union and State law** \u2014 this is what promotes **national legal unity**, unlike a fully dual federal judiciary."},
             ],
             "rail": {"h": "REVIEW AND REMEDY CHAIN", "c": "magenta", "items": [
                 "**Article 13** \u2014 laws inconsistent with Fundamental Rights are void; the doorway to review.",
                 "**Article 32** \u2014 the Supreme Court's remedial jurisdiction for Fundamental Rights.",
                 "**Article 226** \u2014 High Court writ jurisdiction, wider in field.",
                 "Judicial review makes **written supremacy operational** by providing **reasoned remedies against ultra vires action**.",
                 "**LIMIT:** access, delay and compliance affect how effective those remedies actually are.",
             ]}},
            {"type": "matrix", "c": "cyan",
             "title": "FOUR DIMENSIONS OF JUDICIAL DESIGN \u2014 EACH WITH ITS OWN LIMIT",
             "headers": ["DIMENSION", "MEANING", "LIMIT"],
             "widths": [0.18, 0.44, 0.38],
             "rows": [
                 ["**Integrated**", "Supreme Court, High Courts and subordinate courts form **one hierarchy**", "Federal disputes still receive **constitutionally assigned jurisdiction**"],
                 ["**Independent**", "**Tenure, service conditions, charged expenditure** and institutional protections reduce external control", "**Appointment and accountability debates continue**"],
                 ["**Review**", "Courts test legislative and executive action against the Constitution", "Review does **not** confer unlimited governance power"],
                 ["**Remedies**", "Supreme Court and High Courts issue **writs** within constitutional jurisdiction", "**Access, delay and compliance** affect effectiveness"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "THE INDEPENDENCE SAFEGUARDS \u2014 NAME THEM", "c": "teal", "items": [
                    "**Security of tenure** and **protected service conditions**.",
                    "**Charged expenditure** \u2014 salaries and expenses are placed on the Consolidated Fund.",
                    "**Restrictions on legislative discussion** of judicial conduct.",
                    "**Contempt power** and **constitutional separation from the executive**.",
                ]},
                {"h": "TWO TRAPS AND ONE BOUNDARY", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "an integrated judiciary means States have no High Courts."},
                    {"k": "CORRECT:", "kc": "green", "v": "High Courts are **constitutionally significant within one integrated hierarchy**."},
                    {"k": "WRONG:", "kc": "red", "v": "an independent judiciary equals judicial supremacy."},
                    {"k": "CORRECT:", "kc": "green", "v": "the **Constitution**, not any organ, is supreme; independence is **institutional impartiality**, not absence of accountability."},
                    "**LIMIT:** appointments, jurisdiction, PIL, activism and tribunal doctrine belong to the judicial owner topics, not to this feature overview.",
                ]},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 THE JUDICIARY LINE:",
             "text": "An **integrated and independent judiciary** supplies **national legal unity** and makes **constitutional supremacy effective through review and remedies**."},
        ],
    },
    {
        "n": 11, "kind": "core",
        "title": "RIGHTS, DIRECTIVE PRINCIPLES AND DUTIES \u2014 THREE LEGAL STATUSES, ONE NORMATIVE ARCHITECTURE",
        "pills": [
            {"t": "PART III \u00b7 PART IV \u00b7 PART IV-A", "c": "cyan"},
            {"t": "JUSTICIABLE versus NON-JUSTICIABLE", "c": "yellow"},
            {"t": "ARTICLE 37 \u2014 FUNDAMENTAL IN GOVERNANCE", "c": "amber"},
            {"t": "42nd AMENDMENT + 86th AMENDMENT DUTIES", "c": "teal"},
            {"t": "MINERVA MILLS (1980) \u2014 HARMONY", "c": "green"},
            {"t": "HARMONY \u2260 AUTOMATIC HIERARCHY", "c": "magenta"},
        ],
        "blocks": [
            {"type": "triad",
             "cols": [
                 {"h": "FUNDAMENTAL RIGHTS", "c": "teal", "sc": "green", "status": "JUSTICIABLE",
                  "items": [
                      "**Part III.** They **restrain arbitrary public power** and enable **remedies**.",
                      "Subject to **constitutional restrictions** \u2014 they are **not absolute**.",
                      "**Not every right belongs only to citizens.**",
                      "Constitutional purpose: **political liberty, equality and remedies**.",
                  ]},
                 {"h": "DIRECTIVE PRINCIPLES", "c": "amber", "sc": "yellow",
                  "status": "NON-JUSTICIABLE \u00b7 FUNDAMENTAL IN GOVERNANCE",
                  "items": [
                      "**Part IV.** Not enforceable in court **merely as DPSP**.",
                      "**Article 37** declares them **fundamental in the governance of the country** and imposes a **duty on the State to apply them in law-making**.",
                      "Constitutional purpose: **social and economic democracy**, a welfare orientation.",
                  ]},
                 {"h": "FUNDAMENTAL DUTIES", "c": "magenta", "sc": "red", "status": "NON-JUSTICIABLE",
                  "items": [
                      "**Part IV-A.** Added by the **42nd Amendment**, with an additional duty later added by the **86th Amendment**.",
                      "Constitutional purpose: **civic responsibility** and **interpretive support**.",
                      "Their full content belongs to **Topic 09**.",
                  ]},
             ],
             "foot": {"label": "MINERVA MILLS (1980)",
                      "text": "treats **harmony between Fundamental Rights and Directive Principles** as central to constitutional balance. The architecture answers three questions at once: **what the State may not unjustifiably do**, **what social order it should pursue**, and **what civic commitments citizens should cultivate**."}},
            {"type": "matrix", "c": "cyan",
             "title": "LEGAL POSITION AND CONSTITUTIONAL PURPOSE \u2014 NEVER COLLAPSE THE TWO COLUMNS",
             "headers": ["COMPONENT", "LEGAL POSITION", "CONSTITUTIONAL PURPOSE"],
             "widths": [0.24, 0.38, 0.38],
             "rows": [
                 ["**Fundamental Rights**", "**Justiciable**, subject to constitutional restrictions", "Political liberty, equality and remedies"],
                 ["**Directive Principles**", "**Non-justiciable**; declared **fundamental in governance**", "Social and economic democracy; welfare orientation"],
                 ["**Fundamental Duties**", "**Non-justiciable** citizen duties", "Civic responsibility and interpretive support"],
                 ["**Balance**", "**Harmony, not automatic hierarchy**", "Dignity, freedom and social justice"],
             ]},
            {"type": "band", "label": "LIMIT AND TRAP SWEEP", "c": "red", "outline": True,
             "text": "**Do not** turn DPSP into directly enforceable rights, or Duties into free-standing penal offences \u2014 legislation may give concrete legal effect, but **the source and legal status must be identified**. **WRONG:** DPSP are legally irrelevant because non-justiciable \u2014 **CORRECT:** they are **constitutionally fundamental in governance** and guide law and interpretation. **WRONG:** rights always defeat social reform \u2014 **CORRECT:** constitutional adjudication seeks **rights-compatible reform and balance**."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 NORMATIVE ARCHITECTURE:",
             "text": "**Fundamental Rights restrain power**, **Directive Principles direct social transformation** and **Fundamental Duties express civic responsibility**; constitutional balance requires **harmony without erasing their different legal status**."},
        ],
    },
]
