"""Polity 03 stages 0-2: what makes a feature salient · constitution/constitutional law/
constitutionalism · written, lengthy and detailed."""

STAGES_A = [
    {
        "n": 0, "kind": "core",
        "title": "WHAT MAKES A FEATURE 'SALIENT' — A SYSTEM PROPERTY, NOT A MEMORISED LIST",
        "pills": [
            {"t": "SYSTEM-LEVEL CHARACTERISTIC", "c": "yellow"},
            {"t": "FEATURE \u2260 ARTICLE", "c": "red"},
            {"t": "PROVISION \u00b7 INSTITUTION \u00b7 VALUE \u00b7 PRACTICE", "c": "cyan"},
            {"t": "CONSTITUTES \u2192 DISTRIBUTES \u2192 LIMITS \u2192 DIRECTS", "c": "teal"},
            {"t": "NOT A CLOSED CONSTITUTIONAL SCHEDULE", "c": "amber"},
            {"t": "OVERLAPS BASIC STRUCTURE, NOT IDENTICAL", "c": "magenta"},
        ],
        "blocks": [
            {"type": "wheel", "hub_w": 0.30,
             "centre": {"t": "A SALIENT FEATURE", "c": "yellow",
                        "s": "answers **'what kind of constitutional order is this?'** \u2014 wider than one provision, narrower than the whole Constitution"},
             "nodes": [
                 {"t": "PROVISION", "c": "cyan",
                  "s": "A textual rule or cluster. Answers **'what does the text command or permit?'** Example: **Article 1 \u2014 Union of States**."},
                 {"t": "INSTITUTION", "c": "teal",
                  "s": "An office or body created or recognised by law. Answers **'who performs a function?'** Example: the **Election Commission of India**."},
                 {"t": "VALUE", "c": "amber",
                  "s": "A normative commitment that guides interpretation and government. Answers **'towards what constitutional end?'** \u2014 **liberty, equality, dignity, fraternity**."},
                 {"t": "PRACTICE", "c": "magenta",
                  "s": "Conventions, parties, administrative capacity and constitutional morality. This is why the text alone is never the whole feature."},
             ]},
            {"type": "matrix", "c": "cyan",
             "title": "THE FOUR BUILDING BLOCKS, EXACTLY AS THE OWNER DEFINES THEM",
             "headers": ["TERM", "MEANING", "WORKED EXAMPLE"],
             "widths": [0.17, 0.50, 0.33],
             "rows": [
                 ["Feature", "A system-level characteristic produced by **several rules** acting together", "**Federal with centralising features**"],
                 ["Provision", "A textual rule or cluster in the Constitution", "**Article 1: Union of States**"],
                 ["Institution", "An office or body created or recognised by law", "**Election Commission of India**"],
                 ["Value", "A normative commitment that guides interpretation and government", "**Liberty, equality, dignity, fraternity**"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "HOW TO EXPLAIN A FEATURE (ANALYSIS)", "c": "teal", "items": [
                    "State features as **relationships**, never as isolated labels.",
                    "**Written detail** supports legal certainty; **federal distribution** accommodates territory.",
                    "**Parliamentary responsibility** links executive power to representation; **rights and review** limit public power.",
                    "**Constitutional supremacy** means every organ receives its authority from the Constitution \u2014 so **limited government** follows.",
                ]},
                {"h": "THE TWO TRAPS SET HERE", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "a feature is the same as an Article."},
                    {"k": "CORRECT:", "kc": "green", "v": "a feature usually emerges from several provisions, institutions and practices."},
                    {"k": "WRONG:", "kc": "red", "v": "all important features are basic-structure elements."},
                    {"k": "CORRECT:", "kc": "green", "v": "the categories overlap but are not identical \u2014 basic structure is a judicial limit on the amending power (Topic 10 owns it)."},
                ]},
            ]},
            {"type": "band", "label": "LIMIT", "c": "amber", "outline": True,
             "text": "'Salient features' is a **teaching classification, not a closed constitutional schedule**. Lists vary by author and by constitutional development. **Rule of law supplies the operating ethic**: public power must have legal authority, like cases must be treated alike, and remedies must exist against arbitrariness."},
            {"type": "answer", "label": "OPENING DEFINITION \u2014 WRITE THIS FIRST:",
             "text": "A salient constitutional feature is a **system-level design characteristic produced by the interaction of provisions, institutions, values and practice**."},
        ],
    },
    {
        "n": 1, "kind": "core",
        "title": "CONSTITUTION \u2192 CONSTITUTIONAL LAW \u2192 CONSTITUTIONALISM: MOVING FROM DESIGN TO OPERATION",
        "pills": [
            {"t": "CREATES POWER", "c": "cyan"},
            {"t": "GOVERNS POWER", "c": "teal"},
            {"t": "LIMITS POWER EFFECTIVELY", "c": "yellow"},
            {"t": "ARTICLES 1 \u00b7 79 \u00b7 124 \u00b7 245-255 \u00b7 368", "c": "amber"},
            {"t": "ARTICLES 13 \u00b7 32 \u00b7 141 \u00b7 226", "c": "magenta"},
            {"t": "LABELS ARE NOT SELF-EXECUTING", "c": "red"},
        ],
        "blocks": [
            {"type": "ladder", "indent": 96, "steps": [
                {"t": "1 \u00b7 A CONSTITUTION \u2014 it CREATES and DISTRIBUTES public power", "c": "cyan",
                 "s": "The fundamental framework that creates institutions, distributes power, protects rights and prescribes change. Articles 1, 79, 124, 245-255 and 368 each illustrate a different one of those functions."},
                {"t": "2 \u00b7 CONSTITUTIONAL LAW \u2014 it GOVERNS that power", "c": "teal",
                 "s": "The wider body of rules governing public power: the constitutional text, binding judgments and valid implementing law. Anchors: Articles 13, 32, 141 and 226."},
                {"t": "3 \u00b7 CONSTITUTIONALISM \u2014 it ASKS WHETHER THE LIMITS ACTUALLY OPERATE", "c": "yellow",
                 "s": "Effective limitation and accountability of public power under law, delivered through rights, judicial review, responsible government, federalism and basic structure. Design describes the device; constitutionalism tests the restraint."},
            ]},
            {"type": "matrix", "c": "teal",
             "title": "INDIA IS BEST CLASSIFIED THROUGH PAIRED QUALIFICATIONS, NOT SINGLE LABELS",
             "headers": ["THE DESIGN SIDE", "THE OPERATION SIDE", "WHY THE PAIR EARNS THE MARK"],
             "widths": [0.26, 0.30, 0.44],
             "rows": [
                 ["**Enacted**", "**evolutionary in operation**", "A single dated enactment whose meaning is developed by interpretation and practice"],
                 ["**Codified**", "**supported by conventions**", "Written supremacy does not displace parliamentary convention"],
                 ["**Partly rigid**", "**partly flexible**", "Different subjects receive different levels of entrenchment"],
                 ["**Federal**", "**with centralising features**", "Distribution of power coexists with strong Union capacity"],
                 ["**Procedural**", "**transformative**", "It regulates process and simultaneously pursues social change"],
             ]},
            {"type": "band", "label": "ANSWER-WRITING EVIDENCE CHAIN", "c": "magenta", "outline": True,
             "text": "**Claim:** the Constitution both creates and limits public power. \u00b7 **Named evidence:** Articles 79 and 124 constitute Parliament and the Supreme Court; Articles 13, 32 and 226 make public action reviewable. \u00b7 **Analysis:** authority and restraint originate in the same supreme framework, which is what distinguishes Indian constitutional government from unlimited parliamentary sovereignty. \u00b7 **Qualification:** text alone does not guarantee constitutionalism \u2014 conventions, institutional capacity, access to remedies and compliance decide whether limits operate."},
            {"type": "answer", "label": "CONCEPT LINE \u2014 USE TO OPEN ANY 'CONSTITUTIONALISM' DEMAND:",
             "text": "A Constitution **creates public power**, constitutional law **governs it** and constitutionalism asks **whether effective limits, accountability and remedies actually operate**."},
        ],
    },
    {
        "n": 2, "kind": "core",
        "title": "WRITTEN, LENGTHY AND DETAILED \u2014 FOUR CAUSES, ONE ACCOMMODATION DEVICE, TWO COSTS",
        "pills": [
            {"t": "WRITTEN \u2260 RIGID", "c": "red"},
            {"t": "LENGTHY \u2260 MERE VERBOSITY", "c": "red"},
            {"t": "ORIGINAL 1949: PREAMBLE + 395 ARTICLES + 22 PARTS + 8 SCHEDULES", "c": "yellow"},
            {"t": "SOURCE SNAPSHOT: 25 PARTS \u00b7 12 SCHEDULES", "c": "amber"},
            {"t": "DETAIL = ACCOMMODATION TECHNOLOGY", "c": "teal"},
            {"t": "WRITTEN \u2260 SELF-EXECUTING", "c": "magenta"},
        ],
        "blocks": [
            {"type": "fan",
             "causes": [
                 {"t": "GEOGRAPHICAL VASTNESS AND DIVERSITY", "c": "amber",
                  "s": "One text had to speak to a **vast and diverse Union**."},
                 {"t": "THE BULKY GOVERNMENT OF INDIA ACT, 1935", "c": "amber",
                  "s": "An already-detailed administrative inheritance was carried forward."},
                 {"t": "ONE CONSTITUTION FOR UNION AND STATES", "c": "amber",
                  "s": "A **single framework** had to cover both levels of government."},
                 {"t": "INFLUENCE OF LEGAL SPECIALISTS", "c": "amber",
                  "s": "Legal luminaries in the Constituent Assembly favoured **express provision**."},
             ],
             "core": {"t": "A WRITTEN, COMPREHENSIVE AND UNUSUALLY DETAILED CONSTITUTION", "c": "yellow",
                      "s": "It combines **fundamental rules** with **substantial administrative design**, constitutionalising matters that other systems leave to ordinary legislation or convention \u2014 which raises legal visibility and permits judicial enforcement wherever the Constitution creates a standard."},
             "effects": [
                 {"t": "GAIN \u00b7 LEGAL CERTAINTY", "c": "green",
                  "s": "An authoritative text and a **reviewable allocation of power**."},
                 {"t": "GAIN \u00b7 ADVANCE ACCOMMODATION", "c": "green",
                  "s": "Institutions, minority protections, territorial arrangements and emergency rules are **specified in advance**, reducing reliance on unwritten consensus."},
                 {"t": "COST \u00b7 COMPLEXITY AND AMENDMENT PRESSURE", "c": "red",
                  "s": "Technical complexity, litigation over fine distinctions and recurring amendment."},
                 {"t": "COST \u00b7 THE IMPLEMENTATION ILLUSION", "c": "red",
                  "s": "A tendency to mistake **constitutional design** for **guaranteed implementation**."},
             ]},
            {"type": "matrix", "c": "cyan",
             "title": "EACH DIMENSION CARRIES ITS OWN QUALIFICATION \u2014 NEVER STATE ONE WITHOUT THE OTHER",
             "headers": ["DIMENSION", "CONSTITUTIONAL SIGNIFICANCE", "THE QUALIFICATION THAT MUST TRAVEL WITH IT"],
             "widths": [0.20, 0.40, 0.40],
             "rows": [
                 ["**Written**", "Authoritative text and a reviewable allocation of power", "The text still works **with conventions and judicial interpretation**"],
                 ["**Detailed**", "Administrative and institutional specificity", "Detail can create **complexity and frequent amendment**"],
                 ["**Original 1949 form**", "**Preamble, 395 Articles, 22 Parts, 8 Schedules**", "Use these as **historical counts** \u2014 they are safe"],
                 ["**Later form**", "**25 Parts and 12 Schedules** in the source snapshot", "Exact Article totals **vary by counting method**"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "TRAP \u00b7 WRITTEN DOES NOT MEAN WHAT CANDIDATES THINK", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "written means no conventions operate."},
                    {"k": "CORRECT:", "kc": "green", "v": "India has written supremacy **alongside** conventions, especially in parliamentary government."},
                    "Written is **not self-executing**: conventions, statutes, rules, parties, administrative capacity and constitutional morality decide whether text becomes practice.",
                ]},
                {"h": "TRAP \u00b7 THE ARTICLE-COUNT TRAP", "c": "magenta", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "the current Article count is a single uncontested number."},
                    {"k": "CORRECT:", "kc": "green", "v": "quote **Parts and Schedules**, then state the counting caveat."},
                    "'Lengthiest' is a **comparative textbook description**, not a licence to quote an unsourced current Article count \u2014 inserted, omitted and renumbered Articles make totals method-dependent.",
                ]},
            ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 THE LENGTH QUESTION:",
             "text": "India's written detail is an **accommodation device**: it constitutionalises diversity and administration, while remaining dependent on **conventions, interpretation and implementation**."},
        ],
    },
]
