"""Polity 03 stages 3-5: borrowed as adaptation · amendment spectrum · federal quadrant."""

STAGES_B = [
    {
        "n": 3, "kind": "core",
        "title": "BORROWED IN ANCESTRY, ORIGINAL IN DESIGN \u2014 WHAT WAS TAKEN, AND WHAT WAS DELIBERATELY REFUSED",
        "pills": [
            {"t": "BORROWED \u2260 COPIED", "c": "red"},
            {"t": "ADAPTATION IS PROVED BY REJECTION", "c": "yellow"},
            {"t": "STRUCTURAL \u2190 GoI ACT 1935", "c": "amber"},
            {"t": "PHILOSOPHICAL \u2190 US + IRELAND", "c": "teal"},
            {"t": "POLITICAL \u2190 BRITISH", "c": "cyan"},
            {"t": "NO ONE-TO-ONE ORIGIN CLAIMS", "c": "magenta"},
        ],
        "blocks": [
            {"type": "srcmap", "h_src": "SOURCE TRADITION",
             "h_adopt": "SELECTED AND ADAPTED INTO INDIA",
             "h_reject": "REJECTED OR ALTERED \u2014 THIS IS WHERE THE MARKS ARE",
             "rows": [
                 {"src": "UNITED KINGDOM", "c": "cyan",
                  "adopt": "**Cabinet government** and cabinet responsibility, **rule of law**, **single citizenship**, **bicameralism**, legislative procedure, prerogative writs and parliamentary privileges",
                  "reject": "**Parliamentary sovereignty** and **hereditary monarchy** \u2014 India has a **republican head** and **written limits**"},
                 {"src": "UNITED STATES", "c": "teal",
                  "adopt": "**Fundamental Rights**, **judicial review**, **independence of the judiciary**, the **post of Vice-President**, impeachment of the President and removal of judges",
                  "reject": "A **presidential executive**, **dual citizenship** and **rigid separation of powers**"},
                 {"src": "CANADA", "c": "amber",
                  "adopt": "**Federation with a strong Centre**, **residuary powers at the Union**, **Centre-appointed Governors**, advisory jurisdiction of the Supreme Court",
                  "reject": "The **indestructible-State model** \u2014 combined instead with parliamentary government and asymmetric provisions"},
                 {"src": "IRELAND", "c": "green",
                  "adopt": "**Directive Principles of State Policy**, **nomination of members to the Rajya Sabha**, the **method of electing the President**",
                  "reject": "One-to-one copying \u2014 DPSP were made **fundamental in governance but non-justiciable**"},
                 {"src": "AUSTRALIA", "c": "magenta",
                  "adopt": "The **Concurrent List**, **freedom of trade, commerce and intercourse**, the **joint sitting** of the two Houses",
                  "reject": "One-to-one copying \u2014 each device was placed **within India's stronger Union framework**"},
                 {"src": "GOVERNMENT OF INDIA ACT, 1935", "c": "yellow",
                  "adopt": "The **federal scheme**, the **office of Governor**, the **judiciary**, **Public Service Commissions**, **emergency provisions** and administrative detail \u2014 the **most profound and material single source**",
                  "reject": "**Colonial legitimacy, restricted franchise and communal representation** \u2014 popular sovereignty, universal franchise, enforceable rights and republican government transformed the purpose of what was retained"},
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "STRUCTURAL PART", "c": "amber", "items": [
                    "Strongly influenced by the **Government of India Act, 1935**.",
                    "It supplied **federal, gubernatorial, judicial, public-service, emergency and administrative** material.",
                ]},
                {"h": "PHILOSOPHICAL PART", "c": "teal", "items": [
                    "Drew notably on **American Fundamental Rights** and **Irish directive principles**.",
                    "Rights restrain power; directives orient the State towards social transformation.",
                ]},
                {"h": "POLITICAL PART", "c": "cyan", "items": [
                    "Executive-legislative relations drew on the **British model**.",
                    "Cabinet government and collective responsibility were taken **without** parliamentary sovereignty.",
                ]},
            ]},
            {"type": "matrix", "c": "magenta",
             "title": "THE REPOSITORY-VERIFIED SOURCE TABLE \u2014 QUOTE ONLY FROM HERE",
             "headers": ["SOURCE", "FEATURES BORROWED"],
             "widths": [0.24, 0.76],
             "rows": [
                 ["**GoI Act 1935**", "Federal scheme, office of Governor, judiciary, Public Service Commissions, emergency provisions, administrative details"],
                 ["**British**", "Parliamentary government, rule of law, legislative procedure, single citizenship, cabinet system, prerogative writs, parliamentary privileges, **bicameralism**"],
                 ["**United States**", "Fundamental Rights, independence of judiciary, judicial review, impeachment of the President, removal of Supreme Court and High Court judges, **post of Vice-President**"],
                 ["**Ireland**", "DPSP, **nomination of members to the Rajya Sabha**, method of election of the President"],
                 ["**Canada**", "Federation with a strong Centre, residuary powers in the Centre, Centre-appointed Governors, **advisory jurisdiction of the Supreme Court**"],
                 ["**Australia**", "**Concurrent List**, freedom of trade, commerce and intercourse, **joint sitting** of the two Houses"],
                 ["**Weimar (Germany)**", "**Suspension of Fundamental Rights during Emergency**"],
                 ["**USSR (Soviet)**", "**Fundamental Duties**, the ideal of justice \u2014 social, economic and political \u2014 in the Preamble"],
                 ["**France**", "**Republic**, and the ideals of liberty, equality and fraternity in the Preamble"],
                 ["**South Africa**", "**Procedure for amendment**, election of Rajya Sabha members"],
                 ["**Japan**", "**Procedure established by law**"],
             ]},
            {"type": "band", "label": "CLOSE-OPTION TRAP SWEEP", "c": "red", "outline": True,
             "text": "**Concurrent List \u2192 Australia**, not Canada (strong-Centre federalism is the Canadian link). **Fundamental Duties \u2192 USSR**, not the USA. **DPSP \u2192 Ireland**; **Fundamental Rights \u2192 USA**. **'Procedure established by law' \u2192 Japan**, not Britain. **Amendment procedure \u2192 South Africa**, not the USA. **LIMIT:** borrowed-source lists invite **false one-to-one claims** \u2014 a feature may have several intellectual and institutional influences, so use the verified table and avoid decorative trivia."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 THE 'BAG OF BORROWINGS' CHARGE:",
             "text": "The Constitution is **borrowed in ancestry but original in design** because the framers **selected, adapted and rejected** foreign devices to serve Indian conditions."},
        ],
    },
    {
        "n": 4, "kind": "core",
        "title": "THE AMENDMENT SPECTRUM \u2014 A GRADED BLEND OF FLEXIBILITY AND ENTRENCHMENT",
        "pills": [
            {"t": "WRITTEN \u2260 RIGID", "c": "red"},
            {"t": "NOT AS FLEXIBLE AS BRITAIN", "c": "amber"},
            {"t": "NOT AS RIGID AS THE UNITED STATES", "c": "amber"},
            {"t": "ARTICLE 368 = CONSTITUENT POWER", "c": "yellow"},
            {"t": "SOME CHANGES SIT OUTSIDE ARTICLE 368", "c": "teal"},
            {"t": "NO CONSTITUTIONAL REFERENDUM", "c": "magenta"},
        ],
        "blocks": [
            {"type": "spectrum",
             "left": "\u2190 FLEXIBLE \u00b7 ordinary-law style change",
             "right": "entrenched constitutional choice \u00b7 RIGID \u2192",
             "ceiling": "JUDICIAL CEILING OVER THE WHOLE SPECTRUM \u2014 the amending power cannot damage the BASIC STRUCTURE. Flexibility is constitutionally bounded; the doctrine itself belongs to Topic 10 and has no exhaustive closed list.",
             "stops": [
                 {"t": "SIMPLE MAJORITY, OUTSIDE ARTICLE 368", "c": "green",
                  "s": "Certain constitutional changes follow an **ordinary-law style procedure**. This gives adaptability **without treating every change as constituent amendment**."},
                 {"t": "SPECIAL MAJORITY UNDER ARTICLE 368", "c": "cyan",
                  "s": "A **majority of the total membership** of each House **plus two-thirds of the members present and voting**. This entrenches constitutional choice."},
                 {"t": "SPECIAL MAJORITY + RATIFICATION BY AT LEAST HALF THE STATES", "c": "amber",
                  "s": "Specified **federal** provisions additionally require **at least half of the States**. This protects the federal compact by adding State participation."},
                 {"t": "THE BASIC-STRUCTURE BOUNDARY", "c": "magenta",
                  "s": "Amendment is **broad, not destructive**. Constitutional change may not become **constitutional destruction**."},
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "WHY A GRADED SYSTEM AT ALL (ANALYSIS)", "c": "teal", "items": [
                    "Graduated rules **align procedure with constitutional stakes**: technical or territorial adjustments may be easier, while federal balance receives **State participation**.",
                    "**Article 368 supplies constituent power and procedure**, yet some changes described as constitutional amendments lie **outside** it and use a simple majority.",
                    "The basic-structure doctrine creates a real tension between **democratic updating** and **constitutional identity**.",
                ]},
                {"h": "NEVER SAY THIS ABOUT AMENDMENT", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "all amendments use Article 368."},
                    {"k": "CORRECT:", "kc": "green", "v": "some constitution-related changes use a simple majority outside it."},
                    {"k": "WRONG:", "kc": "red", "v": "basic structure prevents amendment."},
                    {"k": "CORRECT:", "kc": "green", "v": "it prevents **destructive alteration**, not constitutional change as such."},
                    "Never claim that every amendment needs **State ratification**, a **referendum** or a **joint sitting** \u2014 India has **no constitutional referendum requirement** for Article 368 amendments.",
                ]},
            ]},
            {"type": "band", "label": "POSITIONING LINE", "c": "amber", "outline": True,
             "text": "India is **neither as flexible as the classic British model nor as rigid as the United States model**. Different subjects receive different levels of entrenchment \u2014 that graded quality, not any single route, is the salient feature."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 RIGIDITY AND FLEXIBILITY:",
             "text": "India's graded amendment system **combines adaptability with entrenchment**, while the **basic-structure doctrine prevents constitutional change from becoming constitutional destruction**."},
        ],
    },
    {
        "n": 5, "kind": "core",
        "title": "FEDERAL IN FORM, CENTRALISING IN CAPACITY, COOPERATIVE AND ASYMMETRIC IN OPERATION",
        "pills": [
            {"t": "ARTICLE 1: 'UNION OF STATES'", "c": "yellow"},
            {"t": "'FEDERATION' NEVER USED", "c": "red"},
            {"t": "NOT AN AGREEMENT OF STATES", "c": "red"},
            {"t": "NO RIGHT TO SECEDE", "c": "red"},
            {"t": "RESIDUARY POWER AT THE UNION", "c": "amber"},
            {"t": "'QUASI-FEDERAL' IS A SCHOLAR'S LABEL, NOT TEXT", "c": "magenta"},
        ],
        "blocks": [
            {"type": "quadrant", "core": "INDIAN FEDERALISM",
             "cells": [
                 {"t": "FEDERAL STRUCTURE", "c": "cyan",
                  "s": "Two levels of government \u00b7 distribution of legislative power across the **Union, State and Concurrent Lists** \u00b7 **written supremacy** \u00b7 partial rigidity \u00b7 **judicial review** \u00b7 **bicameralism** \u00b7 courts as umpire of competence disputes."},
                 {"t": "CENTRALISING CAPACITY", "c": "red",
                  "s": "**Single citizenship** \u00b7 **integrated courts** \u00b7 **Union appointment of Governors** \u00b7 **All-India Services** \u00b7 **emergency provisions** \u00b7 a **strong Union list** \u00b7 **one Constitution** for the general Union-State framework \u00b7 **residuary power at the Union**."},
                 {"t": "COOPERATIVE AND COMPETITIVE", "c": "green",
                  "s": "Cooperative federalism appears where governments **jointly finance, deliberate or implement**; competitive federalism describes **comparison for investment and governance**."},
                 {"t": "ASYMMETRIC", "c": "magenta",
                  "s": "Differentiated arrangements accommodate **distinct histories and communities** \u2014 integration through **accommodation** rather than coerced uniformity."},
             ]},
            {"type": "matrix", "c": "cyan",
             "title": "EVERY FEDERAL INDICATOR CARRIES A CENTRALISING QUALIFIER \u2014 STATE BOTH, ALWAYS",
             "headers": ["FEDERAL DIMENSION", "ILLUSTRATION", "CENTRALISING / QUALIFYING FEATURE"],
             "widths": [0.24, 0.36, 0.40],
             "rows": [
                 ["**Dual governments**", "Union and States each have constitutional fields", "The Union has **residuary power** and stronger **crisis capacity**"],
                 ["**Distribution of powers**", "**Union, State and Concurrent Lists**", "**Union priority** in constitutionally specified conflicts"],
                 ["**Written supremacy**", "Competence is constitutionally allocated", "Parliament may **reorganise State boundaries** under the Constitution"],
                 ["**Judicial umpire**", "Courts decide competence disputes", "The judiciary is **integrated, not dual**"],
                 ["**Territorial chamber**", "The **Rajya Sabha** represents the States", "Representation is **unequal**, and party discipline matters"],
             ]},
            {"type": "cols", "gap": 44, "cols": [
                {"h": "ARTICLE 1 CONTROLS THE ANSWER", "c": "yellow", "items": [
                    "Article 1 calls India a **'Union of States'**; the Constitution **does not use the word 'Federation'**.",
                    "The Union was **not created by a compact among sovereign States**.",
                    "States have **no right to secede**.",
                    "**Scholarly labels describe operation, they are not constitutional text:** **'quasi-federal' (K.C. Wheare)** \u00b7 **'bargaining federalism' (Morris Jones)** \u00b7 **'co-operative federalism' (Granville Austin)** \u00b7 **'federation with a centralising tendency' (Ivor Jennings)**.",
                    "The design seeks **survival and integration without erasing diversity**.",
                ]},
                {"h": "THE TWO FEDERALISM TRAPS", "c": "red", "items": [
                    {"k": "WRONG:", "kc": "red", "v": "India is purely unitary because the Centre is strong."},
                    {"k": "CORRECT:", "kc": "green", "v": "it has a constitutionally distributed federal structure **with** centralising features."},
                    {"k": "WRONG:", "kc": "red", "v": "asymmetry violates federalism."},
                    {"k": "CORRECT:", "kc": "green", "v": "differentiated arrangements can be a **federal device for accommodation**."},
                    "**LIMIT:** 'quasi-federal' is a **scholar's description, not constitutional text** \u2014 weigh domains and time periods instead of declaring India simply unitary.",
                ]},
            ]},
            {"type": "band", "label": "LIVE OFFICIAL \u2014 CHECKED 21 AUGUST 2026", "c": "teal", "outline": True,
             "text": "Gazette notification **S.O. 1922(E)** brought the **Constitution (One Hundred and Sixth Amendment) Act, 2023** into force on **16 April 2026**. **LIMIT:** commencement is **not operational reservation** \u2014 **Article 334A** still links actual reservation to delimitation undertaken after publication of the relevant figures of the first census taken after commencement. No publication date, delimitation date, election year or seat projection is asserted here."},
            {"type": "answer", "label": "ANALYTICAL TRANSITION \u2014 THE FEDERALISM VERDICT:",
             "text": "Indian federalism **distributes power to accommodate diversity**, but retains **centralising, cooperative and asymmetric devices** so the Union can coordinate **without erasing the States**."},
        ],
    },
]
