"""Polity 03 stages 12-14: Indian secularism model · universal adult franchise and
representation · single citizenship and the integration devices."""

STAGES_E = [
    {
        "n": 12, "kind": "core",
        "title": "SECULAR REPUBLIC \u2014 PRINCIPLED STATE ENGAGEMENT BETWEEN TWO REJECTED EXTREMES",
        "pills": [
            {"t": "NO OFFICIAL RELIGION", "c": "cyan"},
            {"t": "NOT THEOCRACY \u00b7 NOT TOTAL WITHDRAWAL", "c": "red"},
            {"t": "'SOCIALIST' \u00b7 'SECULAR' \u00b7 'INTEGRITY' \u2014 42nd AMENDMENT, 1976", "c": "yellow"},
            {"t": "COMMITMENTS PRE-DATED THE WORDS", "c": "amber"},
            {"t": "ARTICLES 14 \u00b7 15 \u00b7 16 \u00b7 25\u201330 \u00b7 44", "c": "teal"},
            {"t": "POSITIVE SECULARISM", "c": "magenta"},
        ],
        "blocks": [
            {"type": "vs3", "labw": 0.17,
             "heads": [
                 {"t": "THEOCRATIC / STATE-RELIGION MODEL", "c": "red"},
                 {"t": "THE INDIAN MODEL \u2014 PRINCIPLED ENGAGEMENT", "c": "green"},
                 {"t": "ABSOLUTE WALL OF SEPARATION", "c": "amber"},
             ],
             "rows": [
                 {"l": "OFFICIAL RELIGION", "v": [
                     "A **State religion** is established and privileged.",
                     "**No official religion** \u2014 the State does not establish or privilege one faith.",
                     "No official religion, achieved by **complete State absence**.",
                 ]},
                 {"l": "STATE AND FAITH", "v": [
                     "Religious authority shapes public law.",
                     "**Principled engagement:** the State may regulate **secular activity associated with religious practice** and act for **equality and social reform**.",
                     "**Strict non-interference**; the State stays outside religion entirely.",
                 ]},
                 {"l": "EQUALITY", "v": [
                     "Formal inequality between believers and others.",
                     "**Articles 14, 15 and 16** \u2014 equality and non-discrimination on grounds including religion, and equal access to public employment.",
                     "Equality pursued with minimal State engagement.",
                 ]},
                 {"l": "FREEDOM OF RELIGION", "v": [
                     "Confined to the established faith.",
                     "**Articles 25\u201328** \u2014 freedom of conscience and religion, subject to **public order, morality, health** and other constitutional limits.",
                     "Strong individual liberty, no regulatory role.",
                 ]},
                 {"l": "GROUP RIGHTS", "v": [
                     "Minority claims subordinated.",
                     "**Articles 29 and 30** \u2014 cultural and educational rights of minorities. Communal representation was **abolished**, except temporary **seat reservation for SCs and STs**.",
                     "No group-specific constitutional guarantees.",
                 ]},
                 {"l": "REFORM MANDATE", "v": [
                     "Reform is a religious, not a civil, question.",
                     "**Article 44** \u2014 a **uniform civil code is a Directive Principle**, a constitutional aspiration, **not an enforced code today**.",
                     "Social reform is left outside the State's concern.",
                 ]},
             ]},
            {"type": "matrix", "c": "yellow",
             "title": "PREAMBULAR VOCABULARY \u2014 EXACT SOURCE, EXACT MEANING",
             "headers": ["TERM", "CONSTITUTIONAL LOCATION", "EXACT MEANING FOR THE EXAM"],
             "widths": [0.20, 0.34, 0.46],
             "rows": [
                 ["**'Secular'**", "Inserted into the Preamble by the **42nd Amendment, 1976**", "The **commitment pre-dated the word** \u2014 equality, freedom of religion and minority rights were already in the text"],
                 ["**'Socialist'**", "Inserted by the **42nd Amendment, 1976**", "Read with the welfare orientation of **Part IV**, not as a fixed economic doctrine"],
                 ["**'Integrity'**", "Inserted by the **42nd Amendment, 1976**", "Read with unity, fraternity and the territorial framework"],
                 ["**'Republic'**", "Preamble, with an **elected head of State**", "No hereditary office; **political sovereignty vests in the people**"],
             ]},
            {"type": "band", "label": "LIMIT \u2014 THE THREE SECULARISM TRAPS", "c": "red", "outline": True,
             "text": "**WRONG:** Indian secularism means total State withdrawal from religion \u2014 **CORRECT:** it permits **regulation of secular activity and reform-oriented intervention** consistent with rights. **WRONG:** the 42nd Amendment created Indian secularism \u2014 **CORRECT:** it **added the word** to a Preamble whose **substantive commitments already existed**. **WRONG:** a uniform civil code is already the enforced law \u2014 **CORRECT:** **Article 44 is a Directive Principle**. Do **not** convert this stage into the detailed doctrine of Articles 25\u201328, which belongs to the Fundamental Rights topics."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 SECULARISM:",
             "text": "Indian secularism protects **equal citizenship and freedom of conscience** through **principled state engagement**, not a theocratic order or an absolute wall of separation."},
        ],
    },
    {
        "n": 13, "kind": "core",
        "title": "UNIVERSAL ADULT FRANCHISE \u2014 EQUAL POLITICAL MEMBERSHIP FROM THE VERY COMMENCEMENT",
        "pills": [
            {"t": "FROM COMMENCEMENT \u2014 NOT PHASED IN", "c": "yellow"},
            {"t": "NO PROPERTY \u00b7 TAX \u00b7 EDUCATION \u00b7 GENDER TEST", "c": "cyan"},
            {"t": "61st AMENDMENT ACT, 1988 \u2014 21 \u2192 18", "c": "teal"},
            {"t": "OPERATIVE FOR ELECTIONS FROM 1989", "c": "amber"},
            {"t": "RAJYA SABHA \u2260 US SENATE", "c": "red"},
            {"t": "BICAMERAL ASYMMETRY IS DELIBERATE", "c": "magenta"},
        ],
        "blocks": [
            {"type": "timeline", "c": "cyan", "items": [
                {"d": "COLONIAL BASELINE", "t": "Representation rested on a restricted franchise and communal electorates \u2014 political membership was rationed by property, tax, education and community."},
                {"d": "26 JAN 1950", "t": "Universal adult franchise operates from the commencement of the Constitution \u2014 no property, tax, education or gender qualification."},
                {"d": "FROM COMMENCEMENT", "t": "Communal representation abolished, except temporary seat reservation for Scheduled Castes and Scheduled Tribes."},
                {"d": "61st AMENDMENT, 1988", "t": "The voting age is reduced from 21 years to 18 years by the Constitution (Sixty-first Amendment) Act, 1988."},
                {"d": "FROM 1989", "t": "The reduced voting age operates for elections held from 1989 \u2014 the amendment year and the operative year are different facts."},
            ]},
            {"type": "panels", "mid": "PLUS",
             "mid2": "Franchise creates the electorate; chamber design decides how that electorate is represented",
             "panels": [
                 {"h": "WHY UNIVERSAL FRANCHISE WAS A DECISIVE CHOICE", "c": "green",
                  "sub": "A poor, largely non-literate, newly independent country did not phase it in",
                  "items": [
                      "It **constitutionalised equal political membership** at the outset instead of treating the vote as a reward for property, literacy or tax payment.",
                      "It broke decisively with the **restricted colonial franchise**, which had made representation a concession rather than a right.",
                      "It made **political equality** the foundation on which social and economic transformation could be pursued through ordinary politics.",
                      "It is a **constitutional commitment**, not an administrative convenience \u2014 which is why the change of voting age itself required a **constitutional amendment**.",
                  ]},
                 {"h": "REPRESENTATION IS NOT ONLY ELECTORAL", "c": "cyan",
                  "sub": "Institutions translate equal votes into accountable government",
                  "items": [
                      "**Bicameralism** at the Union gives a **directly elected popular chamber** and a **federal chamber** representing the States.",
                      "The **Rajya Sabha is a federal chamber, but not an equal-State chamber like the US Senate** \u2014 a very frequent close-option trap.",
                      "The two Houses are **deliberately asymmetric** on **confidence** and on **money bills**; the popular chamber controls the government's survival and the purse.",
                      "**LIMIT:** the machinery of elections, delimitation and party regulation belongs to the elections topic, not to this feature.",
                  ]},
             ]},
            {"type": "matrix", "c": "teal",
             "title": "FOUR EXACT CONTROLS ON THIS STAGE",
             "headers": ["POINT", "EXACT POSITION", "WHY THE PRECISION MATTERS"],
             "widths": [0.20, 0.42, 0.38],
             "rows": [
                 ["**Start date**", "Universal adult franchise applies **from the commencement of the Constitution**", "It was **not** introduced gradually or by later statute"],
                 ["**Voting age**", "**21 \u2192 18** by the **61st Amendment Act, 1988**, operating for elections **from 1989**", "Two different years \u2014 amendment year and operative year"],
                 ["**Republic**", "An **elected head of State**; sovereignty vests in the people", "Distinguishes India from a constitutional monarchy"],
                 ["**Second chamber**", "Federal in character, **not equal-State representation**", "The US Senate analogy is the standard wrong option"],
             ]},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 FRANCHISE AND REPRESENTATION:",
             "text": "Universal adult franchise constitutionalised **equal political membership from the beginning**, while representative institutions translate that equality into **accountable government**."},
        ],
    },
    {
        "n": 14, "kind": "core",
        "title": "THE INTEGRATION BUS \u2014 SINGLE CITIZENSHIP AND THE DEVICES THAT HOLD A FEDERAL POLITY TOGETHER",
        "pills": [
            {"t": "SINGLE CITIZENSHIP", "c": "cyan"},
            {"t": "NOT US-STYLE DUAL CITIZENSHIP", "c": "red"},
            {"t": "ONE INTEGRATED JUDICIARY", "c": "teal"},
            {"t": "ALL-INDIA SERVICES \u2014 COMMON RECRUITMENT", "c": "amber"},
            {"t": "UNITY WITHIN FEDERALISM, NOT INSTEAD OF IT", "c": "yellow"},
            {"t": "INTEGRATION \u2260 UNIFORMITY", "c": "magenta"},
        ],
        "blocks": [
            {"type": "bus", "label": "INTEGRATION DEVICES",
             "l_fn": "INTEGRATIVE FUNCTION", "l_ten": "TENSION / LIMIT",
             "devices": [
                 {"t": "SINGLE CITIZENSHIP", "c": "cyan",
                  "fn": "Every Indian is a **citizen of India alone**, whatever the State of birth or residence \u2014 there is **no separate State citizenship**.",
                  "tension": "It does **not** abolish **domicile-based or residence-based provisions** made under the Constitution."},
                 {"t": "INTEGRATED JUDICIARY", "c": "teal",
                  "fn": "**One hierarchy** administers **both Union and State law**, producing **uniform interpretation** of national law.",
                  "tension": "Access, delay and compliance decide how far that unity is felt on the ground."},
                 {"t": "ALL-INDIA SERVICES", "c": "amber",
                  "fn": "**Common recruitment** for officers who serve **both the Union and the States**, creating a shared administrative culture.",
                  "tension": "Central influence over senior State administration is a recurring **federal grievance**."},
                 {"t": "COMMON CONSTITUTIONAL BODIES", "c": "green",
                  "fn": "Shared **audit, election and public-service institutions** apply **uniform integrity standards** across the polity.",
                  "tension": "Uniform standards must not become a substitute for **State institutional capacity**."},
                 {"t": "SINGLE CONSTITUTION", "c": "magenta",
                  "fn": "One document supplies the framework for the **Union and the States** \u2014 States do not draft separate constitutions.",
                  "tension": "**Asymmetric arrangements** still differentiate within that single framework."},
             ]},
            {"type": "matrix", "c": "cyan",
             "title": "THE COMPARATIVE CONTRAST THAT DECIDES THE OPTION",
             "headers": ["DIMENSION", "UNITED STATES MODEL", "INDIAN POSITION"],
             "widths": [0.22, 0.34, 0.44],
             "rows": [
                 ["**Citizenship**", "**Dual citizenship** \u2014 of the nation and of a State", "**Single citizenship** \u2014 of India alone"],
                 ["**Courts**", "A **dual court system** with separate federal and State hierarchies", "**One integrated hierarchy** applying Union and State law"],
                 ["**Higher services**", "No equivalent common all-India cadre", "**All-India Services** serving both the Union and the States"],
                 ["**Constitutions**", "States have their **own constitutions**", "A **single Constitution** for the Union and the States"],
             ]},
            {"type": "band", "label": "LIMIT \u2014 UNITY WITHIN FEDERALISM", "c": "yellow", "outline": True,
             "text": "These devices exist **within** a federal polity, not **instead of** it: the States retain their own governments, legislative fields and elected accountability. **WRONG:** single citizenship abolishes all residence-based distinctions \u2014 **CORRECT:** constitutionally permitted **residence or domicile provisions survive**. **WRONG:** integration means uniformity \u2014 **CORRECT:** the Constitution integrates **while retaining asymmetry and State autonomy**. The detailed law of citizenship acquisition and loss belongs to the citizenship topic."},
            {"type": "answer", "label": "CORE ARGUMENT \u2014 INTEGRATION DEVICES:",
             "text": "**Single citizenship, integrated courts and All-India Services** create administrative and legal unity **within, not instead of, a federal polity**."},
        ],
    },
]
