from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import sys,json,hashlib
sys.path.insert(0,'tools');import retrofit_v2_core_first as r
ROOT=Path.cwd(); REF=ROOT/'notes/Philosophy/flowcharts/philosophy-paper-i-indian-philosophy-01/continuous-at-a-glance-core-first'; OUT=ROOT/'notes/Polity/flowcharts/polity-01/continuous-at-a-glance-carvaka-standard-g8'; OUT.mkdir(parents=True,exist_ok=False)
F=r.FONT_DIR; bold=lambda n:ImageFont.truetype(str(F/'segoeuib.ttf'),n); reg=lambda n:ImageFont.truetype(str(F/'segoeui.ttf'),n)
stages=[
('CORPORATE STATE BEFORE 1773',['COMPANY: TRADE + TERRITORIAL POWER','NO SETTLED PARLIAMENTARY CONTROL','BENGAL CRISIS -> REGULATION'],['Company commercial rule acquired governmental functions.','Defect: private corporation exercised public power without constitutional accountability.','Consequence: Parliament intervenes, not because Company ceased to trade.'],'Corporate power first produced the need for statutory control.'),
('REGULATING ACT 1773',['GOVERNOR-GENERAL OF BENGAL','COUNCIL: 4 MEMBERS','CALCUTTA SUPREME COURT','CONTROL STILL IMPERFECT'],['Bengal presidency made supervisory centre over Bombay and Madras.','Governor-General in Council and Supreme Court created dual authorities.','Defect: jurisdictional conflict and weak central control remained.'],'1773 begins regulation, but did not create a coherent central government.'),
('SETTLEMENT ACT 1781',['COURT JURISDICTION CLARIFIED','REVENUE ACTS PROTECTED','EXECUTIVE–JUDICIARY BOUNDARY'],['Clarified Supreme Court limits over revenue administration.','Protected acts done in public/revenue capacity from ordinary court interference.','Bridge: exposed why Parliament needed a control system above ad-hoc clarification.'],'1781 repaired the 1773 court–executive conflict; it did not settle political control.'),
('PITT\'S INDIA ACT 1784',['DUAL CONTROL','BOARD OF CONTROL = GOVERNMENT','COURT OF DIRECTORS = COMMERCE'],['BOARD OF CONTROL: political, civil, military and revenue government.','COURT OF DIRECTORS: commercial administration retained.','Consequence: Company survived commercially; British Government gained decisive state supervision.'],'Pitt\'s Act separated commercial management from sovereign supervision.'),
('1786 + CHARTER ACT 1793',['1786: GOVERNOR-GENERAL POWER','1793: COMPANY MONOPOLY RENEWED','CENTRALISING TREND'],['1786 strengthened Governor-General where council opposition obstructed policy.','1793 renewed monopoly without altering dual-control principle.','Direction: executive capacity and Parliamentary oversight deepened together.'],'The early Charter phase retained Company commerce while tightening imperial direction.'),
('CHARTER ACT 1813',['MONOPOLY ENDS: INDIA TRADE','TEA + CHINA EXCEPTED','MISSION + EDUCATION OPENING'],['Ended Company monopoly in Indian trade; tea/China remained excepted.','Opened India to other British merchants and missionaries.','Marked Company shift from trader toward governing agency.'],'1813 weakened commercial exclusivity without yet ending Company rule.'),
('CHARTER ACT 1833',['ALL-INDIA GOVERNMENT','BENGAL GG -> GOVERNOR-GENERAL OF INDIA','COMPANY COMMERCIAL ROLE ENDS','LAW MEMBER'],['Centralised legislative power under Governor-General of India.','Company ceased commercial functions; remained administrative instrument.','Law Member/legislative machinery signalled uniform imperial governance.'],'1833 converted the Company from trader-ruler into a governing instrument.'),
('CHARTER ACT 1853',['LEGISLATIVE–EXECUTIVE SEPARATION','OPEN COMPETITIVE CIVIL SERVICE','NO FIXED RENEWAL'],['Separated legislative functions of Governor-General’s Council.','Opened civil-service competition in principle.','No fixed twenty-year renewal: Company tenure became provisional.'],'1853 made the Company constitutional machinery awaiting replacement.'),
('GOVERNMENT OF INDIA ACT 1858',['CROWN RULE','COMPANY ABOLISHED','SECRETARY OF STATE','VICEROY'],['Company rule ended after 1857; Crown assumed government.','Secretary of State in Council replaced Board/Court control machinery.','Governor-General became Viceroy: imperial executive now directly responsible to Crown.'],'1858 replaces Company governance with Crown responsibility, not representative government.'),
('COUNCILS ACTS 1861 + 1892',['1861: PORTFOLIOS + NOMINATION','1892: INDIRECT ELECTION ELEMENT','ASSOCIATION, NOT RESPONSIBILITY'],['1861 restored legislative councils and recognised portfolio administration.','1892 enlarged councils and introduced an indirect electoral principle.','Limit: executives remained unresponsible to elected Indians.'],'Councils widened consultation; they did not yet transfer executive responsibility.'),
('1909 + 1919',['1909: COMMUNAL ELECTORATES','1919: DYARCHY IN PROVINCES','CENTRE STILL RESPONSIBLE TO BRITAIN'],['1909 institutionalised separate communal electorates.','1919 split provincial subjects: transferred ministers versus reserved Governor control.','Responsible government remained partial and provincial, not central.'],'1909 changed representation; 1919 tested limited responsibility through dyarchy.'),
('GOVERNMENT OF INDIA ACT 1935',['FEDERAL SCHEME','3 LEGISLATIVE LISTS','PROVINCIAL AUTONOMY','GOVERNOR SAFEGUARDS'],['Proposed federation; federal part did not fully operate.','Federal, provincial and concurrent lists structured legislative power.','Provincial autonomy expanded, but Governors retained safeguards/discretion.'],'1935 supplied the institutional grammar later adapted by the Constitution.'),
('INDEPENDENCE ACT 1947',['SOVEREIGN DOMINIONS','PARAMOUNTCY LAPSED','CONSTITUENT ASSEMBLIES SOVEREIGN'],['Created India and Pakistan as independent Dominions.','Lapsed British paramountcy over princely states.','Constituent Assembly acquired sovereign law-making authority.'],'1947 ends imperial constitutional control and opens constitution-making sovereignty.'),
]
W=4800; H=700+len(stages)*510+600; im=Image.new('RGB',(W,H),'#071923');d=ImageDraw.Draw(im); d.rounded_rectangle((70,50,W-70,430),30,fill='#102a3a',outline='#28cde0',width=5);d.text((120,95),'POLITY 01 | HISTORICAL BACKGROUND OF THE INDIAN CONSTITUTION',font=bold(58),fill='white');d.text((120,180),'COMPANY TRADE  →  PARLIAMENTARY CONTROL  →  DUAL CONTROL  →  CROWN RULE  →  REPRESENTATION  →  AUTONOMY  →  SOVEREIGNTY',font=bold(34),fill='#55d8e8');d.text((120,255),'PRIMARY CORE FLOWS CHRONOLOGICALLY; ENRICHMENT FOLLOWS ONLY AFTER THE CONSTITUTIONAL SPINE.',font=reg(28),fill='#b9d2db');y=510
for n,(title,pills,cols,ans) in enumerate(stages,1):
 d.line((170,y,170,y+470),fill='#22cce0',width=12);d.ellipse((125,y+30,215,y+120),fill='#22cce0');d.text((145,y+47),str(n),font=bold(34),fill='#07202b'); x=280; d.rounded_rectangle((x,y,W-120,y+430),25,fill='#102b3a',outline=['#39d5e8','#43d6b0','#ffc857','#d784ff'][n%4],width=4);d.text((x+35,y+25),title,font=bold(42),fill='white');px=x+35
 for p in pills:
  tw=d.textbbox((0,0),p,font=bold(18))[2]+30;d.rounded_rectangle((px,y+88,px+tw,y+122),12,fill=['#27b9dc','#44c78e','#f1bd3e'][len(p)%3]);d.text((px+12,y+95),p,font=bold(18),fill='#071923');px+=tw+12
 for j,c in enumerate(cols):
  cx=x+35+j*1420;d.text((cx,y+155),['CONTROL / CLAIM','FUNCTION / MECHANISM','CONSEQUENCE / TRAP'][j],font=bold(20),fill=['#44d6b0','#ffc857','#ff7e8c'][j]);
  words=c.split();line='';yy=y+190
  for w in words:
   if d.textbbox((0,0),line+' '+w,font=reg(24))[2]>1320:d.text((cx,yy),line,font=reg(24),fill='#d5e8ee');yy+=32;line=w
   else:line=(line+' '+w).strip()
  d.text((cx,yy),line,font=reg(24),fill='#d5e8ee')
 d.rounded_rectangle((x+35,y+365,W-160,y+410),12,fill='#183f35',outline='#74da9a',width=2);d.text((x+55,y+375),'ANSWER SPINE:',font=bold(18),fill='#74da9a');d.text((x+270,y+372),ans,font=bold(22),fill='white');y+=510
d.rounded_rectangle((280,y,W-120,y+380),25,fill='#112c3b',outline='#99b0ba',width=4);d.text((320,y+30),'FINAL SYNTHESIS — THE CONSTITUTIONAL EVOLUTION',font=bold(42),fill='white');d.text((320,y+105),'COMPANY TRADE → PARLIAMENTARY CONTROL → DUAL CONTROL → CROWN RULE → ASSOCIATION → REPRESENTATION → PROVINCIAL RESPONSIBILITY → FEDERATION/AUTONOMY → SOVEREIGNTY',font=bold(27),fill='#57d7e8');d.text((320,y+185),'EXAM ROUTE: distinguish regulation from responsibility; commercial administration from political control; provincial autonomy from sovereign federalism.',font=reg(26),fill='#d5e8ee');im.save(OUT/'master.png',dpi=(300,300));r.poster_pdf(OUT/'master.png',OUT/'poster.pdf',im.size);st=[(i+1,510+i*510,510+(i+1)*510) for i in range(len(stages))];r.tile_pdf(OUT/'master.png',OUT/'tiled.pdf',im.size,st);r.render_previews(OUT/'tiled.pdf',OUT/'previews');spec={'topic':'polity-01','spine':'Company trade -> parliamentary control -> dual control -> Crown rule -> association -> representation -> provincial responsibility -> federation/autonomy -> sovereignty','stages':[{'title':a,'pills':b,'layout':'three-column constitutional timeline','must_show':c,'answer_band':e} for a,b,c,e in stages],'subordinate_enrichment':['comparative Acts/PYQ route after core']};(OUT/'bespoke-design-spec.json').write_text(json.dumps(spec,indent=2),encoding='utf8');h=hashlib.sha256((REF/'Carvaka_Continuous-At-a-Glance-Core-First_Poster_2026-08-22.pdf').read_bytes()).hexdigest();(OUT/'README.txt').write_text('Bespoke Cārvāka-standard Polity 01 companion\nReference SHA256 before/after: '+h+'\n',encoding='utf8');print(OUT)
