"""Authored learner-v2 data for Disaster Management Topic 06."""

from __future__ import annotations

import generate_disaster_management_common as common


LIVE_ATTEMPTS = [
    (
        "https://tsunami.incois.gov.in/TEWS/dsssop.jsp — fetched "
        "2026-09-04; the official ITEWC procedure confirmed staged bulletins, "
        "model and sea-level confirmation, threat categories and the local-"
        "authority all-clear boundary. Technical thresholds were not converted "
        "into a universal evacuation rule or a last-mile outcome."
    ),
    (
        "https://tsunami.incois.gov.in/TEWS/tsunamiready.jsp — fetched "
        "2026-09-04; the official page identified the INCOIS, IOTWMS, IOTIC "
        "and UNESCO-IOC setting but was content-thin for the current community "
        "roster. No nationwide readiness claim was inferred."
    ),
    (
        "https://pib.gov.in/PressReleasePage.aspx?PRID=2226879&reg=3&lang=1 "
        "— attempted 2026-09-04; the official PIB page returned HTTP 403. "
        "Official search metadata was used only to cross-check ITEWC's current "
        "institutional role and exercise context, not warning performance."
    ),
    (
        "https://ndma.gov.in/Natural-Hazards/Tsunami — attempted 2026-09-04; "
        "the official NDMA page failed at the transport layer. The module "
        "therefore retains only coastal-preparedness measures already audited "
        "in the canonical owners."
    ),
]


def _build() -> dict[str, object]:
    facts = [
        ("Tsunami generation", "A tsunami is a series of long waves generated by sudden displacement of a large water volume, commonly from vertical seabed movement during an undersea earthquake but also from landslides, volcanic activity or other displacement events."),
        ("Tide and storm-surge boundary", "A tsunami is not an astronomical tide and not a cyclone storm surge; tides follow gravitational cycles, storm surge is chiefly wind-and-pressure driven, and tsunami generation begins with sudden water displacement."),
        ("Generation is not impact", "An undersea earthquake does not automatically create a destructive tsunami; source mechanism, depth, displacement, distance, bathymetry and coastal form influence whether and how waves affect a coast."),
        ("Shoaling and inundation", "Tsunami waves change as they enter shallower water, producing run-up, inundation and damaging return flow; no universal wave height, speed or inland distance should be assumed."),
        ("Detection chain", "Seismic analysis identifies earthquake parameters, while open-ocean and coastal sea-level observations help confirm wave generation and update the assessment."),
        ("ITEWC", "The Indian Tsunami Early Warning Centre at INCOIS integrates earthquake analysis, pre-run model scenarios and sea-level observations to issue tsunami bulletins for Indian and regional service responsibilities."),
        ("Service-provider role", "ITEWC functions within the UNESCO-IOC Indian Ocean Tsunami Warning and Mitigation System as a Tsunami Service Provider; regional advisory responsibility does not transfer local evacuation authority."),
        ("Forecast and warning", "A tsunami assessment may progress from preliminary earthquake information to model-based threat categories and observation-informed updates; each bulletin is evidence at its own stage, not certainty about local impact."),
        ("Local all clear", "ITEWC may issue threat-passed or final information, but local conditions can vary and the all-clear decision remains with competent local authorities."),
        ("Inundation mapping", "Coastal topography, near-shore bathymetry, source scenarios, land use and exposed assets are combined in inundation or hazard maps for evacuation, siting and preparedness."),
        ("Coastal regulation", "CRZ category-specific controls and tsunami hazard mapping support risk-sensitive coastal development; they do not create one universal setback or elevation rule for every coast."),
        ("Evacuation chain", "Preparedness requires recognisable warnings, mapped routes, vertical or horizontal refuge options where appropriate, accessible transport, assembly points, accountability and repeated drills."),
        ("Natural buffers", "Mangroves, coastal forests, dunes, reefs and other natural features can reduce some impacts and provide co-benefits, but their protection is location-specific and they do not eliminate tsunami risk."),
        ("Ports and critical facilities", "Ports, harbours, coastal roads, power, communications, hospitals and fuel or hazardous-material facilities need shutdown, access, continuity and recovery plans tailored to tsunami and multi-hazard exposure."),
        ("Fisheries and tourism", "Fishers, harbour workers, tourists and seasonal visitors may lack local risk knowledge or face livelihood pressure, so warnings, signage, route information and reopening decisions must be sector-specific."),
        ("Community preparedness", "Last-mile safety depends on trusted local relay, natural-warning awareness, inclusive evacuation assistance, drills, family plans and community feedback, not warning-centre capability alone."),
        ("Tsunami Ready boundary", "UNESCO-IOC Tsunami Ready is community-level, indicator-based recognition that requires maintained preparedness; recognition of named communities is not certification of an entire State or country."),
        ("False alarms and uncertainty", "Precautionary action under uncertainty may produce apparent false alarms, but warning evaluation must consider available evidence, missed-event risk, public trust and transparent updating rather than demand impossible certainty."),
        ("Recovery and livelihoods", "Recovery should restore ports, fisheries, tourism, housing, services and ecosystems while using safer siting and Build Back Better principles instead of recreating exposed coastal development."),
        ("Warning-outcome firewall", "A sensor network, model run, bulletin, siren, map, drill or recognition proves an input or capability; receipt, evacuation, safe shelter, livelihood continuity and avoided loss require separate evidence."),
    ]
    traps = [
        "Do not describe a tsunami as a tide or cyclone-driven storm surge.",
        "Do not assume every undersea earthquake generates a destructive tsunami.",
        "Do not collapse earthquake detection, tsunami confirmation, bulletin and local warning into one step.",
        "Do not invent a universal wave height, speed, inundation distance or warning lead time.",
        "Do not treat a regional advisory as a local evacuation or all-clear order.",
        "Do not present one sea wall, mangrove belt or CRZ rule as sufficient everywhere.",
        "Do not omit ports, fisheries, tourists or hazardous coastal facilities.",
        "Do not call Tsunami Ready a national certification.",
        "Do not treat precaution under uncertainty as institutional failure merely because impact is limited.",
        "Do not infer last-mile safety or avoided loss from warning-system capability.",
    ]
    titles = [
        "Tsunami generation and displacement mechanism",
        "Tsunami tide and storm-surge distinctions",
        "Source bathymetry coast and consequence",
        "Deep-water travel shoaling run-up and return flow",
        "Seismic detection and sea-level confirmation",
        "ITEWC INCOIS and regional service architecture",
        "Bulletin stages threat categories and uncertainty",
        "Local warning evacuation and all-clear authority",
        "Inundation mapping and coastal land use",
        "Structural and ecosystem-based coastal protection",
        "Ports harbours utilities and critical facilities",
        "Fisheries tourism and transient populations",
        "Community preparedness drills and Tsunami Ready",
        "False-alarm trust feedback and readiness decay",
        "Recovery livelihoods and warning-outcome boundary",
    ]
    routes = [
        "Start with sudden displacement rather than a generic large-wave definition.",
        "Use the energy source to separate tsunami tide and storm surge.",
        "Trace source mechanism through bathymetry and coastal form.",
        "Explain consequence without inventing universal speed or height figures.",
        "Separate earthquake parameters from observed sea-level confirmation.",
        "Name ITEWC INCOIS and its regional service context precisely.",
        "Treat each bulletin as a staged assessment with uncertainty.",
        "Assign evacuation and all-clear decisions to competent local authorities.",
        "Connect mapping to routes refuge siting and development control.",
        "Combine engineered protection with conserved natural buffers.",
        "Plan shutdown access redundancy and service restoration.",
        "Tailor warnings and reopening to livelihood and visitor conditions.",
        "Use recognition as a maintained community process not a national label.",
        "Protect trust through transparent updates drills and feedback.",
        "Conclude with safe action and resilient recovery rather than system inputs.",
    ]
    panels = [
        common.panel("Tsunami generation chain", "causal-chain", [
            "SUDDEN WATER DISPLACEMENT",
            "EARTHQUAKE | LANDSLIDE | VOLCANIC ACTIVITY",
            "LONG WAVES -> COASTAL TRANSFORMATION",
            "RUN-UP + INUNDATION + RETURN FLOW",
        ], ["Tsunami generation", "Shoaling and inundation"]),
        common.panel("Coastal-hazard firewall", "comparison-table", [
            "TSUNAMI -> sudden displacement",
            "TIDE -> gravitational cycle",
            "STORM SURGE -> cyclone wind + pressure",
            "RULE -> different monitoring and response logic",
        ], ["Tide and storm-surge boundary"]),
        common.panel("Source-to-impact matrix", "matrix", [
            "SOURCE -> mechanism depth displacement",
            "PATH -> distance and ocean configuration",
            "COAST -> bathymetry topography land use",
            "OUTCOME -> exposure vulnerability and action",
        ], ["Generation is not impact", "Inundation mapping"]),
        common.panel("Detection-confirmation rail", "numbered-rail", [
            "1 SEISMIC EVENT ANALYSIS",
            "2 PRE-RUN MODEL SCENARIO",
            "3 SEA-LEVEL MONITORING",
            "4 UPDATED BULLETIN / THREAT STATUS",
        ], ["Detection chain", "Forecast and warning"]),
        common.panel("ITEWC authority map", "institution-map", [
            "INCOIS / ITEWC -> analysis and advisory",
            "IOTWMS / UNESCO-IOC -> regional framework",
            "STATE / DISTRICT / LOCAL -> protective action",
            "LOCAL AUTHORITY -> all clear",
        ], ["ITEWC", "Service-provider role", "Local all clear"]),
        common.panel("Warning-uncertainty ladder", "status-ladder", [
            "PRELIMINARY INFORMATION",
            "MODEL-BASED THREAT",
            "OBSERVATION-INFORMED UPDATE",
            "FINAL / THREAT PASSED -> local all-clear check",
        ], ["Forecast and warning", "Local all clear"]),
        common.panel("Inundation-to-evacuation map", "process-flow", [
            "HAZARD / INUNDATION MAP",
            "-> ZONE + ROUTE + REFUGE + ASSEMBLY",
            "-> ACCESSIBLE TRANSPORT + ACCOUNTABILITY",
            "-> DRILL + FEEDBACK + REVISION",
        ], ["Inundation mapping", "Evacuation chain"]),
        common.panel("Coastal protection portfolio", "comparison-table", [
            "ENGINEERED -> shelters walls breakwaters where justified",
            "NATURAL -> dunes mangroves forests reefs",
            "REGULATORY -> CRZ + risk-sensitive siting",
            "RULE -> layered and location-specific",
        ], ["Coastal regulation", "Natural buffers"]),
        common.panel("Coastal economy continuity", "network-map", [
            "PORT / HARBOUR -> shutdown access reopening",
            "FISHERIES -> boats landing centres markets",
            "TOURISM -> visitor warning signage route",
            "UTILITIES / HOSPITAL -> continuity and safe recovery",
        ], ["Ports and critical facilities", "Fisheries and tourism"]),
        common.panel("Tsunami Ready cycle", "feedback-loop", [
            "MAP RISK -> EDUCATE -> WARN",
            "EVACUATION MAP + SIGNAGE -> DRILL",
            "EVALUATE INDICATORS -> RENEW READINESS",
            "COMMUNITY RECOGNITION -> NOT NATIONAL CERTIFICATION",
        ], ["Community preparedness", "Tsunami Ready boundary"]),
        common.panel("Trust under uncertainty", "decision-tree", [
            "THREAT POSSIBLE? -> ISSUE PRECAUTIONARY MESSAGE",
            "NEW DATA? -> UPDATE / UPGRADE / DOWNGRADE",
            "EXPLAIN REASON -> PRESERVE TRUST",
            "LIMITED IMPACT -> NOT AUTOMATIC FALSE-ALARM FAILURE",
        ], ["False alarms and uncertainty"]),
        common.panel("Tsunami answer spine", "answer-spine", [
            "DEFINE DISPLACEMENT -> TRACE SHOALING AND CONSEQUENCE",
            "MAP DETECTION MODEL SEA LEVEL BULLETIN AND AUTHORITY",
            "CONNECT MAP TO EVACUATION BUFFERS PORTS AND LIVELIHOODS",
            "QUALIFY UNCERTAINTY READINESS RECOVERY AND OUTCOME",
        ], ["Recovery and livelihoods", "Warning-outcome firewall"]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2025", "GS-I",
            "Explain tsunami formation and consequences.",
            "Verified cross-paper route: Explain · 10 marks · 150 words; Geography retains physical-process ownership and this card supplies the disaster-management application.",
            [0, 1, 2, 3, 4, 8, 11, 12]),
        common.make_pyq_solution(facts, "2023", "GS-I",
            "Comment on the resource potential of India's coastline and highlight hazard preparedness.",
            "Verified cross-cutting route: Comment and highlight · 15 marks · 250 words; this card addresses only tsunami and coastal-preparedness dimensions.",
            [5, 9, 10, 11, 12, 13, 14, 15, 18]),
        common.make_pyq_solution(facts, "2024", "GS-III",
            "Describe the elements that determine disaster resilience.",
            "Verified direct ownership remains Topic 01; this conservative card routes warning, redundancy, community readiness, natural buffers and livelihood recovery as tsunami-resilience elements.",
            [4, 5, 8, 11, 12, 15, 16, 18, 19]),
    ]
    return common.topic(
        6, "Tsunami and Coastal Hazard Management",
        "06_Tsunami-and-Coastal-Hazard-Management", facts, traps,
        [
            (10, "Distinguish tsunami generation from tides and cyclone storm surge.", [0, 1, 2, 3]),
            (10, "Explain the detection, forecast, warning and local all-clear chain for tsunamis.", [4, 5, 6, 7, 8]),
            (15, "Analyse inundation mapping, coastal regulation, evacuation and natural buffers in tsunami preparedness.", [9, 10, 11, 12]),
            (15, "Examine tsunami preparedness for ports, fisheries, tourism and critical coastal services.", [13, 14, 15, 18]),
            (20, "Evaluate India's ITEWC-centred tsunami warning architecture while preserving uncertainty and last-mile boundaries.", [4, 5, 6, 7, 8, 15, 17, 19]),
            (20, "Design a sustained coastal-resilience framework for a low-frequency high-consequence tsunami risk.", [2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "Tsunami", "bathymetry", "Bottom Pressure Recorders",
            "tide gauges", "Indian Tsunami Early Warning Centre",
            "INCOIS", "Tsunami Service Provider", "IOTWMS",
            "Tsunami Ready", "inundation", "CRZ Notification, 2019",
            "bio-shield", "mangroves", "evacuation", "community preparedness",
        ],
        "The 2025 GS-I formation card and 2023 GS-I coastline card are verified cross-paper routes. The 2024 resilience card is a conservative application and does not displace Topic 01 ownership.",
        pyqs, LIVE_ATTEMPTS,
        "Official attempts covered ITEWC procedures, INCOIS Tsunami Ready material, PIB/MoES institutional updates and NDMA guidance. Thin, blocked and transport-failed sources are logged; no universal lead time, inundation figure, recipient count, false-alarm rate or avoided-loss outcome was invented.",
        extra=["00_Master-Framework.md", "README.md", "OFFICIAL-UPSC-SYLLABUS-MAPPING.md", "ANSWER-WORTHINESS-AUDIT.md", "REVISION-CHART_Hazards-Risk-and-Distinctive-Features.md"],
        register_headings=(
            "GENERATION TIDE SURGE SHOALING AND INUNDATION MAP",
            "ITEWC BULLETIN LOCAL-AUTHORITY AND EVACUATION FIREWALLS",
            "COASTAL BUFFERS PORTS LIVELIHOODS AND READINESS ANSWER SPINE",
            "CURRENT INCOIS NDMA AND WARNING-OUTCOME EVIDENCE BOUNDARY",
        ),
        register_answer_spine=[
            "DEFINE TSUNAMI AS SUDDEN WATER-DISPLACEMENT WAVES",
            "DISTINGUISH TIDE STORM SURGE AND NON-GENERATING EARTHQUAKES",
            "TRACE SOURCE PATH SHOALING RUN-UP INUNDATION AND RETURN FLOW",
            "MAP SEISMIC ANALYSIS MODEL SEA LEVEL BULLETIN AND LOCAL AUTHORITY",
            "CONNECT INUNDATION MAPS TO ACCESSIBLE EVACUATION AND REFUGE",
            "COMBINE REGULATION NATURAL BUFFERS PORTS FISHERIES AND TOURISM",
            "MAINTAIN COMMUNITY READINESS AND VERIFY ACTION AND RECOVERY",
        ],
    )


TOPIC_06 = _build()
