"""Authored Economy learner-v2 data for Topics 16-19."""

from __future__ import annotations

import generate_economy_common as common


STEMS = {
    16: "16_Industrial-Policy-1991-Reforms-PSUs-and-Disinvestment",
    17: "17_MSMEs-PLI-Semiconductors-and-Manufacturing-Strategy",
    18: "18_Infrastructure-PPPs-Logistics-and-Public-Investment",
    19: "19_Balance-of-Payments-Exchange-Rates-and-Forex-Reserves",
}


def panel(
    topic_number: int,
    title: str,
    kind: str,
    lines: list[str],
) -> tuple[str, str, str, list[str]]:
    stem = STEMS[topic_number]
    return (
        title,
        kind,
        "\n".join(lines),
        [
            f"upsc-ai-kit/knowledge/Economy/basic/{stem}.md",
            f"upsc-ai-kit/knowledge/Economy/advanced/{stem}.md",
        ],
    )


FACTS_16 = [
    ("Industrial-policy scope", "Industrial policy shapes firm entry, competition, technology, location, finance, infrastructure and strategic capability; it is not a synonym for subsidies or public ownership."),
    ("1948 mixed-economy settlement", "The Industrial Policy Resolution of 1948 assigned the state an important role within a mixed economy, so it must remain distinct from the more detailed public-sector reservation architecture adopted later."),
    ("1956 schedule architecture", "The Industrial Policy Resolution of 1956 classified industries into Schedules A, B and C and placed the commanding heights under public-sector leadership; the schedule boundaries belong to that policy vintage."),
    ("Licence-regime boundary", "Before 1991, industrial licensing under the Industries (Development and Regulation) Act, 1951 constrained entry, capacity, location and expansion in many industries, but licensing never represented every form of regulation."),
    ("1980s transition", "Modernisation, productivity measures, technology upgrading and selective delicensing in the Sixth and Seventh Plan periods preceded 1991, so the reform path was not an instantaneous clean break."),
    ("1991 reform package", "The New Industrial Policy of 1991 substantially reduced industrial licensing and public-sector reservation within a broader package that also included trade, exchange-rate and financial reforms."),
    ("Liberalisation and regulation", "Liberalisation reduces entry controls and expands competition, while competition law, sector regulation, environmental clearance and standards remain necessary after delicensing."),
    ("Disinvestment", "Disinvestment is the sale of part or all of government's equity in a public enterprise; a minority market sale can change ownership dispersion without transferring management control."),
    ("Strategic disinvestment", "DIPAM defines strategic disinvestment as an entire or substantial government share sale together with transfer of management control; privatisation is the subset in which control passes to a private strategic buyer."),
    ("Air India transaction", "The transfer of Air India to Talace Private Limited completed in January 2022 and is a completed control-transfer example, not evidence that every announced strategic sale reaches closure."),
    ("New PSE Policy", "The New Public Sector Enterprise Policy was notified on 4 February 2021 and seeks bare-minimum public-sector presence in four strategic sectors while considering other enterprises for privatisation, merger, subsidiarisation or closure under the policy process."),
    ("PSE-policy exclusions", "The official DIPAM policy page states that the New PSE Policy does not apply to specified classes such as not-for-profit companies and CPSEs with vulnerable-group support or developmental and promotional roles."),
    ("Asset monetisation", "Asset monetisation can transfer operating or revenue rights in a brownfield public asset for a specified period while public ownership is retained; it is not the same transaction as selling government equity."),
    ("Capital-receipt boundary", "Disinvestment proceeds are capital receipts from sale of an asset and cannot be treated as recurring revenue, a permanent deficit correction or proof of enterprise productivity."),
    ("PSU mandate test", "A PSU assessment should separate commercial objectives, explicit strategic or public-service obligations, regulator functions and any soft-budget support rather than presume that all PSUs serve the same purpose."),
    ("Competition after privatisation", "Privatisation can improve incentives, but without contestability and independent regulation it can replace a public monopoly with a private monopoly."),
    ("Employment and regional effects", "Industrial restructuring affects workers, suppliers and regions differently because labour-intensive dispersed industries and capital-intensive concentrated sectors have different adjustment and spillover patterns."),
    ("Plan-thrust distinction", "The Second Plan stressed heavy and basic industry under public-sector leadership; the Sixth and Seventh Plans stressed modernisation and early liberalisation; systemic post-1991 financial reform aligned with the Eighth Plan period."),
    ("Coal Controller distinction", "The Coal Controller's Organisation is a subordinate regulatory office under the Ministry of Coal with plan, grading, statistics and payment functions; it is distinct from Coal India Limited's production role."),
    ("CSR governance boundary", "Section 135 of the Companies Act, 2013 makes CSR a statutory Board-owned obligation for qualifying companies and links spending to Schedule VII; current thresholds and percentages must be verified from the dated law and rules."),
]

TRAPS_16 = [
    "Do not describe industrial policy as subsidies, licensing or state ownership alone.",
    "Do not merge the 1948 mixed-economy statement with the 1956 schedule structure.",
    "Do not treat 1991 as a clean break that had no 1980s precursor.",
    "Do not claim delicensing abolished competition, sector or environmental regulation.",
    "Do not equate every disinvestment transaction with privatisation.",
    "Do not turn policy announcement, in-principle approval and completed sale into one stage.",
    "Do not quote a disinvestment target or receipt without the financial year and official status.",
    "Do not confuse asset monetisation with an equity sale or permanent transfer of ownership.",
    "Do not generalise one completed transaction to every CPSE.",
    "Do not infer a PYQ answer letter from a routed objective demand.",
]

PANELS_16 = [
    panel(16, "Industrial-policy chronology", "timeline-strip", ["1948 -> mixed-economy role", "1956 -> Schedules A / B / C + commanding heights", "1980s -> modernisation + selective delicensing", "1991 -> systemic delicensing + wider reform package"]),
    panel(16, "Licence-to-competition transition", "transition-flow", ["LICENCE RAJ -> entry + capacity + location controls", "DELICENSING -> wider firm choice", "COMPETITION -> productivity pressure", "REGULATION REMAINS -> standards + environment + market power"]),
    panel(16, "Reform-package map", "policy-wheel", ["INDUSTRIAL DELICENSING", "TRADE OPENING", "EXCHANGE-RATE REFORM", "FINANCIAL REFORM -> connected, not isolated"]),
    panel(16, "Ownership-change spectrum", "classification-ladder", ["MINORITY SALE -> government control retained", "STRATEGIC DISINVESTMENT -> stake + management control", "PRIVATISATION -> control passes to private buyer", "CLOSURE / MERGER -> separate restructuring routes"]),
    panel(16, "Air India status chain", "status-flow", ["POLICY / TRANSACTION DESIGN", "-> BID + APPROVAL", "-> OWNERSHIP AND CONTROL TRANSFER", "-> JANUARY 2022 COMPLETION; do not generalise"]),
    panel(16, "New PSE Policy map", "decision-tree", ["FOUR STRATEGIC SECTORS -> bare-minimum public presence", "OTHER STRATEGIC CPSEs -> privatise / merge / subsidiary / close", "NON-STRATEGIC -> privatise where feasible or consider closure", "EXCLUDED CLASSES -> preserve official policy boundary"]),
    panel(16, "Disinvestment versus monetisation", "comparison-matrix", ["DISINVESTMENT -> equity stake", "STRATEGIC SALE -> equity + control", "MONETISATION -> time-bound operating / revenue rights", "FISCAL RULE -> one-off asset receipt, not recurring revenue"]),
    panel(16, "PSU mandate board", "institution-map", ["COMMERCIAL GOAL", "STRATEGIC / PUBLIC-SERVICE OBLIGATION", "OWNERSHIP FUNCTION", "REGULATOR FUNCTION -> keep separate"]),
    panel(16, "Competition safeguard chain", "cause-effect-board", ["PRIVATISATION WITHOUT CONTESTABILITY", "-> PRIVATE MARKET POWER", "-> PRICE / QUALITY RISK", "-> NEED competition law + sector regulation"]),
    panel(16, "Plan-thrust distinctions", "comparison-matrix", ["SECOND PLAN -> heavy / basic industry", "SIXTH -> modernisation + productivity", "SEVENTH -> technology + early delicensing", "EIGHTH -> post-1991 industrial + financial reform"]),
    panel(16, "Objective PYQ distinctions", "trap-board", ["CCO -> regulatory office; CIL -> producer", "CSR -> statutory Board duty; not ordinary tax", "SCHEDULES A/B/C -> 1956 vintage", "ANSWER KEY -> never infer from routing"]),
    panel(16, "Industrial-policy answer spine", "answer-spine", ["TRACE chronology and binding constraint", "DISTINGUISH licensing, ownership and control", "TEST competition, capability, jobs and regions", "CONCLUDE with explicit mandates + review"]),
]

TOPIC_16 = common.topic(
    16,
    "Industrial Policy, 1991 Reforms, PSUs and Disinvestment",
    STEMS[16],
    f"{STEMS[16]}_Learner-V2-Complete-Topic-Package.md",
    FACTS_16,
    TRAPS_16,
    [
        (10, "Distinguish disinvestment, strategic disinvestment and privatisation.", [7, 8, 9]),
        (10, "Why must industrial delicensing be accompanied by competition and sector regulation?", [3, 6, 15]),
        (15, "Trace the evolution of India's industrial policy from 1948 to 1991.", [0, 1, 2, 3, 4, 5]),
        (15, "Examine the design and limits of the New Public Sector Enterprise Policy.", [10, 11, 14, 16]),
        (20, "Evaluate PSU reform through ownership, mandate, competition and fiscal criteria.", [7, 8, 9, 10, 12, 13, 14, 15]),
        (20, "Has India's industrial policy moved from control to strategic capability building?", [0, 4, 5, 6, 15, 16, 17]),
    ],
    [
        "Industrial-policy scope and the 1948 settlement",
        "Industrial Policy Resolution 1956",
        "Licence raj under the IDR Act",
        "The 1980s reform transition",
        "New Industrial Policy 1991 and linked reforms",
        "Liberalisation with continuing regulation",
        "Disinvestment and control",
        "Strategic disinvestment",
        "Air India as a completed transaction",
        "New Public Sector Enterprise Policy",
        "PSE-policy exclusions and asset monetisation",
        "Capital receipts and fiscal boundaries",
        "PSU mandate and competition tests",
        "Employment, regional and Plan-thrust effects",
        "Coal Controller and CSR PYQ distinctions",
    ],
    [
        "Move from chronology to entry, capability, competition, ownership and adjustment effects.",
        "Separate equity sale, transfer of control, time-bound operating rights and closure.",
        "Judge public ownership enterprise by enterprise through mandate, governance and market structure.",
    ],
    PANELS_16,
    ["Industrial Policy Resolution of 1948", "Schedules A, B and C", "Industries (Development and Regulation) Act, 1951", "New Industrial Policy of 1991", "strategic disinvestment", "Talace Private Limited", "4 February 2021", "asset monetisation", "Coal Controller's Organisation", "Section 135"],
    "Audited ledgers route objective demands on Five-Year Plan industrial and financial thrusts, the Coal Controller's Organisation and CSR rules. They do not establish official answer letters here. The Basic owner carries these tested distinctions into the core evidence bank and practice extracts.",
    [],
    [
        "https://dipam.gov.in/disinvestment-policy — retrieved 2026-09-03; the official DIPAM page substantively defined strategic disinvestment, privatisation, minority stake sale and the New PSE Policy notified on 4 February 2021.",
        "https://dipam.gov.in/strategic-disinvestment — retrieved 2026-09-03; the live page exposed transaction notes but not a complete time-series table, so no receipt total, target or inferred completion status was imported.",
    ],
    "The DIPAM policy page was substantively retrievable and supports the transaction and PSE-policy distinctions. No current receipt, target, buyer, valuation or pipeline claim was added from an incomplete dashboard.",
    extra=[
        "basic/17_MSMEs-PLI-Semiconductors-and-Manufacturing-Strategy.md",
        "advanced/17_MSMEs-PLI-Semiconductors-and-Manufacturing-Strategy.md",
        "basic/18_Infrastructure-PPPs-Logistics-and-Public-Investment.md",
        "advanced/18_Infrastructure-PPPs-Logistics-and-Public-Investment.md",
        "basic/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "advanced/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
    ],
    allow_existing_history=True,
)


FACTS_17 = [
    ("MSME composite classification", "MSME classification uses both investment in plant and machinery or equipment and annual turnover under the prevailing notification; both dimensions and the effective date matter."),
    ("Current MSME thresholds", "Notification S.O. 1364(E) dated 21 March 2025 applies from 1 April 2025: micro up to Rs 2.5 crore investment and Rs 10 crore turnover, small up to Rs 25 crore and Rs 100 crore, and medium up to Rs 125 crore and Rs 500 crore."),
    ("Superseded 2020 thresholds", "The 1 July 2020 composite thresholds were lower and are a historical vintage; they must not be presented as the classification currently effective from 1 April 2025."),
    ("Udyam Registration", "Udyam Registration is a paperless, self-declared, Aadhaar and PAN-linked enterprise-registration gateway; registration establishes formal identity but does not guarantee credit, productivity or market access."),
    ("CGTMSE boundary", "CGTMSE provides guarantee cover to lending institutions for eligible collateral-free credit to micro and small enterprises; it reduces lender risk without replacing appraisal or working-capital discipline."),
    ("Delayed-payment problem", "Delayed payment is a receivables and cash-flow constraint distinct from lack of investment credit, collateral or technology capability."),
    ("TReDS mechanism", "RBI-regulated TReDS platforms facilitate discounting of accepted MSME trade receivables by financiers; buyer acceptance and onboarding remain necessary for the mechanism to work."),
    ("M1xchange distinction", "M1xchange is a TReDS platform for invoice and bill discounting, not a credit-rating agency, subsidy portal or machinery-finance institution."),
    ("Cluster route", "Cluster policy can lower shared costs of testing, design, skilling, effluent treatment and logistics, but a cluster label does not prove that supplier capability has upgraded."),
    ("PLI design", "Production Linked Incentive schemes link support to notified eligible incremental production or sales over a specified base and performance period rather than to capacity announcements alone."),
    ("PLI status ladder", "Approved scheme outlay, selected applicants, announced investment, installed capacity, verified incremental output and incentive disbursement are distinct stages and must not be merged."),
    ("PLI additionality test", "PLI should be assessed through additional investment, incremental output, domestic value addition, productivity, jobs, exports, supplier spillovers and fiscal cost, not headline production alone."),
    ("MSME participation limit", "Minimum investment, turnover, scale and compliance conditions can concentrate production incentives among larger firms unless supplier-development channels connect MSMEs to anchor manufacturers."),
    ("Semiconductor value chain", "The semiconductor ecosystem includes design, intellectual property, materials, equipment, wafer fabrication, assembly, testing, marking, packaging and downstream electronics."),
    ("Fab definition", "A semiconductor fab manufactures wafers through capital-, utility- and technology-intensive processes; it is distinct from chip design and downstream electronics assembly."),
    ("ATMP and OSAT", "ATMP or OSAT facilities perform assembly, testing, marking and packaging; they are important manufacturing stages but are not wafer-fabrication plants."),
    ("India Semiconductor Mission", "The India Semiconductor Mission is the nodal agency for implementation of semiconductor and display schemes and aims to build an electronics-manufacturing and design ecosystem."),
    ("Fab enabling conditions", "A fab requires reliable high-quality power, ultra-pure water, process talent, clean logistics, technology partners and a supplier ecosystem in addition to fiscal support."),
    ("Domestic value-addition boundary", "Rapid final assembly or gross production can coexist with high imported content, so domestic technological depth must be measured across stages rather than inferred from the final product label."),
    ("GVC manufacturing strategy", "A durable manufacturing strategy links scale, standards, technology, skills, finance, logistics, R&D and MSME suppliers to domestic demand and exports; low wages alone do not create competitiveness."),
]

TRAPS_17 = [
    "Do not quote an MSME threshold without its notification and effective date.",
    "Do not mix the superseded 2020 limits with the limits effective from 1 April 2025.",
    "Do not treat Udyam registration as a growth or credit guarantee.",
    "Do not merge collateral risk, receivables delay and technology constraints.",
    "Do not call TReDS or M1xchange a credit-rating or machinery-finance service.",
    "Do not equate PLI outlay, selection, investment announcement, output and disbursement.",
    "Do not call final electronics assembly a semiconductor fab.",
    "Do not merge fab, ATMP, OSAT, design and downstream production.",
    "Do not state a project as commissioned from an approval or announcement.",
    "Do not infer objective answer letters from routed or provisional-key PYQs.",
]

PANELS_17 = [
    panel(17, "MSME classification clock", "timeline-strip", ["1 JULY 2020 -> earlier composite thresholds", "21 MARCH 2025 -> S.O. 1364(E)", "1 APRIL 2025 -> revised thresholds effective", "ALWAYS attach investment + turnover + vintage"]),
    panel(17, "Current threshold matrix", "comparison-matrix", ["MICRO -> 2.5 investment / 10 turnover", "SMALL -> 25 investment / 100 turnover", "MEDIUM -> 125 investment / 500 turnover", "UNIT -> Rs crore; both ceilings apply"]),
    panel(17, "MSME constraint map", "problem-tree", ["IDENTITY -> Udyam", "COLLATERAL RISK -> CGTMSE", "RECEIVABLES DELAY -> TReDS", "CAPABILITY -> clusters + standards + technology"]),
    panel(17, "TReDS transaction rail", "process-flow", ["MSME SUPPLIER -> invoice", "BUYER -> accepts receivable", "FINANCIER -> discounts accepted claim", "PLATFORM -> M1xchange / other RBI-regulated TReDS"]),
    panel(17, "PLI status ladder", "status-ladder", ["SCHEME OUTLAY", "-> APPLICANT SELECTION", "-> ANNOUNCED / ACTUAL INVESTMENT", "-> VERIFIED OUTPUT -> DISBURSEMENT"]),
    panel(17, "PLI scorecard", "evaluation-board", ["ADDITIONAL INVESTMENT + OUTPUT", "DOMESTIC VALUE + PRODUCTIVITY", "JOBS + EXPORTS", "SUPPLIER / R&D SPILLOVERS - FISCAL COST"]),
    panel(17, "Anchor-supplier bridge", "ecosystem-flow", ["LARGE ANCHOR FIRM", "-> QUALITY / COST / DELIVERY REQUIREMENTS", "-> MSME SUPPLIER UPGRADING", "-> BROADER DOMESTIC SPILLOVERS"]),
    panel(17, "Semiconductor chain", "value-chain-map", ["DESIGN + IP", "-> MATERIALS + EQUIPMENT", "-> WAFER FABRICATION", "-> ATMP / OSAT -> DOWNSTREAM ELECTRONICS"]),
    panel(17, "Fab versus packaging", "comparison-matrix", ["FAB -> manufactures wafers", "ATMP / OSAT -> assembly + test + mark + package", "DESIGN -> architecture + IP", "ASSEMBLY -> final electronics; not automatically a fab"]),
    panel(17, "Fab enabling ecosystem", "input-wheel", ["RELIABLE POWER + ULTRA-PURE WATER", "PROCESS TALENT + TECHNOLOGY PARTNER", "CLEAN LOGISTICS + MATERIALS", "DEMAND + SUPPLIERS + LONG GESTATION"]),
    panel(17, "Domestic-value trap", "cause-effect-board", ["GROSS OUTPUT RISES", "BUT HIGH-VALUE INPUTS MAY REMAIN IMPORTED", "-> SHALLOW LOCAL VALUE ADDITION", "-> MEASURE stage-wise capability"]),
    panel(17, "Manufacturing answer spine", "answer-spine", ["CLASSIFY firm + bind constraint", "MATCH instrument to finance / scale / technology", "TRACE semiconductor stages and status", "EVALUATE additionality + spillovers + exit rules"]),
]

PYQ_SOLUTIONS_17 = [
    common.make_pyq_solution(FACTS_17, "2023", "GS-III", "Comment on the role of MSMEs in manufacturing and the government policies needed to strengthen them.", "Verified routed Mains demand; original model solution, not an official answer.", [0, 3, 4, 5, 6, 8, 19]),
    common.make_pyq_solution(FACTS_17, "2025", "GS-III", "Discuss the rationale, achievements and improvements required in the Production Linked Incentive scheme.", "Verified routed Mains demand; original model solution, not an official answer.", [9, 10, 11, 12, 18, 19]),
]

TOPIC_17 = common.topic(
    17,
    "MSMEs, PLI, Semiconductors and Manufacturing Strategy",
    STEMS[17],
    f"{STEMS[17]}_Learner-V2-Complete-Topic-Package.md",
    FACTS_17,
    TRAPS_17,
    [
        (10, "Distinguish Udyam, CGTMSE and TReDS as MSME-policy instruments.", [3, 4, 5, 6]),
        (10, "Differentiate semiconductor fabrication from ATMP or OSAT.", [13, 14, 15]),
        (15, "Evaluate PLI through additionality rather than headline production.", [9, 10, 11, 12, 18]),
        (15, "Explain how MSMEs can enter manufacturing supply chains.", [0, 3, 4, 5, 6, 8, 12, 19]),
        (20, "Design an integrated Indian semiconductor-manufacturing strategy.", [13, 14, 15, 16, 17, 18, 19]),
        (20, "Can anchor-firm incentives produce broad-based manufacturing transformation?", [8, 9, 11, 12, 18, 19]),
    ],
    [
        "MSME composite classification",
        "Threshold revisions and effective dates",
        "Udyam registration",
        "CGTMSE and collateral risk",
        "Delayed payments",
        "TReDS and M1xchange",
        "Cluster-based capability building",
        "PLI design",
        "PLI status and additionality",
        "MSME access to anchor-led incentives",
        "Semiconductor value-chain architecture",
        "Wafer fabrication",
        "ATMP and OSAT",
        "India Semiconductor Mission and utilities",
        "Domestic value addition and GVC strategy",
    ],
    [
        "Diagnose identity, collateral, receivables, technology, scale and market constraints separately.",
        "Evaluate production incentives from outlay to verified output, disbursement and spillovers.",
        "Map design, fab, packaging, suppliers, utilities, skills and downstream demand before judging capability.",
    ],
    PANELS_17,
    ["S.O. 1364(E)", "1 April 2025", "Rs 2.5 crore", "Rs 125 crore", "Udyam Registration", "CGTMSE", "TReDS", "M1xchange", "Production Linked Incentive", "ATMP", "OSAT", "India Semiconductor Mission", "ultra-pure water"],
    "Audited ledgers route the 2023 Mains demand on MSMEs, the 2025 Mains demand on PLI, objective demands on MSME classification and PLI, and a 2026 provisional-key demand on M1xchange. The package solves only the verified Mains demands and keeps every objective answer letter neutral.",
    PYQ_SOLUTIONS_17,
    [
        "https://ism.gov.in/ — retrieved 2026-09-03; the official India Semiconductor Mission page substantively described ISM's ecosystem aim and nodal implementation role, but supplied no project commissioning claim used here.",
        "https://pib.gov.in/PressReleseDetailm.aspx?PRID=2118292 — attempted 2026-09-03 and returned HTTP 403; no threshold was imported from that failed fetch, and the dated repository owner remains controlling.",
        "https://www.meity.gov.in/offerings/schemes-and-services/details/production-linked-incentive-scheme-pli-for-large-scale-electronics-manufacturing-gNyMDOtQWa — attempted 2026-09-03 and returned HTTP 403; no incentive rate, outlay, applicant or disbursement figure was imported.",
    ],
    "The ISM homepage was substantively retrievable for institutional purpose only. The PIB and MeitY pages were blocked in the live fetcher, so thresholds and PLI mechanics retain their dated repository-owner provenance and no current project or disbursement number is asserted.",
    extra=[
        "basic/16_Industrial-Policy-1991-Reforms-PSUs-and-Disinvestment.md",
        "advanced/16_Industrial-Policy-1991-Reforms-PSUs-and-Disinvestment.md",
        "basic/18_Infrastructure-PPPs-Logistics-and-Public-Investment.md",
        "advanced/18_Infrastructure-PPPs-Logistics-and-Public-Investment.md",
        "basic/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "advanced/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "basic/22_Employment-Labour-Codes-Skills-and-Demographic-Dividend.md",
        "advanced/22_Employment-Labour-Codes-Skills-and-Demographic-Dividend.md",
    ],
)


FACTS_18 = [
    ("Infrastructure service boundary", "Infrastructure is valuable when a planned asset is completed, connected, operated and maintained as a usable service; sanctioned spending or physical capacity alone is not the outcome."),
    ("Economic and social infrastructure", "Transport, energy and communications enable production, while health, education, water and sanitation build capabilities; their revenue models differ even though both can raise productivity and welfare."),
    ("Project-cycle appraisal", "Demand, engineering, land, environmental, social, financial and institutional appraisal precede financing and determine whether later construction risk is manageable."),
    ("Public investment channels", "Public capital expenditure can support current demand and raise future productive capacity, but the size and timing of any multiplier depend on slack, import leakage, financing, execution and network usefulness."),
    ("Crowding-in boundary", "Public investment can crowd in private investment by lowering logistics cost and uncertainty, but poorly selected or delayed projects can crowd out finance or create stranded assets."),
    ("PPP definition", "A PPP is a long-term arrangement allocating project functions, performance obligations and risks between public and private parties; it is not free infrastructure or complete privatisation."),
    ("Risk-allocation principle", "Construction, demand, finance, land, operating, regulatory and political risks should be assigned to the party best able to manage them rather than shifted mechanically to the private partner."),
    ("BOT variants", "BOT toll and BOT annuity structures allocate demand and payment risk differently; the label BOT alone is insufficient to identify who bears traffic risk."),
    ("Hybrid Annuity Model", "Under the road-sector HAM described by the owner, government provides about 40 per cent through construction-linked payments and the balance is serviced through annuities, moving traffic risk to government while private construction and operating obligations remain."),
    ("Toll-Operate-Transfer", "TOT monetises completed toll-road operating rights for a concession period against an upfront payment; it is a brownfield-operation model, not construction of a new road under BOT."),
    ("VGF boundary", "Viability Gap Funding is grant support for an economically justified PPP that is not fully commercially viable, subject to notified eligibility and ceilings; support does not cure weak demand, land or contract design."),
    ("Kelkar Committee", "The 2015 Kelkar Committee on revisiting and revitalising PPPs stressed balanced risk sharing, dispute resolution, regulation and separation of genuine PPPs from public-financed EPC contracts."),
    ("NIP planning status", "The National Infrastructure Pipeline is a multi-year project and investment planning pipeline; a listed estimate is not proof that finance, land, approval or completion has occurred."),
    ("NMP monetisation status", "The National Monetisation Pipeline identifies brownfield public assets for time-bound private operating or revenue rights while ownership remains public; it is distinct from fresh capex and equity disinvestment."),
    ("PM GatiShakti", "PM GatiShakti is a GIS-based whole-of-government platform for integrated multimodal infrastructure planning; planning visibility does not itself complete land, clearance, finance or construction."),
    ("National Logistics Policy", "The National Logistics Policy addresses process, digital integration, standardisation, data, skills and service improvement in addition to physical transport infrastructure."),
    ("Multimodal logistics", "Efficient logistics links roads, rail, ports, waterways, air, warehousing, border processes and digital information, so a port or corridor cannot be assessed as an isolated asset."),
    ("Rail-station PPP model", "Railway-station redevelopment can use commercial land or lease revenue to cross-subsidise passenger-amenity upgrades, creating footfall, land-title, coordination and public-service risks distinct from road toll models."),
    ("Vizhinjam and Sagarmala", "Vizhinjam is a project-level deep-draft trans-shipment-hub strategy, while Sagarmala is a broader port-led-development programme; project ramp-up must not be inferred from programme ambition."),
    ("Maintenance and liabilities", "Lifecycle maintenance, service standards, renegotiation and contingent public payments determine value for money; keeping a commitment off the immediate budget does not remove taxpayer or user cost."),
]

TRAPS_18 = [
    "Do not equate a project pipeline, allocation, sanction, award, commissioning and service outcome.",
    "Do not quote a capex multiplier as timeless or institution-free.",
    "Do not define PPP as free infrastructure or complete privatisation.",
    "Do not allocate every project risk to the private partner by slogan.",
    "Do not merge BOT toll, BOT annuity, HAM, TOT and EPC.",
    "Do not quote VGF support without the applicable scheme, sector and ceiling.",
    "Do not merge NIP planning, NMP monetisation and new public capex.",
    "Do not treat PM GatiShakti or the National Logistics Policy as completed physical assets.",
    "Do not merge Vizhinjam with the Sagarmala programme.",
    "Do not infer objective answer letters from routed or provisional-key PYQs.",
]

PANELS_18 = [
    panel(18, "Infrastructure service chain", "lifecycle-flow", ["IDENTIFY + APPRAISE", "-> FINANCE + ALLOCATE RISK", "-> BUILD + COMMISSION", "-> OPERATE + MAINTAIN -> USABLE SERVICE"]),
    panel(18, "Infrastructure effects", "two-channel-board", ["DEMAND CHANNEL -> construction activity", "SUPPLY CHANNEL -> lower cost + reliability", "CAPABILITY CHANNEL -> health / education / water", "OUTCOME DEPENDS -> completion + connection + use"]),
    panel(18, "Project appraisal gate", "decision-board", ["DEMAND + ENGINEERING", "LAND + ENVIRONMENT + SOCIAL", "FINANCE + INSTITUTION", "PASS BEFORE bankability claim"]),
    panel(18, "PPP risk matrix", "risk-allocation-grid", ["PUBLIC -> land / policy where controllable", "PRIVATE -> construction / operation where controllable", "DEMAND -> toll or government-payment design", "SHARED -> force majeure + renegotiation rules"]),
    panel(18, "Road-model comparison", "comparison-matrix", ["BOT TOLL -> private traffic exposure", "BOT ANNUITY -> public payment stream", "HAM -> milestone support + annuity", "TOT -> brownfield operating rights"]),
    panel(18, "VGF decision route", "decision-tree", ["ECONOMICALLY JUSTIFIED?", "COMMERCIALLY SUB-VIABLE?", "COMPETITIVE PRIVATE SELECTION?", "NOTIFIED SUPPORT -> still test demand + land + contract"]),
    panel(18, "PPP stress and correction", "timeline-strip", ["POST-2012 -> BOT-toll stress", "2015 -> Kelkar Committee", "2016 ONWARD -> HAM correction", "LIMIT -> risk shifts; it does not disappear"]),
    panel(18, "Infrastructure financing fork", "classification-tree", ["NIP -> planning pipeline", "PUBLIC CAPEX -> new investment spending", "NMP -> brownfield monetisation", "PPP -> contract + risk allocation"]),
    panel(18, "GatiShakti and NLP", "paired-process-map", ["GATISHAKTI -> GIS planning coordination", "NLP -> process + digital + standards + skills", "BOTH -> multimodal efficiency", "NEITHER -> automatic project completion"]),
    panel(18, "Port logistics distinction", "comparison-matrix", ["VIZHINJAM -> trans-shipment project", "SAGARMALA -> port-led programme", "PORT VALUE -> berth + evacuation + customs", "STATUS -> verify actual ramp-up"]),
    panel(18, "Station redevelopment logic", "cash-flow-map", ["COMMERCIAL LAND / LEASE VALUE", "-> CROSS-SUBSIDISE station upgrade", "RISKS -> footfall + title + coordination", "DUTY -> passenger access + safety + affordability"]),
    panel(18, "Infrastructure answer spine", "answer-spine", ["DEFINE service and project stage", "APPRAISE demand + land + finance", "ALLOCATE risks by controllability", "TEST completion + maintenance + contingent liability"]),
]

PYQ_SOLUTIONS_18 = [
    common.make_pyq_solution(FACTS_18, "2018", "GS-III", "Enumerate CPEC as an OBOR subset and India's objections.", "Verified routed Mains demand; original model solution uses the owner's minimum economic route and does not infer a broader official model answer.", [0, 2, 5, 6, 16]),
    common.make_pyq_solution(FACTS_18, "2020", "GS-III", "Explain capital formation and the factors governing a PPP concession agreement.", "Verified routed Mains demand; original model solution, not an official answer.", [2, 3, 5, 6, 7, 10, 19]),
    common.make_pyq_solution(FACTS_18, "2021", "GS-III", "Discuss the role of infrastructure investment in rapid and inclusive growth.", "Verified routed Mains demand; original model solution, not an official answer.", [0, 1, 3, 4, 16, 19]),
    common.make_pyq_solution(FACTS_18, "2022", "GS-II", "Discuss PM GatiShakti and coordination between government and private sector.", "Verified cross-routed Mains demand; original model solution, not an official answer.", [2, 5, 6, 14, 15, 16]),
    common.make_pyq_solution(FACTS_18, "2022", "GS-III", "Examine the role of PPP in railway-station redevelopment.", "Verified routed Mains demand; original model solution, not an official answer.", [5, 6, 17, 19]),
    common.make_pyq_solution(FACTS_18, "2024", "GS-III", "Discuss the need for regional air connectivity and the UDAN scheme.", "Verified routed Mains demand; original model solution uses the owner's project-cycle logic and does not invent current route counts.", [0, 1, 2, 4, 10, 16, 19]),
]

TOPIC_18 = common.topic(
    18,
    "Infrastructure, PPPs, Logistics and Public Investment",
    STEMS[18],
    f"{STEMS[18]}_Learner-V2-Complete-Topic-Package.md",
    FACTS_18,
    TRAPS_18,
    [
        (10, "Why is infrastructure an operating service rather than merely a created asset?", [0, 1, 2, 19]),
        (10, "Distinguish NIP, NMP and PPP.", [5, 12, 13]),
        (15, "Explain the principle of risk allocation in PPP contracts.", [5, 6, 7, 8, 9, 10, 11]),
        (15, "How do PM GatiShakti and the National Logistics Policy complement each other?", [14, 15, 16]),
        (20, "Evaluate India's road-sector PPP evolution from BOT stress to HAM.", [5, 6, 7, 8, 9, 11, 19]),
        (20, "Design an infrastructure strategy that crowds in investment without hiding fiscal and execution risks.", [0, 2, 3, 4, 6, 12, 13, 19]),
    ],
    [
        "Infrastructure as a completed service",
        "Economic and social infrastructure",
        "Project-cycle appraisal",
        "Public investment and multiplier cautions",
        "Crowding in and stranded assets",
        "PPP definition and funding boundary",
        "Risk allocation",
        "BOT toll and annuity",
        "Hybrid Annuity Model",
        "Toll-Operate-Transfer and VGF",
        "Kelkar Committee",
        "NIP and NMP",
        "PM GatiShakti",
        "National Logistics Policy and multimodality",
        "Station, port, maintenance and liability distinctions",
    ],
    [
        "Use the full project cycle from appraisal through maintenance and service outcomes.",
        "Compare financing models through risk, payment, ownership, stage and contingent liability.",
        "Connect multimodal planning, process reform, feeder links and lifecycle maintenance to productivity.",
    ],
    PANELS_18,
    ["public capital expenditure", "Hybrid Annuity Model", "about 40 per cent", "Toll-Operate-Transfer", "Viability Gap Funding", "Kelkar Committee", "National Infrastructure Pipeline", "National Monetisation Pipeline", "PM GatiShakti", "National Logistics Policy", "Vizhinjam", "Sagarmala"],
    "Audited ledgers route Mains demands on CPEC, PPP concession design, infrastructure and inclusive growth, GatiShakti coordination, railway-station redevelopment and UDAN. Objective ledgers add green rural roads, UNOPS S3i, Vizhinjam and Sagarmala. The package solves verified Mains demands only and preserves answer-key neutrality for objective items.",
    PYQ_SOLUTIONS_18,
    [
        "https://www.pppinindia.gov.in/ — retrieved 2026-09-03; the official DEA Infrastructure Finance Secretariat page substantively described the Private Investment Unit's responsibility for PPP policy, model concession agreements, PPPAC, VGF and IIPDF.",
        "https://www.dea.gov.in/viability-gap-funding-vgf-scheme — attempted 2026-09-03 and failed at the transport layer; no current support ceiling or sector eligibility was imported from the failed fetch.",
        "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1860192 — attempted 2026-09-03 and returned HTTP 403; no logistics target, platform count or performance claim was imported.",
    ],
    "The PPP in India homepage was substantively retrievable for institutional architecture. The DEA VGF and PIB logistics pages failed in the fetcher, so the package retains owner-sourced qualitative mechanics and avoids new ceilings, pipeline values, rankings or project counts.",
    extra=[
        "basic/09_Union-Budget-Fiscal-Policy-and-Deficit-Indicators.md",
        "advanced/09_Union-Budget-Fiscal-Policy-and-Deficit-Indicators.md",
        "basic/16_Industrial-Policy-1991-Reforms-PSUs-and-Disinvestment.md",
        "advanced/16_Industrial-Policy-1991-Reforms-PSUs-and-Disinvestment.md",
        "basic/17_MSMEs-PLI-Semiconductors-and-Manufacturing-Strategy.md",
        "advanced/17_MSMEs-PLI-Semiconductors-and-Manufacturing-Strategy.md",
        "basic/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "advanced/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "basic/31_Energy-Infrastructure-Economics-Power-Fuels-and-Energy-Security.md",
        "advanced/31_Energy-Infrastructure-Economics-Power-Fuels-and-Energy-Security.md",
    ],
)


FACTS_19 = [
    ("BoP residence boundary", "The balance of payments is a statistical statement of transactions between residents and non-residents during a period; residence follows centre of predominant economic interest rather than nationality alone."),
    ("Double-entry accounting", "BoP transactions use double-entry accounting, so the overall statement balances through counterpart entries, reserve-asset changes and errors and omissions; a current-account deficit is not an unpaired loss."),
    ("Current account", "Under BPM6-aligned presentation, the current account covers goods, services, primary income and secondary income."),
    ("Goods and services", "Merchandise exports and imports are distinct from services such as transport, travel, software and financial services even though both enter the current account."),
    ("Primary and secondary income", "Primary income includes compensation and investment income, while secondary income records current transfers such as personal remittances; remittances are not merchandise exports."),
    ("Capital account", "The modern capital account records capital transfers and acquisition or disposal of non-produced non-financial assets; it is much narrower than the older broad use of the term capital account."),
    ("Financial account", "Direct investment, portfolio investment, financial derivatives, other investment such as loans and deposits, and reserve assets enter the financial account under modern BoP accounting."),
    ("FDI and portfolio distinction", "FDI is associated with a lasting interest and control-linked relationship, whereas portfolio investment is generally a tradable financial claim without equivalent managerial control; neither is automatically stable in every episode."),
    ("CAD financing", "A current-account deficit must be matched by net financial inflows, reserve use and accounting adjustment, so vulnerability depends on financing quality, maturity, currency and hedging rather than the CAD alone."),
    ("Merchandise-deficit offset", "A merchandise trade deficit can coexist with a smaller current-account deficit when net services, primary-income or secondary-income receipts offset part of the goods gap."),
    ("Exchange-rate quote", "An exchange rate is the price of one currency in another; under a rupees-per-dollar quote, a higher number means the rupee has depreciated against the dollar."),
    ("Depreciation and devaluation", "Depreciation and appreciation describe market-rate movement, while devaluation and revaluation are official parity changes under a fixed or administered exchange-rate arrangement."),
    ("Managed float", "India operates a managed-float framework in which the rupee is market-determined but the RBI may intervene to smooth excessive volatility without declaring a fixed target level."),
    ("Intervention liquidity effect", "An RBI sale of foreign currency supplies dollars and absorbs rupee liquidity, while a purchase of foreign currency injects rupees; the monetary effect can be offset through sterilisation operations."),
    ("Sterilisation boundary", "Sterilised intervention offsets the domestic-liquidity impact of foreign-exchange operations but has costs and cannot permanently override underlying external imbalances."),
    ("NEER and REER", "NEER is a trade-weighted nominal effective exchange-rate index, while REER adjusts the effective rate for relative prices or costs; interpretation requires the published index convention, base and weights."),
    ("Trade-balance response", "Currency depreciation does not guarantee an immediate trade-balance improvement because contracts, import dependence, pass-through, capacity and export-import elasticities shape quantity adjustment."),
    ("Forex-reserve composition", "India's reserve assets include foreign-currency assets, monetary gold, Special Drawing Rights and the reserve-tranche position in the IMF; reserves are central-bank assets, not budget revenue."),
    ("Reserve-adequacy test", "Reserve adequacy is multidimensional and may be assessed against imports, short-term debt, broad money, external financing needs and stress scenarios; an absolute dollar stock alone is insufficient."),
    ("External-debt exposure", "External vulnerability depends on borrower, instrument, original and residual maturity, currency denomination, hedging and rollover needs; ECBs are distinct from FDI, portfolio debt and official assistance."),
]

TRAPS_19 = [
    "Do not define BoP by nationality rather than residence and economic territory.",
    "Do not treat the current-account balance as a standalone cash loss without counterpart entries.",
    "Do not place FDI, portfolio flows and ordinary loans in the narrow BPM6 capital account.",
    "Do not classify personal remittances as merchandise exports.",
    "Do not discuss appreciation or depreciation without stating the currency quote convention.",
    "Do not merge market depreciation with official devaluation.",
    "Do not describe India's managed float as either a fixed peg or a pure free float.",
    "Do not reverse the rupee-liquidity effect of RBI dollar purchases and sales.",
    "Do not interpret NEER or REER without its index convention, base and weights.",
    "Do not quote a reserve stock, import cover or debt ratio without its date and source.",
]

PANELS_19 = [
    panel(19, "BoP accounting spine", "accounting-flow", ["RESIDENT <-> NON-RESIDENT TRANSACTIONS", "CURRENT + CAPITAL + FINANCIAL ACCOUNTS", "DOUBLE ENTRY + ERRORS / OMISSIONS", "RESERVE-ASSET CHANGE closes recorded financing"]),
    panel(19, "Current-account map", "classification-tree", ["GOODS", "SERVICES", "PRIMARY INCOME", "SECONDARY INCOME -> personal remittances"]),
    panel(19, "Capital-financial fork", "comparison-matrix", ["CAPITAL -> capital transfers", "CAPITAL -> non-produced non-financial assets", "FINANCIAL -> FDI + portfolio + loans", "FINANCIAL -> derivatives + reserve assets"]),
    panel(19, "CAD financing identity", "balance-flow", ["CURRENT-ACCOUNT DEFICIT", "-> NET FINANCIAL INFLOWS", "OR -> RESERVE USE", "PLUS -> ERRORS / OMISSIONS; quality matters"]),
    panel(19, "Trade-deficit offsets", "offset-board", ["MERCHANDISE DEFICIT", "+ NET SERVICES", "+ PRIMARY INCOME", "+ SECONDARY INCOME -> CURRENT ACCOUNT"]),
    panel(19, "Currency quote board", "quote-map", ["QUOTE -> RUPEES PER US DOLLAR", "NUMBER RISES -> dollar costs more", "RUPEE -> DEPRECIATES", "ALWAYS state quote before direction"]),
    panel(19, "Rate-change vocabulary", "comparison-matrix", ["MARKET -> depreciation / appreciation", "OFFICIAL PARITY -> devaluation / revaluation", "NOMINAL -> observed currency price", "REAL -> relative-price adjusted"]),
    panel(19, "Managed-float rail", "policy-flow", ["MARKET DEMAND + SUPPLY", "-> RUPEE RATE MOVES", "RBI -> may smooth excessive volatility", "NO DECLARED FIXED TARGET LEVEL"]),
    panel(19, "Intervention-liquidity matrix", "comparison-matrix", ["RBI SELLS DOLLARS -> rupees absorbed", "RBI BUYS DOLLARS -> rupees injected", "STERILISATION -> offsets liquidity effect", "LIMIT -> costs + underlying pressure"]),
    panel(19, "NEER-REER ladder", "index-ladder", ["BILATERAL RATE", "-> TRADE-WEIGHTED NEER", "-> RELATIVE-PRICE ADJUSTED REER", "INTERPRET -> use RBI convention + base + weights"]),
    panel(19, "Reserve-adequacy dashboard", "risk-dashboard", ["IMPORT COVER", "SHORT-TERM DEBT", "BROAD MONEY / FINANCING NEED", "MATURITY + CURRENCY + HEDGING + STRESS"]),
    panel(19, "External-sector answer spine", "answer-spine", ["CLASSIFY transaction by account", "STATE sign / quote / stock-flow convention", "TRACE financing + intervention + liquidity", "JUDGE resilience through composition, not headline"]),
]

TOPIC_19 = common.topic(
    19,
    "Balance of Payments, Exchange Rates and Forex Reserves",
    STEMS[19],
    f"{STEMS[19]}_Learner-V2-Complete-Topic-Package.md",
    FACTS_19,
    TRAPS_19,
    [
        (10, "Distinguish the current, capital and financial accounts of the balance of payments.", [2, 5, 6]),
        (10, "Differentiate depreciation from devaluation and NEER from REER.", [10, 11, 15]),
        (15, "Explain how a current-account deficit is financed and when it becomes vulnerable.", [1, 8, 9, 18, 19]),
        (15, "Trace the liquidity effects of RBI foreign-exchange intervention and sterilisation.", [12, 13, 14]),
        (20, "Assess external-sector resilience through account composition, financing quality and reserves.", [0, 1, 2, 6, 8, 9, 18, 19]),
        (20, "Why does currency depreciation not automatically correct a trade deficit?", [10, 11, 12, 16, 19]),
    ],
    [
        "BoP residence and period boundary",
        "Double-entry accounting",
        "Current-account architecture",
        "Goods and services",
        "Primary income, secondary income and remittances",
        "Narrow capital account",
        "Financial account",
        "FDI and portfolio investment",
        "CAD financing",
        "Merchandise deficit and invisible offsets",
        "Exchange-rate quotation",
        "Depreciation versus devaluation",
        "India's managed float",
        "Intervention and sterilisation",
        "NEER, REER, reserves and external-debt risk",
    ],
    [
        "Classify each flow by residence, account, credit-debit logic and stock-flow boundary.",
        "State the exchange-rate quote before judging appreciation, depreciation or intervention.",
        "Assess resilience through financing quality, reserve adequacy and balance-sheet exposure.",
    ],
    PANELS_19,
    ["centre of predominant economic interest", "current account", "capital account", "financial account", "secondary income", "managed float", "sterilisation", "NEER", "REER", "devaluation", "Special Drawing Rights", "reserve-tranche position", "External Commercial Borrowings"],
    "Audited ledgers route objective demands on external-debt composition, currency-crisis resilience, FDI characteristics and instruments, devaluation, NEER and REER, Federal Reserve tightening and ECBs, and Switzerland's gold-trade versus reserve-holder distinction. Official historical answer keys are unavailable locally for these routed items, so no answer letter is inferred.",
    [],
    [
        "https://www.rbi.org.in/scripts/publicationsview.aspx?id=13013 — retrieved 2026-09-03; the official RBI BPM6-aligned chapter substantively defined BoP, residence and the current, capital and financial accounts.",
        "https://www.rbi.org.in/scripts/PublicationReportDetails.aspx?ID=596 — retrieved 2026-09-03; the official RBI report documented the BPM6-based Balance of Payments Manual for India and its compilation context.",
        "https://www.rbi.org.in/Scripts/PublicationsView.aspx?id=9479 — retrieved 2026-09-03; this older RBI page uses a BPM5-era broad capital-account presentation, so it is recorded as a vintage caution and not used to overwrite the modern capital-versus-financial split.",
    ],
    "The RBI BPM6 pages were substantively retrievable and control the modern account structure. No current reserve stock, exchange-rate level, import cover, intervention amount, debt ratio or unofficial answer key was added.",
    extra=[
        "basic/04_RBI-Monetary-Policy-and-Liquidity-Management.md",
        "advanced/04_RBI-Monetary-Policy-and-Liquidity-Management.md",
        "basic/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "advanced/20_Foreign-Trade-WTO-FTAs-and-Protectionism.md",
        "basic/21_IMF-World-Bank-ADB-AIIB-NDB-and-Global-Governance.md",
        "advanced/21_IMF-World-Bank-ADB-AIIB-NDB-and-Global-Governance.md",
    ],
)
