"""Authored data for Environment and Ecology learner-v2 Topics 25-28."""

from __future__ import annotations

import generate_environment_and_ecology_common as common
from environment_and_ecology_data_helpers import panel


def _topic_25() -> dict[str, object]:
    facts = [
        ("Capacity-generation boundary", "Installed capacity is nameplate power capability, while generation is electrical energy actually produced over time; neither capacity share nor capacity addition proves generation share or reliable supply."),
        ("Renewable-non-fossil boundary", "Solar, wind, hydro, biomass and geothermal are renewable sources, while non-fossil is a wider category that can include nuclear power; the two labels are not interchangeable."),
        ("Source-carrier boundary", "Renewable electricity is an energy source output, while hydrogen is an energy carrier produced using an input pathway; hydrogen is not a primary renewable resource by itself."),
        ("Variable-firm distinction", "Solar and wind output varies with resource availability, whereas dispatchable or firm supply can be scheduled or supported to meet demand; nameplate capacity alone does not establish firmness."),
        ("Integration chain", "A renewable-heavy power system links generation, forecasting, transmission, flexible demand, balancing resources and storage; adding generation without the rest can leave congestion or reliability constraints."),
        ("Storage boundary", "Battery and pumped-storage systems shift energy across time and provide grid services, but storage consumes previously generated energy and is not an independent primary energy source."),
        ("Target-achievement boundary", "A gross announced target, sanctioned project pipeline, installed capacity, commissioned capacity and achieved generation are separate statuses that require separate dated evidence."),
        ("Status-verb discipline", "Announced, approved, allocated, awarded, under construction, commissioned and producing describe different project stages; one stage must never be substituted for another."),
        ("Electrolysis pathway", "Electrolysis uses electricity to split water into hydrogen and oxygen; calling the product green depends on the electricity and accounting pathway, not on the chemical identity of hydrogen."),
        ("Label-standard-certification boundary", "A production pathway, a government definition or standard, a certification method and a market label are distinct layers; a pathway description alone does not prove certified compliance."),
        ("Hydrogen-colour boundary", "Grey, blue and green are shorthand for different production and emissions-management pathways; colour language does not replace a stated lifecycle boundary, capture performance or official standard."),
        ("Electricity-attribute boundary", "Claims about renewable electricity used for hydrogen may depend on sourcing, temporal matching, geography and additionality rules in the applicable standard; those attributes require documentary evidence."),
        ("Direct-electrification test", "Direct use of clean electricity is generally the first option where technically suitable, while hydrogen is considered where molecules, high-temperature heat, long-duration storage or weight constraints matter."),
        ("Hard-to-abate fit", "Fertiliser, refining, selected steel processes, shipping fuels and some heavy transport can use hydrogen or derivatives, but sector suitability and conversion losses must be assessed rather than assumed."),
        ("Derivative boundary", "Hydrogen, ammonia, methanol and synthetic fuels are related but different products with different conversion steps, handling requirements and end uses; a hydrogen target is not automatically a derivative-output target."),
        ("Water-context boundary", "Electrolysis requires water and upstream treatment, but project-level water stress depends on source, quality, location, competing demand and management; no universal water-impact value should be inferred."),
        ("Safety-and-logistics boundary", "Hydrogen production, compression, liquefaction, storage, pipelines, ports and end use create distinct engineering and safety requirements; production capacity does not prove delivered usable fuel."),
        ("Mission-target-outcome boundary", "A mission target expresses intended future scale, while allocation, manufacturing award, commissioning, output and emissions outcome are separate evidence stages."),
        ("SIGHT-dual-pillar boundary", "The SIGHT programme distinguishes support for electrolyser manufacturing from support for green-hydrogen production; manufacturing capability and hydrogen output are related but not identical."),
        ("Current evidence boundary", "Installed capacity, generation, project cost, mission target, achieved output, electrolyser scale, hydrogen classification and certification status require a dated MNRE, power-system or applicable standards source."),
    ]
    traps = [
        "Do not quote installed capacity as electricity generation.",
        "Do not merge renewable and non-fossil categories.",
        "Do not call hydrogen a primary renewable energy source.",
        "Do not treat variable nameplate capacity as firm supply.",
        "Do not omit transmission, flexibility and storage from integration.",
        "Do not call storage an independent source of energy.",
        "Do not merge target, pipeline, installation and generation.",
        "Do not rewrite awarded or allocated capacity as production.",
        "Do not call every electrolytic pathway green.",
        "Do not merge pathway, standard, label and certification.",
        "Do not use colour shorthand as a complete lifecycle assessment.",
        "Do not infer renewable attributes without the applicable rules.",
        "Do not prescribe hydrogen where direct electrification is preferable.",
        "Do not describe every sector as hard to abate.",
        "Do not merge hydrogen with ammonia or synthetic fuels.",
        "Do not invent a universal electrolyser water impact.",
        "Do not infer delivered fuel from production capacity.",
        "Do not turn an announced mission target into an outcome.",
        "Do not merge electrolyser manufacturing with hydrogen production.",
        "Do not invent capacity, generation, cost, target or certification values.",
    ]
    titles = [
        "Installed capacity generation and reliable supply",
        "Renewable and non-fossil source categories",
        "Variable renewables firmness and grid integration",
        "Transmission flexibility and storage chain",
        "Targets pipelines commissioning and generation",
        "Electrolysis and the hydrogen production pathway",
        "Green label standard and certification",
        "Grey blue and green lifecycle boundaries",
        "Renewable electricity attributes and additionality",
        "Direct electrification before hydrogen",
        "Hard-to-abate sector fit and conversion losses",
        "Hydrogen ammonia methanol and synthetic-fuel boundaries",
        "Water source treatment and local stress",
        "Safety storage transport and delivery",
        "Mission SIGHT evidence and current-data audit",
    ]
    routes = [
        "Open by separating installed capacity, generation and dependable supply.",
        "Classify renewable and non-fossil sources before using a target.",
        "Explain variability through forecasting, transmission, flexibility and storage.",
        "Separate an energy-shifting technology from a primary energy source.",
        "Use exact status verbs for target, sanction, construction, commission and output.",
        "Trace electricity, water, electrolysis and hydrogen without assuming a label.",
        "Identify the applicable definition, standard and certification evidence.",
        "Use lifecycle boundaries rather than colour shorthand alone.",
        "State sourcing, time, geography and additionality only when the rule owns them.",
        "Apply a direct-electrification-first screening test.",
        "Match hydrogen to a technically hard-to-abate use and disclose conversion loss.",
        "Track every derivative conversion and end-use boundary.",
        "Assess project water context rather than importing a universal figure.",
        "Carry the chain from production to safe delivered end use.",
        "Close with dated official target, award, commission, production and certification evidence.",
    ]
    panels = [
        panel("Power metric firewall", "comparison-table", [
            "INSTALLED CAPACITY -> nameplate power capability",
            "GENERATION -> electrical energy produced over time",
            "CAPACITY SHARE -> portfolio capability, not output share",
            "RELIABLE SUPPLY -> timing, flexibility and network matter",
            "RULE -> never convert megawatts into generation without evidence",
        ], [facts[0][0], facts[3][0]]),
        panel("Energy category map", "hierarchy", [
            "RENEWABLE -> solar wind hydro biomass geothermal",
            "NON-FOSSIL -> renewable sources plus other non-fossil sources",
            "ELECTRICITY -> generated energy output",
            "HYDROGEN -> manufactured energy carrier",
            "RULE -> source, output and carrier are different categories",
        ], [facts[1][0], facts[2][0]]),
        panel("Grid integration rail", "process-flow", [
            "VARIABLE GENERATION -> forecast resource-dependent output",
            "TRANSMISSION -> move power from resource to demand",
            "FLEXIBLE DEMAND AND BALANCING -> match system conditions",
            "STORAGE -> shift energy and provide selected services",
            "DELIVERY -> reliability is a system outcome",
        ], [facts[3][0], facts[4][0], facts[5][0]]),
        panel("Project status ladder", "hierarchy", [
            "TARGET OR ANNOUNCEMENT -> intended future scale",
            "ALLOCATION OR AWARD -> contractual or policy commitment",
            "CONSTRUCTION -> physical implementation stage",
            "COMMISSIONING -> asset enters service",
            "GENERATION OR PRODUCTION -> measured operating output",
        ], [facts[6][0], facts[7][0], facts[17][0]]),
        panel("Electrolysis pathway", "process-flow", [
            "ELECTRICITY SOURCE -> attribute must be evidenced",
            "WATER AND TREATMENT -> project-specific input context",
            "ELECTROLYSER -> water split into hydrogen and oxygen",
            "HYDROGEN OUTPUT -> chemical product",
            "GREEN CLAIM -> standard and certification layer still required",
        ], [facts[8][0], facts[9][0], facts[15][0]]),
        panel("Hydrogen claim stack", "layered-rail", [
            "PRODUCTION PATHWAY -> how hydrogen is made",
            "LIFECYCLE BOUNDARY -> included emissions stages",
            "OFFICIAL STANDARD -> qualifying conditions",
            "CERTIFICATION -> documented conformity",
            "MARKET LABEL -> cannot replace the layers below",
        ], [facts[9][0], facts[10][0], facts[11][0]]),
        panel("Use-case decision tree", "decision-tree", [
            "CAN CLEAN ELECTRICITY BE USED DIRECTLY -> prefer direct route",
            "MOLECULE OR HIGH HEAT NEEDED -> test hydrogen fit",
            "SECTOR AND DUTY CYCLE -> identify technical constraint",
            "CONVERSION LOSS AND INFRASTRUCTURE -> disclose trade-off",
            "VERDICT -> hydrogen is selective, not universal",
        ], [facts[12][0], facts[13][0]]),
        panel("Derivative conversion map", "process-flow", [
            "HYDROGEN -> base energy carrier and feedstock",
            "AMMONIA -> nitrogen-based derivative",
            "METHANOL OR SYNTHETIC FUEL -> carbon-containing derivative",
            "CONVERSION AND DELIVERY -> extra energy and infrastructure",
            "RULE -> product targets and outputs remain separate",
        ], [facts[14][0]]),
        panel("Water and site screen", "decision-tree", [
            "SOURCE -> freshwater treated water or other verified supply",
            "QUALITY -> pretreatment requirement",
            "LOCATION -> basin and local scarcity context",
            "COMPETING DEMAND -> ecological and social claims",
            "VERDICT -> project evidence, not a universal water number",
        ], [facts[15][0]]),
        panel("Hydrogen logistics chain", "causal-chain", [
            "PRODUCTION -> hydrogen leaves electrolyser",
            "CONDITIONING -> compression liquefaction or conversion",
            "STORAGE AND TRANSPORT -> vessel pipeline tanker or port",
            "END USE -> equipment and safety compatibility",
            "OUTCOME -> delivered service differs from production capacity",
        ], [facts[16][0]]),
        panel("Mission and SIGHT map", "comparison-table", [
            "MISSION TARGET -> intended future production scale",
            "SIGHT MANUFACTURING -> electrolyser capability support",
            "SIGHT PRODUCTION -> hydrogen output support",
            "COMMISSIONED OUTPUT -> later measured evidence",
            "CLIMATE OUTCOME -> separate lifecycle result",
        ], [facts[17][0], facts[18][0]]),
        panel("Energy-transition answer spine", "answer-spine", [
            "DEFINE -> capacity generation reliability source and carrier",
            "TRACE -> grid integration electrolysis certification and delivery",
            "SCREEN -> direct electrification before selective hydrogen use",
            "SEPARATE -> target award commission output and outcome",
            "VERIFY -> dated MNRE power-system and standards evidence",
        ], [facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2025", "GS-I", "Explain ecological and economic benefits of solar energy generation in India.", "Verified routed Mains demand; no current capacity or generation value is inferred.", [0, 3, 4, 6, 19]),
        common.make_pyq_solution(facts, "2025", "GS-III", "Explain how clean technology can support energy independence and the role of biotechnology.", "Verified routed Mains demand; this topic owns the renewable-grid-hydrogen half only.", [0, 1, 4, 12, 13, 17, 19]),
    ]
    return common.topic(
        25, "Renewable Energy and Green Hydrogen",
        "25_Renewable-Energy-and-Green-Hydrogen",
        "learning-sessions/v2/subject-wide-syllabus/environment-and-ecology-25_Learning-Session.md",
        facts, traps,
        [
            (10, "Distinguish renewable installed capacity, generation and reliable supply.", [0, 3, 4, 5]),
            (10, "Explain the electrolysis pathway and the evidence needed for a green-hydrogen claim.", [8, 9, 10, 11]),
            (15, "Assess grid integration requirements for variable renewable energy.", [0, 3, 4, 5, 6]),
            (15, "Explain why hydrogen should be targeted selectively at hard-to-abate uses.", [12, 13, 14, 16]),
            (20, "Evaluate the National Green Hydrogen Mission through target-to-outcome discipline.", [6, 7, 9, 17, 18, 19]),
            (20, "Design a sequenced renewable-electricity-to-green-hydrogen transition strategy.", [0, 1, 2, 4, 8, 12, 13, 15, 16, 19]),
        ],
        titles, routes, panels,
        [
            "installed capacity", "generation", "renewable", "non-fossil",
            "variable renewable energy", "dispatchable", "transmission", "storage",
            "target", "commissioned", "electrolysis", "green hydrogen",
            "standard", "certification", "lifecycle", "additionality",
            "direct electrification", "hard-to-abate", "ammonia", "water",
            "SIGHT", "electrolyser manufacturing",
        ],
        "Audited ledgers route renewable, solar, wind, grid, storage, bioenergy and hydrogen demands. No provisional objective key, installed-capacity value, generation figure, cost or achieved mission outcome is inferred.",
        pyqs,
        [
            "https://mnre.gov.in/en/national-green-hydrogen-mission/ — attempted 2026-09-03; substantive official text confirmed policy-enabling, infrastructure, standards, research, skills and governance components. The page was not used to convert an announced mission scale into achieved output.",
            "https://mnre.gov.in/en/physical-progress/ — attempted 2026-09-03; the official table was dated 31 July 2026 and clearly reported installed capacity. Its changing values were not imported, and installed capacity was not rewritten as generation.",
            "https://mnre.gov.in/en/green-hydrogen/ — attempted 2026-09-03; the route returned no additional substantive standard or certification text for use.",
            "https://powermin.gov.in/ — attempted 2026-09-03; no topic-specific dated generation, storage or reliability result was imported from the general route.",
        ],
        "MNRE supplied substantive mission architecture and a dated installed-capacity table. No installed-capacity, generation, cost, target-achievement, electrolyser, hydrogen-output, classification or certification value is asserted in the authored anchors.",
        extra=[
            "basic/17_Climate-Change-Science-Greenhouse-Effect.md",
            "basic/20_India-Climate-Policy-NAPCC-Panchamrit-LTLEDS.md",
            "basic/21_Carbon-Markets-CCUS-and-Direct-Air-Capture.md",
            "basic/05_IUCN-Red-List-and-Endemism.md",
            "advanced/20_India-Climate-Policy-NAPCC-Panchamrit-LTLEDS.md",
            "advanced/21_Carbon-Markets-CCUS-and-Direct-Air-Capture.md",
        ],
        pyq_audit_heading="AUDITED RENEWABLE, GRID, STORAGE, HYDROGEN AND ENERGY-INDEPENDENCE PYQ OWNERSHIP",
        register_headings=(
            "CAPACITY, GENERATION, GRID AND HYDROGEN PATHWAY MAP",
            "TARGET, STATUS, LABEL, CERTIFICATION AND USE-CASE TRAPS",
            "RENEWABLE-TO-HYDROGEN ANSWER SPINE",
            "LIVE CAPACITY, GENERATION, COST, TARGET, OUTPUT AND CERTIFICATION EVIDENCE BOUNDARY",
        ),
        register_answer_spine=[
            "SEPARATE INSTALLED CAPACITY GENERATION AND RELIABLE SUPPLY",
            "CLASSIFY RENEWABLE NON-FOSSIL ELECTRICITY SOURCE AND HYDROGEN CARRIER",
            "TRACE FORECASTING TRANSMISSION FLEXIBILITY STORAGE AND DELIVERY",
            "TRACE ELECTROLYSIS THEN STANDARD CERTIFICATION AND LIFECYCLE BOUNDARY",
            "APPLY DIRECT-ELECTRIFICATION-FIRST AND HARD-TO-ABATE FIT",
            "SEPARATE TARGET AWARD COMMISSION PRODUCTION AND CLIMATE OUTCOME",
            "CONCLUDE WITH DATED MNRE POWER-SYSTEM AND STANDARD EVIDENCE",
        ],
        allow_existing_history=True,
    )


def _topic_26() -> dict[str, object]:
    facts = [
        ("Hazard boundary", "A hazard is a potentially damaging process, phenomenon or human activity; it is not the same as a disaster or the complete measure of risk."),
        ("Exposure boundary", "Exposure identifies people, infrastructure, livelihoods, ecosystems and assets located where hazards may occur; it does not describe their susceptibility."),
        ("Vulnerability boundary", "Vulnerability is the set of physical, social, economic and environmental conditions that increase susceptibility to harm; it is distinct from exposure."),
        ("Capacity boundary", "Capacity comprises strengths, resources, institutions and abilities available to manage and reduce risk; low capacity can magnify vulnerability and losses."),
        ("Risk relation", "Disaster risk emerges from the interaction of hazard, exposure, vulnerability and capacity across a stated place and time; it cannot be inferred from hazard intensity alone."),
        ("Disaster boundary", "A disaster is serious disruption and loss that exceeds or severely tests the affected community's ability to cope; a hazard event need not become a disaster."),
        ("Prevention-mitigation distinction", "Prevention seeks to avoid existing and new disaster risk where possible, while mitigation reduces adverse impacts where risk cannot be fully prevented."),
        ("Preparedness boundary", "Preparedness develops knowledge, plans, warnings, training, stocks and coordination for effective action before an event; it is not post-event response."),
        ("Response boundary", "Response covers immediate and short-term actions to save lives, protect health and meet basic needs during or just after a disaster."),
        ("Recovery boundary", "Recovery restores and improves livelihoods, systems and assets after emergency response, while rehabilitation and reconstruction are related but distinct components."),
        ("Build-Back-Better boundary", "Build Back Better uses recovery, rehabilitation and reconstruction to reduce future risk rather than merely recreate pre-disaster vulnerability."),
        ("Cycle-continuum boundary", "Prevention, mitigation, preparedness, response and recovery are linked phases with feedback; disaster management is not a linear one-time sequence."),
        ("Domestic-law boundary", "India's Disaster Management Act creates domestic legal and institutional duties; it must not be treated as the legal implementation text of the Sendai Framework."),
        ("NDMA-NEC boundary", "NDMA is the national authority for policy and guidelines, while the National Executive Committee supports coordination, implementation and national planning under the domestic framework."),
        ("NIDM-NDRF boundary", "NIDM focuses on training, research and capacity development, while NDRF is a specialised response force; neither should be substituted for the other."),
        ("State-district boundary", "SDMA and DDMA operate at state and district levels within domestic law; their plans and implementation roles must be attributed to the applicable statutory text."),
        ("Sendai identity", "The Sendai Framework 2015-2030 is a global, voluntary and non-binding disaster-risk-reduction framework, not a domestic statute or operational response agency."),
        ("Priorities-targets boundary", "Sendai has four priorities for action and seven global targets; the priorities describe fields of action, while the targets describe global reduction or increase directions."),
        ("Global-domestic boundary", "Sendai's global targets guide international monitoring, while Indian institutions, plans, funds and legal powers arise from domestic law and policy; alignment does not erase this distinction."),
        ("Current evidence boundary", "Disaster losses, mortality, affected people, target progress, indicators, warning coverage, institutional powers and plan status require dated official NDMA, India Code, UNDRR or sector-agency evidence."),
    ]
    traps = [
        "Do not merge hazard with disaster.",
        "Do not merge exposure with vulnerability.",
        "Do not omit capacity from a risk analysis.",
        "Do not infer risk from hazard intensity alone.",
        "Do not call every hazard event a disaster.",
        "Do not merge prevention with mitigation.",
        "Do not call preparedness a response activity.",
        "Do not call emergency response long-term recovery.",
        "Do not reduce recovery to rebuilding identical assets.",
        "Do not make the disaster cycle a one-way sequence.",
        "Do not derive domestic legal powers from Sendai.",
        "Do not merge NDMA with NEC.",
        "Do not merge NIDM training with NDRF operations.",
        "Do not move national roles automatically to a DDMA.",
        "Do not call Sendai a binding treaty.",
        "Do not replace four priorities with seven targets.",
        "Do not replace seven global targets with four priorities.",
        "Do not equate global monitoring with domestic enforcement.",
        "Do not invent losses, indicators or institutional powers.",
        "Do not state a current plan or amendment status without dated official text.",
    ]
    titles = [
        "Hazard exposure vulnerability capacity and risk",
        "Hazard event disaster and coping threshold",
        "Prevention and mitigation",
        "Preparedness and early action",
        "Response and immediate needs",
        "Recovery rehabilitation and reconstruction",
        "Build Back Better and risk feedback",
        "Continuous disaster-management cycle",
        "Disaster Management Act domestic architecture",
        "NDMA and National Executive Committee",
        "NIDM NDRF and operational boundaries",
        "SDMA DDMA and jurisdictional scale",
        "Sendai identity and four priorities",
        "Seven global targets and monitoring boundary",
        "Sendai domestic alignment and current evidence audit",
    ]
    routes = [
        "Define risk through hazard, exposure, vulnerability and capacity.",
        "Show why an event becomes a disaster only through disruption and coping limits.",
        "Separate avoiding risk from reducing unavoidable impact.",
        "Place warnings, plans, drills and readiness before the event.",
        "Confine response to immediate life-saving and basic-needs action.",
        "Separate recovery, rehabilitation and reconstruction before applying Build Back Better.",
        "Use recovery to reduce future risk rather than reproduce vulnerability.",
        "Link every phase through feedback rather than a one-way cycle.",
        "Anchor domestic roles in the Disaster Management Act.",
        "Differentiate policy authority from executive coordination.",
        "Differentiate training and research from specialised response operations.",
        "Attribute state and district roles only to their owned jurisdiction.",
        "State Sendai's global non-binding identity before its priorities.",
        "List global targets separately from action priorities.",
        "Close with dated domestic law, plan, indicator and UNDRR evidence.",
    ]
    panels = [
        panel("Disaster-risk equation", "causal-chain", [
            "HAZARD -> potentially damaging process or event",
            "EXPOSURE -> people assets systems in harm's way",
            "VULNERABILITY -> susceptibility to damage",
            "CAPACITY -> resources and ability to manage risk",
            "RISK -> interaction across a stated place and time",
        ], [facts[0][0], facts[1][0], facts[2][0], facts[3][0], facts[4][0]]),
        panel("Hazard-to-disaster threshold", "decision-tree", [
            "HAZARD OCCURS -> physical or human-induced event",
            "EXPOSED SYSTEM -> contact with people assets or ecosystems",
            "VULNERABILITY AND LOW CAPACITY -> losses amplify",
            "COPING ABILITY SEVERELY TESTED -> serious disruption",
            "DISASTER -> not every hazard crosses this threshold",
        ], [facts[5][0]]),
        panel("Risk-reduction ladder", "hierarchy", [
            "PREVENTION -> avoid creation or existence of risk where possible",
            "MITIGATION -> reduce adverse impact of remaining risk",
            "PREPAREDNESS -> ready plans warnings skills and resources",
            "RESPONSE -> immediate life-saving and basic needs",
            "RECOVERY -> restore and improve while reducing future risk",
        ], [facts[6][0], facts[7][0], facts[8][0], facts[9][0]]),
        panel("Build Back Better loop", "process-flow", [
            "DAMAGE AND NEEDS ASSESSMENT -> establish recovery baseline",
            "REHABILITATION -> restore essential functions",
            "RECONSTRUCTION -> rebuild assets and systems",
            "RISK-INFORMED IMPROVEMENT -> avoid old vulnerability",
            "FEEDBACK -> prevention mitigation and preparedness improve",
        ], [facts[10][0], facts[11][0]]),
        panel("Domestic architecture firewall", "hierarchy", [
            "DISASTER MANAGEMENT ACT -> domestic legal base",
            "NDMA -> national policy and guidelines",
            "NEC -> executive coordination and implementation support",
            "SDMA AND DDMA -> state and district statutory levels",
            "RULE -> roles come from domestic law, not Sendai text",
        ], [facts[12][0], facts[13][0], facts[15][0]]),
        panel("Training-response split", "comparison-table", [
            "NIDM -> training research documentation capacity development",
            "NDRF -> specialised disaster response operations",
            "NDMA -> policy and guidance",
            "DDMA -> district planning and implementation context",
            "RULE -> institution type determines the answer",
        ], [facts[14][0], facts[15][0]]),
        panel("Sendai identity card", "comparison-table", [
            "PERIOD -> 2015 to 2030",
            "NATURE -> global voluntary non-binding framework",
            "PURPOSE -> prevent new and reduce existing disaster risk",
            "SCOPE -> people livelihoods health assets and systems",
            "NOT -> Indian statute fund or response force",
        ], [facts[16][0]]),
        panel("Four priorities rail", "process-flow", [
            "PRIORITY 1 -> understand disaster risk",
            "PRIORITY 2 -> strengthen risk governance",
            "PRIORITY 3 -> invest in resilience",
            "PRIORITY 4 -> preparedness response and Build Back Better",
            "RULE -> fields of action, not the seven global targets",
        ], [facts[17][0]]),
        panel("Seven-target logic", "comparison-table", [
            "TARGETS A TO D -> substantially reduce specified losses",
            "MORTALITY AND AFFECTED PEOPLE -> human impact directions",
            "ECONOMIC AND CRITICAL-SERVICE LOSS -> system impact directions",
            "TARGETS E TO G -> substantially increase strategies cooperation warnings",
            "RULE -> indicator values require official monitoring metadata",
        ], [facts[17][0], facts[18][0]]),
        panel("Global-domestic bridge", "layered-rail", [
            "SENDAI -> global principles priorities and targets",
            "INDIAN LAW -> authorities powers duties and funds",
            "NATIONAL AND STATE PLANS -> domestic implementation choices",
            "SECTOR AGENCIES -> warnings infrastructure health and relief",
            "ALIGNMENT -> policy bridge, not legal identity",
        ], [facts[12][0], facts[18][0]]),
        panel("Evidence status screen", "decision-tree", [
            "LOSS FIGURE -> event date definition and reporting source",
            "TARGET PROGRESS -> indicator baseline and period",
            "EARLY WARNING -> hazard geography reach and access",
            "INSTITUTIONAL POWER -> current statutory provision",
            "PLAN STATUS -> dated official edition or amendment",
        ], [facts[19][0]]),
        panel("Disaster answer spine", "answer-spine", [
            "DEFINE -> hazard exposure vulnerability capacity risk and disaster",
            "SEQUENCE -> prevention mitigation preparedness response recovery",
            "MAP -> NDMA NEC NIDM NDRF SDMA and DDMA by owned role",
            "SEPARATE -> four Sendai priorities from seven global targets",
            "VERIFY -> domestic law plan loss indicator and warning evidence",
        ], [facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2024", "GS-III", "Define disaster resilience, explain its determination and elements, and mention Sendai global targets.", "Verified direct Mains demand; four priorities are not substituted for seven targets.", [0, 1, 2, 3, 4, 10, 17, 18]),
        common.make_pyq_solution(facts, "2024", "GS-III", "Discuss causes, cases and policy frameworks for urban flooding in India.", "Verified direct Mains demand; no disaster-loss value is inferred.", [0, 1, 2, 3, 4, 6, 7, 12, 15, 19]),
    ]
    return common.topic(
        26, "Disaster Management Framework and Sendai",
        "26_Disaster-Management-Framework-and-Sendai",
        "learning-sessions/v2/subject-wide-syllabus/environment-and-ecology-26_Learning-Session.md",
        facts, traps,
        [
            (10, "Distinguish hazard, exposure, vulnerability, capacity, risk and disaster.", [0, 1, 2, 3, 4, 5]),
            (10, "Explain prevention, mitigation and preparedness as distinct phases.", [6, 7, 11]),
            (15, "Explain response, recovery and Build Back Better.", [8, 9, 10, 11]),
            (15, "Map NDMA, NEC, NIDM, NDRF, SDMA and DDMA by role.", [12, 13, 14, 15]),
            (20, "Compare Sendai's global framework with India's domestic legal architecture.", [12, 13, 15, 16, 17, 18]),
            (20, "Design a risk-reduction framework using the full disaster-management continuum.", [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 19]),
        ],
        titles, routes, panels,
        [
            "hazard", "exposure", "vulnerability", "capacity", "disaster risk",
            "prevention", "mitigation", "preparedness", "response", "recovery",
            "Build Back Better", "Disaster Management Act", "NDMA",
            "National Executive Committee", "NIDM", "NDRF", "SDMA", "DDMA",
            "Sendai Framework", "four priorities", "seven global targets",
        ],
        "Audited ledgers route the verified 2024 resilience, Sendai-target and urban-flood demands plus related disaster-management questions. No objective key, loss figure, target progress or official model answer is inferred.",
        pyqs,
        [
            "https://www.undrr.org/publication/sendai-framework-disaster-risk-reduction-2015-2030 — attempted 2026-09-03; substantive official text confirmed four priorities, seven targets, adoption context and the Build Back Better wording.",
            "https://nidm.gov.in/DMAct.asp — attempted 2026-09-03; the fetched route returned only contact information, so no statutory role, amendment or section claim was imported.",
            "https://ndma.gov.in/Governance/DM-Act-2005 — attempted 2026-09-03; the official route returned HTTP 404, so no current Act or institutional wording was imported.",
            "https://ndma.gov.in/ — attempted 2026-09-03; no dated plan revision, disaster loss, warning-coverage value or institutional outcome was imported from the general route.",
        ],
        "UNDRR supplied substantive Sendai framework text. Indian official routes did not yield substantive current legal or plan text in this check, so no disaster loss, target progress, indicator, warning coverage, amended power or plan-status claim is asserted.",
        extra=[
            "basic/01_Ecosystem-Structure-and-Function.md",
            "basic/07_Biosphere-Reserves-and-Ramsar-Sites.md",
            "basic/17_Climate-Change-Science-Greenhouse-Effect.md",
            "basic/24_Coastal-and-Marine-Ecology-CRZ-Blue-Economy.md",
            "advanced/07_Biosphere-Reserves-and-Ramsar-Sites.md",
            "advanced/24_Coastal-and-Marine-Ecology-CRZ-Blue-Economy.md",
        ],
        pyq_audit_heading="AUDITED DISASTER RISK, RESILIENCE, SENDAI AND URBAN-FLOOD PYQ OWNERSHIP",
        register_headings=(
            "HAZARD, EXPOSURE, VULNERABILITY, CAPACITY AND CYCLE MAP",
            "PHASE, INSTITUTION, PRIORITY, TARGET AND JURISDICTION TRAPS",
            "DISASTER-RISK-REDUCTION ANSWER SPINE",
            "LIVE LAW, PLAN, LOSS, INDICATOR, WARNING AND TARGET EVIDENCE BOUNDARY",
        ),
        register_answer_spine=[
            "DEFINE HAZARD EXPOSURE VULNERABILITY CAPACITY RISK AND DISASTER",
            "SEPARATE PREVENTION MITIGATION PREPAREDNESS RESPONSE AND RECOVERY",
            "USE BUILD BACK BETTER TO REDUCE FUTURE RISK",
            "MAP NDMA NEC NIDM NDRF SDMA AND DDMA ONLY BY OWNED ROLE",
            "SEPARATE SENDAI FOUR PRIORITIES FROM SEVEN GLOBAL TARGETS",
            "SEPARATE GLOBAL FRAMEWORK FROM DOMESTIC LAW INSTITUTIONS AND FUNDS",
            "CONCLUDE WITH DATED LAW PLAN LOSS INDICATOR AND WARNING EVIDENCE",
        ],
        allow_existing_history=True,
    )


def _topic_27() -> dict[str, object]:
    facts = [
        ("Institution-type boundary", "A ministry, statutory board, statutory authority, notified authority, research institute, enforcement body and tribunal have different legal identities, outputs and accountability channels."),
        ("MoEFCC ministry role", "MoEFCC is a Union ministry responsible for policy, administration and coordination across environment, forests and climate matters; it is not the field regulator for every consent or offence."),
        ("CPCB statutory identity", "CPCB is a statutory pollution-control board under the water and air pollution-control framework; its national functions differ from a ministry's policy role."),
        ("CPCB national function", "CPCB advises, coordinates State Boards, provides technical support, compiles data and lays down or modifies specified standards at national level within its legal mandate."),
        ("SPCB consent-enforcement role", "SPCBs and Pollution Control Committees perform state or Union Territory implementation functions, including applicable consent, inspection and enforcement tasks under the governing law."),
        ("Standards-consent boundary", "National standard-setting and coordination by CPCB are distinct from project-specific consent and local enforcement by the relevant State Board or Committee."),
        ("Central-state jurisdiction boundary", "Pollution governance distributes functions across central and state institutions; a central standard does not erase state implementation, and state consent does not create a national standard."),
        ("NBA statutory identity", "The National Biodiversity Authority is a statutory biodiversity body; its access and benefit-sharing role is not pollution control, wildlife-crime enforcement or environmental clearance."),
        ("SBB role boundary", "State Biodiversity Boards operate at the state level within the biodiversity governance framework; their role must not be transferred automatically to NBA or a local committee."),
        ("BMC local role", "Biodiversity Management Committees operate at the local-body level and support local biodiversity documentation and governance; they are not central licensing authorities."),
        ("PBR evidence boundary", "A People's Biodiversity Register is a local documentation instrument and knowledge record; its preparation does not itself grant access approval, determine ownership or prove benefit sharing."),
        ("ABS boundary", "Access and Benefit Sharing links access to biological resources or associated knowledge with fair benefit arrangements under the applicable law; it is not a general wildlife-protection or pollution penalty."),
        ("WII institutional identity", "The Wildlife Institute of India is a research, training and advisory institution in wildlife science and management; it is not a statutory environmental regulator."),
        ("Science-regulation boundary", "WII research can inform policy, management or adjudication, but evidence generation is distinct from granting consent, issuing a notification or enforcing an offence."),
        ("Evidence-decision chain", "Scientific surveys, monitoring and expert studies are inputs; the competent legal authority retains responsibility for the formal regulatory, administrative or judicial decision."),
        ("NTCA-WCCB boundary", "Tiger-conservation authority functions and wildlife-crime coordination are distinct from WII research and from CPCB pollution regulation; similar subject matter does not make mandates interchangeable."),
        ("NGT adjudication boundary", "The National Green Tribunal adjudicates matters within its statutory jurisdiction; it does not replace the ministry, pollution boards, biodiversity authorities or research institutes."),
        ("Constituted-delegated boundary", "A body created by statute, an authority constituted under a parent Act, a delegated administrative arrangement and a research society must be identified by their actual legal basis."),
        ("Coordination chain", "Effective environmental governance links policy, science, standards, consent, monitoring, enforcement and adjudication while preserving the competent actor at every stage."),
        ("Current evidence boundary", "Institutional mandates, powers, jurisdiction, budgets, staffing, directions and current reforms require dated Acts, rules, notifications, annual reports or official institutional pages."),
    ]
    traps = [
        "Do not call every environmental body a regulator.",
        "Do not make MoEFCC the direct consent authority in every case.",
        "Do not call CPCB a ministry.",
        "Do not transfer CPCB national functions to every SPCB.",
        "Do not transfer SPCB consent powers to CPCB without legal basis.",
        "Do not merge standards with consent.",
        "Do not erase central-state jurisdiction.",
        "Do not merge NBA with pollution control.",
        "Do not merge NBA, SBB and BMC levels.",
        "Do not call a BMC a central licensing body.",
        "Do not treat a PBR as an access approval.",
        "Do not merge ABS with wildlife-crime enforcement.",
        "Do not call WII a regulator.",
        "Do not let a scientific recommendation become a legal order.",
        "Do not transfer decision responsibility to an evidence provider.",
        "Do not merge NTCA, WCCB, WII and CPCB.",
        "Do not call NGT an executive regulator.",
        "Do not state statutory status without the founding instrument.",
        "Do not use coordination to blur accountability.",
        "Do not invent mandates, powers, budgets, staffing or directions.",
    ]
    titles = [
        "Institution types legal identity and accountability",
        "MoEFCC ministry policy and coordination",
        "CPCB statutory identity and national functions",
        "CPCB standards and State Board coordination",
        "SPCB consent inspection and enforcement",
        "Central and state jurisdiction firewall",
        "NBA access and benefit-sharing identity",
        "NBA SBB and BMC three-level map",
        "People's Biodiversity Registers and evidence",
        "Access and Benefit Sharing mechanism",
        "WII research training and advisory role",
        "Science input and competent legal decision",
        "NTCA WCCB WII and CPCB comparison",
        "NGT adjudication and institutional interaction",
        "Coordination chain and current mandate audit",
    ]
    routes = [
        "Begin with legal identity before describing subject matter.",
        "Place MoEFCC at policy and coordination level without universalising field power.",
        "State CPCB's statutory national functions from official text.",
        "Separate standard-setting and coordination from state consent.",
        "Place inspection, consent and enforcement at the competent state or UT body.",
        "Map central and state jurisdiction explicitly.",
        "Define NBA through biodiversity access and benefit sharing.",
        "Keep NBA, SBB and BMC at their owned governance levels.",
        "Treat a PBR as documentation, not approval or ownership proof.",
        "Explain ABS without importing pollution or wildlife-crime powers.",
        "Define WII as research, training and advisory support.",
        "Separate expert evidence from the formal decision.",
        "Compare bodies by Act, institutional type, scale and output.",
        "Place NGT as adjudicator rather than executive administrator.",
        "Close with dated legal instruments, official mandates and accountable coordination.",
    ]
    panels = [
        panel("Institution-type compass", "comparison-table", [
            "MINISTRY -> policy administration and coordination",
            "STATUTORY BOARD OR AUTHORITY -> Act-defined functions",
            "RESEARCH INSTITUTE -> evidence training and advisory work",
            "ENFORCEMENT BODY -> investigation or operational compliance role",
            "TRIBUNAL -> adjudication within statutory jurisdiction",
        ], [facts[0][0]]),
        panel("MoEFCC role map", "hierarchy", [
            "UNION MINISTRY -> executive policy institution",
            "LAW AND RULE ADMINISTRATION -> subject to statutory allocation",
            "PROGRAMME AND INTERNATIONAL COORDINATION -> ministry function",
            "SUBORDINATE OR AUTONOMOUS BODIES -> separate legal identities",
            "RULE -> ministry is not every field regulator",
        ], [facts[1][0]]),
        panel("CPCB national rail", "process-flow", [
            "ADVISE CENTRAL GOVERNMENT -> national policy input",
            "COORDINATE STATE BOARDS -> inter-board function",
            "TECHNICAL SUPPORT AND RESEARCH -> capacity and evidence",
            "DATA GUIDELINES AND STANDARDS -> national outputs",
            "IMPLEMENTATION -> relevant State Board or Committee remains distinct",
        ], [facts[2][0], facts[3][0], facts[4][0]]),
        panel("Standards-consent firewall", "comparison-table", [
            "CPCB STANDARD OR GUIDELINE -> national regulatory benchmark",
            "SPCB OR PCC CONSENT -> project-specific permission context",
            "INSPECTION AND ENFORCEMENT -> competent territorial authority",
            "CENTRAL DIRECTION OR COORDINATION -> separate legal route",
            "RULE -> one output cannot be substituted for another",
        ], [facts[5][0], facts[6][0]]),
        panel("Biodiversity governance ladder", "hierarchy", [
            "NBA -> national biodiversity authority level",
            "SBB -> state biodiversity governance level",
            "BMC -> local-body biodiversity level",
            "PBR -> local documentation instrument",
            "ABS -> access and fair-benefit mechanism",
        ], [facts[7][0], facts[8][0], facts[9][0], facts[10][0], facts[11][0]]),
        panel("PBR-to-ABS sequence", "process-flow", [
            "LOCAL KNOWLEDGE AND BIODIVERSITY -> documented carefully",
            "PBR -> evidence and community knowledge record",
            "ACCESS PROPOSAL -> separate legal assessment",
            "BENEFIT ARRANGEMENT -> applicable ABS process",
            "OUTCOME -> documentation alone grants no approval",
        ], [facts[10][0], facts[11][0]]),
        panel("WII science pipeline", "process-flow", [
            "RESEARCH QUESTION -> species habitat or management issue",
            "FIELD AND ANALYTICAL STUDY -> evidence generated",
            "TRAINING AND ADVISORY OUTPUT -> capacity and recommendations",
            "COMPETENT AUTHORITY -> formal decision under law",
            "RULE -> science informs but does not become regulation itself",
        ], [facts[12][0], facts[13][0], facts[14][0]]),
        panel("Wildlife body comparison", "comparison-table", [
            "WII -> research training and advisory science",
            "NTCA -> tiger-conservation statutory authority",
            "WCCB -> wildlife-crime coordination",
            "STATE WILDLIFE MACHINERY -> territorial implementation",
            "CPCB -> pollution control, not wildlife governance",
        ], [facts[15][0]]),
        panel("Adjudication boundary", "hierarchy", [
            "ADMINISTRATIVE DECISION -> ministry authority board or state body",
            "MONITORING OR ENFORCEMENT -> competent executive institution",
            "CHALLENGE OR DISPUTE -> applicable adjudicatory route",
            "NGT -> tribunal within its statutory jurisdiction",
            "RULE -> adjudication does not erase executive responsibility",
        ], [facts[16][0]]),
        panel("Legal-basis test", "decision-tree", [
            "CREATED DIRECTLY BY ACT -> statutory body",
            "CONSTITUTED UNDER PARENT ACT -> notified authority",
            "DELEGATED POWER -> scope follows delegation",
            "AUTONOMOUS OR RESEARCH BODY -> institutional mandate",
            "VERDICT -> cite the exact founding instrument",
        ], [facts[17][0]]),
        panel("Governance coordination chain", "causal-chain", [
            "POLICY -> sets direction",
            "SCIENCE -> supplies evidence",
            "STANDARD AND CONSENT -> regulate activity",
            "MONITORING AND ENFORCEMENT -> test compliance",
            "ADJUDICATION -> resolves qualifying disputes",
        ], [facts[18][0]]),
        panel("Institutions answer spine", "answer-spine", [
            "IDENTIFY -> ministry board authority institute force or tribunal",
            "CITE -> founding Act notification delegation or mandate",
            "MAP -> national state and local jurisdiction",
            "SEPARATE -> standards consent science enforcement and adjudication",
            "VERIFY -> current power direction staffing budget and reform evidence",
        ], [facts[19][0]]),
    ]
    return common.topic(
        27, "Environmental Institutions (MoEFCC, CPCB, NBA, WII)",
        "27_Environmental-Institutions-MoEFCC-CPCB-NBA-WII",
        "learning-sessions/v2/subject-wide-syllabus/environment-and-ecology-27_Learning-Session.md",
        facts, traps,
        [
            (10, "Distinguish a ministry, statutory regulator and research institute.", [0, 1, 2, 12]),
            (10, "Distinguish CPCB national functions from SPCB consent and enforcement.", [2, 3, 4, 5, 6]),
            (15, "Explain the NBA-SBB-BMC biodiversity governance structure.", [7, 8, 9, 10, 11]),
            (15, "Explain how WII research informs but does not replace regulation.", [12, 13, 14, 15]),
            (20, "Map India's environmental institutions by legal basis, scale and function.", [0, 1, 2, 4, 7, 8, 9, 12, 15, 16, 17]),
            (20, "Evaluate coordination and accountability across policy, science, regulation, enforcement and adjudication.", [5, 6, 14, 16, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "ministry", "statutory board", "statutory authority", "MoEFCC",
            "CPCB", "State Pollution Control Board", "standards", "consent",
            "enforcement", "central", "state", "National Biodiversity Authority",
            "State Biodiversity Board", "Biodiversity Management Committee",
            "People's Biodiversity Register", "Access and Benefit Sharing",
            "Wildlife Institute of India", "research", "training", "regulator",
            "National Green Tribunal",
        ],
        "Audited ledgers route institution-matching and legal-basis concepts, including unkeyed or provisionally keyed objective demands. No objective answer, statutory power, mandate update or budget is inferred.",
        [],
        [
            "https://cpcb.nic.in/functions/ — attempted 2026-09-03; redirected substantive official text listed CPCB advice, national planning, State Board coordination, technical support, data and standards functions, and separately described Union Territory functions.",
            "https://wii.gov.in/about_wii — attempted 2026-09-03; redirected substantive official text identified WII as a national research and training institution in wildlife conservation with academic and advisory functions.",
            "https://nbaindia.org/content/16/14/1/introduction.html — attempted 2026-09-03; redirected to a content-managed homepage stub, so no current NBA mandate, power or procedure was imported.",
            "https://moef.gov.in/about-the-ministry — attempted 2026-09-03; the route returned HTTP 404, so no current ministry mandate text was imported.",
            "https://moef.gov.in/ — attempted 2026-09-03; the fetched page exposed an unrelated recruitment notice, so no institutional reform, power or budget claim was imported.",
        ],
        "CPCB and WII pages supplied substantive role text. NBA and MoEFCC routes were stubbed, missing or unrelated; therefore no new statutory mandate, power, jurisdiction, budget, staffing, direction or reform claim is asserted.",
        extra=[
            "basic/05_IUCN-Red-List-and-Endemism.md",
            "basic/08_Wildlife-Protection-Act-and-Schedules.md",
            "basic/13_Air-Pollution-and-CPCB-Standards.md",
            "basic/16_Environmental-Impact-Assessment-and-NGT.md",
            "advanced/13_Air-Pollution-and-CPCB-Standards.md",
            "advanced/16_Environmental-Impact-Assessment-and-NGT.md",
        ],
        pyq_audit_heading="AUDITED ENVIRONMENTAL-INSTITUTION, LEGAL-BASIS AND MANDATE PYQ OWNERSHIP",
        register_headings=(
            "MINISTRY, BOARD, AUTHORITY, INSTITUTE AND TRIBUNAL MAP",
            "LEGAL-BASIS, JURISDICTION, STANDARD, CONSENT AND SCIENCE TRAPS",
            "ENVIRONMENTAL-INSTITUTIONS ANSWER SPINE",
            "LIVE MANDATE, POWER, JURISDICTION, BUDGET AND REFORM EVIDENCE BOUNDARY",
        ),
        register_answer_spine=[
            "IDENTIFY INSTITUTION TYPE BEFORE SUBJECT MATTER",
            "CITE THE FOUNDING ACT NOTIFICATION DELEGATION OR OFFICIAL MANDATE",
            "SEPARATE MOEFCC POLICY FROM CPCB COORDINATION AND SPCB CONSENT ENFORCEMENT",
            "SEPARATE NBA SBB BMC PBR AND ABS ROLES",
            "KEEP WII RESEARCH TRAINING AND ADVISORY WORK DISTINCT FROM REGULATION",
            "MAP SCIENCE STANDARD CONSENT ENFORCEMENT AND ADJUDICATION",
            "CONCLUDE WITH DATED MANDATE POWER JURISDICTION AND CAPACITY EVIDENCE",
        ],
        allow_existing_history=True,
    )


def _topic_28() -> dict[str, object]:
    facts = [
        ("Tracker-record boundary", "A species current-affairs record must contain the taxon, claim type, source, publication or assessment date, status verb, verification date and static-topic link; a headline alone is not a record."),
        ("Taxonomic-identity boundary", "Scientific name, author-accepted taxon and taxonomic rank identify the organism; a common name may refer to more than one taxon or vary by region."),
        ("Species-subspecies boundary", "Species, subspecies, population and regional assessment are different units; a claim about one unit must not be transferred to another."),
        ("Common-name boundary", "A vernacular or media name is a discovery aid, not sufficient identity evidence; the verified scientific name should anchor the tracker entry."),
        ("IUCN-assessment boundary", "An IUCN Red List category is an assessment outcome for a stated taxon, geographic scope and assessment version or date; it is not a domestic legal listing."),
        ("IUCN-date boundary", "A Red List category can become stale when reassessed; every status claim should carry the cited assessment or publication date and be rechecked before reuse."),
        ("WPA-legal boundary", "A Wildlife (Protection) Act schedule entry is a domestic legal classification under the applicable Act and amendment, not an IUCN extinction-risk category."),
        ("CITES-listing boundary", "A CITES Appendix listing governs international trade through the Convention's permit system; it does not by itself state IUCN risk or domestic protection schedule."),
        ("CMS-listing boundary", "A CMS Appendix or agreement concerns migratory-species conservation and cooperation; migratory status, Appendix listing and a separate instrument must be recorded distinctly."),
        ("Endemic-native boundary", "Endemic means naturally restricted to a defined geographic area, while native means naturally occurring there but possibly elsewhere; neither is inferred from cultural prominence or a single sighting."),
        ("Range-record boundary", "A verified range is built from accepted occurrence and distribution evidence; a sighting outside a familiar area may be a record requiring validation, not immediate proof of a stable expanded range."),
        ("Habitat-range boundary", "Habitat association describes ecological use, while geographic range describes distribution; an organism using a habitat type is not necessarily present everywhere that habitat occurs."),
        ("Population-status boundary", "Population size, trend, subpopulation structure and extinction-risk category are distinct claims with different evidence and dates; one cannot be inferred from another."),
        ("Trigger-static boundary", "A verified current trigger such as a dated assessment, notification, conference decision, survey or rediscovery must be separated from the static taxonomy, ecology and legal framework it illustrates."),
        ("News-notification boundary", "A press report or announcement can flag an event, but a legal listing or designation claim requires the applicable official notification, decision or authoritative database entry."),
        ("Status-verb boundary", "Observed, reported, assessed, listed, notified, proposed, adopted and entered into force describe different evidence states; tracker wording must preserve the source's verb."),
        ("Rediscovery boundary", "A rediscovery or new locality record does not automatically change IUCN status, legal schedule, CITES or CMS listing, total range or population trend."),
        ("Cross-source reconciliation", "IUCN, domestic law, CITES, CMS and taxonomic databases answer different questions and can show different dates without contradiction; reconcile by claim type rather than choosing one universal status."),
        ("Stale-current firewall", "Every dated entry should display an as-of or verification date and a recheck trigger; undated words such as current, latest or recently should be avoided in reusable notes."),
        ("Current evidence boundary", "Species status, range, population, legal schedule, CITES or CMS listing and news trigger require dated official or authoritative source evidence; failed checks and omitted claims must be recorded honestly."),
    ]
    traps = [
        "Do not use a headline as a tracker record.",
        "Do not rely on a common name for taxonomic identity.",
        "Do not merge species, subspecies and populations.",
        "Do not transfer a claim between taxa sharing a common name.",
        "Do not call IUCN status a domestic legal schedule.",
        "Do not cite an IUCN category without an assessment date.",
        "Do not call a WPA schedule an extinction-risk assessment.",
        "Do not call a CITES Appendix an IUCN category.",
        "Do not merge CMS migratory status with every international listing.",
        "Do not infer endemism from prominence or one location.",
        "Do not infer stable range expansion from one sighting.",
        "Do not merge habitat association with geographic range.",
        "Do not infer population trend from risk category.",
        "Do not merge a dated trigger with the static anchor.",
        "Do not rewrite a news report as a legal notification.",
        "Do not change the source's status verb.",
        "Do not turn rediscovery into automatic status change.",
        "Do not seek one universal status across unlike systems.",
        "Do not use stale-current language without an as-of date.",
        "Do not invent species status, range, population, listing, date or news.",
    ]
    titles = [
        "Tracker record schema and evidence fields",
        "Scientific name common name and taxonomic rank",
        "Species subspecies population and regional unit",
        "IUCN category scope and assessment date",
        "Wildlife Protection Act schedule and legal date",
        "CITES Appendix trade-listing boundary",
        "CMS Appendix instrument and migration boundary",
        "Endemic native resident and migratory range",
        "Occurrence record range and habitat association",
        "Population size trend and risk category",
        "Dated trigger and static anchor separation",
        "News report notification and authoritative database",
        "Status verbs and effective dates",
        "Rediscovery reassessment and cross-source reconciliation",
        "Stale-current firewall and update audit",
    ]
    routes = [
        "Start each record with taxon, claim, source and date fields.",
        "Anchor identity in the scientific name and stated rank.",
        "Keep species, subspecies, population and regional units separate.",
        "Cite IUCN taxon, scope and assessment date together.",
        "Cite the applicable domestic law and legal date separately.",
        "Use CITES only for its trade-control listing question.",
        "Use CMS only for the owned migratory-conservation claim.",
        "Define endemic and native against an explicit geography.",
        "Separate occurrence, accepted range and habitat association.",
        "Separate population size, trend and risk assessment.",
        "Pair each dated trigger with a stable static concept.",
        "Require official notification or database evidence for legal claims.",
        "Preserve observed, assessed, listed and notified verbs.",
        "Treat rediscovery as a trigger for verification, not automatic reassessment.",
        "Close every current entry with as-of date, recheck rule and honest omission log.",
    ]
    panels = [
        panel("Tracker entry template", "hierarchy", [
            "TAXON -> scientific name and rank",
            "CLAIM TYPE -> status range population law or event",
            "SOURCE AND DATE -> authoritative issuer and publication",
            "STATUS VERB -> assessed listed notified observed or proposed",
            "STATIC LINK AND RECHECK -> concept owner plus expiry trigger",
        ], [facts[0][0], facts[18][0]]),
        panel("Taxonomic identity ladder", "hierarchy", [
            "SCIENTIFIC NAME -> primary identity anchor",
            "RANK -> species subspecies population or other unit",
            "COMMON NAME -> secondary discovery label",
            "TAXONOMIC AUTHORITY -> accepted identity evidence",
            "RULE -> never transfer claims between units",
        ], [facts[1][0], facts[2][0], facts[3][0]]),
        panel("Five-status firewall", "comparison-table", [
            "IUCN -> extinction-risk assessment",
            "WPA SCHEDULE -> domestic legal protection classification",
            "CITES APPENDIX -> international trade-control listing",
            "CMS APPENDIX OR INSTRUMENT -> migratory cooperation",
            "TAXONOMY -> organism identity, not conservation status",
        ], [facts[4][0], facts[6][0], facts[7][0], facts[8][0]]),
        panel("IUCN assessment card", "process-flow", [
            "TAXON -> exact assessed unit",
            "GEOGRAPHIC SCOPE -> global or stated regional assessment",
            "CATEGORY -> assessment outcome",
            "VERSION OR DATE -> currency boundary",
            "RECHECK -> later assessment can supersede the claim",
        ], [facts[4][0], facts[5][0]]),
        panel("Legal and treaty date rail", "process-flow", [
            "DOMESTIC SCHEDULE -> Act and applicable amendment date",
            "CITES LISTING -> Appendix and effective trade date",
            "CMS LISTING -> Appendix or instrument and decision date",
            "SEPARATE DATABASES -> answer different questions",
            "RULE -> no cross-system automatic conversion",
        ], [facts[6][0], facts[7][0], facts[8][0], facts[17][0]]),
        panel("Range vocabulary map", "comparison-table", [
            "ENDEMIC -> naturally restricted to defined geography",
            "NATIVE -> naturally occurs there and may occur elsewhere",
            "RESIDENT -> present through relevant annual cycle",
            "MIGRATORY -> regular movement across areas or seasons",
            "SIGHTING -> occurrence record, not full range proof",
        ], [facts[9][0], facts[10][0]]),
        panel("Habitat and population screen", "comparison-table", [
            "HABITAT ASSOCIATION -> ecological use",
            "GEOGRAPHIC RANGE -> distribution envelope",
            "POPULATION SIZE -> estimate for stated unit and date",
            "POPULATION TREND -> direction across a period",
            "RISK CATEGORY -> assessment, not a census",
        ], [facts[11][0], facts[12][0]]),
        panel("Trigger-static bridge", "layered-rail", [
            "STATIC ANCHOR -> taxonomy ecology law or treaty concept",
            "DATED TRIGGER -> assessment notification decision or survey",
            "SOURCE VERB -> observed assessed listed notified or adopted",
            "EXAM USE -> one current example with its limit",
            "UPDATE RULE -> recheck when source changes",
        ], [facts[13][0], facts[15][0]]),
        panel("News-to-proof decision tree", "decision-tree", [
            "NEWS OR PRESS RELEASE -> discovery lead",
            "LEGAL CLAIM -> find official notification or decision",
            "STATUS CLAIM -> find authoritative assessment database",
            "RANGE OR POPULATION CLAIM -> find dated study or database",
            "NO PRIMARY SUPPORT -> omit and record failure",
        ], [facts[14][0], facts[19][0]]),
        panel("Rediscovery firewall", "causal-chain", [
            "NEW OBSERVATION -> possible rediscovery or locality record",
            "IDENTITY VALIDATION -> taxonomic confirmation",
            "RANGE INTERPRETATION -> evidence synthesis",
            "FORMAL REASSESSMENT OR LISTING -> separate process",
            "RULE -> observation alone changes no status automatically",
        ], [facts[16][0]]),
        panel("Cross-source reconciliation", "comparison-table", [
            "IDENTITY QUESTION -> taxonomic source",
            "EXTINCTION-RISK QUESTION -> IUCN assessment",
            "DOMESTIC LEGAL QUESTION -> WPA text",
            "TRADE OR MIGRATION QUESTION -> CITES or CMS",
            "CURRENT TRIGGER -> dated official decision or study",
        ], [facts[17][0]]),
        panel("Species tracker answer spine", "answer-spine", [
            "IDENTIFY -> scientific name rank and claim unit",
            "SEPARATE -> IUCN WPA CITES CMS range and population",
            "DATE -> assessment legal listing and trigger independently",
            "PAIR -> dated verified item with static anchor",
            "RECHECK OR OMIT -> prevent stale-current claims",
        ], [facts[18][0], facts[19][0]]),
    ]
    return common.topic(
        28, "Species and Current Affairs Tracker",
        "28_Species-and-Current-Affairs-Tracker",
        "learning-sessions/v2/subject-wide-syllabus/environment-and-ecology-28_Learning-Session.md",
        facts, traps,
        [
            (10, "Design a reliable species current-affairs tracker entry.", [0, 1, 3, 13, 15, 18]),
            (10, "Distinguish IUCN, WPA, CITES and CMS status claims.", [4, 5, 6, 7, 8]),
            (15, "Explain endemic, native, range, habitat and occurrence distinctions.", [9, 10, 11]),
            (15, "Explain why population, trend and risk category require separate evidence.", [2, 4, 12, 19]),
            (20, "Evaluate a rediscovery or new-sighting claim through a verification protocol.", [1, 2, 10, 14, 15, 16, 17, 19]),
            (20, "Build a static-plus-current species answer without stale or conflated status claims.", [0, 4, 6, 7, 8, 9, 12, 13, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "scientific name", "taxonomy", "species", "subspecies", "common name",
            "IUCN Red List", "assessment date", "Wildlife Protection Act",
            "CITES Appendix", "CMS Appendix", "endemic", "native", "range",
            "habitat", "population trend", "notification", "status verb",
            "rediscovery", "verified current trigger", "as-of date",
        ],
        "Audited ledgers route species identity, behaviour, range and institution questions, including provisionally keyed 2026 and answer-free objective demands. No option, species status, range, population or listing is inferred.",
        [],
        [
            "https://www.cms.int/en/species — attempted 2026-09-03; substantive official page structure exposed separate scientific name, common name, class, order, family, instrument and Appendix fields. No species-specific current listing was imported.",
            "https://cites.org/eng/app/appendices.php — attempted 2026-09-03; the official route returned HTTP 403, so no Appendix or effective-date claim was imported.",
            "https://www.iucnredlist.org/resources/categories-and-criteria — attempted 2026-09-03; the official route returned HTTP 520, so no current category, assessment version or species claim was imported.",
            "https://www.iucnredlist.org/assessment/process — attempted 2026-09-03; the official route returned HTTP 520, so no assessment-process wording was imported.",
            "https://moef.gov.in/ — attempted 2026-09-03; the fetched page exposed an unrelated recruitment notice, so no Wildlife Protection Act schedule or species notification was imported.",
        ],
        "The CMS species page supplied substantive field-level separation but no selected species update. CITES and IUCN checks failed and the MoEFCC page was unrelated; therefore no current species status, range, population, WPA schedule, CITES or CMS listing, effective date or news claim is asserted.",
        extra=[
            "basic/04_Biodiversity-Levels-and-Hotspots.md",
            "basic/05_IUCN-Red-List-and-Endemism.md",
            "basic/08_Wildlife-Protection-Act-and-Schedules.md",
            "basic/09_CITES-and-Wildlife-Trade.md",
            "basic/10_CMS-Bonn-Convention-Migratory-Species.md",
            "advanced/05_IUCN-Red-List-and-Endemism.md",
            "advanced/09_CITES-and-Wildlife-Trade.md",
            "advanced/10_CMS-Bonn-Convention-Migratory-Species.md",
        ],
        pyq_audit_heading="AUDITED SPECIES IDENTITY, ECOLOGY, RANGE, STATUS AND CURRENT-AFFAIRS PYQ OWNERSHIP",
        register_headings=(
            "TAXONOMY, RANGE, STATUS SYSTEM AND TRACKER-RECORD MAP",
            "ASSESSMENT, LEGAL LISTING, DATE, SIGHTING AND STALE-CURRENT TRAPS",
            "SPECIES CURRENT-AFFAIRS ANSWER SPINE",
            "LIVE STATUS, RANGE, POPULATION, LISTING, DATE AND NEWS EVIDENCE BOUNDARY",
        ),
        register_answer_spine=[
            "IDENTIFY SCIENTIFIC NAME TAXONOMIC RANK AND CLAIM UNIT",
            "SEPARATE IUCN ASSESSMENT WPA SCHEDULE CITES AND CMS LISTING",
            "SEPARATE ENDEMIC NATIVE RANGE HABITAT POPULATION AND TREND",
            "DATE EVERY ASSESSMENT NOTIFICATION LISTING AND CURRENT TRIGGER",
            "PRESERVE OBSERVED ASSESSED LISTED NOTIFIED AND EFFECTIVE STATUS VERBS",
            "PAIR A VERIFIED DATED ITEM WITH ITS STATIC CONCEPT ANCHOR",
            "RECHECK OR OMIT TO PREVENT STALE-CURRENT CLAIMS",
        ],
        allow_existing_history=True,
    )


TOPIC_25 = _topic_25()
TOPIC_26 = _topic_26()
TOPIC_27 = _topic_27()
TOPIC_28 = _topic_28()
