"""Generate the immutable 2026-09-03 Problem of Evil semantic successor only."""

from __future__ import annotations

import copy
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import regenerate_philosophy_religion_deep_review as base


ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-09-03"
TOPIC_KEY = "philosophy-paper-ii-philosophy-of-religion-03"
OWNER = (
    ROOT
    / "upsc-ai-kit"
    / "knowledge"
    / "Philosophy"
    / "paper-2"
    / "philosophy-of-religion"
    / "Problem-of-Evil.md"
)


def extract_section(text: str, heading: str, next_marker: str) -> str:
    match = re.search(
        rf"(?ms)^{re.escape(heading)}\s*$.*?(?=^{re.escape(next_marker)}\s*$)",
        text,
    )
    if not match:
        raise ValueError(f"Cannot extract canonical section {heading!r}.")
    return match.group(0).strip()


def demote(fragment: str, levels: int = 1) -> str:
    return re.sub(
        r"(?m)^(#{2,5})\s+",
        lambda match: "#" * min(len(match.group(1)) + levels, 6) + " ",
        fragment,
    )


def insert_before(text: str, marker: str, fragment: str) -> str:
    if marker not in text:
        raise ValueError(f"Missing learner marker {marker!r}.")
    return text.replace(marker, fragment.rstrip() + "\n\n" + marker, 1)


SESSION_CONTROLS: dict[int, dict[str, str]] = {
    1: {
        "technical": (
            "The problem of evil comprises logical inconsistency, evidential "
            "improbability, existential protest and pastoral-moral burdens generated by "
            "a specified divine profile and suffering."
        ),
    },
    2: {
        "plain": (
            "Mackie's logical problem argues that omnipotence, perfect goodness and evil "
            "become inconsistent only when additional premises connect goodness and "
            "power to evil-prevention."
        ),
        "technical": (
            "The inconsistent set requires bridging principles that a perfectly good "
            "being prevents every evil it can and an omnipotent being has no relevant "
            "limit, unless a morally sufficient reason is possible."
        ),
        "opening": (
            "Mackie's triad is not formally contradictory by itself; the logical problem "
            "depends on additional premises linking perfect goodness and omnipotence to "
            "the prevention of evil."
        ),
        "how": (
            "Use Mackie's inconsistent triad, omnipotence, perfect goodness and the "
            "additional premises to test logical compatibility, then distinguish a "
            "possible defence from an account of God's actual reason."
        ),
    },
    5: {
        "plain": (
            "Classical responses include Augustinian privation and free will, Irenaean "
            "soul-making, natural-law regularity and greater-good reasoning."
        ),
        "technical": (
            "Augustinian and Irenaean-Hick approaches preserve the classical divine "
            "profile by locating evil in defective will, privation, epistemic distance "
            "or a law-governed environment of virtue formation."
        ),
        "opening": (
            "Classical responses preserve divine power and goodness by distinguishing "
            "privation and free misuse from developmental risk, stable law and "
            "soul-making."
        ),
        "how": (
            "Compare Augustinian privation and Irenaean soul-making through free will, "
            "natural-law regularity and virtue formation, then apply the victim-centred "
            "objection to natural, horrendous and distributed suffering."
        ),
    },
    6: {
        "plain": (
            "Non-classical theisms reduce the problem of evil by revising divine power, "
            "foreknowledge, immutability or unilateral control rather than justifying "
            "every permitted evil."
        ),
        "technical": (
            "Process, open and finite-God models trade elements of the classical divine "
            "profile for persuasive, temporally responsive or limited agency and must be "
            "assessed by that attribute cost."
        ),
        "opening": (
            "Process, open and finite-God responses reduce the evil problem by revising "
            "classical control, but every revision purchases relief at a theological cost."
        ),
        "how": (
            "Use process theism, open theism and the finite God to show how persuasive "
            "power or revised omnipotence reduces the evil problem, then state the "
            "attribute cost of departing from classical control."
        ),
    },
    8: {
        "how": (
            "Compare karma, dependent origination, non-creator traditions, Nyaya theism "
            "and Advaita levels on creator, self and collective suffering, without "
            "treating karma as one uniform doctrine."
        ),
    },
    10: {
        "plain": (
            "Comparative synthesis asks what each response establishes logically, "
            "evidentially and existentially and what moral or theological cost it incurs."
        ),
        "technical": (
            "A complete comparison distinguishes possibility-defences, "
            "probability-shifting replies, claimed theodicies and protest-oriented "
            "practical implications before issuing a version-specific verdict."
        ),
        "opening": (
            "The strongest conclusion is version-specific: a response may restore "
            "logical compatibility, reduce evidential pressure or offer existential "
            "meaning without resolving every problem of evil."
        ),
        "how": (
            "Build the comparative synthesis through logical compatibility, evidential "
            "weight and existential adequacy; separate defence from theodicy, state "
            "practical implications and finish with a graded conclusion."
        ),
    },
}


CLOSURE_CONTROLS: dict[int, dict[str, str]] = {
    1: {
        "mechanism": (
            "Identify moral or natural evil, specify the divine profile and classify the "
            "challenge as logical, evidential, existential or pastoral."
        ),
        "consequence": (
            "Different problem-types impose different burdens and cannot be answered by "
            "one generic theodicy."
        ),
        "trap": (
            "Do not confuse strict contradiction, probability-shift, protest and moral "
            "care."
        ),
    },
    2: {
        "mechanism": (
            "Mackie's set becomes inconsistent only with additional evil-prevention "
            "principles linking perfect goodness and omnipotence."
        ),
        "consequence": (
            "A possible morally sufficient reason defeats strict contradiction without "
            "explaining the actual amount or distribution of evil."
        ),
        "trap": (
            "Do not call the bare triad formally contradictory or omit omniscience from "
            "the wider classical profile."
        ),
    },
    3: {
        "mechanism": (
            "Significant freedom includes the possibility of wrong choice, and possible "
            "transworld depravity blocks guaranteed freely chosen goodness."
        ),
        "consequence": (
            "Plantinga establishes logical compatibility for moral evil, not God's actual "
            "reason or a complete account of natural evil."
        ),
        "trap": (
            "Do not present transworld depravity as an established fact about every person "
            "or every possible world."
        ),
    },
    4: {
        "mechanism": (
            "Rowe treats apparently gratuitous suffering as probability-lowering evidence; "
            "skeptical theism challenges the noseeum inference through CORNEA."
        ),
        "consequence": (
            "Epistemic humility can weaken the evidential inference while threatening "
            "ordinary moral and providential reasoning if applied without limits."
        ),
        "trap": (
            "Do not use Rowe's fawn as a deductive contradiction or reduce skeptical "
            "theism to an appeal to mystery."
        ),
    },
    5: {
        "mechanism": (
            "Privation and free will explain defective agency, while soul-making and "
            "natural-law regularity explain developmental risk."
        ),
        "consequence": (
            "Classical responses preserve the divine profile but face inherited-guilt, "
            "natural-evil, excess and victim-instrumentalisation objections."
        ),
        "trap": (
            "Do not treat privation as unreality, a defence as a theodicy or suffering as "
            "automatically beneficial."
        ),
    },
    6: {
        "mechanism": (
            "Process, open and finite-God models revise unilateral power, foreknowledge or "
            "immutability to reduce divine culpability."
        ),
        "consequence": (
            "The problem weakens because the God-concept changes, but worship-worthiness "
            "and final victory over evil become harder to secure."
        ),
        "trap": (
            "Do not call process persuasion voluntary self-limitation; Griffin treats "
            "non-coercion as metaphysically necessary."
        ),
    },
    7: {
        "mechanism": (
            "Existential protest and anti-theodicy test whether explanation respects "
            "lament, victim dignity and resistance to preventable harm."
        ),
        "consequence": (
            "Horrendous evil requires personal defeat rather than world-level balancing "
            "or mere later compensation."
        ),
        "trap": (
            "Do not use severe suffering as a decorative example or let a neat theodicy "
            "silence protest."
        ),
    },
    8: {
        "mechanism": (
            "Indian systems distribute explanatory work among karma, dependent origination, "
            "creator-governance, ignorance and liberation."
        ),
        "consequence": (
            "Beginningless karma addresses distribution without verifying specific desert, "
            "while non-creator systems remove divine culpability but retain suffering."
        ),
        "trap": (
            "Do not infer blame from present suffering or present karma as one uniform "
            "theistic doctrine."
        ),
    },
    9: {
        "mechanism": (
            "Animal, pre-human, collective and horrendous suffering test natural-law, "
            "greater-good, karmic and soul-making explanations at their hardest point."
        ),
        "consequence": (
            "A response must separate causal explanation, logical defence, moral "
            "justification and pastoral meaning."
        ),
        "trap": (
            "Do not treat vulnerable persons, disability or severe suffering as an "
            "instrument for someone else's character."
        ),
    },
    10: {
        "mechanism": (
            "Compare each response by logical compatibility, evidential weight, "
            "existential adequacy, moral practice and attribute cost."
        ),
        "consequence": (
            "No success at one level automatically resolves every other version of the "
            "problem."
        ),
        "trap": (
            "Do not conclude with devotional assertion or total refutation when the "
            "argument supports only a graded result."
        ),
    },
}


def transform_ascii(text: str) -> str:
    text = text.replace(
        " +-> natural: disease, earthquake, congenital suffering",
        " +-> natural: disease, earthquake, non-agential illness",
    )
    text = text.replace(
        " logical: God and evil are strictly inconsistent",
        " logical: claims strict inconsistency only with evil-prevention bridges",
    )
    text = text.replace(
        " KARMA explains moral continuity but faces first-origin, victim-blaming and natural-evil pressures;",
        " KARMA explains moral continuity but faces beginninglessness, verification,\n"
        " victim-blaming and natural-evil pressures;",
    )
    text = text.replace(
        " child suffering | animal pain | genocide | disability | unequal opportunity | hiddenness",
        " suffering of children | animal pain | mass atrocity\n"
        " disabling harm | unequal exposure | hidden suffering",
    )
    return text


def repair_session_contracts(text: str) -> str:
    session_re = re.compile(
        r"(?ms)^### SESSION (\d+) — ([^\n]+)\n(.*?)(?=^### SESSION \d+ — |\Z)"
    )

    def repair(match: re.Match[str]) -> str:
        number = int(match.group(1))
        title = match.group(2).strip()
        body = match.group(3)
        control = SESSION_CONTROLS.get(number, {})
        for field, label in (
            ("plain", "Plain-language definition"),
            ("technical", "Technical definition"),
        ):
            if field in control:
                body = re.sub(
                    rf"(?m)^\*\*{re.escape(label)}:\*\* .+$",
                    f"**{label}:** {control[field]}",
                    body,
                    count=1,
                )
        if "opening" in control:
            body = re.sub(
                r"(?ms)(^#### ANSWER-GRABBING OPENING.*?\n+\s*>\s*).+?$",
                lambda found: found.group(1) + control["opening"],
                body,
                count=1,
            )
        if number == 10 and "- **comparative synthesis**" not in body.casefold():
            body = body.replace(
                "- **graded conclusion**\n\n**How to use them:**",
                "- **graded conclusion**\n"
                "- **comparative synthesis**\n"
                "- **practical implications**\n\n"
                "**How to use them:**",
                1,
            )
        if "how" in control:
            body = re.sub(
                r"(?m)^\*\*How to use them:\*\* .+$",
                f"**How to use them:** {control['how']}",
                body,
                count=1,
            )

        keyword_match = re.search(
            r"(?ms)^#### MUST-WRITE KEYWORDS\s*$\n+(.*?)(?=^\*\*How to use them:\*\*)",
            body,
        )
        if not keyword_match:
            raise ValueError(f"Session {number} has no readable keyword block.")
        keywords = re.findall(
            r"(?m)^\s*[-*]\s+\*\*(.+?)\*\*\s*$",
            keyword_match.group(1),
        )
        if not 4 <= len(keywords) <= 8:
            raise ValueError(f"Session {number} has {len(keywords)} closure keywords.")
        opening_match = re.search(
            r"(?ms)^#### ANSWER-GRABBING OPENING.*?\n+\s*>\s*(.+?)\s*$",
            body,
        )
        if not opening_match:
            raise ValueError(f"Session {number} has no answer opening.")
        opening = opening_match.group(1).strip()
        roles = CLOSURE_CONTROLS[number]
        closure = (
            f"#### CLOSING RECALL FLOW — {title}\n"
            "```closure-flow\n"
            f"SUBTOPIC: {title}\n"
            f"STARTING CONCEPT: {title}\n"
            f"KEY TERMS / DEFINITIONS: {' · '.join(keywords)}\n"
            f"MECHANISM / ARGUMENT: {roles['mechanism']}\n"
            f"CONSEQUENCE / CONTRAST: {roles['consequence']}\n"
            f"UPSC TRAP / ANSWER-USE: {roles['trap']}\n"
            f"ANSWER-GRABBING FORMULATION: {opening}\n"
            "```"
        )
        body, count = re.subn(
            r"(?ms)^#### CLOSING RECALL FLOW[^\n]*\n```closure-flow\n.*?```",
            closure,
            body,
            count=1,
        )
        if count != 1:
            raise ValueError(f"Session {number} closure could not be replaced.")
        return f"### SESSION {number} — {title}\n{body}"

    return session_re.sub(repair, text)


def transform_markdown(text: str, generation: int) -> str:
    owner = OWNER.read_text(encoding="utf-8")
    firewall = demote(
        extract_section(
            owner,
            "## Exact printed ownership and cross-topic firewall",
            "---",
        )
    )
    divine_profile = demote(
        extract_section(
            owner,
            "### 1.1 Divine profile, additional premises and three burdens",
            "---",
        )
    )
    response_control = demote(
        extract_section(
            owner,
            "### 9.5A Greater-good, best-world, mystery, eschatology and anti-theodicy",
            "### 9.6 Evil, the profane and the sacred as religion-forming categories "
            "(2019 Q6(b) owner-module)",
        )
    )
    karma_control = demote(
        extract_section(
            owner,
            "#### Karma, beginninglessness and moral caution",
            "### 9.5A Greater-good, best-world, mystery, eschatology and anti-theodicy",
        )
    )

    if "### Exact printed ownership and cross-topic firewall" not in text:
        text = text.replace(
            "## BASIC LEARNING SESSION",
            "## BASIC LEARNING SESSION\n\n" + firewall,
            1,
        )
    if "#### 1.1 Divine profile, additional premises and three burdens" not in text:
        text = insert_before(
            text,
            "#### CLOSING RECALL FLOW — CLASSICAL FORMULATION AND MACKIE'S LOGICAL PROBLEM",
            divine_profile,
        )
    if "##### Karma, beginninglessness and moral caution" not in text:
        text = insert_before(
            text,
            "#### CLOSING RECALL FLOW — INDIAN AND NON-WESTERN FRAMEWORKS",
            karma_control,
        )
    if (
        "#### 9.5A Greater-good, best-world, mystery, eschatology and anti-theodicy"
        not in text
    ):
        text = insert_before(
            text,
            "#### CLOSING RECALL FLOW — EXISTENTIAL EVIL, PROTEST AND HORRENDOUS EVILS",
            response_control,
        )

    source_control = (
        "### Local source and factual control\n\n"
        "- John Hick's local searchable *Philosophy of Religion*, print pp. 39–52 "
        "(PDF pp. 50–64), controls the Augustinian, Irenaean and process taxonomy.\n"
        "- The local *Oxford Handbook of Philosophy of Religion*, PDF pp. 200–230 "
        "and 444–446, controls defence/theodicy and logical/evidential distinctions.\n"
        "- No empirical frequency, probability or neuroscience claim is used as a "
        "premise; hard cases remain source-controlled and non-graphic."
    )
    if "### Local source and factual control" not in text:
        text = insert_before(
            text,
            "### Source-complete coverage ledger and answer-worthiness labels",
            source_control,
        )

    text = re.sub(
        r"(?ms)^### Current scholarly anchor — .*?(?=^#### Roadmap)",
        "### Current evidence policy — [SUPPORTING]\n\n"
        "No dated publication is used as doctrinal or empirical proof. The live debate "
        "is represented through the source-controlled logical/evidential distinction, "
        "Rowe, skeptical theism and their standard objections.\n\n",
        text,
        count=1,
    )
    replacements = {
        "participation in the murder of one's own children": (
            "coerced participation in grave harm against one's own family"
        ),
        "cannibalising one's own offspring": (
            "devastating violence against intimate relations"
        ),
        "A parent who, under coercion, participates in the death of their own child": (
            "A person coerced into grave harm against someone they love"
        ),
        "dying slowly in a lightning-caused forest fire, unseen and unmourned": (
            "undergoing severe apparently unobserved suffering after a natural fire"
        ),
        "across hundreds of millions of years before any moral agent existed": (
            "across the long pre-human history of life"
        ),
        "child suffering | animal pain | genocide | disability | unequal opportunity | hiddenness": (
            "suffering of children | animal pain | mass atrocity\n"
            "disabling harm | unequal exposure | hidden suffering"
        ),
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    text = repair_session_contracts(text)
    text = transform_ascii(text)
    required = (
        "Exact printed ownership and cross-topic firewall",
        "Divine profile, additional premises and three burdens",
        "Karma, beginninglessness and moral caution",
        "Greater-good, best-world, mystery, eschatology and anti-theodicy",
        "Local source and factual control",
        "STARTING CONCEPT",
        "logical: claims strict inconsistency only with evil-prevention bridges",
    )
    missing = [term for term in required if term.casefold() not in text.casefold()]
    if missing:
        raise ValueError(f"Problem of Evil semantic transform missing: {missing}")
    return text


def transform_graphical(spec: dict[str, Any]) -> dict[str, Any]:
    answer_lines = {
        "00": (
            "Classify moral or natural evil and logical, evidential or existential "
            "burden before selecting any defence or theodicy."
        ),
        "01": (
            "Mackie's triad needs evil-prevention bridges; Plantinga restores possible "
            "compatibility without explaining the actual quantity of suffering."
        ),
        "02": (
            "Soul-making links epistemic distance and stable law to virtue, but must "
            "answer excess, unequal distribution and victim-instrumentalisation."
        ),
        "03": (
            "Privation, best-world, greater-good and process replies preserve different "
            "attributes and incur different moral or theological costs."
        ),
        "04": (
            "Rowe treats apparently gratuitous suffering as evidence; CORNEA blocks the "
            "noseeum inference only at the risk of wider moral scepticism."
        ),
        "05": (
            "Beginningless karma addresses distribution without licensing retrospective "
            "blame; Indian systems differ over creator, self and causal mechanism."
        ),
        "06": (
            "Hard cases test whether a response offers compatibility, explanation, "
            "justification or pastoral meaning while preserving victim dignity."
        ),
        "07": (
            "A strong conclusion is version-specific: evil may not strictly disprove every "
            "God-concept while remaining severe evidence against classical theism."
        ),
    }
    for stage in spec.get("stages", []):
        stage_id = str(stage.get("id"))
        if stage_id in answer_lines:
            stage["answer_line"] = answer_lines[stage_id]
    return spec


def write_generation_ascii_spec(
    generation: int,
    markdown_path: Path,
    transformed_markdown: str,
) -> Path:
    source = (
        ROOT
        / "upsc-ai-kit"
        / "manifests"
        / "retrofits"
        / "ascii-panel-specs"
        / "philosophy-2026-08-23.json"
    )
    target = source.with_name(f"{TOPIC_KEY}-ascii-g{generation}-{DATE}.json")
    if target.exists():
        raise RuntimeError(f"Refusing to overwrite immutable ASCII spec: {target}")
    shared = json.loads(source.read_text(encoding="utf-8"))
    topic = copy.deepcopy(
        next(item for item in shared["topics"] if item["topic_key"] == TOPIC_KEY)
    )
    ascii_fragment = transformed_markdown.split(
        "### COMPLETE TOPIC ASCII MASTER FLOW DIAGRAM",
        1,
    )[1]
    blocks = re.findall(
        r"(?ms)^#### ASCII MASTER FLOW — PANEL \d+/\d+: (.+?)\n+"
        r"```ascii-master\n(.*?)\n```",
        ascii_fragment,
    )
    if len(blocks) != len(topic["panels"]):
        raise ValueError(
            f"Expected {len(topic['panels'])} authored ASCII panels, found {len(blocks)}."
        )
    for panel, (title, body) in zip(topic["panels"], blocks):
        panel["panel_title"] = title.strip()
        panel["lines"] = body.splitlines()
    topic["source_markdown"] = base.rel(markdown_path)
    topic["source_record"] = f"{TOPIC_KEY}:learner-v2:g{generation}"
    spec = {
        "schema_version": 1,
        "benchmark": "Problem-of-Evil reviewed eight-panel ASCII master",
        "generated_on": DATE,
        "scope": f"{TOPIC_KEY} immutable generation g{generation}",
        "constraints": copy.deepcopy(shared.get("constraints", {})),
        "topics": [topic],
    }
    base.dump(target, spec)
    return target


def validate_refreshed(record: dict[str, Any], ascii_spec: Path) -> str:
    command = [
        sys.executable,
        str(ROOT / "tools" / "validate_v2_export.py"),
        str(base.repo(record["markdown"])),
        "--repository-root",
        str(ROOT),
        "--topic-key",
        TOPIC_KEY,
        "--ascii-spec",
        str(ascii_spec),
        "--main-pdf",
        str(base.repo(record["main_pdf"])),
        "--workbook",
        str(base.repo(record["workbook"])),
        "--tracker",
        str(base.TRACKER),
        "--variant",
        "learner-v2",
        "--generation",
        str(record["generation"]),
        "--refreshed-contract",
    ]
    environment = dict(os.environ)
    environment["PYTHONIOENCODING"] = "utf-8"
    completed = subprocess.run(
        command,
        cwd=ROOT,
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode:
        raise RuntimeError(
            "Authoritative refreshed-contract validation failed:\n"
            + completed.stdout
            + completed.stderr
        )
    output = completed.stdout.strip()
    print(output)
    return output


def main() -> int:
    latest = base.latest(TOPIC_KEY)
    if int(latest["generation"]) != 13:
        raise ValueError(
            f"Expected reviewed predecessor g13, found {latest['record_id']}."
        )
    base.DATE = DATE
    generation = int(latest["generation"]) + 1
    next_markdown = (
        base.repo(latest["markdown"]).parents[1]
        / f"g{generation}"
        / f"topic-03_Complete-Learning-Session_{DATE}.md"
    )
    preview_text = transform_markdown(
        base.repo(latest["markdown"]).read_text(encoding="utf-8"),
        generation,
    )
    ascii_spec = write_generation_ascii_spec(
        generation,
        next_markdown,
        preview_text,
    )
    canonical_asset_folder = (
        ROOT
        / "notes"
        / "Learner-v2-Refreshed"
        / "learning-session-v2"
        / TOPIC_KEY
        / "assets"
    )
    changed = {
        base.rel(Path(__file__)),
        base.rel(OWNER),
        base.rel(ROOT / "tools" / "philosophy_indian_religion_reviewed_content.py"),
        base.rel(ascii_spec),
    }
    result = base.process_topic(
        3,
        changed,
        text_transform=transform_markdown,
        graphical_transform=transform_graphical,
        repair_scope=(
            "ten-gate semantic-completeness repair for Problem of Evil: ownership, "
            "logical/evidential precision, response taxonomy, Indian/pastoral control, "
            "session contract and immutable dependent artifacts"
        ),
        baseline_score=97,
        repaired_score=100,
        issues_closed=[
            "exact ownership and cross-topic boundaries made explicit",
            "Mackie's triad corrected through additional premises and omniscience control",
            "logical, evidential and existential/pastoral burdens separated",
            "inherited-guilt, karma, best-world, mystery and anti-theodicy gaps repaired",
            "graphic and unsupported empirical examples removed or bounded",
            "all ten refreshed session contracts and asset metadata repaired",
            "ASCII and graphical artifacts regenerated from one repaired source",
        ],
        ascii_spec_path=ascii_spec,
        canonical_asset_folder=canonical_asset_folder,
        ascii_from_markdown=True,
    )
    record = base.latest(TOPIC_KEY)
    validator_output = validate_refreshed(record, ascii_spec)
    authoritative_validation = (
        ROOT
        / "upsc-ai-kit"
        / "manifests"
        / "exports"
        / f"{TOPIC_KEY}-learner-v2-g{generation}-{DATE}-"
        "authoritative-refreshed-validation.json"
    )
    base.dump(
        authoritative_validation,
        {
            "schema_version": 1,
            "topic_key": TOPIC_KEY,
            "record_id": record["record_id"],
            "generation": generation,
            "validated_on": DATE,
            "validator": "tools\\validate_v2_export.py --refreshed-contract",
            "manual_ascii_spec": base.rel(ascii_spec),
            "asset_folder": record["asset_folder"],
            "result": "passed",
            "stdout": validator_output,
        },
    )
    changed.add(base.rel(authoritative_validation))

    generation = int(result["new_record_id"].rsplit("g", 1)[1])
    inventory = (
        ROOT
        / "upsc-ai-kit"
        / "manifests"
        / "exports"
        / f"{TOPIC_KEY}-learner-v2-g{generation}-{DATE}-changed-files.txt"
    )
    items = set(inventory.read_text(encoding="utf-8").splitlines())
    items.update(changed)
    items.update(
        {
            "V2-SUBJECT-SECTION-COMMAND-INDEX.md",
            "notes\\Philosophy\\learning-session-v2\\paper-ii-philosophy-of-religion"
            "\\indexes\\TOPIC-COVERAGE-INDEX.md",
            "notes\\Philosophy\\learning-session-v2\\paper-ii-philosophy-of-religion"
            "\\indexes\\NOTES-PDF-INDEX.md",
            "notes\\Philosophy\\learning-session-v2\\paper-ii-philosophy-of-religion"
            "\\indexes\\WORKBOOK-PDF-INDEX.md",
        }
    )
    inventory.write_text(
        "\n".join(sorted(filter(None, items), key=str.casefold)) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({**result, "inventory": base.rel(inventory)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
