"""Authored Geography learner-v2 data for Topics 15-19."""

from __future__ import annotations

import generate_geography_common as common


def plan(
    title: str, indexes: list[int], caution: str, exam_use: str
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_15 = common.topic(
    15,
    "Hot Wet Equatorial Climate",
    "15_Hot-Wet-Equatorial-Climate.md",
    "15_India-Evergreen-Forests.md",
    "15_India-Evergreen-Forests_Complete-Topic-Package.md",
    [
        ("Af location and extent", "The textbook hot-wet equatorial or Koppen Af climate is concentrated close to the Equator, commonly about 5 to 10 degrees north and south, with major lowland expressions in Amazonia, the Congo basin and maritime Southeast Asia; mapped limits vary with dataset and relief."),
        ("Equatorial convergence", "Persistent high insolation, the equatorial low-pressure belt and converging moist air favour uplift and convection; seasonal ITCZ movement can shift rainfall maxima without creating a true dry winter."),
        ("Uniform heat", "Source-era climatic summaries place mean monthly temperatures commonly around 26 to 28 degrees Celsius, while the annual range is usually below about 3 degrees Celsius; these are climatic descriptors, not daily limits."),
        ("Diurnal-annual contrast", "The diurnal temperature range exceeds the annual range because day-night radiation changes more than seasonal solar receipt near the Equator; this is a classic close-option discriminator."),
        ("Year-round rainfall", "Source notes commonly give about 150 to 250 centimetres of annual rain, heavy and well distributed through the year; the defining point is absence of a true dry season, not one universal total."),
        ("Convection and equinoxes", "Strong daytime heating produces convection, cumulonimbus growth and frequent afternoon thunderstorms, while slight double rainfall maxima may occur near the equinox passages of the overhead sun."),
        ("Rainforest vertical structure", "Tropical rainforest is evergreen, broad-leaved and multi-storeyed, with emergents above a closed canopy, shaded under-storeys and a dark humid floor; vegetation is not a uniform wall of equal-height trees."),
        ("Lianas, epiphytes and hardwoods", "Lianas and epiphytes exploit light and support within the layered forest, while mixed hardwood species such as ebony and rosewood complicate selective commercial extraction."),
        ("Nutrient paradox", "Rapid decomposition and intense leaching mean nutrient capital is held largely in living biomass and fast litter-root recycling rather than in a deep fertile soil store; young volcanic and alluvial soils are important exceptions."),
        ("Shifting-cultivation logic", "Slash-and-burn or shifting cultivation can work with small clearings and sufficiently long fallow because regrowth rebuilds biomass and nutrient cycling; shortened fallow can convert adaptation into degradation."),
        ("Plantation economy", "Rubber, cocoa, oil palm and coffee plantations developed through capital, labour and export-market systems; they are economic transformations of humid tropics, not inevitable products of Af climate."),
        ("Logging and access", "Dense vegetation, mixed species, difficult access, transport cost, ecological damage and regulation constrain commercial logging; abundant biomass does not automatically equal easy timber exploitation."),
        ("India climate boundary", "India has no extensive true equatorial Af zone; its closest analogue is tropical wet evergreen forest shaped mainly by monsoon rainfall, orography and insularity."),
        ("India evergreen belts", "The principal Indian evergreen and semi-evergreen belts are the windward Western Ghats, parts of North-East India, the eastern Himalayan foothills and the Andaman-Nicobar Islands, with local transitions rather than one continuous zone."),
        ("India moisture threshold", "Indian source notes associate tropical wet evergreen forest with very heavy rainfall, often above about 200 to 250 centimetres and a short dry season; thresholds overlap by altitude, soils and classification."),
        ("Indian biodiversity value", "Western Ghats, North-East and island rainforests combine high endemism, watershed regulation and habitat connectivity; hotspot status does not make every mapped hectare the same forest type or legal category."),
        ("Jhum evidence boundary", "Jhum is a regionally varied shifting-cultivation system whose ecological outcome depends on fallow length, slope, fire, tenure and livelihood alternatives; no universal cycle length should be quoted without a dated local study."),
        ("FSI evidence boundary", "Forest Survey of India reports are biennial national assessments; their dated forest-cover and forest-type products can locate change, but forest cover, recorded forest area and tropical evergreen type are not interchangeable measures."),
        ("Verified rainforest-structure route", "The routed 2021 Prelims demand tests identification of tropical-rainforest vegetation structure; the local ledger withholds the official answer letter, so the examinable support is layered canopy, evergreen habit and associated climbers."),
        ("Verified nutrient-cycle route", "The routed 2023 Prelims demand tests tropical-rainforest soil nutrients and decomposition; the local ledger withholds the official key, so the package teaches rapid decomposition, leaching and biomass-centred recycling without inventing an option."),
    ],
    [
        "Do not turn a textbook 5 to 10 degree belt into an immutable mapped boundary.",
        "Do not call equatorial rainfall a summer-only monsoon regime.",
        "Do not confuse a small annual temperature range with a small day-night range.",
        "Do not present 150 to 250 centimetres as a universal station value.",
        "Do not treat every afternoon storm or equinox maximum as compulsory.",
        "Do not draw rainforest vegetation as one uniform tree layer.",
        "Do not infer fertile agricultural soil from luxuriant standing biomass.",
        "Do not condemn all shifting cultivation without the fallow and tenure context.",
        "Do not present plantation crops as natural climax vegetation.",
        "Do not equate abundant timber with accessible, low-impact commercial logging.",
        "Do not label India's wet monsoon forests as an extensive true Af climate zone.",
        "Do not invent answer letters for the 2021 or 2023 routed objective questions.",
    ],
    [
        (10, "Explain why the annual temperature range is unusually small in the hot-wet equatorial climate.", "Near-constant solar receipt and persistent humidity suppress seasonal thermal contrast, while day-night radiation still makes the diurnal range larger.", [0, 2, 3]),
        (10, "Show how convection produces the characteristic rainfall rhythm of equatorial lowlands.", "Equatorial convergence and strong daytime heating lift moist air into cumulonimbus storms, with year-round rain and possible equinoctial maxima.", [1, 4, 5]),
        (15, "Explain the layered structure and nutrient paradox of tropical rainforest.", "Continuous warmth and moisture build a multi-storeyed biomass system whose rapid decomposition and leaching keep much nutrient capital in vegetation rather than soil.", [6, 7, 8]),
        (15, "Assess shifting cultivation and plantation agriculture as contrasting responses to humid tropical environments.", "Long-fallow shifting cultivation works through biomass recovery, whereas plantations use capital and markets; both become damaging when scale, fallow or regulation fails.", [9, 10, 11]),
        (20, "Compare the global Af rainforest with India's tropical wet evergreen analogue.", "Both share layered evergreen vegetation, but India is governed mainly by monsoon seasonality, orography and island effects rather than an extensive true equatorial climate.", [12, 13, 14, 15]),
        (20, "Design an evidence-led strategy for conserving India's evergreen forests without confusing climate, forest cover and legal status.", "Separate climate type, vegetation type, mapped forest cover and legal category, then combine FSI monitoring, corridor protection, local tenure and region-specific jhum transitions.", [15, 16, 17, 18, 19]),
    ],
    [
        plan("Af location and equatorial setting", [0], "Latitude is a guide, not a wall.", "Locate Amazon, Congo and maritime Southeast Asia before explaining process."),
        plan("Equatorial low and convection", [1], "ITCZ migration alters maxima without creating monsoon seasonality.", "Build the convergence-to-uplift chain."),
        plan("Uniform heat and annual range", [2], "Climatic means are not daily extremes.", "Use latitude and cloud-humidity controls."),
        plan("Diurnal range exceeds annual range", [3], "Do not reverse the two ranges.", "State the classic Prelims discriminator explicitly."),
        plan("Year-round rainfall regime", [4], "The no-dry-season rule matters more than one total.", "Distinguish Af from Am and Aw."),
        plan("Afternoon storms and equinox maxima", [5], "Neither timing nor double maximum is compulsory at every station.", "Trace heating, uplift, condensation and storm."),
        plan("Rainforest layers", [6], "Layering, not uniform height, is diagnostic.", "Draw emergent-canopy-understorey-floor structure."),
        plan("Climbers, epiphytes and hardwood mix", [7], "Species richness can hinder selective extraction.", "Connect forest form to access and logging."),
        plan("Nutrient paradox", [8], "Rich biomass does not imply rich soil.", "Follow litter, decomposition, roots and leaching."),
        plan("Shifting cultivation and fallow", [9], "Outcome depends on scale and recovery time.", "Avoid environmental determinism."),
        plan("Plantations and commercial forestry", [10, 11], "Climate permits but institutions organise land use.", "Compare monoculture and mixed-forest extraction."),
        plan("India's equatorial-type boundary", [12], "Equatorial-type vegetation is not a true national Af belt.", "Preserve global Basic versus India Advanced ownership."),
        plan("Indian evergreen distribution", [13, 14], "Rainfall thresholds overlap and vary locally.", "Map Ghats, North-East, foothills and islands."),
        plan("Biodiversity, jhum and FSI evidence", [15, 16, 17], "Forest cover, forest type and legal status differ.", "Use dated official monitoring without invented rates."),
        plan("Verified rainforest PYQ routes", [18, 19], "The ledger supplies demands but no answer letters.", "Close with structure and nutrient-cycle elimination logic."),
    ],
    [
        panel("Equatorial climate map", "spatial-map", ["EQUATOR -> persistent high solar receipt", "AMAZON + CONGO -> major continental lowlands", "MALAYSIA + EAST INDIES -> maritime expression", "HIGHLANDS / MARGINS -> altitude or monsoon modification"], ["Af location and equatorial setting"]),
        panel("Convection day cycle", "process-flow", ["MORNING SUN -> moist surface heating", "NOON ASCENT -> expanding and cooling air", "AFTERNOON -> cumulonimbus thunderstorm", "EVENING -> rain-cooled air; cycle can recur"], ["Equatorial low and convection", "Afternoon storms and equinox maxima"]),
        panel("Temperature-range firewall", "comparison-table", ["ANNUAL RANGE -> usually very small", "DIURNAL RANGE -> larger than annual range", "CAUSE -> weak seasonality near Equator", "CAUTION -> means do not cap daily extremes"], ["Uniform heat and annual range", "Diurnal range exceeds annual range"]),
        panel("Rainfall identity", "decision-tree", ["RAIN ALL MONTHS -> supports Af reading", "TRUE DRY SEASON -> test Am or Aw instead", "TOTAL -> source notes often 150-250 cm", "RULE -> distribution outranks one annual number"], ["Year-round rainfall regime"]),
        panel("Rainforest vertical profile", "vertical-map", ["EMERGENTS -> crowns above main roof", "CANOPY -> dense light-capturing layer", "UNDERSTOREY -> shade-tolerant growth", "FLOOR -> dark, humid, rapid decay"], ["Rainforest layers"]),
        panel("Nutrient-cycle loop", "causal-system", ["LITTER -> rapid warm-wet decomposition", "ROOT MAT -> rapid nutrient uptake", "BIOMASS -> principal nutrient capital", "HEAVY RAIN -> leaching after clearance"], ["Nutrient paradox"]),
        panel("Fallow decision", "decision-tree", ["SMALL CLEARING + LONG FALLOW -> recovery", "SHORTENED FALLOW -> declining biomass", "STEEP SLOPE + REPEATED FIRE -> erosion risk", "TENURE + LIVELIHOOD -> management outcome"], ["Shifting cultivation and fallow"]),
        panel("Humid-tropics economy", "comparison-table", ["PLANTATION -> capital + labour + export crop", "MIXED FOREST -> selective logging difficulty", "RIVER / ROAD ACCESS -> extraction geography", "RULE -> climate enables; institutions decide"], ["Plantations and commercial forestry"]),
        panel("India analogue map", "spatial-map", ["WESTERN GHATS -> windward evergreen belt", "NORTH-EAST -> wet evergreen / semi-evergreen", "EASTERN HIMALAYAN FOOTHILLS -> transition", "ANDAMAN-NICOBAR -> insular rainforest"], ["India's equatorial-type boundary", "Indian evergreen distribution"]),
        panel("Official evidence firewall", "evidence-table", ["FSI REPORT -> dated biennial assessment", "FOREST COVER -> canopy-based mapped class", "FOREST TYPE -> ecological classification", "LEGAL STATUS -> separate administrative category"], ["Biodiversity, jhum and FSI evidence"]),
        panel("Verified PYQ pair", "exam-matrix", ["2021 -> rainforest vegetation structure", "2023 -> nutrients and decomposition", "LEDGER -> official answer letters withheld", "METHOD -> teach distinction; do not invent key"], ["Verified rainforest PYQ routes"]),
        panel("Equatorial answer spine", "answer-spine", ["LOCATE -> equatorial lowland belt", "DERIVE -> heat, convergence, convection, rain", "LINK -> layers, nutrients and land use", "QUALIFY -> India analogue and source limits"], ["Verified rainforest PYQ routes"]),
    ],
    ["Koppen Af", "diurnal range exceeds annual range", "convection", "equinoxes", "selva", "emergents", "lianas", "epiphytes", "nutrient capital", "leaching", "shifting cultivation", "Western Ghats", "Andaman-Nicobar", "Forest Survey of India"],
    "Verified direct routing retains the 2021 Prelims tropical-rainforest vegetation-structure demand and the 2023 Prelims rainforest nutrient/decomposition demand. The local ledger withholds both official answer letters, so the package teaches the tested distinctions and does not manufacture an objective key.",
    [
        ("2021", "Prelims GS-I", "Tropical rain forest vegetation structure identification.", "Verified routed objective demand; official key unavailable locally.", "Use evergreen multi-storeyed structure, emergents, canopy, under-storeys, lianas and epiphytes to evaluate the statements. Preserve the official option order and do not invent an answer letter."),
        ("2023", "Prelims GS-I", "Tropical rainforest soil nutrient levels and decomposition rate.", "Verified routed objective demand; official key unavailable locally.", "Use rapid warm-wet decomposition, strong leaching and biomass-centred nutrient cycling. Distinguish rich standing vegetation from generally nutrient-poor, quickly depleted cleared soils; do not manufacture a key."),
    ],
    [
        "https://fsi.nic.in/publications",
        "https://fsi.nic.in/uploads/isfr2023/isfr_book_eng-vol-1_2023.pdf",
        "https://fsi.nic.in/uploads/isfr2023/isfr_book_eng-vol-2_2023.pdf",
    ],
    "Rechecked 5 September 2026: FSI's official publications surface describes the State of Forest Report as biennial, and ISFR 2023 Volumes I-II remain the latest located official national assessment; no official ISFR 2025 release was located. Forest-cover classes and state tables are therefore cited only as ISFR 2023 evidence, never as a September 2026 measurement or as tropical-evergreen extent. Forest cover, recorded forest area, ecological forest type and legal status remain separate.",
    extra=["basic/04_Weathering-MassMovement-Groundwater.md", "basic/16_Tropical-Monsoon-and-Marine-Climate.md"],
)


TOPIC_16 = common.topic(
    16,
    "Tropical Monsoon and Marine Climate",
    "16_Tropical-Monsoon-and-Marine-Climate.md",
    "16_India-Monsoon-Mechanism.md",
    "16_India-Monsoon-Mechanism_Complete-Topic-Package.md",
    [
        ("Am and marine distinction", "Tropical monsoon or Koppen Am climate has a pronounced seasonal wind reversal and concentrated wet season, whereas tropical marine climates receive moist onshore Trade Winds for much of the year and generally have steadier rainfall."),
        ("Monsoon distribution", "Source texts commonly place tropical monsoon climates on tropical continental margins roughly 10 to 30 degrees north and south, best developed over the Indian subcontinent; local boundaries depend on relief and classification."),
        ("Complete seasonal reversal", "The defining monsoon feature is a seasonal reversal between moist summer onshore flow and generally drier winter offshore flow; it is not merely a stronger sea breeze."),
        ("Three-level mechanism", "A complete explanation combines land-sea thermal contrast, seasonal ITCZ or monsoon-trough migration and upper-air circulation involving the subtropical westerly and tropical easterly jets."),
        ("Indian seasonal sequence", "The hot-weather season builds the continental thermal low, the southwest monsoon advances in summer, withdrawal follows weakening heating, and the retreating or northeast phase shifts rain toward the south-east coast."),
        ("Burst and onset normal", "The burst is the abrupt establishment of widespread monsoon rain; the climatological onset normal near 1 June over Kerala is a reference date, not an annual deadline or a measure of seasonal success."),
        ("Arabian Sea branch", "The Arabian Sea branch strikes the Western Ghats, producing heavy windward rain and a leeward Deccan rain shadow; later rainfall depends on trajectory, relief and embedded systems."),
        ("Bay of Bengal branch", "The Bay branch enters North-East India and the Ganga plain, where Himalayan blocking and west-north-westward movement distribute rain; Bay depressions are major rain-bearing systems."),
        ("Tropical marine setting", "Tropical marine climate occurs on many eastern tropical coasts and islands under persistent onshore Trades, including parts of the Caribbean, eastern Brazil, East Africa, Madagascar, the Philippines and north-eastern Australia."),
        ("Rainfall reliability contrast", "Monsoon rainfall is strongly seasonal and variable in onset, distribution, breaks and withdrawal, while tropical marine rainfall is generally more evenly spread; neither regime guarantees hazard-free agriculture."),
        ("Vegetation gradient", "Monsoon vegetation grades from evergreen or moist forest through deciduous woodland to savanna and thorn scrub as rainfall amount and dry-season length change."),
        ("Active and break spells", "Active spells accompany a favourably placed monsoon trough and rain-bearing systems, while breaks shift or weaken the rain zone and can dry the plains even within a season of normal national total."),
        ("Jet-stream boundary", "Northward withdrawal of the subtropical westerly jet from south of the Himalaya and establishment of tropical easterly flow accompany onset, but neither jet is a deterministic single switch."),
        ("Western-disturbance boundary", "Western disturbances are extra-tropical westerly winter systems that bring rain or snow to north-west India and the western Himalaya; they are not monsoon depressions."),
        ("ENSO and IOD", "ENSO and the Indian Ocean Dipole modify monsoon probabilities and spatial distribution; an El Nino does not guarantee drought and a positive IOD does not guarantee compensation."),
        ("MJO timescale", "The Madden-Julian Oscillation is an eastward-moving intra-seasonal tropical convective signal that can favour active or break spells; it differs in timescale and geography from ENSO."),
        ("Northeast-monsoon rain", "During retreat, northeasterly flow crossing the Bay of Bengal acquires moisture and gives the Tamil Nadu or Coromandel coast its principal rainy season; retreat is not the same as a short break."),
        ("IMD status discipline", "IMD seasonal forecasts, onset declarations, daily observations and end-season verification are different products; as of 1 September 2026 the season is incomplete, so a forecast or current bulletin cannot be presented as the final 2026 outcome."),
        ("Verified Purvaiya route", "The routed 2023 GS-I demand asks why the southwest monsoon is called Purvaiya in Bhojpur and how it shaped cultural ethos, requiring physical wind direction to be linked with regional language, agriculture and memory."),
        ("Verified island-climate route", "The routed 2026 Prelims demand concerns Andaman-Nicobar climate and seasonal precipitation; the local Set-A key is provisional, so no answer letter is recorded or inferred."),
    ],
    [
        "Do not merge tropical monsoon and tropical marine climates.",
        "Do not reduce the monsoon to a giant sea breeze.",
        "Do not call every summer rain system a monsoon depression.",
        "Do not treat a normal Kerala onset date as a fixed deadline.",
        "Do not reverse the Arabian Sea and Bay of Bengal branches.",
        "Do not equate a break with seasonal withdrawal.",
        "Do not classify western disturbances as monsoon systems.",
        "Do not use ENSO, IOD or MJO as deterministic switches.",
        "Do not claim Tamil Nadu's principal rain comes from the southwest branch.",
        "Do not use an IMD forecast as observed final rainfall.",
        "Do not detach Purvaiya cultural meaning from Bhojpur's regional wind perception.",
        "Do not invent a final 2026 Prelims key or seasonal monsoon result.",
    ],
    [
        (10, "Distinguish tropical monsoon climate from tropical marine climate.", "Seasonal wind reversal and concentrated rainfall define Am, whereas persistent onshore Trades give tropical marine coasts a steadier moisture supply.", [0, 1, 8, 9]),
        (10, "Explain why the burst of the monsoon is an onset concept rather than a seasonal-outcome measure.", "Burst records abrupt circulation establishment near a climatological date, but later distribution, breaks and withdrawal determine performance.", [3, 4, 5]),
        (15, "Explain the Arabian Sea and Bay of Bengal branches of the Indian monsoon.", "Peninsular geometry, the Western Ghats, Himalaya and Bay depressions create different routes, rain shadows and inland rainfall gradients.", [6, 7]),
        (15, "Analyse active-break variability and its agricultural significance.", "Trough shifts, embedded systems and MJO-scale convection redistribute rain within weeks, so crop stress depends on timing as much as seasonal total.", [11, 15, 17]),
        (20, "Critically compare thermal, dynamic and upper-air explanations of the Indian monsoon.", "Land-sea contrast, ITCZ migration and jet reorganisation are complementary levels, while teleconnections modify rather than dictate the realised season.", [2, 3, 12, 14]),
        (20, "Use verified PYQ routes to explain the monsoon as both a physical and cultural system.", "Purvaiya joins regional wind perception to agriculture and culture, while island rainfall tests spatial seasonality; both require source and key discipline.", [16, 18, 19]),
    ],
    [
        plan("Monsoon and tropical marine identities", [0, 1], "Related tropical climates are not synonyms.", "Compare wind direction and rainfall distribution."),
        plan("Seasonal reversal", [2], "Monsoon is more than a sea-breeze scale response.", "Start from pressure reversal."),
        plan("Thermal, ITCZ and upper-air mechanism", [3], "The three levels complement one another.", "Build a nested causal explanation."),
        plan("India's four-season circulation", [4], "Season names describe a sequence, not fixed dates.", "Trace heating, advance, retreat and winter flow."),
        plan("Burst and onset", [5], "Onset timing does not measure seasonal success.", "Separate normal, declaration and outcome."),
        plan("Arabian Sea branch", [6], "Orography does not explain all branch rainfall.", "Map windward Ghats and Deccan shadow."),
        plan("Bay branch and depressions", [7], "The Bay route is deflected and depleted inland.", "Connect Himalaya, plains and lows."),
        plan("Tropical marine coasts", [8], "Persistent onshore Trades differ from full reversal.", "Locate eastern tropical margins and islands."),
        plan("Rainfall reliability and vegetation", [9, 10], "A wet annual total can remain seasonally risky.", "Link dry-season length to vegetation."),
        plan("Active and break monsoon", [11], "A break is intra-seasonal, not withdrawal.", "Use trough-position and crop-stage logic."),
        plan("Jet-stream reorganisation", [12], "No single jet guarantees onset or rainfall.", "Place STWJ and easterly flow in wider circulation."),
        plan("Western disturbances", [13], "Winter frontal systems are outside monsoon physics.", "Compare origin, season and precipitation."),
        plan("ENSO, IOD and MJO", [14, 15], "Teleconnections shift probability, not destiny.", "Separate inter-annual and intra-seasonal scales."),
        plan("Northeast monsoon and IMD products", [16, 17], "Forecast, observation and verification differ.", "Explain Coromandel rain with status discipline."),
        plan("Verified Purvaiya and island PYQs", [18, 19], "Cultural route and provisional key need separate treatment.", "End with physical-to-human integration."),
    ],
    [
        panel("Climate-type discriminator", "comparison-table", ["MONSOON Am -> seasonal wind reversal", "TROPICAL MARINE -> onshore Trades most months", "MONSOON RAIN -> strongly concentrated", "MARINE RAIN -> generally steadier distribution"], ["Monsoon and tropical marine identities"]),
        panel("Three-level monsoon engine", "causal-system", ["THERMAL -> land-sea pressure reversal", "DYNAMIC -> seasonal ITCZ migration", "UPPER AIR -> jet reorganisation", "OUTCOME -> cross-equatorial moist flow"], ["Thermal, ITCZ and upper-air mechanism"]),
        panel("Seasonal circulation rail", "seasonal-map", ["MAR-MAY -> thermal low and local storms", "JUN-SEP -> southwest advance and rain", "OCT-NOV -> withdrawal and Bay systems", "DEC-FEB -> dry NE flow; WDs in north-west"], ["India's four-season circulation"]),
        panel("Onset evidence ladder", "evidence-ladder", ["NORMAL DATE -> long-period reference", "ONSET DECLARATION -> observed criteria met", "BURST -> abrupt rain establishment", "SEASON RESULT -> verified only after completion"], ["Burst and onset", "Northeast monsoon and IMD products"]),
        panel("Arabian Sea branch map", "spatial-map", ["ARABIAN SEA -> moisture-bearing branch", "WESTERN GHATS -> windward uplift and rain", "LEEWARD DECCAN -> rain shadow", "INTERIOR -> systems and relief modify totals"], ["Arabian Sea branch"]),
        panel("Bay branch map", "spatial-map", ["BAY OF BENGAL -> branch and depressions", "NORTH-EAST HILLS -> forced uplift", "HIMALAYA -> blocks northward escape", "GANGA PLAIN -> west-north-west rain route"], ["Bay branch and depressions"]),
        panel("Active-break switch", "decision-tree", ["TROUGH OVER PLAINS -> widespread active rain", "BAY LOWS -> inland rain corridors", "TROUGH TO FOOTHILLS -> plains break", "CROP STAGE -> impact can exceed total deficit"], ["Active and break monsoon"]),
        panel("Jet and WD firewall", "comparison-table", ["STWJ -> winter upper-air westerly regime", "TROPICAL EASTERLY FLOW -> summer monsoon aloft", "WESTERN DISTURBANCE -> extra-tropical system", "MONSOON DEPRESSION -> tropical rain-bearing low"], ["Jet-stream reorganisation", "Western disturbances"]),
        panel("Variability timescales", "comparison-table", ["MJO -> weeks / active-break modulation", "ENSO -> inter-annual Pacific signal", "IOD -> Indian Ocean seasonal signal", "RULE -> none is a deterministic switch"], ["ENSO, IOD and MJO"]),
        panel("Coromandel rain chain", "process-flow", ["SW MONSOON WITHDRAWS -> flow reverses", "NE FLOW CROSSES BAY -> moisture gained", "TAMIL NADU COAST -> onshore exposure", "RAIN + CYCLONE RISK -> retreating season"], ["Northeast monsoon and IMD products"]),
        panel("Verified PYQ routes", "exam-matrix", ["2023 GS-I -> Purvaiya and cultural ethos", "2026 PRELIMS -> island climate and rain", "2026 KEY -> provisional; no letter inferred", "METHOD -> map wind, season and regional meaning"], ["Verified Purvaiya and island PYQs"]),
        panel("Monsoon answer spine", "answer-spine", ["DEFINE -> reversal and marine contrast", "DERIVE -> thermal, ITCZ and jets", "MAP -> branches, breaks and retreat", "QUALIFY -> teleconnections and source status"], ["Verified Purvaiya and island PYQs"]),
    ],
    ["Koppen Am", "complete seasonal reversal", "monsoon trough", "Arabian Sea branch", "Bay of Bengal branch", "burst of the monsoon", "subtropical westerly jet", "tropical easterly jet", "western disturbances", "Madden-Julian Oscillation", "ENSO", "Indian Ocean Dipole", "Purvaiya", "Coromandel coast"],
    "Verified direct ownership includes the cross-cutting 2023 GS-I Purvaiya demand and the 2026 Prelims Andaman-Nicobar climate demand. The 2026 local Set-A key is provisional, so no objective answer is inferred; unrelated ocean-temperature and cultural-geography questions remain with their routed co-owners.",
    [
        ("2023", "GS-I", "Why is the South-West Monsoon called Purvaiya in Bhojpur Region? How has this directional seasonal wind system influenced the cultural ethos of the region? (150 words)", "Verified routed cross-cutting Mains demand.", "Explain the locally perceived easterly arrival path and moisture-bearing seasonal wind, then connect rainfall timing with sowing, songs, festivals, migration memory and regional vocabulary. Qualify that Purvaiya is a cultural-directional name within a wider southwest-monsoon circulation."),
        ("2026", "Prelims GS-I", "Andaman and Nicobar climate, monsoon rainfall, and seasonal precipitation.", "Verified routed objective demand; provisional 2026 Set-A key present locally, answer not inferred.", "Map the islands' maritime setting and exposure to both monsoon phases, then test any statement against seasonal precipitation rather than assuming one mainland pattern. Preserve option order and do not state an answer letter."),
    ],
    [
        "https://mausam.imd.gov.in/responsive/seasonal_forecast.php",
        "https://mausam.imd.gov.in/responsive/monsooninformation.php",
        "https://pib.gov.in/PressReleaseIframePage.aspx?PRID=2067907",
    ],
    "IMD's official seasonal-forecast and monsoon-information pages are used to separate forecast, onset monitoring, observation and verification. Mission Mausam is used only as an official observation-and-forecasting capacity anchor. Because the 2026 southwest-monsoon season was incomplete on 1 September 2026, no final rainfall outcome or anomaly is claimed.",
    extra=["basic/12_The-Oceans-Currents-Tides-Salinity.md", "advanced/13_India-JetStream-Western-Disturbances.md", "advanced/37_Cultural-and-Social-Geography-of-India.md"],
)


TOPIC_17 = common.topic(
    17,
    "Savanna Sudan Climate",
    "17_Savanna-Sudan-Climate.md",
    "17_India-Deciduous-and-Grasslands.md",
    "17_India-Deciduous-and-Grasslands_Complete-Topic-Package.md",
    [
        ("Aw transition belt", "Savanna or Sudan climate, commonly Koppen Aw, is a tropical transition between equatorial rainforest and hot desert, often mapped roughly from 5 to 20 degrees north and south; it is a gradient rather than a sharp line."),
        ("Global savanna regions", "The Sudan belt of Africa is the classic expression, while the Llanos, Campo Cerrado and northern Australia are major regional examples with different soils, fire histories and land use."),
        ("Wet-dry circulation", "Poleward and equatorward migration of the ITCZ alternates a hot rainy high-sun season with a warm or cooler dry low-sun season dominated by drier trade-wind air."),
        ("Source rainfall range", "Source notes commonly describe about 75 to 150 centimetres of summer-concentrated rain; the decisive feature is a marked dry season, and totals decline toward desert margins."),
        ("Rainfall unreliability", "Late onset, early cessation, long dry spells and drought make water reliability more important than annual total for crops, livestock and settlement."),
        ("Parkland grass-tree form", "Savanna has a continuous or near-continuous grass layer with scattered trees, producing a parkland appearance; grasses generally become shorter and woody cover more open toward the desert margin."),
        ("Drought adaptations", "Deciduous habit, deep roots, thick bark, small leaves and umbrella crowns help trees such as acacia and baobab withstand seasonal drought, browsing and fire."),
        ("Fire-grazing interaction", "Seasonal climate makes grassland possible, while recurrent fire and herbivory suppress some tree recruitment and help maintain the grass-tree mosaic; neither climate-only nor fire-only explanation is sufficient."),
        ("Wildlife system", "Savannas support large grazing and browsing herds and associated predators because seasonal grass production, water and migration create a spatially dynamic food web."),
        ("Livelihood adaptations", "Pastoral mobility and drought-tolerant crops such as millet and sorghum respond to variable water and forage; forced sedentarisation or fixed water points can concentrate grazing pressure."),
        ("Soil-degradation risk", "Strong wet-dry alternation can promote leaching, lateritic tendencies, surface sealing, erosion and fire exposure after vegetation loss; savanna soils are not uniformly infertile."),
        ("India analogue boundary", "India has wet-dry tropical environments and savanna-like mosaics, but the Advanced owner is an analogue of deciduous forest, thorn scrub and grasslands rather than proof that India is one homogeneous Sudan climate."),
        ("Moist deciduous belt", "Indian source notes associate tropical moist deciduous forest broadly with about 100 to 200 centimetres of rainfall, with teak prominent in many peninsular belts and sal in many northern and eastern belts."),
        ("Dry deciduous belt", "Dry deciduous forests occupy drier monsoon interiors and shed leaves to reduce dry-season water loss; rainfall thresholds overlap regionally and should not be treated as exact national walls."),
        ("Thorn and scrub belt", "Tropical thorn forest and scrub reflect climatic aridity interacting with grazing and cutting, grading through north-western and interior semi-arid belts; they are not invariably degraded moist forest."),
        ("Distinct Indian grasslands", "Terai tall grasslands, shola grassland-forest mosaics and Banni's arid-saline grassland have different hydrology and histories; one universal fire or grazing prescription is unsafe."),
        ("Restoration design", "Savanna and dryland restoration should protect native grass-forb-tree mosaics, water processes, mobility and disturbance regimes rather than equating restoration with dense tree planting everywhere."),
        ("Aravalli Green Wall boundary", "Official PIB material presents the Aravalli Green Wall as landscape restoration involving native vegetation, water-body rejuvenation and multi-state coordination; it should not be reduced to one uniform plantation strip or uncited target."),
        ("Verified savanna PYQ route", "The routed 2021 Prelims demand tests conditions limiting tree development in savanna; the ledger withholds the official answer letter, so rainfall seasonality, fire and herbivory are taught as interacting controls."),
        ("Savanna management verdict", "A defensible policy distinguishes natural open ecosystems from degraded land and manages water, grazing, fire, invasives and livelihoods together; increasing tree density is not automatically ecological improvement."),
    ],
    [
        "Do not draw Aw as a sharp border between rainforest and desert.",
        "Do not treat all global savannas as identical Sudan replicas.",
        "Do not say rainfall is evenly distributed through the year.",
        "Do not infer reliability from a moderate annual rainfall total.",
        "Do not portray savanna as treeless steppe.",
        "Do not explain the grass-tree balance by climate alone.",
        "Do not describe every fire as external ecological damage.",
        "Do not treat pastoral mobility as irrational backwardness.",
        "Do not equate every Indian grassland with Banni, Terai or shola.",
        "Do not force rigid rainfall thresholds across Indian forest belts.",
        "Do not equate restoration with dense plantation on natural grassland.",
        "Do not invent the 2021 objective answer letter or Green Wall outcome figures.",
    ],
    [
        (10, "Why is the Sudan climate described as a tropical transition?", "ITCZ seasonality produces a wet-dry gradient between rainforest and desert, expressed in changing rain duration, grass height and woody cover.", [0, 2, 3]),
        (10, "Explain why savanna is a grass-tree mosaic rather than a closed forest.", "Seasonal moisture limits interact with fire and herbivory to suppress recruitment while drought-adapted trees persist.", [5, 6, 7]),
        (15, "Assess rainfall unreliability as the central livelihood constraint in savanna lands.", "Timing and dry spells govern forage and crop risk, encouraging mobility and drought-tolerant cultivation more than annual totals alone.", [4, 8, 9]),
        (15, "Compare global savanna with India's deciduous, thorn and grassland analogues.", "Both reflect wet-dry seasonality, but India's forest and grassland mosaics differ by monsoon, soil, hydrology and management history.", [11, 12, 13, 14, 15]),
        (20, "Critically examine fire and grazing in savanna ecology and restoration.", "They can maintain biodiversity-rich open mosaics or cause degradation depending on timing, intensity and context, so restoration cannot default to fire exclusion or dense planting.", [7, 15, 16, 19]),
        (20, "Evaluate the Aravalli Green Wall through savanna and dryland geography.", "Judge native ecosystem recovery, water, connectivity and livelihoods rather than plantation area alone, while retaining official status and target discipline.", [14, 16, 17, 18, 19]),
    ],
    [
        plan("Aw transition and global map", [0, 1], "A climate gradient is not a political belt.", "Locate Sudan, Llanos, Cerrado and northern Australia."),
        plan("ITCZ wet-dry rhythm", [2], "Seasonal migration, not distance alone, makes the two seasons.", "Draw the high-sun and low-sun circulation."),
        plan("Rainfall amount and reliability", [3, 4], "Distribution and timing outrank one total.", "Translate dry spells into livelihood risk."),
        plan("Parkland grass-tree structure", [5], "Savanna is neither closed forest nor treeless steppe.", "Use the equator-to-desert vegetation gradient."),
        plan("Tree drought adaptations", [6], "Adaptations answer seasonal stress, fire and browsing together.", "Link form to function."),
        plan("Fire and grazing controls", [7], "Climate permits; disturbance helps maintain.", "Reject single-cause explanations."),
        plan("Wildlife and migration", [8], "Large fauna depend on seasonal space and water.", "Connect grass production to movement."),
        plan("Pastoral and farming adaptation", [9], "Mobility can be rational risk management.", "Use water-point pressure as a qualification."),
        plan("Soils and degradation", [10], "Savanna soils are heterogeneous.", "Trace wet-dry weathering and cover loss."),
        plan("India analogue boundary", [11], "Analogue does not mean climate identity.", "Keep global Basic before India Advanced."),
        plan("Moist and dry deciduous forests", [12, 13], "Thresholds overlap and species dominance varies.", "Compare leaf-shedding and rainfall belts."),
        plan("Thorn scrub and open ecosystems", [14], "Thorn is not always degraded moist forest.", "Separate aridity from land-use intensification."),
        plan("Terai, shola and Banni", [15], "Indian grasslands need ecosystem-specific management.", "Compare hydrology, altitude and salinity."),
        plan("Restoration and Aravalli Green Wall", [16, 17], "Official project language is not proof of outcomes.", "Prioritise native mosaics, water and connectivity."),
        plan("Verified savanna PYQ and verdict", [18, 19], "No official answer letter is locally available.", "Use climate-fire-herbivory interaction."),
    ],
    [
        panel("Savanna transition map", "spatial-map", ["EQUATORWARD -> wetter and taller grass", "SUDAN BELT -> classic wet-dry savanna", "POLEWARD -> shorter grass and open trees", "DESERT MARGIN -> drought risk intensifies"], ["Aw transition and global map"]),
        panel("ITCZ seasonal switch", "seasonal-map", ["HIGH-SUN SEASON -> ITCZ approaches", "CONVERGENCE + CONVECTION -> summer rain", "LOW-SUN SEASON -> dry trades dominate", "RESULT -> hot wet / warm dry rhythm"], ["ITCZ wet-dry rhythm"]),
        panel("Water-reliability chain", "hazard-flow", ["LATE ONSET -> delayed sowing", "MID-SEASON BREAK -> crop and forage stress", "EARLY CESSATION -> incomplete grain filling", "DROUGHT -> migration and herd loss risk"], ["Rainfall amount and reliability"]),
        panel("Grass-tree gradient", "replacement-diagram", ["WET MARGIN -> tall grass + more trees", "CORE SAVANNA -> parkland mosaic", "DRY MARGIN -> short grass + thorny shrubs", "DESERT EDGE -> discontinuous vegetation"], ["Parkland grass-tree structure"]),
        panel("Fire-herbivory balance", "causal-system", ["SEASONAL RAIN -> grass biomass", "DRY SEASON -> combustible fuel", "FIRE + BROWSING -> seedling suppression", "THICK BARK + ROOTS -> selected tree survival"], ["Tree drought adaptations", "Fire and grazing controls"]),
        panel("Wildlife-livelihood matrix", "comparison-table", ["HERDS -> follow seasonal forage and water", "PREDATORS -> track herbivore concentrations", "PASTORALISTS -> mobility spreads risk", "CULTIVATORS -> millet / sorghum timing"], ["Wildlife and migration", "Pastoral and farming adaptation"]),
        panel("Degradation pathway", "process-flow", ["COVER LOSS -> raindrop and wind exposure", "WET SEASON -> runoff, leaching and erosion", "DRY SEASON -> fire and surface sealing", "FIXED WATER POINT -> local grazing concentration"], ["Soils and degradation"]),
        panel("India forest gradient", "comparison-table", ["MOIST DECIDUOUS -> longer wet season", "DRY DECIDUOUS -> stronger leaf-shedding", "THORN / SCRUB -> semi-arid moisture stress", "RULE -> overlapping belts, not fixed walls"], ["India analogue boundary", "Moist and dry deciduous forests", "Thorn scrub and open ecosystems"]),
        panel("Indian grassland firewall", "comparison-table", ["TERAI -> humid tall grass and floodplain", "SHOLA -> montane grass-forest mosaic", "BANNI -> arid-saline Kachchh grassland", "MANAGEMENT -> hydrology and history first"], ["Terai, shola and Banni"]),
        panel("Restoration decision tree", "decision-tree", ["NATURAL OPEN ECOSYSTEM -> conserve openness", "DEGRADED SCRUB -> restore native mosaic", "WATER PROCESS -> recharge and drainage", "LIVELIHOOD -> grazing and tenure design"], ["Restoration and Aravalli Green Wall"]),
        panel("Savanna PYQ firewall", "exam-matrix", ["2021 PRELIMS -> tree-limiting conditions", "CLIMATE -> long dry season", "DISTURBANCE -> fire + herbivory", "LEDGER -> no answer letter invented"], ["Verified savanna PYQ and verdict"]),
        panel("Savanna answer spine", "answer-spine", ["LOCATE -> rainforest-desert transition", "DERIVE -> ITCZ and wet-dry season", "EXPLAIN -> grass-tree disturbance balance", "APPLY -> India mosaics and restoration"], ["Verified savanna PYQ and verdict"]),
    ],
    ["Koppen Aw", "Sudan belt", "Llanos", "Campo Cerrado", "ITCZ", "parkland", "acacia", "baobab", "fire and grazing", "moist deciduous", "dry deciduous", "Banni", "Terai", "Aravalli Green Wall"],
    "Verified direct ownership retains the 2021 Prelims savanna tree-limitation demand. The routing ledger supplies no official answer letter, so the package teaches rainfall seasonality, fire and herbivory as tested distinctions without manufacturing a key; Sahel and Indian restoration examples remain analytical applications rather than relabelled PYQs.",
    [
        ("2021", "Prelims GS-I", "Savanna biome conditions limiting tree development.", "Verified routed objective demand; official key unavailable locally.", "Evaluate statements through the interaction of a marked dry season, moisture competition, recurrent fire and herbivory. Distinguish limits on tree recruitment from complete absence of trees, and do not invent an answer letter."),
    ],
    [
        "https://pib.gov.in/PressReleasePage.aspx?PRID=1910392",
        "https://pib.gov.in/PressReleasePage.aspx?PRID=1910745",
        "https://pib.gov.in/PressReleasePage.aspx?PRID=2214525",
    ],
    "Official PIB material is used only to establish the Aravalli Green Wall's landscape-restoration, native-vegetation, water-rejuvenation and coordination logic. Conflicting or evolving area, width, finance and completion figures are omitted, and project announcements are not treated as verified ecological outcomes.",
    extra=["basic/07_Arid-Desert-Landforms.md", "basic/20_Temperate-Continental-Steppe-Climate.md"],
)


TOPIC_18 = common.topic(
    18,
    "Hot and MidLatitude Desert Climate",
    "18_Hot-and-MidLatitude-Desert-Climate.md",
    "18_Thar-Desert-and-GIB.md",
    "18_Thar-Desert-and-GIB_Complete-Topic-Package.md",
    [
        ("Aridity definition", "A desert is defined by persistent moisture deficit or scanty precipitation relative to demand, not by heat, sand or absence of life; polar, coastal and mid-latitude deserts show why aridity, not heat, is the master criterion."),
        ("Hot and mid-latitude types", "Hot BWh examples include Sahara, Arabian, Thar, Namib, Atacama and Australian deserts, while cold or mid-latitude BWk examples include Gobi, Turkestan and Patagonian sectors."),
        ("Subtropical subsidence", "Descending air in subtropical high-pressure belts warms adiabatically, lowers relative humidity and suppresses cloud development, helping locate many hot deserts around the subtropical margins."),
        ("Offshore-wind effect", "On western subtropical margins and some interiors, prevailing airflow may be offshore or have travelled over dry land, limiting oceanic moisture supply; it is one cause among several."),
        ("Cold-current deserts", "Cold currents such as the Humboldt Current or Peru Current and the Benguela Current stabilise lower air and reduce convection, so coastal deserts may be cool or foggy yet receive little rain; cold water does not automatically produce rainfall."),
        ("Continentality", "Mid-latitude interiors lie far from maritime moisture sources and may be enclosed by large land masses, creating severe annual thermal ranges and low precipitation."),
        ("Rain-shadow aridity", "Mountains remove moisture on windward slopes and leave leeward basins dry; Patagonia east of the Andes is a classic example, while rain shadow often reinforces rather than solely creates a desert."),
        ("Scanty erratic rain", "Source notes commonly use annual precipitation below about 25 centimetres for true-desert examples, but the defining condition is long-term water deficit and high variability, not a universal cutoff."),
        ("Thermal contrast", "Hot deserts are especially known for large diurnal ranges under clear skies, whereas mid-latitude deserts add very cold winters and a much larger annual range."),
        ("Cloudburst and wadi", "Rare intense storms can exceed infiltration, producing flash floods in normally dry channels or wadis; low annual rainfall does not mean low flood hazard."),
        ("Xerophytic adaptations", "Reduced or waxy leaves, thorns, water-storing tissues, deep or spreading roots and widely spaced growth reduce water loss or improve access; no single trait defines every desert plant."),
        ("Oasis groundwater", "An oasis forms where groundwater, springs or river-fed irrigation make water accessible, permitting date palms and cultivation; it is not a rainfall-fed forest island."),
        ("Human water strategy", "Pastoral mobility, wells, tanks, gravity conduits, exotic rivers, canals and modern irrigation organise desert settlement, while over-abstraction, waterlogging and salinity can relocate the constraint."),
        ("Thar location", "The Thar lies chiefly in western Rajasthan, extending into adjoining Indian states and Pakistan; its Indian core lies west of the Aravallis with a gradient toward less arid margins."),
        ("Thar aridity mechanism", "The Aravallis run broadly parallel to the Arabian Sea monsoon branch and force little ascent, while continentality, subsiding air and weak Bay-branch penetration reinforce low rainfall."),
        ("Thar landforms and drainage", "Barchans, seif dunes, sand sheets, playas or dhands and inland drainage characterise the Thar; the Luni is the principal inland-draining river, while salt-lake histories are locally specific."),
        ("Thar adaptation and transformation", "Tanka, khadin and johad harvesting, pastoralism and dryland crops represent adaptation, while the Indira Gandhi Canal, irrigation and renewable-energy infrastructure transform water, soil and settlement patterns."),
        ("Great Indian Bustard boundary", "The Great Indian Bustard is a Critically Endangered open-landscape species threatened by habitat change and collision risk; conservation and renewable transmission require spatial planning, but no undated population estimate is used."),
        ("UNCCD COP16 boundary", "UNCCD COP16 met in Riyadh from 2 to 13 December 2024 and advanced drought-resilience and land-restoration work, but did not finalise a binding global drought framework; pledge totals and future negotiations require dated official decisions."),
        ("Transparent zero-direct route", "The audited Geography ledgers contain no direct question owned by Topic 18; desert-lake, landform, biodiversity and land-degradation questions remain with their routed owners, so no PYQ wording or key is invented."),
    ],
    [
        "Do not define desert by heat or sand cover.",
        "Do not call the Gobi a hot tropical desert.",
        "Do not use subtropical subsidence as the sole cause of every desert.",
        "Do not say cold currents bring abundant coastal rain.",
        "Do not omit continentality and rain shadow from mid-latitude deserts.",
        "Do not convert a source-era 25-centimetre guide into a universal legal threshold.",
        "Do not assume arid channels cannot flood.",
        "Do not call every thorny plant native to every desert.",
        "Do not explain oases by local rainfall alone.",
        "Do not claim the Aravallis effectively block the Arabian Sea branch.",
        "Do not treat canal irrigation or renewable power as cost-free desert improvement.",
        "Do not invent a direct PYQ, GIB population or COP16 binding outcome.",
    ],
    [
        (10, "Why must deserts be defined by aridity rather than heat?", "Cold-current coasts and mid-latitude interiors can be cold yet water-deficient, so moisture balance explains the shared desert condition.", [0, 1, 8]),
        (10, "Explain how cold ocean currents produce coastal deserts.", "Cold water stabilises lower air and suppresses convection, allowing fog without effective rainfall in Atacama and Namib settings.", [4]),
        (15, "Account for the world distribution of hot and mid-latitude deserts.", "Subtropical subsidence, offshore flow, cold currents, continentality and rain shadow combine differently across named deserts.", [2, 3, 4, 5, 6]),
        (15, "Compare environmental hazards and human adaptations in hot and mid-latitude deserts.", "Thermal regimes differ, but erratic storms, groundwater dependence and mobile or engineered water strategies organise both.", [7, 8, 9, 10, 11, 12]),
        (20, "Explain why the Thar is arid despite lying within monsoon India, and assess its transformation.", "Parallel Aravallis and weak moisture penetration create aridity, while harvesting, canal irrigation and energy infrastructure bring gains alongside salinity and habitat trade-offs.", [13, 14, 15, 16]),
        (20, "Use the GIB and UNCCD COP16 cases to frame a just dryland-development strategy.", "Combine open-ecosystem conservation, transmission planning, drought preparedness, land restoration and source-bounded monitoring without treating announcements as outcomes.", [17, 18, 19]),
    ],
    [
        plan("Aridity, not heat", [0], "Sand and temperature are secondary identifiers.", "Open with the moisture-deficit test."),
        plan("Hot and mid-latitude desert map", [1], "Type names must match latitude and winter regime.", "Locate Sahara, Atacama, Gobi and Patagonia."),
        plan("Subtropical subsidence", [2], "Subsidence is powerful but not universal.", "Use adiabatic warming and cloud suppression."),
        plan("Offshore winds and cold currents", [3, 4], "Fog can coexist with extreme aridity.", "Compare moisture supply and atmospheric stability."),
        plan("Continentality and rain shadow", [5, 6], "Interior and leeward causes often reinforce each other.", "Use Gobi and Patagonia contrasts."),
        plan("Rainfall and temperature regimes", [7, 8], "A guide value is not a universal cutoff.", "Separate diurnal from annual range."),
        plan("Flash floods and wadis", [9], "Low annual rain can still produce intense runoff.", "Trace cloudburst to channel flood."),
        plan("Xerophytes and oasis ecology", [10, 11], "One adaptation does not fit every species.", "Link plant form and groundwater access."),
        plan("Desert societies and water", [12], "Technology relocates rather than erases water limits.", "Compare mobility, wells, canals and salinity."),
        plan("Thar location and gradient", [13], "The Indian desert has a core and margins.", "Map west of Aravallis and adjoining regions."),
        plan("Why the Thar is arid", [14], "Aravalli orientation is not the only control.", "Combine branch geometry and continentality."),
        plan("Thar landforms and drainage", [15], "Not every playa shares the same origin.", "Connect dunes, dhands and Luni."),
        plan("Water harvesting and canal change", [16], "Irrigation has soil and ecological costs.", "Compare tanka-khadin-johad with canal systems."),
        plan("GIB and renewable-energy planning", [17], "Avoid undated population figures.", "Treat open habitat and transmission corridors spatially."),
        plan("UNCCD drought governance and PYQ boundary", [18, 19], "Conference progress is not a binding framework.", "Close with verified status and ownership."),
    ],
    [
        panel("Desert identity test", "decision-tree", ["MOISTURE DEFICIT -> desert criterion", "HOT + ARID -> BWh tendency", "COLD WINTER + ARID -> BWk tendency", "SAND / HEAT -> possible, not defining"], ["Aridity, not heat", "Hot and mid-latitude desert map"]),
        panel("Aridity cause matrix", "comparison-table", ["SUBSIDENCE -> stable descending air", "OFFSHORE FLOW -> weak moisture supply", "COLD CURRENT -> fog but weak convection", "CONTINENT / RAIN SHADOW -> inland dryness"], ["Subtropical subsidence", "Offshore winds and cold currents", "Continentality and rain shadow"]),
        panel("Cold-current coast", "process-flow", ["COLD WATER -> chilled marine boundary layer", "STABLE AIR -> weak vertical uplift", "FOG / MIST -> moisture without deep rain", "COASTAL DESERT -> aridity persists"], ["Offshore winds and cold currents"]),
        panel("Temperature firewall", "comparison-table", ["HOT DESERT -> very large day-night range", "MID-LATITUDE DESERT -> cold winter", "CLEAR SKY -> rapid nocturnal radiation", "RULE -> do not equate desert with constant heat"], ["Rainfall and temperature regimes"]),
        panel("Wadi flood chain", "hazard-flow", ["RARE INTENSE STORM -> high rain rate", "BARE / CRUSTED SURFACE -> rapid runoff", "DRY CHANNEL -> sudden flow concentration", "SETTLEMENT / ROAD -> flash-flood exposure"], ["Flash floods and wadis"]),
        panel("Plant-water adaptations", "classification-tree", ["LEAF -> reduced, waxy or thorny", "STEM -> water storage in some species", "ROOT -> deep tap or wide shallow network", "SPACING -> lower competition for water"], ["Xerophytes and oasis ecology"]),
        panel("Oasis and water strategy", "institutional-ladder", ["AQUIFER / SPRING / EXOTIC RIVER -> source", "WELL / CONDUIT / TANK -> access", "DATE PALM + CROPS -> layered use", "OVERUSE -> depletion, salinity or conflict"], ["Desert societies and water"]),
        panel("Thar aridity map", "spatial-map", ["ARABIAN SEA BRANCH -> approaches north-west", "ARAVALLIS -> broadly parallel orientation", "WEAK FORCED ASCENT -> little orographic rain", "CONTINENTALITY + SUBSIDENCE -> reinforce aridity"], ["Thar location and gradient", "Why the Thar is arid"]),
        panel("Thar landscape ledger", "evidence-table", ["DUNES -> barchan, seif and sand sheets", "DHANDS / PLAYAS -> inland salt basins", "LUNI -> principal inland-draining river", "KHEJRI / GRASS -> xeric open habitat"], ["Thar landforms and drainage"]),
        panel("Transformation trade-off", "comparison-table", ["TANKA / KHADIN / JOHAD -> local harvesting", "CANAL -> irrigation and settlement expansion", "RENEWABLE GRID -> low-carbon power", "RISKS -> salinity, waterlogging, habitat collision"], ["Water harvesting and canal change", "GIB and renewable-energy planning"]),
        panel("UNCCD status gate", "evidence-ladder", ["COP16 -> Riyadh, 2-13 December 2024", "LAND + DROUGHT -> resilience agenda advanced", "BINDING FRAMEWORK -> not finalised", "PYQ LEDGER -> no direct Topic 18 demand"], ["UNCCD drought governance and PYQ boundary"]),
        panel("Desert answer spine", "answer-spine", ["DEFINE -> aridity and water balance", "MAP -> circulation, current and relief causes", "COMPARE -> hot versus mid-latitude", "APPLY -> Thar, GIB and drought governance"], ["UNCCD drought governance and PYQ boundary"]),
    ],
    ["aridity, not heat", "BWh", "BWk", "subtropical high", "Humboldt Current", "Benguela", "rain shadow", "wadi", "xerophyte", "oasis", "Aravallis", "Luni", "Great Indian Bustard", "UNCCD COP16"],
    "The audited routing ledgers contain no direct question owned by Geography Topic 18. Desert-lake identification, arid landforms, Great Indian Bustard conservation and land-degradation demands remain with their routed regional, geomorphology, Environment or governance owners. This package records a transparent zero-direct-PYQ audit and invents no wording, year, marks or key.",
    [],
    [
        "https://www.unccd.int/cop16",
        "https://www.unccd.int/convention/cop-decisions",
    ],
    "Official UNCCD COP16 and decision pages are used only for the Riyadh dates, the drought-and-land-restoration agenda and the status that no binding global drought framework was finalised. No changing pledge total is quoted. No sufficiently stable official 2026 GIB population figure is used.",
    extra=["basic/07_Arid-Desert-Landforms.md", "basic/17_Savanna-Sudan-Climate.md", "advanced/31_Mineral-Energy-Resources-World-and-India.md"],
)


TOPIC_19 = common.topic(
    19,
    "Mediterranean Climate",
    "19_Mediterranean-Climate.md",
    "19_India-Himalayan-Fruit-Belt.md",
    "19_India-Himalayan-Fruit-Belt_Complete-Topic-Package.md",
    [
        ("Cs western-margin location", "Mediterranean or warm-temperate western-margin climate, commonly Koppen Cs, occupies western continental margins mainly around 30 to 45 degrees north and south; local limits depend on currents, relief and pressure-belt migration."),
        ("Five world regions", "The Mediterranean basin, California, central Chile, the Cape region and south-western or southern Australia are the five classic world expressions."),
        ("Summer subtropical high", "Poleward expansion of the subtropical high brings subsiding stable air, clear skies and offshore or weak-moisture flow in summer, producing the characteristic dry season."),
        ("Winter westerlies", "Equatorward migration of the westerly belt and travelling depressions brings onshore frontal or cyclonic rain in winter; the mechanism is seasonal pressure-belt displacement."),
        ("Summer-dry winter-wet identity", "Dry sunny summers and mild wet winters distinguish Mediterranean climate from summer-rain monsoon and humid eastern-margin climates; winter rain is the primary climatic signature."),
        ("Local-wind contrast", "The Sirocco is a hot dusty wind from the Sahara, while the Mistral is a cold strong wind down the Rhone valley and the Bora is a cold Adriatic wind; local winds are not all hot."),
        ("Sclerophyll vegetation", "Mediterranean vegetation is evergreen or drought-deciduous scrub and open woodland with small hard leathery or waxy leaves, deep roots and thick bark adapted to summer drought and recurrent fire."),
        ("Regional scrub names", "Maquis belongs to the Mediterranean basin, chaparral to California and mallee to Australia; similar drought form does not make the floras taxonomically identical."),
        ("Autumn-spring growth", "Plant growth is favoured in autumn and spring when moisture and temperature overlap, while peak summer heat coincides with drought and winter can limit growth at cooler sites."),
        ("Orchard and horticulture system", "Olives, citrus, figs and other tree crops exploit deep roots and sunshine, while irrigation supports high-value summer fruits and vegetables; water access converts climatic constraint into comparative advantage."),
        ("Winter cereals and vines", "Wheat and barley use cool-season moisture, and viticulture is prominent across Mediterranean-climate regions; historical textbook shares must not be used as current production statistics."),
        ("Wildfire mechanism", "Wet-season biomass production followed by summer desiccation creates fuel, while heat, low humidity, wind, ignition and land management govern spread; climate type raises risk but does not alone cause each fire."),
        ("India climate boundary", "India has no extensive classic Mediterranean Cs region, so the Advanced owner is a horticultural analogue rather than a claim that Kashmir or the Himalaya possess the same winter-rain circulation."),
        ("Himalayan orchard analogue", "Kashmir, Himachal Pradesh and Uttarakhand support temperate fruit belts including apple, pear, peach, cherry, walnut, almond and apricot, while their climate remains Himalayan and monsoonal-continental."),
        ("Apple chilling requirement", "Apple is a temperate fruit whose dormancy and bud break depend on cultivar-specific winter chilling followed by a suitable growing season; one universal chilling-hour threshold should not be asserted."),
        ("Apple-region evidence", "Kullu and Shimla districts, the Kashmir Valley and suitable Uttarakhand hills are established apple regions, with altitude, aspect, frost, hail, moisture and cultivar shaping local suitability."),
        ("Perishability and access", "Fruit geography depends on roads, grading, storage, cold chains and market timing because apples and many horticultural products are perishable; climate alone does not create a viable orchard economy."),
        ("Indian viticulture analogue", "Nashik and adjoining Maharashtra districts, with Sangli also important, form a major grape belt; this is an agricultural analogue and not evidence of Mediterranean Cs climate."),
        ("ICAR low-chill boundary", "Official ICAR material on low-chill apple innovation shows cultivar development can expand adaptation, but an award or variety profile does not establish a national shift in climate zones or universal field performance."),
        ("Transparent zero-direct route", "The audited Geography ledgers contain no direct question owned by Topic 19; Mediterranean pipelines, world regions, horticulture and wildfire demands remain with their routed owners, so no PYQ is invented."),
    ],
    [
        "Do not place classic Mediterranean climate on eastern continental margins.",
        "Do not reverse summer drought and winter rain.",
        "Do not treat subtropical highs as the winter rain source.",
        "Do not call Sirocco, Mistral and Bora all hot winds.",
        "Do not describe sclerophyll vegetation as dense equatorial forest.",
        "Do not treat maquis, chaparral and mallee as one identical flora.",
        "Do not list Mediterranean crops without the seasonal water logic.",
        "Do not quote a historical wine share as current production data.",
        "Do not attribute every wildfire solely to climate change.",
        "Do not label Kashmir or the Himalayan fruit belt a true Cs climate.",
        "Do not reduce apple geography to temperature while ignoring chilling and access.",
        "Do not invent a direct PYQ or quantified upslope shift.",
    ],
    [
        (10, "Explain why Mediterranean climates receive winter rain and experience summer drought.", "Seasonal pressure-belt migration places the subtropical high overhead in summer and brings westerly depressions in winter.", [0, 2, 3, 4]),
        (10, "Distinguish Sirocco, Mistral and Bora as local Mediterranean winds.", "Sirocco is hot and dusty, whereas Mistral and Bora are cold winds with different corridors; origin and temperature prevent close-option confusion.", [5]),
        (15, "Explain how Mediterranean vegetation is adapted to summer drought and fire.", "Sclerophyll leaves, roots, bark, open structure and seasonal growth conserve water and tolerate disturbance, with regional scrub analogues.", [6, 7, 8, 11]),
        (15, "Why is Mediterranean agriculture dominated by orchards, vines and high-value horticulture?", "Winter moisture, summer sunshine, drought-resistant perennials and irrigation create specialisation, while cereals exploit cool-season rain.", [9, 10]),
        (20, "Compare classic Mediterranean agriculture with India's Himalayan fruit-belt analogue.", "Both specialise in temperate or perennial horticulture, but India's orchard belts depend on Himalayan chilling and monsoonal-continental conditions rather than Cs winter rain.", [12, 13, 14, 15, 17]),
        (20, "Design a climate-resilient strategy for India's apple economy without treating current anomalies as a climate classification.", "Use cultivar-specific chill monitoring, frost-hail risk, water, diversification, cold chains and official trials, while separating adaptation evidence from claims of a new climate zone.", [14, 15, 16, 18, 19]),
    ],
    [
        plan("Cs western-margin map", [0, 1], "Latitude and margin are tendencies with local modifiers.", "Locate all five classic regions."),
        plan("Summer subtropical high", [2], "Subsidence creates dryness, not winter rain.", "Trace poleward high-pressure migration."),
        plan("Winter westerly rain", [3], "Travelling depressions are the rain-bearing mechanism.", "Map equatorward westerly movement."),
        plan("Summer-dry winter-wet identity", [4], "Do not reverse the seasonal pattern.", "Compare Cs with monsoon and eastern margin climates."),
        plan("Sirocco, Mistral and Bora", [5], "Local winds differ in origin and temperature.", "Use a hot-versus-cold discriminator."),
        plan("Sclerophyll adaptations", [6], "Vegetation is open and drought-adapted, not rainforest.", "Link leaves, roots and bark to summer stress."),
        plan("Maquis, chaparral and mallee", [7], "Analogous form does not imply identical flora.", "Place each regional name correctly."),
        plan("Seasonal growth rhythm", [8], "Summer heat coincides with water shortage.", "Use the moisture-temperature overlap."),
        plan("Orchards and irrigated horticulture", [9], "Climate creates opportunity only where water and markets exist.", "Connect tree crops to summer sunshine."),
        plan("Winter cereals and viticulture", [10], "Historical shares are not current statistics.", "Separate cool-season crops and perennial vines."),
        plan("Wildfire geography", [11], "Climate risk is not event attribution.", "Build fuel, drought, wind and ignition chain."),
        plan("India analogue boundary", [12], "Horticultural similarity is not Cs classification.", "Preserve global Basic versus India Advanced."),
        plan("Himalayan fruit regions", [13, 15], "Suitability varies by altitude, aspect and hazard.", "Map Kashmir, Himachal and Uttarakhand."),
        plan("Chilling, perishability and grapes", [14, 16, 17], "No universal chill threshold or climate analogy applies.", "Join physiology with transport and market geography."),
        plan("ICAR adaptation and PYQ boundary", [18, 19], "Innovation evidence does not redraw climate zones.", "Close with official status and ownership discipline."),
    ],
    [
        panel("Five-region world map", "spatial-map", ["MEDITERRANEAN BASIN -> largest expression", "CALIFORNIA + CENTRAL CHILE -> west coasts", "CAPE -> south-west South Africa", "SW / SOUTH AUSTRALIA -> fifth region"], ["Cs western-margin map"]),
        panel("Seasonal pressure switch", "seasonal-map", ["SUMMER -> subtropical high shifts poleward", "SUBSIDENCE -> clear sky and drought", "WINTER -> westerlies shift equatorward", "DEPRESSIONS -> frontal rain arrives"], ["Summer subtropical high", "Winter westerly rain"]),
        panel("Climate identity firewall", "comparison-table", ["MEDITERRANEAN -> summer dry / winter wet", "MONSOON -> summer wet / winter drier", "EASTERN MARGIN -> rain through much of year", "RULE -> rainfall season outranks latitude alone"], ["Summer-dry winter-wet identity"]),
        panel("Local-wind matrix", "comparison-table", ["SIROCCO -> hot, dusty, Sahara origin", "MISTRAL -> cold, Rhone-valley outflow", "BORA -> cold, Adriatic downslope wind", "TRAP -> local Mediterranean winds are not all hot"], ["Sirocco, Mistral and Bora"]),
        panel("Sclerophyll design", "classification-tree", ["LEAF -> small, hard, waxy or leathery", "ROOT -> deep access to stored moisture", "BARK -> drought and fire protection", "STRUCTURE -> scrub or open woodland"], ["Sclerophyll adaptations"]),
        panel("Regional scrub names", "evidence-table", ["MAQUIS -> Mediterranean basin", "CHAPARRAL -> California", "MALLEE -> Australia", "FORM CONVERGES -> species remain regional"], ["Maquis, chaparral and mallee"]),
        panel("Growth-season calendar", "seasonal-map", ["AUTUMN -> rain returns after drought", "WINTER -> moisture but cooler growth", "SPRING -> best moisture-temperature overlap", "SUMMER -> drought and fire stress"], ["Seasonal growth rhythm"]),
        panel("Agricultural system", "causal-system", ["WINTER RAIN -> cereals and soil recharge", "DEEP-ROOTED TREES -> survive dry summer", "SUN + IRRIGATION -> fruit and vegetables", "MARKETS -> high-value export horticulture"], ["Orchards and irrigated horticulture", "Winter cereals and viticulture"]),
        panel("Wildfire chain", "hazard-flow", ["WET SEASON -> biomass and fine fuel", "SUMMER DROUGHT -> fuel desiccation", "HEAT + WIND + IGNITION -> rapid spread", "LAND MANAGEMENT -> exposure and recovery"], ["Wildfire geography"]),
        panel("India analogue map", "spatial-map", ["KASHMIR -> temperate fruit valleys", "HIMACHAL -> Kullu and Shimla apple belts", "UTTARAKHAND -> suitable hill orchards", "MAHARASHTRA -> grape belt, not Cs climate"], ["India analogue boundary", "Himalayan fruit regions"]),
        panel("Apple viability ladder", "institutional-ladder", ["WINTER CHILL -> cultivar-specific dormancy", "SITE -> frost, hail, aspect and water", "HARVEST -> grading and storage", "MARKET -> roads, cold chain and timing"], ["Chilling, perishability and grapes"]),
        panel("Mediterranean answer spine", "answer-spine", ["LOCATE -> western margins at 30-45 degrees", "DERIVE -> summer high / winter westerlies", "LINK -> sclerophyll, crops and fire", "QUALIFY -> India is an orchard analogue only"], ["ICAR adaptation and PYQ boundary"]),
    ],
    ["Koppen Cs", "summer drought and winter rain", "subtropical high", "westerlies", "Sirocco", "Mistral", "Bora", "sclerophyll", "maquis", "chaparral", "mallee", "viticulture", "chilling", "cold chain"],
    "The audited routing ledgers contain no direct question owned by Geography Topic 19. Mediterranean pipeline geography, world-region mapping, horticulture, local winds and wildfire questions remain with their routed owners. This package records a transparent zero-direct-PYQ audit and does not invent wording, year, marks or key.",
    [],
    [
        "https://icar.org.in/en/low-chill-apple-man-india-hariman-sharma-conferred-padma-shri",
        "https://icarcith.org.in/",
    ],
    "Official ICAR material is used only to establish low-chill apple innovation as an adaptation example, and ICAR-CITH is retained as the relevant official temperate-horticulture institution. No unofficial chilling-hour trend, production loss, market value or measured upslope shift is quoted, and India is not reclassified as Mediterranean climate.",
    extra=["basic/16_Tropical-Monsoon-and-Marine-Climate.md", "basic/21_Warm-Temperate-Eastern-Margin-China-Type.md", "basic/30_Primary-Economic-Activities-Agriculture.md"],
)


TOPICS_15_19 = [TOPIC_15, TOPIC_16, TOPIC_17, TOPIC_18, TOPIC_19]
