"""Authored Geography learner-v2 data for Topics 10-14."""

from __future__ import annotations

import generate_geography_common as common


def plan(
    title: str, indexes: list[int], caution: str, exam_use: str
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_10 = common.topic(
    10,
    "Coastal Landforms / India Coast and CRZ",
    "10_Coastal-Landforms.md",
    "10_India-Coast-and-CRZ.md",
    "10_India-Coast-and-CRZ_Complete-Topic-Package.md",
    [
        ("Coastal-system budget", "A coast records the balance among wave and tidal energy, currents, sediment supply, geology, relative sea-level change and human intervention; shoreline position is an outcome, not a fixed boundary."),
        ("Wave refraction", "Wave fronts slow in shallow water and bend toward the shore, concentrating energy on headlands and dispersing it in bays; refraction redistributes rather than creates wave energy."),
        ("Marine erosion", "Hydraulic action, abrasion or corrasion, attrition and solution attack exposed coasts, with effectiveness controlled by wave energy, joints, lithology and beach protection."),
        ("Cliff-platform sequence", "Undercutting at a cliff foot forms a notch; collapse and debris removal cause retreat and leave a wave-cut platform that may later be raised or submerged by relative sea-level change."),
        ("Cave-arch-stack sequence", "Wave attack exploits a headland weakness to form a cave, may open it into an arch, and can isolate a stack and later a stump; the sequence is conditional on structure and erosion."),
        ("Headland-bay contrast", "Differential erosion leaves resistant rock as headlands and recesses weaker rock into bays, while refraction reinforces the contrast by focusing energy on projections."),
        ("Beach and berm", "A beach is a mobile deposit of sand, shingle or other sediment between land and sea; swash, backwash, storm waves and seasonal energy shift its profile and may build berms."),
        ("Longshore drift and spit", "Oblique swash and more direct downslope backwash transport sediment alongshore; where the coast changes direction, deposition can extend a spit whose end may recurved by waves or currents."),
        ("Bar-lagoon-tombolo", "A bar extends across a bay or river mouth and may enclose a lagoon, while a tombolo joins an island to the mainland or another island; neither term is a synonym for spit."),
        ("Emergent and submergent coasts", "Relative land-sea movement can expose raised beaches and marine terraces or drown valleys into rias; a fjord is specifically a drowned glacial trough."),
        ("Relative sea-level rule", "Local coastal change combines global ocean-volume change with vertical land movement, sediment compaction, ocean dynamics and measurement method; global mean rise is not an identical local value."),
        ("Storm-surge mechanism", "A storm surge is an abnormal water-level rise driven mainly by cyclone winds and low pressure and modified by track, shelf shape, bathymetry and tide; it is not the astronomical tide itself."),
        ("India east-west contrast", "India's east coast is generally broader and more deltaic, while much of the west coast is narrower with estuaries and submergent features; local exceptions prevent a rigid binary."),
        ("Delta-estuary-port relation", "Large sediment-rich east-flowing rivers build deltas, whereas Narmada and Tapi enter estuarine mouths; port suitability depends on depth, shelter, sedimentation and engineering, not coast label alone."),
        ("NCCR shoreline classes", "The official NCCR assessment for 1990-2018 classified about 33.6 percent of the analysed mainland coast as eroding, 26.9 percent accreting and 39.6 percent stable; these are period classes, not annual rates."),
        ("CRZ 2019 architecture", "The CRZ Notification 2019 uses category-specific regulation implemented through approved Coastal Zone Management Plans; a national notification does not produce one uniform permission line for every site."),
        ("HTL-LTL-hazard distinction", "High Tide Line, Low Tide Line and hazard-related mapping inputs serve different regulatory or risk purposes; technical demarcation supports a plan but does not itself grant project clearance."),
        ("Institutional decision chain", "MoEFCC, NCZMA, coastal zone authorities, authorised mapping agencies and appraisal bodies perform distinct recommendation, mapping, approval and compliance roles; recommendation is not final approval."),
        ("Verified coastline PYQ route", "The direct routed 2023 GS-I demand asks for India's coastline resource potential and hazard preparedness, requiring physical geography, economic uses and warning-to-evacuation capacity in one qualified answer."),
        ("Integrated coastal response", "A defensible response follows avoid-retreat-accommodate-protect-restore choices, combining sediment-cell analysis, dunes and wetlands, risk-sensitive siting, early warning, local participation and monitored engineering."),
    ],
    [
        "Do not treat a shoreline as a permanently fixed legal or physical line.",
        "Do not reverse swash and backwash roles in longshore drift.",
        "Do not assume every cave must become an arch and stack.",
        "Do not call every sand ridge a spit, bar or tombolo interchangeably.",
        "Do not confuse a ria with a fjord.",
        "Do not equate astronomical tide with storm surge.",
        "Do not state that every east-coast sector is depositional or every west-coast sector erosional.",
        "Do not use the 1990-2018 NCCR percentages as a current annual erosion rate.",
        "Do not invent a single CRZ no-development distance for all categories and locations.",
        "Do not treat HTL demarcation, CZMP approval and project clearance as the same act.",
        "Do not convert an authority recommendation or draft into final law.",
        "Do not present hard structures as universally beneficial without downdrift and maintenance effects.",
    ],
    [
        (10, "Explain how wave refraction and differential erosion produce the headland-bay coastal pattern.", "Refraction concentrates energy on resistant projections and disperses it in bays, but rock structure, sediment and storm history control the realised form.", [1, 2, 5]),
        (10, "Differentiate a spit, bar, lagoon and tombolo through formation and map evidence.", "The landforms are separated by attachment and enclosure: drift-built projection, cross-bay ridge, enclosed water body and island-joining ridge.", [7, 8]),
        (15, "Compare India's eastern and western coasts as geomorphic and economic systems.", "Broad east-coast deltas and narrower west-coast estuaries are useful tendencies, qualified by local geology, sediment budgets, hazards and engineered ports.", [12, 13]),
        (15, "Assess why shoreline erosion cannot be inferred from one national percentage or one beach visit.", "Shoreline trajectory is scale- and period-dependent and reflects sediment cells, storms, structures, sea level and method; the NCCR classes are a dated national assessment.", [0, 10, 14]),
        (20, "Examine how CRZ governance converts coastal geography into differentiated land-use decisions.", "CRZ governance depends on category, mapped lines, approved CZMPs, appraisal routes and compliance; technical mapping, recommendation, approval and outcome must remain separate.", [15, 16, 17]),
        (20, "Design an integrated strategy for using India's coastline while reducing multi-hazard risk.", "Combine resource mapping with ecosystem buffers, risk-sensitive siting, early warning, evacuation, sediment-cell planning, selective engineering and adaptive monitoring.", [11, 18, 19]),
    ],
    [
        plan("Coastal system and sediment budget", [0], "A beach or cliff is a moving system boundary.", "Open with energy, sediment and relative sea level."),
        plan("Wave refraction and energy concentration", [1], "Refraction redistributes wave energy.", "Draw converging and diverging wave rays."),
        plan("Marine erosion agents", [2], "Name the agent and rock control together.", "Use process vocabulary before landform names."),
        plan("Cliff, notch and wave-cut platform", [3], "A platform records retreat, not an unchanged cliff line.", "Derive the sequence with a cross-section."),
        plan("Cave, arch, stack and stump", [4], "The sequence is conditional, not compulsory.", "Attach structure to every stage."),
        plan("Headlands, bays and beaches", [5, 6], "Deposition can protect a bay without stopping all erosion.", "Compare energy focus and sediment storage."),
        plan("Longshore drift and spits", [7], "Drift direction follows the wave approach and shoreline.", "Use swash-backwash arrows."),
        plan("Bars, lagoons and tombolos", [8], "Attachment and enclosure decide the term.", "Use a map-view discriminator."),
        plan("Emergent and submergent coasts", [9, 10], "Relative sea level includes land movement.", "Separate ria, fjord and raised coast."),
        plan("Storm surge and compound water level", [11], "Surge is not the astronomical tide.", "Build a wind-pressure-shelf-tide chain."),
        plan("India east-west coastal map", [12, 13], "Treat the contrast as a tendency with exceptions.", "Link physiography to deltas, estuaries and ports."),
        plan("NCCR shoreline evidence", [14], "A period class is not an annual forecast.", "State 1990-2018 beside the percentages."),
        plan("CRZ category and CZMP logic", [15, 16], "Do not invent one universal setback.", "Move from notification to mapped plan."),
        plan("Institutions and clearance boundaries", [17], "Recommendation, approval and compliance differ.", "Write the institutional chain explicitly."),
        plan("PYQ route and integrated response", [18, 19], "Resource use and hazard preparedness need separate evidence.", "Conclude with adaptive coastal-zone management."),
    ],
    [
        panel("Coastal-system balance", "causal-system", ["WAVES + TIDES + CURRENTS -> marine energy", "RIVERS + CLIFFS + OFFSHORE -> sediment supply", "SEA LEVEL + LAND MOTION -> accommodation space", "HUMAN WORKS -> redistribute erosion and accretion"], ["Coastal system and sediment budget"]),
        panel("Refraction map", "spatial-map", ["DEEP WATER -> wave fronts travel faster", "SHALLOW HEADLAND -> fronts slow and converge", "BAY -> fronts diverge and energy disperses", "RESULT -> erosion focus / depositional shelter"], ["Wave refraction and energy concentration"]),
        panel("Erosional sequence", "process-flow", ["JOINT / FAULT -> hydraulic action + abrasion", "CAVE -> widening and roof attack", "ARCH -> roof collapse -> STACK", "STACK -> undercutting -> STUMP"], ["Marine erosion agents", "Cave, arch, stack and stump"]),
        panel("Cliff retreat section", "replacement-diagram", ["WAVE NOTCH -> basal undercutting", "OVERHANG -> instability and collapse", "DEBRIS REMOVAL -> renewed attack", "RETREAT -> widening wave-cut platform"], ["Cliff, notch and wave-cut platform"]),
        panel("Depositional discriminator", "comparison-table", ["SPIT -> one end attached", "BAR -> crosses bay or mouth", "LAGOON -> water enclosed behind bar", "TOMBOLO -> joins island to land"], ["Longshore drift and spits", "Bars, lagoons and tombolos"]),
        panel("Relative sea-level fork", "decision-tree", ["LAND RISE / SEA FALL -> emergence", "RAISED BEACH + TERRACE -> exposed marine forms", "LAND FALL / SEA RISE -> submergence", "RIA = drowned river valley / FJORD = glacial trough"], ["Emergent and submergent coasts"]),
        panel("Storm-surge chain", "hazard-flow", ["CYCLONE WIND + LOW PRESSURE -> water setup", "TRACK + SHELF + BATHYMETRY -> local amplification", "HIGH TIDE + WAVES + RIVER FLOW -> compound level", "EXPOSURE + WEAK EVACUATION -> disaster risk"], ["Storm surge and compound water level"]),
        panel("India coast contrast", "comparison-table", ["EAST -> broader plains + large deltas", "WEST -> narrower plain + many estuaries", "PORT TEST -> depth, shelter, siltation, engineering", "RULE -> tendency, not universal binary"], ["India east-west coastal map"]),
        panel("NCCR evidence boundary", "evidence-table", ["PERIOD -> 1990-2018 assessment", "ERODING -> about 33.6 percent", "ACCRETING -> about 26.9 percent", "STABLE -> about 39.6 percent; not an annual rate"], ["NCCR shoreline evidence"]),
        panel("CRZ implementation ladder", "institutional-ladder", ["NOTIFICATION -> category-specific national rules", "MAPPING -> HTL/LTL and technical inputs", "CZMP -> consultation + approval + local map", "PROJECT -> appraisal, decision, compliance"], ["CRZ category and CZMP logic", "Institutions and clearance boundaries"]),
        panel("Coastal response hierarchy", "decision-tree", ["AVOID -> keep new exposure out of high-risk space", "RESTORE / ACCOMMODATE -> buffers + resilient use", "RETREAT -> move assets where persistence fails", "PROTECT -> selective works with downdrift audit"], ["PYQ route and integrated response"]),
        panel("Coast answer spine", "answer-spine", ["DEFINE + MAP -> process and coastal sector", "DERIVE -> energy, sediment and sea-level chain", "VERIFY -> period, category, plan and status", "VERDICT -> integrated, adaptive and locally mapped"], ["PYQ route and integrated response"]),
    ],
    ["wave refraction", "wave-cut platform", "longshore drift", "tombolo", "ria", "storm surge", "east coast", "west coast", "NCCR", "1990-2018", "CRZ Notification 2019", "Coastal Zone Management Plan", "High Tide Line", "NCZMA"],
    "Verified direct ownership retains the 2023 GS-I coastline resource-potential and hazard-preparedness demand. Mangrove, blue-carbon and tsunami questions remain with their routed Environment or Disaster Management owners and are not relabelled as direct CRZ PYQs.",
    [
        ("2023", "GS-I", "Comment on the resource potentials of the long coastline of India and highlight the status of natural hazard preparedness in these areas. (250 words)", "Verified routed direct Mains demand; preparedness is cross-cutting with Disaster Management.", "Map fisheries, ports, tourism, energy and ecosystems, then separate cyclone, surge, tsunami, erosion and sea-level hazards. Evaluate observation, warning, evacuation, shelters, CRZ/CZMP risk-sensitive siting and ecosystem buffers. Conclude that economic potential depends on locally mapped, inclusive and adaptive preparedness."),
    ],
    [
        "https://environmentclearance.nic.in/writereaddata/CRZ_Notifications/CRZ_Notification_2019/0.pdf",
        "https://pib.gov.in/PressReleasePage.aspx?PRID=1811914",
        "https://ncscm.res.in/",
    ],
    "The official CRZ Notification 2019 is used only for category-, map- and plan-dependent architecture. PIB's official NCCR release supplies the 1990-2018 shoreline classes; they are not restated as a current annual rate or forecast. No weakly verified 2026 rule change is used.",
    extra=["basic/05_Landforms-by-Running-Water.md", "basic/11_Islands-and-Coral-Reefs.md", "basic/12_The-Oceans-Currents-Tides-Salinity.md"],
)


TOPIC_11 = common.topic(
    11,
    "Islands and Coral Reefs / India Islands-Great Nicobar",
    "11_Islands-and-Coral-Reefs.md",
    "11_India-Islands-Great-Nicobar.md",
    "11_India-Islands-Great-Nicobar_Complete-Topic-Package.md",
    [
        ("Island classification", "Islands may be continental fragments or shelf islands, oceanic volcanic islands, coral islands or depositional islands; classification must state the origin criterion."),
        ("Continental islands", "Continental islands share continental crustal or shelf affinity and may be separated by drowning, faulting or erosion; proximity to a continent alone does not prove origin."),
        ("Volcanic islands", "Oceanic volcanic islands grow where magma builds edifices above sea level at plate boundaries or hotspots; volcanic origin does not imply current eruptive activity."),
        ("Coral islands", "Coral islands are low accumulations of reef-derived carbonate sediment built and reworked by organisms, waves and currents; the living reef and the island landform are related but distinct."),
        ("Coral polyp symbiosis", "Reef-building corals are animals that secrete calcium-carbonate skeletons and commonly host photosynthetic zooxanthellae, linking clear sunlit water to reef productivity."),
        ("Coral-growth controls", "Most reef-building corals favour warm, shallow, clear, well-lit, normally saline and oxygenated water with limited sediment stress; local tolerances vary."),
        ("Fringing reef", "A fringing reef lies close to shore with no lagoon or only a narrow shallow lagoon, making it the closest reef type to the land."),
        ("Barrier reef", "A barrier reef lies farther offshore and is separated from land by a broader, deeper lagoon; offshore position and lagoon width distinguish it from a fringing reef."),
        ("Atoll", "An atoll is a roughly ring-shaped reef or reef-island system enclosing a lagoon, generally without a central high island at the surface."),
        ("Darwin subsidence model", "Darwin's model links fringing reef to barrier reef to atoll as a volcanic foundation slowly subsides while coral growth keeps pace near sea level; it is a process model, not a rule for every reef."),
        ("Daly glacial-control model", "Daly emphasised lowered glacial sea level, wave planation and post-glacial flooding as controls on reef platforms; it supplements rather than erases biological growth and tectonics."),
        ("Bleaching boundary", "Coral bleaching is the loss of symbiotic algae or pigments under stress, often marine heat; bleaching raises mortality risk but does not mean every colony is already dead."),
        ("Reef service bundle", "Reefs support biodiversity, fisheries, tourism, carbonate sediment and wave-energy attenuation, but they cannot eliminate extreme surge, tsunami or poor land-use exposure."),
        ("Andaman-Nicobar origin", "The Andaman and Nicobar Islands are emergent parts of a tectonic island arc connected to the Sunda-Andaman subduction system; the group is not simply a chain of coral atolls."),
        ("Lakshadweep origin", "Lakshadweep consists of low coral islands, reefs and atolls on submarine ridges in the Arabian Sea; reef-derived land and freshwater lenses make the islands physically sensitive."),
        ("India island-channel map", "The Ten Degree Channel separates the Andaman group from the Nicobar group, while the Nine Degree Channel separates Minicoy from the main Lakshadweep group."),
        ("Great Nicobar biosphere status", "Great Nicobar is in UNESCO's World Network of Biosphere Reserves, added in 2013; biosphere-reserve recognition does not make the entire island an inviolate no-use zone."),
        ("Great Nicobar project components", "Official 2026 PIB material describes an international container transshipment port, airport, township and power infrastructure as the proposed integrated project components."),
        ("Great Nicobar status boundary", "A Rajya Sabha answer dated 12 February 2026 stated that Stage-II or final forest approval had not been granted and project activity depended on final approval; a factsheet is not proof of completed mitigation."),
        ("Island appraisal framework", "Island decisions must combine tectonic and tsunami exposure, reefs and nesting beaches, freshwater and sediment limits, indigenous rights, cumulative carrying capacity, alternatives and monitored safeguards."),
    ],
    [
        "Do not classify an island only by its present shape or distance from a mainland.",
        "Do not equate volcanic origin with an active volcano.",
        "Do not call the Andaman-Nicobar arc a coral-atoll chain.",
        "Do not confuse a coral reef, reef island and atoll.",
        "Do not reverse fringing and barrier reef lagoon relations.",
        "Do not present Darwin's sequence as the only possible reef history.",
        "Do not equate bleaching automatically with immediate coral death.",
        "Do not claim reefs can stop every extreme wave or tsunami.",
        "Do not reverse the Ten Degree and Nine Degree Channel locations.",
        "Do not infer a project clearance or construction outcome from a policy factsheet.",
        "Do not quote changing project capacities, costs or forest-area figures without a dated official source.",
        "Do not reduce Great Nicobar appraisal to a strategy-versus-environment slogan.",
    ],
    [
        (10, "Classify islands by origin and explain why present shape alone is inadequate.", "Continental, volcanic, coral and depositional origins reflect different crustal and sedimentary histories that can converge on similar present shapes.", [0, 1, 2, 3]),
        (10, "Differentiate fringing reefs, barrier reefs and atolls using a map-view sketch.", "Distance from land, lagoon width and the presence or absence of a central high island separate the three forms.", [6, 7, 8]),
        (15, "Explain Darwin's reef-subsidence sequence and assess its limits.", "Subsidence with upward-outward coral growth explains a powerful sequence, but sea-level oscillation, antecedent topography, ecology and tectonics require qualification.", [9, 10]),
        (15, "Compare the geological and ecological character of Andaman-Nicobar and Lakshadweep.", "A tectonic island arc and low coral-atoll system create different relief, hazards and resource limits, though both contain vulnerable reefs and coasts.", [13, 14, 15]),
        (20, "Assess how marine heat stress can transform coral-reef ecology, island security and livelihoods.", "Bleaching affects habitat, fisheries, tourism, carbonate sediment and wave attenuation, with outcomes shaped by duration, local stress and recovery capacity.", [4, 5, 11, 12]),
        (20, "Construct a balanced appraisal framework for the Great Nicobar project.", "Separate official components and approval status from projected benefits, then test cumulative ecology, hazards, rights, carrying capacity, alternatives, safeguards and monitoring.", [16, 17, 18, 19]),
    ],
    [
        plan("Island origin classes", [0, 1], "State the origin criterion before the example.", "Build a continental-volcanic-coral-depositional table."),
        plan("Volcanic and coral island formation", [2, 3], "Origin does not determine present activity or elevation alone.", "Use crust-building versus carbonate-building chains."),
        plan("Coral polyp and reef metabolism", [4], "Corals are animals, not plants or rocks.", "Link symbiosis to the light requirement."),
        plan("Coral growth conditions", [5], "Conditions are preferences with local tolerance.", "Use a limiting-factor diagram."),
        plan("Fringing reef anatomy", [6], "A narrow lagoon does not make a barrier reef.", "Draw reef-shore contact."),
        plan("Barrier reef anatomy", [7], "Offshore separation and lagoon width are decisive.", "Compare directly with fringing reef."),
        plan("Atoll and lagoon", [8], "Ring form does not reveal one universal origin history.", "Use plan and cross-section views."),
        plan("Darwin and Daly models", [9, 10], "Treat them as testable models, not slogans.", "Compare subsidence with glacial sea-level control."),
        plan("Bleaching, mortality and recovery", [11], "Bleached is stressed, not necessarily dead.", "Separate trigger, state and outcome."),
        plan("Reef ecosystem services and limits", [12], "Wave attenuation is not complete hazard removal.", "Link ecology to livelihoods and protection."),
        plan("Andaman-Nicobar tectonic arc", [13], "Do not label the whole arc coral.", "Map arc, trench-side setting and hazards."),
        plan("Lakshadweep coral system", [14, 15], "Keep Nine and Ten Degree Channels separate.", "Map atolls, channels and freshwater constraint."),
        plan("Great Nicobar biosphere value", [16], "Biosphere reserve is zoned, not a whole-island ban.", "Use conservation status precisely."),
        plan("Project components and approval status", [17, 18], "Proposal, approval and delivered outcome differ.", "Attach every status to an official date."),
        plan("PYQ reef route and island appraisal", [19], "Do not borrow cross-owned PYQs as direct routes.", "Conclude with a cumulative carrying-capacity test."),
    ],
    [
        panel("Island-origin tree", "classification-tree", ["CONTINENTAL -> crust or shelf affinity", "VOLCANIC -> magma builds oceanic edifice", "CORAL -> reef carbonate + wave-built sediment", "DEPOSITIONAL -> river, current or barrier accumulation"], ["Island origin classes"]),
        panel("Reef-building engine", "process-flow", ["POLYP -> calcium-carbonate skeleton", "ZOOXANTHELLAE -> photosynthetic symbiosis", "LIGHT + CLEAR WATER -> reef productivity", "HEAT / SEDIMENT STRESS -> bleaching or decline"], ["Coral polyp and reef metabolism", "Coral growth conditions"]),
        panel("Reef-type cross-section", "comparison-table", ["FRINGING -> shore contact + narrow lagoon", "BARRIER -> offshore reef + broad lagoon", "ATOLL -> ring reef around lagoon", "TEST -> land relation, lagoon and foundation"], ["Fringing reef anatomy", "Barrier reef anatomy", "Atoll and lagoon"]),
        panel("Darwin sequence", "process-flow", ["VOLCANIC ISLAND + FRINGING REEF", "SLOW SUBSIDENCE + UPWARD CORAL GROWTH", "BARRIER REEF + WIDER LAGOON", "ISLAND SUBMERGED -> ATOLL"], ["Darwin and Daly models"]),
        panel("Daly qualification", "comparison-table", ["GLACIAL SEA-LEVEL FALL -> exposed platform", "WAVE PLANATION -> foundation shaping", "POST-GLACIAL RISE -> renewed reef growth", "VERDICT -> combine sea level, biology and tectonics"], ["Darwin and Daly models"]),
        panel("Bleaching outcome fork", "decision-tree", ["THERMAL / LIGHT / POLLUTION STRESS", "SYMBIONT LOSS -> pale or white colony", "STRESS EASES -> possible recovery", "STRESS PERSISTS -> disease, mortality, erosion"], ["Bleaching, mortality and recovery"]),
        panel("Reef-service chain", "causal-system", ["REEF COMPLEXITY -> habitat + fisheries", "REEF CREST -> wave-energy attenuation", "CARBONATE PRODUCTION -> island sediment", "DEGRADATION -> livelihood + exposure risk"], ["Reef ecosystem services and limits"]),
        panel("India island contrast", "comparison-table", ["A&N -> tectonic arc, high relief, seismic setting", "LAKSHADWEEP -> low coral atolls and reefs", "TEN DEGREE -> Andaman / Nicobar divide", "NINE DEGREE -> Minicoy / main Lakshadweep divide"], ["Andaman-Nicobar tectonic arc", "Lakshadweep coral system"]),
        panel("Great Nicobar value map", "evidence-map", ["TECTONIC ISLAND -> earthquake-tsunami exposure", "BIOSPHERE RESERVE -> core-buffer-transition logic", "REEFS + BEACHES + FORESTS -> connected habitats", "INDIGENOUS COMMUNITIES -> rights and livelihood"], ["Great Nicobar biosphere value"]),
        panel("Project-status firewall", "status-ladder", ["PROPOSAL -> port + airport + township + power", "CLEARANCE CONDITIONS -> safeguards to implement", "12 FEB 2026 -> final forest approval not granted", "RULE -> official claim is not measured outcome"], ["Project components and approval status"]),
        panel("Island appraisal gate", "decision-tree", ["NEED -> strategic and economic rationale", "PLACE -> hazard, freshwater and carrying capacity", "PEOPLE / ECOLOGY -> rights + cumulative effects", "DECISION -> alternatives, safeguards, monitoring"], ["PYQ reef route and island appraisal"]),
        panel("Island answer spine", "answer-spine", ["CLASSIFY -> origin and reef type", "MAP -> arc, atoll, channel and lagoon", "ASSESS -> heat, hazard, rights and status", "VERDICT -> island-specific and precautionary"], ["PYQ reef route and island appraisal"]),
    ],
    ["zooxanthellae", "fringing reef", "barrier reef", "atoll", "Darwin", "Daly", "coral bleaching", "Andaman and Nicobar", "Lakshadweep", "Ten Degree Channel", "Nine Degree Channel", "Great Nicobar", "biosphere reserve", "Stage-II"],
    "Verified direct routes are the 2018 Prelims coral-reef distribution and biodiversity demand and the 2019 GS-I global-warming impact on coral life. Barren Island, biorock and island-nation sea-level questions retain their separate routed owners and are not duplicated as direct PYQs.",
    [
        ("2018", "Prelims GS-I", "Coral reef global distribution in tropical waters and its biodiversity significance.", "Verified routed objective demand; official key unavailable in the local ledger.", "Test each statement independently: reef-building corals are concentrated mainly in warm, shallow tropical-subtropical seas, but distribution is not universal; the Coral Triangle and Great Barrier Reef are major centres; reefs support high taxonomic diversity. Preserve the official option order and do not invent an answer letter."),
        ("2019", "GS-I", "Assess the impact of global warming on the coral life system with examples. (150 words)", "Verified routed direct Mains demand.", "Explain marine heat stress and bleaching, then trace mortality, habitat simplification, fisheries, tourism, carbonate sediment and coastal protection. Use Indian reef settings as examples without unsupported event counts. Qualify that bleaching can recover if stress is brief and local pressures are reduced."),
    ],
    [
        "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/may/doc202651860401.pdf",
        "https://www.sansad.in/getFile/annex/270/AU1486_8zAFvF.pdf?source=pqars",
        "https://www.unesco.org/en/mab/great-nicobar",
        "https://lakshadweep.gov.in/about-lakshadweep/",
    ],
    "Official PIB material is used for the stated project components, UNESCO for Great Nicobar's 2013 biosphere-reserve recognition, and the 12 February 2026 Rajya Sabha answer for the final-forest-approval boundary. No project capacity, cost, island count, reef count or completed mitigation outcome is asserted.",
    extra=["basic/03_Vulcanism-and-Earthquakes.md", "basic/10_Coastal-Landforms.md", "basic/12_The-Oceans-Currents-Tides-Salinity.md"],
)


TOPIC_12 = common.topic(
    12,
    "The Oceans: Currents, Tides, Salinity / Indian Ocean and IOD",
    "12_The-Oceans-Currents-Tides-Salinity.md",
    "12_Indian-Ocean-and-IOD.md",
    "12_Indian-Ocean-and-IOD_Complete-Topic-Package.md",
    [
        ("Ocean-current definition", "An ocean current is a persistent, directed movement of seawater at a stated depth and time scale; a surface current, tidal stream, eddy and deep overturning branch are not interchangeable."),
        ("Surface-current drivers", "Planetary winds provide major surface stress, while Coriolis, pressure gradients, basin shape, friction and sea-level slope organise the resulting circulation."),
        ("Density circulation", "Temperature and salinity alter seawater density; cooling, evaporation, sea-ice processes, mixing and freshwater input help create sinking, spreading and overturning at depth."),
        ("Warm-cold current rule", "Warm and cold describe a current relative to surrounding water and source region, not an absolute temperature; each current also changes air-sea heat and moisture exchange."),
        ("Gyre rotation", "Wind stress and Coriolis organise subtropical gyres clockwise in the Northern Hemisphere and anticlockwise in the Southern Hemisphere, with equatorial and seasonal complications."),
        ("Western-boundary intensification", "Western boundary currents such as the Gulf Stream and Kuroshio are generally narrow, swift and deep because basin-scale vorticity balance concentrates return flow on the west."),
        ("Eastern-boundary upwelling", "Eastern boundary currents are generally broad and cool, and alongshore winds can drive Ekman transport away from the coast so nutrient-rich deeper water rises."),
        ("Currents and fisheries", "Productive fisheries often occur in upwelling zones or mixing fronts because nutrients support food webs; current convergence alone does not guarantee a rich fishery."),
        ("Tide-generating forces", "Tides arise chiefly from the differential gravitational effects of the Moon and Sun together with Earth-Moon system dynamics, then are reshaped by basin geometry and friction."),
        ("Spring-neap cycle", "Spring tides occur near new and full moon when solar and lunar tidal effects reinforce; neap tides occur near quarter moons when the effects partly offset."),
        ("Tidal-range controls", "Tidal range depends on astronomical forcing, coastline and basin resonance, shelf depth, friction and local timing; funnel-shaped bays can amplify range."),
        ("Salinity budget", "Ocean salinity rises with net evaporation and brine formation and falls with precipitation, river runoff, ice melt and mixing; it is a conservative tracer only within stated processes."),
        ("Halocline-density link", "A halocline is a strong vertical salinity gradient; together with temperature it contributes to stratification, mixing resistance and the depth of the mixed layer."),
        ("Arabian Sea-Bay contrast", "The Arabian Sea is generally more saline than the Bay of Bengal because evaporation is stronger and freshwater input lower, while the Bay receives heavy rain and large river discharge."),
        ("North Indian Ocean reversal", "North Indian Ocean surface circulation reverses or reorganises seasonally with monsoon winds, unlike a single fixed subtropical-gyre arrow map."),
        ("Somali-current upwelling", "During the southwest monsoon, strong winds and the Somali Current support coastal upwelling in the western Arabian Sea, linking circulation to nutrients and air-sea exchange."),
        ("IOD definition", "The Indian Ocean Dipole is a coupled zonal contrast in sea-surface temperature and associated atmosphere-ocean conditions between western and eastern equatorial Indian Ocean sectors."),
        ("IOD phase boundary", "Positive and negative IOD phases shift thermocline, winds and convection differently, but neither phase guarantees a uniform Indian monsoon outcome because timing, ENSO and internal variability matter."),
        ("Official observing network", "INCOIS describes OMNI and RAMA moorings that collect upper-ocean temperature, salinity, currents and meteorological variables for Indian Ocean monitoring and model validation."),
        ("Verified current PYQ routes", "Direct routed Mains demands are 2019 on ocean currents versus water masses and marine life, and 2022 on forces influencing currents and their fishing role."),
    ],
    [
        "Do not treat every moving water mass as a permanent ocean current.",
        "Do not explain all currents by wind or all currents by density alone.",
        "Do not define warm and cold currents by one absolute temperature threshold.",
        "Do not reverse Northern and Southern Hemisphere subtropical gyres.",
        "Do not assume every current meeting point guarantees fisheries.",
        "Do not link spring tides to the spring season.",
        "Do not link neap tides to the farthest Earth-Moon distance alone.",
        "Do not treat salinity and temperature as independent of density.",
        "Do not reverse the general Arabian Sea-Bay of Bengal salinity contrast.",
        "Do not draw one year-round current direction for the North Indian Ocean.",
        "Do not equate IOD with ENSO or a simple SST value at one point.",
        "Do not state a current IOD phase, forecast or monsoon outcome without a dated official bulletin.",
    ],
    [
        (10, "Explain why surface currents cannot be derived from wind direction alone.", "Wind stress initiates motion, but Coriolis, pressure gradients, friction and basin geometry turn it into organised currents and gyres.", [1, 4]),
        (10, "Differentiate spring and neap tides and explain why local tidal range still varies.", "Astronomical alignment sets the cycle, while shelf-basin geometry, resonance and friction determine local expression.", [8, 9, 10]),
        (15, "Analyse how temperature and salinity create ocean stratification and deep circulation.", "Heat and freshwater budgets alter density, producing mixed layers, haloclines and sinking-spreading pathways modified by mixing and topography.", [2, 11, 12]),
        (15, "Explain the Arabian Sea-Bay of Bengal contrast in salinity and circulation.", "Evaporation, rainfall, river runoff and monsoon winds generate contrasting stratification and seasonal current responses across the two basins.", [13, 14, 15]),
        (20, "Examine the influence of ocean currents on climate, upwelling and fisheries.", "Currents redistribute heat and nutrients, but marine productivity depends on light, mixing, oxygen, habitat and fishing pressure as well as circulation.", [3, 5, 6, 7]),
        (20, "Assess the Indian Ocean Dipole as a modifier of the Indian monsoon rather than a deterministic switch.", "IOD couples SST, thermocline, winds and convection, yet impacts depend on phase timing, amplitude, ENSO-MJO interaction and regional circulation.", [16, 17, 18, 19]),
    ],
    [
        plan("Current vocabulary and scales", [0], "Name depth, persistence and time scale.", "Separate current, eddy, tide and water mass."),
        plan("Surface-current force balance", [1], "Wind is a driver, not the complete pathway.", "Use wind-Coriolis-pressure-friction logic."),
        plan("Thermohaline density circulation", [2], "Density depends on both temperature and salinity.", "Build a cooling-salinity-sinking chain."),
        plan("Warm and cold current effects", [3], "Warm and cold are relative labels.", "Connect advection to coastal climate."),
        plan("Gyres and boundary currents", [4, 5], "State hemisphere and basin before direction.", "Contrast western and eastern limbs."),
        plan("Upwelling and fisheries", [6, 7], "Nutrients are necessary but not sufficient.", "Trace wind to Ekman transport to food web."),
        plan("Tide-generating forces", [8], "Tides are differential gravitational responses.", "Separate forcing from local amplification."),
        plan("Spring and neap tides", [9, 10], "Spring is an alignment term, not a season.", "Draw Sun-Earth-Moon geometry."),
        plan("Salinity controls and halocline", [11, 12], "State the freshwater and heat budgets.", "Link salinity to stratification."),
        plan("Arabian Sea and Bay of Bengal", [13], "Use generally, not universally.", "Compare evaporation and river input."),
        plan("Seasonal monsoon-current reversal", [14, 15], "Every arrow needs a season label.", "Map summer and winter separately."),
        plan("IOD coupled mechanism", [16], "IOD includes atmospheric coupling, not SST alone.", "Draw west-east thermocline and convection."),
        plan("IOD phases and uncertainty", [17], "No phase guarantees all-India rainfall.", "Add timing, ENSO and regional qualification."),
        plan("INCOIS observing architecture", [18], "Observation is not a forecast or outcome.", "Link moorings to data and model validation."),
        plan("Verified PYQs and ocean answer spine", [19], "Preserve direct routing and key status.", "Conclude with a process-to-ecology chain."),
    ],
    [
        panel("Ocean-current force chain", "causal-system", ["WIND STRESS -> surface momentum", "CORIOLIS -> turning by hemisphere", "PRESSURE GRADIENT -> geostrophic tendency", "BASIN + FRICTION -> realised current path"], ["Surface-current force balance"]),
        panel("Density-overturning chain", "process-flow", ["COOLING / EVAPORATION -> density increase", "FRESHWATER / WARMING -> density decrease", "DENSE WATER -> sinking and spreading", "MIXING + TOPOGRAPHY -> overturning pathways"], ["Thermohaline density circulation"]),
        panel("Gyre comparison", "comparison-table", ["NORTH SUBTROPICS -> clockwise tendency", "SOUTH SUBTROPICS -> anticlockwise tendency", "WESTERN LIMB -> narrow, swift, warm", "EASTERN LIMB -> broad, cool, upwelling-prone"], ["Gyres and boundary currents"]),
        panel("Upwelling-food web", "process-flow", ["ALONGSHORE WIND -> Ekman transport offshore", "DEEPER WATER RISES -> nutrient supply", "PHYTOPLANKTON -> zooplankton -> fish", "LIMITS -> oxygen, light, habitat, fishing pressure"], ["Upwelling and fisheries"]),
        panel("Tide geometry", "comparison-table", ["NEW / FULL MOON -> aligned forces", "SPRING TIDE -> larger range", "QUARTER MOON -> partial offset", "NEAP TIDE -> smaller range"], ["Tide-generating forces", "Spring and neap tides"]),
        panel("Local tidal range", "causal-system", ["ASTRONOMICAL FORCING -> incoming tide", "SHELF DEPTH + BAY SHAPE -> amplification", "RESONANCE + FRICTION -> timing and height", "RULE -> same forcing, different local range"], ["Spring and neap tides"]),
        panel("Salinity budget", "balance-sheet", ["EVAPORATION + BRINE -> salinity rises", "RAIN + RIVER + MELT -> salinity falls", "ADVECTION + MIXING -> redistribute salt", "TEMP + SALINITY -> density and stratification"], ["Salinity controls and halocline"]),
        panel("Arabian-Bay contrast", "comparison-table", ["ARABIAN SEA -> stronger evaporation", "BAY OF BENGAL -> rain + large river input", "GENERAL RESULT -> Arabian Sea more saline", "QUALIFIER -> season and local mixing matter"], ["Arabian Sea and Bay of Bengal"]),
        panel("Monsoon-current switch", "seasonal-map", ["SW MONSOON -> winds drive summer reorganisation", "SOMALI SECTOR -> strong current + upwelling", "NE MONSOON -> northern flows reverse/reorganise", "MAP RULE -> label every arrow by season"], ["Seasonal monsoon-current reversal"]),
        panel("IOD coupled seesaw", "mechanism-map", ["WEST-EAST SST CONTRAST -> pressure gradient", "WINDS -> thermocline and upwelling response", "CONVECTION -> rainfall shifts zonally", "INDIA EFFECT -> conditional on timing + ENSO + MJO"], ["IOD coupled mechanism", "IOD phases and uncertainty"]),
        panel("Observation-to-service chain", "institutional-ladder", ["OMNI / RAMA -> ocean + weather observations", "INCOIS -> data management and products", "MODELS -> analysis and forecast ensembles", "USER -> marine service with uncertainty"], ["INCOIS observing architecture"]),
        panel("Ocean answer spine", "answer-spine", ["DEFINE -> depth, scale and season", "DERIVE -> force, density or gravity", "MAP -> basin, current, tide or salinity", "QUALIFY -> variability, ecology and evidence date"], ["Verified PYQs and ocean answer spine"]),
    ],
    ["Coriolis", "thermohaline", "western boundary current", "upwelling", "spring tide", "neap tide", "salinity", "halocline", "Arabian Sea", "Bay of Bengal", "Somali Current", "Indian Ocean Dipole", "OMNI", "RAMA"],
    "Verified direct routes retain the 2019 GS-I ocean-current and water-mass demand and the 2022 GS-I current-forces and fishing demand. No current IOD phase, forecast value or official objective answer letter is inferred.",
    [
        ("2019", "GS-I", "How do ocean currents and water masses differ in their impacts on marine life and the coastal environment? Give suitable examples. (250 words)", "Verified routed direct Mains demand.", "Define currents as moving flows and water masses as bodies with characteristic temperature-salinity properties. Compare heat transport, fronts, upwelling, oxygen and nutrient pathways; use Gulf Stream, Peru upwelling and Arabian Sea-Bay contrasts. Qualify that ecology also depends on light, habitat and fishing pressure."),
        ("2022", "GS-I", "What are the forces that influence ocean currents? Describe their role in the fishing industry of the world. (250 words)", "Verified routed direct Mains demand.", "Group wind stress, Coriolis, pressure gradient, density, gravity, friction and basin geometry. Link upwelling and fronts to nutrient supply and fish aggregation, using Peru, Benguela, Somali and Kuroshio-Oyashio examples. Qualify with oxygen, seasonality, habitat and management."),
    ],
    [
        "https://incois.gov.in/site/datainfo/jointportal.jsp",
        "https://iioe-2.incois.gov.in/site/services/osf.jsp",
        "https://mausam.imd.gov.in/ClimateInformation/imdweb/CLIMATE_FCST/Bulletin/ENSO_IOD_Update_Bulletin.pdf",
    ],
    "INCOIS's official OMNI/RAMA page is used for observing variables and purpose, and its ocean-state service page for service architecture. The IMD ENSO-IOD bulletin is retained only as the official place for dated monitoring; no September 2026 phase, forecast probability or monsoon outcome is copied.",
    extra=["basic/10_Coastal-Landforms.md", "basic/11_Islands-and-Coral-Reefs.md", "basic/13_Weather-Elements.md", "advanced/16_India-Monsoon-Mechanism.md"],
)


TOPIC_13 = common.topic(
    13,
    "Weather Elements / India Jet Stream-Western Disturbances",
    "13_Weather-Elements.md",
    "13_India-JetStream-Western-Disturbances.md",
    "13_India-JetStream-Western-Disturbances_Complete-Topic-Package.md",
    [
        ("Weather-element chain", "Insolation, temperature, pressure, wind, humidity, clouds and precipitation are linked state variables and processes; weather is their short-period atmospheric expression at a place."),
        ("Insolation controls", "Received solar energy varies with solar angle, day length, Earth-Sun distance, cloud, dust and surface orientation; latitude alone does not determine daily receipt."),
        ("Heat-budget distinction", "The atmosphere gains energy from absorbed solar radiation and from terrestrial longwave, sensible and latent heat; incoming shortwave and outgoing longwave must not be conflated."),
        ("Lapse rate and inversion", "Temperature generally decreases upward in the troposphere, while an inversion has temperature increasing with height through a layer and can suppress mixing and trap pollutants."),
        ("Pressure-gradient force", "Horizontal pressure differences accelerate air from higher toward lower pressure, with strength related to gradient rather than the absolute pressure value."),
        ("Coriolis force", "Earth's rotation deflects moving air to the right in the Northern Hemisphere and left in the Southern Hemisphere, is zero at the equator and increases poleward for a given speed."),
        ("Frictional wind", "Near the surface, friction slows wind, weakens Coriolis deflection and allows flow to cross isobars toward low pressure; aloft the balance differs."),
        ("Geostrophic balance", "Away from the equator and friction layer, pressure-gradient and Coriolis forces can approximately balance, producing wind nearly parallel to straight isobars."),
        ("Pressure belts", "Equatorial low, subtropical highs, subpolar lows and polar highs are idealised planetary belts that migrate seasonally and are broken by land-sea heating and topography."),
        ("Planetary winds", "Trade winds, westerlies and polar easterlies connect the pressure belts, but monsoons, cyclones, local winds and seasonal migration complicate the ideal pattern."),
        ("Humidity measures", "Absolute, specific and relative humidity measure different properties; relative humidity changes with both water-vapour content and temperature."),
        ("Condensation and clouds", "Air reaching saturation through cooling or moisture addition can condense on nuclei, forming cloud or fog when lift, stability and droplet processes permit."),
        ("Rainfall mechanisms", "Convectional, orographic and cyclonic or frontal rainfall describe uplift mechanisms; one storm can combine more than one mechanism."),
        ("Troposphere depth", "The troposphere is generally deeper over the warm tropics and shallower toward the poles, and most weather occurs there because water vapour, vertical mixing and instability are concentrated in it."),
        ("Jet-stream definition", "A jet stream is a narrow current of strong upper-tropospheric or lower-stratospheric winds associated with sharp horizontal temperature gradients; it is not fixed at one altitude."),
        ("Winter STWJ role", "In winter the subtropical westerly jet lies south of the Himalaya in the broad Indian-sector circulation and helps steer western disturbances toward north and northwest India."),
        ("Summer easterly-jet boundary", "The tropical easterly jet is a summer upper-air feature linked to the monsoon circulation, but its appearance or strength is not a single-cause switch that proves monsoon onset or rainfall."),
        ("Western-disturbance structure", "Western disturbances are eastward-moving mid-latitude troughs, lows or cyclonic circulations embedded in the westerlies and commonly draw moisture along their path; they are not southwest-monsoon systems."),
        ("IMD observation architecture", "IMD's official upper-air service describes radiosonde and pilot-balloon observations that support analysis of winds, pressure and temperature aloft; observation, diagnosis and forecast remain distinct."),
        ("Verified weather PYQ routes", "Direct routes include 2021 GS-I mountain alignment and local weather, 2022 GS-I tropospheric weather processes, and objective demands on jet streams, clouds, insolation, isotherms and atmospheric dust."),
    ],
    [
        "Do not reduce weather to temperature and rainfall alone.",
        "Do not say latitude alone fixes insolation at a place.",
        "Do not state that the atmosphere is heated only directly by solar radiation.",
        "Do not confuse an inversion with the normal environmental lapse tendency.",
        "Do not make Coriolis initiate motion; it deflects existing motion.",
        "Do not draw surface winds exactly parallel to isobars.",
        "Do not treat pressure belts as fixed uninterrupted latitude lines.",
        "Do not equate relative humidity with the total water vapour present.",
        "Do not classify all mountain rain as purely orographic.",
        "Do not place a jet at one permanent altitude or latitude.",
        "Do not call western disturbances a branch of the southwest monsoon.",
        "Do not infer a long-term jet trend or a verified event outcome from one bulletin or forecast.",
    ],
    [
        (10, "Explain why relative humidity can rise at night without additional water vapour.", "Cooling lowers saturation capacity, so relative humidity can rise toward saturation even when actual vapour content changes little.", [10, 11]),
        (10, "Differentiate pressure-gradient, Coriolis and frictional controls on wind.", "Pressure gradient initiates acceleration, Coriolis deflects motion, and friction slows and turns surface flow across isobars.", [4, 5, 6, 7]),
        (15, "Explain how atmospheric stability and uplift mechanism determine clouds and rainfall.", "Lapse structure controls parcel buoyancy, while convection, terrain and fronts provide lift; moisture and microphysics determine precipitation efficiency.", [3, 11, 12]),
        (15, "Analyse why the troposphere is the principal weather-producing layer.", "Its water vapour, vertical mixing, heating from below and pressure-temperature gradients host clouds, storms and upper-air steering, with depth varying by latitude.", [1, 2, 13, 14]),
        (20, "Examine the role of upper-air jets and western disturbances in India's seasonal weather.", "Winter STWJ steering and evolving western disturbances support rain and snow, while summer easterly flow belongs to a wider monsoon system; no jet acts as a deterministic switch.", [14, 15, 16, 17]),
        (20, "Design an evidence chain for forecasting western-disturbance impacts over India.", "Combine upper-air soundings, satellite, radar, numerical ensembles, terrain and impact exposure, while separating observation, forecast, warning and verified outcome.", [17, 18, 19]),
    ],
    [
        plan("Weather elements as a linked system", [0], "Do not teach variables as an isolated list.", "Start with the energy-to-rainfall chain."),
        plan("Insolation and heat budget", [1, 2], "Separate shortwave receipt from atmospheric heating.", "Use an input-transfer-output diagram."),
        plan("Lapse rate and inversion", [3], "State the layer and stability consequence.", "Draw normal and inverted profiles."),
        plan("Pressure-gradient force", [4], "Gradient, not pressure alone, controls acceleration.", "Read isobar spacing before wind speed."),
        plan("Coriolis and friction", [5, 6], "Coriolis deflects but does not start wind.", "Compare upper and surface wind."),
        plan("Geostrophic upper-air balance", [7], "It is an approximation away from equator and friction.", "Use a force-vector sketch."),
        plan("Pressure belts and planetary winds", [8, 9], "Belts migrate and break into cells.", "Map the ideal pattern with seasonal caveats."),
        plan("Humidity and saturation", [10], "Relative humidity depends on temperature.", "Use a cooling-air parcel example."),
        plan("Cloud and fog formation", [11], "Saturation alone does not guarantee rain.", "Connect nuclei, lift and droplet growth."),
        plan("Rainfall mechanisms", [12], "Real storms can mix uplift mechanisms.", "Compare convectional, relief and frontal uplift."),
        plan("Troposphere structure", [13], "Depth varies with latitude and season.", "Link thermal expansion to convection."),
        plan("Jet stream mechanics", [14], "A jet core is not fixed at one pressure level.", "Connect temperature gradient to strong upper wind."),
        plan("STWJ and tropical easterly jet", [15, 16], "Neither jet alone determines seasonal rainfall.", "Place both within winter and summer circulation."),
        plan("Western disturbances and IMD observations", [17, 18], "A WD can be a trough or circulation, not only a surface low.", "Trace detection, steering and precipitation."),
        plan("Verified PYQs and forecast discipline", [19], "Forecast, warning and outcome are different claims.", "Close with source-date and uncertainty discipline."),
    ],
    [
        panel("Weather causation chain", "process-flow", ["INSOLATION -> surface and atmospheric heating", "TEMPERATURE GRADIENT -> pressure gradient", "WIND -> moisture transport and convergence", "LIFT + SATURATION -> cloud and precipitation"], ["Weather elements as a linked system"]),
        panel("Heat-budget ledger", "balance-sheet", ["SUN -> incoming shortwave", "SURFACE -> reflected + absorbed energy", "EARTH -> longwave + sensible + latent heat", "BALANCE -> temperature and circulation response"], ["Insolation and heat budget"]),
        panel("Stability profiles", "comparison-table", ["NORMAL TENDENCY -> temperature falls upward", "INVERSION -> temperature rises through layer", "STABLE LAYER -> vertical mixing suppressed", "SURFACE INVERSION -> fog and pollution trapping"], ["Lapse rate and inversion"]),
        panel("Wind-force triangle", "causal-system", ["PRESSURE GRADIENT -> starts acceleration", "CORIOLIS -> right north / left south", "FRICTION -> slows and crosses isobars", "ALOFT -> near-geostrophic parallel flow"], ["Pressure-gradient force", "Coriolis and friction", "Geostrophic upper-air balance"]),
        panel("Planetary circulation rail", "spatial-map", ["EQUATORIAL LOW -> convergence and ascent", "SUBTROPICAL HIGH -> descent and trades", "SUBPOLAR LOW -> westerly-polar interaction", "POLAR HIGH -> cold outflow; belts migrate"], ["Pressure belts and planetary winds"]),
        panel("Humidity-to-cloud chain", "process-flow", ["MOISTURE CONTENT + TEMPERATURE -> relative humidity", "COOLING TO SATURATION -> dew point reached", "NUCLEI + LIFT -> droplets or ice crystals", "GROWTH + FALL SPEED -> precipitation"], ["Humidity and saturation", "Cloud and fog formation"]),
        panel("Rainfall comparison", "comparison-table", ["CONVECTIONAL -> buoyant thermal ascent", "OROGRAPHIC -> forced relief ascent", "FRONTAL / CYCLONIC -> convergent dynamic ascent", "REAL EVENT -> mechanisms may combine"], ["Rainfall mechanisms"]),
        panel("Troposphere section", "vertical-map", ["SURFACE -> moisture, friction and heating", "MID LEVELS -> clouds, troughs and stability", "UPPER TROPOSPHERE -> jets and divergence", "TROPICS DEEPER / POLES SHALLOWER"], ["Troposphere structure"]),
        panel("Jet-stream engine", "causal-system", ["HORIZONTAL TEMPERATURE GRADIENT", "HEIGHT / PRESSURE GRADIENT ALOFT", "CORIOLIS BALANCE -> strong near-zonal wind", "ROSSBY WAVES -> ridges, troughs and steering"], ["Jet stream mechanics"]),
        panel("India seasonal jets", "seasonal-map", ["WINTER -> STWJ south of Himalaya sector", "STWJ -> steers western disturbances east", "SUMMER -> tropical easterly jet develops", "RULE -> jets are parts of wider circulation"], ["STWJ and tropical easterly jet"]),
        panel("Western-disturbance chain", "process-flow", ["UPPER TROUGH / LOW -> eastward westerly motion", "MOISTURE + DYNAMICAL LIFT -> cloud and rain/snow", "HIMALAYA + PLAINS -> terrain-specific impacts", "OUTCOME -> beneficial or damaging by timing/intensity"], ["Western disturbances and IMD observations"]),
        panel("Forecast evidence ladder", "institutional-ladder", ["RADIOSONDE / PILOT BALLOON -> upper-air state", "SATELLITE + RADAR -> cloud and precipitation", "NWP ENSEMBLE -> scenarios and uncertainty", "WARNING -> action; later observations verify outcome"], ["Verified PYQs and forecast discipline"]),
    ],
    ["insolation", "temperature inversion", "pressure gradient", "Coriolis", "relative humidity", "troposphere", "jet stream", "subtropical westerly jet", "tropical easterly jet", "western disturbances", "radiosonde", "pilot balloon", "isotherm", "cloudburst"],
    "Verified routing retains direct owner demands on weather elements and upper-air processes, including the 2021 and 2022 GS-I questions and relevant objective routes. No official answer letter is invented where the ledger withholds it, and no unrelated Disaster Management warning question is relabelled direct.",
    [
        ("2021", "GS-I", "Briefly mention the alignment of major mountain ranges of the world and explain their impact on local weather conditions, with examples. (250 words)", "Verified routed direct Mains demand.", "Map east-west and north-south ranges, then explain barrier, orographic rain, rain shadow, channelling, foehn-type descent and cold-air blocking. Use Himalaya and Western Ghats examples and qualify by synoptic wind direction, pass geometry and season."),
        ("2022", "GS-I", "Discuss how the troposphere determines weather processes. (250 words)", "Verified routed direct Mains demand.", "Link surface heating, water vapour, lapse rate, convection, condensation, pressure systems and upper-air steering within the troposphere. Add its greater tropical depth and the tropopause boundary. Qualify that stratospheric and oceanic influences can modulate tropospheric weather."),
        ("2024", "Prelims GS-I", "Inferences from January isothermal maps.", "Verified routed objective demand; official Set-A key exists locally but the routing ledger records no answer letter.", "Trace land-sea thermal contrast, current influence and continentality from the mapped isotherms. Preserve the official option order and do not manufacture an answer letter."),
        ("2025", "Prelims GS-I", "Atmospheric dust distribution across climatic zones.", "Verified routed objective demand; official Set-A key exists locally but the routing ledger records no answer letter.", "Use source, aridity, vegetation cover, uplift and washout rather than assuming uniform vertical or latitudinal distribution. Preserve the official option order and do not invent a key."),
    ],
    [
        "https://mausam.imd.gov.in/responsive/servicesMetUpperAir.php",
        "https://mausam.imd.gov.in/responsive/radar.php",
        "https://mausam.imd.gov.in/imd_latest/contents/satmet.php",
    ],
    "IMD's official upper-air, radar and satellite service pages are used only to establish observation and forecasting architecture. The live search found no sufficiently stable, topic-specific official September 2026 western-disturbance item, so no current event, jet trend, forecast or realised impact is claimed.",
    extra=["advanced/06_Himalayan-Glaciers-GLOF.md", "advanced/16_India-Monsoon-Mechanism.md", "basic/12_The-Oceans-Currents-Tides-Salinity.md"],
)


TOPIC_14 = common.topic(
    14,
    "Climate Classification (Koppen) / India Climatic Regions",
    "14_Climate-Classification-Koppen.md",
    "14_India-Climatic-Regions.md",
    "14_India-Climatic-Regions_Complete-Topic-Package.md",
    [
        ("Classification purpose", "A climate classification simplifies long-period temperature and moisture patterns for comparison, mapping or planning; its classes depend on variables, thresholds, period, scale and purpose."),
        ("Koppen empirical basis", "Koppen's system is empirical and vegetation-linked, using observed temperature and precipitation thresholds rather than directly classifying air masses or causal circulation."),
        ("Original major groups", "The original major groups are A tropical, B dry, C warm temperate, D snow or continental and E polar; H highland is a later practical addition, not an original sixth group."),
        ("A-group boundary", "In the usual Koppen grammar, A climates have every month's mean temperature at least 18 degrees Celsius, with second letters expressing rainfall seasonality."),
        ("B-group boundary", "B climates are defined first by precipitation falling below a temperature- and season-dependent dryness threshold, then divided into desert BW and steppe BS."),
        ("C-D convention", "C and D separation depends on the coldest-month threshold, for which minus 3 degrees Celsius and 0 degrees Celsius conventions both occur; an answer must state the convention."),
        ("E-group boundary", "E climates have no month with a mean temperature of at least 10 degrees Celsius, separating tundra ET from ice-cap EF by the warmest-month condition."),
        ("Second-letter grammar", "For A, C and D climates, f indicates no dry season, s a dry summer and w a dry winter; m denotes monsoon in the A group."),
        ("Third-letter grammar", "For C and D climates, a, b, c and d refine summer warmth or winter severity, while h and k commonly refine hot and cold dry climates in B-group applications."),
        ("Common tropical codes", "Af denotes tropical rainforest, Am tropical monsoon and Aw or As tropical wet-dry climates; the code describes threshold behaviour, not a complete causal explanation."),
        ("Common midlatitude codes", "Cfa, Cfb, Csa, Csb and Cwa are combinations of moisture seasonality and summer-temperature letters; similar code labels can mask different local mechanisms."),
        ("Climatological normal", "A climatological normal is a reference average, normally over 30 years; it is a baseline for anomalies rather than a forecast or promise of typical weather."),
        ("Anomaly-variability-trend", "An anomaly is departure from a stated normal, variability is fluctuation around a reference and trend is a multi-period direction; one month or season cannot redraw a climate region."),
        ("Boundary as transition", "A mapped climatic boundary is a modelled transition based on gridded or station data and interpolation, not a wall visible on the ground."),
        ("India climate controls", "India's climatic patterns reflect latitude, altitude, relief, continentality, monsoon circulation, western disturbances, tropical systems and ocean-atmosphere variability acting together."),
        ("India Koppen application", "Applied maps commonly identify tropical wet, monsoon, wet-dry, arid, semi-arid, humid subtropical or temperate and highland sectors, but exact codes and boundaries vary by dataset and convention."),
        ("Trewartha comparison", "Trewartha modifies Koppen to give middle-latitude and subtropical thermal regimes different emphasis; it remains a classification, not a direct hazard or crop map."),
        ("Thornthwaite comparison", "Thornthwaite emphasises water balance and potential evapotranspiration, making it useful for moisture effectiveness while increasing data and method dependence."),
        ("Planning-region distinction", "Agro-climatic regions organise climate and cropping conditions, whereas agro-ecological regions additionally integrate soils, landform and growing period; neither is identical to a Koppen map."),
        ("Official-data boundary", "IMD climate services provide normals, station or gridded data and climate products, but no single immutable official Koppen map should be asserted without naming source, period, resolution and threshold convention."),
    ],
    [
        "Do not call Koppen a genetic or circulation-based classification.",
        "Do not list H as one of Koppen's original five groups.",
        "Do not classify B climates by temperature alone.",
        "Do not quote a C-D threshold without stating whether minus 3 or 0 degrees Celsius is used.",
        "Do not reverse s as dry summer and w as dry winter.",
        "Do not assume the same code has identical causes and impacts everywhere.",
        "Do not treat a climatological normal as a forecast.",
        "Do not infer climate change from one positive anomaly.",
        "Do not draw a climatic boundary as a sharp natural wall.",
        "Do not claim one timeless set of Indian Koppen codes or exact region boundaries.",
        "Do not equate Koppen, Trewartha, Thornthwaite, agro-climatic and agro-ecological regions.",
        "Do not invent a direct UPSC PYQ where the routing ledgers show none.",
    ],
    [
        (10, "Explain why Koppen's classification is empirical and vegetation-linked rather than genetic.", "Its temperature and precipitation thresholds approximate vegetation limits and permit reproducible maps, but they do not directly explain circulation causes.", [0, 1, 2]),
        (10, "Decode the logic of the letters in Af, Am, Aw, BW, BS and Cwa.", "The first letter gives the major thermal-moisture group, the second rainfall seasonality or dryness type, and later letters refine temperature.", [3, 4, 7, 8, 9]),
        (15, "Critically examine the threshold and boundary problems in Koppen classification.", "Threshold conventions, station density, interpolation, topography and reference period can shift mapped classes, so reproducibility requires explicit methods.", [5, 6, 11, 13]),
        (15, "Explain the controls that create India's climatic diversity without relying on a code list.", "Latitude, altitude, relief, continentality, monsoon and synoptic-ocean drivers create the patterns that classifications summarise.", [14, 15]),
        (20, "Compare Koppen, Trewartha and Thornthwaite as tools for classifying Indian climate.", "Koppen offers communicable temperature-rainfall classes, Trewartha refines thermal zones and Thornthwaite adds water balance; purpose and data determine suitability.", [1, 16, 17]),
        (20, "Design a multi-layer climatic regionalisation for Indian planning under climate variability.", "Use transparent normals and trends, retain a descriptive climate layer, and overlay soils, growing period, hazards, water and livelihoods rather than forcing one map to answer every purpose.", [12, 13, 18, 19]),
    ],
    [
        plan("Why classify climate", [0], "Every map needs a stated purpose and scale.", "Begin with model utility and limits."),
        plan("Koppen's empirical design", [1, 2], "Keep vegetation linkage separate from causation.", "Explain the original A-E architecture."),
        plan("Tropical A climates", [3, 9], "Codes express thresholds, not full mechanisms.", "Decode Af, Am and Aw/As."),
        plan("Dry B climates", [4], "Apply dryness before desert-steppe division.", "Use precipitation-demand logic."),
        plan("Temperate C and continental D", [5], "State the minus 3 or 0 degree convention.", "Show why maps may differ."),
        plan("Polar E and highland H", [6], "H is a later practical addition.", "Separate thermal polar limits from elevation."),
        plan("Second-letter grammar", [7], "Do not reverse s and w.", "Use a seasonality key."),
        plan("Third-letter grammar", [8, 10], "Later letters refine, not replace, the first group.", "Decode common midlatitude codes."),
        plan("Normals and reference periods", [11], "A normal is a baseline, not predicted weather.", "Always write the period beside the map."),
        plan("Anomaly, variability and trend", [12], "One event cannot establish a trend.", "Use an evidence-strength ladder."),
        plan("Mapped boundaries and scale", [13], "Classification zones are transitional.", "Link stations, grids and interpolation."),
        plan("Controls of India's climatic mosaic", [14], "Reject one-factor monsoon explanations.", "Map relief, distance and circulation controls."),
        plan("Koppen regions applied to India", [15], "Do not claim one immutable code map.", "Name dataset and convention before boundaries."),
        plan("Trewartha, Thornthwaite and planning regions", [16, 17, 18], "Classification purpose decides the preferred framework.", "Compare descriptive, water-balance and land-use maps."),
        plan("Classification evidence and exam application", [19], "No direct route means no invented PYQ.", "Close with transparent source and method discipline."),
    ],
    [
        panel("Classification design gate", "decision-tree", ["PURPOSE -> comparison, explanation or planning", "VARIABLES -> temperature, rain or water balance", "METHOD -> thresholds, period, scale, interpolation", "OUTPUT -> useful model with explicit limits"], ["Why classify climate"]),
        panel("Koppen major groups", "classification-tree", ["A -> tropical thermal regime", "B -> dryness threshold first", "C / D -> coldest-month convention matters", "E -> warmest month below 10 C; H added later"], ["Koppen's empirical design", "Polar E and highland H"]),
        panel("Tropical code grammar", "comparison-table", ["Af -> no dry season", "Am -> monsoon short dry season logic", "Aw / As -> dry winter / dry summer", "RULE -> first letter climate, second rainfall"], ["Tropical A climates", "Second-letter grammar"]),
        panel("Dry-climate gate", "decision-tree", ["TEMPERATURE + RAIN SEASON -> dryness threshold", "PRECIPITATION BELOW THRESHOLD -> B group", "DRIER -> BW desert", "LESS DRY -> BS steppe; h/k thermal suffix"], ["Dry B climates", "Third-letter grammar"]),
        panel("C-D threshold firewall", "comparison-table", ["COLDEST MONTH -> C/D discriminator", "CONVENTION 1 -> minus 3 C boundary", "CONVENTION 2 -> 0 C boundary", "ANSWER RULE -> state convention before mapping"], ["Temperate C and continental D"]),
        panel("Normal-to-trend ladder", "evidence-ladder", ["NORMAL -> stated 30-year reference", "ANOMALY -> observation minus normal", "VARIABILITY -> spread and recurrence", "TREND -> multi-period direction with uncertainty"], ["Normals and reference periods", "Anomaly, variability and trend"]),
        panel("Climate-boundary model", "process-flow", ["STATIONS / GRIDS -> measured variables", "QUALITY CONTROL -> comparable records", "INTERPOLATION + THRESHOLDS -> class map", "GROUND REALITY -> transition, not wall"], ["Mapped boundaries and scale"]),
        panel("India control matrix", "causal-system", ["LATITUDE + ALTITUDE -> thermal structure", "RELIEF -> uplift, rain shadow, cold barrier", "SEA DISTANCE -> maritime / continental range", "MONSOON + WDs + OCEAN -> seasonal variability"], ["Controls of India's climatic mosaic"]),
        panel("India code-map boundary", "evidence-table", ["COMMON TYPES -> tropical, dry, subtropical, highland", "EXACT CODE -> depends on dataset and threshold", "BOUNDARY -> depends on scale and interpolation", "RULE -> cite source, period and convention"], ["Koppen regions applied to India"]),
        panel("Classification comparison", "comparison-table", ["KOPPEN -> temperature + precipitation thresholds", "TREWARTHA -> modified thermal zonation", "THORNTHWAITE -> water balance + PET", "CHOICE -> match method to question purpose"], ["Trewartha, Thornthwaite and planning regions"]),
        panel("Planning overlay", "layer-map", ["CLIMATE TYPE -> long-period thermal-rain pattern", "AGRO-CLIMATE -> crop and season context", "AGRO-ECOLOGY -> soil + landform + growing period", "RISK LAYER -> hazards, exposure and vulnerability"], ["Trewartha, Thornthwaite and planning regions"]),
        panel("Climate answer spine", "answer-spine", ["DEFINE -> purpose, variables and period", "DECODE -> letters and thresholds", "MAP -> India with transition caveat", "COMPARE -> method, use, limitation and verdict"], ["Classification evidence and exam application"]),
    ],
    ["Koppen", "empirical", "Af", "Am", "Aw", "BW", "BS", "Cwa", "minus 3", "0 degrees Celsius", "climatological normal", "Trewartha", "Thornthwaite", "agro-ecological"],
    "The audited routing ledgers contain no direct question owned by Geography Topic 14. Weather-element, monsoon, vegetation and crop-region questions remain with their routed owners. This package therefore records a transparent zero-direct-PYQ audit and does not invent wording, year, marks or key.",
    [],
    [
        "https://mausam.imd.gov.in/imd_latest/contents/pdf/pubbrochures/Climate%20Services.pdf",
        "https://mausam.imd.gov.in/",
    ],
    "IMD official climate-service material is used only to identify normals and climate-data products. No sufficiently clear official live item was found that establishes a new national Koppen map or revised region boundary, so no current code, boundary, forecast or measurement is claimed.",
    extra=["basic/13_Weather-Elements.md", "advanced/16_India-Monsoon-Mechanism.md", "basic/15_Hot-Wet-Equatorial-Climate.md"],
)


TOPICS_10_14 = [TOPIC_10, TOPIC_11, TOPIC_12, TOPIC_13, TOPIC_14]
