"""Authored Geography learner-v2 data for Topics 05-09."""

from __future__ import annotations

import generate_geography_common as common


def plan(
    title: str, indexes: list[int], caution: str, exam_use: str
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_05 = common.topic(
    5,
    "Landforms by Running Water / India Drainage and Interlinking",
    "05_Landforms-by-Running-Water.md",
    "05_India-Drainage-and-Interlinking.md",
    "05_India-Drainage-and-Interlinking_Complete-Topic-Package.md",
    [
        ("Drainage basin anatomy", "A drainage basin is the area contributing runoff to a river system; a watershed or divide separates neighbouring basins, while tributaries join a trunk stream before its outlet."),
        ("River work and load", "Running water erodes by hydraulic action, corrasion or abrasion, attrition and solution; it transports load by traction, saltation, suspension and solution before deposition when competence falls."),
        ("Long-profile adjustment", "A graded river tends toward a concave-up long profile in dynamic balance with discharge, sediment load, rock resistance and base level; uplift, floods and dams can interrupt the tendency."),
        ("Upper-course suite", "Steep gradients favour vertical incision, V-shaped valleys, gorges, rapids, waterfalls and interlocking spurs, but local rock and discharge matter more than a rigid stage label."),
        ("Meander and floodplain system", "Helicoidal flow links outer-bank erosion to inner-bank deposition; neck cutoff can form an ox-bow lake, while repeated overbank deposition builds floodplains and natural levees."),
        ("Delta-estuary discriminator", "A delta develops where sediment accumulation exceeds marine removal and subsidence, whereas an estuary is a drowned or tidally scoured river mouth; estuarine is not a delta shape."),
        ("Drainage-pattern diagnosis", "Dendritic drainage suggests broadly uniform resistance; trellis alternating hard-soft bands; rectangular joints or faults; radial a central high; centripetal an enclosed basin."),
        ("Antecedence and superimposition", "An antecedent river maintains a course across rising relief by incision, while a superimposed river inherits a pattern from a removed cover and cuts into unrelated underlying structure."),
        ("River capture", "Headward erosion can divert a neighbouring stream, producing an elbow of capture, wind gap and misfit reach; capture is a drainage-evolution process, not ordinary tributary joining."),
        ("Himalayan drainage", "The Indus, Ganga and Brahmaputra systems cross high relief and international boundaries; their regimes combine rain, snow or glacier melt and groundwater in varying proportions."),
        ("Peninsular drainage", "Most large Peninsular rivers follow the eastward plateau slope toward Bay of Bengal deltas, while Narmada and Tapi use west-flowing structural troughs and many Ghats streams are short and steep."),
        ("Named river map hooks", "The named Ganga begins at Devprayag after the Bhagirathi-Alaknanda confluence; Godavari rises near Trimbakeshwar, Krishna near Mahabaleshwar, Kaveri at Talakaveri and Narmada at Amarkantak."),
        ("Sediment-budget comparison", "Delta behaviour depends on basin sediment supply, wave-tidal energy, subsidence, relative sea level and distributary behaviour; equal sea-level forcing can produce different trajectories."),
        ("Floodplain risk chain", "Channel aggradation, migration, floodplain occupation, embankment confinement and drainage obstruction convert a natural inundation process into differentiated exposure and disaster risk."),
        ("Inter-basin transfer test", "A defensible link requires seasonal donor-basin accounting, recipient demand and hydrogeological fit, downstream and environmental-flow needs, conveyance losses and viable local alternatives."),
        ("Ken-Betwa direction and status", "Official NWDA material identifies Ken-to-Betwa transfer and the project as the first National Perspective Plan link under implementation; implementation is not proof of delivered outcomes."),
        ("Panna landscape boundary", "Ken-Betwa appraisal must include habitat connectivity, downstream flow and sediment, forest and biodiversity effects, displacement, participation, mitigation compliance and long-term monitoring."),
        ("Flood-navigation limits", "A link moderates floods only with storage space, timing and operating rules; navigation separately requires dependable depth, locks, terminals and sediment management."),
        ("Verified PYQ routes", "The routed direct Mains demand is 2020 GS-I on interlinking for droughts, floods and navigation; 2021 Prelims routes test Indus tributaries and rivers rising in the Eastern Ghats."),
        ("Qualified basin governance", "River planning is a basin-scale, federal and ecological exercise combining demand management, recharge, reuse, reservoir operations, floodplain restoration and selective infrastructure."),
    ],
    [
        "Do not treat upper, middle and lower courses as rigid boxes that exclude local variation.",
        "Do not confuse corrasion with corrosion or attrition with bank erosion.",
        "Do not call every wide river-mouth deposit a delta.",
        "Do not treat antecedent and superimposed drainage as synonyms.",
        "Do not label the entire Himalayan network antecedent.",
        "Do not say every Peninsular river flows east.",
        "Do not confuse the Bhagirathi headstream with the named Ganga at Devprayag.",
        "Do not infer basin surplus from annual rainfall alone.",
        "Do not reverse the Ken-to-Betwa transfer direction.",
        "Do not treat construction status as evidence that promised benefits have been delivered.",
        "Do not assume a canal automatically solves drought, flood and navigation together.",
        "Do not quote river lengths, basin areas, project costs or command areas without a dated primary source.",
    ],
    [
        (10, "Explain how a river's energy-load relation creates a sequence of erosional and depositional landforms.", "Fluvial form follows changing energy relative to load, modified by rock, discharge, base level and tectonic or human interruption.", [1, 2, 3, 4]),
        (10, "Differentiate antecedent drainage, superimposed drainage and river capture with diagnostic evidence.", "The three concepts differ by timing and mechanism: persistence through uplift, inheritance from cover, and diversion by headward erosion.", [7, 8]),
        (15, "Compare Himalayan and Peninsular drainage on regime, structure, valley form and mouth type.", "Relief, geological age, water sources and structural controls explain the contrast, while west-flowing trough rivers and regulated reaches qualify stereotypes.", [9, 10, 11]),
        (15, "Assess why deltas facing the same sea-level trend can show different patterns of advance and retreat.", "Sediment budget, marine energy, subsidence and distributary management mediate common sea-level forcing.", [5, 12, 13]),
        (20, "Critically examine river interlinking as a response to droughts, floods and interrupted navigation.", "Each claimed benefit requires a separate mechanism and test; selective transfer can help, but basin accounting, ecology, federalism and alternatives control viability.", [14, 15, 16, 17, 19]),
        (20, "Design an integrated basin-governance framework for Indian rivers under climatic and sediment uncertainty.", "Combine hydrological accounting, sediment and floodplain management, demand-side reform, federal coordination, ecological safeguards and adaptive monitoring.", [12, 13, 14, 16, 19]),
    ],
    [
        plan("Basin, divide and channel network", [0], "A watershed is the boundary, not the entire river channel.", "Begin map answers with basin anatomy."),
        plan("Erosion, transport and deposition", [1], "The same reach may perform all three functions during different flows.", "Use agent-process-load vocabulary precisely."),
        plan("Long profile and graded adjustment", [2], "A graded profile is a dynamic tendency, not a final fixed form.", "Explain adjustment rather than merely drawing a curve."),
        plan("Upper-course erosional suite", [3], "Landforms reflect local gradient and resistance, not age labels alone.", "Derive gorge, waterfall and V-valley from process."),
        plan("Meanders, ox-bows and floodplains", [4], "A floodplain is a working river space, not vacant land.", "Link channel migration to risk."),
        plan("Delta versus estuary", [5, 12], "Mouth form and net shoreline trajectory are separate questions.", "Use the five-part sediment-budget test."),
        plan("Drainage patterns as structural evidence", [6], "Pattern is evidence of controls, not a decorative map label.", "Match form to geology and relief."),
        plan("Antecedence, superimposition and capture", [7, 8], "Timing and mechanism must remain separate.", "Use gorges, elbows and wind gaps diagnostically."),
        plan("Himalayan river systems", [9], "Perennial does not mean uniform discharge or glacier-only flow.", "Build a rain-snow-groundwater regime answer."),
        plan("Peninsular river systems", [10, 11], "Eastward flow is the broad rule with structural and short-stream exceptions.", "Draw the off-centre Western Ghats divide."),
        plan("Floodplain and delta vulnerability", [13], "Rainfall alone does not explain disaster losses.", "Connect channel process, exposure and governance."),
        plan("Inter-basin transfer accounting", [14], "Annual basin totals conceal seasonal and ecological claims.", "Test donor, recipient and alternatives."),
        plan("Ken-Betwa and Panna", [15, 16], "Project status proves neither benefit delivery nor ecological failure.", "Use a dated, conditional case study."),
        plan("Flood, navigation and federal limits", [17, 19], "One canal cannot satisfy different objectives automatically.", "Separate mechanisms before giving a verdict."),
        plan("Verified routes and final basin spine", [18, 19], "Preserve official routing and do not invent objective keys.", "Close with a basin-scale qualified conclusion."),
    ],
    [
        panel("Basin anatomy", "root-axes", ["RIDGELINE -> watershed / drainage divide", "SLOPES -> runoff enters tributaries", "TRIBUTARIES -> trunk stream -> outlet", "BASIN RULE -> upstream change travels downstream"], ["Basin, divide and channel network"]),
        panel("River-work engine", "process-flow", ["ENERGY + DISCHARGE -> erosion capacity", "LOAD SIZE + VOLUME -> transport demand", "COMPETENCE FALLS -> deposition begins", "FEEDBACK -> bed form alters velocity and load"], ["Erosion, transport and deposition"]),
        panel("Long-profile controls", "causal-system", ["UPLIFT / BASE LEVEL -> potential-energy change", "ROCK + DISCHARGE -> local incision", "SEDIMENT -> abrasion, transport and storage", "GRADED CURVE -> moving dynamic balance"], ["Long profile and graded adjustment"]),
        panel("Meander-floodplain loop", "process-flow", ["OUTER BANK -> faster flow -> erosion", "INNER BANK -> slower flow -> point bar", "NECK CUTOFF -> ox-bow lake", "OVERBANK SILT -> floodplain + natural levee"], ["Meanders, ox-bows and floodplains"]),
        panel("Drainage-pattern matrix", "comparison-table", ["DENDRITIC -> uniform resistance", "TRELLIS -> alternating resistant bands", "RECTANGULAR -> joints and faults", "RADIAL / CENTRIPETAL -> outward high / inward basin"], ["Drainage patterns as structural evidence"]),
        panel("Drainage-evolution firewall", "comparison-table", ["ANTECEDENT -> river older than uplift", "SUPERIMPOSED -> cover pattern inherited below", "CAPTURE -> headward erosion diverts neighbour", "FIELD CUES -> gorge / discordance / elbow-wind gap"], ["Antecedence, superimposition and capture"]),
        panel("India river-system contrast", "comparison-table", ["HIMALAYAN -> high relief, mixed perennial inputs", "PENINSULAR -> old shield, monsoon-dominant regime", "EAST -> long rivers and major deltas", "WEST -> Narmada-Tapi troughs + short Ghats streams"], ["Himalayan river systems", "Peninsular river systems"]),
        panel("Source-course-mouth rail", "spatial-map", ["INDUS -> Tibetan headwaters -> Arabian Sea", "GANGA -> Devprayag name -> Bengal delta", "BRAHMAPUTRA -> Tsangpo-Siang -> joined delta", "PENINSULA -> Godavari-Krishna-Kaveri / Narmada-Tapi"], ["Peninsular river systems"]),
        panel("Delta budget", "evidence-table", ["INPUT -> basin sediment delivery", "REMOVAL -> waves, tides and cyclone scour", "VERTICAL -> compaction + relative sea level", "CHANNELS -> distributary mobility or confinement"], ["Delta versus estuary"]),
        panel("Transfer viability test", "decision-tree", ["DONOR -> seasonal water after existing claims", "RECIPIENT -> demand, soil, aquifer and delivery fit", "CORRIDOR -> loss, energy, ecology and people", "ALTERNATIVES -> recharge, efficiency, reuse, operations"], ["Inter-basin transfer accounting"]),
        panel("Ken-Betwa boundary", "case-study", ["DIRECTION -> Ken basin to Betwa basin", "STATUS -> official material says under implementation", "LANDSCAPE -> Panna connectivity + downstream flow", "RULE -> status is not measured outcome"], ["Ken-Betwa and Panna"]),
        panel("Basin answer spine", "answer-spine", ["DEFINE + MAP -> basin and direction", "EXPLAIN -> process, timing and sediment", "ASSESS -> benefit mechanism against limits", "VERDICT -> selective, adaptive and basin-wide"], ["Verified routes and final basin spine"]),
    ],
    ["hydraulic action", "graded long profile", "ox-bow lake", "dendritic", "antecedent", "superimposed", "river capture", "Devprayag", "Narmada", "Tapi", "sediment budget", "Ken-Betwa", "Panna Tiger Reserve", "environmental flow"],
    "Verified routing retains the 2020 GS-I interlinking demand and two 2021 Prelims river-map demands. The local routing ledgers do not supply official keys for those objective items; no answer letter is invented.",
    [
        ("2020", "GS-I", "The interlinking of rivers can provide viable solutions to droughts, floods and interrupted navigation. Critically examine. (250 words)", "Verified routed direct Mains demand.", "Separate the three claims. Transfer may relocate seasonal water; flood moderation needs storage and operating rules; navigation needs depth and infrastructure. Use Ken-to-Betwa implementation as dated evidence, then test donor balance, downstream and environmental flows, Panna landscape effects, social costs, federal coordination and cheaper local alternatives before a conditional verdict."),
        ("2021", "Prelims GS-I", "Indus river-system tributaries and their direct junctions.", "Verified routed objective demand; official key unavailable in the ledger.", "Solve by tracing direct confluences on a basin sketch rather than by proximity. Preserve the official option order when using the paper; do not infer an answer letter from this neutral routing summary."),
        ("2021", "Prelims GS-I", "Identification of rivers rising in the Eastern Ghats.", "Verified routed objective demand; official key unavailable in the ledger.", "Separate origin from course: several rivers cross or drain the Eastern Ghats without rising there. Use source-location mapping and do not manufacture an official key."),
    ],
    [
        "https://nwda.gov.in/upload/jal%20VikasApril%202026.pdf",
        "https://nwda.gov.in/upload/Ken-Betwa%20Link%20Project%20.pdf",
    ],
    "NWDA's April 2026 publication and project material are used only to verify Ken-to-Betwa direction and an under-implementation status. No cost, command-area, completion, benefit-delivery or ecological-outcome figure is restated.",
    extra=["basic/04_Weathering-MassMovement-Groundwater.md", "basic/09_Lakes.md", "basic/10_Coastal-Landforms.md"],
)


TOPIC_06 = common.topic(
    6,
    "Landforms of Glaciation / Himalayan Glaciers-GLOF",
    "06_Landforms-of-Glaciation.md",
    "06_Himalayan-Glaciers-GLOF.md",
    "06_Himalayan-Glaciers-GLOF_Complete-Topic-Package.md",
    [
        ("Glacier definition", "A glacier is compacted and recrystallised land ice thick enough to deform or slide under gravity; a persistent snowfield need not be a glacier because it may not flow."),
        ("Mass-balance system", "Accumulation adds snow and refrozen water, ablation removes mass, and net balance is their difference over a stated glacier and period."),
        ("ELA, snowline and snout", "The equilibrium-line altitude balances annual accumulation and ablation; the climatic snowline is a long-term regional limit, while the snout is the glacier terminus."),
        ("Forward-flow retreat paradox", "Ice can continue moving down-valley while the snout retreats when ablation at the terminus exceeds forward ice delivery."),
        ("Debris-cover qualification", "Thin debris can enhance melt by lowering albedo, whereas sufficiently thick debris can insulate; debris-covered tongues may thin without rapid visible snout retreat."),
        ("Glacial erosion", "Plucking detaches jointed blocks and abrasion by entrained debris polishes, striates and grinds bedrock, producing rock flour and asymmetric roche moutonnee forms."),
        ("Erosional landform suite", "Cirques, aretes and horns develop around glacier heads; valley ice widens and deepens V-valleys into U-shaped troughs and leaves hanging tributary valleys."),
        ("Fjord discriminator", "A fjord is a marine-flooded glacial trough, whereas a ria is a drowned river valley; marine inundation follows rather than creates the glacial excavation."),
        ("Till and moraine", "Direct ice deposition is generally unsorted till; lateral, medial, terminal and ground moraines describe debris position or form."),
        ("Meltwater deposits", "Eskers are sinuous ridges deposited by subglacial or englacial streams, while outwash plains contain relatively sorted sediment spread by braided meltwater."),
        ("Ice-mass sea-level rule", "Loss of grounded glaciers, ice caps and ice sheets adds ocean mass; floating sea ice or shelf melt does not directly add mass beyond displacement, though shelves can buttress grounded ice."),
        ("Himalayan map discipline", "Gangotri links to the Bhagirathi, Zemu to the Teesta, Bara Shigri to the Chenab system and Siachen to the Nubra-Shyok-Indus system; map claims must remain distinct from boundary claims."),
        ("Water-timing effect", "Sustained ice loss can initially raise local melt contribution but later weaken lean-season and drought-year buffering; monsoon rain, snow and groundwater prevent a uniform all-rivers-dry conclusion."),
        ("Glacial-lake formation", "Retreat can expose overdeepened basins or leave moraine dams that store water; lake existence alone does not establish instability or downstream risk."),
        ("GLOF mechanism", "A GLOF is sudden lake release after overtopping or dam failure; triggers can include slope failure, ice or rock entry, intense inflow, piping, erosion or seismic disturbance."),
        ("Hazard-risk distinction", "GLOF hazard depends on lake, dam, slope and breach processes; risk additionally requires exposed people, settlements, roads, hydropower and limited warning or evacuation capacity."),
        ("South Lhonak boundary", "South Lhonak was a moraine-dammed lake involved in the October 2023 Teesta disaster; event-specific work examines slope movement, impulse, overtopping and breach without reducing attribution to warming alone."),
        ("Risk-reduction stack", "Inventory and remote sensing must lead to field assessment, thresholds and warning, communication and drills, land-use controls, evacuation routes and GLOF-informed infrastructure design."),
        ("Verified PYQ routes", "Direct routed demands include 2020 GS-I on glacier melting and Indian water resources, 2023 GS-I on fjords and 2019 Prelims glacier-river matching."),
        ("Current evidence boundary", "SAC's official Himalayan Glacier Inventory Atlas remains the mapping portal. ISRO's 22 April 2024 assessment compared 2,431 lakes larger than 10 hectares in the 2016-17 inventory with observations since 1984 and identified 676 expanding lakes, including 130 within India; the dated inventory does not itself establish present GLOF probability."),
    ],
    [
        "Do not call every persistent snow patch a glacier.",
        "Do not equate ELA, climatic snowline and snout elevation.",
        "Do not say a retreating glacier flows uphill.",
        "Do not claim all debris cover increases melt.",
        "Do not reverse the stoss and lee sides of a roche moutonnee.",
        "Do not confuse till with sorted outwash.",
        "Do not confuse a fjord with a ria.",
        "Do not say floating sea-ice melt directly raises sea level like grounded-ice loss.",
        "Do not treat every glacial lake as an imminent GLOF.",
        "Do not conflate avalanche, landslide, cloudburst and GLOF.",
        "Do not attribute a specific GLOF to warming without an event-specific chain.",
        "Do not invent glacier counts, retreat rates, lake counts, discharge shares or loss figures.",
    ],
    [
        (10, "Explain glacier mass balance and the apparent paradox of a retreating yet forward-flowing glacier.", "Mass balance controls geometry, while the terminus retreats when local loss exceeds ice delivery even though ice motion remains downslope.", [0, 1, 2, 3, 4]),
        (10, "Differentiate the principal erosional and depositional landforms of valley glaciation.", "Agent, process, form and sediment sorting distinguish plucking-abrasion landforms from till and meltwater deposits.", [5, 6, 8, 9]),
        (15, "Explain fjord formation and distinguish fjords from rias.", "Valley-glacier overdeepening followed by marine inundation creates fjords; drowned fluvial valleys create rias.", [6, 7]),
        (15, "Assess the far-reaching effects of Himalayan glacier loss on India's water resources.", "The strongest effect is altered timing and reliability in glacierised headwaters, qualified by monsoon, snow, groundwater and basin heterogeneity.", [11, 12, 19]),
        (20, "Analyse GLOF risk as an interaction of cryospheric change, geomorphic instability and valley-floor development.", "Risk arises from lake-dam-slope hazard plus downstream exposure and vulnerability, not from lake growth or warming alone.", [13, 14, 15, 16, 17]),
        (20, "Design a Himalayan cryosphere risk-governance strategy integrating observation, warning, land use and infrastructure.", "A complete strategy joins remote inventory to field thresholds, interoperable warning, evacuation, zoning, dam safety and transparent uncertainty.", [15, 17, 19]),
    ],
    [
        plan("What makes flowing glacier ice", [0], "Persistent snow without flow is not a glacier.", "Define the land-ice system before naming forms."),
        plan("Accumulation, ablation and ELA", [1, 2], "Every balance claim needs a glacier and period.", "Use budget vocabulary instead of temperature slogans."),
        plan("Flow, retreat and debris cover", [3, 4], "Snout movement is not a complete mass-balance metric.", "Explain geometry through delivery versus loss."),
        plan("Plucking and abrasion", [5], "Both processes can operate together on structured bedrock.", "Link mechanism to polish, striation and asymmetry."),
        plan("Cirque-to-trough erosional suite", [6], "A U-valley is glacial; a V-valley is primarily fluvial.", "Reconstruct the erosional landscape."),
        plan("Fjords and rias", [7], "The sea floods an existing trough; it does not excavate it.", "Prepare the direct 2023 route."),
        plan("Till, moraine, esker and outwash", [8, 9], "Sorting reveals whether ice or meltwater deposited the load.", "Use agent and texture for elimination."),
        plan("Grounded and floating ice", [10], "Ice shelf loss can matter indirectly through buttressing.", "Apply the displacement rule carefully."),
        plan("Himalayan glacier map hooks", [11], "Physical mapping must not be turned into a political-boundary assertion.", "Solve glacier-river matching."),
        plan("Glacier loss and water timing", [12], "Avoid uniform annual-flow-collapse claims.", "Prepare the 2020 GS-I water-resources answer."),
        plan("How glacial lakes form", [13], "Lake growth is not identical to dam instability.", "Separate inventory from hazard assessment."),
        plan("GLOF trigger-to-breach chain", [14], "GLOF is a release mechanism, not a synonym for mountain flood.", "Explain trigger, overtopping or failure and cascade."),
        plan("Hazard, exposure and South Lhonak", [15, 16], "Event attribution must remain evidence-specific.", "Build a bounded Teesta case."),
        plan("Monitoring and risk reduction", [17, 19], "Remote sensing cannot replace field assessment and last-mile warning.", "Create an end-to-end governance stack."),
        plan("Verified routes and cryosphere spine", [18, 19], "Do not invent official objective keys or dynamic rates.", "Close with process, map, risk and qualification."),
    ],
    [
        panel("Glacier budget", "root-axes", ["ACCUMULATION -> snowfall, avalanche and refreezing", "ELA -> annual gain equals annual loss", "ABLATION -> melt, sublimation and calving where relevant", "NET BALANCE -> geometry responds with a lag"], ["Accumulation, ablation and ELA"]),
        panel("Retreat paradox", "causal-system", ["ICE PARTICLES -> continue moving downslope", "TERMINUS -> receives forward ice flux", "ABLATION > DELIVERY -> snout shifts up-valley", "METRIC RULE -> flow direction differs from margin change"], ["Flow, retreat and debris cover"]),
        panel("Erosion suite", "process-flow", ["PLUCKING -> jointed blocks removed", "ABRASION -> polish, striae and rock flour", "CIRQUE / ARETE / HORN -> headwall system", "U-TROUGH / HANGING VALLEY -> valley-scale overdeepening"], ["Plucking and abrasion", "Cirque-to-trough erosional suite"]),
        panel("Fjord-ria firewall", "comparison-table", ["FJORD -> glacial trough later flooded by sea", "RIA -> river valley later drowned by sea", "FJORD CUES -> deep water, steep walls, hanging valleys", "RULE -> inundation preserves different pre-existing valleys"], ["Fjords and rias"]),
        panel("Depositional sorting", "comparison-table", ["TILL / MORAINE -> direct ice, generally unsorted", "ESKER -> meltwater ridge in or under ice", "OUTWASH -> braided meltwater, relatively sorted", "DRUMLIN -> streamlined drift/till landform"], ["Till, moraine, esker and outwash"]),
        panel("Ice-mass family", "hierarchy", ["GROUNDED -> glacier, ice cap, ice sheet", "FLOATING -> shelf, iceberg and sea ice", "SEA LEVEL -> grounded loss adds ocean mass", "BUTTRESSING -> shelf loss can accelerate inland discharge"], ["Grounded and floating ice"]),
        panel("Himalayan map hooks", "spatial-map", ["GANGOTRI -> Bhagirathi", "ZEMU -> Teesta", "BARA SHIGRI -> Chenab system", "SIACHEN -> Nubra-Shyok-Indus system"], ["Himalayan glacier map hooks"]),
        panel("Water-timing sequence", "timeline", ["EARLY LOSS -> local melt contribution may rise", "STORED ICE DECLINES -> buffering weakens", "LEAN SEASON -> reliability risk grows locally", "QUALIFIER -> monsoon, snow and groundwater vary by basin"], ["Glacier loss and water timing"]),
        panel("Glacial-lake test", "decision-tree", ["BASIN / DAM -> how water is impounded", "SLOPE + ICE -> possible displacement trigger", "DAM CONDITION -> overtopping, piping or erosion", "DOWNSTREAM -> exposure converts hazard into risk"], ["How glacial lakes form", "Hazard, exposure and South Lhonak"]),
        panel("GLOF cascade", "process-flow", ["TRIGGER -> slope failure, inflow or instability", "WAVE / OVERTOPPING -> dam erosion begins", "BREACH -> sudden release + sediment", "VALLEY -> constrictions and assets shape consequences"], ["GLOF trigger-to-breach chain"]),
        panel("Risk-reduction stack", "ladder", ["SATELLITE INVENTORY -> changing lakes and slopes", "FIELD ASSESSMENT -> dam material and thresholds", "WARNING + DRILLS -> last-mile action", "LAND USE + DESIGN -> reduce exposure and fragility"], ["Monitoring and risk reduction"]),
        panel("Cryosphere answer spine", "answer-spine", ["DEFINE -> glacier, lake, GLOF and risk", "MAP -> glacier-basin relation", "EXPLAIN -> budget, trigger and breach", "QUALIFY -> heterogeneity, attribution and data date"], ["Verified routes and cryosphere spine"]),
    ],
    ["equilibrium-line altitude", "snout", "plucking", "abrasion", "roche moutonnee", "fjord", "ria", "till", "moraine", "esker", "outwash", "Gangotri", "Zemu", "South Lhonak", "GLOF"],
    "Verified routing retains the 2020 and 2023 GS-I questions and the 2019 glacier-river objective route. Older objective keys unavailable locally remain explicitly unverified.",
    [
        ("2020", "GS-I", "How will the melting of Himalayan glaciers have a far-reaching impact on the water resources of India? (150 words)", "Verified routed direct Mains demand.", "Explain phased water timing: local melt may initially increase, but reduced stored ice can later weaken lean-season buffering. Link irrigation, hydropower, sediment, ecology and hazard, then qualify with monsoon rain, snow, groundwater, debris and basin-specific glacier fractions."),
        ("2023", "GS-I", "How are fjords formed and why do they constitute picturesque areas? (150 words)", "Verified routed direct Mains demand.", "Trace valley-glacier plucking and abrasion to an overdeepened U-trough, then deglaciation and marine inundation. Steep walls, deep water and hanging-valley waterfalls explain scenery. Distinguish a ria as a drowned river valley."),
        ("2019", "Prelims GS-I", "Matching Himalayan glaciers with associated river systems.", "Verified routed objective demand; official key unavailable locally.", "Use the secure pairs Gangotri-Bhagirathi, Zemu-Teesta, Bara Shigri-Chenab and Siachen-Nubra. Preserve the official options and label any answer inference separately."),
    ],
    [
        "https://vedas.sac.gov.in/en/Himalayan_Glacier_Inventory_Atlas.html",
        "https://www.isro.gov.in/Satellite_Insights_Expanding_Glacial_Lakes_Indian_Himalayas.html",
        "https://cwc.gov.in/glacial-lake-outburst-floods-glof",
        "https://cwc.gov.in/glacial-lakeswater-bodies-himalayan-region",
        "https://mitigation.ndma.gov.in/ndmahr-admin/public/uploads/advertisement_document/file63791735554350.pdf",
    ],
    "Rechecked 2026-09-05: SAC's atlas remains the official glacier inventory portal; ISRO's 22 April 2024 assessment supplies inventory-period lake counts, CWC's live GLOF pages supply the monitoring rationale and reports, and NDMA supplies the management guideline. No inventory count is presented as a current risk ranking or event forecast.",
    extra=["basic/05_Landforms-by-Running-Water.md", "basic/09_Lakes.md"],
)


TOPIC_07 = common.topic(
    7,
    "Arid Desert Landforms / Thar Desertification",
    "07_Arid-Desert-Landforms.md",
    "07_Thar-Desertification.md",
    "07_Thar-Desertification_Complete-Topic-Package.md",
    [
        ("Concept boundary", "A desert is a climatic region, aridity a long-term moisture deficit, drought a temporary anomaly, land degradation a broad decline in condition, and desertification dryland degradation."),
        ("Aridity controls", "Subtropical subsidence, continentality, rain shadow, cold currents and polar cold can create deserts; heat alone is neither necessary nor sufficient."),
        ("Weathering in arid lands", "Large thermal ranges, salt crystallisation and episodic wetting weaken exposed rock, while sparse cover leaves debris available to wind and flash runoff."),
        ("Aeolian transport", "Wind moves coarse particles mainly by surface creep, sand by saltation and fine dust by suspension; deflation removes loose material and abrasion sandblasts exposed surfaces."),
        ("Erosional landforms", "Deflation hollows, desert pavement, ventifacts, yardangs, zeugens, rock pedestals and inselbergs reflect different combinations of wind, structure and weathering."),
        ("Dune anatomy", "A barchan has horns pointing downwind under limited sand and one prevailing wind; transverse, longitudinal, parabolic and star dunes indicate different sand, vegetation and wind regimes."),
        ("Water-built desert forms", "Wadis, alluvial fans, bajadas, pediments, playas and salt flats show that episodic runoff and evaporation are integral to desert geomorphology."),
        ("Thar spatial mosaic", "The Thar includes dune fields, interdunes, rocky residuals, pediments, alluvium, playas, settlements and canal-modified tracts; it is not one continuous erg."),
        ("Thar climate and ecology", "Highly variable rainfall, high evaporative demand, ephemeral drainage and pulse-based productivity support drought-adapted vegetation, pastoral mobility and risk-spreading livelihoods."),
        ("Origin debate", "The Thar is polygenetic: tectonic and drainage history, monsoon variability, wind reworking and human land use operated over different timescales; one-cause origin claims are unsafe."),
        ("Natural susceptibility", "Low and variable rainfall, erodible sediment, strong winds, saline basins and slow biological recovery create susceptibility without proving degradation."),
        ("Human accelerators", "Vegetation removal, poorly managed grazing, repeated tillage, groundwater stress, mining, infrastructure fragmentation and unsuitable irrigation can exceed recovery thresholds."),
        ("Aravalli function", "The Aravalli influences relief, drainage, habitat connectivity and local erosion control, but it is not a complete wall that mechanically blocks all desert movement."),
        ("Indira Gandhi Canal balance", "Canal irrigation can support farming, water supply and settlement while seepage, waterlogging, salinity, invasive spread and crop-water mismatch create new risks where drainage is weak."),
        ("Desertification beyond desert", "The 2020 GS-I wording invites examples beyond visible deserts, but strict UNCCD usage confines desertification to arid, semi-arid and dry sub-humid lands; humid cases are broader land degradation."),
        ("LDN logic", "Land Degradation Neutrality seeks to balance anticipated losses with measures that avoid, reduce and reverse degradation while protecting land-based natural capital."),
        ("Process-matched restoration", "Dune stabilisation, shelterbelts, native grass and rangeland recovery, watershed treatment, drainage, salinity management and community institutions must match the diagnosed process."),
        ("Monitoring discipline", "Land-cover change, vegetation productivity, soil carbon and field indicators need scale, baseline and causal interpretation; mapped degradation is not automatically current condition or programme impact."),
        ("Verified PYQ boundary", "The central routing ledger assigns the 2020 desertification demand to Environment and Ecology, and the checked ledgers contain no direct Geography Topic 07 route; those questions remain cross-owner context only."),
        ("Current evidence boundary", "SAC's 2021 atlas reports 97.85 million hectares, or 29.77 percent of India's geographical area, under land degradation/desertification in 2018-19. This is a dated national mapping baseline, not a September 2026 condition report or a Thar-only percentage."),
    ],
    [
        "Do not equate a desert with desertification.",
        "Do not equate one drought year with persistent land degradation.",
        "Do not say all deserts are hot.",
        "Do not attribute every pedestal or mushroom rock solely to wind abrasion.",
        "Do not reverse the downwind direction of barchan horns.",
        "Do not ignore episodic running water in desert landform development.",
        "Do not describe the Thar as a continuous sea of mobile dunes.",
        "Do not claim the Aravalli completely blocks desert expansion.",
        "Do not assume irrigation automatically reverses degradation.",
        "Do not call humid-region erosion desertification without a convention caveat.",
        "Do not quote the 2018-19 atlas baseline as a 2026 measurement.",
        "Do not invent COP17 outcomes, restoration achievements or current desertification percentages.",
    ],
    [
        (10, "Differentiate desert, aridity, drought, land degradation and desertification.", "The concepts occupy different climatic, temporal and ecological levels; policy fails when they are collapsed.", [0, 14]),
        (10, "Explain how wind and episodic water jointly create arid landforms.", "Aeolian erosion and deposition interact with weathering, flash runoff, fan building, playa flooding and evaporation.", [2, 3, 4, 5, 6]),
        (15, "Describe the Thar as a dynamic geomorphic and livelihood mosaic rather than a uniform sand sea.", "Dunes, pediments, playas, drainage, ecological pulses and human adaptation create regional diversity.", [7, 8, 9]),
        (15, "Assess the role of the Aravalli and the Indira Gandhi Canal in shaping desertification risk.", "Both alter spatial processes and livelihoods, but neither is a single-direction barrier or cure.", [12, 13]),
        (20, "Evaluate the drivers of Thar desertification and propose a process-matched restoration strategy.", "Natural susceptibility becomes degradation when pressures exceed recovery; responses must target cover, soil, water, salinity and institutions.", [10, 11, 16, 17]),
        (20, "Justify the proposition that desertification does not have simple climatic boundaries while retaining UNCCD precision.", "Use broad degradation mechanisms across climates, then explicitly preserve the Convention's dryland definition.", [0, 14, 15, 19]),
    ],
    [
        plan("Desert, aridity, drought and degradation", [0], "These terms are related but non-equivalent.", "Open the 2020 route with a definition firewall."),
        plan("Why deserts form", [1], "High temperature alone does not define desert genesis.", "Classify deserts by atmospheric and locational control."),
        plan("Weathering and sediment supply", [2], "Arid weathering includes thermal, salt and episodic moisture effects.", "Connect material production to later transport."),
        plan("Creep, saltation and suspension", [3], "Transport mode depends on particle size and wind threshold.", "Use process vocabulary for elimination."),
        plan("Wind erosion and residual landforms", [4], "Many forms also require structural or weathering controls.", "Avoid wind-only explanations."),
        plan("Dune types and wind regimes", [5], "Barchan horns point downwind.", "Read dune shape as process evidence."),
        plan("Wadis, fans, pediments and playas", [6], "Deserts are not geomorphically waterless.", "Integrate episodic runoff and evaporation."),
        plan("Thar regional mosaic", [7, 8], "A schematic region is not a legal boundary.", "Draw dunes, Aravalli, Luni, playas and canal tract."),
        plan("Thar origin and susceptibility", [9, 10], "Origin and present degradation are different questions.", "Give a polygenetic, multi-timescale account."),
        plan("Human acceleration and thresholds", [11], "Presence of people is not itself degradation.", "Link pressure to loss of recovery capacity."),
        plan("Aravalli ecological functions", [12], "Do not use the simplistic wall metaphor.", "Explain relief, drainage and connectivity."),
        plan("Indira Gandhi Canal trade-offs", [13], "Benefits and salinity-waterlogging risks can coexist.", "Use a balanced irrigation transformation case."),
        plan("PYQ boundary and LDN", [14, 15], "Broad wording does not erase formal dryland usage.", "Reconcile exam demand with UNCCD precision."),
        plan("Restoration and monitoring", [16, 17], "A map is a baseline, not causal proof.", "Match intervention and indicator to process."),
        plan("PYQ ownership and current boundary", [18, 19], "Do not claim a cross-owned demand as a direct Geography PYQ.", "Close with definition, diagnosis, response and caveat."),
    ],
    [
        panel("Concept firewall", "comparison-table", ["DESERT -> climatic region", "ARIDITY -> long-term moisture deficit", "DROUGHT -> temporary anomaly", "DESERTIFICATION -> degradation within drylands"], ["Desert, aridity, drought and degradation"]),
        panel("Desert-forming controls", "causal-system", ["SUBTROPICAL HIGH -> descending dry air", "CONTINENTALITY / RAIN SHADOW -> moisture loss", "COLD CURRENT -> stable dry coastal air", "POLAR COLD -> low absolute moisture"], ["Why deserts form"]),
        panel("Aeolian transport", "process-flow", ["CREEP -> coarse grains roll or slide", "SALTATION -> sand grains bounce", "SUSPENSION -> fine dust travels far", "DEPOSITION -> velocity or carrying power falls"], ["Creep, saltation and suspension"]),
        panel("Dune discriminator", "comparison-table", ["BARCHAN -> limited sand, horns downwind", "TRANSVERSE -> abundant sand, one dominant wind", "LONGITUDINAL -> aligned with resultant winds", "PARABOLIC / STAR -> vegetation anchor / multidirectional winds"], ["Dune types and wind regimes"]),
        panel("Water in the desert", "process-flow", ["STORM RUNOFF -> wadi discharge", "MOUNTAIN FRONT -> alluvial fan", "FANS COALESCE -> bajada", "CLOSED BASIN -> playa and salt concentration"], ["Wadis, fans, pediments and playas"]),
        panel("Thar spatial anatomy", "spatial-map", ["WEST -> sandy Marusthali core", "EAST -> Bagar and Aravalli transition", "SOUTHWEST -> Luni and saline-basin route", "NORTH -> canal-alluvial transformation"], ["Thar regional mosaic"]),
        panel("Susceptibility-to-degradation", "causal-system", ["VARIABLE RAIN + WIND -> natural stress", "COVER LOSS + SOIL DISTURBANCE -> exposure", "WATER MISMANAGEMENT -> salinity or depletion", "THRESHOLD CROSSED -> recovery capacity declines"], ["Human acceleration and thresholds"]),
        panel("Aravalli boundary", "evidence-table", ["RELIEF -> modifies local wind and runoff", "DRAINAGE -> divides and routes water", "HABITAT -> supports connectivity", "LIMIT -> not an impermeable desert wall"], ["Aravalli ecological functions"]),
        panel("Canal balance", "comparison-table", ["BENEFIT -> water supply and production", "SEEPAGE -> water-table rise", "POOR DRAINAGE -> waterlogging and salinity", "MANAGEMENT -> crop-water fit + drainage + monitoring"], ["Indira Gandhi Canal trade-offs"]),
        panel("LDN response hierarchy", "ladder", ["AVOID -> protect functioning land", "REDUCE -> improve grazing, tillage and water use", "REVERSE -> restore soil, grass and drainage", "BALANCE -> monitor gains and losses transparently"], ["PYQ boundary and LDN"]),
        panel("Restoration matrix", "decision-tree", ["WIND EROSION -> cover, shelter and dune management", "RUNOFF EROSION -> contour and watershed treatment", "SALINITY -> drainage and water balance", "RANGELAND DECLINE -> native grass + institutions"], ["Restoration and monitoring"]),
        panel("Desertification answer spine", "answer-spine", ["DEFINE -> retain UNCCD dryland boundary", "MAP -> locate process and pressure", "DIAGNOSE -> susceptibility plus accelerator", "RESPOND -> process-matched, monitored and qualified"], ["PYQ ownership and current boundary"]),
    ],
    ["surface creep", "saltation", "suspension", "barchan", "yardang", "inselberg", "wadi", "playa", "Thar", "Aravalli", "Indira Gandhi Canal", "desertification", "Land Degradation Neutrality"],
    "TRANSPARENT ZERO-DIRECT-PYQ AUDIT: the central Mains ledger routes the 2020 desertification demand to Environment and Ecology, and no direct Topic 07 objective route appears in the checked central ledgers. Cross-owned questions remain conceptual context, not claimed Geography PYQs.",
    [],
    [
        "https://vedas.sac.gov.in/vedas/dsm_atlas.html",
        "https://www.sac.gov.in/data/Publication/128/Desertification_and_Land_Degradation_Atlas_of_India_2021.pdf",
        "https://pib.gov.in/PressReleseDetailm.aspx?PRID=1727987",
        "https://moef.gov.in/uploads/2023/07/NAP%20final-2023.pdf",
        "https://www.unccd.int/land-and-life/land-degradation-neutrality/overview",
    ],
    "Rechecked 2026-09-05: SAC's 2021 atlas supplies the 2018-19 national baseline of 97.85 million hectares or 29.77 percent. MoEFCC's 2023 NAP records the 26-million-hectare restoration ambition for 2030, and UNCCD supplies the avoid-reduce-reverse LDN framework. No baseline value is presented as a current Thar percentage or achieved target.",
    extra=["basic/18_Hot-and-MidLatitude-Desert-Climate.md", "advanced/18_Thar-Desert-and-GIB.md"],
)


TOPIC_08 = common.topic(
    8,
    "Limestone and Karst Landforms / India Caves-Meghalayan Age",
    "08_Limestone-and-Karst-Landforms.md",
    "08_India-Caves-Meghalayan-Age.md",
    "08_India-Caves-Meghalayan-Age_Complete-Topic-Package.md",
    [
        ("Karst system definition", "Karst is soluble-rock terrain organised by dissolution and underground drainage; a cave is a natural void, while cavern usually describes a large chamber rather than a separate universal origin."),
        ("Carbonation chemistry", "Soil carbon dioxide dissolved in water forms weak carbonic acid that converts calcium carbonate to dissolved calcium and bicarbonate; degassing can reverse the balance and precipitate calcite."),
        ("Karst prerequisites", "Effective karstification requires soluble and sufficiently thick rock, joints or bedding pathways, recharge, hydraulic gradient, outlet or base-level relation and adequate time."),
        ("Epikarst-vadose-phreatic zones", "Epikarst stores and routes recharge near the surface, vadose water descends through air-filled openings, and phreatic passages develop below the water table under saturated flow."),
        ("Surface karst suite", "Karren or lapies, dolines, uvalas, poljes, swallow holes, disappearing streams and blind valleys express solution, collapse, structural guidance and underground diversion at different scales."),
        ("Cave-development sequence", "Passages may begin along structural openings, enlarge under phreatic flow, incise under vadose flow after base-level change and later undergo collapse, sediment fill or renewed dissolution."),
        ("Speleothem suite", "Stalactites hang, stalagmites rise, columns join them, while curtains, flowstone, rimstone and cave pearls are secondary mineral deposits rather than excavated voids."),
        ("Monsoon karst hazard", "Rapid recharge through conduits can produce flash flooding, contamination transfer and unstable access; high rainfall promotes solution only where rock, structure and drainage permit."),
        ("India cave geography", "Meghalaya's limestone caves, Borra in Andhra Pradesh and Belum in Andhra Pradesh are natural cave examples; survey length or rank claims must carry a dated authoritative source."),
        ("Natural-rock-cut firewall", "Ajanta and Ellora are human-excavated rock-cut architecture, not karst solution caves; natural cave genesis and cultural use are separate analytical categories."),
        ("Speleothem proxy chain", "A cave proxy links climate to rainfall and vegetation, recharge routing, drip-water chemistry, calcite deposition, isotope or trace-element measurement and an independently constrained chronology."),
        ("Geological-time hierarchy", "The hierarchy runs eon, era, period, epoch and age; the Holocene is an Epoch and the Meghalayan is its uppermost formal Age or Stage."),
        ("GSSP method", "A Global Boundary Stratotype Section and Point is the physical reference defining a unit's lower boundary; the correlation signal and the named time interval are related but not identical."),
        ("Meghalayan boundary", "The Meghalayan GSSP is in the KM-A speleothem from Mawmluh Cave, Meghalaya, and the official Quaternary page identifies it as the Upper or Late Holocene Stage or Age reference."),
        ("4.2 ka caution", "The 4.2 ka hydroclimatic event guides correlation, but spatially variable climate evidence does not prove one uniform global drought or one-cause collapse of ancient societies."),
        ("Anthropocene status", "The formal chart retains Holocene and Meghalayan; Anthropocene remains an informal term rather than a ratified Epoch after rejection of the formal proposal."),
        ("Cave values", "Karst stores and transmits groundwater, supports specialised biodiversity, preserves palaeoclimate and archaeological archives and sustains cultural and tourism values."),
        ("Threat-response chain", "Quarrying, pollution, altered recharge, waste, infrastructure and unmanaged visitation can damage a connected catchment-aquifer-cave system; conservation must extend beyond the entrance."),
        ("Verified PYQ boundary", "The checked central ledgers route Ajanta to Indian Art and Culture and contain no direct Geography Topic 08 demand; cave-shrine and limestone questions in the legacy package are retained only as cross-owner context."),
        ("Current official anchor", "The ICS June 2026 chart retains the Meghalayan. The official Quaternary page places its GSSP at 7.45 mm depth in Mawmluh Cave's KM-A speleothem, ratified 14 June 2018 and modelled at 4.200 ± 0.030 ka before 1950 (= 4.250 ± 0.030 ka b2k)."),
    ],
    [
        "Do not call every cave a limestone solution cave.",
        "Do not describe neutral rainwater alone as sufficient for mature karst.",
        "Do not confuse a doline with every large closed depression.",
        "Do not treat stalactites and stalagmites as erosional forms.",
        "Do not assume heavy monsoon rain guarantees karst without soluble rock and pathways.",
        "Do not confuse natural caves with rock-cut monuments.",
        "Do not infer present cave condition from an old tourism or survey description.",
        "Do not treat one speleothem signal as a direct rain gauge.",
        "Do not call the Meghalayan an Epoch.",
        "Do not confuse the GSSP point, correlation signal and named interval.",
        "Do not say the Anthropocene formally replaced the Meghalayan.",
        "Do not invent cave rankings, lengths, geological dates, mining approvals or damage outcomes.",
    ],
    [
        (10, "Explain how carbonation and groundwater routing create a karst landscape.", "Chemistry supplies dissolution while structure, recharge, gradient, base level and time organise surface and underground forms.", [0, 1, 2, 3, 4]),
        (10, "Differentiate natural caves, speleothems and rock-cut cave architecture.", "Natural void, secondary mineral deposit and human excavation are separate genetic categories.", [6, 8, 9]),
        (15, "Explain the stages of cave development and the role of changing base level.", "Structural inception, phreatic enlargement, vadose incision and later modification can overlap as hydrology shifts.", [3, 5, 7]),
        (15, "Assess how speleothems are used as palaeoclimate archives and identify their limitations.", "Proxy interpretation requires a climate-recharge-cave-calcite-measurement-age chain, with site-specific uncertainty at every link.", [10, 14]),
        (20, "Explain the formal basis of the Meghalayan Age and critically assess civilisation-collapse narratives around 4.2 ka.", "Separate hierarchy, GSSP point, correlation signal and interval, then qualify spatially uneven climate and societal causation.", [11, 12, 13, 14, 15, 19]),
        (20, "Design a conservation framework for India's karst and cave systems.", "Protect recharge and groundwater, map passages and biodiversity, regulate extraction and visitation, monitor change and keep natural and cultural-cave governance distinct.", [16, 17, 18]),
    ],
    [
        plan("Karst, cave and cavern", [0], "A cave is a feature; karst is a landscape-hydrology system.", "Start with coupled surface-subsurface drainage."),
        plan("Carbonation and calcite reversal", [1], "Dissolution and deposition are opposite directions of one carbonate system.", "Derive voids and speleothems from chemistry."),
        plan("Rock, structure, recharge and base level", [2], "Rainfall alone cannot produce mature karst.", "List the necessary controls."),
        plan("Epikarst, vadose and phreatic zones", [3], "Water-table position and passage form change through time.", "Use a vertical hydrological cross-section."),
        plan("Surface karst landforms", [4], "Closed depressions differ by process and scale.", "Diagnose karren, doline, uvala and polje."),
        plan("Cave development and modification", [5], "Cave stages can repeat after base-level change.", "Explain inception, enlargement, incision and collapse."),
        plan("Speleothems and deposition", [6], "Speleothems are deposits, not the cave void.", "Match shape to drip, film or pool process."),
        plan("Monsoon recharge and cave hazard", [7], "Fast conduit flow increases both recharge efficiency and vulnerability.", "Link flood and contamination pathways."),
        plan("Indian natural-cave map", [8], "Rank and length claims are volatile survey statements.", "Use location and cave type safely."),
        plan("Natural versus rock-cut caves", [9], "Ajanta and Ellora are architecture despite the word cave.", "Prepare objective elimination."),
        plan("Speleothems as climate proxies", [10], "Proxy signal is filtered by catchment and cave processes.", "Build a method-and-limit answer."),
        plan("Time hierarchy and GSSP", [11, 12], "Age, Epoch, point and signal are not interchangeable.", "Establish formal stratigraphic vocabulary."),
        plan("Mawmluh and the Meghalayan", [13, 19], "The locality defines a global unit, not an India-only label.", "Use the directly fetched official anchor."),
        plan("4.2 ka and Anthropocene cautions", [14, 15], "Neither uniform drought nor formal Anthropocene status should be assumed.", "Add scientific and status qualifications."),
        plan("Values, threats, PYQ boundary and conservation", [16, 17, 18], "No direct Mains route should be fabricated.", "Close with a catchment-to-cave conservation spine."),
    ],
    [
        panel("Karst coupled system", "root-axes", ["RECHARGE -> joints, bedding and sink points", "DISSOLUTION -> openings enlarge underground", "CONDUITS -> springs export water and solute", "SURFACE + CAVE -> one hydrological landscape"], ["Karst, cave and cavern"]),
        panel("Carbonate cycle", "process-flow", ["CO2 + WATER -> weak carbonic acid", "ACID + CaCO3 -> dissolved bicarbonate", "TRANSPORT -> solution moves through conduits", "DEGASSING -> calcite can precipitate"], ["Carbonation and calcite reversal"]),
        panel("Karst prerequisites", "decision-tree", ["ROCK -> soluble, thick and exposed to recharge", "STRUCTURE -> joints and bedding pathways", "FLOW -> gradient plus outlet / base level", "TIME -> sustained dissolution and removal"], ["Rock, structure, recharge and base level"]),
        panel("Hydrological zones", "spatial-map", ["EPKARST -> shallow storage and routing", "VADOSE -> descending water in air-filled voids", "WATER TABLE -> fluctuating boundary", "PHREATIC -> saturated tubes and loops"], ["Epikarst, vadose and phreatic zones"]),
        panel("Surface-karst ladder", "hierarchy", ["KARREN -> small solution grooves", "DOLINE -> closed depression", "UVALA / POLJE -> larger composite / structural basin", "SWALLOW HOLE -> surface stream transfers underground"], ["Surface karst landforms"]),
        panel("Cave-development sequence", "timeline", ["INCEPTION -> favourable fracture or bedding plane", "PHREATIC -> passage enlarges under saturation", "VADOSE -> stream incises after water-table fall", "LATE CHANGE -> collapse, fill or renewed solution"], ["Cave development and modification"]),
        panel("Speleothem map", "comparison-table", ["STALACTITE -> roof drip deposit", "STALAGMITE -> floor splash / drip deposit", "COLUMN -> roof and floor forms join", "FLOWSTONE / CURTAIN -> film flow on wall or slope"], ["Speleothems and deposition"]),
        panel("India cave firewall", "comparison-table", ["MAWMLUH / MAWSMAI / SIJU -> Meghalaya limestone", "BORRA / BELUM -> natural caves in Andhra Pradesh", "AJANTA / ELLORA -> human rock-cut architecture", "RULE -> location does not replace genetic classification"], ["Indian natural-cave map", "Natural versus rock-cut caves"]),
        panel("Proxy pipeline", "causal-system", ["CLIMATE -> rainfall, vegetation and soil CO2", "RECHARGE -> route and residence time", "CALCITE -> isotope / element signal", "CHRONOLOGY -> dated series with uncertainty"], ["Speleothems as climate proxies"]),
        panel("Meghalayan hierarchy", "hierarchy", ["QUATERNARY -> Period", "HOLOCENE -> Epoch", "MEGHALAYAN -> Age / Stage", "GSSP -> KM-A speleothem at Mawmluh"], ["Time hierarchy and GSSP", "Mawmluh and the Meghalayan"]),
        panel("Status and narrative caution", "comparison-table", ["4.2 ka EVENT -> correlation guide", "GSSP POINT -> physical lower boundary", "MEGHALAYAN -> named formal interval", "ANTHROPOCENE -> not a ratified Epoch"], ["4.2 ka and Anthropocene cautions"]),
        panel("Karst conservation spine", "answer-spine", ["MAP -> recharge, passages, springs and values", "AVOID -> irreversible quarry and pollution pathways", "MANAGE -> visitation, waste and water use", "MONITOR -> hydrology, biodiversity and structural change"], ["Values, threats, PYQ boundary and conservation"]),
    ],
    ["carbonation", "epikarst", "vadose", "phreatic", "doline", "uvala", "polje", "stalactite", "stalagmite", "speleothem", "Mawmluh", "KM-A", "Meghalayan", "GSSP", "Anthropocene"],
    "TRANSPARENT ZERO-DIRECT-PYQ AUDIT: no direct Geography Topic 08 route was found in the checked central ledgers. Ajanta is routed to Indian Art and Culture; other adjacent legacy-package questions are not promoted into direct PYQ cards.",
    [],
    [
        "https://stratigraphy.org/ICSchart/ChronostratChart2026-06.pdf",
        "https://quaternary.stratigraphy.org/major-divisions",
        "https://www.iugs.org/the-anthropocene-iugs-ics-statement/",
        "https://www.iugs.org/wp-content/uploads/2024/03/Anthropocene_short_IUGS-ICS_Statement-1.pdf",
    ],
    "Rechecked 2026-09-05: the ICS June 2026 chart and official Quaternary page retain the Holocene-Meghalayan hierarchy, KM-A GSSP, 14 June 2018 ratification and 4.200 ± 0.030 ka before-1950 age. IUGS-ICS still treats Anthropocene as informal after the March 2024 decision. No cave-length record, cave-wide age or civilisation-collapse claim is inferred.",
    extra=["basic/04_Weathering-MassMovement-Groundwater.md"],
)


TOPIC_09 = common.topic(
    9,
    "Lakes / India Lakes and Wetlands",
    "09_Lakes.md",
    "09_India-Lakes-and-Wetlands.md",
    "09_India-Lakes-and-Wetlands_Complete-Topic-Package.md",
    [
        ("Lake-wetland boundary", "A lake is standing water in an inland basin, while wetland is a broader hydro-ecological category including marshes, floodplains, peatlands, mangroves and shallow coastal waters."),
        ("Genetic classification", "Lake origin can be tectonic, glacial, volcanic, fluvial, coastal, solutional, impact, aeolian, landslide-dammed or artificial; mixed controls require qualification."),
        ("Water-budget equation", "Lake storage changes with precipitation, inflow and groundwater inputs minus evaporation, outflow and seepage; level change cannot be assigned to one driver without a budget."),
        ("Residence and mixing", "Depth, area, residence time, temperature, wind and inflow density influence stratification and turnover; tropical and shallow lakes need not follow a simple temperate seasonal model."),
        ("Oligotrophic-eutrophic states", "Oligotrophic lakes are relatively nutrient-poor and clear, while eutrophic systems are nutrient-rich and productive; trophic state is condition, not basin origin or legal status."),
        ("Eutrophication chain", "Nutrient loading can drive algal growth, reduced light, decomposition and oxygen depletion; internal loading, flushing and food-web responses complicate recovery."),
        ("Natural lake succession", "Sediment and organic accumulation can gradually make lakes shallower and convert open water to marsh or terrestrial habitat; this differs from rapid water-budget collapse."),
        ("Human-induced shrinkage", "Diversion, damming, groundwater extraction, catchment change and warming-driven evaporation can shrink lakes; Aral Sea and Lake Chad illustrate different combinations and trajectories."),
        ("Wetland functions", "Wetlands store and slow water, trap sediment and nutrients, support biodiversity and livelihoods and sometimes recharge or discharge groundwater; every function is site and connectivity dependent."),
        ("Hydroperiod and connectivity", "Duration, depth, timing and frequency of inundation plus river, groundwater and coastal connections control ecological character more precisely than the label wetland alone."),
        ("Indian origin examples", "Wular is tectonic-influenced, Lonar impact-origin, Kanwar or Kabar Tal fluvial-floodplain, Chilika lagoonal, Sambhar saline inland and Bhoj an artificial reservoir system."),
        ("River-lake map hooks", "Wular is linked to the Jhelum, Kolleru lies between the Krishna and Godavari delta systems but is not directly fed by the Krishna, and Loktak's phumdis are distinctive floating biomass-soil masses."),
        ("Urban reclamation impacts", "Filling or constricting water bodies removes storage and drainage space, fragments habitat, worsens flood peaks and water quality and can shift risk toward poorer low-lying communities."),
        ("Threat-pathway diagnosis", "Catchment sewage, nutrients, sediment, encroachment, invasive species, altered inflow, extraction and shoreline hardening act through different mechanisms and require different remedies."),
        ("Restoration hierarchy", "Protect catchment and inflow, stop pollution and encroachment, restore hydrological connectivity, manage sediment and invasives, then monitor ecological response rather than beautification alone."),
        ("Ramsar wise use", "Ramsar designation recognises international importance and wise-use obligations; it does not automatically create a National Park, prohibit all human use or prove ecological health."),
        ("Montreux and criteria", "A site can qualify by meeting at least one Ramsar criterion; the Montreux Record highlights listed sites where ecological character has changed, is changing or is likely to change."),
        ("Indian governance", "Wetlands Rules 2017 establish State or Union Territory Wetland Authorities and a notification-regulation framework; NPCA and other programmes are separate implementation instruments."),
        ("Verified PYQ routes", "Direct Geography routes cover human-caused lake shrinkage, artificial lakes, reservoir names, saline Rajasthan lakes, river-lake matching and the provisional Lake Turkana demand; wetland-governance Mains questions are cross-owned."),
        ("Current evidence boundary", "Ramsar Convention and PIB announcements record Glaw Lake, Arunachal Pradesh, as India's 101st Ramsar site on 3 August 2026. MoEFCC's list dated 21 April 2026 records 99, so designation counts must always retain their as-of date."),
    ],
    [
        "Do not treat all wetlands as lakes.",
        "Do not confuse lake origin, trophic condition and Ramsar status.",
        "Do not infer cause from lake-level change without a water budget.",
        "Do not apply a single dimictic mixing model to every tropical or shallow lake.",
        "Do not assume all eutrophication is irreversible or caused by one nutrient source.",
        "Do not confuse gradual infilling with rapid diversion-driven shrinkage.",
        "Do not claim every wetland recharges groundwater.",
        "Do not say Kolleru is directly fed by the Krishna merely because it lies between two deltas.",
        "Do not treat Ramsar designation as proof of ecological health.",
        "Do not confuse the Montreux Record with a heritage list or funding scheme.",
        "Do not treat notification, project funding and measured restoration outcome as the same status.",
        "Do not invent current Ramsar counts, site status, lake area trends or restoration outcomes.",
    ],
    [
        (10, "Classify lakes by origin and explain why mixed-origin qualifications matter.", "Genetic classification identifies the basin-forming process, but later hydrology and human modification can overprint the original form.", [0, 1, 10]),
        (10, "Explain lake-level change through a water-budget framework.", "Storage responds to multiple inflows and losses, so attribution requires scale, period and connectivity rather than one visible driver.", [2, 3, 7]),
        (15, "Differentiate natural lake succession from eutrophication and rapid human-induced shrinkage.", "The three pathways differ in mechanism, tempo, indicators and remedy despite sometimes sharing a smaller open-water area.", [4, 5, 6, 7]),
        (15, "Explain the environmental implications of reclaiming urban water bodies.", "Reclamation removes hydrological storage and connectivity while concentrating flood, pollution, heat and equity burdens.", [9, 12, 13]),
        (20, "Assess India's wetland conservation architecture from Ramsar designation to site restoration.", "International recognition, domestic regulation, programme finance, local implementation and measured ecological outcomes are distinct governance stages.", [14, 15, 16, 17, 19]),
        (20, "Design a basin-to-wetland restoration and monitoring strategy for a degraded Indian lake.", "Diagnose catchment, hydrology, nutrients, sediment, biodiversity and use, then sequence source control, reconnection, adaptive management and transparent indicators.", [8, 9, 13, 14, 17]),
    ],
    [
        plan("Lake, pond, reservoir and wetland", [0], "Every lake may have wetland functions, but the categories are not identical.", "Build a definition-first answer."),
        plan("How lake basins form", [1], "Mixed origin and later modification are common.", "Classify by dominant genetic process."),
        plan("Lake water budget", [2], "A level trend needs a stated period and complete inputs and outputs.", "Use storage accounting before attribution."),
        plan("Stratification, turnover and residence", [3], "Temperate textbook cycles are not universal.", "Link physical limnology to oxygen and nutrients."),
        plan("Trophic states and eutrophication", [4, 5], "Trophic state is neither lake origin nor conservation status.", "Explain nutrient-to-oxygen causation."),
        plan("Two modes of lake loss", [6, 7], "Slow succession and rapid shrinkage need different evidence.", "Compare infilling with water-budget failure."),
        plan("Wetland functions and limits", [8], "Function depends on hydroperiod, soils, connectivity and condition.", "Avoid universal service claims."),
        plan("Hydroperiod and connectivity", [9], "Area alone can miss ecological change.", "Use timing, depth, duration and connection."),
        plan("Indian lake-origin map", [10], "Named examples must match both place and genesis.", "Prepare map-based prelims elimination."),
        plan("River-lake and phumdi hooks", [11], "Between two deltas does not mean direct river feeding.", "Retain exact Indian spatial relations."),
        plan("Urban reclamation", [12], "A water body is drainage infrastructure and habitat, not vacant land.", "Prepare the 2021 GS-I route."),
        plan("Threat diagnosis and restoration", [13, 14], "Beautification without source control is not ecological restoration.", "Match mechanism, intervention and indicator."),
        plan("Ramsar wise use and Montreux", [15, 16], "Designation does not equal domestic protected-area status or health.", "Separate international recognition from condition."),
        plan("Wetlands Rules and programmes", [17, 19], "Law, finance, implementation and outcome are separate statuses.", "Build an Indian governance chain."),
        plan("Verified routes and final wetland spine", [18, 19], "Do not invent dynamic site counts or objective keys.", "Close with origin, budget, function, governance and qualification."),
    ],
    [
        panel("Category boundary", "comparison-table", ["LAKE -> standing water in an inland basin", "RESERVOIR -> artificial or strongly regulated storage", "WETLAND -> broader hydrological-ecological category", "RAMSAR SITE -> international designation, not basin origin"], ["Lake, pond, reservoir and wetland"]),
        panel("Lake-origin tree", "hierarchy", ["EARTH MOVEMENT -> tectonic or volcanic basin", "ICE / RIVER / COAST -> tarn, ox-bow or lagoon", "BLOCKAGE / IMPACT -> landslide dam or crater", "HUMAN WORK -> reservoir, bund or excavation"], ["How lake basins form"]),
        panel("Water-budget equation", "causal-system", ["INPUT -> rain + river + groundwater", "OUTPUT -> evaporation + outflow + seepage", "STORAGE CHANGE -> inputs minus outputs", "ATTRIBUTION -> state period, basin and uncertainty"], ["Lake water budget"]),
        panel("Lake-change firewall", "comparison-table", ["SUCCESSION -> sediment and organic infilling", "EUTROPHICATION -> nutrient-productivity-oxygen shift", "SHRINKAGE -> water-budget deficit", "RULE -> similar appearance can hide different mechanisms"], ["Trophic states and eutrophication", "Two modes of lake loss"]),
        panel("Wetland hydroperiod", "process-flow", ["TIMING -> season of inundation", "DURATION -> how long water remains", "DEPTH + FREQUENCY -> habitat filter", "CONNECTIVITY -> river, aquifer or coast link"], ["Hydroperiod and connectivity"]),
        panel("India lake map", "spatial-map", ["WULAR -> Jhelum-linked Kashmir basin", "SAMBHAR -> saline Rajasthan closed basin", "CHILIKA -> Odisha coastal lagoon", "LONAR / KANWAR / BHOJ -> impact / fluvial / artificial"], ["Indian lake-origin map"]),
        panel("River-lake traps", "comparison-table", ["WULAR -> linked to Jhelum", "KOLLERU -> between Krishna and Godavari deltas", "LOKTAK -> phumdi-bearing lake", "RULE -> adjacency does not prove direct feeding"], ["River-lake and phumdi hooks"]),
        panel("Urban reclamation chain", "causal-system", ["FILL / NARROW -> storage and drainage lost", "RUNOFF -> flood peak and duration rise", "POLLUTION -> dilution and habitat decline", "EQUITY -> low-lying communities bear shifted risk"], ["Urban reclamation"]),
        panel("Threat-response matrix", "decision-tree", ["SEWAGE / NUTRIENT -> source control + treatment", "SEDIMENT -> catchment and erosion management", "ENCROACHMENT -> protect hydrological space", "INVASIVE / ALTERED FLOW -> ecological and flow restoration"], ["Threat diagnosis and restoration"]),
        panel("Ramsar status firewall", "comparison-table", ["CRITERION -> at least one can support listing", "WISE USE -> maintain ecological character", "MONTREUX -> priority attention to character change", "LIMIT -> listing is not automatic National Park status"], ["Ramsar wise use and Montreux"]),
        panel("India governance chain", "ladder", ["INVENTORY -> identify and delineate system", "NOTIFICATION / RULES -> regulate activities", "PLAN / NPCA -> finance and implement management", "MONITOR -> prove ecological response"], ["Wetlands Rules and programmes"]),
        panel("Lake-wetland answer spine", "answer-spine", ["DEFINE -> basin, wetland and status", "CLASSIFY -> origin and hydrology", "DIAGNOSE -> budget, nutrient or connectivity failure", "RESPOND -> basin-scale, monitored and status-aware"], ["Verified routes and final wetland spine"]),
    ],
    ["water budget", "residence time", "oligotrophic", "eutrophic", "hydroperiod", "Wular", "Kolleru", "Loktak", "phumdi", "Chilika", "Sambhar", "Ramsar", "wise use", "Montreux Record", "Wetlands Rules 2017", "NPCA"],
    "Verified routing retains direct Geography objective routes from 2018, 2019, 2021 and 2023 plus a provisional 2026 Lake Turkana route. The 2021 urban-water-body Mains demand is routed to Environment and Ecology and is not claimed as a direct Geography PYQ.",
    [
        ("2018", "Prelims GS-I", "Human-induced shrinkage of major world lakes and identification of an artificial Indian lake.", "Verified routed objective demands; official keys unavailable locally.", "Separate diversion-driven Aral shrinkage from unrelated water bodies, and classify Kodaikanal as artificial while preserving official options and unverified-key status."),
        ("2019", "Prelims GS-I", "Common feature of Aliyar, Isapur and Kangsabati.", "Verified routed objective demand; official key unavailable locally.", "They are reservoir or project water bodies. The route tests artificial storage rather than natural lake genesis; do not manufacture an official answer letter."),
        ("2021", "Prelims GS-I", "Saline lakes of Rajasthan.", "Verified routed objective demand; official key unavailable locally.", "Use Didwana, Kuchaman, Sargol and Khatu as arid closed-drainage saline-lake cues while keeping the official options unchanged."),
        ("2023", "Prelims GS-I", "Indian rivers feeding or associated with Wular, Kolleru and Kanwar lakes.", "Verified routed objective demand; official key unavailable locally.", "Wular is Jhelum-linked; Kolleru lies between the Krishna and Godavari delta systems but is not directly Krishna-fed; Kanwar or Kabar Tal is a floodplain wetland."),
        ("2026", "Prelims GS-I", "Lake Turkana geography, desert-lake status and UNESCO heritage.", "Provisional routed demand; no answer letter recorded or inferred.", "Use only the neutral routing theme until the provisional key and official status evidence are independently verified; do not solve by memory."),
    ],
    [
        "https://indianwetlands.in/",
        "https://www.ramsar.org/news/india-designates-glaw-lake-wetland-international-importance",
        "https://pib.gov.in/PressReleasePage.aspx?PRID=2294036&reg=48&lang=1",
        "https://www.ramsar.org/news/thats-century-india-names-its-100th-wetland-international-importance",
        "https://moef.gov.in/ramsar-convention",
        "https://moef.gov.in/uploads/pdf-uploads/pdf_698ae4f8f28953.18411376.pdf",
        "https://moef.gov.in/regulatory-framework-wetlands-rules",
    ],
    "Rechecked 2026-09-05: Ramsar and PIB identify Glaw Lake as India's 101st Ramsar site from 3 August 2026; the MoEFCC list dated 21 April 2026 records the earlier tally of 99. The package separates international designation, Wetlands Rules 2017 regulation, site management and measured ecological condition.",
    extra=["basic/05_Landforms-by-Running-Water.md", "basic/08_Limestone-and-Karst-Landforms.md", "basic/10_Coastal-Landforms.md"],
)


TOPICS = [TOPIC_05, TOPIC_06, TOPIC_07, TOPIC_08, TOPIC_09]
