"""Authored content data for Governance learner-v2 Topics 15-16."""

from __future__ import annotations

import generate_governance_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_15 = common.topic(
    15,
    "Monitoring, Evaluation and Outcomes",
    "15_Monitoring-Evaluation-and-Outcomes",
    "15_Monitoring-Evaluation-and-Outcomes_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and why it is built for transfer", "This topic owns the evidence layer of governance, namely how a claim that a scheme worked is established or refuted, and its distinctive feature is that no direct General Studies Mains demand in the audited 2018 to 2025 ledgers is routed to it, so it appears as the evaluative half of demands about schemes, governance quality and expenditure; the architecture is therefore built for transfer to an unfamiliar programme rather than for a remembered question, and the measurement of governance quality by composite indices belongs to the good-governance owner while the policy cycle belongs to the policy-design owner."),
        ("Input, activity, output, outcome and impact", "An input is the money, staff and materials committed, an activity is what was done, an output is what the activity directly produced such as kilometres of road or schools constructed, an outcome is the change in the target population's condition such as reduced travel time or improved learning, and an impact is the longer-term and wider change such as market access, income or mobility; outputs are necessary evidence and are never sufficient evidence that the intended change occurred, and most Indian scheme reporting stops at the output rung."),
        ("The results chain as the spine of every evaluative answer", "The results chain is the ordered sequence from input through activity and output to outcome and impact, and it is the spine of any demand that asks for an evaluation or an assessment of impact because it locates where the available evidence actually sits, shows where reporting stops, and identifies the rung at which attribution becomes contested; building the chain before citing anything is what converts a descriptive answer into an evaluative one."),
        ("Classify the examiner's own statistic", "The move that earns marks is to name the rung on which a cited statistic sits, because a figure such as the share of households covered is an output while a figure such as water quality at the point of use is an outcome, so performing that classification on the examiner's own number demonstrates both the criteria and the evidence discipline at once and prevents an answer from treating coverage as proof of effect."),
        ("The Development Monitoring and Evaluation Office and its mandate", "The Development Monitoring and Evaluation Office is an attached office of NITI Aayog whose own website, read on 2 September 2026, states that it was constituted in September 2015 by merging the erstwhile Program Evaluation Office and the Independent Evaluation Office, that it is mandated to actively monitor and evaluate the implementation of schemes, programmes and initiatives of the Government of India in order to strengthen their implementation and scope of delivery on an ongoing basis, and that this requires tracking performance, determining outcomes, diagnosing reasons for poor performance and generating recommendations for course correction; it is an evaluator without authority to redesign, so its findings must be adopted by the line ministry to have effect."),
        ("The REESI plus coherence and equity criteria", "The office's evaluation criteria are relevance, effectiveness, efficiency, sustainability and impact together with coherence and equity, and they supply a ready frame for any demand that uses the word evaluate, because they prevent impact from being reduced to output completion and force distributional effects to be stated explicitly; the criteria are a frame rather than evidence, so they organise an answer and never substitute for the findings themselves."),
        ("The Output-Outcome Monitoring Framework and its coverage rule", "The Output-Outcome Monitoring Framework is an annual Union Budget document administered by the Ministry of Finance's Budget Division that requires covered major central-sector and centrally sponsored schemes to state financial outlay, outputs, outcomes, indicators and targets, so budget scrutiny extends beyond expenditure and physical counts, and its central limitation is that it does not cover every scheme in every year; the owners record for the 2026-27 document a coverage of one hundred and seventy-two major schemes at an outlay threshold of five hundred crore rupees or more as checked on 21 July 2026, and that figure must always be cited with its Budget year and never carried forward, because coverage is revised annually by design."),
        ("Outcome budgeting against output and input budgeting", "Input budgeting is traditional line-item budgeting that tracks how much money is allocated to a category, output budgeting tracks the physical units produced for that allocation, and outcome budgeting links the allocation to the change actually achieved, so the framework represents a deliberate shift from output-focused reporting toward outcome-focused accountability; its unfinished business is that outcome achievement carries no budgetary consequence and that outcome targets can themselves be set undemandingly, so the formal requirement outruns the practice."),
        ("The Aspirational Districts Programme and its dashboard architecture", "The Aspirational Districts Programme of NITI Aayog covers one hundred and twelve districts and tracks forty-nine key performance indicators across five themes, namely health and nutrition, education, agriculture and water resources, financial inclusion and skill development, and basic infrastructure, through the Champions of Change dashboard with a delta-ranking system, and its distinctive contribution is that monthly indicators closer to outcome measures are collected directly from district officers rather than waiting for a periodic evaluation report; the district unit necessarily masks divergence within a district."),
        ("Delta ranking against absolute ranking", "Absolute ranking compares units on their present level and therefore favours already-advantaged units, while delta ranking compares the rate of improvement over a defined period and therefore rewards effort regardless of the starting position, which is a deliberate incentive-design choice that prevents a historically disadvantaged district from being permanently placed at the bottom; the corresponding risk is that any improvement-based metric can be gamed through baseline understatement, so careful baseline-setting and independent validation are the conditions on which its credibility rests."),
        ("The Aspirational Blocks Programme as a separate exercise", "A related Aspirational Blocks Programme extends a similar logic to the sub-district level and is recorded in current NITI Aayog material as covering five hundred and thirteen blocks, and the analytical requirement is to keep the two programmes separate, because merging district and block unit counts or their indicator sets is the standard factual error in this area; the finer unit exists precisely because a district average can conceal a failing block."),
        ("Monitoring and evaluation are complementary and distinct", "Monitoring is the continuous, routine and typically self-reported tracking of implementation and immediate outputs, which supports rapid course correction, while evaluation is a periodic and often independent assessment of whether outcomes and impact were actually achieved, which supports scheme redesign, so neither substitutes for the other and conflating them leads either to over-reliance on self-reported dashboards or to under-use of the responsiveness that monitoring offers."),
        ("Self-reported data with a validation layer", "The district dashboard data is initially self-reported by district-level officers and then subject to validation by agencies selected by NITI Aayog, which is a two-stage design that balances the speed and frequency advantage of self-reporting against the reliability advantage of independent checking, although validation capacity and rigour can vary by sector and indicator; an implausibly large one-month jump in an indicator is exactly the case the validation layer exists to catch."),
        ("Attribution is the hard problem and the baseline is the precondition", "The difficult question in evaluation is not whether an indicator moved but whether it moved because of the intervention, which requires a counterfactual rather than a simple before-and-after comparison, and without a baseline measured before the intervention no method can produce a defensible outcome claim; the absence of baselines is a recurring and nameable weakness in Indian scheme design, and most current Indian evaluations approximate outcome assessment through before-and-after comparison rather than rigorous causal-inference designs."),
        ("What each evaluation method can and cannot establish", "A before-and-after comparison shows that the indicator moved but cannot separate the intervention from everything else that changed, a with-and-without comparison supplies a plausible counterfactual but the comparison group may differ systematically, a randomised controlled trial establishes a causal effect for the population and design studied but has limited external validity, faces ethical and practical limits on randomising an entitlement, measures the variant tested rather than the policy as generally implemented and cannot capture general-equilibrium or political effects, a quasi-experimental design supports causal inference where randomisation is impossible but depends on assumptions that must be stated and can fail, a process evaluation explains why an outcome did or did not occur without measuring the effect size, a mixed-method design captures effect together with mechanism and beneficiary experience at greater cost and only if genuinely integrated, and administrative-data analysis is continuous and cheap at scale but only as reliable as the incentive of whoever enters the data."),
        ("What makes an indicator usable", "A usable indicator is specific, measurable at a defined frequency, attributable to the intervention, independently verifiable, disaggregable by group and geography, and resistant to manipulation, and an evaluation that recommends better monitoring without specifying these properties has recommended nothing; disaggregation by gender, social group, disability and geography is an evaluation requirement rather than an optional extra, because an average conceals precisely the distributional failure an equity criterion is meant to expose."),
        ("The six indicator failure modes and their corrections", "The failure modes are Goodhart's problem, in which an indicator that carries a consequence stops measuring and starts being produced, corrected by a basket of indicators, rotation and independent sample audit, self-reported data, in which the entity judged by the number also generates it, corrected by third-party validation and an independent sample survey, aggregation masking, in which a district average conceals block-level and group-level failure, corrected by mandatory disaggregation, output substitution, in which effort shifts toward what is counted, corrected by including quality and outcome indicators rather than coverage alone, survivor and selection effects, in which only reachable beneficiaries are measured, corrected by measuring drop-off and exclusion explicitly, and definition drift, in which an indicator's definition changes between years, corrected by publishing definitions with the series and noting breaks."),
        ("Third-party evaluation and the conditions on its independence", "Third-party evaluation is assessment conducted by an entity independent of the implementing ministry or agency, and its purpose is to remove the conflict of interest inherent in an agency assessing its own performance, so it is not the same thing as internal departmental self-assessment; its independence is nevertheless conditional rather than automatic, because it depends on who commissions the study, who funds it and who is able to withhold the report from publication, and an evaluation that is not published cannot be contested, replicated or used, which makes publication itself an accountability mechanism."),
        ("Learning against accountability, and the other honest trade-offs", "Evaluation used punitively produces defensive reporting and suppresses the honest failure data that learning requires, so separating the learning use from the accountability use and protecting the first is a genuine institutional design problem; alongside it sit measurability bias, in which what is easy to count crowds out what matters so that enrolment displaces learning and toilets displace use, proportionality, since rigorous evaluation is expensive and slow so the large and the novel should be evaluated while the routine is monitored, the direct trade-off between the frequency of a dashboard and the reliability of its data, the tension between standardised indicators that permit national comparison and context-specific indicators that are locally useful, and the plain fact that an evaluation recommending discontinuation of a flagship programme rarely prevails against political commitment, which is realism rather than cynicism."),
        ("Incidence, the learning loop and honest question ownership", "The incidence of a monitoring system is uneven, because the district or block officer both generates the data and is ranked on it, which is the single strongest source of gaming pressure, the frontline worker carries the reporting burden on multiple parallel formats, which itself reduces service time, the line ministry owns the reputational stake in the finding, the evaluator produces evidence without authority to act on it, the Ministry of Finance uses the budget framework to connect allocation to expected results, the beneficiary alone experiences the outcome and is usually surveyed rather than consulted, and the legislature and its public accounts committee convert findings into consequence; the loop closes only where a management response with an accepted action, a responsible owner and a follow-up date is published. On ownership, no direct General Studies Mains demand and no objective demand in the audited 2018-2023, 2024-2025 or 2026 ledgers is routed to this topic, so no demand card is manufactured and no question is invented from the locally held official papers, and no district rank or indicator value, no evaluation finding, effect size or recommendation, no count of completed evaluations, no scheme-coverage percentage without its year and no study attribution is asserted anywhere in this package."),
    ],
    [
        "Do not treat an output as evidence of an outcome, because production is not the same as change in a person's condition.",
        "Do not treat monitoring and evaluation as interchangeable, because one is continuous and self-reported while the other is periodic and often independent.",
        "Do not describe the evaluation office as newly created from nothing, because it was constituted in September 2015 by merging two pre-existing bodies.",
        "Do not claim that the budget framework covers every scheme in every year, because coverage is revised with each Budget cycle.",
        "Do not carry a scheme-coverage or threshold figure forward across Budget years, because a stale figure is the most likely factual error in this topic.",
        "Do not merge the district programme's unit count or indicator set with the block programme's, because they are separate exercises.",
        "Do not state that the district programme ranks only on absolute level, because delta ranking rewards the pace of improvement.",
        "Do not present delta ranking as risk-free, because any improvement-based metric can be gamed through baseline understatement.",
        "Do not describe dashboard data as unchecked, because a validation layer by agencies selected by NITI Aayog exists, and do not describe that validation as uniformly rigorous either.",
        "Do not equate third-party evaluation with internal departmental self-assessment.",
        "Do not treat independence as automatic, because it depends on who commissions, funds and can withhold the report.",
        "Do not claim that Indian outcome budgeting has achieved rigorous causal attribution, because most current evaluations approximate it through before-and-after comparison.",
        "Do not offer a before-and-after movement as proof of effect without a counterfactual and a baseline.",
        "Do not assert any district's rank or indicator value, any evaluation's findings, effect size or recommendation, or the number of completed evaluations.",
        "Do not cite a coverage percentage without its year, and do not attribute any randomised study result.",
        "Do not recommend better monitoring without naming the indicator properties and the failure mode being corrected.",
    ],
    [
        (10, "Distinguish output indicators from outcome indicators in the evaluation of a government scheme, with an Indian example.", "The distinction is the difference between what was produced and what changed, so the answer must build the results chain, classify a concrete indicator on it and name one limitation of the evidence rather than listing institutions.", [1, 2, 3, 8]),
        (10, "Examine the design choice of ranking districts by the pace of improvement rather than by absolute level.", "Delta ranking solves a real demotivation problem created by absolute ranking and introduces a real baseline-gaming problem in its place, so the examination must state the incentive logic and the validation condition on which its credibility depends.", [9, 8, 12, 19]),
        (15, "Distinguish monitoring from evaluation as governance-information functions and assess India's architecture on that distinction.", "The two functions trade frequency against rigour and neither substitutes for the other, so the architecture must be assessed institution by institution with each body's distinct function, its data basis and the limitation that follows from it.", [11, 4, 6, 12]),
        (15, "Examine why attribution rather than measurement is the hard problem in evaluating a public programme.", "Movement in an indicator is easy to observe and hard to explain, so the answer must set out the counterfactual requirement, the baseline precondition and what each available method can and cannot establish before offering any verdict on a programme.", [13, 14, 2, 18]),
        (20, "Assess whether India's monitoring and evaluation architecture has shifted governance from counting outputs to accounting for outcomes.", "The formal requirement has shifted further than the practice, because dual reporting, an evaluation office and a real-time dashboard now exist while attribution, data incentives and budgetary consequence remain unresolved, so the verdict must be graded and carry a reversal condition.", [7, 6, 4, 19]),
        (20, "Assess the design of an indicator system for a new government programme, including the failure modes it must survive.", "An indicator system is an incentive system, so the assessment must specify the properties a usable indicator requires, name the failure modes that follow from attaching consequences to numbers, and pair each with a correction rather than recommending better monitoring in general.", [15, 16, 17, 18]),
    ],
    [
        plan("What the evidence layer owns and why it transfers", [0], "No direct Mains demand is routed here, so the architecture is built for transfer.", "Open any evaluation demand by stating what evidence would settle it."),
        plan("The results chain from input to impact", [1, 2], "Outputs are necessary evidence and never sufficient evidence of change.", "Build the chain before citing a single figure."),
        plan("Classifying the examiner's own statistic", [3], "Coverage is an output and must not be presented as proof of effect.", "Demonstrate evidence discipline on the number supplied in the stem."),
        plan("The evaluation office and its criteria", [4, 5], "The office evaluates and cannot redesign, and criteria are a frame rather than evidence.", "Anchor an evaluate demand in a named institution and a named criteria set."),
        plan("The budget framework and its coverage rule", [6], "Coverage is annual, so a figure must carry its Budget year and never be carried forward.", "Cite the budget instrument with the discipline that protects it from staleness."),
        plan("Outcome budgeting against output and input budgeting", [7], "The formal requirement outruns the practice while achievement carries no budgetary consequence.", "Grade a budgeting reform instead of endorsing or dismissing it."),
        plan("The district programme and its dashboard", [8], "The district unit conceals divergence inside the district.", "Supply the standard Indian example of near-real-time monitoring with its limit."),
        plan("Ranking by improvement rather than level", [9], "Any improvement metric can be gamed through baseline understatement.", "Show an incentive-design choice with its risk and its validation condition."),
        plan("The block programme as a separate exercise", [10], "District and block unit counts and indicator sets must never be merged.", "Avoid the standard factual error in this area of the syllabus."),
        plan("Monitoring against evaluation", [11], "Neither function substitutes for the other and each fails differently.", "Split the two before assessing any information system."),
        plan("Self-reporting with a validation layer", [12], "Validation capacity and rigour vary by sector and indicator.", "State a data-quality design honestly instead of praising or dismissing a dashboard."),
        plan("Attribution, the baseline and the method set", [13, 14], "Without a baseline no method produces a defensible outcome claim.", "Answer a twenty-mark evaluation demand at the level of method rather than opinion."),
        plan("Indicator properties and their failure modes", [15, 16], "An indicator carrying a consequence stops measuring and starts being produced.", "Convert a vague monitoring recommendation into a specified design."),
        plan("Independence and the publication condition", [17], "Independence depends on who commissions, funds and can withhold the report.", "Recommend third-party evaluation with the condition that makes it real."),
        plan("Learning, trade-offs, incidence and ownership", [18, 19], "Punitive use suppresses the failure data that learning requires, and the routing is stated.", "Close with the learning loop, the incidence of reporting and an explicit data boundary."),
    ],
    [
        panel("Results chain", "process-flow", [
            "INPUT -> money, staff and materials committed to the intervention",
            "-> ACTIVITY: what was actually done, such as training conducted or pipes laid",
            "-> OUTPUT: what was directly produced, such as kilometres of road or schools built",
            "-> OUTCOME: the change in the target population, such as travel time or learning",
            "-> IMPACT: the wider, longer-term change in access, income or mobility",
            "REPORTING STOPS -> most Indian scheme reporting halts at the output rung",
        ], ["Input, activity, output, outcome and impact", "The results chain as the spine of every evaluative answer"]),
        panel("Classify the statistic", "comparison-table", [
            "OUTPUT CLAIM -> share of households covered; number of facilities constructed",
            "OUTCOME CLAIM -> water quality at the point of use; measured learning level",
            "IMPACT CLAIM -> market access, household income, mobility over years",
            "EXAM MOVE -> name the rung of the figure the stem supplies before using it",
        ], ["Classify the examiner's own statistic"]),
        panel("Institutional map", "evidence-table", [
            "EVALUATION OFFICE -> attached office of NITI Aayog; constituted September 2015",
            "FORMED BY MERGING -> Program Evaluation Office and Independent Evaluation Office",
            "BUDGET FRAMEWORK -> Ministry of Finance, Budget Division; dual output and outcome reporting",
            "DISTRICT PROGRAMME -> Champions of Change dashboard with delta ranking",
            "LIMIT -> the evaluator produces evidence and cannot redesign the scheme",
        ], ["The Development Monitoring and Evaluation Office and its mandate", "The Output-Outcome Monitoring Framework and its coverage rule"]),
        panel("Evaluation criteria set", "root-axes", [
            "RELEVANCE -> was the intervention the right response to the problem",
            "EFFECTIVENESS and EFFICIENCY -> was the objective met, and at what cost",
            "SUSTAINABILITY and IMPACT -> does the change persist, and how wide is it",
            "COHERENCE and EQUITY -> does it fit other policy, and who gained and who did not",
        ], ["The REESI plus coherence and equity criteria"]),
        panel("Coverage discipline card", "labelled-system", [
            "RULE -> the budget framework does not cover every scheme in every year",
            "OWNER-VERIFIED -> 2026-27 document covers 172 major schemes",
            "THRESHOLD -> an outlay of five hundred crore rupees or more in that document",
            "DISCIPLINE -> cite with the Budget year and never carry the figure forward",
        ], ["The Output-Outcome Monitoring Framework and its coverage rule"]),
        panel("Three budgeting modes", "hierarchy", [
            "INPUT BUDGETING -> line items; how much money was allocated to a category",
            "OUTPUT BUDGETING -> physical units produced for the allocation",
            "OUTCOME BUDGETING -> the change achieved relative to the allocation",
            "UNFINISHED -> outcome achievement carries no budgetary consequence",
        ], ["Outcome budgeting against output and input budgeting"]),
        panel("District and block programmes kept separate", "matrix", [
            "DISTRICT PROGRAMME -> 112 districts; 49 key performance indicators; five themes",
            "FIVE THEMES -> health and nutrition; education; agriculture and water resources",
            "FIVE THEMES -> financial inclusion and skill development; basic infrastructure",
            "BLOCK PROGRAMME -> 513 blocks in current NITI Aayog material; a finer unit",
            "ERROR TO AVOID -> merging district and block counts or their indicator sets",
        ], ["The Aspirational Districts Programme and its dashboard architecture", "The Aspirational Blocks Programme as a separate exercise"]),
        panel("Ranking design", "comparison", [
            "ABSOLUTE RANKING -> compares present level; already-advantaged units stay on top",
            "DELTA RANKING -> compares the rate of improvement over a defined period",
            "GAIN -> a historically disadvantaged district is not permanently placed at the bottom",
            "RISK -> baseline understatement inflates apparent improvement",
            "CONDITION -> careful baseline-setting plus independent validation of the data",
        ], ["Delta ranking against absolute ranking"]),
        panel("Monitoring against evaluation", "root-axes", [
            "MONITORING -> continuous, high frequency, typically self-reported administrative data",
            "ITS USE -> rapid course correction while the programme is running",
            "EVALUATION -> periodic, often independent, assesses whether outcomes were achieved",
            "ITS USE -> scheme redesign and resource reallocation after the evidence is in",
            "RULE -> neither substitutes for the other and each fails in a different way",
        ], ["Monitoring and evaluation are complementary and distinct", "Self-reported data with a validation layer"]),
        panel("Method and limit table", "evidence-table", [
            "BEFORE AND AFTER -> shows movement; cannot separate the intervention from everything else",
            "WITH AND WITHOUT -> plausible counterfactual; the comparison group may differ systematically",
            "RANDOMISED TRIAL -> causal effect for the design studied; limited external validity",
            "QUASI-EXPERIMENTAL -> causal inference without randomisation; assumptions can fail",
            "PROCESS EVALUATION -> explains why an outcome occurred; no effect size",
            "ADMINISTRATIVE DATA -> continuous and cheap; only as good as the reporter's incentive",
        ], ["What each evaluation method can and cannot establish", "Attribution is the hard problem and the baseline is the precondition"]),
        panel("Indicator failure modes and corrections", "path-consequence", [
            "GOODHART -> a measure with consequences is produced rather than observed; use a basket",
            "SELF-REPORTED -> the judged entity generates the number; validate a sample independently",
            "AGGREGATION MASKING -> the average hides block and group failure; disaggregate by rule",
            "OUTPUT SUBSTITUTION -> effort moves to what is counted; add quality and outcome measures",
            "SELECTION EFFECTS -> only reachable beneficiaries are measured; report drop-off",
            "DEFINITION DRIFT -> the definition changes between years; publish definitions and breaks",
        ], ["What makes an indicator usable", "The six indicator failure modes and their corrections"]),
        panel("Answer spine for an evaluate demand", "answer-spine", [
            "OPEN -> say what an output claim proves and what it does not, before citing anything",
            "BUILD -> place the evidence on the results chain and name the missing baseline",
            "CORRECT -> state the counterfactual required and the gaming risk in the indicator",
            "CLOSE -> graded verdict about the evaluation design as much as about the scheme",
        ], ["Incidence, the learning loop and honest question ownership"]),
    ],
    [
        "results chain",
        "output",
        "outcome",
        "impact",
        "Development Monitoring and Evaluation Office",
        "Program Evaluation Office",
        "Independent Evaluation Office",
        "September 2015",
        "relevance, effectiveness, efficiency, sustainability and impact",
        "coherence and equity",
        "Output-Outcome Monitoring Framework",
        "Budget Division",
        "outcome budgeting",
        "Aspirational Districts Programme",
        "Champions of Change",
        "delta-ranking",
        "Aspirational Blocks Programme",
        "third-party evaluation",
        "counterfactual",
        "baseline",
        "Goodhart",
    ],
    "No direct General Studies Mains demand and no applied objective demand in the audited 2018-2023, 2024-2025 or 2026 routing ledgers is routed to this topic, and the Basic owner records the same position expressly, so this package carries a transparent zero-direct-question audit rather than a manufactured demand card. No question has been invented from the locally held OCR-searchable official papers, no stem has been paraphrased into an apparent routing, and no official answer key or marking scheme has been consulted for this topic because none is applicable. The examinable consequence is stated openly instead: this topic appears in the examination as the evaluative half of demands owned elsewhere, such as assessing a scheme's effectiveness, judging governance quality or scrutinising expenditure, so the six original solved Mains answers below are built for transfer to an unfamiliar programme rather than for a remembered question, and every figure used is carried with its owner-verified status date and its year. No district rank or indicator value, no evaluation finding, effect size or recommendation, no count of completed evaluations, no coverage percentage without its year and no study attribution is recorded or inferred anywhere in this package.",
    [],
    live_sources=["https://dmeo.gov.in/"],
    current_note="One live official page was verified for this topic on 2026-09-02. The Development Monitoring and Evaluation Office's own website at dmeo.gov.in was read successfully on that date and states that the office is an attached office of NITI Aayog, that it was constituted in September 2015 by merging the erstwhile Program Evaluation Office and the Independent Evaluation Office, that it works to fulfil the monitoring and evaluation mandate and to build the monitoring and evaluation ecosystem in India, and that it is mandated to actively monitor and evaluate the implementation of schemes, programmes and initiatives of the Government of India in order to strengthen their implementation and scope of delivery on an ongoing basis by tracking performance, determining outcomes, diagnosing reasons for poor performance and generating recommendations for course correction; only that statement of constitution and mandate is used, and no evaluation, finding, effect size, recommendation or completed-evaluation count is imported from it. Two further official checks were attempted on the same date and were refused with an access error, namely the NITI Aayog website and the Union Budget portal, so no content from either was read or used and no secondary summary has been treated as an official source. The remaining dated official elements used are those already carried by the repository owners with their status checks, namely the administration of the Output-Outcome Monitoring Framework by the Ministry of Finance's Budget Division as an annual Union Budget document requiring outlay, outputs, outcomes, indicators and targets for covered schemes, the coverage of the 2026-27 document recorded as one hundred and seventy-two major schemes at an outlay threshold of five hundred crore rupees or more, the Aspirational Districts Programme's one hundred and twelve districts and forty-nine key performance indicators across five themes with the Champions of Change dashboard and delta ranking, the separate Aspirational Blocks Programme recorded as five hundred and thirteen blocks, and the office's relevance, effectiveness, efficiency, sustainability and impact criteria together with coherence and equity, all as checked by the owners on 21 July 2026. Every one of those counts is document-year-specific or programme-design-specific and is cited here with that status date, and the package states expressly that a scheme-coverage or threshold figure must never be carried forward across Budget years. No district rank or indicator value is asserted, no evaluation finding, effect size or recommendation is asserted, no count of completed evaluations is asserted, no scheme-coverage percentage without its year is asserted, and no randomised study result or attribution is asserted. The measurement of governance quality by composite indices is cross-linked to the good-governance owner and the evaluation stage of the policy cycle to the policy-design owner rather than restated here.",
)


TOPIC_16 = common.topic(
    16,
    "Sports Governance, Institutions and Major Tournaments",
    "16_Sports-Governance-Institutions-and-Major-Tournaments",
    "16_Sports-Governance-Institutions-and-Major-Tournaments_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and the two ways it is examined", "This topic is examined in two very different ways, namely as objective precision about tournament and institutional rules and as a General Studies Paper-II governance case study on autonomy, accountability and rights in a self-regulating sector, and both are held in this owner; the analysis is confined to governance, statutory status, eligibility architecture, integrity systems and dispute routes, and it deliberately carries no match result, no medal tally, no athlete name, no doping case and no federation's current recognition status, because those are volatile or unverifiable and are not what either paper tests."),
        ("The layered governance map of organised sport", "Organised sport is governed in layers, with the International Olympic Committee governing the Olympic Movement and the Olympic Games, an international federation governing the common rules and recognition of its own sport, continental and national federations governing and representing the sport in their territory, and the tournament organiser or league governing entry conditions for its own event, above which sits the athlete's eligibility, entry, discipline and safeguarding; running parallel to that chain are an integrity layer built on the World Anti-Doping Code and implemented by a national anti-doping organisation, and a dispute layer running from internal appeal to a sport tribunal or to arbitration where applicable."),
        ("The distinct roles of the named institutions", "The International Olympic Committee is distinct from each sport's international federation, a national sports federation governs and represents its sport nationally subject to the applicable recognition and legal framework, the World Anti-Doping Agency writes the global code and standards and does not organise tournaments, the national anti-doping organisation implements testing and results management within its jurisdiction, the Court of Arbitration for Sport is an independent sports-dispute forum and not the ordinary rule-maker for any sport, the Ministry of Youth Affairs and Sports holds the Union policy and recognition framework, and the Sports Authority of India implements training, infrastructure and athlete support."),
        ("Recognition, selection and organisation are three different functions", "Recognising a federation, selecting athletes and organising an event are distinct functions that are routinely merged in weak answers, and keeping them apart is what allows a governance analysis to locate the failure, because a complaint about a selection decision is not a complaint about recognition policy and a complaint about entry into an event is a matter for the organiser's rules rather than for the recognising authority."),
        ("Autonomy is a functional protection and never a jurisdictional immunity", "Sporting autonomy is a functional protection for technical and selection decisions and it does not confer immunity from national law, from anti-doping rules, from financial accountability or from judicial review, because a body exercising monopoly power over a person's livelihood and career is exercising public power in substance whatever its legal form; the defensible line is that oversight directed at governance standards, finance and rights is categorically different from interference in team selection or technical rules, and it is that distinction which makes statutory regulation defensible against the charge of interference."),
        ("Structural monopoly is the reason sport needs governing", "The governance problem in sport is structural monopoly, because there is ordinarily one federation per sport and no exit for the athlete, so the contractual and market disciplines that constrain an ordinary association do not operate and the athlete cannot take custom elsewhere; that absence of exit, rather than any assumption of bad faith, is what makes published criteria, recorded reasons and an independent appeal more important in sport than in most regulated sectors."),
        ("The Grand Slam architecture and the ownership distinction", "The four Grand Slam tournaments are the Australian Open, Roland-Garros, Wimbledon and the US Open, and each event has its own organiser and ownership while the four cooperate through a shared governance structure and a common Grand Slam Rule Book, so a shared partnership in rule-making does not erase separate ownership and operation and the proposition that one owner operates all four is false; the owners verified the tournament-rule position on 2 August 2026."),
        ("The four distinct entry routes and the eligibility distinction", "Entry into a competition can arise through direct ranking acceptance, through qualifying, through a wild card or through a protected or special entry, and these routes are not interchangeable, so eligibility is a separate question from acceptance into a draw and a player who is internationally ranked does not thereby hold unlimited automatic entry; treating a broadly true description of elite sport as proof of a specific entry rule is the standard trap in this area."),
        ("Wild-card precision", "A wild card is a discretionary entry outside ordinary ranking-based acceptance, and two precisions decide objective statements about it, namely that it does not exempt the player from eligibility, conduct or anti-doping rules and that a limit on the number of wild-card slots available in a draw is not the same thing as a cap on how many wild cards a player may receive over a career; a statement that converts a slot limit into a lifetime player cap is therefore a distinct proposition that must be tested on its own."),
        ("Main draw, qualifying and the meaning of an age threshold", "The main draw and the qualifying competition are separate stages with separate draw sizes and separate entry routes, and an age threshold in a rule book is an eligibility condition rather than proof of acceptance into a draw, so an answer that reads an age rule as an entitlement to play has confused a condition of eligibility with an outcome of acceptance."),
        ("The statement-by-statement method for objective demands", "An objective demand in this area typically combines an institutional proposition about shared governance, an eligibility proposition about age and ranking, and a wild-card proposition about caps, and the disciplined method is to evaluate each proposition separately against the applicable rule book rather than accepting or rejecting the set as a whole; a broadly accurate description of elite competition is not evidence of a specific entry rule, and this is precisely the confusion such items exploit."),
        ("The National Sports Governance Act, 2025 and its legislative trail", "The National Sports Governance Act, 2025 was introduced in the Lok Sabha on 23 July 2025, passed by the Lok Sabha on 11 August 2025 and by the Rajya Sabha on 12 August 2025, received assent on 18 August 2025 and is Act No. 25 of 2025, as verified by the owners on 13 August 2026, and its enactment means that any answer written on the earlier code-only framework, which described Indian sports governance without a national governance statute, is now wrong."),
        ("Phased commencement and the gazette-verified tranche", "Commencement of the Act is phased rather than immediate, with select provisions in force from 1 January 2026 and a second tranche from 12 May 2026 under S.O. 2406(E), which the owners record as commencing sections 5(3) to 5(5), section 7, section 17(8) to 17(9) and sections 18, 19, 21, 28 and 29; rules under the Act were framed during 2026 and their existence is recorded while individual rule contents remain secondary-reported and must be verified before detailed citation, and the specific list of provisions commenced on 1 January 2026 is likewise recorded as secondary-reported."),
        ("What the Act creates as examinable governance content", "The Act creates a National Sports Board as a statutory body whose recognition and regulatory jurisdiction it designs, a National Sports Tribunal as a statutory forum designed for sports disputes, and a structured statutory category of national sports bodies covering the Olympic and Paralympic bodies, National Sports Federations and regional federations with compliance conditions attached to recognition, and its stated purposes include alignment with international charter standards, athlete welfare and representation, ethics arrangements, gender representation and transparency, with bodies receiving public funding brought within the ambit of the Right to Information Act."),
        ("The status ladder that must appear in any answer", "The controlling discipline is the status ladder that enactment is not commencement of a provision, commencement is not the framing of rules, rules are not the constitution of an institution, and constitution is not operational jurisdiction, and applying that ladder to the verified record means that the principal recognition-power provision was not located in a commenced tranche as of 13 August 2026, that the Tribunal's jurisdiction and appeal provisions were likewise not located in the commenced tranches, and that the National Sports Development Code of India, 2011 therefore remains the operative recognition framework read with the Act's deeming continuity for previously recognised bodies until the recognition jurisdiction is commenced and operationalised."),
        ("The anti-doping statutory layer and the amendment recorded as unverified", "The National Anti-Doping Act, 2022 made the national anti-doping organisation a statutory body in place of its earlier society-registered form and supplies the statutory framework for anti-doping rule violations and results management in India, which is a genuine change of legal status in 2022; a National Anti-Doping (Amendment) Act, 2025 has been enacted and its reported thrust is to strengthen the operational independence of that body's leadership from sports federations and government agencies, to relocate the power to constitute the appeal panel and to clarify appeal routes to the Court of Arbitration for Sport, but this item is recorded from secondary reporting rather than from a gazette text obtained during the audit, so it must be described as an enacted amendment whose detailed provisions require verification and its section numbers and commencement dates must not be stated."),
        ("Layered anti-doping jurisdiction and strict liability", "The anti-doping chain runs from the World Anti-Doping Code, which the global agency writes, through the national statute and the national organisation that conducts testing and results management, to an appeal that may lie to the Court of Arbitration for Sport, and the single most examinable concept in it is strict liability, under which an athlete is responsible for what is found in their body irrespective of intent; strict liability is necessary because intent is generally unprovable and it is genuinely harsh on an athlete affected by contamination or by negligent support staff, which is why due process, accredited testing and reasoned results management are the conditions that keep it defensible."),
        ("Institutional legal character, the distinction most often got wrong", "The Sports Authority of India is an autonomous body registered as a society under the Societies Registration Act, 1860 under the Ministry of Youth Affairs and Sports and is not a statutory corporation created by its own Act, and the 2025 statute brings sports bodies within a statutory regulatory framework without converting that organisational form; the national anti-doping organisation is statutory under the 2022 Act, the National Sports Board and the National Sports Tribunal are statutory creations under the 2025 Act, National Sports Federations remain private associations that require recognition, the Indian Olympic Association is the National Olympic Committee and a private body within the Olympic Movement whose charter autonomy coexists with national law, and the Court of Arbitration for Sport is an international arbitral institution based in Lausanne and established in 1984 rather than a court of any state or a rule-maker for any sport."),
        ("The six-test checklist for any sports body or governance failure", "Any sports body or governance failure, including an unfamiliar federation dispute or eligibility controversy, can be assessed on six tests, namely the basis of authority and whether it rests on statute, recognition, contract or a private rule book, recognition and its conditions including who recognises on what published criteria and whether recognition can be withdrawn with reasons, internal governance covering elections, tenure limits, athlete and gender representation, conflict-of-interest rules and published audited accounts, selection and eligibility covering whether criteria are published before the selection cycle, applied consistently and supported by reasons for exclusion, dispute resolution covering an independent forum with notice, hearing, reasons and appeal and whether the athlete is required to waive access to courts, and athlete protection covering safeguarding against abuse and harassment, grievance channels independent of the coach and federation, health and injury support and protection from retaliation for complaining."),
        ("Trade-offs, incidence and honest question ownership", "The honest trade-offs are that international charters protect sports bodies from government interference so that excessive interference can risk international suspension of a national body while oversight of governance, finance and rights remains categorically different, that a specialist tribunal brings speed and domain knowledge which matter when a selection dispute must be settled before a competition while raising the same appointment-independence questions as tribunals generally, that governance attention and funding follow medals so broad-base and school sport have weaker constituencies, that event and broadcast revenue concentrates at federation and organiser level so athlete representation in governance is the mechanism that addresses it, and that a national statute does not by itself reform State-level associations; incidence is uneven because the athlete has the shortest career horizon, the least bargaining power and a real fear of retaliation, the coach and support staff hold day-to-day power which is why safeguarding channels must be independent of them, and the national federation holds monopoly recognition while depending on public funding. A Ministry of Youth Affairs and Sports page read on 2 September 2026 carries the National Sports Policy text stating that broad-basing of sports remains primarily a responsibility of the State Governments with the Union Government supplementing their efforts, and that the question of inclusion of sports in the Concurrent List of the Constitution and the introduction of appropriate legislation for guiding all matters involving national and inter-State jurisdiction will be pursued, which is recorded as a stated policy intention and not as a claim about the present entry-list position. On ownership, the audited 2026 Prelims ledger routes one objective demand on Grand Slam tennis governance, eligibility and wild-card participation rules to this Basic owner, the locally held 2026 Set-A key is provisional so no option, answer letter or distractor is recorded or inferred, and no direct Mains demand in the audited 2018-2023 or 2024-2025 ledgers is routed here; no unverified substantive-power section number, member count, tenure, age limit, quorum or penalty under the 2025 Act is asserted, no decision, inquiry or derecognition by the Board is asserted, no case decided by the Tribunal is asserted, no doping case, athlete name or sanction is asserted, no federation's recognition status is asserted, and no medal tally, funding figure or tournament result is asserted anywhere."),
    ],
    [
        "Do not state that the International Olympic Committee makes the ordinary competition rules of every sport, because international federations do.",
        "Do not treat sporting autonomy as immunity from national law, anti-doping rules, financial accountability or judicial review.",
        "Do not merge recognition of a federation, selection of athletes and organisation of an event into one function.",
        "Do not claim that shared Grand Slam governance means a single owner operates all four tournaments.",
        "Do not treat international ranking as conferring unlimited automatic entry, because eligibility and acceptance are different questions.",
        "Do not convert a limit on wild-card slots in a draw into a cap on how many wild cards a player may receive.",
        "Do not suggest that a wild card exempts a player from eligibility, conduct or anti-doping rules.",
        "Do not read an age threshold as proof of acceptance into a draw, because it is an eligibility condition.",
        "Do not evaluate a set of objective statements as a block, because each proposition must be tested separately against the applicable rule book.",
        "Do not describe Indian sports governance as having no national governance statute, because the National Sports Governance Act, 2025 is enacted.",
        "Do not treat enactment as commencement, commencement as rules, rules as constitution of an institution, or constitution as operational jurisdiction.",
        "Do not present the National Sports Board as already exercising its recognition power or the National Sports Tribunal as having replaced ordinary litigation.",
        "Do not assert any unverified substantive-power section number, member count, tenure, age limit, quorum or penalty under the 2025 Act.",
        "Do not assert any decision, inquiry or derecognition by the Board, any case decided by the Tribunal, or any federation's recognition status.",
        "Do not state section numbers or commencement dates for the National Anti-Doping (Amendment) Act, 2025, which is recorded only from secondary reporting.",
        "Do not describe the Sports Authority of India as a statutory corporation, because it is a society registered under the Societies Registration Act, 1860.",
        "Do not describe the Court of Arbitration for Sport as a court of any state or as a rule-maker for any sport.",
        "Do not assert any doping case, athlete name or sanction, any medal tally, funding figure or tournament result.",
        "Do not claim that sports has been placed in the Concurrent List, because the policy text records only that the question will be pursued.",
    ],
    [
        (10, "Distinguish the roles of the Olympic body, an international federation, a national federation and a tournament organiser in the governance of sport.", "Each layer makes a different kind of rule and a governance answer must place the disputed decision in the correct layer, because a complaint about entry belongs to the organiser, a complaint about sport rules to the international federation and a complaint about recognition to the national framework.", [1, 2, 3, 0]),
        (10, "Explain why autonomy of sports federations cannot be treated as immunity from public accountability.", "Autonomy protects technical and selection judgement while monopoly control over a person's livelihood makes the power public in substance, so oversight of governance, finance and rights is categorically different from interference in selection and is therefore defensible.", [4, 5, 18, 19]),
        (15, "Examine the shift in Indian sports governance from an executive code to a statutory framework.", "The change is real because the source of authority has moved from funding-linked administrative conditions to a statute with a regulator and a tribunal, but the change in practice is unproven because commencement is phased and the recognition jurisdiction was not located in a commenced tranche on the verified record.", [11, 12, 13, 14]),
        (15, "Examine the governance conditions that make anti-doping enforcement fair as well as effective.", "Strict liability is necessary because intent is unprovable and harsh because contamination and negligent support staff fall on the athlete, so fairness depends on accredited testing, reasoned results management, an independent appeal route and an authority whose leadership is insulated from the bodies it regulates.", [15, 16, 2, 18]),
        (20, "Assess how an objective demand about tournament eligibility should be analysed proposition by proposition.", "Such an item combines an institutional claim, an eligibility claim and a discretionary-entry claim that are true or false independently, so the disciplined method separates ownership from cooperation, eligibility from acceptance and a draw-slot limit from a player cap before any judgement is offered.", [6, 7, 8, 10]),
        (20, "Assess the governance of a self-regulating sector in which the regulated party cannot exit, using sport as the case.", "Absence of exit removes the market discipline that ordinarily restrains a private association, so the governance answer must rebuild that discipline through published criteria, recorded reasons, independent dispute resolution, safeguarding independent of the coach and representation of the party with least bargaining power.", [5, 18, 19, 17]),
    ],
    [
        plan("What the sports-governance owner holds", [0], "No result, medal tally, athlete name, doping case or recognition status belongs in this answer.", "Set the correct scope and avoid decorative sporting detail from the first sentence."),
        plan("The layered governance map", [1, 2], "The Olympic body does not make the ordinary rules of every sport.", "Place a disputed decision in the correct governing layer before analysing it."),
        plan("Three functions and one autonomy limit", [3, 4], "Autonomy protects sporting judgement and never displaces law, audit or rights.", "Separate recognition, selection and organisation, then bound the autonomy claim."),
        plan("Why the absence of exit changes everything", [5], "The problem is structural monopoly rather than any assumption of bad faith.", "Explain why sport needs governing without moralising about federations."),
        plan("The Grand Slam architecture", [6], "Cooperation in rule-making does not merge ownership or operation.", "Get the institutional proposition right before touching eligibility."),
        plan("Four entry routes and the eligibility distinction", [7], "Eligibility is a separate question from acceptance into a draw.", "Replace an impression of elite sport with the exact route structure."),
        plan("Wild-card precision", [8], "A limit on slots in a draw is not a cap on a player.", "Defeat the discretionary-entry proposition on its own terms."),
        plan("Stages, thresholds and the statement method", [9, 10], "A broadly true description of elite sport is not evidence of a specific rule.", "Apply proposition-by-proposition discipline to an objective demand."),
        plan("The statute and its legislative trail", [11], "An answer written on the earlier code-only framework is now wrong.", "Name the Act with its dates and number rather than gesturing at reform."),
        plan("Phased commencement and the gazette record", [12], "Rule contents and the first tranche list remain secondary-reported and need verification.", "Cite commencement with its instrument instead of implying full operation."),
        plan("What the Act actually creates", [13], "Design in the statute is not the same as exercise of the power.", "Supply the examinable institutional content of the reform."),
        plan("The status ladder discipline", [14], "The 2011 Code remains the operative recognition framework on the verified record.", "Write the one paragraph that separates a current answer from an outdated one."),
        plan("Anti-doping law and strict liability", [15, 16], "Section numbers and commencement dates of the 2025 amendment must not be stated.", "Handle a fast-moving integrity layer without overstating the record."),
        plan("Legal character and the six-test checklist", [17, 18], "A society is not a statutory corporation and an arbitral institution is not a court.", "Transfer the framework to an unfamiliar body or governance failure."),
        plan("Trade-offs, incidence and honest ownership", [19], "Policy intention about the Concurrent List is not a claim about the present entry list.", "Close a twenty-mark answer with balance, incidence and an explicit data boundary."),
    ],
    [
        panel("Governance layer map", "hierarchy", [
            "OLYMPIC BODY -> the Olympic Movement and the Games; not the rule-maker for each sport",
            "INTERNATIONAL FEDERATION -> common sport rules and international recognition",
            "CONTINENTAL AND NATIONAL FEDERATION -> governs and represents the sport in territory",
            "ORGANISER OR LEAGUE -> entry conditions and conduct of its own event",
            "ATHLETE -> eligibility, entry, discipline and safeguarding sit at the end of the chain",
        ], ["The layered governance map of organised sport"]),
        panel("Parallel integrity and dispute layers", "root-axes", [
            "INTEGRITY LAYER -> global anti-doping code, then the national anti-doping organisation",
            "DISPUTE LAYER -> internal appeal, then a sport tribunal or arbitration where applicable",
            "SEPARATION -> the code writer does not organise events; the arbitral forum makes no rules",
            "STRICT LIABILITY -> the athlete answers for what is in the body, irrespective of intent",
        ], ["The distinct roles of the named institutions", "Layered anti-doping jurisdiction and strict liability"]),
        panel("Three functions kept apart", "comparison-table", [
            "RECOGNITION -> who is entitled to represent the sport, on published criteria",
            "SELECTION -> who is chosen to compete, on criteria published before the cycle",
            "ORGANISATION -> who may enter this event, on the organiser's own entry rules",
            "USE -> locate the complaint in one function before proposing a remedy",
        ], ["Recognition, selection and organisation are three different functions"]),
        panel("Autonomy against accountability", "causal-system", [
            "AUTONOMY PROTECTS -> technical rules and selection judgement from political direction",
            "-> MONOPOLY: one federation per sport and no exit for the athlete",
            "-> PUBLIC POWER IN SUBSTANCE: livelihood and career depend on the body's decision",
            "-> OVERSIGHT OF GOVERNANCE, FINANCE AND RIGHTS is not interference in selection",
            "RISK IF CROSSED -> interference in selection can expose a body to charter consequences",
        ], ["Autonomy is a functional protection and never a jurisdictional immunity", "Structural monopoly is the reason sport needs governing"]),
        panel("Grand Slam architecture card", "evidence-table", [
            "THE FOUR -> Australian Open, Roland-Garros, Wimbledon and the US Open",
            "OWNERSHIP -> each event has its own organiser and its own operation",
            "COOPERATION -> a shared governance structure and a common Grand Slam Rule Book",
            "FALSE PROPOSITION -> shared governance means one owner operates all four",
        ], ["The Grand Slam architecture and the ownership distinction"]),
        panel("Four entry routes", "matrix", [
            "DIRECT RANKING ACCEPTANCE -> entry earned by position on the applicable ranking",
            "QUALIFYING -> a separate stage with its own draw size and its own entry route",
            "WILD CARD -> discretionary entry outside ordinary ranking acceptance",
            "PROTECTED OR SPECIAL ENTRY -> a defined exception route under the rule book",
            "RULE -> eligibility is a condition; acceptance into a draw is an outcome",
        ], ["The four distinct entry routes and the eligibility distinction", "Main draw, qualifying and the meaning of an age threshold"]),
        panel("Wild-card proposition test", "labelled-system", [
            "WHAT IT IS -> discretionary entry bypassing ordinary ranking acceptance",
            "WHAT IT IS NOT -> an exemption from eligibility, conduct or anti-doping rules",
            "SLOT LIMIT -> a cap on wild-card places available within a given draw",
            "PLAYER CAP -> a separate proposition about one player over a career; test it alone",
        ], ["Wild-card precision", "The statement-by-statement method for objective demands"]),
        panel("Statutory trail of the 2025 Act", "timeline", [
            "23 JULY 2025 -> introduced in the Lok Sabha",
            "11 AND 12 AUGUST 2025 -> passed by the Lok Sabha and the Rajya Sabha",
            "18 AUGUST 2025 -> assent; the National Sports Governance Act, 2025, Act No. 25 of 2025",
            "1 JANUARY 2026 -> first tranche of select provisions in force",
            "12 MAY 2026 -> second tranche under S.O. 2406(E); rules framed during 2026",
        ], ["The National Sports Governance Act, 2025 and its legislative trail", "Phased commencement and the gazette-verified tranche"]),
        panel("Status ladder discipline", "process-flow", [
            "ENACTED -> the Act has received assent and carries a number",
            "-> PROVISION COMMENCED: only the notified tranches are in force",
            "-> RULES FRAMED: existence recorded; individual contents need verification",
            "-> INSTITUTION CONSTITUTED: creation in law is not the exercise of a power",
            "-> JURISDICTION OPERATIONAL: not asserted, so the 2011 Code still governs recognition",
        ], ["The status ladder that must appear in any answer"]),
        panel("Institutional legal character", "comparison-table", [
            "SPORTS AUTHORITY OF INDIA -> society under the Societies Registration Act, 1860",
            "NATIONAL ANTI-DOPING ORGANISATION -> statutory under the 2022 Act; a real 2022 change",
            "BOARD AND TRIBUNAL -> statutory creations under the 2025 Act; powers not all commenced",
            "NATIONAL FEDERATIONS -> private associations that require recognition to represent",
            "ARBITRAL FORUM -> an international arbitral institution at Lausanne, established 1984",
        ], ["Institutional legal character, the distinction most often got wrong"]),
        panel("Six-test checklist for a sports body", "path-consequence", [
            "1 BASIS OF AUTHORITY -> statute, recognition, contract or a private rule book",
            "2 RECOGNITION -> published criteria, and withdrawal with recorded reasons",
            "3 INTERNAL GOVERNANCE -> elections, tenure limits, athlete and gender representation",
            "4 SELECTION -> criteria published before the cycle and reasons given for exclusion",
            "5 DISPUTE -> independent forum with notice, hearing, reasons and appeal",
            "6 ATHLETE PROTECTION -> safeguarding independent of coach, and no retaliation",
        ], ["The six-test checklist for any sports body or governance failure"]),
        panel("Answer spine for a sports-governance demand", "answer-spine", [
            "OPEN -> name the layer and the legal character of the body actually in dispute",
            "BUILD -> autonomy as protection for sporting judgement, bounded by law and rights",
            "CORRECT -> apply the status ladder and never treat enactment as operation",
            "CLOSE -> graded verdict on basis of authority against practice, with no result cited",
        ], ["Trade-offs, incidence and honest question ownership"]),
    ],
    [
        "International Olympic Committee",
        "international federation",
        "World Anti-Doping Code",
        "Court of Arbitration for Sport",
        "Lausanne",
        "Sports Authority of India",
        "Societies Registration Act, 1860",
        "Indian Olympic Association",
        "National Sports Governance Act, 2025",
        "Act No. 25 of 2025",
        "18 August 2025",
        "1 January 2026",
        "12 May 2026",
        "S.O. 2406(E)",
        "National Sports Board",
        "National Sports Tribunal",
        "National Sports Development Code of India, 2011",
        "National Anti-Doping Act, 2022",
        "Right to Information Act",
        "Australian Open",
        "Roland-Garros",
        "Wimbledon",
        "US Open",
        "wild card",
        "strict liability",
    ],
    "One applied objective demand is routed to this topic across the audited ledgers and no direct General Studies Mains demand in the audited 2018-2023 or 2024-2025 ledgers is routed here, so no Mains demand card is manufactured and no question is invented from the locally held OCR-searchable official papers. The audited 2026 Prelims ledger routes the objective demand on Grand Slam tennis governance, eligibility and wild-card participation rules to this Basic owner, and the owner's own generated 2026 integration block records the same routing. The 2026 Set-A key held locally is provisional, so no option, answer letter or distractor is recorded or inferred for it, and the demand card below supplies only the rule-architecture route by which each proposition in such an item is tested separately. The Indian statutory position was verified by the owners on 13 August 2026 and the tournament-rule position on 2 August 2026, and the package applies the status ladder throughout, so no unverified substantive-power section number, member count, tenure, age limit, quorum or penalty under the 2025 Act is asserted, no decision, inquiry or derecognition by the National Sports Board is asserted, no case decided by the National Sports Tribunal is asserted, no doping case, athlete name or sanction is asserted, no federation's recognition status is asserted, and no medal tally, funding figure or tournament result is asserted anywhere.",
    [
        ("2026", "Preliminary Examination General Studies Paper-I", "Objective demand on Grand Slam tennis governance, eligibility and wild-card participation rules, routed to this Basic owner by the audited 2026 Prelims ledger and by the owner's own 2026 integration block.", "The 2026 Set-A key held locally is provisional, so no option, answer letter or distractor is recorded or inferred, and no tournament result, player or draw outcome is asserted. The tournament-rule position underlying this route was verified by the owners on 2 August 2026.", "An item of this family combines three propositions that are true or false independently, so the method is to separate them before judging any of them. Take the institutional proposition first. The four Grand Slam tournaments are the Australian Open, Roland-Garros, Wimbledon and the US Open, each with its own organiser and its own operation, and they cooperate through a shared governance structure and a common Grand Slam Rule Book; cooperation in rule-making is therefore compatible with four separate owners, and any statement that shared governance means a single owner operates all four is false on that ground alone. Take the eligibility proposition second. Entry into a competition arises through four distinct routes, namely direct ranking acceptance, qualifying, a wild card and a protected or special entry, and eligibility is a condition that a player must satisfy while acceptance into a draw is a separate outcome produced by one of those routes, so a statement that an internationally ranked player of a stated age is thereby entitled to enter confuses a condition with an outcome. Add the stage precision that supports it: the main draw and the qualifying competition are separate stages with separate draw sizes and separate entry routes, and an age threshold in a rule book is an eligibility condition rather than proof of acceptance. Take the wild-card proposition third, and read it with the greatest care because it is where such items usually turn. A wild card is a discretionary entry outside ordinary ranking-based acceptance, and it does not exempt the recipient from eligibility, conduct or anti-doping rules; further, a limit on the number of wild-card slots available within a draw is a rule about the event, while a cap on how many wild cards a single player may receive is a rule about the player, and the two must not be inferred from each other. Now state the general discipline that the item is testing. A broadly accurate description of elite tennis is not evidence of a specific entry rule, so each statement must be checked against the named rule book on its own terms rather than accepted because the overall picture sounds right. Close on the honest boundary: because the locally held 2026 key is provisional, no option may be selected here, no answer letter is inferred, and no distractor is reconstructed; what the routing establishes is the obligation to hold the rule architecture precisely, not an entitlement to state an answer."),
    ],
    live_sources=["https://yas.gov.in/sports/national-sports-governance-act-2025"],
    current_note="One live official page was verified for this topic on 2026-09-02. A Ministry of Youth Affairs and Sports page on the official yas.gov.in domain was read successfully on that date and returned the text of the National Sports Policy, which states that the Central Government, in conjunction with the State Governments, the Indian Olympic Association and the National Sports Federations, will pursue the twin objectives of broad-basing of sports and achieving excellence in sports at the national and international levels, that broad-basing will primarily remain a responsibility of the State Governments while the Union Government actively supplements their efforts including for tapping latent talent in rural and tribal areas, that the Union Government and the Sports Authority of India in association with the Indian Olympic Association and the National Sports Federations will focus on achieving excellence, that a Resolution on the National Sports Policy was laid in both Houses of Parliament in August 1984, and that the question of inclusion of sports in the Concurrent List of the Constitution of India and the introduction of appropriate legislation for guiding all matters involving national and inter-State jurisdiction will be pursued; that last item is recorded strictly as a stated policy intention and is not treated as a claim about the present position of sports in the constitutional lists, and nothing further is inferred from the page. Seven further official checks were attempted on the same date and yielded no usable official text, namely the Sports Authority of India website, which returned a server error, the national anti-doping organisation's about page, which redirected away from any content, the Court of Arbitration for Sport's information pages, which returned not-found errors, the international tennis federation's rules and regulations page, which was blocked by a bot-protection interstitial, the world anti-doping agency's code page, which returned no extractable content, the international Olympic body's governance information page, which timed out, and the Press Information Bureau release page, which was refused with an access error; no content from any of them was read or used and no secondary summary has been treated as an official source. Every substantive statutory and tournament element in this package therefore rests on the repository owners with their own status checks, namely the National Sports Governance Act, 2025 introduced on 23 July 2025, passed on 11 and 12 August 2025, assented on 18 August 2025 as Act No. 25 of 2025, with select provisions in force from 1 January 2026 and a second tranche from 12 May 2026 under S.O. 2406(E) commencing sections 5(3) to 5(5), section 7, sections 17(8) to 17(9) and sections 18, 19, 21, 28 and 29, rules framed during 2026 whose individual contents remain secondary-reported, the National Sports Board and National Sports Tribunal as statutory creations whose recognition and jurisdiction provisions were not located in a commenced tranche, the National Sports Development Code of India, 2011 as the still-operative administrative recognition instrument read with the Act's deeming continuity, the National Anti-Doping Act, 2022 giving the national anti-doping organisation statutory status, the National Anti-Doping (Amendment) Act, 2025 recorded only from secondary reporting and therefore cited without section numbers or commencement dates, the Sports Authority of India as a society registered under the Societies Registration Act, 1860, and the Court of Arbitration for Sport as an international arbitral institution at Lausanne established in 1984, all as verified by the owners on 13 August 2026, together with the Grand Slam tournament and entry-route architecture verified by the owners on 2 August 2026. The controlling discipline applied throughout is that enactment is not commencement, commencement is not the framing of rules, rules are not the constitution of an institution and constitution is not operational jurisdiction. No unverified substantive-power section number, member count, tenure, age limit, quorum or penalty under the 2025 Act is asserted, no decision, inquiry or derecognition by the National Sports Board is asserted, no case decided by the National Sports Tribunal is asserted, no doping case, athlete name or sanction is asserted, no federation's recognition status is asserted, no tournament date, host, draw outcome or result is asserted, no medal tally is asserted, and no funding figure is asserted. Decorative match trivia is excluded by design, because the examinable content of this topic is institutional and legal rather than sporting.",
)

