"""Authored content data for Governance learner-v2 Topics 09-10."""

from __future__ import annotations

import generate_governance_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_09 = common.topic(
    9,
    "Civil Services and Mission Karmayogi",
    "09_Civil-Services-and-Mission-Karmayogi",
    "09_Civil-Services-and-Mission-Karmayogi_Learner-V2-Complete-Topic-Package.md",
    [
        ("Civil services as a structurally distinctive democratic institution", "The civil service occupies a structurally distinctive place in a democracy because it is the permanent, neutral and expert executant of decisions taken by a changing elected political executive, and its three classical traits of political neutrality, permanence and anonymity were designed as one package in which each trait supports the others, so an answer that recites a list of civil-service duties has already missed what the demand is testing."),
        ("Political neutrality as impartiality rather than passivity", "Political neutrality is the obligation to serve any elected government impartially and to implement lawful policy irrespective of personal political preference, which is the classical basis of the service's legitimacy across changes of government; it does not mean the absence of policy influence, because civil servants can and do shape technical and expert advice, and treating neutrality as silence is the commonest conceptual error in this whole area."),
        ("Permanence and institutional memory", "Permanence means the civil service continues in office across changes of political government, supplying the institutional memory and continuity that budget execution, law and order and service delivery require and that a purely political appointee system would lack, while its cost is that permanence can shelter sustained non-performance wherever appraisal carries no consequence."),
        ("Anonymity as accountability displacement", "Anonymity is the convention that civil servants advise confidentially while ministers take public credit or blame, and it must be described as accountability displacement rather than accountability absence, because internal accountability through service rules, vigilance mechanisms, departmental hierarchy and performance appraisal continues even where public attributive accountability sits with the political executive."),
        ("The constitutional setting of Articles 309 to 312", "Articles 309 to 311 govern recruitment and service conditions, the doctrine of pleasure and the dismissal safeguards, and Article 312 permits Parliament to create an All India Service after the required Rajya Sabha resolution, so tenure protection is the legal basis of neutrality; the detailed composition, appointment and removal architecture of the Union and State Public Service Commissions is owned by Polity and must be cross-linked rather than restated from memory."),
        ("The Doctrine of Democratic Governance as a perceptual legitimacy claim", "The Doctrine of Democratic Governance, as framed in the audited 2024 General Studies Paper-II demand, holds that because civil servants exercise substantial unelected discretionary power the democratic warrant for that power depends on citizens continuing to perceive them as impartial and committed, and it is an analytical and normative principle to be explained and applied rather than a judicially defined constitutional doctrine with a fixed case-law holding to be quoted."),
        ("Perceptual legitimacy as a variable distinct from structure and procedure", "Structural safeguards make the service trustworthy by construction and procedural safeguards enforce that trustworthiness case by case, but the analytical claim that carries an evaluative answer is that perceptual legitimacy is a third and separate variable, because a civil service can be formally neutral and fully rule-compliant while a high-visibility incident degrades public trust faster than institutional reform can repair it, and sustained erosion eventually generates political pressure for direct control over administration."),
        ("Mission Karmayogi as a change in training philosophy", "The National Programme for Civil Services Capacity Building was approved by the Union Cabinet on 2 September 2020 under the Ministry of Personnel, Public Grievances and Pensions, and it shifts civil-service training from rules-based compliance to role-based and competency-driven capacity building, so the substantive reform is a change of training philosophy rather than a change of delivery mode from an offline classroom to an online screen."),
        ("The six-pillar design of the national programme", "The programme is structured around six pillars commonly cited in official material, namely the policy framework, the institutional framework including the Capacity Building Commission, the competency framework, the digital learning framework, electronic human-resource management, and monitoring and evaluation, and this six-pillar architecture is the durable citable design even where the underlying framing documents are refined over time."),
        ("The four-tier institutional chain", "The institutional chain runs from the Prime Minister's Human Resources Council for apex guidance, through the Cabinet Secretariat Coordination Unit, to the Capacity Building Commission for standards, Annual Capacity Building Plans and institutional capacity, and finally to Karmayogi Bharat, the government-owned special purpose vehicle that operates the online platform, so describing the Commission as the sole implementing or platform-operating body is inaccurate."),
        ("The Capacity Building Commission and its dated establishment", "The Capacity Building Commission's own official website, read on 2 September 2026, states that the Commission was established on 1 April 2021 and functions at the core of Mission Karmayogi through policy frameworks that lay the foundation of capacity-building initiatives, and the same official page describes the programme as envisioned in the year 2020; its working instruments are the Annual Capacity Building Plans and the Karmayogi Competency Model, and the repository owners record the same structure as re-verified on 13 August 2026."),
        ("iGOT Karmayogi and the output against outcome distinction", "iGOT Karmayogi is the integrated government online training platform that delivers role-based modules at scale, and the exam-safe discipline is that enrolment, course counts, completion certificates and platform totals are outputs carried on a continuously updated dashboard whereas the outcome is demonstrated workplace application, which is why no learner count, course count, completion total, certificate figure, State memorandum count or training-institute accreditation figure is asserted anywhere in this package."),
        ("The Karmayogi Competency Model and the untested link", "The Karmayogi Competency Model maps behavioural, functional and domain competencies to specific roles and thereby makes the word competency operational rather than rhetorical, but the untested link in the entire reform is whether assessed competency actually governs posting decisions, because a competency framework that never enters the posting file changes training without changing allocation."),
        ("Generalist and specialist as a capacity-allocation problem", "The generalist and specialist question is best treated as a capacity-allocation problem rather than an either-or contest, because policy complexity in technology, finance and climate argues for specialist depth while administrative coordination across sectors and levels of government argues for generalist breadth, and competency mapping is precisely an attempt to allocate the right mix to each specific post instead of resolving the debate wholesale in either direction."),
        ("Lateral entry as a bounded supplement", "Lateral entry is the direct recruitment of domain experts from outside the regular cadre into specified senior positions at Joint Secretary, Director or Deputy Secretary level in selected ministries, and it operates as a periodic and targeted supplement to regular cadre promotion rather than a continuous or cadre-replacing channel; a lateral entrant typically serves a fixed and often shorter contractual tenure and may lack socialisation into permanent-service norms, so the genuine design question is whether it dilutes or complements the classical structural safeguards."),
        ("How neutrality erodes through posting and transfer discretion", "Neutrality erodes through an identifiable chain in which unconstrained posting and transfer discretion leads officers to anticipate the political executive's preference, advice is shaped before it is asked for, permanence protects the office rather than the post because dismissal is hard while displacement to an inconsequential post is easy, anonymity becomes asymmetric as the officer is publicly blamed in controversy and publicly invisible in achievement, and the resulting perception of partiality erodes the legitimacy of unelected discretion."),
        ("The protections that hold neutrality in place", "The protections against that chain are a transparent transfer and posting process, minimum-tenure norms, written reasons for any deviation, recorded advice, a functioning appraisal with meaningful differentiation and institutional rather than personal accountability for outcomes, and stating them as a connected set is what converts a description of politicisation into a reform answer that answers the directive."),
        ("The reciprocal obligation on the political executive", "The Doctrine of Democratic Governance implies a reciprocal obligation, because civil servants must act with integrity while political executives must equally refrain from politically motivated transfers and from pressure for partisan compliance that make neutral service impossible to sustain or to perceive, and a one-sided answer that only asks civil servants to improve misses the two-sided institutional design point the demand rewards."),
        ("Six outcome indicators for any capacity claim", "Any capacity-building claim should be judged on six indicators instead of enrolment figures, namely competency-to-post fit, application of learning visible in work products rather than in completion certificates, citizen-facing outcomes such as service timelines, grievance recurrence and appeal outcomes, tenure stability measured as average time in post, domain staffing of technical posts by qualified people, and independent audit by someone other than the provider of the training."),
        ("The reform-conflict bank and honest question ownership", "Every proposed reform buys a risk that must be named for a fifteen or twenty mark answer, since fixed minimum tenure repairs arbitrary transfer and can entrench a poor performer, performance-linked accountability repairs non-performance and can become a political lever, lateral entry repairs a domain deficit and raises representation and institutional-memory questions, specialisation improves technical quality and costs cross-sector coordination, greater visibility of official advice improves adviser accountability and reduces candour, and contractual mission-mode staffing buys speed at the cost of tenure protection; on ownership, the audited ledgers route the 2020 institutional-quality demand and the 2025 civil-service-ethos demand to this owner, while the 2024 demand on the Doctrine of Democratic Governance is routed by the audited 2024-2025 ledger to the citizen-centric-administration owner and is therefore cross-linked here rather than claimed."),
    ],
    [
        "Do not describe political neutrality as the absence of policy influence or as official silence.",
        "Do not describe anonymity as the absence of accountability; it displaces public accountability and preserves internal accountability.",
        "Do not describe Mission Karmayogi as merely a digital training application or as an offline-to-online delivery change.",
        "Do not describe the Capacity Building Commission as the platform operator or as the sole implementing body of the programme.",
        "Do not assert any learner, course, completion, certificate, State memorandum or accredited-institute figure for the online platform.",
        "Do not assert any lateral-entry vacancy, application, selection or ministry-coverage number.",
        "Do not assert a minimum-tenure figure, an appraisal rule or any committee's specific recommendation on tenure or cadre review.",
        "Do not claim that any component of Mission Karmayogi implements a named Second Administrative Reforms Commission recommendation, because thematic similarity is not evidence of implementation.",
        "Do not restate the composition, appointment or removal provisions of the Public Service Commissions from memory in a governance answer.",
        "Do not treat the Doctrine of Democratic Governance as a judicially defined constitutional doctrine with a fixed case-law holding.",
        "Do not attribute a quotation about civil-service ethos to any named leader or official, because no such quotation is sourced here.",
        "Do not present lateral entry as replacing the generalist cadre structure.",
        "Do not answer an institutional governance stem with an Ethics essay on personal probity and vigilance.",
        "Do not treat course enrolment or completion as evidence of workplace application.",
        "Do not present nationalist consciousness as loyalty to the government of the day rather than to the Constitution and the public interest.",
        "Do not assert civil-service vacancy, sanctioned-strength or attrition figures.",
        "Do not claim verbatim ownership of the 2024 Doctrine of Democratic Governance demand, which the audited ledger routes to the citizen-centric-administration owner.",
    ],
    [
        (10, "Explain why political neutrality, permanence and anonymity were designed as a single package rather than as three separate virtues of the Indian civil service.", "The three traits are interlocking rather than additive, because neutrality without tenure security is unenforceable, permanence without neutrality is merely entrenchment and anonymity without internal accountability is impunity, so weakening any one destabilises the other two and the package rather than the list is what the demand is testing.", [0, 1, 2, 3]),
        (10, "Discuss why capacity building alone cannot resolve the politicisation of the Indian civil service.", "Capacity reform improves the officer while politicisation operates on the institution through posting and transfer discretion, so a competency programme that leaves the incentive structure untouched raises capability without changing the behaviour that the incentive structure rewards, and the defensible position pairs capacity investment with transfer transparency, minimum-tenure norms and appraisal consequence.", [15, 16, 7]),
        (15, "Examine the generalist and specialist debate in the Indian civil services and assess whether lateral entry and competency-based capacity building adequately address it.", "The debate is a capacity-allocation problem rather than a contest to be won, so the correct test is whether each post is matched to the competency it needs, and on that test lateral entry supplies bounded senior domain depth while competency mapping supplies the allocation logic, yet neither is adequate until assessed competency actually governs posting decisions and technical posts are staffed by qualified people.", [13, 14, 12, 18]),
        (15, "Examine the claim that civil-service legitimacy in a democracy is as much perceptual as structural.", "The claim holds because perceptual legitimacy is an analytically separate variable that can erode while structural and procedural safeguards remain formally intact, but it is incomplete without the reciprocal obligation on the political executive and without the anonymity trade-off, since perception that is managed rather than earned invites symbolic integrity-signalling in place of institutional repair.", [5, 6, 17, 3]),
        (20, "Assess Mission Karmayogi as a reform by identifying what it correctly diagnoses, what it deliberately leaves untouched, and how its success should be measured.", "The programme correctly diagnoses that India's civil-service problem has shifted from availability of talent to matching competency to role, it deliberately leaves tenure, posting and appraisal untouched because it is a capacity reform and not a structural one, and its verdict must therefore rest on competency-to-post fit, workplace application, citizen-facing outcomes, tenure stability, domain staffing and independent audit rather than on platform statistics.", [7, 8, 9, 10, 11, 18]),
        (20, "Assess the reforms needed to make institutional quality rather than individual calibre the driver of civil-service performance in a democracy.", "Institutional quality is the binding constraint because the same officers perform differently under different incentive, tenure and accountability structures, so reform must be organised by the lever it pulls across entry and composition, tenure security, performance management, capacity, accountability allocation and ethical infrastructure, while conceding openly that several of these levers conflict and must be reconciled rather than merely listed.", [19, 15, 16, 4]),
    ],
    [
        plan("Civil services as a structurally distinctive democratic institution", [0], "The three classical traits are a designed package and not an optional list of virtues.", "Set the correct analytical scope in the opening sentence of any civil-services demand."),
        plan("Political neutrality as impartiality rather than passivity", [1], "Neutrality is impartiality between governments and not the absence of expert policy input.", "Avoid the commonest conceptual error before the second paragraph of a neutrality answer."),
        plan("Permanence and anonymity as a designed pair", [2, 3], "Permanence can shelter non-performance and anonymity displaces rather than removes accountability.", "Convert two convention words into two mechanisms with a named cost each."),
        plan("The constitutional setting of Articles 309 to 312", [4], "Tenure protection is the legal setting of neutrality and the commission architecture belongs to Polity.", "Use the constitutional frame as setting rather than as content in a twenty-mark answer."),
        plan("The Doctrine of Democratic Governance", [5], "The doctrine is an analytical principle to apply and not a case-law holding to quote.", "Open a legitimacy demand with the correct character of the doctrine it names."),
        plan("Perceptual legitimacy as a separate variable", [6], "Formal soundness of structure and procedure does not guarantee perceptual legitimacy.", "Show why politicisation is a legitimacy problem before it is an efficiency problem."),
        plan("Mission Karmayogi as a change in training philosophy", [7], "The reform is a change of training philosophy and not a change of delivery mode.", "Name the current capacity reform precisely instead of describing an application."),
        plan("The six-pillar design of the national programme", [8], "The six pillars are the durable citable design and not a list of programme features.", "Give a capacity answer a structure that survives revision of framing documents."),
        plan("The four-tier institutional chain", [9], "The Commission is not the platform operator and not the sole implementing body.", "Earn a precision mark by separating standard-setting from platform operation."),
        plan("The Commission's dated establishment and working instruments", [10], "Every dated institutional fact must carry the official source and the date it was read.", "Cite a live official anchor safely by attaching its issuing body and reading date."),
        plan("Platform outputs against workplace outcomes", [11], "Dashboard totals are continuously updated outputs and must never be quoted as outcomes.", "Judge a capacity claim by application rather than by enrolment in an evaluative answer."),
        plan("Competency mapping and the posting link", [12], "A competency model that never enters the posting file changes training without changing allocation.", "Locate the untested link that decides whether the reform reaches the institution."),
        plan("Generalist, specialist and bounded lateral entry", [13, 14], "Lateral entry supplements specified senior posts and does not replace the generalist cadre.", "Argue an allocation position rather than declaring a winner in the debate."),
        plan("How neutrality erodes and what protects it", [15, 16, 17], "Displacement rather than dismissal is the operative pressure, and the obligation is reciprocal.", "Trace the politicisation chain and attach a matching protection to each stage."),
        plan("Judging capacity claims and stating reform conflicts honestly", [18, 19], "Every reform buys a risk, and routed ownership is stated rather than assumed.", "Close a twenty-mark answer with graded indicators, named conflicts and honest ownership."),
    ],
    [
        panel("Three designed traits, one package", "root-axes", [
            "NEUTRALITY -> impartial service to any elected government; not the absence of policy influence",
            "PERMANENCE -> continuity and institutional memory across changes of political government",
            "ANONYMITY -> confidential advice; the minister answers publicly for the policy outcome",
            "RULE -> the three were designed together; weakening one destabilises the other two",
        ], ["Civil services as a structurally distinctive democratic institution"]),
        panel("Neutrality: what it is and what it is not", "comparison", [
            "IS -> impartial implementation of lawful policy irrespective of personal preference",
            "IS -> the reason the same officer can serve successive, ideologically different governments",
            "IS NOT -> silence, passivity or the absence of technical and expert policy advice",
            "IS NOT -> loyalty to the government of the day rather than to the Constitution",
        ], ["Political neutrality as impartiality rather than passivity"]),
        panel("Constitutional setting card", "evidence-table", [
            "ARTICLES 309 TO 311 -> recruitment, service conditions, pleasure doctrine, dismissal safeguards",
            "ARTICLE 312 -> Parliament may create an All India Service after the Rajya Sabha resolution",
            "GOVERNANCE USE -> tenure protection is the legal basis on which neutrality rests",
            "BOUNDARY -> commission composition, appointment and removal detail is Polity-owned",
        ], ["The constitutional setting of Articles 309 to 312"]),
        panel("Three layers of civil-service legitimacy", "hierarchy", [
            "STRUCTURAL -> neutrality, permanence and anonymity built into the design",
            "PROCEDURAL -> conduct rules, vigilance machinery, disciplinary process, appraisal",
            "PERCEPTUAL -> sustained public belief that unelected discretion is exercised impartially",
            "CLAIM -> the first two can be formally sound while the third erodes independently",
        ], ["Perceptual legitimacy as a variable distinct from structure and procedure"]),
        panel("Six pillars of the capacity programme", "matrix", [
            "1 POLICY FRAMEWORK -> the reform intent and its stated shift to role-based learning",
            "2 INSTITUTIONAL FRAMEWORK -> including the Capacity Building Commission",
            "3 COMPETENCY FRAMEWORK -> behavioural, functional and domain competencies mapped to roles",
            "4 DIGITAL LEARNING FRAMEWORK -> the online platform that delivers modules at scale",
            "5 ELECTRONIC HUMAN-RESOURCE MANAGEMENT -> the personnel data spine of the reform",
            "6 MONITORING AND EVALUATION -> the pillar on which the verdict must ultimately rest",
        ], ["The six-pillar design of the national programme"]),
        panel("Institutional chain in four tiers", "process-flow", [
            "APEX GUIDANCE -> Prime Minister's Human Resources Council",
            "COORDINATION -> Cabinet Secretariat Coordination Unit",
            "STANDARDS AND PLANS -> Capacity Building Commission, Annual Capacity Building Plans",
            "PLATFORM OPERATION -> Karmayogi Bharat, the government-owned special purpose vehicle",
            "TRAP -> the Commission sets standards; it does not operate the platform",
        ], ["The four-tier institutional chain"]),
        panel("Dated capacity anchors", "labelled-system", [
            "CABINET APPROVAL -> 2 September 2020, Ministry of Personnel, Public Grievances and Pensions",
            "COMMISSION ESTABLISHED -> 1 April 2021, stated on the Commission's official website",
            "OFFICIAL PAGE READ -> 2 September 2026; repository status re-verified 13 August 2026",
            "INSTRUMENTS -> Annual Capacity Building Plans and the Karmayogi Competency Model",
        ], ["The Capacity Building Commission and its dated establishment"]),
        panel("Output against outcome", "comparison-table", [
            "OUTPUT -> enrolment, course counts, completions, certificates on a live dashboard",
            "OUTCOME -> competency-to-post fit and trained behaviour visible in work products",
            "OUTCOME -> service timelines, grievance recurrence, appeal outcomes, tenure stability",
            "DISCIPLINE -> no platform total is asserted anywhere; the number changes daily",
        ], ["Platform outputs against workplace outcomes"]),
        panel("Generalist, specialist and lateral entry", "comparison", [
            "GENERALIST -> breadth for coordination across sectors and levels of government",
            "SPECIALIST -> depth for technology, finance and climate policy complexity",
            "LATERAL ENTRY -> bounded, periodic recruitment at Joint Secretary, Director, Deputy Secretary",
            "LIMIT -> shorter contractual tenure and weaker socialisation into permanent-service norms",
        ], ["Generalist, specialist and bounded lateral entry"]),
        panel("How neutrality erodes", "causal-system", [
            "UNCONSTRAINED POSTING AND TRANSFER DISCRETION",
            "-> officers anticipate the political executive's preference before advice is asked for",
            "-> permanence protects the office, not the post: displacement is easier than dismissal",
            "-> anonymity turns asymmetric: public blame in controversy, invisibility in achievement",
            "-> perceived partiality erodes the legitimacy of unelected discretionary power",
        ], ["How neutrality erodes and what protects it"]),
        panel("Reform conflict ladder", "path-consequence", [
            "FIXED MINIMUM TENURE -> repairs arbitrary transfer; can entrench a poor performer",
            "PERFORMANCE ACCOUNTABILITY -> repairs non-performance; can become a political lever",
            "LATERAL ENTRY -> repairs domain deficit; raises representation and memory questions",
            "CONTRACTUAL MISSION-MODE STAFFING -> buys speed; weakens tenure and neutrality guarantees",
        ], ["Judging capacity claims and stating reform conflicts honestly"]),
        panel("Answer spine for a civil-services demand", "answer-spine", [
            "OPEN -> name the function being tested rather than listing duties of the service",
            "BUILD -> the three-trait package, then the legitimacy layer the stem actually engages",
            "CORRECT -> pair every reform with the risk it buys and the protection that reconciles it",
            "CLOSE -> graded verdict, outcome indicators instead of dashboard totals, stated ownership",
        ], ["Judging capacity claims and stating reform conflicts honestly"]),
    ],
    [
        "political neutrality",
        "permanence",
        "anonymity",
        "Articles 309 to 311",
        "Article 312",
        "Doctrine of Democratic Governance",
        "2 September 2020",
        "Ministry of Personnel, Public Grievances and Pensions",
        "Capacity Building Commission",
        "1 April 2021",
        "Annual Capacity Building Plans",
        "Karmayogi Bharat",
        "iGOT Karmayogi",
        "Karmayogi Competency Model",
        "lateral entry",
        "Joint Secretary",
    ],
    "Two direct Mains demands and one applied objective demand are routed to this topic across the audited ledgers, and both routed Mains stems were confirmed word for word in the locally held OCR-searchable official question papers. The audited 2018-2023 Mains ledger routes the 2020 General Studies Paper-II demand on institutional quality and civil-service reform for strengthening democracy to this Basic owner as a cross-cutting demand shared with the Polity ministries-and-departments owner, so the civil-service half is answered here and the departmental machinery half is cross-linked rather than restated. The audited 2024-2025 Mains ledger routes the 2025 General Studies Paper-I demand on the ethos of the civil service to this Basic owner. The audited 2018-2023 Prelims ledger routes the 2020 objective demand on the characteristics of bureaucracy appropriate for public policy in India here; the official 2018-2023 Prelims key is not held locally, and no option, answer letter or distractor is recorded or inferred for it. One ownership conflict is recorded openly rather than resolved by assertion: the 2024 General Studies Paper-II demand on the Doctrine of Democratic Governance and the public perception of the integrity and commitment of civil servants is discussed at length in the text of this owner, but the audited 2024-2025 ledger routes that demand to the citizen-centric-administration owner, so it is solved there and treated here only as the legitimacy half of the same demand family. No official answer key or marking scheme is held locally for any routed Mains demand, so every model solution below is an authored answer route rather than an official key.",
    [
        ("2020", "General Studies Paper-II", "Institutional quality is a crucial driver of economic performance. In this context suggest reforms in Civil Service for strengthening democracy. Answer in 150 words for 10 marks.", "Routed by the audited 2018-2023 Mains ledger to this Basic owner as a cross-cutting demand shared with the Polity ministries-and-departments owner, and confirmed word for word in the locally held official 2020 General Studies Paper-II. No official answer key is held locally, so the model solution is an authored answer route.", "Suggest reforms is a prescriptive directive, so the organising decision is to state the causal claim first and then to group reforms by the lever each one pulls, because an ungrouped list of desirable measures cannot show why any of them would work. Open with the claim the stem hands you: institutional quality rather than individual calibre is the binding constraint, because the same officers demonstrably perform differently under different incentive, tenure and accountability structures, and a reform programme that improves officers without changing the structure improves the officer and not the institution. Then take the levers in order. On entry and composition, build domain specialisation alongside generalist capability, because policy complexity in technology, finance and climate argues for depth while coordination across sectors and levels of government argues for breadth, and bounded lateral entry at Joint Secretary, Director or Deputy Secretary level supplies senior domain depth as a targeted supplement rather than as a cadre replacement. On tenure security, adopt a transparent transfer and posting process with minimum-tenure norms and written reasons for any deviation, because arbitrary transfer is the most direct route to politicisation and because permanence protects the office rather than the post, so displacement to an inconsequential post achieves what dismissal cannot. On performance management, use appraisal with meaningful differentiation, mid-career review and consequence for sustained non-performance, since permanence without appraisal consequence shelters exactly the behaviour the stem calls an institutional-quality problem. On capacity, use role-based competency building under the National Programme for Civil Services Capacity Building approved on 2 September 2020, with the Capacity Building Commission established on 1 April 2021 setting standards and Annual Capacity Building Plans, and judge it on competency-to-post fit and workplace application rather than on platform enrolment. On accountability, allocate responsibility clearly so that the anonymity convention displaces public accountability to the minister without becoming a shield against internal accountability. On ethical infrastructure, use codes, conflict-of-interest disclosure and functioning vigilance, cross-linking the Ethics owner rather than writing an ethics essay. Now supply the counterpoint that earns the analytical mark: several of these reforms conflict, because tenure security protects neutrality and can shelter a poor performer, while performance-linked accountability corrects non-performance and can itself be turned into a political lever if the assessor is political, so the reconciliation is a tenure norm paired with appraisal consequence, multi-source appraisal with published criteria and an appeal. Add the reciprocal obligation, because the political executive must equally refrain from politically motivated transfers if neutral service is to be sustainable and visible. Conclude that reforms strengthen democracy only when they change the incentive structure around posting, appraisal and accountability, and that capacity building without tenure and appraisal reform is a real improvement aimed at the wrong constraint. Assert no minimum-tenure figure, no committee recommendation, no vacancy or sanctioned-strength number and no platform statistic."),
        ("2025", "General Studies Paper-I", "The ethos of civil service in India stand for the combination of professionalism with nationalistic consciousness - Elucidate. Answer in 150 words for 10 marks.", "Routed to this Basic owner by the audited 2024-2025 Mains ledger and confirmed word for word in the locally held official 2025 General Studies Paper-I. No official answer key is held locally, so the model solution is an authored answer route.", "Elucidate asks for clarification with precision rather than for evaluation, so the highest-value move is to separate the two ideas the stem joins and then to show what makes them one ethos rather than two duties. Define professionalism first as competence in the assigned function, procedural fidelity, impartiality between governments, evidence-based advice and the specific discipline of serving a policy one did not choose and may not privately prefer. Define nationalist consciousness second as an orientation to national purpose and the public interest as against sectional, regional, communal or personal interest. Then join them: the ethos is not a rulebook but a disposition in which the civil servant's commitment runs to the constitutional order and to the citizen, and that is precisely what makes impartial service to successive and ideologically different governments coherent rather than cynical, because the officer is not serving a party in turn but a continuing constitutional purpose through whichever government the electorate returns. Ground the claim in the designed traits: political neutrality supplies the impartiality limb, permanence supplies the continuity that makes national purpose a multi-government project rather than a term-bound one, and anonymity supplies the candour that professional advice requires while displacing public credit and blame to the minister. Add the contemporary institutional expression, because an elucidation still needs an anchor: the shift from rules-based to role-based and competency-driven capacity building under the programme approved on 2 September 2020, with the Karmayogi Competency Model mapping behavioural, functional and domain competencies to roles, is an attempt to make professionalism specific to the post rather than generic to the service. Now supply the essential qualification, which is where the precision marks lie. Nationalist consciousness in a constitutional democracy means loyalty to the Constitution and to the public interest and not identification with the government of the day or with any political programme, and conflating the two is exactly how neutrality erodes, because an officer who reads national purpose as governmental preference has already surrendered the impartiality that made professional advice valuable. Note also that the two limbs can pull apart in practice, since a technically excellent officer may be indifferent to public purpose while a publicly committed officer may lack the competence to deliver it, which is why the ethos requires both together. Conclude that the ethos joins professional competence to a constitutional rather than governmental loyalty, and that this joint character is what allows the same officer to serve successive governments with integrity. Attribute no quotation to any leader or official, because none is sourced here, and assert no recruitment, training or vacancy figure."),
        ("2020", "Preliminary Examination General Studies Paper-I", "Objective demand on the characteristics of bureaucracy appropriate for public policy in India, routed to this owner by the audited 2018-2023 Prelims ledger.", "The official 2018-2023 Preliminary Examination key is not held locally, so no option, answer letter or distractor is recorded or inferred, and this card supplies only the statement-level distinctions the owner is required to support.", "The examinable content is the classical trait set and the exact boundary of each trait, so the safe method is to test every statement in such a stem against four distinctions rather than against a remembered option. First, political neutrality is impartial service to any elected government and is not the absence of technical or expert policy input, so a statement that a neutral bureaucracy takes no part in policy formulation is a boundary error rather than a description. Second, permanence is continuity in office across changes of political government, supplying institutional memory, and it is not a guarantee of individual immovability from a particular post, since displacement to an inconsequential post is administratively easy even where dismissal is hard. Third, anonymity is confidential advice with public credit and blame resting on the political executive, so it displaces public attributive accountability while internal accountability through service rules, vigilance machinery, departmental hierarchy and appraisal continues, and a statement that a bureaucracy is therefore unaccountable is a misreading of the design rather than a fact about it. Fourth, expertise in the classical model is technical competence applied to policy, and in the Indian debate it is contested between generalist breadth for coordination and specialist depth for complex sectors, so a statement that either model is the settled Indian position overstates a live allocation question. Add the constitutional setting only as setting: Articles 309 to 311 govern recruitment, service conditions, the pleasure doctrine and dismissal safeguards, and Article 312 permits Parliament to create an All India Service after the required Rajya Sabha resolution. Finally, apply the current-reform boundary, because a statement-based stem may reach for it: the programme approved on 2 September 2020 shifts training philosophy from rules-based to role-based and competency-driven learning, the Capacity Building Commission established on 1 April 2021 sets standards and Annual Capacity Building Plans, and Karmayogi Bharat operates the platform, so a statement that the Commission runs the platform, or that the reform is only a change of delivery mode, is a category error. No option is selected, no answer letter is recorded, and no platform or recruitment figure is asserted."),
    ],
    live_sources=[
        "https://cbc.gov.in/",
    ],
    current_note="One live official page was verified for this topic on 2026-09-02. The Capacity Building Commission's official website at cbc.gov.in was read successfully on that date and states that Mission Karmayogi was envisioned in the year 2020 and that the Capacity Building Commission was established on 1 April 2021 and functions at the core of Mission Karmayogi through policy frameworks that lay the foundation of capacity-building initiatives, and that the Commission emphasises capacity enhancement and upgrading of training institutes. Two further official checks were attempted on the same date and failed with an access error, namely the Press Information Bureau release page and the Department of Administrative Reforms and Public Grievances website, so no content from either was read or used, and no secondary summary has been treated as an official source. The remaining dated official elements used are those already carried by the repository owners with their status checks, namely the Cabinet approval of the National Programme for Civil Services Capacity Building on 2 September 2020 under the Ministry of Personnel, Public Grievances and Pensions, the four-tier institutional chain from the Prime Minister's Human Resources Council through the Cabinet Secretariat Coordination Unit and the Capacity Building Commission to Karmayogi Bharat, the Annual Capacity Building Plans and the Karmayogi Competency Model, and Articles 309 to 311 and Article 312 as the constitutional setting, all as re-verified by the owners on 13 August 2026. No learner, course, completion, certificate, State memorandum or accredited-institute figure is asserted, no lateral-entry vacancy, application or selection number is asserted, no minimum-tenure figure or committee recommendation on tenure, appraisal or cadre review is asserted, and no claim is made that any component of the programme implements a named Second Administrative Reforms Commission recommendation. The composition, appointment and removal of the Public Service Commissions are cross-linked to Polity, and personal probity and vigilance ethics are cross-linked to Ethics, rather than restated here.",
)


TOPIC_10 = common.topic(
    10,
    "Administrative Reforms and the Second ARC",
    "10_Administrative-Reforms-and-the-2nd-ARC",
    "10_Administrative-Reforms-and-the-2nd-ARC_Learner-V2-Complete-Topic-Package.md",
    [
        ("Administrative reform as a routing discipline rather than a quotation bank", "This topic is designed as a routing index with reform-analysis capability, which means an administrative-reform recommendation earns marks only when it is routed to a specific report, matched to a specific governance problem and qualified by its implementation status, and the single most damaging habit in this area is the decontextualised commission quotation offered as authority."),
        ("The First Administrative Reforms Commission, 1966 to 1970", "The First Administrative Reforms Commission ran from 1966 to 1970, was chaired initially by Morarji Desai and later by K. Hanumanthaiah, and examined the post-Independence public administration structure across the machinery of government, personnel administration and Centre-State relations, addressing the basic structure-building questions of a newly independent, planning-era state."),
        ("The Second Administrative Reforms Commission, constituted 2005", "The Second Administrative Reforms Commission was constituted in 2005, was chaired by M. Veerappa Moily and produced fifteen reports between 2006 and 2009 addressing the governance challenges of a liberalised, technology-enabled and rights-based India, which makes it the dominant commission reference for current General Studies Paper-II preparation."),
        ("The era contrast that answers a comparison stem", "The two commissions differ by era and by question rather than by subject alone, because the First Commission asked how to build an administrative structure while the Second asked how to make an existing structure accountable, participatory and technology-enabled, so the shift in the question is itself the answer a comparison demand is looking for, and neither was fully implemented for different reasons, capacity in the first case and incentives and federal structure in the second."),
        ("The nodal department and the limits of a coordinating role", "The Department of Administrative Reforms and Public Grievances is the nodal Union department that tracks and coordinates follow-up on commission recommendations across ministries and departments and serves as their continuing institutional memory, but its role is coordinative and advisory rather than directive, so it cannot compel a line ministry or a State government to implement anything."),
        ("Recommendation against enacted reform", "A commission recommendation is a dated analytical reform proposal and becomes binding only when separately enacted as law, notified as a rule or order, or adopted as administrative practice, so any specific recommendation must be described as proposed, partially implemented or adopted rather than assumed to be current law, and the status language itself is where the mark lies."),
        ("The five-status ladder", "Every commission citation should carry one of five statuses with the evidence each requires, namely proposed on the report text alone, accepted in principle on a recorded government decision with no operative instrument, notified or enacted where an Act, rule, order or scheme instrument exists, operational where institutions, staff, budget and procedure actually function, and evaluated where independent evidence exists on quality and outcome."),
        ("Using the ladder as a sentence rather than a table", "The ladder earns its marks when it is written as a single sentence inside the answer, of the form that the commission recommended a measure, that the government accepted it in principle, that the operative instrument is a named later Act or rule, and that whether it functions as intended has not been independently evaluated, because that one sentence demonstrates source discipline and evaluative honesty together."),
        ("The fifteen reports as a routing table", "The fifteen reports of the Second Commission are, in order, Right to Information as the master key to good governance, Unlocking Human Capital on entitlements and governance, Crisis Management, Ethics in Governance, Public Order, Local Governance, Capacity Building for Conflict Resolution, Combating Terrorism, Social Capital as a shared destiny, Refurbishing of Personnel Administration, Promoting e-Governance, Citizen-Centric Administration, the Organisational Structure of the Government of India, Strengthening Financial Management Systems, and State and District Administration."),
        ("The four reports that sit mainly outside General Studies Paper-II", "Reports three, five, seven and eight, on crisis management, public order, capacity building for conflict resolution and combating terrorism, sit mainly in the General Studies Paper-III internal-security and disaster-management space, so they should be cross-referenced rather than forced into a Paper-II governance answer, and treating all fifteen reports as equally central to Paper-II is a standard error."),
        ("Report ten and the personnel-administration route", "Report ten, Refurbishing of Personnel Administration and titled Scaling New Heights, is the personnel-administration route and its analytical depth belongs to the civil-services owner, where neutrality, capacity and performance are developed; its recommendations touching performance-linked promotion and cadre restructuring illustrate the politically contested end of the implementation spectrum where adoption has been much more partial."),
        ("Reports six and fifteen and the local-governance route", "Report six on Local Governance and report fifteen on State and District Administration jointly ground the local-governance and district-delivery route, where the three functional legs of devolution, activity mapping and parastatal encroachment are developed, and both address subjects requiring State action, which is why their non-implementation is frequently a federal-capacity fact rather than a Union-indifference fact."),
        ("Reports eleven and twelve and the service-delivery route", "Report eleven, Promoting e-Governance and titled The Smart Way Forward, and report twelve, Citizen-Centric Administration and titled The Heart of Governance, ground the e-governance and citizen-centric service-delivery routes, where process re-engineering before digitisation and the service-standard, grievance and capability architecture are developed in their own owners rather than restated here."),
        ("The remaining high-weight reports and their destinations", "Report one on the Right to Information routes to the transparency and accountability owner for proactive disclosure and the accountability ecosystem, report two on Unlocking Human Capital routes to policy design and implementation for entitlement design, report four on Ethics in Governance routes to institutional accountability owners while personal probity is owned by Ethics, report nine on Social Capital routes to the civil-society owner for bonding, bridging and linking, report thirteen on the Organisational Structure of the Government of India routes to machinery and coordination with a Polity cross-link, and report fourteen on Strengthening Financial Management Systems routes to public finance and expenditure control."),
        ("The acceptance-to-outcome causal chain", "Reform recommendations move through a chain in which diagnosis identifies a structural problem, acceptance occurs report by report and recommendation by recommendation with the failure mode of acceptance in principle without an instrument, an instrument in the form of an Act, rule, order or scheme must then be separately created, a federal step is required where the subject needs State action, capacity in staff, money, systems and skills must exist to operate the instrument, and incentives finally determine adoption, so partial and often unattributed adoption is the normal outcome."),
        ("The federal step as the most under-used explanation", "The most under-used and most rewarded explanation of partial implementation is federal rather than political, because several of the highest-value reports, including Local Governance, State and District Administration and much of Refurbishing of Personnel Administration, address subjects requiring State legislative or administrative action, so a Union acceptance cannot deliver them and uneven national adoption is a structural consequence of the federal division rather than evidence of Union indifference."),
        ("The attribution problem and the most common fabricated claim", "Where a later reform resembles a commission proposal the causal link is usually unprovable, so no answer should claim that a named current programme implements a named report without a sourced acceptance or decision trail, and asserting that a capacity-building programme implements the personnel-administration report or that State service-guarantee statutes implement the citizen-centric-administration report is the single most common fabricated claim in this area, because thematic similarity is not implementation evidence."),
        ("The datedness objection and its reply", "The datedness objection is that a diagnosis produced between 2006 and 2009 predates population-scale digital public infrastructure, the current data-protection framework, statutory service guarantees at scale and post-goods-and-services-tax fiscal federalism, and the correct reply is that the commission's analytical categories of capacity, accountability, citizen-centricity and decentralisation have aged far better than its specific prescriptions, so the answer must say which of the two it is using."),
        ("Comprehensiveness against implementability, and commission fatigue", "A fifteen-report programme is analytically complete and politically indigestible while incremental reform is implementable and incoherent, and repeated commissions can substitute for action by converting reform into a documented intention, which is why the political-economy explanation of failure is that recommendations reducing discretion or reallocating authority face concentrated resistance against diffuse benefit rather than that they fail on merit."),
        ("Stakeholder variation and honest question ownership", "Adoption varies by actor, since a Union ministry accepts what fits its existing mandate and resists what reallocates it, a State government must act on the local-governance, personnel and district-administration reports and has its own political economy, the nodal department tracks and coordinates without power to compel, civil-service associations hold an organised interest in tenure, cadre and promotion rules, and the citizen is a diffuse beneficiary of accountability reform with weak organisation relative to the concentrated interests reform touches; on ownership, the audited 2018-2023 Prelims ledger routes one objective demand on the Administrative Reforms Commission and the creation of a personnel department to this owner, no direct Mains demand is routed here, and the commission-grounded Mains demands are routed to their destination owners."),
    ],
    [
        "Do not present a commission recommendation as automatically enacted law or as current administrative practice.",
        "Do not assert a percentage of recommendations accepted, implemented or rejected.",
        "Do not assert a specific recommendation number, paragraph or the date on which a recommendation was implemented.",
        "Do not claim that any named current programme implements a named commission report without a sourced acceptance or decision trail.",
        "Do not treat thematic similarity between a later reform and a report as evidence of implementation.",
        "Do not assert the composition of either Commission beyond the chairs named in the owner.",
        "Do not assert a First Administrative Reforms Commission report count or a report title that is not held in the owner.",
        "Do not describe the two Commissions as having covered identical subject matter across identical eras.",
        "Do not treat all fifteen reports as equally central to General Studies Paper-II.",
        "Do not force the crisis-management, public-order, conflict-resolution or counter-terrorism reports into a Paper-II governance answer.",
        "Do not describe the nodal department as able to compel a ministry or a State to implement a recommendation.",
        "Do not write the commission established, the commission mandated or under the commission; write recommended, accepted in principle, notified, operational or unevaluated.",
        "Do not reproduce full report content here when the analytical depth is owned by a destination topic file.",
        "Do not explain non-implementation of a State-subject recommendation as Union indifference when it is a federal-capacity fact.",
        "Do not infer effectiveness from the existence of a constituted body without evidence that it is operational.",
        "Do not claim that any Mains demand is directly owned here when the audited ledgers route only one objective demand to this owner.",
    ],
    [
        (10, "Distinguish the focus areas of the First and Second Administrative Reforms Commissions.", "The distinction is one of era and of question rather than of subject list, because the First Commission asked how to build an administrative structure for a newly independent planning-era state while the Second asked how to make an existing structure accountable, participatory and technology-enabled, and the reasons for incomplete implementation differ correspondingly.", [1, 2, 3, 17]),
        (10, "Explain why the implementation status of an administrative-reform recommendation must be stated before the recommendation is used in an answer.", "Status discipline is the whole examinable skill in this area, because a proposal presented as practice converts a dated analytical recommendation into a false statement of current law, and the five-status ladder written as a single sentence demonstrates source discipline and evaluative honesty in the same breath.", [5, 6, 7, 16]),
        (15, "Examine why the recommendations of the Second Administrative Reforms Commission have been implemented selectively rather than uniformly.", "Selective implementation is a structural outcome of the acceptance, instrument, federal, capacity and incentive stages of the reform chain rather than a verdict on the quality of the diagnosis, and the federal step in particular explains why the highest-value reports on local governance, district administration and personnel administration remain the least implemented.", [14, 15, 4, 18]),
        (15, "Examine the continuing relevance of the Second Administrative Reforms Commission for current Indian governance reform.", "The reports remain indispensable as a diagnostic map and unsafe as a statement of current practice, because their analytical categories have aged far better than their specific prescriptions, so the honest use cites the report for the problem and the current instrument for the answer while conceding what has changed since 2009.", [17, 0, 8, 12]),
        (20, "Assess the fifteen reports of the Second Administrative Reforms Commission as a diagnostic architecture rather than as a list of recommendations.", "Read as an architecture, the reports map a complete governance problem set from information rights and entitlements through ethics, local governance, social capital, personnel, technology, citizen-centricity, organisational structure and financial management, which is why routing each report to its destination owner and attaching an honest status label produces a stronger answer than reproducing report content.", [8, 9, 10, 11, 12, 13]),
        (20, "Assess why expert-commission-driven administrative reform in India delivers rigorous diagnosis and uneven adoption.", "The commission model supplies evidence-based diagnosis without enforcement power, so its impact is contingent on acceptance, instrument creation, federal action, capacity and above all on the distribution of costs, since recommendations that reduce discretion or reallocate authority face concentrated resistance and diffuse benefit while a coordinating department cannot compel anyone.", [19, 14, 18, 4]),
    ],
    [
        plan("Administrative reform as a routing discipline", [0], "A decontextualised commission quotation offered as authority earns nothing.", "Set the controlling discipline before writing a single recommendation into the answer."),
        plan("The First Administrative Reforms Commission", [1], "The chairs and the period are safe; no report count or title beyond the owner is safe.", "Answer a comparison demand with a dated, correctly attributed first limb."),
        plan("The Second Administrative Reforms Commission", [2], "Constitution year, chair and the fifteen reports between 2006 and 2009 are the safe anchors.", "Anchor any current governance-reform answer in a correctly dated source commission."),
        plan("The era contrast that answers a comparison stem", [3], "The two commissions differ by question and era, not merely by subject coverage.", "Convert a distinguish directive into an analytical contrast rather than two lists."),
        plan("The nodal department and the limits of coordination", [4], "A coordinating department cannot compel a line ministry or a State government.", "Explain non-implementation institutionally instead of attributing it to indifference."),
        plan("Recommendation against enacted reform", [5], "A recommendation becomes binding only through separate enactment, notification or adopted practice.", "Protect every commission citation from becoming a false statement of current law."),
        plan("The five-status ladder", [6], "Each status has its own evidence requirement and none may be assumed from the one below.", "Attach a defensible status label to every recommendation an answer uses."),
        plan("Writing the ladder as a sentence", [7], "The ladder earns marks inside the prose, not as a reproduced table.", "Demonstrate source discipline and evaluative honesty in one written sentence."),
        plan("The fifteen reports as a routing table", [8], "The titles are safe; recommendation numbers, paragraphs and adoption dates are not.", "Name the underlying report by title to show precise source knowledge."),
        plan("The four reports outside General Studies Paper-II", [9], "Crisis management, public order, conflict resolution and terrorism belong mainly to Paper-III.", "Avoid forcing an internal-security report into a governance answer."),
        plan("The personnel and local-governance routes", [10, 11], "Both routes need State action, which is why their adoption is the most partial.", "Route a personnel or local-governance stem to the owner that holds its depth."),
        plan("The service-delivery and remaining routes", [12, 13], "Report content belongs to the destination owner; restating it here multiplies misattribution risk.", "Attribute a question to its underlying report and answer from the destination file."),
        plan("The acceptance-to-outcome chain and the federal step", [14, 15], "A Union acceptance cannot deliver a State-subject recommendation.", "Explain uneven adoption with the strongest available structural argument."),
        plan("The attribution problem and the datedness objection", [16, 17], "Thematic similarity is not implementation evidence, and prescriptions age faster than categories.", "Survive the two hardest counters an examiner can put to a commission answer."),
        plan("Political economy, stakeholders and honest ownership", [18, 19], "Recommendations fail at the instrument and incentive stages rather than at the diagnosis stage.", "Close with a political-economy verdict and a stated ledger routing."),
    ],
    [
        panel("Two commissions, two questions", "comparison", [
            "FIRST COMMISSION -> 1966 to 1970; Morarji Desai, later K. Hanumanthaiah",
            "QUESTION ASKED -> how to build an administrative structure for a planning-era state",
            "SECOND COMMISSION -> constituted 2005; M. Veerappa Moily; fifteen reports, 2006 to 2009",
            "QUESTION ASKED -> how to make an existing structure accountable and technology-enabled",
        ], ["The era contrast that answers a comparison stem"]),
        panel("Five-status ladder", "hierarchy", [
            "PROPOSED -> the report text alone; the commonest error is presenting this as practice",
            "ACCEPTED IN PRINCIPLE -> a recorded decision with no operative instrument",
            "NOTIFIED OR ENACTED -> an Act, rule, order or scheme instrument exists",
            "OPERATIONAL -> institutions, staff, budget and procedure are actually functioning",
            "EVALUATED -> independent evidence exists on implementation quality and outcome",
        ], ["The five-status ladder"]),
        panel("The ladder written as one sentence", "answer-spine", [
            "STEP 1 -> the commission recommended the measure",
            "STEP 2 -> the government accepted it in principle",
            "STEP 3 -> the operative instrument is the named later Act, rule or scheme",
            "STEP 4 -> whether it functions as intended has not been independently evaluated",
        ], ["Writing the ladder as a sentence"]),
        panel("Routing table, reports one to eight", "matrix", [
            "1 RIGHT TO INFORMATION -> transparency and accountability owner",
            "2 UNLOCKING HUMAN CAPITAL -> policy design and implementation owner",
            "3 CRISIS MANAGEMENT -> Paper-III disaster-management space; cross-reference only",
            "4 ETHICS IN GOVERNANCE -> institutional accountability owners; personal probity is Ethics",
            "5 PUBLIC ORDER -> Paper-III internal-security space; cross-reference only",
            "6 LOCAL GOVERNANCE -> local governance and service delivery owner",
            "7 CAPACITY BUILDING FOR CONFLICT RESOLUTION -> cross-reference only",
            "8 COMBATING TERRORISM -> Paper-III internal-security space; cross-reference only",
        ], ["The fifteen reports as a routing table"]),
        panel("Routing table, reports nine to fifteen", "matrix", [
            "9 SOCIAL CAPITAL -> civil-society, self-help-group and non-governmental-organisation owner",
            "10 REFURBISHING OF PERSONNEL ADMINISTRATION -> civil services and capacity owner",
            "11 PROMOTING E-GOVERNANCE -> e-governance models and user-centricity owner",
            "12 CITIZEN-CENTRIC ADMINISTRATION -> citizen-centric administration owner",
            "13 ORGANISATIONAL STRUCTURE OF GOVERNMENT -> machinery and coordination; Polity cross-link",
            "14 STRENGTHENING FINANCIAL MANAGEMENT -> public finance and service-delivery tools owner",
            "15 STATE AND DISTRICT ADMINISTRATION -> local governance and district delivery owner",
        ], ["The fifteen reports as a routing table"]),
        panel("Nodal department card", "evidence-table", [
            "WHAT IT IS -> the nodal Union department for tracking and coordinating follow-up",
            "WHAT IT DOES -> circulates recommendations, holds institutional memory, coordinates ministries",
            "WHAT IT CANNOT DO -> compel a line ministry or a State government to implement anything",
            "CONSEQUENCE -> non-implementation is often an institutional fact, not an attitude",
        ], ["The nodal department and the limits of coordination"]),
        panel("Diagnosis to outcome chain", "causal-system", [
            "DIAGNOSIS -> the commission identifies a structural problem",
            "-> ACCEPTANCE, report by report; failure mode is acceptance in principle with no instrument",
            "-> INSTRUMENT: an Act, rule, order or scheme must be separately created",
            "-> FEDERAL STEP: State subjects need State action; a Union acceptance cannot deliver them",
            "-> CAPACITY, then INCENTIVE: who loses discretion, authority or rent?",
            "-> OUTCOME: partial adoption, often unattributed and frequently unevaluated",
        ], ["The acceptance-to-outcome chain and the federal step"]),
        panel("The federal explanation", "labelled-system", [
            "STATE-ACTION REPORTS -> Local Governance; State and District Administration",
            "PARTLY STATE-ACTION -> much of Refurbishing of Personnel Administration",
            "MECHANISM -> Union acceptance cannot legislate or staff a State subject",
            "USE -> explains uneven national adoption without asserting Union indifference",
        ], ["The acceptance-to-outcome chain and the federal step"]),
        panel("The attribution trap", "dialectic", [
            "TEMPTATION -> a later reform resembles a report, so the answer claims implementation",
            "REALITY -> causation is usually unprovable without a sourced acceptance or decision trail",
            "NAMED RISK -> capacity programmes and State service-guarantee statutes are the usual claims",
            "CORRECT MOVE -> state thematic continuity, and say that the linkage is not verified",
        ], ["The attribution problem and the datedness objection"]),
        panel("Datedness objection and reply", "dialectic", [
            "OBJECTION -> a 2006 to 2009 diagnosis predates population-scale digital infrastructure",
            "OBJECTION -> it also predates the current data-protection framework and later fiscal design",
            "REPLY -> the analytical categories have aged far better than the specific prescriptions",
            "DISCIPLINE -> say which of the two the answer is actually using",
        ], ["The attribution problem and the datedness objection"]),
        panel("Political economy of adoption", "path-consequence", [
            "COMPREHENSIVE PROGRAMME -> analytically complete and politically indigestible",
            "INCREMENTAL REFORM -> implementable and incoherent across the system",
            "COMMISSION FATIGUE -> repeated commissions convert reform into a documented intention",
            "COST DISTRIBUTION -> concentrated resistance against diffuse benefit decides adoption",
        ], ["Political economy, stakeholders and honest ownership"]),
        panel("Answer spine for a reform demand", "answer-spine", [
            "OPEN -> name the report by title and the governance problem it diagnoses",
            "BUILD -> route the theme to its destination owner and take the evidence from there",
            "CORRECT -> attach a status label, then give the federal or incentive reason for the gap",
            "CLOSE -> graded verdict on continuing relevance with the datedness reply stated",
        ], ["Political economy, stakeholders and honest ownership"]),
    ],
    [
        "First Administrative Reforms Commission",
        "1966",
        "Morarji Desai",
        "K. Hanumanthaiah",
        "Second Administrative Reforms Commission",
        "2005",
        "M. Veerappa Moily",
        "fifteen reports",
        "2006 and 2009",
        "Department of Administrative Reforms and Public Grievances",
        "Right to Information",
        "Ethics in Governance",
        "Local Governance",
        "Refurbishing of Personnel Administration",
        "Promoting e-Governance",
        "Citizen-Centric Administration",
        "State and District Administration",
        "accepted in principle",
    ],
    "One applied objective demand is routed to this topic across the audited ledgers and no direct Mains demand is routed here, which is stated openly rather than disguised. The audited 2018-2023 Prelims ledger routes the 2021 objective demand on the Administrative Reforms Commission and the creation of a personnel department to this Basic owner; the official 2018-2023 Preliminary Examination key is not held locally, so no option, answer letter or distractor is recorded or inferred for it, and no year of departmental creation and no recommendation number is asserted, because no official source for that step is held locally. The audited Mains ledgers route the commission-grounded Mains demands to their destination owners rather than to this file, since local-body functionality and grassroots decentralisation are routed to the local-governance owner, the Citizens' Charter and public-perception demands are routed to the citizen-centric-administration owner, the civil-service reform and ethos demands are routed to the civil-services owner, and the competition-regulator demand is routed to the regulatory-governance owner, so this owner supplies the routing, status and political-economy discipline that each of those answers uses rather than claiming their ownership. No official answer key or marking scheme is held locally for any routed demand, so the model solution below is an authored answer route rather than an official key.",
    [
        ("2021", "Preliminary Examination General Studies Paper-I", "Objective demand on the Administrative Reforms Commission and the creation of a personnel department, routed to this owner by the audited 2018-2023 Prelims ledger.", "The official 2018-2023 Preliminary Examination key is not held locally, so no option, answer letter or distractor is recorded or inferred, and no year of departmental creation and no recommendation number is asserted because no official source for that step is held locally.", "The examinable content is the First Commission's place in India's administrative history and the institutional lineage of the personnel function, so the safe method is to answer from remit and period rather than from a remembered recommendation. State what is held: the First Administrative Reforms Commission ran from 1966 to 1970, was chaired initially by Morarji Desai and later by K. Hanumanthaiah, and examined the machinery of government, personnel administration and Centre-State relations, so its work belongs to the period in which the Union's personnel function was institutionally consolidated. Then apply the discipline that makes an unfamiliar statement testable. First, distinguish the two Commissions by era and question, since the First addressed the structure-building problems of a newly independent planning-era state while the Second, constituted in 2005 under M. Veerappa Moily, produced fifteen reports between 2006 and 2009 on accountability, citizen-centricity, technology and capacity, so any statement that treats the two as covering identical subject matter is an era error. Second, apply the recommendation-against-implementation distinction, because a statement asserting that a Commission created, established or mandated a department confuses a recommendation with an instrument; a Commission recommends, and creation requires a separate executive, legislative or rule-making act. Third, apply the coordination limit, since the Department of Administrative Reforms and Public Grievances tracks and coordinates follow-up and holds institutional memory but cannot compel a ministry or a State to act, so a statement giving it directive power is a design error. Fourth, apply the five-status ladder, because a statement claiming that a recommendation is in force needs evidence of an operative instrument and not merely of acceptance in principle. Finally, note the federal boundary, since recommendations touching State cadres and State administration require State action, so a statement asserting uniform national implementation of a personnel recommendation is unsafe on its face. No option is selected, no answer letter is recorded, no year of departmental creation is asserted, and no recommendation number or percentage of accepted recommendations is inferred."),
    ],
    live_sources=[],
    current_note="No new live official item was verified for this topic on 2026-09-02. Two official checks were attempted on that date and both failed with an access error, namely the Press Information Bureau release page and the Department of Administrative Reforms and Public Grievances website, so no primary official page could be read for this topic and no secondary summary has been treated as an official source or imported. The only dated elements used are those already carried by the repository owners with their status checks, namely the First Administrative Reforms Commission of 1966 to 1970 chaired initially by Morarji Desai and later by K. Hanumanthaiah, the Second Administrative Reforms Commission constituted in 2005 under M. Veerappa Moily with fifteen reports between 2006 and 2009, the report titles as listed by the owners, and the nodal role of the Department of Administrative Reforms and Public Grievances as the institutional home for commission material and follow-up, as checked by the owners on 21 July 2026. No percentage of recommendations accepted or implemented is asserted, no recommendation number, paragraph or implementation date is asserted, no composition of either Commission beyond the named chairs is asserted, and no claim is made that any named current programme implements a named report, because thematic similarity is not implementation evidence. Implementation status is deliberately described report by report and recommendation by recommendation rather than generalised across all fifteen reports.",
)
