"""Authored content data for Governance learner-v2 Topics 01-02."""

from __future__ import annotations

import generate_governance_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_01 = common.topic(
    1,
    "Good Governance: Concepts and Frameworks",
    "01_Good-Governance-Concepts-and-Frameworks",
    "01_Good-Governance-Concepts-and-Frameworks_Learner-V2-Complete-Topic-Package.md",
    [
        ("Government as a formal authority set", "Government is the formal, constitutionally mandated set of institutions - legislature, executive and judiciary - that holds legitimate public authority, and it is only one actor inside governance rather than the whole of it."),
        ("Governance as a wider decision process", "Governance is the wider process by which state and non-state actors, including the market, civil society and citizens, together make, implement and enforce collective decisions, so a governance answer must name which actor holds the duty before it evaluates performance."),
        ("Good governance as a normative standard", "Good governance is governance judged against normative standards - rule of law, transparency, accountability, participation, responsiveness, equity, effectiveness and consensus orientation - and the Second Administrative Reforms Commission frames it as public institutions conducting public affairs and managing public resources largely free of abuse and corruption with due regard for the rule of law."),
        ("Worldwide Governance Indicators: six dimensions", "The World Bank Worldwide Governance Indicators use six named dimensions - Voice and Accountability, Political Stability and Absence of Violence, Government Effectiveness, Regulatory Quality, Rule of Law and Control of Corruption - and countries are scored on each dimension separately rather than on one undifferentiated total."),
        ("The perception basis of the Worldwide Governance Indicators", "The Worldwide Governance Indicators are built substantially from aggregated perception surveys and expert assessments rather than solely from administrative statistics, so a score reports perceived quality with a margin of error and an administrative improvement can move ahead of, or lag behind, the perception it is supposed to reflect."),
        ("UNDP principles as a checklist, not an index", "The UNDP governance principles - participation, rule of law, transparency, responsiveness, consensus orientation, equity and inclusiveness, effectiveness and efficiency, accountability and strategic vision - form a normative checklist that supplies process vocabulary and cannot rank anything, so treating them as a scoring system is a category error."),
        ("The Second ARC frame and the absence of one governance statute", "The Second Administrative Reforms Commission, constituted in 2005 and reporting through fifteen reports, supplies the India-specific institutional-reform frame, and India deliberately enforces the good-governance standard through a patchwork of sector laws such as the Right to Information Act, state right-to-service Acts and Section 17 of the Mahatma Gandhi National Rural Employment Guarantee Act rather than through a single overarching good-governance statute."),
        ("DARPG as reformer and measurer in one department", "The Department of Administrative Reforms and Public Grievances functions under the Ministry of Personnel, Public Grievances and Pensions and is simultaneously the nodal department for administrative reform, Sevottam, the Centralised Public Grievance Redress and Monitoring System and Second ARC follow-up, and the nodal department for good-governance measurement, so agenda-setting and self-assessment sit inside one department."),
        ("Good Governance Day", "Good Governance Day has been observed on 25 December every year since 2014, marking the birth anniversary of former Prime Minister Atal Bihari Vajpayee, and it promotes accountability, transparency and citizen-centric administration without being a measurement instrument."),
        ("Good Governance Index launch and latest located edition", "The Good Governance Index was launched by the Department of Administrative Reforms and Public Grievances on 25 December 2019 as a composite diagnostic tool assessing state and union-territory performance across ten sectors, and the latest completed national edition located on that department as of 13 August 2026 is the Good Governance Index 2020-21, released on 25 December 2021."),
        ("Edition-specific Good Governance Index grouping", "The Good Governance Index comparison grouping is edition-specific: the 2019 edition used three groups while the 2020-21 edition used four - Other States Group A, Other States Group B, North-East and Hill States, and Union Territories - so any grouping claim must carry its edition year, and the Gujarat top-rank fact belongs specifically to the 2020-21 edition."),
        ("The withdrawn Good Governance Index 2025 claim", "A previous audit introduced an unsupported claim that a third Good Governance Index edition described as 2025 had been released, no departmental report or Press Information Bureau release establishing that edition was located, and the correction record of 13 August 2026 withdraws the claim explicitly, so no post-2021 national edition, rank, score, top performer or indicator count may be asserted."),
        ("The District Good Governance Index is not a national edition", "The District Good Governance Index is a separate sub-national exercise developed for particular states and union territories, and it neither supersedes nor substitutes for a released national Good Governance Index edition, so converting a district index, a workshop, a proposed cycle or a Good Governance Day event into a released national edition is a factual error."),
        ("The Rule of Law Index attribution", "The Rule of Law Index is published by the World Justice Project and not by the World Bank, and this attribution is the exact objective distinction routed by the audited 2018 Preliminary examination ledger to this owner, so the index must never be folded into the World Bank Worldwide Governance Indicators family."),
        ("Four measurement instruments at four different scales", "The Worldwide Governance Indicators measure cross-country comparison, the Good Governance Index measures state and union-territory sectoral governance, the National e-Governance Service Delivery Assessment measures end-service delivery depth at portal level and the Panchayati Raj Ministry Devolution Index measures panchayat devolution only, so treating the four as interchangeable governance rankings is the discrimination failure that costs marks."),
        ("Norms to instruments: legality, transparency and answerability", "Rule of law is anchored in Article 14 non-arbitrariness and reasoned quasi-judicial orders whose discipline is uneven below the regulator tier, transparency in Section 4 proactive disclosure under the Right to Information Act, 2005 whose compliance is not independently audited across authorities, and accountability in the Comptroller and Auditor General under Articles 148 to 151, the Lokpal and Lokayuktas Act, 2013 and the Central Vigilance Commission Act, 2003, which supply three different remedies and none of which is a general grievance authority."),
        ("Norms to instruments: participation, responsiveness, equity and effectiveness", "Participation is anchored in Section 17 Gram Sabha social audit under the Mahatma Gandhi National Rural Employment Guarantee Act and in the Pre-Legislative Consultation Policy of 2014, which is executive rather than statutory and whose comments are not binding; responsiveness in state right-to-service Acts beginning with Madhya Pradesh in 2010 and the twenty-one-day benchmark of the Centralised Public Grievance Redress and Monitoring System stated in departmental guidelines of August 2024, which cover only notified services and remain administrative rather than adjudicatory; equity in direct benefit transfer targeting, where authentication failure converts an inclusion tool into an exclusion risk; and effectiveness in the Output-Outcome Monitoring Framework and the Development Monitoring and Evaluation Office, where output reporting still dominates."),
        ("The seven-stage chain from norm to outcome", "A norm becomes an outcome only by passing seven stages - legal form, identified duty-holding institution, procedure with timeline, officer, appeal and penalty, administrative capacity, citizen-side access and cost, correctable remedy, and counted feedback - and naming the stage at which a named instrument stops converts a generic complaint about poor governance into a diagnosis."),
        ("Five tests for any governance index", "Any governance index must be tested on indicator validity, data comparability where the ranked entity self-reports, the balance between output and realised outcome, federal and contextual adjustment for states of different size, base level and subject responsibility, and consequence, because an index whose poor score triggers no corrective process measures governance without improving it."),
        ("Counter-arguments and the behavioural-insights anchor", "Four standing objections must be answered rather than ignored - the vagueness objection that bundled values such as speed against consultation conflict, the measurement objection that perception indices can encode elite priors, the conditionality objection that the agenda entered through donor conditionality, answered by tracing Indian norms to the Constitution and to domestic statutes, and the capacity objection that a further charter changes nothing at the capacity stage - while the Economic Survey 2018-19 Chapter 2 supplies the official behavioural-insights anchor in which a nudge changes the choice architecture without removing formal choice and cannot cure missing supply, unequal power, weak enforcement or a wrongly designed entitlement."),
    ],
    [
        "Do not treat government and governance as interchangeable terms in the opening sentence of an answer.",
        "Do not reduce good governance to corruption control when control of corruption is one dimension among six.",
        "Do not present the UNDP principles as a scoring system capable of ranking states or countries.",
        "Do not quote a Worldwide Governance Indicators score as a direct outcome measurement rather than an aggregated perception estimate.",
        "Do not assert that a national Good Governance Index edition later than the 2020-21 edition has been released.",
        "Do not quote any Good Governance Index rank, score, indicator count or top performer without naming the edition year.",
        "Do not describe the Good Governance Index as an annual or reliably biennial series.",
        "Do not carry the Gujarat top-rank fact across editions when it belongs specifically to the 2020-21 edition.",
        "Do not treat the District Good Governance Index as a later national Good Governance Index edition.",
        "Do not attribute the Rule of Law Index to the World Bank when the World Justice Project publishes it.",
        "Do not treat the Worldwide Governance Indicators, the Good Governance Index, the National e-Governance Service Delivery Assessment and the Devolution Index as interchangeable rankings.",
        "Do not describe Second Administrative Reforms Commission recommendations as enacted binding law.",
        "Do not present the Pre-Legislative Consultation Policy of 2014 as a statute or its comments as binding.",
        "Do not treat the Comptroller and Auditor General, the Lokpal or the Central Vigilance Commission as a general grievance-redress authority.",
        "Do not claim that a right-to-service Act covers services that a state has not notified under it.",
        "Do not present a nudge as capable of curing missing supply, unequal power or a wrongly designed entitlement.",
    ],
    [
        (10, "Distinguish government from governance and explain why the distinction changes the evaluation of a public institution in India.", "Government names the institutions, governance names the process and good governance names the standard, so an evaluation that begins by identifying the duty-holder and the binding form reaches a defensible verdict while one that begins with adjectives about the state does not.", [0, 1, 2]),
        (10, "Explain why the Worldwide Governance Indicators and the UNDP governance principles cannot be used interchangeably.", "One is an aggregated perception-based comparative index with six named dimensions and the other is a normative process checklist that cannot rank anything, so an answer that merges them has already failed the discrimination the examiner is testing.", [3, 4, 5]),
        (15, "Critically examine the Good Governance Index as a tool for measuring governance performance across Indian states.", "As a sector-wise diagnostic that forces states to confront specific weakness the index is defensible, but as a summary judgment on governance quality it over-claims, and its value depends on whether an edition-dated poor score triggers correction rather than contestation.", [9, 10, 11, 18]),
        (15, "Examine the claim that India's good-governance deficits lie in enforceable conversion mechanisms rather than in the absence of norms.", "India has not lacked good-governance norms but enforceable conversion mechanisms, which is why the reforms that supplied an identifiable duty-holder and a remedy have moved outcomes further than any additional charter of principles.", [6, 15, 16, 17]),
        (20, "Assess whether the good-governance agenda is a universal standard or an externally imposed development discourse, using Indian institutional evidence.", "The core of the standard - legality, answerability and non-arbitrariness - is universal while its instruments are contextual, and the Indian route is traceable to constitutional guarantees and domestic statutes rather than to donor conditionality, so the conditionality objection is answerable without abandoning the norms.", [19, 2, 6, 16]),
        (20, "Assess how far governance measurement in India can be trusted to guide reform, given the number and variety of instruments in use.", "Measurement guides reform only where the instrument, the scale and the object are stated together and where the index carries a corrective loop, because four instruments measuring four different objects at four different scales cannot be aggregated into a single verdict on governance quality.", [14, 4, 18, 13]),
    ],
    [
        plan("Government, governance and the normative test", [0, 1, 2], "The three terms are not synonyms and the third is a standard applied to the second, so an answer that uses them interchangeably has conceded the distinction the examiner is testing.", "Open a governance answer by separating the institution set, the decision process and the normative standard before any evaluation begins."),
        plan("The Worldwide Governance Indicators frame", [3, 4], "The dimensions are scored separately and rest substantially on aggregated perception with a margin of error, so a score is not a direct outcome measurement.", "Cite a comparative measurement frame with its dimension names and its methodological limit attached."),
        plan("UNDP principles as a process checklist", [5], "The checklist supplies vocabulary and cannot rank, so it must not be presented as an index.", "Supply the process vocabulary a normative-standard demand expects without pretending to a score."),
        plan("The Second ARC frame and the patchwork of sector laws", [6], "Commission recommendations are dated reform proposals rather than enacted law, and the statutory patchwork is a deliberate design choice rather than an omission.", "Provide the India-specific institutional-reform frame that converts an international standard into a domestic reform route."),
        plan("DARPG as reformer and measurer", [7], "One department holding both the reform agenda and its own measurement concentrates agenda-setting and self-assessment, which is an analytical point rather than an allegation.", "Name the nodal institution precisely and flag the structural feature that a critical directive rewards."),
        plan("Good Governance Day as a dated institutional anchor", [8], "The day is an observance rather than a measurement instrument, so it may not be substituted for a released index edition.", "Retain a dated institutional anchor that a Preliminary statement question can test directly."),
        plan("The Good Governance Index and its located edition", [9], "Only a released edition may be used, and the latest completed national edition located is dated rather than assumed to be current.", "Attach an edition year to every index claim so that a correct instinct is not converted into a factual error."),
        plan("Reading Good Governance Index groupings by edition", [10], "The grouping changed between the 2019 and 2020-21 editions and a rank belongs to the edition that produced it.", "Answer a grouping or ranking question with the edition-specific structure rather than a remembered aggregate."),
        plan("Withdrawn claims and prohibited assertions", [11, 12], "A withdrawn claim must be stated as withdrawn, and a district-level exercise is not a national edition.", "Demonstrate factual discipline by naming what the repository refuses to assert and why."),
        plan("The Rule of Law Index attribution", [13], "The publisher is the World Justice Project and the index does not belong to the World Bank family.", "Preserve the exact attribution that the audited objective ledger routed to this owner."),
        plan("Four measurement instruments at four scales", [14], "The four instruments measure four different objects at four different scales and cannot be aggregated.", "Separate measurement instruments by object and scale before any comparative verdict is offered."),
        plan("Norms to instruments: legality, transparency and answerability", [15], "Each named remedy is specific, none of the three accountability institutions is a general grievance authority, and routing a grievance to the wrong one loses marks.", "Convert a norm into a named Indian instrument with its mechanism and its stated limitation."),
        plan("Norms to instruments: participation, responsiveness, equity and effectiveness", [16], "An executive policy is not a statute, a right-to-service Act reaches only notified services, and a targeting tool that reduces one error can raise the other.", "Supply four further norm-to-instrument evidence units with the qualification each one requires."),
        plan("Where a norm stops becoming an outcome", [17], "The diagnosis must name the stage at which the named instrument stops rather than assert general implementation weakness.", "Answer a why-does-governance-remain-poor demand by locating the stalling stage and the missing remedy."),
        plan("Critically examining an index and answering the objections", [18, 19], "A critical examination must state a verdict on soundness and must answer the standing objections rather than list principles.", "Close a critical-examination demand with tested criteria, an answered objection and a graded verdict."),
    ],
    [
        panel("Three terms, one test", "root-axes", [
            "GOVERNMENT -> legislature, executive, judiciary; the formal authority-holders",
            "GOVERNANCE -> state plus market plus civil society making and enforcing collective decisions",
            "GOOD GOVERNANCE -> the normative standard applied to the second, not a synonym for the first",
            "ANSWER MOVE -> name the duty-holder and the binding form before evaluating performance",
        ], ["Government, governance and the normative test"]),
        panel("Measurement layer against normative layer", "comparison-table", [
            "MEASUREMENT -> Worldwide Governance Indicators, six dimensions, aggregated perception",
            "MEASUREMENT -> Good Governance Index, ten sectors, state and union-territory diagnostic",
            "NORMATIVE -> UNDP principles as a process checklist that cannot rank",
            "NORMATIVE -> Second Administrative Reforms Commission institutional-reform frame",
        ], ["The Worldwide Governance Indicators frame", "UNDP principles as a process checklist"]),
        panel("The six named dimensions", "labelled-system", [
            "VOICE AND ACCOUNTABILITY | POLITICAL STABILITY AND ABSENCE OF VIOLENCE",
            "GOVERNMENT EFFECTIVENESS | REGULATORY QUALITY",
            "RULE OF LAW | CONTROL OF CORRUPTION",
            "CAUTION -> scored separately, perception-based, reported with a margin of error",
        ], ["The Worldwide Governance Indicators frame"]),
        panel("Good Governance Index edition card", "evidence-table", [
            "LAUNCH -> 25 December 2019 by the Department of Administrative Reforms and Public Grievances",
            "LATEST LOCATED NATIONAL EDITION -> Good Governance Index 2020-21, released 25 December 2021",
            "GROUPING -> three groups in 2019; four in 2020-21 including North-East and Hill States",
            "WITHDRAWN -> the claim of a 2025 national edition, corrected on 13 August 2026",
        ], ["The Good Governance Index and its located edition", "Reading Good Governance Index groupings by edition"]),
        panel("What may not be asserted", "hierarchy", [
            "SAFE -> launch date, located edition, edition-specific grouping, Good Governance Day since 2014",
            "BOUNDED -> a rank only with its edition year attached",
            "PROHIBITED -> any post-2021 national edition, rank, score, indicator count or top performer",
            "PROHIBITED -> the District Good Governance Index treated as a national edition",
        ], ["Withdrawn claims and prohibited assertions"]),
        panel("Attribution discipline", "matrix", [
            "WORLD BANK -> Worldwide Governance Indicators, six dimensions, cross-country",
            "WORLD JUSTICE PROJECT -> Rule of Law Index, published annually, distinct family",
            "DEPARTMENT OF ADMINISTRATIVE REFORMS -> Good Governance Index and Good Governance Day",
            "MINISTRY OF PANCHAYATI RAJ -> Devolution Index, panchayat scope only",
        ], ["The Rule of Law Index attribution", "Four measurement instruments at four scales"]),
        panel("Four objects at four scales", "comparison", [
            "CROSS-COUNTRY -> Worldwide Governance Indicators benchmark over time",
            "STATE SECTORAL -> Good Governance Index, ten sectors, comparison categories",
            "SERVICE PORTAL -> National e-Governance Service Delivery Assessment, end-service depth",
            "PANCHAYAT -> Devolution Index; urban local bodies are outside its scope",
        ], ["Four measurement instruments at four scales"]),
        panel("Norm to instrument, legality half", "evidence-table", [
            "RULE OF LAW -> Article 14 non-arbitrariness and reasoned orders; uneven below the regulator tier",
            "TRANSPARENCY -> Right to Information Act, 2005, Section 4 proactive disclosure; unaudited compliance",
            "ACCOUNTABILITY -> Comptroller and Auditor General, Articles 148 to 151; audit remedy",
            "ACCOUNTABILITY -> Lokpal Act, 2013 and Central Vigilance Commission Act, 2003; distinct remedies",
        ], ["Norms to instruments: legality, transparency and answerability"]),
        panel("Norm to instrument, delivery half", "evidence-table", [
            "PARTICIPATION -> Section 17 Gram Sabha social audit; Pre-Legislative Consultation Policy, 2014",
            "RESPONSIVENESS -> state right-to-service Acts from Madhya Pradesh, 2010; notified services only",
            "RESPONSIVENESS -> grievance portal twenty-one-day benchmark, departmental guidelines August 2024",
            "EQUITY AND EFFECTIVENESS -> direct benefit transfer targeting; Output-Outcome Monitoring Framework",
        ], ["Norms to instruments: participation, responsiveness, equity and effectiveness"]),
        panel("Seven stages from norm to outcome", "process-flow", [
            "LEGAL FORM -> Act, rule, guideline or executive policy, and who is bound",
            "INSTITUTION AND PROCEDURE -> identified duty-holder, timeline, officer, appeal, penalty",
            "CAPACITY AND CITIZEN SIDE -> staff, records, budget; awareness, distance, cost, language",
            "REMEDY AND FEEDBACK -> is failure correctable, and is it counted and used for redesign",
        ], ["Where a norm stops becoming an outcome"]),
        panel("Five index tests", "path-consequence", [
            "INDICATOR VALIDITY -> does it measure the governed outcome or an easily counted input",
            "COMPARABILITY -> is the data self-reported by the entity being ranked",
            "OUTPUT AGAINST OUTCOME -> how much of the score is coverage rather than realised change",
            "ADJUSTMENT AND CONSEQUENCE -> like-for-like federal comparison; does a poor score trigger correction",
        ], ["Critically examining an index and answering the objections"]),
        panel("Answer spine and answered objections", "answer-spine", [
            "OPEN -> separate the institution set, the decision process and the normative standard",
            "BUILD -> norm to named instrument to mechanism to stated limitation, three to six units",
            "TEST -> five index tests; answer vagueness, measurement, conditionality and capacity objections",
            "CLOSE -> graded verdict with the edition-dated evidence and the condition that would reverse it",
        ], ["Critically examining an index and answering the objections"]),
    ],
    [
        "Worldwide Governance Indicators",
        "World Justice Project",
        "Good Governance Index 2020-21",
        "25 December 2019",
        "25 December 2021",
        "Department of Administrative Reforms and Public Grievances",
        "Second Administrative Reforms Commission",
        "Pre-Legislative Consultation Policy",
        "Output-Outcome Monitoring Framework",
        "Economic Survey 2018-19",
        "Articles 148 to 151",
        "Section 4 proactive disclosure",
    ],
    "No direct General Studies Mains demand is routed to this owner in the audited 2018-2023 or 2024-2025 Mains ledgers. The audited 2018-2023 Preliminary ledger routes one objective demand to this owner, namely the organisation that releases the Rule of Law Index annually, and that ledger itself records the official key as unavailable locally. The printed wording of that objective question could not be confirmed in the locally held OCR-searchable 2018 Preliminary paper, whose scan does not yield searchable text for the item, so no option set, no official key and no verbatim stem is reproduced or inferred. The owner therefore carries the examinable distinction - the Rule of Law Index is published by the World Justice Project and not by the World Bank - without converting an unkeyed objective question into a solved answer. The six original Mains answers below are authored practice, not previous-year questions, and the Basic owner records that this topic functions mainly as the conceptual opening for evaluative demands owned by Topics 02 to 15 rather than as a standalone Mains topic.",
    [],
    live_sources=[],
    current_note="No new live official item was verified for this topic on 2026-09-02. Only the dated official anchors already carried by the repository owners are used, each with its issuing body and date, namely Good Governance Day observed on 25 December since 2014, the Good Governance Index launched on 25 December 2019, the latest completed national edition located as the Good Governance Index 2020-21 released on 25 December 2021 with its status checked on 13 August 2026, the twenty-one-day grievance benchmark stated in departmental guidelines of August 2024, and the Economic Survey 2018-19 Chapter 2 behavioural-insights anchor. The withdrawal of the unsupported 2025 edition claim is carried forward explicitly. No governance indicator value, index edition, state rank, score, indicator count, percentile or top performer is asserted, no scheme or policy status is inferred, no institutional power is invented, and the personal-probity dimension of governance is cross-linked to Ethics rather than restated here.",
    extra=[
        "00_Master-Framework.md",
        "REVISION-CHART_Systems-Delivery-and-Distinctive-Features.md",
        "ANSWER-WORTHINESS-AUDIT.md",
    ],
)


TOPIC_02 = common.topic(
    2,
    "Government Policy Design and Implementation",
    "02_Government-Policy-Design-and-Implementation",
    "02_Government-Policy-Design-and-Implementation_Learner-V2-Complete-Topic-Package.md",
    [
        ("The policy cycle as a locating device", "The policy cycle - agenda setting, formulation, decision or enactment, implementation and evaluation, feeding back into agenda setting - is used analytically to locate exactly where a named policy is succeeding or failing, and the syllabus clause itself separates issues arising out of design from issues arising out of implementation."),
        ("The implementation gap", "The implementation gap is the difference between the policy as designed or announced and the policy as actually delivered on the ground, and it is the multiplicative product of design realism, the count of independent approval points and the quality of frontline discretion rather than a synonym for corruption."),
        ("Clearance points and the complexity of joint action", "Pressman and Wildavsky established that each additional actor, level of government or approval step is a clearance point, and that the cumulative probability of delay or distortion rises sharply as clearance points multiply even where each individual point is separately likely to succeed, which is why a centrally sponsored scheme requiring Union, state, district and panchayat sign-off is structurally more gap-prone than a single-agency central-sector scheme."),
        ("Street-level bureaucracy", "Michael Lipsky's street-level bureaucracy thesis holds that frontline officials such as teachers, police, ration-shop dealers, auxiliary nurse midwives and examination-centre invigilators exercise substantial discretion and in effect make policy through their daily choices, so the policy a citizen experiences is what the frontline official actually does rather than what the scheme guideline says."),
        ("Coping routines and exclusion without an allegation of corruption", "Lipsky identifies predictable coping routines under heavy caseload and resource scarcity - rationing time and attention, creaming by serving the easier cases first, and informal rule-bending - and these routines explain welfare exclusion error without alleging corruption, which is the analytical wedge that separates a diagnosed answer from a complaint."),
        ("Top-down and bottom-up readings of implementation", "A top-down reading asks whether frontline action matched the original design while a bottom-up reading treats frontline output as the real policy regardless of design intent, and neither view alone is complete, so a strong answer reframes the question of whether an Act worked into the question of what the designated centres and officials actually did."),
        ("Design realism against design ambition", "A policy can be ambitious in coverage and targets without being realistic against actual administrative capacity, and the gap between ambition and realism is a formulation-stage cause of failure distinct from any delivery-stage cause, so most failures attributed to implementation are in fact design failures that became visible only at delivery."),
        ("The Pre-Legislative Consultation Policy of 2014", "The Pre-Legislative Consultation Policy of 2014 advises Union departments to publish draft legislation with an explanatory note and an ordinary minimum public comment window of about thirty days before introduction, and it is an executive policy rather than a statute whose comments are not binding, so publishing a draft is consultation compliance while incorporating feedback is consultation depth."),
        ("Regulatory impact assessment as an emerging practice", "A regulatory impact assessment is a structured ex-ante assessment of a proposed regulation's costs, benefits and alternatives before it is finalised, and it remains unevenly institutionalised across Indian ministries and regulators, so it must be cited as an emerging good-governance practice rather than as a uniformly binding legal requirement."),
        ("Convergence as clearance-point removal", "Convergence is the deliberate alignment of multiple schemes and departments toward a common local outcome, and its analytical value is that it adds no new scheme but removes clearance points and duplicate targeting between existing ones at the district and panchayat level, which is why it improves outcomes without a proportional increase in outlay and why it fails wherever functional devolution is absent."),
        ("The Public Examinations Act, 2024 and its commencement", "The Public Examinations (Prevention of Unfair Means) Act, 2024 was enacted to prevent and penalise unfair means such as question-paper leaks, impersonation and tampering in public examinations, it came into force on 21 June 2024 by notification S.O. 2422(E), and its scheduled central authorities include the Union Public Service Commission, the Staff Selection Commission, Railway Recruitment Boards, the Institute of Banking Personnel Selection, Central Government departments and attached offices, and the National Testing Agency."),
        ("Authority-based coverage against territorial extent", "Coverage under the Public Examinations (Prevention of Unfair Means) Act, 2024 is authority-based rather than subject-matter-based or territorial, so a state board or university examination is not automatically covered merely because the Act extends to India, and inclusion requires either notification of that authority by the Central Government or separate state legislation, which is precisely the scope half of the 2024 demand and the point an aims-only answer misses."),
        ("The six-stage implementation map", "Any unfamiliar policy can be diagnosed through six stages - legal authority and who is bound, rules and standard operating procedures specifying entitlement and eligibility, the named responsible agency across Union, state, district, local or parastatal levels, staff and money and technology including sanctioned against filled posts and the fund-flow route, the citizen interface of awareness and documents and distance and language and digital access, and grievance and review including appeal, penalty, evaluation and any sunset clause - and an enacted law can stall at any stage after the first."),
        ("The Aspirational Districts Programme design", "The Aspirational Districts Programme of NITI Aayog targets inter-district rather than inter-state divergence across 112 districts using 49 key performance indicators grouped into five themes - health and nutrition, education, agriculture and water resources, financial inclusion and skill development, and basic infrastructure - tracked on the Champions of Change dashboard, and it operates through the three named levers of convergence, collaboration including the Prabhari officer arrangement, and competition through delta ranking."),
        ("Delta ranking and the self-reported-data limit", "Delta ranking scores the pace of improvement rather than the absolute level so that the historically worst-off district is not permanently bottom and therefore permanently unmotivated, while the dashboard data is largely district-self-reported with validation by selected agencies and the district unit can mask intra-district divergence, which is why the Aspirational Blocks Programme covering 513 blocks exists as a separate and non-substitutable unit and why the programme is best read as an administrative-attention and convergence instrument rather than a financing instrument."),
        ("Policy contradiction as an externality problem", "Environmental degradation is frequently produced not by an absence of policy but by mutually contradicting policies pursued by different ministries with separate mandates and no arbitration mechanism, because each sectoral ministry optimises its own objective function, no single actor is accountable for the aggregate outcome, and the environmental cost is an externality that appears in nobody's departmental performance metric - although some contradictions are genuine value conflicts between livelihood today and ecological stock tomorrow rather than coordination failures."),
        ("PM GatiShakti as an information layer", "PM GatiShakti is a National Master Plan approach for multi-modal infrastructure connectivity built on a shared geographic-information-system planning platform that layers infrastructure and utility data from multiple ministries, and its mechanism is the removal of sequencing failure and private-sector information risk through a common map, but it coordinates information rather than authority, since land, utilities and many approvals remain with states and local bodies."),
        ("Public-private partnership governance", "A public-private partnership is a procurement and service-delivery choice rather than privatisation by definition, and its governance chain runs from public purpose and output standard through risk allocation to the actor best able to manage each risk, competitive procurement with disclosed criteria, performance-linked payment, independent monitoring and contract disclosure, renegotiation and exit rules, to affordability and continuity safeguards, with Viability Gap Funding supporting economically justified but commercially weak projects and the Hybrid Annuity Model illustrating deliberate risk-sharing."),
        ("Targeting error and the universalism trade-off", "Targeting concentrates scarce resources but requires identification machinery that itself excludes, while universalism avoids identification error at higher cost, and tightening verification reduces inclusion error where the ineligible are included while increasing exclusion error where the eligible are left out, so an entitlement affecting subsistence should fix the tolerable exclusion error first and add an offline or assisted fallback."),
        ("Verified question ownership across two ledgers", "The audited 2024-2025 Mains ledger routes the 2024 General Studies Paper-II demand on the Public Examinations (Prevention of Unfair Means) Act, 2024 to this Basic owner, while the audited 2018-2023 ledger routes three further demands - the 2018 General Studies Paper-I demand on aspirational districts, the 2018 General Studies Paper-II demand on policy contradictions and environmental degradation, and the 2022 General Studies Paper-II demand on Gati-Shakti coordination - to the Advanced owner, and the Basic owner records that core routing supersedes the older Advanced pointer so that all four are answered from the core file."),
    ],
    [
        "Do not equate implementation failure with corruption when design realism, clearance points and frontline discretion explain most Indian delivery failures.",
        "Do not describe street-level bureaucrats as officials who merely follow orders.",
        "Do not treat frontline discretion as something to be eliminated rather than guided by written reasons, recorded decisions and appeal.",
        "Do not claim that more clearance points automatically deliver more accountability.",
        "Do not present the Pre-Legislative Consultation Policy of 2014 as a statute or its comment window as binding.",
        "Do not describe regulatory impact assessment as a uniformly mandatory requirement across Indian ministries and regulators.",
        "Do not describe convergence as an additional scheme rather than as the removal of clearance points between existing ones.",
        "Do not claim that the Public Examinations (Prevention of Unfair Means) Act, 2024 automatically covers state board or university examinations.",
        "Do not answer the 2024 scope demand with the aims of the Act alone and omit the authority-based coverage rule.",
        "Do not treat an executive announcement of adoption as equivalent to a Gazette notification naming an additional authority.",
        "Do not assert any Aspirational Districts rank, key performance indicator value or outlay figure.",
        "Do not treat the Aspirational Blocks Programme as a substitute unit for the district programme or the reverse.",
        "Do not state a Gati-Shakti investment figure, ministry count, target date or logistics-cost percentage.",
        "Do not claim that a shared planning platform resolves federal or jurisdictional friction over land and approvals.",
        "Do not present every policy contradiction as a coordination failure when some are genuine value conflicts.",
        "Do not present a public-private partnership as privatisation by definition or invent a project success rate or fiscal figure.",
        "Do not present inclusion error and exclusion error as the same error or claim that de-duplication corrects both.",
        "Do not invent an environmental-degradation statistic or a scheme name while answering a policy-contradiction demand.",
    ],
    [
        (10, "Explain the implementation gap in public policy and locate its causes on the policy cycle with an Indian illustration.", "The gap is the multiplicative product of design realism, clearance-point count and frontline discretion quality, so an answer that names the stage at which a specific policy stops diagnoses the failure while one that asserts poor implementation only describes it.", [0, 1, 2]),
        (10, "Explain why street-level discretion should be guided rather than eliminated in Indian welfare delivery.", "Discretion is not eliminable and can adapt policy humanely or ration it arbitrarily, so the governance task is clear entitlement rules, reasoned rejection, recorded decisions and an appeal rather than an unattainable demand for uniformity.", [3, 4, 5]),
        (15, "Examine the aims of the Public Examinations (Prevention of Unfair Means) Act, 2024 and the separate question of its coverage.", "The aims are integrity-protective and general while the reach is authority-based and therefore specific, and conflating the two is precisely the error the scope half of the demand is designed to expose.", [10, 11, 12, 7]),
        (15, "Examine how convergence and pre-legislative consultation can reduce the implementation gap in Indian public policy.", "Consultation improves design realism at formulation and convergence removes clearance points at delivery, so the two correctives act at different stages and neither can substitute for the other or for functional devolution.", [9, 7, 8, 13]),
        (20, "Assess the claim that contradictory sectoral policies rather than an absence of policy explain inadequate environmental protection in India.", "The coordination diagnosis holds wherever each ministry optimises its own objective function and the environmental cost appears in no departmental metric, but it fails where the conflict is a genuine value conflict that better process alone cannot resolve.", [15, 16, 8, 18]),
        (20, "Assess how far coordination instruments can substitute for authority in Indian infrastructure and service delivery.", "A shared information layer and a well-specified contract can reduce sequencing failure and information risk, but neither transfers authority over land, utilities or approvals, so coordination reforms raise the ceiling on delivery without removing the federal constraint beneath it.", [16, 17, 14, 19]),
    ],
    [
        plan("Locating failure on the policy cycle", [0, 1], "The syllabus separates design from implementation, so a merged answer forfeits the distinction the clause itself makes.", "Open a policy-failure answer by naming the stage rather than asserting a general implementation weakness."),
        plan("Clearance points and the complexity of joint action", [2], "Cumulative failure probability rises with each approval point even where every point is separately likely to succeed, and reducing points centralises decisions.", "Explain why a multi-tier scheme is structurally gap-prone independent of funding adequacy."),
        plan("Street-level bureaucracy", [3], "The frontline official makes policy through discretion, so the guideline is not the policy the citizen experiences.", "Convert an abstract delivery question into a claim about what named frontline actors actually do."),
        plan("Coping routines and exclusion without corruption", [4], "Rationing and creaming are predictable responses to caseload rather than random dereliction, and asserting them in a specific case needs caseload evidence.", "Explain welfare exclusion analytically without alleging corruption."),
        plan("Top-down and bottom-up readings", [5], "Neither reading is complete on its own, so an answer that adopts only one has answered half the question.", "Reframe a did-the-Act-work demand into a question about frontline output."),
        plan("Design realism against design ambition", [6], "Ambition is not realism, and a formulation-stage cause is distinct from a delivery-stage cause.", "Attribute a visible delivery failure to its formulation origin where the evidence supports it."),
        plan("Pre-legislative consultation and its statutory status", [7], "The 2014 policy is executive rather than statutory and its comments are not binding, so compliance is not depth.", "Distinguish consultation compliance from consultation depth in a reform-suggestion answer."),
        plan("Regulatory impact assessment as an emerging practice", [8], "The practice is unevenly institutionalised and must not be described as uniformly binding.", "Cite an ex-ante design instrument with its true institutional status attached."),
        plan("Convergence as clearance-point removal", [9], "Convergence adds no scheme and fails where functional devolution is absent.", "Recommend convergence as a mechanism rather than as another programme in a way-forward list."),
        plan("The Public Examinations Act, 2024 and its scope rule", [10, 11], "Territorial extent does not create coverage, and inclusion requires notification of an authority or separate state law.", "Answer the scope half of a recent-statute demand separately and explicitly."),
        plan("The six-stage implementation map", [12], "An enacted law can stall at any stage after legal authority, so stating that the Act exists answers only the first stage.", "Diagnose an unfamiliar policy by walking the six stages and stopping at the one the stem is about."),
        plan("Aspirational districts: convergence, collaboration, competition", [13, 14], "Dashboard data is largely district-self-reported and the district unit can mask intra-district divergence.", "Use an area-based targeting programme as an administrative-attention instrument rather than a financing claim."),
        plan("Contradictory sectoral policies and the environmental externality", [15], "Some contradictions are value conflicts rather than coordination failures, and no degradation statistic may be invented.", "Diagnose a cross-sectoral contradiction as an externality that appears in no departmental metric."),
        plan("PM GatiShakti and public-private coordination", [16, 17], "A planning platform coordinates information rather than authority, and no investment or logistics-cost figure may be asserted.", "Classify an infrastructure-coordination demand as an institutional rather than a financing question."),
        plan("Targeting error and honest question ownership", [18, 19], "Tightening verification reduces one error while raising the other, and three of the four routed demands sit with the Advanced owner in the older ledger.", "Assemble the policy answer spine with an explicit targeting trade-off and transparent question ownership."),
    ],
    [
        panel("Design against implementation", "root-axes", [
            "DESIGN SIDE -> problem diagnosis, target population, incentive, realism against capacity",
            "IMPLEMENTATION SIDE -> clearance points, frontline discretion, citizen interface, remedy",
            "SYLLABUS RULE -> the clause names both, so answer in two labelled halves",
            "GAP -> design realism multiplied by clearance-point count multiplied by discretion quality",
        ], ["Locating failure on the policy cycle"]),
        panel("Clearance-point arithmetic", "causal-system", [
            "EACH APPROVAL -> Union, state, district, panchayat sign-off adds an independent point",
            "EFFECT -> cumulative failure probability rises even where every point is separately likely",
            "CONTRAST -> a single-agency central-sector scheme carries fewer points by construction",
            "COST OF THE FIX -> removing points centralises decisions and reduces local adaptation",
        ], ["Clearance points and the complexity of joint action"]),
        panel("Frontline discretion", "comparison-table", [
            "TOP-DOWN -> did frontline action match the original design",
            "BOTTOM-UP -> frontline output is the real policy regardless of design intent",
            "COPING ROUTINES -> rationing attention, creaming the easier cases, informal rule-bending",
            "PAYOFF -> explains exclusion error without alleging corruption",
        ], ["Street-level bureaucracy", "Coping routines and exclusion without corruption"]),
        panel("Consultation and ex-ante design", "hierarchy", [
            "POLICY -> Pre-Legislative Consultation Policy, 2014, executive and not statutory",
            "WINDOW -> ordinary minimum public comment period of about thirty days",
            "DEPTH AGAINST COMPLIANCE -> publishing a draft is not incorporating feedback",
            "REGULATORY IMPACT ASSESSMENT -> emerging and unevenly institutionalised, not uniformly binding",
        ], ["Pre-legislative consultation and its statutory status", "Regulatory impact assessment as an emerging practice"]),
        panel("Public Examinations Act card", "evidence-table", [
            "STATUTE -> Public Examinations (Prevention of Unfair Means) Act, 2024",
            "COMMENCEMENT -> in force 21 June 2024 by notification S.O. 2422(E)",
            "SCHEDULED AUTHORITIES -> UPSC, SSC, Railway Recruitment Boards, IBPS, NTA, Central departments",
            "COVERAGE RULE -> authority-based; a state board or university examination is not automatic",
        ], ["The Public Examinations Act, 2024 and its scope rule"]),
        panel("Aims against scope", "matrix", [
            "AIMS -> prevent and penalise paper leaks, impersonation and tampering; protect credibility",
            "SCOPE -> scheduled authority, or a Central Government notification, or separate state law",
            "ERROR -> reading territorial extent as coverage",
            "ANSWER MOVE -> answer the scope half separately and explicitly",
        ], ["The Public Examinations Act, 2024 and its scope rule"]),
        panel("Six-stage implementation map", "process-flow", [
            "1 LEGAL AUTHORITY -> Act, rule, guideline or executive scheme, and who is bound",
            "2 RULES AND PROCEDURE -> entitlement, eligibility and process specified",
            "3 AGENCY AND RESOURCES -> named responsible tier; sanctioned against filled posts; fund flow",
            "4 CITIZEN INTERFACE AND REMEDY -> awareness, documents, distance, language; appeal and review",
        ], ["The six-stage implementation map"]),
        panel("Aspirational Districts design card", "evidence-table", [
            "UNIT -> inter-district divergence; 112 districts under NITI Aayog",
            "MEASUREMENT -> 49 key performance indicators across five named themes",
            "LEVERS -> convergence, collaboration with the Prabhari officer arrangement, competition",
            "SEPARATE UNIT -> Aspirational Blocks Programme covering 513 blocks",
        ], ["Aspirational districts: convergence, collaboration, competition"]),
        panel("Delta ranking and its limit", "path-consequence", [
            "CHOICE -> rank on the pace of improvement rather than the absolute level",
            "REASON -> the historically worst-off district is not permanently bottom and unmotivated",
            "LIMIT -> dashboard data is largely district-self-reported with selective validation",
            "READING -> an administrative-attention and convergence instrument, not a financing instrument",
        ], ["Aspirational districts: convergence, collaboration, competition"]),
        panel("Contradiction as externality", "causal-system", [
            "MANDATES -> each ministry optimises its own objective function",
            "GAP -> no single actor is accountable for the aggregate environmental outcome",
            "MECHANISM -> the environmental cost sits in nobody's departmental performance metric",
            "QUALIFICATION -> some contradictions are value conflicts, not coordination failures",
        ], ["Contradictory sectoral policies and the environmental externality"]),
        panel("Coordination against authority", "comparison", [
            "PM GATISHAKTI -> shared geographic-information-system layer for multi-modal connectivity",
            "GAIN -> removes sequencing failure and lowers private-sector information risk",
            "LIMIT -> coordinates information, not authority over land, utilities and approvals",
            "PARTNERSHIP CHAIN -> risk allocation, competitive procurement, performance payment, exit rules",
        ], ["PM GatiShakti and public-private coordination"]),
        panel("Targeting and answer spine", "answer-spine", [
            "TRADE-OFF -> tighter verification lowers inclusion error and raises exclusion error",
            "RULE -> fix the tolerable exclusion error first for subsistence entitlements; add assisted fallback",
            "OWNERSHIP -> one routed demand sits with the Basic owner; three sit with the Advanced owner",
            "CLOSE -> name the stalling stage, attach one corrective and state its cost",
        ], ["Targeting error and honest question ownership"]),
    ],
    [
        "Public Examinations (Prevention of Unfair Means) Act, 2024",
        "21 June 2024",
        "S.O. 2422(E)",
        "Pressman",
        "Lipsky",
        "Pre-Legislative Consultation Policy",
        "Aspirational Districts Programme",
        "112 districts",
        "49 key performance indicators",
        "513 blocks",
        "PM GatiShakti",
        "Viability Gap Funding",
        "Hybrid Annuity Model",
    ],
    "Four direct General Studies Mains demands are routed to this topic across the audited ledgers and every one of them was confirmed word for word in the locally held OCR-searchable official question papers. The audited 2024-2025 ledger routes the 2024 General Studies Paper-II demand on the Public Examinations (Prevention of Unfair Means) Act, 2024 to the Basic owner. The audited 2018-2023 ledger routes three further demands to the Advanced owner - the 2018 General Studies Paper-I demand on the transformation of aspirational districts, the 2018 General Studies Paper-II demand on policy contradictions and environmental degradation, and the 2022 General Studies Paper-II demand on Gati-Shakti coordination between the government and the private sector - and the 2018 Paper-I entry itself carries the ledger's own note that the printed stem is partly word-scrambled in the scan. The Basic owner records that core routing supersedes the older Advanced pointer, so all four are answered from the core file rather than from the optional advanced block. No official answer key or marking scheme is held locally for any of them, so each model solution below is an authored answer route and not an official key, and the objective ledgers route no Preliminary demand to this owner.",
    [
        ("2024", "General Studies Paper-II", "What are the aims and objects of recently passed and enforced, The Public Examination (Prevention of Unfair Means) Act, 2024? Whether University/State Education Board examinations, too, are covered under the Act? Discuss in 250 words for 15 marks.", "Routed to the Basic owner by the audited 2024-2025 Mains ledger and confirmed word for word in the locally held official 2024 General Studies Paper-II. No official answer key is held locally, so the model solution is an authored route.", "Answer in two labelled halves because the stem asks two separate things. First state the aims: the Act prevents and penalises unfair means in public examinations, defining offences such as question-paper leak, impersonation and tampering, and its object is protecting the credibility of public recruitment and admission examinations. Name the commencement precisely, 21 June 2024 by notification S.O. 2422(E), because a recently enforced statute demand rewards the date. Second, answer the scope question directly rather than describing the Act again: coverage is authority-based, the Schedule names central authorities including the Union Public Service Commission, the Staff Selection Commission, Railway Recruitment Boards, the Institute of Banking Personnel Selection, the National Testing Agency and Central Government departments and attached offices, and further authorities may be added by Central Government notification. It follows that a university or state education board examination is not automatically covered merely because the Act extends to India; inclusion requires notification of that authority or separate state legislation, and an executive statement of adoption is not a notification. Then add the analysis the directive expects: enactment is only the first of six implementation stages, so the deterrent effect will be determined by designated authorities, rules, investigation capacity and examination-centre practice rather than by the statute alone. Qualify honestly - the Act creates offences and designated authorities but does not by itself supply the forensic, invigilation and coordination capacity that detection requires, and no conviction, detection or deterrence figure is available here. Conclude that the aims are integrity-protective and general while the reach is authority-based and therefore specific, and that conflating the two is the error the scope half of the question is designed to expose."),
        ("2018", "General Studies Paper-I", "Mention core strategies for the transformation of aspirational districts in India and explain the nature of convergence, collaboration and competition for its success. Answer in 250 words for 15 marks.", "Routed by the audited 2018-2023 Mains ledger to the Advanced owner with the ledger's own note that the printed stem is partly word-scrambled in the scan; the stem was nevertheless confirmed word for word in the locally held official 2018 General Studies Paper-I. The Basic owner records that core routing supersedes the older Advanced pointer. No official answer key is held locally.", "Open by naming the problem the programme addresses, because the targeting unit is the analytical core: inter-district rather than inter-state divergence, a unit smaller than the state and larger than the block. State the design with its exact figures - the NITI Aayog Aspirational Districts Programme covering 112 districts, measured on 49 key performance indicators grouped into five themes of health and nutrition, education, agriculture and water resources, financial inclusion and skill development, and basic infrastructure, tracked on the Champions of Change dashboard. Then explain each of the three named levers in the programme's own logic rather than as adjectives. Convergence aligns Union and state schemes on one district outcome and its governance value is that it removes clearance points between parallel schemes instead of adding a new scheme. Collaboration operates through Union, state and district officials working with the Prabhari officer arrangement, which supplies supervisory attention that ordinary line administration does not. Competition operates through delta ranking, and the analytically interesting choice is that ranking on the pace of improvement rather than the absolute level prevents the historically worst-off district from being permanently bottom and therefore permanently unmotivated. State the limitations honestly: dashboard data is largely district-self-reported with validation by selected agencies, an indicator improvement is an output measure rather than a realised outcome, and the district unit can mask intra-district divergence at block and habitation level, which is why the Aspirational Blocks Programme covering 513 blocks exists as a separate and non-substitutable unit. Conclude that the programme is best read as an administrative-attention and convergence instrument that re-allocates supervisory intensity rather than primarily money, and assert no district rank, indicator value or expenditure figure."),
        ("2018", "General Studies Paper-II", "Policy contradictions among various competing sectors and stakeholders have resulted in inadequate protection and prevention of degradation to environment. Comment with relevant illustrations in 150 words for 10 marks.", "Routed by the audited 2018-2023 Mains ledger to the Advanced owner as a cross-cutting demand linked to both policy design and environmental regulation, and confirmed in the locally held official 2018 General Studies Paper-II. The Basic owner answers it under core routing. No official answer key is held locally.", "Take a position in the first sentence because comment permits an argued view: environmental degradation in India is frequently produced not by an absence of policy but by mutually contradicting policies pursued by different ministries with separate mandates and no arbitration mechanism. Give the mechanism precisely rather than the sentiment, since this is where the marks sit: each sectoral ministry optimises its own objective function, no single actor is accountable for the aggregate environmental outcome, and the environmental cost is an externality that appears in nobody's departmental performance metric. Make the illustrations structural rather than anecdotal - input and price support that encourages water-intensive cropping in a water-stressed region while a separate programme funds groundwater conservation, energy-access expansion running against emission-reduction commitments, and infrastructure-clearance timelines running against impact-assessment depth. Name the governance correctives and attach each to the stage it fixes: regulatory impact assessment at formulation, inter-ministerial appraisal before notification, convergence at the district level, and outcome indicators that carry the environmental externality. Then supply the counterpoint that lifts the answer: some contradictions are genuine value conflicts between livelihood today and ecological stock tomorrow rather than coordination failures, and better process alone cannot resolve them. Cross-link the environmental impact assessment and tribunal machinery to the Environment owner rather than restating it, and invent no degradation statistic, ministry position or scheme name. Conclude that coordination reform is necessary but insufficient, because a contradiction rooted in a value conflict requires a political choice that no appraisal procedure can make on its behalf."),
        ("2022", "General Studies Paper-II", "The Gati-Shakti Yojana needs meticulous coordination between the government and the private sector to achieve the goal of connectivity. Discuss in 150 words for 10 marks.", "Routed by the audited 2018-2023 Mains ledger to the Advanced owner as a cross-cutting demand whose Economy infrastructure route terminates in the answer-complete core file, and confirmed word for word in the locally held official 2022 General Studies Paper-II. No official answer key is held locally.", "Classify the question correctly in the opening line, because misclassification is the commonest failure here: this is a coordination and information-asymmetry problem rather than an infrastructure-finance problem, so the governance content is the institutional answer to siloed planning. Describe the design only to the extent verified - PM GatiShakti is a National Master Plan approach for multi-modal infrastructure connectivity built on a shared geographic-information-system planning platform that layers infrastructure and utility data from multiple ministries so that projects are planned against a common map rather than in isolation. State the mechanism in two steps. Within government, a shared data layer removes the sequencing failures that arise when each ministry plans on its own data, the familiar case being a road surfaced and then dug up for a utility line. Toward the private sector, the same layer reduces information risk, because a bidder can see planned alignments and utility corridors, so the state's contribution is de-risking through predictability rather than direct subsidy. Then state the governance limitation squarely: a planning platform coordinates information, not authority, since land, utilities and many approvals remain with states and local bodies, so visibility improves without resolving federal or jurisdictional friction. Add the contractual layer where private participation is actually procured - risk allocated to the actor best able to manage it, competitive procurement with disclosed criteria, performance-linked payment, independent monitoring and disclosed contracts, and renegotiation and exit rules - noting that Viability Gap Funding and the Hybrid Annuity Model show that risk transfer is deliberately varied rather than uniform. Conclude that the reform is an information-layer reform whose value depends on data currency and on state participation, and assert no investment figure, ministry count, target date or logistics-cost percentage."),
    ],
    live_sources=[],
    current_note="No new live official item was verified for this topic on 2026-09-02. The only dated official elements used are those already carried by the repository owners with their status checks, namely the Public Examinations (Prevention of Unfair Means) Act, 2024 in force from 21 June 2024 by notification S.O. 2422(E) with its authority-based coverage rule as checked on 21 July 2026, the Pre-Legislative Consultation Policy of 2014 as an executive policy, and the design figures of the Aspirational Districts Programme and the Aspirational Blocks Programme. No later expansion of the 2024 Act is asserted without a Gazette notification naming the additional authority, no district rank, indicator value, outlay, investment figure, ministry count, target date or logistics-cost percentage is asserted, no environmental-degradation statistic is invented, no public-private-partnership success rate or fiscal figure is claimed, health-scheme content is cross-linked to Social Justice, environmental impact assessment and tribunal machinery are cross-linked to Environment and Ecology, and infrastructure financing and sector economics are cross-linked to Economy rather than restated here.",
    extra=[
        "00_Master-Framework.md",
        "REVISION-CHART_Systems-Delivery-and-Distinctive-Features.md",
        "ANSWER-WORTHINESS-AUDIT.md",
    ],
)
