"""Authored content data for Indian Art and Culture learner-v2 Topics 06-10."""

from __future__ import annotations

import generate_indian_art_culture_common as common
from indian_art_culture_01_05_data import panel, plan


TOPIC_06 = common.topic(
    6,
    "Sculpture, Pottery and Iconography",
    "06_Sculpture-Pottery-and-Iconography",
    "06_Sculpture-Pottery-and-Iconography_Complete-Topic-Package.md",
    [
        ("Six-variable sculpture method", "Read sculpture through material, posture or gesture, iconographic attribute, patron, site context and cross-site comparison; this converts visual description into bounded historical analysis."),
        ("Cire-perdue technique", "In lost-wax casting a wax model is clay-coated, heated so the wax drains away, and filled with molten metal; the technique is evidenced from the Indus tradition and later enabled free-standing bronzes."),
        ("Harappan label caution", "Pashupati, Mother Goddess and Priest-King are modern interpretive labels for Harappan objects, not identities read from the undeciphered script."),
        ("Pottery sequence", "The source spine runs from Neolithic hand-made coarse ware through Chalcolithic painted wares, Harappan Red Ware and Painted Grey Ware to Northern Black Polished Ware."),
        ("Northern Black Polished Ware", "NBPW is fine lustrous tableware associated especially with early historic urbanisation; it is not exclusively a Mauryan court product and is not the same as Black-and-Red Ware."),
        ("Yaksha, Yakshi and Shalabhanjika", "Yaksha and Yakshi figures connect water, fertility, trees and wilderness with multiple religions; the Shalabhanjika is a tree-holding yakshi used as an auspicious bracket figure."),
        ("Gandhara school", "Gandhara sculpture used bluish-grey sandstone and later stucco for a mainly Buddhist programme whose drapery, hair and body modelling show Hellenistic, Parthian and Central Asian layers."),
        ("Mathura school", "Mathura developed in spotted red sandstone, served Buddhist, Hindu and Jain patrons, and used attributes or avayudhas and emphatic halos within an indigenous visual grammar."),
        ("Amaravati school", "Amaravati or Vengi sculpture used dynamic narrative relief, greenish-white limestone and extensive tribhanga within a mainly Buddhist Satavahana and later Ikshvaku setting."),
        ("Aniconic symbolism", "Early Buddhist programmes marked the Buddha through symbols such as the empty throne, Bodhi tree, wheel, footprints and stupa; an empty seat is a presence-marker, not a missing figure."),
        ("Parallel iconic shift", "Anthropomorphic Buddha images emerged in broadly overlapping early-CE contexts at Gandhara and Mathura, so neither school should be declared the uncontested sole origin."),
        ("Gupta Sarnath idiom", "The Sarnath school used cream-coloured sandstone and metal for subtly modelled, thinly draped figures; the Sultanganj copper Buddha is safer described as late or post-Gupta."),
        ("Nataraja origin and peak", "The earliest known Nataraja example in the owner is at Ravana Phadi, Aihole, under early Chalukya rule; Chola bronzes perfected and ritualised the form rather than originating it."),
        ("Nataraja attribute system", "Damaru signifies creation, fire destruction, abhaya reassurance, the raised foot release, Apasmara ignorance and the surrounding aureole cyclical time; each attribute must be read in position."),
        ("Lion and bull programme", "Rampurva preserves an inscribed Ashokan lion pillar and an uninscribed bull pillar, while the Sarnath abacus places lion and bull within a wider Buddhist and imperial symbol system."),
        ("Nandi as architecture", "At Shaiva temples the bull is not merely ornament: a Nandi mandapa or pavilion stands axially before the sanctum, as at Brihadishvara, Ellora Kailasa and Ramappa."),
        ("Yali and Vyala distinction", "Yali is a composite lion-based guardian associated especially with Vijayanagara pillars and Nayaka identity, while Khajuraho Vyalas are hybrid imaginary animals with lions' bodies."),
        ("Temple sculpture as social evidence", "Dancers, musicians, teachers, couples and ritual scenes show what patrons selected for visibility; carvings are commissioned representations, not statistical photographs of medieval society."),
        ("Terracotta continuity", "Terracotta moves from Harappan figurines and plough models to Chandraketugarh craft, Gupta plaques and Bengal architectural relief, linking domestic objects, urban workshops and façades."),
        ("Verified sculpture PYQ routes", "The routed direct Mains cluster comprises 2019 Gandhara external elements and the 2022 demands on medieval temple sculpture as social evidence and lion-bull significance."),
    ],
    [
        "Do not treat Pashupati, Mother Goddess or Priest-King as decoded Harappan identities.",
        "Do not collapse Harappan red ware into Black-and-Red Ware.",
        "Do not describe NBPW as exclusively Mauryan or exclusively black.",
        "Do not declare Gandhara the uncontested first source of the human Buddha image.",
        "Do not reduce Gandhara to Greek art without its Buddhist subject and Kushana setting.",
        "Do not describe Mathura as a Buddhist-only school.",
        "Do not transfer Gandhara foreign influence to indigenous Amaravati.",
        "Do not date the Didarganj chauri-bearer firmly to the Mauryan period.",
        "Do not make Chola patronage the origin of Nataraja iconography.",
        "Do not put a lion on a Harappan seal or read later Shaiva meaning backwards into its bull.",
        "Do not invent Nandi mythology where the owner verifies only vahana and axial placement.",
        "Do not treat temple sculpture as a demographic photograph of society.",
        "Do not name an unverified living terracotta centre as evidence from this owner.",
        "Do not invent dimensions, alloy percentages, museum locations or repatriation status.",
    ],
    [
        (10, "Highlight the Central Asian and Greco-Bactrian elements in Gandhara art.", "Gandhara was a Buddhist iconographic programme rendered in a Hellenised surface idiom under Kushana patronage; named external elements must be separated from the Indian subject.", [6, 7, 10]),
        (10, "How can medieval temple sculpture be used as evidence of social life?", "Temple sculpture records patron-selected social and ritual visibility through named registers, but cannot be treated as a representative census of ordinary life.", [0, 17]),
        (15, "Compare the Gandhara, Mathura and Amaravati schools on common axes.", "Material, religious scope, external influence, posture, narrative treatment and patronage reveal three different workshop solutions rather than a quality hierarchy.", [6, 7, 8, 10]),
        (15, "Explain the development and iconographic structure of Nataraja.", "Nataraja must be traced from an early Chalukya antecedent to the Chola canonical bronze and decoded attribute by attribute through casting, gesture and ritual mobility.", [1, 12, 13]),
        (20, "Discuss the significance of lion and bull figures in Indian mythology, art and architecture.", "The lion repeatedly visualised authority and doctrine while the bull marked generative, biographical and Shaiva-vahana meanings; Harappan, Buddhist and temple evidence must remain source-separated.", [2, 9, 14, 15, 16]),
        (20, "Trace the relationship between material, technique and meaning in Indian sculpture and pottery.", "Clay, stone, stucco and bronze enabled different scales, movements and survival patterns; technique shaped representation while chronology and attribution limits prevent a simple progress story.", [1, 3, 4, 5, 11, 18]),
    ],
    [
        plan("How to read sculpture", [0], "Description must connect form to evidence and its limits.", "Use the six variables as the method for the whole topic."),
        plan("Lost-wax bronze and Harappan labels", [1, 2], "Technique is fact; object identity remains interpretive.", "Separate secure manufacture from disputed meaning."),
        plan("Pottery as chronological evidence", [3, 4], "Harappan Red Ware, Black-and-Red Ware and NBPW are distinct.", "Build a material-culture sequence."),
        plan("Yaksha and auspicious tree figures", [5], "Absorption across religions does not erase local cult roots.", "Use motif continuity without claiming unchanged meaning."),
        plan("Gandhara's layered idiom", [6], "Name Greco-Bactrian and Central Asian strands separately.", "Prepare the direct 2019 route."),
        plan("Mathura's indigenous breadth", [7], "Religious plurality is a key discriminator.", "Contrast material, scope and attribute grammar."),
        plan("Amaravati's narrative dynamism", [8], "Do not borrow Gandhara's foreign-influence formula.", "Complete the three-school comparison."),
        plan("Aniconism and the iconic shift", [9, 10], "A symbol is not absence, and priority remains debated.", "Explain representational change cautiously."),
        plan("Gupta restraint and dating limits", [11], "Late or post-Gupta is safer for Sultanganj.", "Add a chronological bridge to southern sculpture."),
        plan("Nataraja from Aihole to Chola", [12, 13], "Distinguish origin, peak and iconographic meaning.", "Build a full named-image answer."),
        plan("Lion and bull across media", [14, 15], "Keep Harappan, Buddhist and imperial claims source-separated.", "Prepare the direct 2022 animal-symbol route."),
        plan("Nandi, Yali and Vyala", [15, 16], "Placed architecture and hybrid ornament solve different problems.", "Link iconography to temple planning."),
        plan("Sculpture as social evidence", [17], "Commissioned visibility is not representative social data.", "Prepare the direct 2022 social-life route."),
        plan("Terracotta's long material arc", [18], "Object continuity does not prove unchanged community or meaning.", "Add the pottery and living-material dimension."),
        plan("Verified PYQs and final answer spine", [19, 0], "Do not solve the provisional 2026 objective route.", "Integrate method, evidence, comparison and qualification."),
    ],
    [
        panel("Six-variable reading rail", "root-axes", ["MATERIAL -> what carving or casting permits", "POSTURE + ATTRIBUTE -> identity and action", "PATRON + SITE -> commissioned context", "COMPARISON -> similarity, difference and limit"], ["How to read sculpture"]),
        panel("Lost-wax and label firewall", "process-flow", ["WAX MODEL -> clay investment", "HEAT -> wax leaves a cavity", "MOLTEN METAL -> bronze form", "MEANING -> separate from a museum label"], ["Lost-wax bronze and Harappan labels"]),
        panel("Pottery chronology", "timeline", ["NEOLITHIC -> coarse hand-made ware", "CHALCOLITHIC -> Ahar, Malwa and Jorwe painted wares", "HARAPPAN / PGW -> separate chronological markers", "NBPW -> fine early historic tableware"], ["Pottery as chronological evidence"]),
        panel("Three-school matrix", "comparison-table", ["GANDHARA -> grey stone, Buddhist, layered influence", "MATHURA -> red stone, three religions, attributes", "AMARAVATI -> limestone, Buddhist narrative, tribhanga", "RULE -> compare on the same axes"], ["Gandhara's layered idiom", "Mathura's indigenous breadth"]),
        panel("Aniconic to iconic", "causal-system", ["EMPTY THRONE / TREE / WHEEL -> symbolic presence", "DEVOTIONAL CHANGE -> human image becomes central", "GANDHARA + MATHURA -> overlapping early-CE contexts", "CAUTION -> no uncontested sole origin"], ["Aniconism and the iconic shift"]),
        panel("Gupta bridge", "comparison", ["SARNATH -> cream sandstone", "BODY -> subtle modelling and thin drapery", "SULTANGANJ -> late or post-Gupta caution", "BRIDGE -> restraint before denser temple programmes"], ["Gupta restraint and dating limits"]),
        panel("Nataraja chronology", "timeline", ["AIHOLE -> early known antecedent", "CHOLA -> canonical portable bronze", "TEMPLE PROCESSION -> ritual mobility", "RULE -> peak is not origin"], ["Nataraja from Aihole to Chola"]),
        panel("Nataraja attribute map", "spatial-map", ["DAMARU / FIRE -> creation and destruction", "ABHAYA / RAISED FOOT -> reassurance and release", "APASMARA -> ignorance subdued", "AUREOLE -> recurring time"], ["Nataraja from Aihole to Chola"]),
        panel("Lion-bull evidence ladder", "evidence-table", ["HARAPPAN -> bull visible, meaning unrecoverable", "RAMPURVA -> inscribed lion, uninscribed bull", "SARNATH -> animals inside a Buddhist-imperial system", "TEMPLE -> Nandi, Yali and Vyala gain placed roles"], ["Lion and bull across media"]),
        panel("Temple animal placement", "comparison-table", ["NANDI -> axial pavilion before Shiva", "YALI -> composite guardian on southern pillars", "VYALA -> lion-bodied hybrid at Khajuraho", "DISTINCTION -> building, guardian and motif"], ["Nandi, Yali and Vyala"]),
        panel("Social-evidence test", "decision-tree", ["FIGURE -> dancer, musician, teacher or couple", "PATRON -> selected what became visible", "CLAIM -> valued activity or ritual idiom", "LIMIT -> not a census of society"], ["Sculpture as social evidence"]),
        panel("Sculpture answer spine", "answer-spine", ["DEFINE -> school, object or symbol", "EVIDENCE -> material, posture, attribute and site", "COMPARE -> period or regional workshop", "QUALIFY -> attribution, priority and social inference"], ["Verified PYQs and final answer spine"]),
    ],
    ["cire-perdue", "Northern Black Polished Ware", "Shalabhanjika", "Gandhara", "Mathura", "Amaravati", "empty throne", "Sarnath", "Ravana Phadi", "Nataraja", "Apasmara", "Rampurva", "Nandi mandapa", "Yali", "Vyala", "terracotta"],
    "Three direct GS-I Mains demands are verified in the 2018-2023 routing ledger: 2019 Gandhara external elements, 2022 medieval temple sculpture as social evidence, and 2022 lion-bull significance. The 2026 empty-seat objective route has only a provisional key and is retained unsolved.",
    [
        ("2019", "GS-I", "Highlight the Central Asian and Greco-Bactrian elements in Gandhara art. (Answer in 150 words)", "Verified routed direct Mains demand.", "Separate Greco-Bactrian body modelling, wavy hair, pleated drapery and workshop material from Central Asian Kushana patronage and layered Parthian-Bactrian transmission; retain the Buddhist subject and add one Mathura contrast."),
        ("2022", "GS-I", "Medieval Indian temple sculptures represent the social life of those days. How will you explain this statement? (Answer in 150 words)", "Verified routed direct Mains demand.", "Use dancers, musicians, teachers, couples and ritual scenes as patron-selected registers; apply material, posture and site context; qualify that commissioned temple images are not demographic photographs."),
        ("2022", "GS-I", "Discuss the significance of the lion and bull figures in Indian mythology, art and architecture. (Answer in 250 words)", "Verified routed direct Mains demand.", "Keep mythology, art and architecture as separate legs; use Harappan bull caution, Rampurva and Sarnath, Nandi mandapas and Yali-Vyala programmes; close with the national-emblem continuity without inventing meanings."),
    ],
    extra=[
        "basic/02_Mauryan-Buddhist-Jain-and-Rock-Cut-Heritage.md",
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "advanced/03_Temple-Architecture-and-Chandella-Khajuraho.md",
    ],
)


TOPIC_07 = common.topic(
    7,
    "Painting Traditions",
    "07_Painting-Traditions",
    "07_Painting-Traditions_Complete-Topic-Package.md",
    [
        ("Shadanga of painting", "Roopbheda, Pramana, Bhava, Lavanya Yojana, Sadrishya and Varnikabhanga organise appearance, proportion, expression, composition, resemblance and brush-colour treatment."),
        ("Rock-art foundation", "Bhimbetka and Lakhudiyar establish a prehistoric rock-art beginning, while a petroglyph is an engraving and must not be confused with a painted image."),
        ("Ajanta technique", "Ajanta pigments were generally applied after prepared plaster dried, so fresco secco or tempera is safer than calling the murals true wet fresco."),
        ("Bagh evidence", "Bagh lies on the Baghni river in Dhar district; Cave 4 is Rang Mahal, while Hallisalasya is attributed to Bagh paintings generally and not to a specified cave."),
        ("Pallava mural survival", "The principal surviving Pallava mural locations are Kailasanatha at Kanchipuram and Talagishwara at Panamalai; survival scarcity is not proof of low original production."),
        ("Chola mural record", "Vijaya Cholishwaram and Brihadishvara preserve the principal Chola wall-painting record, with Rajaraja and Karuvur Devar and later Nayaka superimposition at Brihadishvara."),
        ("Format-patronage relation", "Monumental murals require architectural sponsorship and collective viewing, whereas portable manuscripts and albums enable smaller royal or elite commissions and regional dispersal."),
        ("Pala and Western Indian manuscripts", "Pala Buddhist and Western Indian or Jain manuscript traditions precede Mughal miniatures and preserve devotional page-based painting under monastic and mercantile patronage."),
        ("Akbar atelier", "Akbar's karkhana produced large illustrated manuscripts through collaborative labour by artists drawn from multiple regions and religious backgrounds."),
        ("Jahangir shift", "Jahangir-era painting emphasised album pages, individual portraiture and natural history, with Mansur associated with flora-fauna observation."),
        ("Regional dispersal mechanism", "Reduced imperial patronage and artist mobility helped regional Rajasthani and Pahari centres adapt shared miniature resources rather than develop as sealed ethnic styles."),
        ("Kishangarh identification", "Bani Thani belongs to the Kishangarh school and is associated with Nihal Chand; it must not be assigned to Kangra, Bundi or Jaipur."),
        ("Pahari sequence", "Basohli is marked by intense colour and bold line, while Guler and Kangra move toward softer naturalism and lyrical Krishna-poetry themes."),
        ("Deccani distinction", "Deccani miniatures use saturated colour, elongated figures and fantastic landscapes within Persianate-Deccan court culture; shared Persian roots do not make them Mughal."),
        ("Tanjore and Mysore", "Tanjore painting is identified by devotional icons, gesso relief and gold coating; Mysore is a distinct South Indian tradition and must not be treated as its synonym."),
        ("Company and bazaar publics", "Company painting served colonial patrons and documentation, whereas bazaar and Kalighat production addressed pilgrimage and commercial publics; neither is a single uniform school."),
        ("Ravi Varma transition", "Raja Ravi Varma applied European academic realism to Indian mythological subjects and expanded their print circulation, creating the immediate contrast used by Bengal School critics."),
        ("Bengal School programme", "Abanindranath Tagore's Bengal School used wash, subdued colour and Ajanta, Mughal and Rajasthani resources as a nationalist reaction to colonial and academic idioms."),
        ("Folk-painting specificity", "Madhubani, Warli, Pattachitra, Kalamkari, Gond, Phad and Thangka differ by region, support, community, ritual function and market; folk and tribal are not homogeneous labels."),
        ("Painting PYQ and live boundary", "The verified routes are objective demands on Bani Thani, Jahangir-era portraiture and provisional Hallisalasya; Lalit Kala Akademi's 2025 exhibition is a living institutional link, not historical-style evidence."),
    ],
    [
        "Do not call every Indian mural a true fresco.",
        "Do not assign Hallisalasya to Bagh Cave 4 or to a modern classical form.",
        "Do not silently choose between the source's two Bagh dating ranges.",
        "Do not treat few surviving Pallava or Chola murals as proof of a minor tradition.",
        "Do not make miniature painting begin with the Mughals.",
        "Do not describe Mughal manuscripts as the work of one isolated artist.",
        "Do not attribute Bani Thani to any school other than Kishangarh.",
        "Do not collapse Basohli, Guler and Kangra into one Pahari style.",
        "Do not treat Deccani painting as a Mughal sub-school.",
        "Do not equate Tanjore and Mysore painting.",
        "Do not describe the Bengal School as a rejection of every external exchange.",
        "Do not homogenise folk and tribal painting traditions.",
        "Do not invent pigments, dimensions, artist-work pairs or GI dates.",
        "Do not infer answers for objective routes whose local key is unavailable or provisional.",
    ],
    [
        (10, "Explain why survival bias matters when assessing Indian mural traditions.", "The small Pallava and Chola survival record constrains quantity claims but cannot measure original production; named fragments, literary evidence and superimposed layers must be read together.", [2, 4, 5]),
        (10, "Distinguish Akbar-era manuscript painting from Jahangir-era album painting.", "The shift is from collaborative narrative manuscript series to refined album portraiture and natural history, reflecting a changed patronal gaze rather than a complete workshop rupture.", [8, 9]),
        (15, "Trace the evolution of Indian painting through changes of format and audience.", "Rock surface, cave and temple wall, manuscript, album, canvas and print each altered portability, patronage, subject and viewing public.", [1, 6, 7, 15, 16]),
        (15, "Compare major Rajasthani, Pahari and Deccani miniature idioms.", "Common miniature resources were regionally reworked through palette, line, theme and court ecology; Kishangarh, Basohli-Kangra and Deccani distinctions should be made on identical axes.", [10, 11, 12, 13]),
        (20, "Assess the relationship between patronage and stylistic change in Indian painting.", "Institutional mural sponsorship, monastic manuscript production, imperial karkhanas, regional courts, colonial commissions and nationalist publics successively changed format and subject without creating sealed traditions.", [6, 7, 8, 9, 10, 15, 17]),
        (20, "Discuss modern, folk and tribal painting as living cultural systems.", "Ravi Varma, the Bengal School and community traditions show different relations among technique, market, ritual, nationalism and institutions; protection cannot reduce them to decorative survivals.", [16, 17, 18, 19]),
    ],
    [
        plan("Painting vocabulary and rock art", [0, 1], "Separate painted images from petroglyphs and technical limbs.", "Establish the reading vocabulary."),
        plan("Ajanta's dry-plaster technique", [2], "Fresco secco is safer than true fresco.", "Use technique as a close-option discriminator."),
        plan("Bagh and Hallisalasya", [3], "Do not assign the dance to Cave 4.", "Prepare the provisional 2026 route without an answer letter."),
        plan("Pallava and Chola mural survival", [4, 5], "Survival is not total historical production.", "Support dynastic art answers with a provenance caveat."),
        plan("From wall to portable page", [6, 7], "Format change does not erase devotional continuity.", "Turn chronology into a patronage argument."),
        plan("Akbar's collaborative atelier", [8], "Court style is collective workshop production.", "Explain manuscript scale and labour."),
        plan("Jahangir's album and natural history", [9], "A shift of emphasis is not a total break.", "Prepare the routed 2019 objective distinction."),
        plan("Artist mobility and regional schools", [10], "Regional identity is porous, not sealed.", "Explain diffusion after imperial contraction."),
        plan("Kishangarh and Bani Thani", [11], "Keep school and artist attribution exact.", "Prepare the routed 2018 identification."),
        plan("Pahari and Deccani discriminators", [12, 13], "Compare palette, line, theme and court ecology.", "Build close-option elimination."),
        plan("Tanjore and Mysore", [14], "Gold-gesso is a Tanjore marker, not a generic southern feature.", "Distinguish South Indian miniature traditions."),
        plan("Company, bazaar and colonial publics", [15], "Different buyers produced different images.", "Connect market and documentation."),
        plan("Ravi Varma and Bengal School", [15, 16, 17], "Nationalist reaction still involved selective exchange.", "Build the modern-painting sequence."),
        plan("Folk and tribal production systems", [18], "Region, support and community must remain specific.", "Add living-heritage analysis."),
        plan("PYQ audit and living institutional link", [19, 6], "The 2025 exhibition proves current institutional activity only.", "Close with a bounded current linkage."),
    ],
    [
        panel("Painting reading axes", "root-axes", ["FORMAT -> rock, wall, page, album or canvas", "TECHNIQUE -> engraving, dry plaster, wash or print", "PATRON -> monastery, court, market or community", "AUDIENCE -> collective, private or mass"], ["Painting vocabulary and rock art"]),
        panel("Mural technique firewall", "comparison", ["AJANTA -> prepared plaster, pigment after drying", "TRUE FRESCO -> pigment into wet plaster", "BAGH -> do not transfer Ajanta's label automatically", "RULE -> technique must be site-specific"], ["Ajanta's dry-plaster technique"]),
        panel("Bagh identification card", "evidence-table", ["SITE -> Baghni river, Dhar district", "CAVE 4 -> Rang Mahal, Jataka murals", "HALLISALASYA -> Bagh paintings generally", "LIMIT -> no modern-form equivalence"], ["Bagh and Hallisalasya"]),
        panel("Southern mural survival", "timeline", ["PALLAVA -> Kanchipuram and Panamalai", "PANDYA -> Sittanavasal bridge", "CHOLA -> Vijaya Cholishwaram and Brihadishvara", "NAYAKA -> later superimposition"], ["Pallava and Chola mural survival"]),
        panel("Format-patronage shift", "causal-system", ["MONUMENTAL WALL -> institutional sponsor", "MANUSCRIPT -> portable devotional page", "ALBUM -> private connoisseurial patron", "PRINT / CANVAS -> market and public"], ["From wall to portable page"]),
        panel("Mughal atelier change", "comparison-table", ["AKBAR -> narrative manuscript series", "WORKSHOP -> collaborative karkhana", "JAHANGIR -> album portrait and natural history", "CONTINUITY -> mobile trained artists"], ["Akbar's collaborative atelier", "Jahangir's album and natural history"]),
        panel("Regional miniature map", "spatial-map", ["KISHANGARH -> Bani Thani, Nihal Chand", "BASOHLI -> bold line and intense colour", "GULER / KANGRA -> lyrical naturalism", "DECCAN -> saturated Persianate court idiom"], ["Kishangarh and Bani Thani", "Pahari and Deccani discriminators"]),
        panel("South Indian distinction", "comparison", ["TANJORE -> gesso relief and gold coating", "MYSORE -> separate court tradition", "DEVOTIONAL ICON -> shared broad purpose", "TRAP -> shared region is not identity"], ["Tanjore and Mysore"]),
        panel("Colonial public matrix", "comparison-table", ["COMPANY -> European patron and documentation", "BAZAAR / KALIGHAT -> commercial public", "RAVI VARMA -> academic realism and prints", "BENGAL SCHOOL -> nationalist wash idiom"], ["Company, bazaar and colonial publics", "Ravi Varma and Bengal School"]),
        panel("Folk-painting discriminator", "comparison-table", ["MADHUBANI -> Mithila line-and-fill", "WARLI -> white geometric figures on earth ground", "PATTACHITRA -> Odisha cloth or palm leaf", "KALAMKARI -> narrative textile process"], ["Folk and tribal production systems"]),
        panel("Survival-bias ladder", "hierarchy", ["SURVIVING OBJECT -> direct evidence", "LITERARY REFERENCE -> practice was known", "MISSING WALL -> preservation gap", "VERDICT -> do not equate survival with production"], ["Pallava and Chola mural survival"]),
        panel("Painting answer spine", "answer-spine", ["DEFINE -> format and technique", "TRACE -> patron and audience change", "COMPARE -> named school on common axes", "QUALIFY -> survival, attribution and current status"], ["PYQ audit and living institutional link"]),
    ],
    ["Shadanga", "petroglyph", "fresco secco", "Baghni", "Hallisalasya", "Kailasanatha", "Brihadishvara", "karkhana", "Jahangir", "Bani Thani", "Kishangarh", "Basohli", "Kangra", "Deccani", "Tanjore", "Bengal School", "Madhubani", "Warli"],
    "No direct GS-I Mains PYQ is routed to painting in the audited ledgers. The package retains the verified 2018 Bani Thani and 2019 Jahangir objective routes without inferring unavailable keys, and the 2026 Hallisalasya route without inferring its provisional answer.",
    [],
    live_sources=["https://lalitkala.gov.in/event_details/317"],
    current_note=("Lalit Kala Akademi's official page was rechecked on 2026-09-04. It records that the 64th National Exhibition of Art award ceremony was held on 24 September 2025 and awards were conferred on 20 artists. The linkage is used only for the living national visual-arts institution, not to infer a historical school, artwork category or stylistic claim."),
    extra=[
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "basic/12_Crafts-Textiles-Folk-and-Tribal-Traditions.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_08 = common.topic(
    8,
    "Indian Music",
    "08_Indian-Music",
    "08_Indian-Music_Complete-Topic-Package.md",
    [
        ("Saptaswara", "Shadja, Rishabha, Gandhara, Madhyama, Panchama, Dhaivata and Nishada form the seven-note base shared across Indian classical traditions."),
        ("Thaat definition", "A thaat is an unsung Hindustani parent scale of seven notes stated in ascending order, without vaadi-samvadi or an independent emotional identity."),
        ("Raga definition", "A raga is a melodic entity with aaroha-avaroha, characteristic note hierarchy and phrase, five, six or seven notes, and aesthetic or temporal associations."),
        ("Melakarta and janya", "Carnatic theory uses seventy-two sampurna melakarta or janaka parent ragas, with janya ragas derived from them; melakarta is not another name for a Hindustani thaat."),
        ("Shared-root comparison", "Hindustani and Carnatic music share older theory but differ in classification, repertoire, ornament and performance sequence; neither is improvisation-free or culturally pure."),
        ("Rasa-raga linkage", "Music uses the wider nine-rasa aesthetic vocabulary by associating melodic treatment with mood, time or season; such associations are tradition-specific rather than universal acoustical laws."),
        ("Treatise contribution chain", "Bharata links music with drama, Matanga's Brihaddeshi defines raga, Sharngadeva's Sangita Ratnakara precedes bifurcation, and Venkatamakhin systematises melakarta."),
        ("Modern pedagogy", "V.N. Bhatkhande systematised thaat-based Hindustani pedagogy, while V.D. Paluskar founded Gandharva Mahavidyalaya in 1901 to teach and transmit classical music."),
        ("Gharana as transmission ecology", "A gharana is a family or lineage-based structure that concentrates specialised technique, ties it to patronage and reproduces it through descent or long apprenticeship."),
        ("Named gharana distinctions", "Dagar centres Dhrupad, Darbhanga balances alaap and layakari, Gwalior is the oldest khayal gharana, Kirana stresses swara, Agra blends khayal and Dhrupad-Dhamar, and Patiala favours thumri-ghazal."),
        ("Dhrupad and khayal", "Dhrupad is an older austere vocal form with vani and gharana lineages, while khayal permits a different improvisational and compositional field; one is not merely the fast version of the other."),
        ("Aurangzeb correction", "Imperial court singing was curtailed, but instruments, elite patronage and music writing continued; Aurangzeb played the veena and Sadarang-Adarang later strengthened khayal under Muhammad Shah."),
        ("Carnatic composer bank", "Annamacharya praised Venkateswara, Purandara Dasa is honoured for pedagogic and repertorial foundations, and Tyagaraja, Muthuswami Dikshitar and Syama Sastri form the Carnatic Trinity."),
        ("Kriti and concert anatomy", "A kriti is a composed Carnatic form set to raga and tala with pallavi, anupallavi and charana; concerts also use varnam, alapana, niraval, kalpana swara, tanam and tillana."),
        ("Four instrument families", "Tata are chordophones, Sushira aerophones, Avanaddha membranophones and Ghana idiophones; the presence of a stretched membrane separates Avanaddha from solid-bodied Ghana."),
        ("Instrument identification limits", "Santoor is a struck string instrument, ghatam and jaltarang are Ghana, tabla and mridangam are Avanaddha, and no inventor or unsupported invention date should be attached to them."),
        ("Modern musician precision", "The owner verifies selected instrument, tradition and Bharat Ratna pairings but prohibits adding unsupported gurus, gharanas, films or awards; Ravi Shankar is not assigned a gharana there."),
        ("Folk-music function", "Baul, Pandavani, Panihari, Lavani, Powada, Khongjom Parba and other forms are best distinguished by region, occasion, theme and transmission rather than ranked below classical music."),
        ("Institutional recognition boundary", "Sangeet Natak Akademi award lists are dynamic official recognition records; an award does not define a raga, gharana, instrument family or the historical value of a tradition."),
        ("Music PYQ audit", "Verified routes are objective demands on Tyagaraja-Annamacharya, Tansen, Gandharva Mahavidyalaya and two provisional 2026 questions; no direct routed Mains demand is invented."),
    ],
    [
        "Do not use thaat and raga as synonyms.",
        "Do not equate the seventy-two melakartas with Bhatkhande's ten thaats.",
        "Do not say Carnatic music lacks improvisation.",
        "Do not turn Hindustani and Carnatic into foreign-versus-pure essences.",
        "Do not define a gharana as only a region or only a family name.",
        "Do not assign every gharana the same stylistic emphasis.",
        "Do not say Aurangzeb eliminated all music.",
        "Do not claim Tansen certainly invented named ragas.",
        "Do not make Tyagaraja and Annamacharya contemporaries.",
        "Do not say Annamacharya's compositions praise Krishna rather than Venkateswara.",
        "Do not credit Amir Khusrau with certainly inventing sitar, tabla, khayal or qawwali.",
        "Do not file ghatam or jaltarang as membranophones.",
        "Do not invent Mallikarjun Mansur's gharana from nearby names.",
        "Do not infer objective-answer letters where the ledger withholds them.",
    ],
    [
        (10, "Distinguish thaat, raga and melakarta as systems of melodic classification.", "Thaat and melakarta are parent-scale devices in different traditions, while raga is the performed melodic entity; note count, phrase, hierarchy and emotional identity prevent interchangeability.", [1, 2, 3]),
        (10, "Explain the gharana as a system of musical transmission.", "A gharana concentrates technique through lineage and apprenticeship, links skill to patronage and survives political change by moving into concert, radio, teaching and recording.", [8, 9]),
        (15, "Compare Hindustani and Carnatic music on common analytical axes.", "The traditions share theory but organise parent scales, improvisation, repertoire, patronage and performance sequence differently; comparison must reject foreign-pure and fixed-improvised binaries.", [4, 5, 6, 12, 13]),
        (15, "Assess the role of treatises and modern institutions in standardising Indian music.", "Texts fixed concepts such as raga and melakarta, while Bhatkhande, Paluskar and institutions widened transmission beyond hereditary circles but also standardised plural practice.", [6, 7, 18]),
        (20, "Trace changing patronage and transmission in Indian classical music.", "Temple, court, household, gharana, sabha, festival, school, radio and recording redirected traditions rather than simply replacing one another; the Aurangzeb case tests this continuity.", [8, 11, 12, 13, 18]),
        (20, "Discuss the relationship among classical theory, instruments and folk function in Indian music.", "Scale and raga theory, instrument sound mechanisms and occasion-bound folk repertoires are distinct but interacting systems; none supplies a hierarchy of cultural worth.", [0, 5, 14, 15, 17]),
    ],
    [
        plan("Swara, thaat and raga", [0, 1, 2], "Parent scale and performed melody are distinct.", "Build the foundational theory vocabulary."),
        plan("Melakarta and janya logic", [3], "Do not map seventy-two melakartas onto ten thaats.", "Prepare system-comparison questions."),
        plan("Hindustani and Carnatic shared roots", [4], "Reject foreign-versus-pure and improvisation-versus-fixed binaries.", "Create a balanced comparison thesis."),
        plan("Raga, rasa and time", [5], "Associations are aesthetic conventions, not universal physical laws.", "Add the cross-performing-arts dimension."),
        plan("Treatises by contribution", [6], "A title list without conceptual contribution earns little.", "Build a chronological theory spine."),
        plan("Bhatkhande, Paluskar and pedagogy", [7], "Institutional transmission widened access while standardising practice.", "Prepare the 2025 objective route."),
        plan("Gharana as labour and patronage", [8], "A gharana is more than a stylistic label.", "Explain transmission as social organisation."),
        plan("Named gharana discriminators", [9], "Do not swap exponents or specialisations.", "Build Prelims elimination."),
        plan("Dhrupad, khayal and court change", [10, 11], "Court restriction was redirection, not extinction.", "Correct the Aurangzeb cliché."),
        plan("Carnatic composers and patrons", [12], "Keep Venkateswara, Krishna and the Trinity distinct.", "Prepare the 2018 objective route."),
        plan("Kriti and concert sequence", [13], "Do not invent a formal definition of kirtana.", "Explain form and manodharma."),
        plan("Instrument families by mechanism", [14, 15], "Membrane, air, string and solid-body tests control classification.", "Prepare instrument identification."),
        plan("Modern musicians and source limits", [16], "Do not fill recorded gaps from memory.", "Model attribution discipline."),
        plan("Folk music by occasion and region", [17], "Difference of function is not hierarchy.", "Add living and historical memory functions."),
        plan("SNA linkage and PYQ audit", [18, 19], "A current award list does not prove musical attributes.", "Close with transparent objective-route handling."),
    ],
    [
        panel("Melodic hierarchy", "hierarchy", ["SAPTASWARA -> shared note base", "THAAT / MELAKARTA -> parent-scale systems", "RAGA -> performed melodic identity", "TALA -> rhythmic cycle framing performance"], ["Swara, thaat and raga", "Melakarta and janya logic"]),
        panel("Thaat-raga firewall", "comparison-table", ["THAAT -> seven-note unsung scale", "RAGA -> phrase, hierarchy and melodic identity", "MELAKARTA -> Carnatic sampurna parent", "JANYA -> derived Carnatic raga"], ["Swara, thaat and raga", "Melakarta and janya logic"]),
        panel("Two-tradition matrix", "comparison", ["HINDUSTANI -> thaat, gharana, alap and khayal", "CARNATIC -> melakarta, kriti and manodharma", "SHARED -> swara, raga, tala and older theory", "REJECT -> foreign versus pure"], ["Hindustani and Carnatic shared roots"]),
        panel("Treatise contribution chain", "timeline", ["BHARATA -> music with drama and rasa", "MATANGA -> early raga definition", "SHARNGADEVA -> pre-bifurcation synthesis", "VENKATAMAKHIN -> melakarta system"], ["Treatises by contribution"]),
        panel("Modern pedagogy shift", "causal-system", ["HEREDITARY LINEAGE -> concentrated technique", "PALUSKAR 1901 -> institutional teaching", "BHATKHANDE -> pedagogic classification", "RESULT -> wider access and standardisation"], ["Bhatkhande, Paluskar and pedagogy"]),
        panel("Gharana mechanism", "process-flow", ["HOUSEHOLD / LINEAGE -> specialised skill", "PATRON -> court or elite support", "APPRENTICESHIP -> controlled transmission", "NEW MEDIA -> concert, radio and recording"], ["Gharana as labour and patronage"]),
        panel("Gharana discriminator", "comparison-table", ["DAGAR -> Dhrupad", "GWALIOR -> old khayal lineage", "KIRANA -> precise swara", "PATIALA -> thumri and ghazal"], ["Named gharana discriminators"]),
        panel("Aurangzeb correction rail", "decision-tree", ["COURT SINGING -> curtailed", "INSTRUMENTS -> continued", "WOMEN / NOBLES -> retained patronage", "MUHAMMAD SHAH -> khayal strengthened later"], ["Dhrupad, khayal and court change"]),
        panel("Carnatic composer map", "hierarchy", ["ANNAMACHARYA -> Venkateswara sankirtanas", "PURANDARA DASA -> pedagogic foundation", "TYAGARAJA + DIKSHITAR + SYAMA SASTRI -> Trinity", "VENKATAMAKHIN -> theory and composition"], ["Carnatic composers and patrons"]),
        panel("Instrument mechanism test", "comparison-table", ["TATA -> vibrating string", "SUSHIRA -> vibrating air column", "AVANADDHA -> stretched membrane", "GHANA -> solid body vibrates"], ["Instrument families by mechanism"]),
        panel("Folk-function map", "spatial-map", ["PANDAVANI -> epic memory, Chhattisgarh", "PANIHARI -> water and women's labour, Rajasthan", "POWADA -> heroic memory, Maharashtra", "KHONGJOM PARBA -> battle memory, Manipur"], ["Folk music by occasion and region"]),
        panel("Music answer spine", "answer-spine", ["DEFINE -> note, scale, raga or form", "COMPARE -> grammar, repertoire and patronage", "EVIDENCE -> treatise, gharana, composer or instrument", "QUALIFY -> attribution, key and current-list limits"], ["SNA linkage and PYQ audit"]),
    ],
    ["Saptaswara", "thaat", "raga", "melakarta", "janya", "Brihaddeshi", "Sangita Ratnakara", "Gandharva Mahavidyalaya", "gharana", "Dhrupad", "khayal", "Tyagaraja", "Annamacharya", "kriti", "Tata Vadya", "Sushira Vadya", "Avanaddha", "Ghana Vadya"],
    "No direct GS-I Mains PYQ is routed to Indian music in the audited ledgers. Verified objective routes are retained for 2018 Tyagaraja-Annamacharya, 2019 Tansen, 2025 Gandharva Mahavidyalaya, and the provisional 2026 raga-equivalence and Mallikarjun Mansur demands; no withheld answer is inferred.",
    [],
    live_sources=["https://sangeetnatak.gov.in/award-honours/awardees"],
    current_note=("Sangeet Natak Akademi's official awardees page was rechecked on 2026-09-04 and displayed a 2025 award record. It is used only to verify that the national performing-arts recognition list is a live, updateable official record; no musician's gharana, repertoire, instrument classification or unsourced award claim is inferred from it."),
    extra=[
        "basic/09_Indian-Dance.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/13_Religion-Philosophy-and-Cultural-Synthesis.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_09 = common.topic(
    9,
    "Indian Dance",
    "09_Indian-Dance",
    "09_Indian-Dance_Complete-Topic-Package.md",
    [
        ("Natya Veda framework", "The layered Natyashastra tradition presents performance as a composite of text, enactment, music and rasa; a broad late-BCE to early-CE range is safer than a falsely exact composition date."),
        ("Lasya and Tandava", "Lasya and Tandava identify graceful-expressive and vigorous-rhythmic aspects of dance; they are qualities of movement, not rigid rules limiting performers by gender."),
        ("Nritta, Nritya and Natya", "Nritta is pure rhythmic movement, Nritya expression through gesture and emotion, and Natya dramatic representation; the three terms are not interchangeable."),
        ("Rasa vocabulary", "Shringara, Roudra, Bibhatsa, Veera, Shanta, Haasya, Karuna, Bhayanaka and Adbhuta form the nine-rasa performance vocabulary shared with music and theatre."),
        ("Hasta and karana", "A hasta or mudra is a codified hand gesture, while a karana is a coordinated whole-body movement unit; the famous number 108 belongs to karanas, not basic mudras."),
        ("Eight-form SNA list", "The Sangeet Natak Akademi list contains Bharatanatyam, Kuchipudi, Kathakali, Mohiniyattam, Kathak, Odissi, Manipuri and Sattriya."),
        ("Institutional-list distinction", "The owner separately records a Ministry of Culture list of nine including Chhau; it must not be merged with the SNA eight-form list or with UNESCO inscriptions."),
        ("Bharatanatyam history", "Bharatanatyam developed from Sadir or Dashiattam repertories transmitted by hereditary practitioners and was reconfigured through anti-nautch disruption and named revival actors."),
        ("Bharatanatyam recital", "The Tanjore Quartet codified a recital sequence including Alarippu, Jatiswaram, Shabdam, Varnam, Padam, Jawali and Thillana."),
        ("Kuchipudi identity", "Kuchipudi is linked to Kuchelapuram in Andhra Pradesh, travelling actor traditions and Siddhendra; its dance-drama origin distinguishes it from a temple-solo narrative."),
        ("Kathakali identity", "Kathakali is Kerala dance-drama with Attakkatha text, Manipravalam, gesture-led acting, elaborate make-up and percussion; it is not Mohiniyattam's solo lasya form."),
        ("Mohiniyattam identity", "Mohiniyattam is a Kerala solo form marked by lasya, gentle unthumped footwork and white-gold Kasavu costume; Nagabandha belongs to Manipuri, not Mohiniyattam."),
        ("Kathak identity", "Kathak combines storytelling, tatkar footwork and chakkars through temple and court histories; it should not be reduced to either a purely Mughal or purely temple form."),
        ("Odissi identity", "Odissi uses tribhanga and chowk, torso articulation, Gita Govinda repertoire and mahari-gotipua histories; its mobile-sculpture analogy does not prove an unchanged ancient choreography."),
        ("Manipuri identity", "Manipuri Vaishnava performance emphasises raslila, pung or cholom traditions, restrained facial display and Nagabandha rather than Odissi's torso-led tribhanga."),
        ("Sattriya identity", "Sattriya developed in Assam's sattra and ankiya-nat context associated with Sankaradeva, with mati-akhora as a movement base."),
        ("Revival and reconfiguration", "Twentieth-century revival preserved repertories but also relocated authority from hereditary communities to institutions and elite stages; continuity and rupture must be argued together."),
        ("Dance-sculpture vocabulary", "Dancer figures at Khajuraho, Konark, Ellora and Chidambaram share posture and gesture vocabularies with dance, but sculpture proves an idiom of movement rather than a complete named choreography."),
        ("Recognition tracks", "SNA classical recognition and UNESCO Intangible Cultural Heritage inscription are different institutional acts; a form may hold one, both or neither."),
        ("Garba official linkage", "UNESCO describes Garba as a ritual and devotional Navaratri dance around a lit earthen pot or image of Amba; its 2023 inscription is a folk-dance linkage, not SNA classical status."),
    ],
    [
        "Do not assign a falsely exact date to the Natyashastra.",
        "Do not make Lasya and Tandava gender-exclusive rules.",
        "Do not interchange Nritta, Nritya and Natya.",
        "Do not equate 108 karanas with 108 mudras.",
        "Do not merge the SNA eight-form list with a Ministry list including Chhau.",
        "Do not conflate SNA recognition with UNESCO ICH inscription.",
        "Do not present Bharatanatyam as unchanged from antiquity.",
        "Do not erase hereditary practitioners from revival narratives.",
        "Do not confuse Kuchipudi's dance-drama origin with Bharatanatyam's solo history.",
        "Do not confuse Kathakali with Mohiniyattam because both are from Kerala.",
        "Do not put Nagabandha in Mohiniyattam.",
        "Do not treat Kathak as exclusively a Mughal court creation.",
        "Do not use shared Vaishnava themes alone to identify Odissi, Manipuri or Sattriya.",
        "Do not claim temple sculpture preserves the choreography of a modern named form.",
    ],
    [
        (10, "Distinguish Nritta, Nritya and Natya and explain their analytical value.", "The three categories separate pure rhythmic movement, expressive gesture and dramatic representation, allowing a performance to be analysed as a composite rather than called simply dance.", [0, 2, 3]),
        (10, "Why must SNA classical recognition be separated from UNESCO ICH inscription?", "One is national canon formation by a cultural academy and the other treaty-based international safeguarding; neither alone reconstructs a form's social history.", [5, 6, 18, 19]),
        (15, "Compare Bharatanatyam and Kuchipudi through origin, format and transmission.", "A Sadir-derived solo recital and an itinerant dance-drama tradition now share classical status, but their social origins, stage grammars and revival histories remain distinct.", [7, 8, 9, 16]),
        (15, "Compare Odissi, Manipuri and Sattriya using close-option discriminators.", "Tribhanga-chowk and mahari-gotipua history, pung-led restrained raslila, and sattra-ankiya-nat institutions distinguish three devotional eastern forms more securely than shared Vaishnava themes.", [13, 14, 15]),
        (20, "Critically assess twentieth-century revival and institutionalisation of Indian classical dance.", "Revival preserved repertoire, widened stages and created recognised canons, but selectively reconstructed older practices and displaced or obscured hereditary communities.", [5, 6, 7, 16, 18]),
        (20, "Examine the relationship among dance, sculpture, music and theatre in Indian aesthetics.", "The Natyashastra's composite-art framework and shared rasa, gesture and movement vocabulary connect the arts, while each medium preserves different evidence and cannot prove the full content of another.", [0, 1, 3, 4, 17]),
    ],
    [
        plan("Natya Veda as composite art", [0], "Use a broad textual date and distinguish prescription from practice.", "Frame dance with music, text, enactment and rasa."),
        plan("Lasya and Tandava", [1], "Qualities are not gender-exclusive rules.", "Build movement vocabulary."),
        plan("Nritta, Nritya and Natya", [2], "Keep pure movement, expression and drama distinct.", "Prepare the most common terminology test."),
        plan("Rasa, hasta and karana", [3, 4], "The number 108 belongs to karanas.", "Link aesthetic mood to gesture and body."),
        plan("Who recognises a classical form", [5, 6], "SNA, Ministry and UNESCO lists are different.", "Build institutional precision."),
        plan("Bharatanatyam's social history", [7], "Revival must retain hereditary knowledge and anti-nautch rupture.", "Prepare a critical revival answer."),
        plan("Bharatanatyam recital grammar", [8], "Do not import unsourced recital variants.", "Build sequence-based identification."),
        plan("Kuchipudi as dance drama", [9], "Kuchelapuram and itinerant actors are discriminators.", "Contrast with a solo temple-stage history."),
        plan("Kathakali and Mohiniyattam", [10, 11], "Shared Kerala origin does not erase genre difference.", "Use costume, text, troupe and footwork."),
        plan("Kathak's layered history", [12], "Avoid a single-origin court or temple story.", "Connect storytelling, tatkar and chakkars."),
        plan("Odissi's sculptural dialogue", [13], "Mobile sculpture is an analogy, not proof of unchanged choreography.", "Use tribhanga and chowk precisely."),
        plan("Manipuri and Sattriya", [14, 15], "Shared devotion needs institutional discriminators.", "Break close options with pung and sattra."),
        plan("Revival as reconfiguration", [16], "Preservation and displacement occurred together.", "Add the gender-community dimension."),
        plan("Dance figures as evidence", [17], "Sculpture preserves movement idiom, not a full repertoire.", "Support sculpture and temple questions."),
        plan("Garba and recognition boundaries", [18, 19], "UNESCO inscription is not classical-form recognition.", "Close with a directly fetched official linkage."),
    ],
    [
        panel("Composite performance root", "root-axes", ["TEXT -> narrative and dialogue", "ENACTMENT -> body, face and gesture", "MUSIC -> melody and rhythm", "RASA -> aesthetic reception"], ["Natya Veda as composite art"]),
        panel("Movement vocabulary", "comparison-table", ["LASYA -> graceful and expressive quality", "TANDAVA -> vigorous rhythmic quality", "NRITTA -> pure movement", "NRITYA / NATYA -> expression and drama"], ["Lasya and Tandava", "Nritta, Nritya and Natya"]),
        panel("Gesture firewall", "comparison", ["HASTA / MUDRA -> hand gesture", "KARANA -> whole-body movement unit", "108 -> attached to karanas", "TRAP -> do not convert the number to mudras"], ["Rasa, hasta and karana"]),
        panel("Recognition map", "institution-map", ["SNA -> eight classical forms", "MINISTRY LIST -> separately includes Chhau", "UNESCO ICH -> safeguarding inscription", "RULE -> three non-interchangeable records"], ["Who recognises a classical form"]),
        panel("Bharatanatyam change", "timeline", ["SADIR / HEREDITARY PRACTICE -> repertory base", "ANTI-NAUTCH -> disruption", "IYER + RUKMINI DEVI -> reconfiguration", "MODERN STAGE -> wider canon and new authority"], ["Bharatanatyam's social history"]),
        panel("Recital sequence", "process-flow", ["ALARIPPU -> opening", "JATISWARAM / SHABDAM -> movement and expression", "VARNAM / PADAM / JAWALI -> developed core", "THILLANA -> rhythmic close"], ["Bharatanatyam recital grammar"]),
        panel("Andhra discriminator", "comparison", ["KUCHIPUDI -> itinerant dance-drama origin", "KUCHELAPURAM -> place-name anchor", "SIDDHENDRA -> association", "BHARATANATYAM -> different solo history"], ["Kuchipudi as dance drama"]),
        panel("Kerala pair", "comparison-table", ["KATHAKALI -> Attakkatha, make-up, troupe and percussion", "MOHINIYATTAM -> solo lasya and Kasavu", "COMMON -> Kerala performance ecology", "DISTINCTION -> drama versus lyrical solo"], ["Kathakali and Mohiniyattam"]),
        panel("Eastern three-form key", "comparison-table", ["ODISSI -> tribhanga, chowk, mahari and gotipua", "MANIPURI -> pung, raslila and restrained face", "SATTRIYA -> sattra, ankiya nat and mati-akhora", "TRAP -> devotion alone cannot identify"], ["Odissi's sculptural dialogue", "Manipuri and Sattriya"]),
        panel("Dance-sculpture bridge", "causal-system", ["POSE -> movement idiom made visible", "MUDRA -> shared gestural vocabulary", "TEMPLE SITE -> patron-selected sacred context", "LIMIT -> no complete modern choreography proved"], ["Dance figures as evidence"]),
        panel("Garba official card", "evidence-table", ["OCCASION -> Navaratri", "CENTRE -> lit earthen pot or image of Amba", "MOVEMENT -> communal circular dance", "STATUS -> UNESCO ICH 2023, not SNA classical"], ["Garba and recognition boundaries"]),
        panel("Dance answer spine", "answer-spine", ["DEFINE -> component, form or recognition track", "IDENTIFY -> region and unique discriminator", "ANALYSE -> patronage, revival and community", "QUALIFY -> continuity, sculpture and status"], ["Garba and recognition boundaries"]),
    ],
    ["Natyashastra", "Lasya", "Tandava", "Nritta", "Nritya", "Natya", "karana", "Bharatanatyam", "Kuchipudi", "Kathakali", "Mohiniyattam", "Kathak", "Odissi", "Manipuri", "Sattriya", "Garba"],
    "No direct GS-I Mains PYQ is routed to Indian dance in the audited ledgers. The 2024 objective route on India's latest UNESCO ICH inclusion is retained in the owner extract with its official-key status, but the package does not infer or reproduce an answer letter.",
    [],
    live_sources=["https://ich.unesco.org/en/RL/garba-of-gujarat-01962"],
    current_note=("UNESCO's official Garba element page was rechecked on 2026-09-04. Its metadata describes Garba as a ritual and devotional Navaratri dance around a lit earthenware pot or image of Amba. The package retains the verified 2023 inscription and expressly does not convert UNESCO ICH status into SNA classical recognition or a changing 'latest Indian element' claim."),
    extra=[
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "basic/06_Sculpture-Pottery-and-Iconography.md",
        "basic/08_Indian-Music.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_10 = common.topic(
    10,
    "Theatre, Puppetry and Performance Traditions",
    "10_Theatre-Puppetry-and-Performance-Traditions",
    "10_Theatre-Puppetry-and-Performance-Traditions_Complete-Topic-Package.md",
    [
        ("Natyashastra dramaturgy", "Bharata's layered Natyashastra codifies plot, character, rasa, preliminaries and staging while narrating theatre as a Natya Veda assembled from the four Vedas."),
        ("Lokadharmi and Natyadharmi", "Lokadharmi denotes realistic representation of daily life, while Natyadharmi denotes conventional, stylised and symbolic narration."),
        ("Ten rupakas", "Nataka, Prakarana, Bhana, Prahasana, Dima, Vyayoga, Samavakara, Vithi, Ihamriga and Utsrishtikanka form the recorded ten-rupaka classification."),
        ("Sutradhar function", "In Sanskrit theatre the Sutradhar conducts preliminaries and introduces the play; in puppetry the term also evokes the string-holder and narrator."),
        ("Character and language register", "Nayaka, Nayika and Vidusaka are broad character types, and the Vidusaka's traditional Prakrit speech shows language register marking stage position."),
        ("Dramaturgical convention", "The owner records multi-act structure, rare staged tragedy, male protagonists who ordinarily achieve their aim and closure restoring order; these are prescriptive conventions, not a census of every performance."),
        ("Named decline mechanisms", "The source attributes Sanskrit theatre's contraction to writers moving toward poetry and song, difficult rule-bound Sanskrit losing reach, and changed patronage under later courts."),
        ("Kutiyattam continuity", "Kutiyattam preserves a living Kerala Sanskrit-theatre lineage with codified gesture, Sanskrit-Prakrit-Malayalam use, Nirvahana and temple-theatre institutions; Sanskrit theatre is therefore not wholly extinct."),
        ("Folk-theatre arc", "Folk theatre developed through devotional themes, romance and local heroes, and later social messages, using regional language and rural performance ecologies."),
        ("Modern proscenium and law", "Colonial urban theatre adopted commercial proscenium spaces and addressed social and political themes; the Dramatic Performances Act of 1876 demonstrates state concern with its political effect."),
        ("Parsi and political theatre", "Parsi theatre linked commercial multilingual melodrama to early cinema, while IPTA organised theatre around famine and social mobilisation; they represent different modern performance economies."),
        ("Institutional modern stage", "Prithvi Theatre, Sangeet Natak Akademi, National School of Drama and regional repertories shifted support toward touring, ticketing, grants and formal training."),
        ("Four puppetry mechanisms", "Indian puppetry is classified into string, shadow, rod and glove forms; mechanism, construction and movement must be named before region."),
        ("String-puppet distinctions", "Kathputli uses legless finger-string dolls, Kundhei uses more jointed Odissi-influenced figures, and Gombeyatta adapts Yakshagana character design with multiple puppeteers."),
        ("Shadow-puppet distinctions", "Tholu Bommalata, Togalu Gombeyatta and Ravana Chhaya project cut-outs against a lit screen; leather, opacity, scale and regional narrative practice vary."),
        ("Rod and glove distinctions", "Putul Nach and Yampuri use rods from below or behind, while Kerala Pavakoothu uses fingers inside a sleeve-like body to control head and arms."),
        ("Puppetry as archive", "References in the Mahabharata and Silappadikaram and the Bhagavad Gita's puppeteer metaphor support puppetry as a vehicle of epic, devotional and philosophical transmission, not children's entertainment alone."),
        ("Current puppetry vulnerability", "The owner documents lack of funding and captive audience as current pressures and names Anupama Hoskere, Dhaatu and a 2020 SNA Puraskar as a bounded revival example."),
        ("Martial-performance continuum", "Kalaripayattu, Silambam, Thang-ta, Gatka, Mardani Khel and Pari-khanda or Chhau-linked forms differ by weapon, pedagogy, community and degree of staged display."),
        ("Two-decline distinction", "Classical Sanskrit theatre underwent historical contraction yet retains living Kutiyattam continuity, while puppetry faces ongoing policy-actionable vulnerability; the two require different safeguarding responses."),
    ],
    [
        "Do not call Sitabenga or Jogimara the world's oldest amphitheatre as settled fact.",
        "Do not reverse Lokadharmi and Natyadharmi.",
        "Do not reconstruct the ten rupakas from faulty OCR spellings.",
        "Do not reduce Sutradhar to only a puppeteer or only a stage manager.",
        "Do not universalise prescriptive stage dimensions or conventions.",
        "Do not say Sanskrit theatre always staged tragedy like Greek drama.",
        "Do not present Sanskrit theatre as wholly extinct.",
        "Do not apply one revival narrative to every folk-theatre form.",
        "Do not confuse modern proscenium theatre with older court or temple stages.",
        "Do not interchange string, shadow, rod and glove puppetry.",
        "Do not treat Kathputli, Kundhei and Gombeyatta as identical marionettes.",
        "Do not describe puppetry only as children's entertainment.",
        "Do not invent puppeteer names, troupe names or award years.",
        "Do not treat all martial traditions as interchangeable war dances.",
    ],
    [
        (10, "Distinguish Lokadharmi and Natyadharmi and explain their dramatic use.", "The pair separates realistic representation from stylised symbolic convention and provides a method for analysing how Indian performance moves between everyday action and codified theatrical language.", [0, 1, 5]),
        (10, "Classify Indian puppetry by mechanism with named examples.", "String, shadow, rod and glove forms are defined by control technology; Kathputli, Tholu Bommalata, Putul Nach and Pavakoothu should be matched to mechanism and region.", [12, 13, 14, 15]),
        (15, "Why did Sanskrit theatre contract, and in what sense does Kutiyattam complicate a decline narrative?", "Literary, linguistic and patronage shifts weakened court Sanskrit drama, but a regional temple institution preserved living performance; contraction is therefore not extinction.", [6, 7, 19]),
        (15, "Trace the development of modern Indian theatre as a social and political medium.", "Colonial proscenium commerce, censorship, Parsi circulation, nationalist-social drama, IPTA mobilisation and post-Independence institutions created successive publics.", [8, 9, 10, 11]),
        (20, "Discuss puppetry as an archive and a vulnerable living tradition.", "Mechanism-specific regional forms transmit epics and philosophy through integrated craft, music and theatre, yet current audience and funding pressures require performer-centred safeguarding rather than museum preservation alone.", [12, 13, 14, 15, 16, 17]),
        (20, "Examine India's performance traditions as a continuum of ritual, theatre, martial practice and public communication.", "Codified Sanskrit drama, folk theatre, puppetry and martial display use different institutions and bodies but repeatedly combine narrative, music, gesture and community; analysis must preserve their distinct ecologies.", [0, 8, 16, 18, 19]),
    ],
    [
        plan("Natyashastra and dramatic modes", [0, 1], "Textual prescription is not identical to every historical performance.", "Establish the dramaturgical method."),
        plan("Rupakas and the Sutradhar", [0, 2, 3], "Keep the genre list and stage function exact.", "Build classical-theatre vocabulary."),
        plan("Character and language on stage", [4], "Prakrit use is a stage-register fact, not a social census.", "Connect role, satire and language."),
        plan("Convention and closure", [5], "Rare tragedy is a recorded convention, not universal proof.", "Explain the system through accepted rules."),
        plan("Why Sanskrit theatre contracted", [6], "The source's causes are multiple and not mutually exclusive.", "Build a causal answer."),
        plan("Kutiyattam as living continuity", [7], "Do not turn an old inscription into a claim of unchanged practice.", "Qualify the decline narrative."),
        plan("Folk theatre's changing public", [8], "Devotional, heroic and social-message phases can overlap.", "Prepare communication and change questions."),
        plan("Colonial proscenium and censorship", [9], "The 1876 Act proves concern, not total suppression.", "Link form, city and political effect."),
        plan("Parsi, IPTA and institutions", [10, 11], "Commercial, political and state-supported theatres are distinct.", "Build the modern-stage sequence."),
        plan("Four puppetry mechanisms", [12], "Name control technology before examples.", "Create the classification spine."),
        plan("String-puppet regional grammar", [13], "Jointing, legs and character design differ.", "Break close options among marionettes."),
        plan("Shadow-puppet screen grammar", [14], "Do not universalise one material or scale.", "Identify light-screen performance."),
        plan("Rod, glove and control", [15], "Rod and finger control are mechanically different.", "Complete the four-category comparison."),
        plan("Puppetry as archive and livelihood", [16, 17], "One 2020 example does not prove every form is secure.", "Connect transmission to current vulnerability."),
        plan("Martial performance and two decline types", [18, 19], "Combat, ritual and staged display must remain distinct.", "Close with differentiated safeguarding."),
    ],
    [
        panel("Dramatic root system", "root-axes", ["PLOT -> codified progression", "CHARACTER -> Nayaka, Nayika and Vidusaka", "RASA -> audience reception", "STAGE -> ritual opening and convention"], ["Natyashastra and dramatic modes"]),
        panel("Dramatic-mode firewall", "comparison", ["LOKADHARMI -> realistic daily-life representation", "NATYADHARMI -> stylised symbolic narration", "PERFORMANCE -> may combine both", "TRAP -> do not reverse the pair"], ["Natyashastra and dramatic modes"]),
        panel("Sutradhar role chain", "process-flow", ["PRELIMINARIES -> ritual preparation", "INTRODUCTION -> time, place and play", "STAGE MANAGEMENT -> performance order", "PUPPETRY -> narrator and holder-of-strings sense"], ["Rupakas and the Sutradhar"]),
        panel("Character-language map", "comparison-table", ["NAYAKA -> hero type", "NAYIKA -> heroine type", "VIDUSAKA -> comic and satirical friend", "PRAKRIT -> marked speech register"], ["Character and language on stage"]),
        panel("Decline and survival", "causal-system", ["WRITERS SHIFT -> poetry and song", "LANGUAGE BARRIER -> Sanskrit loses reach", "PATRONAGE SHIFT -> court ecology changes", "KUTIYATTAM -> regional living continuity"], ["Why Sanskrit theatre contracted", "Kutiyattam as living continuity"]),
        panel("Folk-theatre arc", "timeline", ["DEVOTIONAL -> early regional themes", "ROMANCE / HERO -> local narrative expansion", "SOCIAL MESSAGE -> post-Independence use", "RULE -> stages overlap by region"], ["Folk theatre's changing public"]),
        panel("Modern theatre sequence", "timeline", ["PROSCENIUM -> colonial city and commerce", "1876 ACT -> political control", "PARSI / IPTA -> circulation and mobilisation", "SNA / NSD -> institutional training"], ["Colonial proscenium and censorship", "Parsi, IPTA and institutions"]),
        panel("Puppetry mechanism matrix", "comparison-table", ["STRING -> suspended marionette", "SHADOW -> cut-out before a lit screen", "ROD -> figure moved from below or behind", "GLOVE -> fingers inside a sleeve body"], ["Four puppetry mechanisms"]),
        panel("String-puppet distinctions", "comparison-table", ["KATHPUTLI -> legless Rajasthan doll", "KUNDHEI -> jointed Odisha figure", "GOMBEYATTA -> Yakshagana-styled Karnataka figure", "CONTROL -> strings, but different bodies"], ["String-puppet regional grammar"]),
        panel("Shadow, rod and glove map", "spatial-map", ["THOLU BOMMALATA -> Andhra shadow", "RAVANA CHHAYA -> Odisha shadow", "PUTUL NACH / YAMPURI -> rod", "PAVAKOOTHU -> Kerala glove"], ["Shadow-puppet screen grammar", "Rod, glove and control"]),
        panel("Performance vulnerability test", "decision-tree", ["TEXT SURVIVES? -> archive and teaching", "PERFORMER SURVIVES? -> skill transmission", "AUDIENCE + FUNDING? -> living ecology", "RESPONSE -> form-specific safeguarding"], ["Puppetry as archive and livelihood"]),
        panel("Performance answer spine", "answer-spine", ["DEFINE -> mode, genre or control mechanism", "TRACE -> patronage and public", "COMPARE -> region, body and institution", "QUALIFY -> convention, continuity and vulnerability"], ["Martial performance and two decline types"]),
    ],
    ["Lokadharmi", "Natyadharmi", "rupaka", "Sutradhar", "Vidusaka", "Kutiyattam", "Dramatic Performances Act", "Parsi theatre", "IPTA", "string puppets", "shadow puppets", "rod puppets", "glove puppets", "Kathputli", "Tholu Bommalata", "Pavakoothu", "Kalaripayattu", "Thang-ta"],
    "No direct routed PYQ for theatre, puppetry or performance traditions appears in the audited 2018-2026 ledgers used by this authoring engine. Older question references inside the Basic owner remain contextual examples and are not promoted into solved PYQ cards without a controlling routed record.",
    [],
    live_sources=["https://ich.unesco.org/en/RL/kutiyattam-sanskrit-theatre-00010"],
    current_note=("UNESCO's official Kutiyattam element page was rechecked on 2026-09-04. Its metadata identifies Kutiyattam as a Kerala synthesis of Sanskrit classicism and local tradition with codified eye and hand expression. The package uses the official Representative List status as a living-safeguarding link and does not invent a new inscription, award or current performer count."),
    extra=[
        "basic/08_Indian-Music.md",
        "basic/09_Indian-Dance.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
        "basic/15_Indian-Cinema-Film-Institutions-and-Awards.md",
    ],
)
