"""Authored content data for Indian Art and Culture learner-v2 Topics 11-15."""

from __future__ import annotations

import generate_indian_art_culture_common as common
from indian_art_culture_01_05_data import panel, plan


TOPIC_11 = common.topic(
    11,
    "Languages, Scripts, Literature and Manuscripts",
    "11_Languages-Scripts-Literature-and-Manuscripts",
    "11_Languages-Scripts-Literature-and-Manuscripts_Complete-Topic-Package.md",
    [
        ("Classification firewall", "Language family, script, literary register, constitutional status, classical-language recognition and documentary-heritage recognition are separate classifications; none may be inferred from another."),
        ("Four major language families", "Indo-Aryan within Indo-European, Dravidian, Austroasiatic and Tibeto-Burman are the four major family groupings used by the owner; no family is culturally more Indian than another."),
        ("Sanskrit and Prakrit coexistence", "Sanskrit and the Prakrit registers performed different literary and social functions and coexisted; Prakrit is not merely a later or corrupted Sanskrit."),
        ("Middle Indo-Aryan registers", "Pali is associated with the Theravada canon, Ardhamagadhi especially with the Svetambara Jain canon, and Shauraseni and Maharashtri with major dramatic or literary uses; historical speech cannot be reduced to one neat branch chart."),
        ("Grammar and Sanskrit epigraphy", "Panini's Ashtadhyayi systematised Sanskrit grammar, while Rudradaman I's Junagarh inscription around 150 CE is the earliest extensive datable Sanskrit inscriptional evidence in the owner; literary antiquity and epigraphic chronology are different questions."),
        ("Ashokan multilingual record", "Ashokan edicts are mostly Prakrit in Brahmi, use Kharoshthi in the northwest, and include Greek and Aramaic at Kandahar; describing them as Sanskrit in Devanagari is false."),
        ("Brahmi and Kharoshthi", "Brahmi is an ancestral script with many regional descendants, while Kharoshthi ran right-to-left and was used especially in the northwest; neither name denotes a language family."),
        ("Kushana coexistence", "Kushana rulers used Greek, Kharoshthi and Brahmi scripts with Greek, Prakrit and Sanskritised registers, demonstrating multilingual coexistence rather than linear replacement."),
        ("Layered early corpora", "The Vedas, Brahmanas, Aranyakas, early Upanishads, epics and Puranas have layered oral, compositional, redactional and manuscript histories and should not be assigned one publication date."),
        ("Buddhist and Jain textual worlds", "Buddhist literature spans Pali, Prakrits, Buddhist Hybrid Sanskrit and Sanskrit, while Jain literature spans Ardhamagadhi and other Prakrits with later Sanskrit, Apabhramsha and regional-language production."),
        ("Sangam evidence boundary", "The Sangam corpus, compiled around CE 300-600 with older layers, illuminates towns, trade, crafts, war, ranking and hero-stone culture but is not a connected dynastic chronicle."),
        ("Classical attribution discipline", "Bhasa, Kalidasa, Shudraka, Bharavi and Dandin belong to the classical Sanskrit evidence bank, but each work-author pair must be verified; the 2021 and 2024 objective routes are attribution tests, not licence to guess."),
        ("Pallava literary route", "Dandin's Avantisundari Katha, bilingual Tamil-Sanskrit inscriptions and Pallava-Grantha court use supply the literature-and-script side of the 2024 Pallava demand; court usage must not be generalised to all writing in the region."),
        ("Vernacular expansion", "The rise of Hindi and other regional literatures expanded literary publics through Bhakti, court and translation networks without causing the disappearance of Sanskrit or Persian."),
        ("Urdu as Indian literary formation", "The owner classes Urdu as Indo-Aryan, structured on Khari Boli and shaped through Persian-Hindi interaction in India; Dakkani, qaseeda, shahr ashob and ginan must be used as distinct historical labels."),
        ("Language as staged social marker", "The Sanskrit-Prakrit speech convention in Gupta-period drama marks social position on stage; it is direct textual evidence for hierarchy but cannot be universalised to every period and genre."),
        ("Text date versus recognition date", "Composition, redaction, earliest surviving manuscript, critical edition and UNESCO Memory of the World inscription are different dates; the Rigveda's 2007 inscription does not date its composition."),
        ("Documentary-heritage diversity", "India's Memory of the World entries include religious, aesthetic, medical, administrative, Persian-chronicle and folk-performance records, so documentary heritage is not synonymous with ancient scripture."),
        ("Manuscript survey and custody", "The Ministry of Culture's Gyan Bharatam National Manuscript Survey, launched 16 March 2026, uses identification, expert verification, metadata creation and conservation or digitisation as four stages without transferring ownership from custodians."),
        ("Verified language PYQ routes", "The audited routes are 2021 Bhavabhuti-Hastimalla-Kshemeshvara, 2024 Bhasa and provisional 2026 place-value notation objective demands; no direct GS-I Mains PYQ belongs solely to this topic."),
    ],
    [
        "Do not conflate a language family with a script or constitutional status.",
        "Do not claim that India has a constitutionally declared national language.",
        "Do not treat Sanskrit and Prakrit as a simple old-to-new succession.",
        "Do not assign the Buddha or Mahavira one certain recorded spoken language.",
        "Do not call Ashokan edicts Sanskrit texts in Devanagari.",
        "Do not describe Kharoshthi as left-to-right.",
        "Do not give one exact date to a layered oral-textual corpus.",
        "Do not treat Sangam literature as a connected dynastic chronicle.",
        "Do not infer a work-author pair from a famous literary name.",
        "Do not generalise Gupta dramatic speech conventions to all Indian theatre.",
        "Do not treat vernacular growth as the disappearance of Sanskrit or Persian.",
        "Do not describe Urdu as a non-Indian or exclusively religious language.",
        "Do not confuse a text's composition date with a manuscript-inscription year.",
        "Do not merge Memory of the World with World Heritage, ICH or GI status.",
        "Do not invent manuscript counts, folio totals, readings or ownership changes.",
    ],
    [
        (10, "Distinguish language family, script, literary register and constitutional or heritage status.", "India's linguistic diversity becomes intelligible only when genealogical, graphic, social-literary and legal classifications are kept separate.", [0, 1, 6]),
        (10, "Explain why Sangam literature is powerful but bounded historical evidence.", "The corpus illuminates social and material worlds through layered poems, but compilation history prevents its use as a continuous dynastic chronicle.", [8, 10]),
        (15, "Examine the coexistence of Sanskrit, Prakrit and regional literary languages.", "Indian literary history is a division of labour among overlapping registers and publics rather than a succession in which one language eliminates another.", [2, 3, 7, 13, 14]),
        (15, "Assess Pallava contributions to literature and script culture within the wider art-and-literature demand.", "Named textual, bilingual epigraphic and court-script evidence makes Pallava literary patronage demonstrable, while the court-use limit prevents overgeneralisation.", [4, 12]),
        (20, "Discuss manuscripts as documentary heritage and the institutional tasks required for their safeguarding.", "Documentary value depends on disciplined dating, diverse custody, cataloguing, conservation, digitisation and access rather than prestige inscription alone.", [16, 17, 18]),
        (20, "Trace how language, script and literature can be used as evidence of social and political change in India.", "Scripts and registers record authority, hierarchy and changing publics, but every inference must remain tied to a dated corpus, inscription or performance convention.", [5, 7, 9, 11, 15, 19]),
    ],
    [
        plan("The classification firewall", [0, 1], "A family, script, register and legal status answer different questions.", "Open every language answer with the correct axis."),
        plan("Sanskrit and Prakrit as coexisting registers", [2], "Difference of function is not a degeneration story.", "Explain social and literary division of labour."),
        plan("Pali and the literary Prakrits", [3], "Canonical labels do not reconstruct one certain spoken language.", "Prepare close-option identification."),
        plan("Panini and the Sanskrit epigraphic record", [4], "Literary antiquity is not the date of surviving inscriptional evidence.", "Build a chronology with an explicit evidence limit."),
        plan("Ashokan scripts and languages", [5, 6], "Brahmi and Kharoshthi are scripts, not language families.", "Correct the Sanskrit-Devanagari shortcut."),
        plan("Kushana multilingual coexistence", [7], "Several scripts and registers can operate under one polity.", "Replace linear replacement with a coexistence model."),
        plan("Layered Vedic, epic and Puranic corpora", [8], "Composition, redaction and manuscript dates must remain separate.", "Use text-layer discipline."),
        plan("Buddhist and Jain textual worlds", [9], "Religious corpus does not imply one language or one period.", "Compare canon, narrative and later transmission."),
        plan("Sangam literature as bounded evidence", [10], "Rich social detail does not create a continuous chronicle.", "Write evidence plus limitation."),
        plan("Classical Sanskrit attribution", [11], "A famous author is not a substitute for a verified work-author pair.", "Prepare the 2021 and 2024 objective routes."),
        plan("Pallava literature and script culture", [12], "Court-script change is not a claim about all regional writing.", "Supply the literature half of the Pallava answer."),
        plan("Vernacular and Urdu literary publics", [13, 14], "Expansion is not zero-sum replacement or religious ownership.", "Connect language to audience and patronage."),
        plan("Language as staged hierarchy", [15], "The convention is documented for a bounded dramatic setting.", "Use language as social evidence without universalising it."),
        plan("Manuscripts and recognition dates", [16, 17, 18], "Recognition does not date a text or transfer custody.", "Connect UNESCO recognition to survey, metadata and conservation."),
        plan("Verified PYQs and final language answer spine", [19, 0], "Do not solve objective routes whose answer is not recorded.", "Integrate classification, evidence, dating and qualification."),
    ],
    [
        panel("Classification firewall", "root-axes", ["FAMILY -> genealogical relationship", "SCRIPT -> graphic system", "REGISTER -> social or literary use", "STATUS -> constitutional or heritage recognition"], ["The classification firewall"]),
        panel("Register coexistence", "comparison-table", ["SANSKRIT -> codified learned register", "PRAKRITS -> plural literary and social registers", "PALI / ARDHAMAGADHI -> canonical associations", "RULE -> coexistence, not simple succession"], ["Sanskrit and Prakrit as coexisting registers"]),
        panel("Script geography", "spatial-map", ["BRAHMI -> widespread ancestral script", "KHAROSHTHI -> northwest, right-to-left", "KANDAHAR -> Greek and Aramaic", "ASHOKAN RECORD -> multilingual, mostly Prakrit"], ["Ashokan scripts and languages"]),
        panel("Epigraphic chronology", "timeline", ["PANINI -> grammatical system", "ASHOKA -> Prakrit and multilingual edicts", "RUDRADAMAN c.150 CE -> extensive Sanskrit epigraphy", "CHEBROLU 207 CE -> South Indian datable Sanskrit"], ["Panini and the Sanskrit epigraphic record"]),
        panel("Text-layer ladder", "hierarchy", ["ORAL FORMATION -> earliest layer", "COMPOSITION / REDACTION -> changing text", "SURVIVING MANUSCRIPT -> material witness", "MODERN INSCRIPTION -> recognition event"], ["Layered Vedic, epic and Puranic corpora"]),
        panel("Corpus evidence matrix", "evidence-table", ["VEDIC -> ritual and cosmology", "BUDDHIST / JAIN -> canon and narrative", "SANGAM -> towns, trade, war and ranking", "LIMIT -> corpus is not a transparent chronicle"], ["Buddhist and Jain textual worlds", "Sangam literature as bounded evidence"]),
        panel("Pallava literature route", "causal-system", ["KANCHIPURAM -> patronage centre", "DANDIN -> named court-associated author", "BILINGUAL INSCRIPTIONS -> Tamil and Sanskrit", "GRANTHA -> court-script intervention"], ["Pallava literature and script culture"]),
        panel("Vernacular expansion", "process-flow", ["BHAKTI / COURT / TRANSLATION -> new production", "REGIONAL LANGUAGES -> wider publics", "SANSKRIT + PERSIAN -> continue", "RESULT -> layered literary ecology"], ["Vernacular and Urdu literary publics"]),
        panel("Stage-language hierarchy", "comparison", ["HIGH-STATUS CHARACTERS -> Sanskrit convention", "WOMEN / SHUDRAS -> Prakrit convention", "EVIDENCE -> hierarchy encoded in drama", "LIMIT -> bounded period and genre"], ["Language as staged hierarchy"]),
        panel("Documentary heritage range", "evidence-table", ["RELIGIOUS -> Rigveda and Gita manuscripts", "AESTHETIC -> Natyashastra and poetics", "ADMINISTRATIVE -> Dutch company archives", "RULE -> cite composition and inscription separately"], ["Manuscripts and recognition dates"]),
        panel("Survey-to-safeguarding", "process-flow", ["IDENTIFY -> locate custodians and repositories", "VERIFY -> expert and state review", "CATALOGUE -> language, script and subject metadata", "CONSERVE / DIGITISE -> preservation and research"], ["Manuscripts and recognition dates"]),
        panel("Language answer spine", "answer-spine", ["DEFINE -> state the classification axis", "EVIDENCE -> text, inscription or convention", "COMPARE -> register, script or public", "QUALIFY -> dating, attribution and status"], ["Verified PYQs and final language answer spine"]),
    ],
    ["Indo-Aryan", "Dravidian", "Austroasiatic", "Tibeto-Burman", "Prakrit", "Kharoshthi", "Rudradaman", "Sangam", "Bhasa", "Dandin", "Pallava-Grantha", "Dakkani", "Memory of the World", "Gyan Bharatam"],
    "No direct GS-I Mains PYQ is routed solely to Topic 11. The audited objective routes are 2021 Bhavabhuti-Hastimalla-Kshemeshvara, 2024 Bhasa, and provisional 2026 place-value notation; the 2024 Pallava Mains demand is cross-owned through Topic 03, so no objective answer letter or fabricated direct Mains ownership is supplied.",
    [],
    live_sources=[
        "https://culture.gov.in/events/launch-gyan-bharatam-national-manuscript-survey-map-indias-manuscript-heritage",
    ],
    current_note=("The Ministry of Culture page rechecked on 2026-09-04 records the launch of the Gyan Bharatam National Manuscript Survey on 16 March 2026 and its voluntary four-stage path from identification through verification and metadata to conservation or digitisation. Participation does not transfer ownership. PIB retains eleven classical languages after the October 2024 additions, while UNESCO's 2025 Memory of the World register records the Bhagavadgita and Natyashastra manuscript additions; these statuses remain separate."),
    extra=[
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/13_Religion-Philosophy-and-Cultural-Synthesis.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_12 = common.topic(
    12,
    "Crafts, Textiles, Folk and Tribal Traditions",
    "12_Crafts-Textiles-Folk-and-Tribal-Traditions",
    "12_Crafts-Textiles-Folk-and-Tribal-Traditions_Complete-Topic-Package.md",
    [
        ("Handicraft and material classes", "Handicraft joins hand skill, livelihood and cultural heritage; the owner's material classes include glass, cloth, ivory, silver, clay, bronze, other metals, leather, wood, toys, stone and floor designs."),
        ("Craft ecology chain", "A craft survives through linked raw material, skill, producing community, market access, legal recognition and safeguarding; failure at any earlier link cannot be repaired by a label alone."),
        ("GI as origin-linked IP", "A Geographical Indication protects an origin-linked product name for authorised users; it is not a quality certificate, UNESCO heritage status or community-welfare guarantee."),
        ("GI legal mechanics", "India's sui generis GI Act of 1999 has operated since 2003, covers goods rather than services, is administered through the GI Registry at Chennai under DPIIT, and grants renewable ten-year registration."),
        ("First and cross-border GI examples", "Darjeeling Tea was India's first GI-tagged product in 2004-05, while Kangra Tea obtained separate European Union protection; an Indian registration does not automatically extend abroad."),
        ("Continuity through market change", "Harappan, Sangam, medieval karkhana, merchant-export, colonial, tourism and GI markets changed patronage, scale, motif and labour, so continuity means selective adaptation rather than unchanged production."),
        ("Patola and Pochampally", "Patola from Patan uses double ikat, while Pochampally in Telangana uses resist-dyed yarn and may be single or double ikat; technique and centre must be stated together."),
        ("Kanchipuram and Banarasi", "Kanchipuram silk is distinguished by contrasting borders joined to the body, while Banarasi brocade uses supplementary-weft zari; neither is embroidery."),
        ("Chikankari and Kantha", "Chikankari is Lucknow's white-on-white embroidery repertoire, while Kantha is Bengal running-stitch quilting or embroidery associated with reused cloth traditions."),
        ("Kalamkari and Dhokra", "Kalamkari uses hand-drawn or block-printed cotton with mordant or resist processes in Andhra Pradesh and Telangana centres, while Dhokra is lost-wax non-ferrous casting across central and eastern artisan communities."),
        ("Glass craft chronology", "The owner links glass to Mahabharata reference, Painted Grey Ware evidence, the term kanch or kaca in the Shatapatha Brahmana, and a Brahmapuri-Kolhapur industry producing lenticular beads."),
        ("North-East handloom process", "The owner's North-East handloom frame links community-held knowledge to ginning, spinning and weaving; region, community, fibre, process and product must be recorded together."),
        ("Meghalaya Eri evidence", "Eri silk is commonly produced in Meghalaya, where Garo, Khasi and Jaintia communities are described as skilled weavers of shawls, sarongs and mekhela chadors using silk and cotton."),
        ("Assam Muga discriminator", "Assam is identified with golden Muga silk, while mekhela chador occurs in both Assam and Meghalaya and therefore cannot identify a state by itself."),
        ("Manipur and Nagaland textiles", "Manipur is linked with Moirang Phee and the Phanek, while Nagaland traditions use tribe-specific patterns, vibrant colours and natural dyes; neither should be reduced to a single pan-state motif."),
        ("Arunachal, Mizoram and Tripura", "Adi, Apatani, Nyishi and Monpa weaving anchors Arunachal Pradesh; women are the primary weavers of Mizoram's Puan; Tripura is described through striped and dispersed-embroidery patterning."),
        ("GI is not safeguarding", "GI intervenes at legal recognition but does not by itself secure raw material, fair price, labour conditions, design protection, market power or intergenerational skill transmission."),
        ("Certification versus GI boundary", "The routed Oeko-Tex demand combines a voluntary textile-testing standard with Eri production; the owner supports the Eri fact but holds no verified criteria or current producer-status evidence for the certification half."),
        ("Ecology, gender and appropriation", "Wildlife-law limits bar revivalist arguments for new ivory production; invisible preparatory labour and copying outside a protected name show why ecology, gender and design appropriation require analysis beyond GI."),
        ("Verified craft routes and live boundary", "The routed demands cover 2018 folk-culture and textile matching plus provisional 2026 Eri-Oeko-Tex; deindustrialisation-as-context, not this topic's primary claim, means this topic supplies specific craft-material vocabulary while Modern History and Economy own the causal verdict. The official 2025 handloom-award document is used only as evidence of current institutional recognition, not as a source for unverified winners."),
    ],
    [
        "Do not treat handicraft and GI as the same concept.",
        "Do not call GI a quality certificate or UNESCO heritage designation.",
        "Do not claim that GI registration is permanent.",
        "Do not extend a domestic GI automatically to foreign jurisdictions.",
        "Do not treat one textile name as one technique everywhere.",
        "Do not confuse ikat, brocade, embroidery and painted or printed cloth.",
        "Do not place Patola at Pochampally or describe Kanchipuram as embroidery.",
        "Do not treat Dhokra as a single-state monopoly.",
        "Do not attribute Eri silk exclusively to Assam or confuse it with Muga.",
        "Do not use mekhela chador alone as a state discriminator.",
        "Do not invent Oeko-Tex criteria, issuers, producer status or dates.",
        "Do not romanticise tribal craft as anonymous or timeless.",
        "Do not propose new ivory production as heritage safeguarding.",
        "Do not invent artisan counts, export values, employment shares or current GI totals.",
        "Do not answer the deindustrialisation or diversity-marginality debates as if this topic owned them.",
    ],
    [
        (10, "Distinguish a craft tradition from a Geographical Indication.", "Craft is a production ecology of material, skill, community and market, whereas GI is a narrow renewable right over an origin-linked name.", [0, 1, 2, 3]),
        (10, "Compare ikat, brocade, embroidery and painted or printed textile processes with examples.", "Process, region and product together distinguish textile traditions more reliably than a one-word state match.", [6, 7, 8, 9]),
        (15, "Explain why GI recognition cannot by itself safeguard craft livelihoods.", "Name protection acts at only one link of the craft ecology chain and leaves material access, income, labour conditions, transmission and market power unresolved.", [1, 16, 18]),
        (15, "Assess North-East handloom traditions through community, fibre, process and product.", "Named community-held weaving systems reveal regional plurality, but close-option discipline is needed for Eri, Muga and shared garments.", [11, 12, 13, 14, 15]),
        (20, "Trace continuity and change in Indian craft production from early material cultures to contemporary markets.", "Technique can persist while patrons, intermediaries, designs and market institutions change, making adaptation rather than stasis the key historical argument.", [5, 10, 16]),
        (20, "Discuss the institutional and ethical framework needed to conserve living craft traditions.", "Effective safeguarding combines legal recognition with ecology, fair market access, visible labour, transmission, documentation and carefully bounded certification claims.", [2, 4, 17, 18, 19]),
    ],
    [
        plan("Handicraft and its material classes", [0], "A material list becomes analysis only when linked to skill and livelihood.", "Define the scope before naming examples."),
        plan("The craft ecology chain", [1], "Legal recognition is one link, not the whole system.", "Build the causal spine for every craft answer."),
        plan("What a GI legally protects", [2, 3], "Origin-linked name protection is not quality or welfare certification.", "State the instrument and statutory limit precisely."),
        plan("First GI and foreign protection", [4], "Cross-border protection requires a separate jurisdictional act.", "Use dated examples without implying automatic extension."),
        plan("Continuity through changing markets", [5], "Continuity does not mean unchanged design, patronage or labour.", "Trace adaptation across historical markets."),
        plan("Ikat close options", [6], "State centre and resist-dye logic together.", "Separate Patola from Pochampally."),
        plan("Brocade, silk and embroidery", [7, 8], "A weave is not embroidery and reuse can be intrinsic to form.", "Prepare four-tradition comparison."),
        plan("Kalamkari, Dhokra and material process", [9], "Surface design and lost-wax casting solve different material problems.", "Link process to product."),
        plan("Glass craft chronology", [10], "Textual reference and archaeological evidence are different evidence classes.", "Construct a cautious craft-history chain."),
        plan("North-East handloom method", [11], "Region must be joined to community, fibre, process and product.", "Replace anonymous tribal labels with sourced specificity."),
        plan("Eri and Muga firewall", [12, 13], "A shared garment cannot identify the fibre or state alone.", "Prepare the provisional 2026 route without solving it."),
        plan("Manipur and Nagaland discriminators", [14], "Named fabrics and motif systems must remain distinct.", "Build close-option confidence."),
        plan("Arunachal, Mizoram and Tripura", [15], "Do not flatten several communities into a single North-East style.", "Add gendered labour and pattern evidence."),
        plan("Beyond the GI label", [16, 17, 18], "Unsupported certification detail must remain a disclosed gap.", "Evaluate livelihood, ecology, labour and appropriation."),
        plan("Verified craft PYQs and live institutional link", [19], "Current awards cannot prove technique or tribal attribution.", "Close with evidence, boundary and dated-source discipline."),
    ],
    [
        panel("Craft ecology root", "causal-system", ["RAW MATERIAL -> ecological access", "SKILL -> technique and apprenticeship", "COMMUNITY -> labour and transmission", "MARKET / LAW -> access, GI and safeguarding"], ["The craft ecology chain"]),
        panel("GI legal boundary", "comparison-table", ["GI -> origin-linked product name", "TERM -> ten years, renewable", "SCOPE -> goods, not services", "LIMIT -> no automatic livelihood guarantee"], ["What a GI legally protects"]),
        panel("Cross-border protection", "process-flow", ["DARJEELING TEA -> first Indian GI", "INDIAN GI -> domestic protection", "KANGRA TEA -> separate EU protection", "RULE -> rights do not travel automatically"], ["First GI and foreign protection"]),
        panel("Ikat matrix", "comparison-table", ["PATOLA -> Patan, double ikat", "POCHAMPALLY -> Telangana, single or double ikat", "COMMON -> resist-dyed yarn", "TRAP -> centre plus process must match"], ["Ikat close options"]),
        panel("Textile process ladder", "comparison-table", ["KANCHIPURAM -> joined silk border", "BANARASI -> supplementary-weft brocade", "CHIKANKARI -> white embroidery", "KANTHA -> running stitch and reused cloth"], ["Brocade, silk and embroidery"]),
        panel("Surface and metal process", "comparison", ["KALAMKARI -> mordant or resist cotton surface", "DHOKRA -> lost-wax metal casting", "PROCESS -> determines tools and labour", "RULE -> shared craft label proves nothing"], ["Kalamkari, Dhokra and material process"]),
        panel("Glass evidence chain", "timeline", ["TEXT -> Mahabharata and Shatapatha Brahmana", "PGW -> archaeological glass evidence", "BRAHMAPURI / KOLHAPUR -> bead industry", "LIMIT -> evidence classes must remain separate"], ["Glass craft chronology"]),
        panel("North-East method", "hierarchy", ["COMMUNITY -> identify the weavers", "FIBRE -> Eri, Muga, silk or cotton", "PROCESS -> ginning, spinning and weaving", "PRODUCT -> garment and motif"], ["North-East handloom method"]),
        panel("Eri-Muga firewall", "comparison-table", ["MEGHALAYA -> Eri, Garo-Khasi-Jaintia", "ASSAM -> golden Muga", "MEKHELA CHADOR -> shared garment", "TRAP -> garment alone cannot identify state"], ["Eri and Muga firewall"]),
        panel("Regional handloom map", "spatial-map", ["MANIPUR -> Moirang Phee and Phanek", "NAGALAND -> tribe-specific motifs and natural dyes", "ARUNACHAL -> Adi, Apatani, Nyishi and Monpa", "MIZORAM / TRIPURA -> Puan, stripes and embroidery"], ["Manipur and Nagaland discriminators", "Arunachal, Mizoram and Tripura"]),
        panel("Certification gap test", "decision-tree", ["PRODUCTION FACT VERIFIED? -> write Eri evidence", "CERTIFICATION CRITERIA VERIFIED? -> no", "GI COMPARISON -> legal instrument only", "VERDICT -> disclose the bounded gap"], ["Beyond the GI label"]),
        panel("Craft answer spine", "answer-spine", ["DEFINE -> material, skill and community", "IDENTIFY -> region, process and product", "ANALYSE -> market, law, ecology and labour", "QUALIFY -> status, ownership and source limits"], ["Verified craft PYQs and live institutional link"]),
    ],
    ["handicraft", "Geographical Indication", "GI Registry", "Patola", "Pochampally", "Kanchipuram", "Banarasi", "Chikankari", "Kantha", "Kalamkari", "Dhokra", "Eri silk", "Muga silk", "Puan", "Oeko-Tex"],
    "No direct GS-I Mains PYQ is routed to Topic 12. The audited direct objective routes are the two 2018 matching demands and the provisional 2026 Eri-Oeko-Tex demand; the 2024 handicraft-decline and diversity-marginality Mains questions remain adjacent routes owned by Modern History or Economy and Indian Society.",
    [],
    live_sources=[
        "https://www.handlooms.gov.in/award_details.php",
        "https://handlooms.gov.in/assets/img/upcoming_markeing/Final%20List%20of%20selected%20entries%20for%20Sant%20Kabir_awards_2025.pdf",
    ],
    current_note=("The Development Commissioner (Handlooms) official award page and 2025 selection document were rechecked on 2026-09-04. They are used only to show current institutional recognition of named handloom work; no recipient is used to infer community ownership, and no count, fibre attribution, GI status, certification, fair-livelihood or unchanged-tradition claim is imported."),
    extra=[
        "basic/06_Sculpture-Pottery-and-Iconography.md",
        "basic/07_Painting-Traditions.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_13 = common.topic(
    13,
    "Religion, Philosophy and Cultural Synthesis",
    "13_Religion-Philosophy-and-Cultural-Synthesis",
    "13_Religion-Philosophy-and-Cultural-Synthesis_Complete-Topic-Package.md",
    [
        ("Cultural-framework boundary", "This topic studies religion and philosophy where they shape patronage, form, social practice, language and monuments; full doctrinal argument belongs to Philosophy and political policy detail to History."),
        ("Purushartha framework", "Artha, Dharma, Kama and Moksha organise wealth, social regulation, pleasure or love, and salvation; the cultural use is to explain why art can represent several legitimate human ends together."),
        ("Six orthodox darshanas", "Samkhya, Yoga, Nyaya, Vaisheshika, Mimamsa and Vedanta are six Vedic-authority-accepting schools of inquiry, not six separate religions."),
        ("Samkhya and Yoga caution", "Classical Samkhya distinguishes purusha and prakriti and uses perception, inference and testimony, while Patanjali's layered Yogasutra systematises citta-vritti control and eight-limbed practice; neither text should receive a falsely certain authorship or date."),
        ("Vedanta and Prasthanatrayi", "Vedanta draws on the Upanishads, Bhagavad Gita and Brahma Sutras as the Prasthanatrayi and connects Brahman, atman, karma, rebirth and liberation; doctrinal disputes remain outside this cultural owner."),
        ("Advaita cultural anchor", "Adi Shankaracharya's Advaita emphasises attributeless Brahman, knowledge and jivanmukti and is linked with the Dashanami order and four mathas; this is a sourced cultural-institutional consequence, not a full philosophical proof."),
        ("Ramanuja and devotion", "Ramanuja's Vishishtadvaita treats Brahman as possessing attributes and gives love and devotion a central salvific role, explaining its Saguna and temple-devotional cultural alignment."),
        ("Dvaita and attribution trap", "Madhvacharya is linked with Dvaita and the Brahma Sampradaya, while Pushtimarg belongs to Vallabhacharya; the source does not supply a separate Dvaita salvation formula and none should be invented."),
        ("Bhakti four-factor model", "The owner's causal frame combines reaction to orthodoxy and caste rigidity, inclusion of marginalised communities, space created by Buddhist and Jain decline, and royal patronage; no single diffusion story explains all regions."),
        ("Nayanar and Alvar canons", "Nayanars are the canonical sixty-three Tamil Shaiva saints and Alvars the canonical twelve Tamil Vaishnava saints whose hymns form the Nalayira Divya Prabandham; Andal is the sole woman in the Alvar canon."),
        ("Saguna and Nirguna variety", "Saguna Bhakti worships a deity with form and attributes, while Nirguna Bhakti stresses the formless divine; the classification helps comparison but cannot erase regional chronology or internal difference."),
        ("Named Bhakti literature", "Kabir's dohas, Tulsidas's Awadhi Ramcharitmanas, Surdas's Braj Sur Sagar and the multilingual Sant Bhasha show devotion widening literary publics through different languages and forms."),
        ("Basavanna and Varkari streams", "Basavanna's Vachanas and Anubhava Mantapa belong to the Lingayat formation, while Jnaneshwar, Namdev, Eknath and Tukaram mark a distinct Marathi Varkari stream; Lingayat and Veerashaiva must not be equated."),
        ("Women and institutional limits", "Andal, Karaikkal Ammaiyar, Akka Mahadevi, Mirabai and Lal Ded show uneven regional participation, but the evidence does not justify the claim that Bhakti abolished patriarchy or gave women equal authority."),
        ("Sufi order diversity", "Chishti, Suhrawardi, Qadiri, Naqshbandi, Shattari and other silsilahs differed over property, court proximity, ritual and scholarship; Sufism cannot be reduced to one uniformly syncretic position."),
        ("Named Chishti cultural links", "Moinuddin Chishti's Ajmer khanqah and urs, Nizamuddin Auliya's service ethic, Amir Khusrau's music-poetry link and Baba Farid's verses in the Adi Granth provide named practice, place, person and text evidence."),
        ("Sufi practices and sources", "Sama, zikr, ziyarat, pir-murid and khanqah are distinct practices or institutions, while malfuzat, maktubat and tazkiras are conversations, letters and biographies with different evidentiary value."),
        ("Synthesis mechanism and qualification", "Cultural synthesis is strongest when shown through shared spaces, music, translation, vernacular texts and pilgrimage, and weakest when asserted as merged doctrine; the Naqshbandi counter-current and Din-i-Ilahi's lack of mass acceptance are necessary qualifications."),
        ("Philosophy converted into form", "Purushartha at Khajuraho, Buddhist aniconism, relic-centred stupas, Nandi's axial placement and Nayanar legends at Airavatesvara show ideas becoming design decisions, but patron intention must not be invented."),
        ("Festivals and verified routes", "Kumbh, Ramlila, Durga Puja, Garba and Deepavali join sacred geography, performance, artisan labour and safeguarding; Deepavali's 2025 ICH inscription is a current living-heritage link, while the direct routed Mains demand is the 2020 philosophy-and-monuments question."),
    ],
    [
        "Do not turn this cultural topic into a full theology or metaphysics essay.",
        "Do not treat the six darshanas as six religions.",
        "Do not assign the extant Samkhya Sutra to Kapila as settled fact.",
        "Do not give the Yogasutra a falsely precise date.",
        "Do not confuse Advaita, Vishishtadvaita and Dvaita.",
        "Do not attribute Pushtimarg to Madhvacharya.",
        "Do not describe Bhakti as one simple south-to-north relay.",
        "Do not claim Nayanar or Alvar canonical hymns are Telugu.",
        "Do not equate Lingayats and Veerashaivas.",
        "Do not claim Bhakti abolished caste, patriarchy or priestly authority everywhere.",
        "Do not flatten Kabir, Tulsidas, Basavanna and Tukaram into one contribution.",
        "Do not give Eknath one exact lifespan from the conflicting local source.",
        "Do not describe all Sufi orders as holding one position on court and property.",
        "Do not merge Bhakti and Sufism into one religion.",
        "Do not invent Al-Biruni's Somnath account or a Pran Pratishtha definition.",
        "Do not derive a monument plan from a philosophical text without evidence.",
    ],
    [
        (10, "Distinguish religion as doctrine from religion as a cultural framework.", "Art-and-culture analysis asks how belief changes language, patronage, form, institution and practice while leaving doctrinal proof to the specialist owner.", [0, 18]),
        (10, "Compare Saguna and Nirguna Bhakti using named literary evidence.", "The distinction becomes useful only when form, language, audience and regional trajectory are attached to named saints and texts.", [9, 10, 11]),
        (15, "Explain the causes, regional trajectories and limits of the Bhakti movement.", "A four-factor causal model and named regional streams show inclusion and cultural production alongside temple institutionalisation, hierarchy and unequal gender outcomes.", [8, 9, 12, 13]),
        (15, "Compare major Sufi orders and assess their cultural interaction with Bhakti traditions.", "Named differences among silsilahs prevent a harmony-only narrative, while place, text, music and pilgrimage demonstrate real interaction without doctrinal merger.", [14, 15, 16, 17]),
        (20, "Discuss how Indian philosophy and tradition shaped monuments and art.", "The answer must trace each doctrine or practice into a concrete design decision and named monument, then qualify philosophy against patronage, material and politics.", [1, 2, 3, 4, 5, 6, 18]),
        (20, "Evaluate cultural synthesis in India through literature, performance, pilgrimage and festivals.", "Synthesis is demonstrable at the level of shared practice and circulation but remains unequal, contested and bounded at the level of doctrine and authority.", [11, 15, 17, 19]),
    ],
    [
        plan("Religion and philosophy as cultural frameworks", [0], "Doctrinal proof and political policy remain with their specialist owners.", "Define the art-and-culture question."),
        plan("Purushartha and the six darshanas", [1, 2], "A framework of ends and schools is not a list of religions.", "Connect philosophical classification to cultural form."),
        plan("Samkhya and Yoga boundaries", [3], "Authorship and dating must remain qualified.", "Use only the sourced minimum doctrinal content."),
        plan("Vedanta and its textual base", [4], "The cultural owner does not adjudicate doctrinal objections.", "Prepare the parent-school frame."),
        plan("Advaita, Vishishtadvaita and Dvaita", [5, 6, 7], "Do not invent a Dvaita salvation formula or misassign Pushtimarg.", "Compare attributes, means and institutions."),
        plan("Why Bhakti emerged", [8], "Four causes do not imply one origin or diffusion date.", "Build a causal rather than saint-list answer."),
        plan("Tamil Bhakti canons", [9], "Canonical numbers and language must remain exact.", "Link hymn, temple and gender evidence."),
        plan("Saguna, Nirguna and named literature", [10, 11], "Internal variety needs language, form and named text.", "Prepare literature-contribution answers."),
        plan("Basavanna and Varkari trajectories", [12], "Lingayat and Veerashaiva are not synonyms; Eknath dates conflict.", "Compare Kannada and Marathi institutions."),
        plan("Women and the limits of inclusion", [13], "Named participation does not establish equality.", "Write inclusion and patriarchal qualification together."),
        plan("Sufi orders are not one position", [14], "Property, court distance and ritual vary by silsilah.", "Prevent a flattened synthesis answer."),
        plan("Chishti place, person and text links", [15], "Named cultural links do not prove doctrinal merger.", "Build evidence around Ajmer, Delhi and the Adi Granth."),
        plan("Sufi practices and source genres", [16], "Practice vocabulary and source genres answer different questions.", "Strengthen evidence criticism."),
        plan("Where synthesis works and fails", [17], "Shared form is stronger evidence than a claim of merged theology.", "Use mechanism plus counter-current."),
        plan("Philosophy, monuments, festivals and PYQs", [18, 19], "Do not invent patron intention or solve unsupported objective halves.", "Prepare the direct 2020 route and current ICH close."),
    ],
    [
        panel("Cultural-framework root", "root-axes", ["BELIEF -> subject and symbolism", "PATRONAGE -> institution and monument", "LANGUAGE -> devotional public", "PRACTICE -> pilgrimage, music and festival"], ["Religion and philosophy as cultural frameworks"]),
        panel("Purushartha map", "hierarchy", ["ARTHA -> material means", "DHARMA -> social regulation", "KAMA -> pleasure and love", "MOKSHA -> liberation"], ["Purushartha and the six darshanas"]),
        panel("Vedanta discriminator", "comparison-table", ["ADVAITA -> nirguna, knowledge, jivanmukti", "VISHISHTADVAITA -> attributes and devotion", "DVAITA -> Madhva and Brahma Sampradaya", "TRAP -> Pushtimarg belongs to Vallabha"], ["Advaita, Vishishtadvaita and Dvaita"]),
        panel("Bhakti causal model", "causal-system", ["ORTHODOXY / CASTE RIGIDITY -> reaction", "MARGINALISED PUBLICS -> inclusion claim", "BUDDHIST-JAIN DECLINE -> religious space", "ROYAL PATRONAGE -> institutional growth"], ["Why Bhakti emerged"]),
        panel("Tamil canon matrix", "comparison-table", ["NAYANARS -> 63, Shaiva, Tamil", "ALVARS -> 12, Vaishnava, Tamil", "ANDAL -> sole woman in Alvar canon", "TEMPLE -> compilation and sculptural afterlife"], ["Tamil Bhakti canons"]),
        panel("Bhakti literature rail", "evidence-table", ["KABIR -> doha and Sant Bhasha", "TULSIDAS -> Awadhi Ramcharitmanas", "SURDAS -> Braj Sur Sagar", "BASAVANNA / TUKARAM -> Vachana and Abhanga"], ["Saguna, Nirguna and named literature", "Basavanna and Varkari trajectories"]),
        panel("Women and authority", "decision-tree", ["NAMED WOMAN -> identify region and tradition", "ROUTE -> household or renunciant practice", "CANON -> test institutional remembrance", "VERDICT -> participation did not equal emancipation"], ["Women and the limits of inclusion"]),
        panel("Sufi order matrix", "comparison-table", ["CHISHTI -> service and court distance", "SUHRAWARDI -> property and scholarship", "QADIRI / SHATTARI -> named cultural links", "NAQSHBANDI -> counter-current to harmony"], ["Sufi orders are not one position"]),
        panel("Chishti cultural circuit", "spatial-map", ["AJMER -> Moinuddin, khanqah and urs", "DELHI -> Nizamuddin and Amir Khusrau", "PUNJAB -> Baba Farid in Adi Granth", "RULE -> place, person, practice and text"], ["Chishti place, person and text links"]),
        panel("Sufi evidence grammar", "comparison-table", ["MALFUZAT -> conversations", "MAKTUBAT -> letters", "TAZKIRAS -> biographies", "SAMA / ZIYARAT -> practice, not source genre"], ["Sufi practices and source genres"]),
        panel("Synthesis test", "decision-tree", ["SHARED SPACE / FORM? -> name it", "TRANSLATION / TEXT? -> identify it", "DOCTRINAL MERGER? -> prove, do not assume", "LIMIT -> power, opposition and counter-current"], ["Where synthesis works and fails"]),
        panel("Philosophy-to-art spine", "answer-spine", ["IDEA -> identify the doctrine or practice", "DESIGN -> show the formal conversion", "MONUMENT -> name the evidence", "QUALIFY -> patronage, material and intention"], ["Philosophy, monuments, festivals and PYQs"]),
    ],
    ["Purushartha", "Shada Darshanas", "Samkhya", "Yogasutra", "Prasthanatrayi", "Advaita", "Vishishtadvaita", "Nalayira Divya Prabandham", "Saguna", "Nirguna", "Vachana", "Abhanga", "Chishti", "Suhrawardi", "malfuzat", "Deepavali"],
    "The verified direct Mains route is 2020 GS-I on Indian philosophy and tradition shaping monuments and art. The 2022 Ramanuja and Somnath objective routes remain answer-letter-free, with the Somnath-Al-Biruni-Pran Pratishtha demand explicitly bounded where local evidence is absent; the 2025 Akbar question is adjacent and owned by Medieval History.",
    [
        ("2020", "GS-I", "Indian philosophy and tradition played a significant role in conceiving and shaping the monuments and their art in India. Discuss. (Answer in 250 words)", "Verified routed direct Mains demand; Core ownership supersedes the legacy Advanced pointer.", "Open with doctrine made visible through design. Use aniconism and the stupa for conception; Nandi's axial placement, Bhakti temple enclosure and Nayanar reliefs for shaping; Purushartha as a qualified reading of Khajuraho. End by stating that philosophy operated with patronage, material, craft and political context rather than mechanically determining form."),
    ],
    live_sources=[
        "https://culture.gov.in/events/deepavali-inscribed-unescos-intangible-cultural-heritage-list",
    ],
    current_note=("The Ministry of Culture and UNESCO pages rechecked on 2026-09-04 record Deepavali's inscription on 10 December 2025 at the twentieth Intergovernmental Committee session at the Red Fort and identify a diverse community practice. The package uses it as a living-heritage and transmission example, not as proof of one uniform religious meaning, doctrinal merger or unconflicted synthesis."),
    extra=[
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "basic/04_Indo-Islamic-and-Regional-Architecture.md",
        "basic/08_Indian-Music.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/11_Languages-Scripts-Literature-and-Manuscripts.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)


TOPIC_14 = common.topic(
    14,
    "Heritage Conservation, Institutions and UNESCO",
    "14_Heritage-Conservation-Institutions-and-UNESCO",
    "14_Heritage-Conservation-Institutions-and-UNESCO_Complete-Topic-Package.md",
    [
        ("Four-category firewall", "World Heritage, Intangible Cultural Heritage, Memory of the World and Geographical Indications are four non-interchangeable systems with different objects, instruments and granting bodies."),
        ("World Heritage mechanism", "World Heritage properties are inscribed under the 1972 Convention for cultural, natural or mixed outstanding universal value by the World Heritage Committee with advisory bodies; inscription is an obligation, not a transfer of sovereignty."),
        ("Intangible heritage mechanism", "The 2003 Convention covers living practices, expressions, knowledge and skills through the Representative List, Urgent Safeguarding List and Register of Good Safeguarding Practices; recognition alone does not ensure transmission."),
        ("Memory of the World mechanism", "Memory of the World concerns documentary heritage such as manuscripts and archives, where custody, cataloguing, conservation and digitisation remain distinct from site management."),
        ("GI is domestic IP", "A Geographical Indication is origin-linked intellectual property under India's GI Act and GI Registry, not a UNESCO programme or general heritage-quality mark."),
        ("ASI and its statutes", "The Archaeological Survey of India was established in 1861 under Alexander Cunningham and functions through the AMASR Act, 1958 and Antiquities and Art Treasures Act, 1972 for monuments, archaeology and antiquities."),
        ("Akademi mandate map", "Sahitya Akademi serves literature, Sangeet Natak Akademi performing arts and Lalit Kala Akademi fine arts; founding dates and programmes do not make their mandates interchangeable."),
        ("Documentary and research institutions", "The National Mission for Manuscripts, National Archives, IGNCA, NMMA, Anthropological Survey, Asiatic Society, ICCR and CCRT perform different documentation, custody, research, cultural-relations and training roles."),
        ("Constitutional heritage frame", "Article 29 protects community language, script and culture; Article 49 directs State protection against spoliation, disfigurement, destruction, removal, disposal or export; Article 51A(f) places a citizen duty to value and preserve composite heritage."),
        ("AMASR zone firewall", "The generally prohibited first 100 metres and regulated next 200 metres around a centrally protected monument arise from Indian statute and are not UNESCO buffer zones mapped through nomination and management documents."),
        ("Threat-to-instrument matching", "Visitor load, urban construction, climate, disaster, material loss, illicit trade and transmission failure damage heritage through different mechanisms and require different legal, technical, archival or livelihood responses."),
        ("Conservation and restoration", "Conservation stabilises and retains fabric through minimum documented intervention, while restoration returns an object to a selected earlier state and therefore raises greater authenticity and reversibility risks."),
        ("Community rights in living sites", "Active worship, ancestor practice, access and livelihood are conservation variables at sites such as Matangeshvara and Moidams; fabric protection cannot presume that a heritage place is socially empty."),
        ("Danger List conditionality", "Manas and Hampi were once on the List of World Heritage in Danger and were later removed after improvement, proving that inscription remains conditional on continuing management."),
        ("Moidams evidence", "Moidams at Charaideo are Tai-Ahom mound-covered royal burial vaults with shrine and octagonal enclosure in a continuing funerary landscape, inscribed in 2024 under criteria (iii) and (iv)."),
        ("Recent World Heritage ledger", "Nalanda, Mumbai's Victorian Gothic and Art Deco ensembles, Dholavira, Ramappa, Santiniketan, the Hoysala ensembles, Moidams, the Maratha Military Landscapes and Sarnath form a dated 2016-2026 ledger; it is not India's complete list."),
        ("Intangible heritage ledger", "The dated Indian ICH ledger runs from 2008 elements through Deepavali in 2025, includes the multinational Nowruz entry, and must keep inscription year separate from any changing total or latest-item question."),
        ("Schemes, funds and statutes", "Adopt a Heritage and Adarsh Smarak are executive amenity or participation schemes, the National Culture Fund is a funding mechanism, and AMASR and the Antiquities Act are statutes; none may be substituted for another."),
        ("Current World Heritage status", "UNESCO records the Ancient Buddhist Site of Sarnath as a serial property inscribed on 25 July 2026 and official UNESCO reporting identifies it as India's forty-fifth World Heritage property; the Maratha Military Landscapes remains the 2025 forty-fourth entry."),
        ("Verified heritage PYQ routes", "The direct routed Mains demand is 2018 safeguarding Indian art heritage; objective routes cover 2023 archaeologists, 2024 Santiniketan-Hoysalas and provisional 2026 Moidams, with no answer letter inferred."),
    ],
    [
        "Do not call WHS, ICH, Memory of the World and GI interchangeable tags.",
        "Do not treat Tentative List status as World Heritage inscription.",
        "Do not claim that UNESCO takes ownership or legal jurisdiction over an Indian property.",
        "Do not treat recognition as completed safeguarding.",
        "Do not substitute an AMASR control zone for a UNESCO buffer zone.",
        "Do not call ASI, SNA, LKA, Sahitya Akademi and NMM interchangeable bodies.",
        "Do not call a scheme a statute or a fund a conservation authority.",
        "Do not say Adopt a Heritage transfers structural conservation to a private partner.",
        "Do not use conservation and restoration as synonyms.",
        "Do not treat monuments and living sites as socially empty fabric.",
        "Do not present World Heritage status as permanent or cost-free.",
        "Do not convert a recent-inscription ledger into India's total list.",
        "Do not confuse an extension year with first inscription.",
        "Do not state current counts without a dated direct official source.",
        "Do not invent repatriations, budgets, staff numbers, visitor figures or project outcomes.",
    ],
    [
        (10, "Distinguish World Heritage, ICH, Memory of the World and GI.", "The four-category firewall matches tangible property, living practice, documentary record and origin-linked product name to four different instruments and institutions.", [0, 1, 2, 3, 4]),
        (10, "Explain the constitutional and statutory architecture of heritage protection in India.", "Articles 29, 49 and 51A(f) supply the constitutional frame while AMASR and antiquities law enable domain-specific protection through ASI.", [5, 8, 9]),
        (15, "Discuss safeguarding Indian art heritage as a present need.", "Current damage mechanisms require instrument-fit: monument law for fabric, archives for documents, academies for transmission, GI for names, funds for finance and community consent for living sites.", [10, 17, 19]),
        (15, "Compare conservation and restoration and assess the role of community rights.", "Minimum intervention protects evidentiary fabric, while restoration selects a past and living use adds access, ritual and livelihood claims that technical conservation must negotiate.", [11, 12]),
        (20, "Evaluate UNESCO recognition as a tool of heritage conservation.", "International recognition creates leverage, duties and visibility but also visitor pressure, conditional monitoring and authenticity trade-offs that domestic institutions must manage.", [1, 2, 13, 14, 18]),
        (20, "Assess India's heritage institutions through mandate, capacity and coordination.", "India has specialised bodies and instruments; the core challenge is matching mandate and threat while maintaining dated status discipline, documentation and public participation.", [5, 6, 7, 15, 16, 17]),
    ],
    [
        plan("The four-category firewall", [0, 1, 2, 3, 4], "Four systems protect different cultural objects.", "Prevent the most frequent heritage-status error."),
        plan("World Heritage as conditional obligation", [1, 13], "Inscription does not transfer sovereignty or guarantee permanence.", "Evaluate benefit, duty and Danger List leverage."),
        plan("Living and documentary heritage", [2, 3], "Recognition, custody and transmission remain different tasks.", "Compare ICH and Memory of the World."),
        plan("ASI and the statutory base", [5], "Institutional founding and statutory mandate answer different questions.", "Name the monument-and-antiquities owner precisely."),
        plan("Akademis and cultural institutions", [6, 7], "Overlapping projects do not erase primary mandates.", "Build an institution-by-function map."),
        plan("Constitutional heritage duties", [8], "Articles have different right, State-duty and citizen-duty structures.", "Give the domestic normative frame."),
        plan("AMASR zones and UNESCO buffers", [9], "Domestic statutory distance is not an international management boundary.", "Prepare a close-option legal distinction."),
        plan("Threats and instrument fit", [10], "Each damage mechanism needs a matched response.", "Convert a generic threat list into policy analysis."),
        plan("Conservation versus restoration", [11], "Restoring an earlier state always selects and may erase a layer.", "Explain authenticity and reversibility."),
        plan("Community rights and living use", [12], "Access and ritual are conservation variables, not noise.", "Balance fabric, worship and livelihood."),
        plan("Moidams form and status", [14], "Funerary architecture and political history must remain distinct.", "Prepare the provisional 2026 route."),
        plan("Recent World Heritage chronology", [15], "A dated partial ledger is not a national total.", "Retain property and serial-component discipline."),
        plan("Indian ICH chronology", [16], "Nowruz is multinational and latest-item answers are date-bound.", "Use inscription years rather than stale totals."),
        plan("Schemes, funds and statutes", [17], "Amenities, finance, regulation and conservation are different functions.", "Prevent institutional category errors."),
        plan("Sarnath, safeguarding PYQ and final spine", [18, 19], "Current recognition must be tied to a direct dated source.", "Close with the direct 2018 demand and current UNESCO evidence."),
    ],
    [
        panel("Four-category firewall", "comparison-table", ["WHS -> tangible or mixed property", "ICH -> living practice and transmission", "MoW -> documentary record", "GI -> domestic origin-linked IP"], ["The four-category firewall"]),
        panel("Conditional-status loop", "causal-system", ["INSCRIPTION -> recognition and duty", "MONITORING -> management scrutiny", "DANGER LIST -> corrective pressure", "REMOVAL -> improvement can restore status"], ["World Heritage as conditional obligation"]),
        panel("Institution mandate map", "institution-map", ["ASI -> monuments and archaeology", "SNA -> performing arts", "SAHITYA / LKA -> literature and fine arts", "NMM / ARCHIVES -> manuscripts and records"], ["Akademis and cultural institutions"]),
        panel("Constitutional ladder", "hierarchy", ["ARTICLE 29 -> community cultural right", "ARTICLE 49 -> State monument duty", "ARTICLE 51A(f) -> citizen duty", "STATUTES -> operational protection"], ["Constitutional heritage duties"]),
        panel("Boundary firewall", "comparison-table", ["AMASR 100 m -> generally prohibited", "AMASR next 200 m -> regulated", "UNESCO BUFFER -> mapped management zone", "RULE -> separate legal sources"], ["AMASR zones and UNESCO buffers"]),
        panel("Threat-response matrix", "evidence-table", ["VISITOR LOAD -> access management", "URBAN / CLIMATE -> regulation and monitoring", "DISASTER / DECAY -> documentation and conservation", "TRANSMISSION LOSS -> practitioner support"], ["Threats and instrument fit"]),
        panel("Conservation-restoration test", "comparison-table", ["CONSERVE -> stabilise existing fabric", "RESTORE -> return to chosen earlier state", "REVERSIBILITY -> preferred in conservation", "AUTHENTICITY -> risk rises with reconstruction"], ["Conservation versus restoration"]),
        panel("Living-site balance", "decision-tree", ["ACTIVE WORSHIP? -> protect access", "LIVELIHOOD? -> assess displacement", "FRAGILE FABRIC? -> regulate use", "VERDICT -> negotiate, do not empty the site"], ["Community rights and living use"]),
        panel("Moidams form map", "spatial-map", ["VAULT -> hollow royal burial chamber", "MOUND -> earth-covered form", "SHRINE + WALL -> ritual enclosure", "LANDSCAPE -> continuing ancestor practice"], ["Moidams form and status"]),
        panel("Recent WH ledger", "timeline", ["2016 -> Nalanda", "2021 -> Dholavira and Ramappa", "2023 -> Santiniketan and Hoysalas", "2024 / 2025 / 2026 -> Moidams, Maratha forts, Sarnath"], ["Recent World Heritage chronology"]),
        panel("Scheme-statute firewall", "comparison-table", ["AMASR / ANTIQUITIES -> statutes", "ADOPT A HERITAGE -> amenities partnership", "ADARSH SMARAK -> visitor amenities", "NCF -> funding mechanism"], ["Schemes, funds and statutes"]),
        panel("Heritage answer spine", "answer-spine", ["DIAGNOSE -> category and threat", "MATCH -> law, body, fund or scheme", "EVIDENCE -> named site or practice", "QUALIFY -> capacity, community and dynamic status"], ["Sarnath, safeguarding PYQ and final spine"]),
    ],
    ["World Heritage", "Intangible Cultural Heritage", "Memory of the World", "Geographical Indication", "AMASR", "Antiquities and Art Treasures Act", "Article 49", "Article 51A(f)", "Danger List", "Moidams", "Santiniketan", "Sacred Ensembles of the Hoysalas", "Deepavali", "Adopt a Heritage", "National Culture Fund", "Sarnath"],
    "The verified direct Mains route is 2018 GS-I on safeguarding Indian art heritage as a present need. The objective routes are 2023 colonial archaeologists, 2024 the 2023 inscriptions of Santiniketan and the Hoysala ensembles, and provisional 2026 Moidams; objective answer letters are not inferred.",
    [
        ("2018", "GS-I", "Safeguarding the Indian art heritage is the need of the moment. Discuss. (Answer in 150 words)", "Verified routed direct Mains demand; Core ownership supersedes the legacy Advanced pointer.", "Define safeguarding as threat-to-instrument matching. Use the WHS-ICH-MoW-GI firewall, then name ASI and AMASR for monuments, NMM or Archives for documents, academies for living arts and GI for names. Add visitor, climate, illicit-trade and transmission pressures, one dated property or practice, the capacity and community limit, and a verdict that recognition begins rather than completes protection."),
    ],
    live_sources=[
        "https://www.unesco.org/en/articles/ancient-buddhist-site-sarnath-inscribed-unesco-world-heritage-list",
        "https://whc.unesco.org/en/list/927",
        "https://whc.unesco.org/en/list/1739",
        "https://whc.unesco.org/en/danger/",
        "https://ich.unesco.org/en/RL/deepavali-02312",
        "https://ich.unesco.org/en/files-2026-under-process-01395",
        "https://www.unesco.org/en/memory-world/register2025",
        "https://asi.nic.in/pages/Monuments",
        "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=1954675",
    ],
    current_note=("Official sources rechecked on 2026-09-04 record the Ancient Buddhist Site of Sarnath as a serial property inscribed on 25 July 2026 and identify it as India's forty-fifth World Heritage property; Maratha Military Landscapes remains the 2025 forty-fourth entry. UNESCO's live lists show no Indian property on the Danger List and no later Indian ICH inscription before the late-2026 cycle; the 2025 Memory register retains fourteen Indian inscriptions. ASI records 3,679 centrally protected monuments and sites, while PIB confirms Adopt a Heritage 2.0 as a visitor-amenities programme. Counts and latest-status claims are valid only with this access date."),
    extra=[
        "basic/03_Temple-Architecture-and-Chandella-Khajuraho.md",
        "basic/05_Colonial-and-Post-Independence-Architecture.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/11_Languages-Scripts-Literature-and-Manuscripts.md",
        "basic/12_Crafts-Textiles-Folk-and-Tribal-Traditions.md",
        "basic/13_Religion-Philosophy-and-Cultural-Synthesis.md",
    ],
)


TOPIC_15 = common.topic(
    15,
    "Indian Cinema, Film Institutions and Awards",
    "15_Indian-Cinema-Film-Institutions-and-Awards",
    "15_Indian-Cinema-Film-Institutions-and-Awards_Complete-Topic-Package.md",
    [
        ("Cinema as composite art", "Cinema combines literature or story, performance, moving image, colour and production design, music and sound, and editing, then adds reproducibility and mass circulation."),
        ("Film-form vocabulary", "Cinematography creates moving images through camera, lens, lighting, framing and movement; editing arranges shots; mise-en-scene organises setting, costume, light, performance and composition within the frame."),
        ("Documentary and animation", "Documentary is non-fiction but still selected and framed, while animation creates movement from drawn, modelled or computer-generated frames; neither is a lesser appendage to feature fiction."),
        ("Arrival and indigenisation", "Motion pictures were shown in Bombay in 1896, an Indian-shot film appeared in 1897, Indian filmmakers made shorts by 1899 and Indian-owned exhibition infrastructure developed before the indigenous feature of 1913."),
        ("Silent cinema and Phalke", "Indian silent films used live musical accompaniment; Raja Harishchandra in 1913 is the first indigenous Indian silent feature, while Lanka Dahan in 1917 is identified as the first box-office hit."),
        ("Fatma Begum milestone", "Fatma Begum became the first Indian woman to produce and direct her own film with Bulbul-e-Paristan in 1926; this is a dated production-history fact, not a general claim about equality in the industry."),
        ("Talkie and recorded song", "Alam-Ara in 1931 was the first Indian talkie, with W.M. Khan associated with the first recorded song in Indian cinema; sound changed performance, music and language markets."),
        ("Colour-film firewall", "Sairandhri in 1933 was the first Indian colour film but was processed in Germany, whereas Kisan Kanya in 1937 was the first indigenously made colour film."),
        ("Parallel cinema", "From the late 1940s parallel cinema offered an alternative to mainstream commercial production through poverty, injustice and everyday suffering, with Satyajit Ray, Ritwik Ghatak, Guru Dutt and Shyam Benegal named by the owner."),
        ("Representation is bounded evidence", "Films reveal how gender, caste, region and nation were represented and what producers expected audiences to accept, but they are not direct social surveys or measures of lived conditions."),
        ("Multilingual regional field", "Indian cinema is structured through multiple language markets, regional production, dubbing and administration; it cannot be equated with Hindi-language cinema or Bollywood."),
        ("MIB, Act and CBFC", "The Ministry of Information and Broadcasting is the Union policy anchor, the Cinematograph Act, 1952 supplies the certification framework, and CBFC certifies public exhibition rather than judging artistic merit."),
        ("Certification powers and federal split", "The statutory scheme permits audience categories, modifications or refusal of sanction; certification is a Union function while State governments enforce exhibition controls in their domains."),
        ("Certification versus censorship", "Certification classifies audiences, while censorship modifies or suppresses content; under the amended Act the UA markers are UA7+, UA13+ and UA16+, section 5C appeals lie to the High Court, and section 5D's FCAT was omitted in 2021."),
        ("FTII training function", "FTII at Pune, established in 1960 as a society under the Ministry of Information and Broadcasting, performs training rather than certification, archiving or awards."),
        ("NFAI and NFDC consolidation", "Film preservation was institutionally associated with NFAI from 1964, while the Government's 23 December 2020 decision merged the functions of NFAI, Films Division, DFF and CFSI into NFDC's integrated development architecture."),
        ("Award and festival firewall", "National Film Awards, BAFTA, Academy Awards and Cannes, Venice or Berlin prizes belong to different institutions; festival selection, nomination and winning are separate statuses."),
        ("Dadasaheb Phalke Award", "Instituted in 1969, the Dadasaheb Phalke Award is India's highest award in cinema and commemorates the maker of Raja Harishchandra; its stable identity must be separated from changing administrative arrangements and recipients."),
        ("Preservation and soft power", "Film preservation confronts material decay, obsolete formats and selection bias, while festivals, awards and streaming widen visibility; international recognition is neither preservation nor proof of cultural superiority."),
        ("Boong and verified route", "BAFTA's official category page lists Boong with Lakshmipriya Devi and Ritesh Sidhwani in Children's and Family Film; the provisional 2026 objective route tests category, person and milestone separately, and no answer letter is inferred."),
    ],
    [
        "Do not force cinema into theatre merely because both use performance.",
        "Do not treat documentary as an unmediated record.",
        "Do not confuse first exhibition, first Indian-shot film and first indigenous feature.",
        "Do not call silent cinema literally silent where live accompaniment is documented.",
        "Do not omit Fatma Begum from the dated firsts.",
        "Do not confuse Sairandhri with Kisan Kanya.",
        "Do not equate Indian cinema with Hindi-language cinema.",
        "Do not treat film representation as a social survey.",
        "Do not call CBFC an award jury or quality assessor.",
        "Do not use certification and censorship as exact synonyms.",
        "Do not describe FCAT as current after its 2021 omission or ignore the UA7+, UA13+ and UA16+ markers.",
        "Do not merge FTII, NFAI, NFDC, IFFI and the National Film Awards by function.",
        "Do not treat festival selection or nomination as a prize.",
        "Do not treat BAFTA and the Academy Awards as one institution.",
        "Do not invent award winners, archive holdings, restoration counts, box-office data or screen totals.",
        "Do not expand a category-specific first claim into a universal Indian-cinema first.",
    ],
    [
        (10, "Explain why cinema is a distinct composite modern art form.", "Cinema recombines older narrative, performance, image and music traditions through camera, editing, recorded sound and mass reproducibility.", [0, 1, 2]),
        (10, "Distinguish film certification, festival selection and an award.", "Certification is a legal exhibition decision, festival selection is programming, and an award is institutional recognition after a distinct jury process.", [11, 13, 16]),
        (15, "Trace the early development and indigenisation of Indian cinema.", "Imported exhibition technology was rapidly localised through Indian shooting, ownership, live musical practice, feature production, sound and colour, with every first kept distinct.", [3, 4, 5, 6, 7]),
        (15, "Assess cinema as evidence of social change and regional plurality.", "Film representation records cultural imagination and audience expectation across many language markets, but it cannot substitute for measured social history.", [8, 9, 10]),
        (20, "Critically examine India's film-institutional architecture.", "Certification, training, archiving, development, festivals and awards perform different functions, while consolidation promises coordination and raises a specialist-mandate risk that must remain analytical rather than asserted.", [11, 12, 13, 14, 15, 17]),
        (20, "Discuss preservation, awards and soft power in Indian cinema.", "Cultural value depends on form, regional representation, archival survival and access; awards expand visibility but should neither determine preservation priorities nor stand in for significance.", [18, 19, 16]),
    ],
    [
        plan("Cinema as a composite modern art", [0], "Shared acting does not make cinema a branch of theatre.", "Define the medium through form and circulation."),
        plan("Camera, editing and the frame", [1], "Technical vocabulary must explain how meaning is made.", "Build a form-first answer."),
        plan("Documentary and animation", [2], "Non-fiction remains framed and animation remains cinema.", "Expand the field beyond feature fiction."),
        plan("From exhibition to Indian production", [3], "Several different firsts occur between 1896 and 1913.", "Construct the indigenisation chronology."),
        plan("Silent film, live music and Phalke", [4], "First feature and first box-office hit are distinct.", "Link cinema with music and exhibition."),
        plan("Women behind the camera", [5], "One milestone does not prove industry-wide equality.", "Use Fatma Begum as named production evidence."),
        plan("Sound transforms cinema", [6], "Talkie, playback and recorded song are separate claims.", "Explain how sound reshaped markets and performance."),
        plan("The colour-film close option", [7], "Processing abroad and indigenous production are different criteria.", "Defeat the 1933 versus 1937 trap."),
        plan("Parallel and commercial cinema", [8], "Alternative subject matter does not imply equal reach.", "Compare form, theme and circulation."),
        plan("Representation and social evidence", [9], "Film shows representation, not measured social conditions.", "Use gender and class evidence cautiously."),
        plan("Indian cinema as many language markets", [10], "National cinema cannot be reduced to Bollywood.", "Connect language, dubbing and regional administration."),
        plan("Cinematograph Act and CBFC", [11, 12], "The regulator is not a jury and States do not issue certificates.", "Map law, Board and enforcement."),
        plan("Certification and censorship tension", [13], "Use the amended Act: UA age markers and High Court appeal, not the abolished FCAT.", "Write a balanced regulatory verdict."),
        plan("Training, archive and development", [14, 15], "Institutional consolidation does not erase functional differences.", "Compare FTII, NFAI and NFDC."),
        plan("Awards, preservation, Boong and PYQ boundary", [16, 17, 18, 19], "Recognition must remain category-specific and cannot prove value.", "Close with verified institutions and no inferred answer letter."),
    ],
    [
        panel("Composite-art root", "root-axes", ["STORY / LITERATURE -> narrative", "PERFORMANCE + DESIGN -> staged world", "CAMERA + SOUND -> recorded form", "EDITING + CIRCULATION -> cinematic meaning and reach"], ["Cinema as a composite modern art"]),
        panel("Film-form grammar", "comparison-table", ["CINEMATOGRAPHY -> moving image", "EDITING -> shot arrangement", "MISE-EN-SCENE -> within-frame design", "DOCUMENTARY -> selected non-fiction"], ["Camera, editing and the frame", "Documentary and animation"]),
        panel("Indigenisation timeline", "timeline", ["1896 -> Bombay exhibition", "1897 / 1899 -> Indian-shot and Indian-made shorts", "1907 -> Indian-owned exhibition house", "1913 -> indigenous silent feature"], ["From exhibition to Indian production"]),
        panel("Silent-era circuit", "causal-system", ["SILENT IMAGE -> live instruments", "PHALKE -> Raja Harishchandra", "LANKA DAHAN -> box-office milestone", "MASS PUBLIC -> myth, music and reproducibility"], ["Silent film, live music and Phalke"]),
        panel("Sound-colour sequence", "timeline", ["1931 -> Alam-Ara talkie", "RECORDED SONG -> W.M. Khan", "1933 -> Sairandhri, processed abroad", "1937 -> Kisan Kanya, indigenous colour"], ["Sound transforms cinema", "The colour-film close option"]),
        panel("Two-cinema matrix", "comparison-table", ["COMMERCIAL -> mass entertainment", "PARALLEL -> social-realist alternative", "COMMON -> production and distribution constraints", "LIMIT -> reach and value are not identical"], ["Parallel and commercial cinema"]),
        panel("Representation test", "decision-tree", ["WHAT IS SHOWN? -> representation", "WHO PRODUCED IT? -> institutional choice", "WHO WAS ADDRESSED? -> expected audience", "LIMIT -> not a social census"], ["Representation and social evidence"]),
        panel("Multilingual field", "spatial-map", ["LANGUAGE MARKET -> production", "REGIONAL OFFICE -> administration", "DUBBING -> fresh certification issue", "RULE -> Indian cinema exceeds Hindi cinema"], ["Indian cinema as many language markets"]),
        panel("Regulatory chain", "process-flow", ["CBFC -> U / UA7+ / UA13+ / UA16+ / A / S", "MODIFICATION / REFUSAL -> statutory powers", "SECTION 5C -> High Court appeal", "SECTION 5D -> FCAT omitted in 2021"], ["Cinematograph Act and CBFC", "Certification and censorship tension"]),
        panel("Institution function map", "institution-map", ["FTII -> training", "NFAI -> preservation legacy", "NFDC -> integrated development and promotion", "IFFI / AWARDS -> exhibition and recognition"], ["Training, archive and development"]),
        panel("Recognition firewall", "comparison-table", ["CERTIFICATE -> exhibition status", "SELECTION -> festival programming", "NOMINATION -> award consideration", "WIN -> exact institution, category and year"], ["Awards, preservation, Boong and PYQ boundary"]),
        panel("Cinema answer spine", "answer-spine", ["FORM -> camera, sound and editing", "HISTORY -> dated firsts", "INSTITUTION -> function and law", "QUALIFY -> representation, preservation and award limits"], ["Awards, preservation, Boong and PYQ boundary"]),
    ],
    ["cinematography", "mise-en-scene", "Raja Harishchandra", "Fatma Begum", "Alam-Ara", "Sairandhri", "Kisan Kanya", "parallel cinema", "Cinematograph Act", "CBFC", "FTII", "NFAI", "NFDC", "National Film Awards", "Dadasaheb Phalke Award", "Boong"],
    "No direct GS-I Mains PYQ is routed to Topic 15. The only audited direct route is the provisional 2026 objective demand on Boong, its BAFTA category, credited person and claimed milestone; no answer letter or universal first claim is inferred.",
    [],
    live_sources=[
        "https://mib.gov.in/sites/default/files/2024-12/cinematograph-act-1952-incorporating-latest-amendments.pdf",
        "https://www.mib.gov.in/en/ministry/organizations/national-film-development-corporation-limited",
        "https://www.bafta.org/awards/film/childrens-family/",
        "https://mib.gov.in/en/press-releases/legendary-actor-director-and-producer-mohanlal-be-honoured-dadasaheb-phalke-award",
    ],
    current_note=("Official MIB and BAFTA sources rechecked on 2026-09-04 show that the amended Cinematograph Act uses UA7+, UA13+ and UA16+ markers, sends section 5C appeals to the High Court and omits FCAT under section 5D from 2021. MIB confirms NFDC's 1975 setup and the four-unit consolidation; BAFTA lists Boong with Lakshmipriya Devi and Ritesh Sidhwani in Children's and Family Film. The latest located official Dadasaheb Phalke announcement names Mohanlal for award year 2023; no 2026 recipient, archive total, box-office figure or broader first claim is invented."),
    extra=[
        "basic/08_Indian-Music.md",
        "basic/10_Theatre-Puppetry-and-Performance-Traditions.md",
        "basic/13_Religion-Philosophy-and-Cultural-Synthesis.md",
        "basic/14_Heritage-Conservation-Institutions-and-UNESCO.md",
    ],
)
