"""Authored content data for Indian Art and Culture learner-v2 Topics 01-05."""

from __future__ import annotations

import generate_indian_art_culture_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_01 = common.topic(
    1,
    "Architecture Foundations and Harappan Urbanism",
    "01_Architecture-Foundations-and-Harappan-Urbanism",
    "01_Architecture-Foundations-and-Harappan-Urbanism_Complete-Topic-Package.md",
    [
        ("Architecture reading axes", "Architecture is read through material, plan, elevation and function; patronage, ecology and evidence limits convert description into analysis."),
        ("Rectangular grid", "Harappan streets commonly ran north-south and east-west and met at right angles, making pre-planning rather than organic accretion the central inference."),
        ("Citadel and lower town", "The upraised western citadel held large public structures, while the larger lower town was predominantly residential; this is functional zoning, not proof of caste."),
        ("Standardised burnt brick", "Harappan builders used standardised burnt mud bricks laid in layers and joined with gypsum mortar, indicating a shared technical norm."),
        ("Maintainable drainage", "House drains joined larger covered street drains with cesspits and removable covers, so maintenance was built into the civic system."),
        ("Domestic water design", "Private wells, ventilated bathrooms and stairs indicating some double-storeyed houses placed water and hygiene within ordinary domestic architecture."),
        ("Great Bath", "Mohenjo-daro's Great Bath was a large public water structure surrounded by rooms and galleries; ritual cleansing is a plausible inference, not an inscriptional fact."),
        ("Conventional granary label", "Raised platforms and ventilation support a storage interpretation, but 'granary' remains a modern archaeological label rather than an ancient attested name."),
        ("No confirmed palace or temple", "No large structure has been securely identified as a Harappan palace or temple, distinguishing the evidence from Egyptian and Mesopotamian royal-sacred monumentality."),
        ("Dholavira adaptation", "Dholavira combined a fortified multi-part settlement with reservoirs and water-harnessing systems, proving that shared Harappan norms allowed regional adaptation."),
        ("Lothal basin caution", "Lothal's basin is conventionally called a dockyard, but its precise function remains debated and must be presented conditionally."),
        ("Harappa and Kalibangan variation", "Harappa's large brick platforms and Kalibangan's distinctive planning prevent Mohenjo-daro from becoming an identical template for every settlement."),
        ("Standardisation inference", "Repeated bricks, grids and drainage imply coordination or a shared technical culture, but do not by themselves prove one centralised empire."),
        ("Undeciphered-script boundary", "The undeciphered-script boundary is the evidentiary limit created by the absence of readable Harappan texts and securely named buildings; reconstructions of rulers, religion and social order therefore remain graded."),
        ("Meluha and external contact", "Indus seals in Mesopotamia support long-distance trade contact; the identification of the Harappans with Mesopotamian Meluha remains a scholarly argument."),
        ("Civic versus monumental priority", "Harappan surplus is most visible in streets, drains, wells, baths and storage rather than confirmed royal tombs or temples."),
        ("Verified 2025 Mains demand", "The verified 2025 GS-I question asks for the salient features of Harappan architecture in 150 words, making selection and evidentiary caution essential."),
        ("Water-architecture firewall", "Harappan water works were settlement-wide civic infrastructure; later stepwells and temple tanks served different ritual, commemorative or storage purposes."),
        ("Official Dholavira linkage", "UNESCO's official Dholavira property page describes planned urban areas, fortifications, reservoirs and drainage; it is used only as current official corroboration."),
        ("Harappan answer spine", "A high-value answer moves from grid to zoning, public works, drainage, material and regional variation, then closes with the palace-temple evidence limit."),
    ],
    [
        "Do not identify any Harappan building as a confirmed palace or temple.",
        "Do not convert functional zoning into a proven caste hierarchy.",
        "Do not call the Lothal basin an uncontested dockyard.",
        "Do not infer a centralised empire from brick standardisation alone.",
        "Do not present ritual use of the Great Bath as inscriptionally proved.",
        "Do not describe stone as the primary Harappan building material.",
        "Do not project Mohenjo-daro's plan unchanged onto every site.",
        "Do not invent brick ratios, street widths, populations or bath dimensions.",
        "Do not identify the horned seal figure as definitively Shiva.",
        "Do not present Meluha as an uncontested self-name.",
        "Do not make Harappan drains the ancestor of later stepwells.",
        "Do not import a current excavation claim without a dated ASI source.",
        "Do not replace evidence analysis with adjectives such as advanced or scientific.",
        "Do not omit the no-confirmed-palace-or-temple caveat in a critical answer.",
    ],
    [
        (10, "Discuss the salient features of Harappan architecture.", "Harappan architecture was civic rather than dynastic-monumental: a grid, functional zoning, standardised brick, public water works and maintainable drainage reveal coordinated urban norms, while no palace or temple is securely identified.", [1, 2, 3, 4, 6, 8]),
        (10, "Why is drainage central to an assessment of Harappan urbanism?", "Its importance lies in the network from house to street and in provisions for cleaning, which show continuing civic maintenance rather than an isolated engineering object.", [4, 5]),
        (15, "Harappan standardisation operated through regional adaptation. Analyse.", "Shared grids, bricks and water logic were translated into Mohenjo-daro's bath, Dholavira's reservoirs, Lothal's basin and regional plans rather than copied identically.", [1, 3, 9, 10, 11, 12]),
        (15, "To what extent can architecture reconstruct Harappan society?", "Built form supports strong claims about planning, labour and hygiene, weaker claims about differentiation, and no settled claims about named rulers or religion because the script is undeciphered.", [2, 7, 8, 13]),
        (20, "Compare Harappan urban priorities with contemporary monumental traditions.", "The contrast is between repeated civic infrastructure and securely attested royal-sacred monumentality elsewhere; it suggests different visible priorities without proving Harappan irreligion or egalitarianism.", [8, 15, 12, 13]),
        (20, "Examine water architecture in the Harappan city and distinguish it from later Indian water structures.", "Harappan wells, baths, drains and reservoirs formed settlement systems; later stepwells and temple tanks answered aridity, patronage and ritual, so resemblance of medium does not establish continuity of function.", [4, 5, 6, 9, 17]),
    ],
    [
        plan("How to read architecture", [0], "Description earns value only when material, plan, function and evidence are connected.", "Build the method used by all five architecture topics."),
        plan("Grid planning and pre-planning", [1], "A grid indicates planning but does not identify the planner.", "Open a Harappan answer with the spatial system."),
        plan("Citadel and lower town", [2], "Use functional zoning; do not infer a rigid caste map.", "Explain settlement hierarchy without over-reading it."),
        plan("Brick modules and coordination", [3, 12], "Shared standards do not prove one political constitution.", "Turn material into a bounded governance inference."),
        plan("The drainage network", [4], "Stress connection and maintenance, not only covered drains.", "Make civic engineering the standout feature."),
        plan("Water inside the house", [5], "Domestic evidence varies by house and quarter.", "Show ordinary architecture, hygiene and differentiation."),
        plan("Great Bath and ritual inference", [6], "Form supports collective use; ritual meaning remains inferential.", "Separate direct evidence from likely function."),
        plan("Public buildings and labels", [7, 8], "Granary is conventional; palace and temple are unconfirmed.", "Use naming caution as analytical strength."),
        plan("Dholavira's regional solution", [9, 18], "Use the official page only for bounded corroboration.", "Show adaptation in a water-scarce setting."),
        plan("Lothal, Harappa and Kalibangan", [10, 11], "Do not force one city template onto the civilisation.", "Build a site-comparison paragraph."),
        plan("The script and inference ceiling", [13], "Architecture cannot supply names or doctrines the text cannot.", "Answer 'to what extent' demands honestly."),
        plan("Meluha and exchange", [14], "External contact is stronger than the disputed label.", "Add an economic-network dimension without leaving architecture."),
        plan("Civic versus monumental comparison", [15], "Absence of identification is not proof of absence of belief.", "Create the comparative analytical edge."),
        plan("PYQ and water-architecture boundaries", [16, 17], "The direct demand is narrow; later water forms are not descendants.", "Prepare 10- and 15-mark routes."),
        plan("Complete answer architecture", [19, 0], "A graded conclusion must preserve evidence limits.", "Assemble the final Harappan answer spine."),
    ],
    [
        panel("Architecture reading method", "root-axes", ["MATERIAL -> brick, stone, mortar and finish", "PLAN -> grid, zoning, circulation and water", "FUNCTION -> domestic, civic, storage or ritual", "EVIDENCE LIMIT -> form is not an inscription"], ["How to read architecture"]),
        panel("Harappan city grid", "spatial-map", ["NORTH-SOUTH STREET -> planned urban axis", "EAST-WEST STREET -> right-angle crossing", "BLOCKS -> houses and facilities organised", "INFERENCE -> pre-planning, not a named ruler"], ["Grid planning and pre-planning"]),
        panel("Two-part settlement", "comparison", ["CITADEL -> raised western public zone", "LOWER TOWN -> larger residential zone", "HOUSE SIZE -> differentiation is visible", "CAUTION -> caste hierarchy is not proved"], ["Citadel and lower town"]),
        panel("Brick-to-authority chain", "causal-system", ["STANDARD BRICK -> repeatable construction", "GYPSUM MORTAR -> joined layered masonry", "DISTANT SITES -> shared technical norm", "LIMIT -> no proven centralised empire"], ["Brick modules and coordination"]),
        panel("Drainage as a network", "process-flow", ["BATHROOM -> small household drain", "STREET -> larger covered drain", "CESSPIT -> sediment captured", "REMOVABLE COVER -> regular cleaning possible"], ["The drainage network"]),
        panel("Great Bath evidence test", "evidence-table", ["FORM -> tank with surrounding rooms", "DIRECT CLAIM -> collective public water structure", "INFERENCE -> ceremonial or ritual cleansing", "PROHIBITION -> no invented priesthood or rite"], ["Great Bath and ritual inference"]),
        panel("Naming public structures", "decision-tree", ["RAISED PLATFORM + AIR DUCTS -> storage likely", "MODERN LABEL -> conventionally called granary", "NO INSCRIPTION -> function remains debated", "PALACE/TEMPLE -> not securely identified"], ["Public buildings and labels"]),
        panel("Regional urban solutions", "comparison-table", ["MOHENJO-DARO -> Great Bath and drains", "DHOLAVIRA -> fortifications and reservoirs", "LOTHAL -> debated basin", "KALIBANGAN/HARAPPA -> distinct local plans"], ["Dholavira's regional solution", "Lothal, Harappa and Kalibangan"]),
        panel("Evidence ladder", "hierarchy", ["STRONG -> grid, brick, drain and reservoir", "MODERATE -> storage and functional zoning", "WEAK -> precise hierarchy and authority form", "UNSUPPORTED -> named king, temple or state faith"], ["The script and inference ceiling"]),
        panel("Civic and monumental contrast", "comparison", ["HARAPPAN -> streets, wells, baths and drains", "EGYPT/MESOPOTAMIA -> royal-sacred monuments", "ANALYSIS -> different visible investment", "QUALIFY -> preservation and naming biases remain"], ["Civic versus monumental comparison"]),
        panel("Water architecture firewall", "comparison-table", ["HARAPPAN -> settlement supply and sanitation", "STEPWELL -> arid storage and patronage", "TEMPLE TANK -> ritual and processional space", "RULE -> shared water does not prove descent"], ["PYQ and water-architecture boundaries"]),
        panel("Harappan answer spine", "answer-spine", ["OPEN -> civic urbanism thesis", "BODY -> grid, zoning, drainage and brick", "COMPARE -> Dholavira, Lothal and monumentality", "CLOSE -> no confirmed palace or temple"], ["Complete answer architecture"]),
    ],
    ["citadel", "lower town", "Great Bath", "standardised burnt brick", "gypsum mortar", "drainage system", "Dholavira", "Lothal", "Kalibangan", "Meluha", "functional zoning", "undeciphered script"],
    "One direct Mains demand is verified: 2025 GS-I on the salient features of Harappan architecture. Its wording is reproduced only from the routed repository owner; no additional PYQ is invented.",
    [
        ("2025", "GS-I", "Discuss the salient features of the Harappan architecture. (Answer in 150 words)", "Verified verbatim in the Basic and Advanced owners.", "Open with planned grid and zoning; add standardised burnt brick, public works and the house-to-street drainage network; qualify labels such as granary; conclude that no palace or temple is securely identified."),
    ],
    live_sources=["https://whc.unesco.org/en/list/1645/"],
    current_note=("UNESCO's official Dholavira property page was fetched on 2026-09-01. It corroborates planned urban areas, fortifications, reservoirs and drainage. The package imports no changing count, excavation claim or unsupported measurement from the page."),
)


TOPIC_02 = common.topic(
    2,
    "Mauryan, Buddhist, Jain and Rock-Cut Heritage",
    "02_Mauryan-Buddhist-Jain-and-Rock-Cut-Heritage",
    "02_Mauryan-Buddhist-Jain-and-Rock-Cut-Heritage_Complete-Topic-Package.md",
    [
        ("Court and non-courtly art", "Mauryan pillars and palaces fit court patronage, while yaksha, terracotta and donor production are often grouped as popular; royal Ajivika caves show the binary's limits."),
        ("Ashokan pillar format", "Many pillars use a monolithic Chunar-sandstone shaft, polished surface and lotus- or bell-shaped capital as a repeatable imperial communication form."),
        ("Sarnath lion capital", "The four lions on an animal-and-wheel abacus became India's National Emblem on 26 January 1950; it must be distinguished from single-animal capitals."),
        ("Barabar and Nagarjuni", "These third-century BCE Bihar caves are the oldest known Indian rock-cut architecture and were dedicated by Ashoka and Dasharatha to the Ajivikas."),
        ("Stupa origin and function", "A stupa is a votive or commemorative relic repository with pre-Buddhist antecedents, so it is not an exclusively Buddhist architectural idea."),
        ("Stupa anatomy", "Anda, medhi, vedika, pradakshina patha, harmika, chhatra and torana organise relic, boundary, movement, honour and entry."),
        ("Sanchi's layered patronage", "Sanchi Stupa 1 grew from an Ashokan brick core through Sunga enlargement and stone facing, Satavahana-period gateways and Gupta additions."),
        ("Chaitya and vihara", "A chaitya is a prayer or assembly hall commonly terminating in a stupa; a vihara is monastic residence, and the two terms are not interchangeable."),
        ("Ajanta location and phases", "Ajanta lies in the Waghora gorge in Maharashtra and combines an earlier Satavahana-linked phase with a later Vakataka-era florescence."),
        ("Ellora's plural complex", "Ellora's thirty-four caves comprise Buddhist, Brahmanical and Jain groups with overlapping phases rather than a perfectly clean sequence."),
        ("Kailasha monolith", "Ellora Cave 16 is the monolithic Kailasha temple associated with Rashtrakuta Krishna I, showing temple plan, sculpture and excavation as one operation."),
        ("Udayagiri-Khandagiri", "The Odisha twin hills preserve a predominantly Jain cave landscape linked to Kharavela and later patronage."),
        ("Hathigumpha source criticism", "Kharavela's Prakrit Brahmi inscription is a major narrative source but a commemorative royal text whose selections and omissions require criticism."),
        ("Elephanta attribution caution", "Elephanta is a Shaiva-dominant island cave complex with Buddhist remains; precise dynastic attribution remains debated."),
        ("Amaravati Mahachaitya", "Amaravati links a relic monument, Satavahana-period enlargement, limestone sculpture, inscriptions, ayaka pillars and colonial dispersal history."),
        ("Jain architectural scales", "Jain heritage ranges from Udayagiri-Khandagiri and Ellora caves to marble or stone temples, monolithic ritual images and hill pilgrimage landscapes."),
        ("Aniconic to iconic transition", "Early Buddhist art represented the Buddha through symbols, while later figural images changed shrine programmes; architecture records but does not alone explain the shift."),
        ("Inscriptions as selective evidence", "Donor and royal inscriptions can identify patrons and acts, yet eulogy and silence prevent treating them as neutral chronicles."),
        ("Verified 2020 Mains route", "The routed 2020 GS-I demand treats rock-cut architecture as evidence for early Indian art and history and is answerable from the Core owner."),
        ("Official Sanchi linkage", "UNESCO's official Sanchi page describes the site's long accretion, aniconic art, stupa anatomy and continuing sacred significance."),
    ],
    [
        "Do not treat court and popular art as a watertight patronage division.",
        "Do not call every Ashokan capital a four-lion capital.",
        "Do not say Barabar was dedicated to Buddhists or by Chandragupta.",
        "Do not reverse chaitya and vihara.",
        "Do not describe stupas as exclusively Buddhist in origin.",
        "Do not assign Sanchi's gateways to one named Satavahana king.",
        "Do not make Ajanta's cave count the analytical point.",
        "Do not present Ellora's phases as perfectly non-overlapping.",
        "Do not call Ellora a Buddhist-only site.",
        "Do not treat Hathigumpha as a neutral chronicle.",
        "Do not give Elephanta one settled sole dynastic patron.",
        "Do not use Bharhut as an anthropomorphic-Buddha example.",
        "Do not invent dates, patrons or dimensions for Jain temples lacking them.",
        "Do not solve objective PYQs whose official key is unavailable or provisional.",
    ],
    [
        (10, "Discuss rock-cut architecture as a source for early Indian art and history.", "Rock-cut sites preserve patronage, liturgical plan, technique, inscriptions and sectarian change, but privilege durable elite endowment and require source criticism.", [3, 7, 9, 12, 17, 18]),
        (10, "Distinguish a chaitya from a vihara and explain why the distinction matters.", "Function drives form: congregational worship and stupa focus differ from monastic residence, allowing plans to reconstruct religious practice cautiously.", [7]),
        (15, "Trace the evolution of the Buddhist stupa through Sanchi.", "The relic mound remained the core while railings, paths, gateways, sculpture and shrines accumulated through successive patronage layers.", [4, 5, 6, 19]),
        (15, "How should inscriptions be used to interpret early monuments?", "Inscriptions can name patrons, grants and claims, but must be read for genre, eulogy and silence, as Hathigumpha demonstrates.", [12, 17]),
        (20, "Examine religious plurality and sacred-site continuity in Indian rock-cut heritage.", "Barabar's Ajivika dedication, Ellora's overlapping Buddhist-Hindu-Jain phases and Elephanta's palimpsest show recurring sacred geographies, not one planned pluralist project.", [3, 9, 13, 15]),
        (20, "Compare Buddhist and Jain architectural programmes from caves to structural monuments.", "Both used regional building idioms, but programme and ritual differentiated chaitya-vihara-stupa complexes from Jain cave, temple, colossus and pilgrimage-hill forms.", [4, 7, 14, 15, 16]),
    ],
    [
        plan("Court art and category limits", [0], "Royal Ajivika caves break a simple court-versus-popular equation.", "Begin with a qualified classification."),
        plan("Ashokan pillars as communication", [1, 2], "Capital forms vary by site.", "Connect material standardisation to imperial messaging."),
        plan("Barabar, Nagarjuni and the Ajivikas", [3], "Do not relabel Ajivika dedications as Buddhist.", "Use the oldest rock-cut case precisely."),
        plan("Stupa origin and anatomy", [4, 5], "Function and parts must be connected.", "Build the objective and Mains vocabulary."),
        plan("Sanchi as a layered monument", [6, 19], "Separate each dynasty's contribution.", "Turn one stupa into a chronology of patronage."),
        plan("Chaitya and vihara", [7], "Worship and residence are distinct functions.", "Read plan as evidence of practice."),
        plan("Ajanta's landscape and phases", [8], "Keep the Waghora identifier and avoid fixed cave counts.", "Answer site-identification and patronage questions."),
        plan("Ellora and the Kailasha monolith", [9, 10], "Plurality does not mean one simultaneous tolerance scheme.", "Explain overlap, technique and patronage."),
        plan("Udayagiri-Khandagiri", [11, 12], "A royal inscription is selective.", "Combine Jain patronage with source criticism."),
        plan("Elephanta as a palimpsest", [13], "Precise dynastic attribution remains debated.", "Use affiliation without false certainty."),
        plan("Amaravati's complete dossier", [14], "Retain hedges around scale and early phases.", "Connect monument, sculpture, epigraphy and dispersal."),
        plan("Jain architecture beyond caves", [15], "Programme is distinctive; formal vocabulary is often regional.", "Prepare a broad Jain-heritage answer."),
        plan("Aniconic and iconic programmes", [16], "Do not make architecture the sole cause of religious change.", "Link image history to shrine form."),
        plan("Inscriptions and evidence limits", [17], "Record both testimony and omission.", "Create the critical-method paragraph."),
        plan("Verified PYQ answer spine", [18, 0], "The question asks what architecture evidences, not a site tour.", "Assemble the 2020 demand response."),
    ],
    [
        panel("Mauryan art classification", "comparison", ["COURT -> pillars and palace architecture", "NON-COURTLY -> yaksha, terracotta and donors", "CROSSOVER -> royal Ajivika cave dedications", "VERDICT -> useful categories, porous boundary"], ["Court art and category limits"]),
        panel("Ashokan pillar system", "process-flow", ["CHUNAR SANDSTONE -> monolithic shaft", "POLISH -> imperial finish", "CAPITAL -> lion, bull or other animal forms", "INSCRIPTION -> message varies by site"], ["Ashokan pillars as communication"]),
        panel("Barabar evidence card", "evidence-table", ["PLACE -> Jehanabad district, Bihar", "DATE -> third century BCE", "PATRONS -> Ashoka and Dasharatha", "SECT -> Ajivikas, not Buddhists"], ["Barabar, Nagarjuni and the Ajivikas"]),
        panel("Stupa anatomy", "labelled-system", ["ANDA -> relic mound", "VEDIKA + PATH -> boundary and movement", "HARMIKA + CHATTRA -> summit and honour", "TORANA -> narrative gateway"], ["Stupa origin and anatomy"]),
        panel("Sanchi accretion", "timeline", ["MAURYAN -> brick core and pillar", "SUNGA -> enlargement and stone facing", "SATAVAHANA PERIOD -> carved toranas", "GUPTA -> shrines and later additions"], ["Sanchi as a layered monument"]),
        panel("Chaitya versus vihara", "comparison-table", ["CHAITYA -> prayer and assembly", "CHAITYA PLAN -> apse, columns and stupa", "VIHARA -> monastic residence", "RULE -> function explains form"], ["Chaitya and vihara"]),
        panel("Ajanta identifier", "spatial-map", ["WAGHORA RIVER -> horseshoe gorge", "SAHYADRI -> rock-cut setting", "EARLY PHASE -> Satavahana-linked", "LATER PHASE -> Vakataka florescence"], ["Ajanta's landscape and phases"]),
        panel("Ellora shared hillside", "comparison-table", ["BUDDHIST -> monasteries and worship halls", "BRAHMANICAL -> Kailasha among major works", "JAIN -> Digambara cave group", "CHRONOLOGY -> broad sequence with overlap"], ["Ellora and the Kailasha monolith"]),
        panel("Inscription evidence test", "decision-tree", ["TEXT -> names patron or claim", "CONTEXT -> monument and language", "GENRE -> grant, edict or eulogy", "SILENCE -> omission limits neutrality"], ["Udayagiri-Khandagiri", "Inscriptions and evidence limits"]),
        panel("Jain architecture scales", "hierarchy", ["CAVE -> Udayagiri-Khandagiri and Ellora", "TEMPLE -> Dilwara, Ranakpur and Khajuraho", "COLOSSUS -> Shravanabelagola ritual focus", "LANDSCAPE -> Palitana and Shikharji"], ["Jain architecture beyond caves"]),
        panel("Image-programme transition", "path-consequence", ["EARLY -> Buddha represented by symbols", "STUPA -> narrative and aniconic programme", "LATER -> anthropomorphic Buddha images", "SHRINE -> figural image joins sacred focus"], ["Aniconic and iconic programmes"]),
        panel("Rock-cut answer spine", "answer-spine", ["DEFINE -> excavated, durable architecture", "EVIDENCE -> plan, patron, inscription and style", "COMPARE -> Barabar, Ajanta and Ellora", "QUALIFY -> durable patronage is not all social life"], ["Verified PYQ answer spine"]),
    ],
    ["Court Art", "Ashokan pillars", "Sarnath", "Barabar", "Ajivika", "stupa", "anda", "harmika", "torana", "chaitya", "vihara", "Sanchi", "Ajanta", "Waghora", "Ellora", "Kailasha", "Hathigumpha", "Amaravati"],
    "The direct owned Mains route is the 2020 GS-I demand on rock-cut architecture as a source for early Indian art and history. Repository routing preserves a neutral rendering rather than claiming locally unavailable verbatim punctuation. Unkeyed or provisionally keyed Prelims routes are not solved.",
    [
        ("2020", "GS-I", "Rock-cut architecture as a source for early Indian art and history", "Verified neutral routed demand; not claimed as verbatim.", "Define rock-cut evidence, then use Barabar for Ajivika royal patronage, chaitya-vihara plans for practice, Sanchi or Ellora for accretion, and Hathigumpha for inscriptional limits; conclude that stone over-represents durable endowment."),
    ],
    live_sources=["https://whc.unesco.org/en/list/524/"],
    current_note=("UNESCO's official Buddhist Monuments at Sanchi property page was fetched on 2026-09-01. It directly corroborates the long Mauryan-to-Gupta accretion, aniconic art and stupa anatomy. No changing site count or conservation claim is added."),
)


TOPIC_03 = common.topic(
    3,
    "Temple Architecture and Chandella Khajuraho",
    "03_Temple-Architecture-and-Chandella-Khajuraho",
    "03_Temple-Architecture-and-Chandella-Khajuraho_Complete-Topic-Package.md",
    [
        ("Temple spatial lexicon", "Garbhagriha, mandapa, antarala, ardhamandapa, pradakshina patha, vahana and platform describe a ritual sequence rather than decorative labels."),
        ("Gupta developmental stages", "Early structural temples moved from flat-roofed square shrines through raised and circumambulatory plans toward shikhara, panchayatana and varied ground plans."),
        ("Nagara and Dravida", "Nagara commonly emphasises a curvilinear sanctum shikhara; Dravida organises a walled axial complex with a tiered vimana and increasingly prominent gopuram."),
        ("Vesara caution", "Vesara is best used after describing Deccan plan, tower and material; it is not a mechanically equal mixture of Nagara and Dravida."),
        ("Chandella political setting", "Jejabhukti's Chandellas used temple patronage during political self-assertion, with Dhanga's maharajadhiraja title providing the key sovereignty context."),
        ("Khajuraho axial chain", "A high jagati supports ardhamandapa, mandapa, antarala and garbhagriha beneath a clustered shikhara of urushringas."),
        ("Khajuraho material and enclosure", "Most temples use fine-grained sandstone on open terraces without an enclosure wall, while granite exceptions prevent a uniform-material claim."),
        ("Plural sacred programme", "Shaiva, Vaishnava, Surya, Ganesha and Jain dedications share the Khajuraho landscape and regional architectural idiom."),
        ("Vigour and breadth of life", "Dynamic figures and deep carving create vigour, while deities, worshippers, teachers, dancers, musicians, courtly scenes, vyalas and maithuna create breadth."),
        ("Kandariya Mahadeva", "The largest and loftiest Khajuraho temple is the culminating case for mature Nagara massing and integrated sculpture."),
        ("Chausath Yogini distinction", "Khajuraho's early open-air granite Chausath Yogini enclosure must not be confused with the circular Kachchhapaghata-period Mitaoli temple near Morena."),
        ("Pallava transition", "Pallava patronage moved from rock-cut mandapas to monolithic rathas and structural temples, with Mahabalipuram and Kanchipuram linking architecture, painting and letters."),
        ("Chola achievement", "Chola legacy combines monumental granite temples, bronze icons, murals, inscriptions and living ritual, with Brihadishvara as the architectural climax."),
        ("Chalukya and Hoysala experiment", "Aihole-Badami-Pattadakal and Hoysala stellate soapstone temples demonstrate Deccan selection from northern and southern grammars."),
        ("Vijayanagara temple-secular split", "Hampi's temples extend Dravida gopuram and mandapa forms, while Islamicate arches and domes are strongest in the royal and secular zone."),
        ("Nayaka expansion", "Nayaka building enlarged older complexes through graded gopurams, prakarams, temple tanks, stucco superstructures and processional halls."),
        ("Pala-Sena eastern school", "Bengal's brick and terracotta architecture joined Buddhist and Hindu patronage and translated the bamboo-hut roof into the Bangla roof later used by Mughals."),
        ("Verified temple PYQ cluster", "The Core owner supports direct 2024 Pallava and Chola demands, the 2025 Chandella demand and the routed 2022 temple-sculpture social-life demand."),
        ("Official Khajuraho linkage", "UNESCO's official property page describes axial Nagara spaces, clustered spires and sacred-secular sculptural themes under ASI management."),
        ("Temple answer spine", "A strong answer names school, morphology, patron, monument, sculptural programme, comparison, evidence limit and heritage status in that order."),
    ],
    [
        "Do not confuse a Nagara shikhara with a Dravida gopuram.",
        "Do not define Vesara only as a half-Nagara half-Dravida mixture.",
        "Do not reduce Khajuraho to erotic sculpture.",
        "Do not give an unsupported percentage for maithuna imagery.",
        "Do not say every Khajuraho temple has identical material or orientation.",
        "Do not merge Khajuraho and Mitaoli Chausath Yogini temples.",
        "Do not assign every Khajuraho temple to a named Chandella ruler.",
        "Do not confuse Virupaksha at Pattadakal with Virupaksha at Hampi.",
        "Do not call the Vitthala stone chariot monolithic.",
        "Do not describe Mahanavami Dibba as a temple.",
        "Do not attribute Islamicate form chiefly to Hampi's sanctum temples.",
        "Do not call the three Great Living Chola Temples three separate properties.",
        "Do not use traveller praise as a measured architectural fact.",
        "Do not solve provisional 2026 objective keys.",
    ],
    [
        (10, "Elucidate the resilient vigour and breadth of life in Chandella art.", "Khajuraho's vigour comes from dynamic carving integrated with sandstone walls; breadth comes from its sacred, social, animal, performance and intimate registers, of which maithuna is only one.", [5, 6, 7, 8, 9]),
        (10, "Estimate the Pallava contribution to South Indian art and architecture.", "The Pallava achievement was a transition from excavated mandapas to monolithic experiments and structural temples, joined to mural and Sanskrit-Tamil literary patronage.", [11]),
        (15, "Why are the Cholas remembered for art and architecture?", "Monumental granite building, portable bronzes, murals, inscriptions, administration and continuing worship survive together, giving Chola patronage both scale and living afterlife.", [12]),
        (15, "Temple sculpture is selected evidence of medieval social life. Explain.", "Performance, learning, courtly activity, ritual and labour appear in commissioned programmes, but representation records what patrons made visible rather than society statistically.", [8, 17]),
        (20, "Trace the development of South Indian temple architecture from Pallava to Nayaka.", "The organising movement is rock-cut to structural temple, imperial vimana, Deccan experiment, gateway-dominated Vijayanagara complex and Nayaka enclosure expansion.", [11, 12, 13, 14, 15]),
        (20, "Compare major regional schools of Indian temple architecture.", "Nagara, Dravida, Deccan and eastern schools differ through tower, enclosure, plan, material and patronage; named monuments reveal a family of regional solutions, not rigid boxes.", [2, 3, 5, 13, 16, 19]),
    ],
    [
        plan("Temple space and ritual movement", [0], "Vocabulary must describe a sequence of access.", "Build the common lexicon."),
        plan("From Gupta shrine to regional schools", [1, 2], "Development was not one straight national line.", "Explain the structural branching."),
        plan("How to use Vesara", [3], "Describe form before applying the label.", "Avoid the mechanical-hybrid trap."),
        plan("Chandella sovereignty and patronage", [4], "Political context explains confidence, not a one-to-one victory monument.", "Link power to temple building."),
        plan("Khajuraho plan and massing", [5], "Keep shikhara, urushringa and axial spaces distinct.", "Describe mature Nagara morphology."),
        plan("Material, terrace and enclosure", [6], "Sandstone dominates but granite exceptions matter.", "Tie material to carving and viewing."),
        plan("Plural patronage at Khajuraho", [7], "Shared idiom does not erase sectarian programmes.", "Use dedication breadth analytically."),
        plan("Vigour and breadth", [8, 9], "Maithuna is one register, not the definition.", "Answer the 2025 demand."),
        plan("Chausath Yogini identification", [10], "Khajuraho and Mitaoli are different monuments.", "Defeat a high-risk objective trap."),
        plan("Pallava transition", [11], "Estimate a trajectory, not a monument list.", "Prepare the 2024 ten-marker."),
        plan("Chola living achievement", [12], "Balance monumentality with administration and living use.", "Prepare the 2024 fifteen-marker."),
        plan("Deccan experiment", [13], "Pattadakal and Hoysala evidence must precede Vesara.", "Compare plan, tower and material."),
        plan("Vijayanagara and Nayaka", [14, 15], "Keep temple and royal-secular zones distinct.", "Trace the late Dravida trajectory."),
        plan("Eastern material logic", [16], "Do not invent unsupported Kerala or Ahom vocabularies.", "Add the Pala-Sena regional case."),
        plan("PYQ cluster and final answer spine", [17, 18, 19], "Use official status as a close, not a substitute for analysis.", "Integrate all direct demand families."),
    ],
    [
        panel("Temple ritual sequence", "process-flow", ["JAGATI -> elevated sacred platform", "MANDAPA -> congregational approach", "ANTARALA -> transition to sanctum", "GARBHAGRIHA -> deity and ritual focus"], ["Temple space and ritual movement"]),
        panel("Regional morphology", "comparison-table", ["NAGARA -> curvilinear shikhara", "DRAVIDA -> tiered vimana and enclosure", "DECCAN -> selective northern-southern grammar", "EASTERN -> brick, terracotta and Bangla roof"], ["From Gupta shrine to regional schools"]),
        panel("Khajuraho power-to-form", "causal-system", ["CHANELLA ASSERTION -> visible patronage need", "DHANGA -> maharajadhiraja context", "TEMPLE CLUSTER -> sovereignty in stone", "LIMIT -> no invented victory dedication"], ["Chandella sovereignty and patronage"]),
        panel("Khajuraho axial chain", "labelled-system", ["ARDHAMANDAPA -> entrance porch", "MANDAPA -> hall", "ANTARALA -> vestibule", "GARBHAGRIHA + SHIKHARA -> sacred climax"], ["Khajuraho plan and massing"]),
        panel("Mountain silhouette", "hierarchy", ["MAIN SHIKHARA -> central vertical mass", "URUSHRINGAS -> clustered replica spires", "JAGATI -> raised horizontal base", "RESULT -> mountain-range composition"], ["Khajuraho plan and massing"]),
        panel("Breadth-of-life ledger", "comparison-table", ["SACRED -> deities and worshippers", "SOCIAL -> teachers, dancers and musicians", "IMAGINATIVE -> vyalas and narrative forms", "INTIMATE -> maithuna as one register"], ["Vigour and breadth"]),
        panel("Chausath Yogini distinction", "comparison", ["KHAJURAHO -> Chandella landscape", "KHAJURAHO FORM -> open-air granite enclosure", "MITAOLI -> near Morena, Kachchhapaghata", "MITAOLI FORM -> circular; popular Parliament link"], ["Chausath Yogini identification"]),
        panel("Pallava transition", "timeline", ["MAHENDRAVARMAN -> rock-cut mandapas", "MAMALLA -> monolithic Pancha Rathas", "RAJASIMHA -> structural Shore Temple", "LEGACY -> Chola structural expansion"], ["Pallava transition"]),
        panel("Chola achievement system", "causal-system", ["GRANITE TEMPLE -> monumental state form", "BRONZE + MURAL -> portable and painted art", "INSCRIPTION -> administration and patronage", "LIVING WORSHIP -> continuing cultural memory"], ["Chola living achievement"]),
        panel("Deccan experiment", "comparison-table", ["PATTADAKAL VIRUPAKSHA -> Dravida tower", "PATTADAKAL PAPANATHA -> Nagara tower", "HOYSALA -> stellate soapstone density", "VERDICT -> describe evidence before Vesara"], ["Deccan experiment"]),
        panel("Late Dravida shift", "path-consequence", ["CHOLA -> vimana-dominant imperial complex", "VIJAYANAGARA -> raya gopuram and mandapas", "NAYAKA -> graded gateways and prakarams", "FUNCTION -> procession, gathering and ritual expansion"], ["Vijayanagara and Nayaka"]),
        panel("Temple answer spine", "answer-spine", ["NAME -> school, dynasty and monument", "DESCRIBE -> plan, tower, material and enclosure", "ANALYSE -> patronage, sculpture and society", "QUALIFY -> comparison, source limit and status"], ["PYQ cluster and final answer spine"]),
    ],
    ["garbhagriha", "mandapa", "antarala", "shikhara", "vimana", "gopuram", "Nagara", "Dravida", "Vesara", "jagati", "urushringa", "Jejabhukti", "Dhanga", "Kandariya Mahadeva", "Chausath Yogini", "Pallava", "Chola", "Pattadakal", "Hoysala", "Vijayanagara", "Nayaka", "Pala-Sena"],
    "Verified owned Mains routes are the 2024 Pallava and Chola demands, the 2025 Chandella demand, and the routed 2022 demand on medieval temple sculpture as social evidence. The 2026 objective route remains provisionally keyed and is not solved.",
    [
        ("2025", "GS-I", "'The sculptors filled the Chandella artform with resilient vigor and breadth of life.' Elucidate. (Answer in 150 words)", "Verified verbatim in the Basic owner.", "Separate vigour as carving method from breadth as subject range; cite sandstone, dynamic figures, sacred and secular registers, vyalas and maithuna as one element; close with Kandariya Mahadeva."),
        ("2024", "GS-I", "Estimate the contribution of Pallavas of Kanchi for the development of art and literature of South India. (Answer in 150 words)", "Verified verbatim in the Basic owner.", "Estimate the rock-cut to monolithic to structural sequence through Mandagapattu, Pancha Rathas and Shore Temple, then add Kanchipuram, murals, inscriptions and Dandin with a survival limitation."),
        ("2024", "GS-I", "Though the great Cholas are no more yet their name is still remembered with great pride because of their highest achievements in the domain of art and architecture. Comment. (Answer in 250 words)", "Verified verbatim in the Basic owner.", "Use Brihadishvara for granite scale, Nataraja for bronze, murals and inscriptions for cultural-administrative depth, and the living UNESCO serial property for afterlife; qualify labour and incomplete survivals."),
        ("2022", "GS-I", "Medieval Indian temple sculptures represent the social life of those days. How will you explain this statement?", "Verified routed wording in the Core owner.", "Use dancers and musicians, teachers and disciples, courtly scenes, patron women and named artisans as selected evidence; state that commissioned images are representations, not a statistical photograph of society."),
    ],
    live_sources=["https://whc.unesco.org/en/list/240/"],
    current_note=("UNESCO's official Khajuraho Group of Monuments page was fetched on 2026-09-01. It corroborates the axial Nagara plan, clustered spires, integrated sacred-secular sculpture and ASI management. No unsupported visitor or conservation figure is added."),
)


TOPIC_04 = common.topic(
    4,
    "Indo-Islamic and Regional Architecture",
    "04_Indo-Islamic-and-Regional-Architecture",
    "04_Indo-Islamic-and-Regional-Architecture_Complete-Topic-Package.md",
    [
        ("Trabeate and arcuate", "Post-and-lintel trabeate construction continued while scientifically executed arches, vaults and domes expanded under Sultanate builders."),
        ("Lime mortar and wide spans", "Stronger lime mortar and arcuate geometry made wider openings and high domes structurally routine without eliminating slab-and-beam work."),
        ("Hybrid construction industry", "Imported structural knowledge, indigenous craft labour, local material and reused motifs created hybridity in building practice rather than two sealed religious styles."),
        ("Ornamental vocabulary", "Jaali, arabesque, calligraphy, charbagh and pietra dura name distinct devices and must not be collapsed into 'intricate decoration'."),
        ("Imperial and provincial Sultanate", "Delhi's dynastic imperial styles coexisted with Bengal, Jaunpur, Malwa and Bijapur schools shaped by local rulers, material and climate."),
        ("Qutb Minar accretion", "Aibak began the Qutb Minar, Iltutmish substantially completed it and Firoz Shah Tughlaq repaired or rebuilt damaged upper work."),
        ("Quwwat-ul-Islam spolia", "Its inscription records material from twenty-seven demolished Hindu and Jaina temples, a specific reuse case that must not be universalised."),
        ("Double-dome development", "An early mature Indian double-dome line runs through Sikandar Lodi's tomb to Humayun's Tomb, separating external profile from internal ceiling."),
        ("Bengal and Jaunpur", "Bengal translated the sloping Bangla roof into masonry, while Jaunpur used monumental screen facades and omitted minars."),
        ("Malwa and Bijapur", "Malwa used ventilation, windows and baulis; Bijapur developed a three-arched facade and near-spherical bulbous dome."),
        ("Akbar's sandstone phase", "Akbar's architecture foregrounded red sandstone, four-centred arches, Agra Fort and Fatehpur Sikri as imperial experiments."),
        ("Ibadat Khana boundary", "Fatehpur Sikri's Ibadat Khana was the setting for interfaith debate, but the doctrinal ownership of Sulh-i-Kul and Din-i-Ilahi lies elsewhere."),
        ("Marble and pietra dura", "Itmad-ud-Daulah's tomb marks the all-white-marble and fine-inlay transition associated with Jahangir and Nur Jahan before Shah Jahan's culmination."),
        ("Taj workshop authorship", "Named specialists matter, but the Taj is safest treated as a collective workshop achievement rather than one uncontested mastermind's creation."),
        ("Aurangzeb and continuity", "Fewer imperial commissions under Aurangzeb did not extinguish Mughal form, which continued through regional eighteenth-century patronage."),
        ("Rajput, Sikh and Awadh", "Jharokha, chhatri and onion-dome combinations, and Awadh's mortar-built imambaras show regional adaptation rather than derivative decline."),
        ("Material as chronology", "Red sandstone, white marble, local brick or basalt and mortar can help distinguish periods and regions when used with patronage evidence."),
        ("Two Indo-Saracenic usages", "Medieval Indo-Islamic synthesis and the later colonial Indo-Saracenic revival share vocabulary but are historically distinct phenomena."),
        ("PYQ ownership correction", "The routed Kalyana Mandapa objective demand belongs to Vijayanagara temple architecture, not Indo-Islamic architecture; this owner records the correction."),
        ("Official Maratha-forts linkage", "UNESCO's 2025 Maratha Military Landscapes inscription provides a current comparative case of regional fortification adapted to mountain and coast."),
    ],
    [
        "Do not say arches and domes were wholly unknown before the Sultanate.",
        "Do not describe trabeate practice as disappearing after 1206.",
        "Do not essentialise fixed Hindu and Muslim architectural styles.",
        "Do not generalise the Quwwat-ul-Islam reuse record to every monument.",
        "Do not credit the whole Qutb Minar to one ruler.",
        "Do not make minars universal to provincial schools.",
        "Do not describe Din-i-Ilahi as a mass religion.",
        "Do not credit Agra Fort's surviving interiors wholly to Akbar.",
        "Do not call Ustad Ahmad Lahori the uncontested sole Taj architect.",
        "Do not explain Aurangzeb-era patronage through personality alone.",
        "Do not dismiss Bibi Ka Maqbara with an aesthetic insult.",
        "Do not merge medieval and colonial Indo-Saracenic usage.",
        "Do not answer the Kalyana Mandapa demand from mosque vocabulary.",
        "Do not invent construction costs, workforce totals or exact dimensions.",
    ],
    [
        (10, "What technological change did Sultanate architecture normalise?", "The decisive change was large-scale scientific arcuate construction using arches, domes and lime mortar, while trabeate practice persisted inside the same industry.", [0, 1, 2]),
        (10, "Why is the Quwwat-ul-Islam mosque a high-value but limited reuse case?", "Its inscription supplies specific evidence of spolia from twenty-seven temples, but one documented site cannot establish a universal practice.", [6]),
        (15, "Indo-Islamic architecture was a synthesis of practice, not merely appearance. Discuss.", "Shared workshops combined arcuate knowledge, local trabeate skill, regional materials and selected motifs, producing structural and climatic hybrids.", [0, 1, 2, 3, 16]),
        (15, "Compare provincial Sultanate schools as environmental adaptations.", "Bengal, Jaunpur, Malwa and Bijapur solved roof, facade, ventilation, water and dome problems differently, disproving a single imported template.", [4, 8, 9]),
        (20, "Trace Mughal architecture through material, patronage and workshop practice.", "Akbar's sandstone mass, the Nur Jahan-era marble transition, Shah Jahan's inlay culmination and later regional continuity create a material-patronage chronology qualified by collective authorship.", [10, 11, 12, 13, 14, 16]),
        (20, "Explain the regionalisation of Indo-Islamic architectural vocabulary.", "Imperial arcuate forms moved through provincial, Rajput, Sikh, Awadh and Maratha settings where climate, material, ritual and military terrain transformed their use.", [4, 8, 9, 15, 19]),
    ],
    [
        plan("Trabeate and arcuate systems", [0, 1], "The change was scale and technique, not first knowledge.", "Build the structural foundation."),
        plan("One hybrid building industry", [2], "Name labour, material and technique rather than vague fusion.", "Frame synthesis as a mechanism."),
        plan("The ornamental grammar", [3], "Keep each device precise.", "Strengthen identification answers."),
        plan("Imperial and provincial classification", [4], "Provincial does not mean inferior.", "Organise the Sultanate period."),
        plan("Qutb complex as accretion and reuse", [5, 6], "Layered construction and specific spolia are separate claims.", "Use one monument critically."),
        plan("Why the double dome matters", [7], "Do not name a single inventor.", "Explain a structural proportion solution."),
        plan("Bengal and Jaunpur", [8], "Climate and political identity operate together.", "Compare roof and facade."),
        plan("Malwa and Bijapur", [9], "Name water, ventilation and dome form.", "Add regional environmental evidence."),
        plan("Akbar's architectural phase", [10, 11], "The architectural setting does not own the whole doctrine.", "Connect form and imperial experiment."),
        plan("Marble transition", [12], "A material marker is not an exclusive-material rule.", "Date the Mughal sequence."),
        plan("Taj authorship and workshops", [13], "Reject the single-genius shortcut.", "Discuss production and collaboration."),
        plan("Aurangzeb and survival", [14], "Reduced imperial building is not stylistic extinction.", "Qualify decline narratives."),
        plan("Rajput, Sikh and Awadh adaptations", [15, 16], "Regional forms retain their own purposes.", "Extend beyond the Mughal court."),
        plan("Terminology and routed-PYQ correction", [17, 18], "Kalyana Mandapa belongs to Vijayanagara.", "Prevent two high-risk category errors."),
        plan("Maratha comparison and answer spine", [19, 2], "The 2025 inscription is comparative, not a Mughal property.", "Close with a current regional-fortification link."),
    ],
    [
        panel("Structural transition", "comparison", ["TRABEATE -> post and lintel", "ARCUATE -> arch, vault and dome", "LIME MORTAR -> stronger wide-span work", "OUTCOME -> coexistence, not replacement"], ["Trabeate and arcuate systems"]),
        panel("Synthesis mechanism", "causal-system", ["ARCUATE KNOWLEDGE -> new structural range", "LOCAL CRAFT -> trabeate skill and motifs", "REGIONAL MATERIAL -> stone, brick and mortar", "BUILDING INDUSTRY -> hybrid results"], ["One hybrid building industry"]),
        panel("Ornament identification", "comparison-table", ["JAALI -> perforated light screen", "ARABESQUE -> geometric-vegetal continuity", "CHARBAGH -> four-part garden", "PIETRA DURA -> fitted stone inlay"], ["The ornamental grammar"]),
        panel("Sultanate classification", "hierarchy", ["IMPERIAL -> Slave, Khilji, Tughlaq, Lodi", "BENGAL -> Bangla roof", "JAUNPUR/MALWA -> no universal minar", "BIJAPUR -> bulbous dome experiment"], ["Imperial and provincial classification"]),
        panel("Qutb layered monument", "timeline", ["AIBAK -> begins tower", "ILTUTMISH -> substantial completion", "FIROZ SHAH -> upper repair or rebuilding", "LESSON -> one monument, several reigns"], ["Qutb complex as accretion and reuse"]),
        panel("Spolia evidence boundary", "decision-tree", ["INSCRIPTION -> records reused material", "COUNT -> twenty-seven temples at this site", "CLAIM -> specific documented reuse", "PROHIBITION -> no period-wide generalisation"], ["Qutb complex as accretion and reuse"]),
        panel("Provincial climate map", "comparison-table", ["BENGAL -> rain-responsive sloping roof", "MALWA -> windows, pavilions and baulis", "JAUNPUR -> screen facade without minars", "BIJAPUR -> Deccani dome geometry"], ["Bengal and Jaunpur", "Malwa and Bijapur"]),
        panel("Mughal material chronology", "timeline", ["AKBAR -> red sandstone mass", "NUR JAHAN/JAHANGIR -> white marble turn", "SHAH JAHAN -> marble and inlay culmination", "LATER -> regional continuation"], ["Akbar's architectural phase", "Marble transition"]),
        panel("Fatehpur Sikri boundary", "evidence-table", ["PLACE -> imperial capital and complex", "IBADAT KHANA -> debate setting", "ARCHITECTURE -> owns spatial evidence", "DOCTRINE -> primary ownership elsewhere"], ["Akbar's architectural phase"]),
        panel("Workshop authorship", "hierarchy", ["PATRON -> Shah Jahan", "SPECIALISTS -> designers and craftsmen", "WORKSHOP -> collective execution", "VERDICT -> no uncontested sole mastermind"], ["Taj authorship and workshops"]),
        panel("Regional continuation", "comparison-table", ["RAJPUT -> jharokha and court display", "SIKH -> chhatri, cornice and onion dome", "AWADH -> mortar and imambara scale", "MARATHA -> terrain-based fort network"], ["Rajput, Sikh and Awadh adaptations", "Maratha comparison and answer spine"]),
        panel("Indo-Islamic answer spine", "answer-spine", ["DEFINE -> trabeate-arcuate coexistence", "EVIDENCE -> monument, material and workshop", "COMPARE -> provincial and regional solutions", "QUALIFY -> reuse, authorship and terminology"], ["Maratha comparison and answer spine"]),
    ],
    ["trabeate", "arcuate", "lime mortar", "jaali", "arabesque", "charbagh", "pietra dura", "Qutb Minar", "Quwwat-ul-Islam", "double dome", "Bangla roof", "Fatehpur Sikri", "Ibadat Khana", "Itmad-ud-Daulah", "Ustad Ahmad Lahori", "jharokha", "Awadh", "Indo-Saracenic", "Kalyana Mandapa"],
    "No direct GS-I Mains question is owned by this topic in the audited 2024-2025 set. The 2025 Akbar-syncretism question is adjacent and owned primarily by Medieval History; the Kalyana Mandapa objective route is explicitly corrected to Temple Architecture. Existing unkeyed objective routes are preserved but not solved.",
    [],
    live_sources=["https://whc.unesco.org/en/list/1739"],
    current_note=("UNESCO's official Maratha Military Landscapes of India property page was fetched on 2026-09-01. It verifies the 2025 inscription and a twelve-fort network adapted to coastal and mountain terrain. The topic uses it only as a comparative regional-fortification case."),
)


TOPIC_05 = common.topic(
    5,
    "Colonial and Post-Independence Architecture",
    "05_Colonial-and-Post-Independence-Architecture",
    "05_Colonial-and-Post-Independence-Architecture_Complete-Topic-Package.md",
    [
        ("Portuguese Baroque and fort", "Portuguese architecture joined church-centred Gothic and Baroque forms with forts and patio houses, making religious and maritime authority visible."),
        ("French Cartesian planning", "French settlements used rational street grids and restrained facades, so urban plan rather than one monument is the key signature."),
        ("British Indo-Gothic", "Nineteenth- and early-twentieth-century Indo-Gothic combined Gothic Revival structure and detail with domes, jaali, turrets, balconies and climate adaptation."),
        ("Post-1911 Neo-Classical capital", "Lutyens and Baker's New Delhi used axial planning and monumental classical-imperial form after the capital transfer."),
        ("Architecture as colonial power", "Church, grid, railway-city monument and imperial capital were programmes for organising space and displaying authority, not merely imported styles."),
        ("Post-1947 school split", "The source divides post-Independence architecture into Revivalist and Modernist schools and criticises both for incomplete escape from colonial inheritance."),
        ("Chandigarh paradox", "Le Corbusier's Chandigarh gave a partitioned Indian state a new capital, but its foreign authorship complicates a simple indigenous-break narrative."),
        ("G.B. Deolalikar", "The Supreme Court of India, completed in 1958, supplies an early major post-Independence state commission associated with an Indian architect."),
        ("Laurie Baker", "Local materials, filler slabs, ventilation and thermal comfort made Baker's low-cost housing a change of client, climate logic and cost structure."),
        ("Charles Correa", "Correa adapted modern institutional architecture through courtyards, open-to-sky space and civic projects including the Madhya Pradesh Assembly and Gandhi memorial museum."),
        ("Achyut Kanvinde", "Kanvinde's institutional modernism used modern and Brutalist elements in projects such as IIT Kanpur and the National Science Centre."),
        ("B.V. Doshi precision", "The owner records Doshi as the first Indian Pritzker laureate in 2018 and preserves his official Padma sequence: Shri 1976, Bhushan 2020, Vibhushan 2023 posthumous."),
        ("Raj Rewal boundary", "Hall of Nations and Asian Games Village are retained as bounded widely reported works, while no Padma or other award is attributed to Raj Rewal."),
        ("New Parliament House", "Bimal Patel's new Parliament House became the main working building in 2023 while the 1927 building survives as Samvidhan Sadan."),
        ("Mitaoli attribution caution", "The resemblance or influence claim linking the 1927 Parliament building to the Mitaoli Chausath Yogini temple remains a popular, debated attribution."),
        ("Climate and material as decolonisation", "Courtyard, shade, ventilation, local material and low-cost structure can mark a deeper break than changing ornamental vocabulary alone."),
        ("Continuity across 1947", "Monumental state axes and institutional building types continued even as clients, symbols, materials and programmes changed."),
        ("Modern-heritage vulnerability", "The Hall of Nations case shows that celebrated post-Independence buildings can fall outside antiquity-based statutory protection."),
        ("Official Mumbai linkage", "UNESCO's Mumbai ensembles page explains Victorian Gothic, Indo-Deco, climate adaptation and urban-development pressure around the Oval Maidan."),
        ("Zero-direct-PYQ status", "No direct GS-I Mains question is verified as owned by colonial or post-Independence architecture in the audited current set."),
    ],
    [
        "Do not merge Portuguese, French and British colonial styles.",
        "Do not treat Indo-Gothic and Neo-Classical New Delhi as one phase.",
        "Do not confuse colonial Indo-Saracenic revival with medieval usage.",
        "Do not say post-1947 architecture made a clean break from colonial planning.",
        "Do not call Le Corbusier an Indian architect.",
        "Do not say Laurie Baker won the Pritzker Prize.",
        "Do not write Padma Vibhushan 2020 for B.V. Doshi.",
        "Do not omit Doshi's correct 2023 posthumous Padma Vibhushan.",
        "Do not attribute any award to Raj Rewal.",
        "Do not attach unsupported dimensions or structural claims to Hall of Nations.",
        "Do not attach the Mitaoli influence claim to the 2023 Parliament building.",
        "Do not present the Mitaoli influence as documented fact.",
        "Do not describe Samvidhan Sadan as demolished or abandoned.",
        "Do not invent a direct UPSC PYQ for this topic.",
    ],
    [
        (10, "How did colonial architecture make political authority visible?", "Colonial regimes used church scale, rational grids, transport-city monuments and axial capitals to organise subjects and stage institutional permanence.", [0, 1, 2, 3, 4]),
        (10, "Why is Laurie Baker a distinctive post-Independence architect?", "Baker changed the client and building economy through local material, filler slabs, ventilation and low-cost housing rather than merely replacing colonial ornament.", [8, 15]),
        (15, "Compare Portuguese, French and British colonial architectural programmes.", "Portuguese church-fort authority, French grid rationality and British Indo-Gothic then Neo-Classical monumentality were distinct spatial programmes shaped by different institutions.", [0, 1, 2, 3, 4]),
        (15, "Did Indian architecture break decisively with colonial inheritance after 1947?", "Political sovereignty changed patron and symbol, but monumental planning and institutional typologies persisted; Baker, Correa, Kanvinde and Doshi produced uneven deeper adaptations.", [5, 6, 8, 9, 10, 11, 16]),
        (20, "Assess the contribution of major architects to post-1947 Indian modernism.", "Deolalikar, Baker, Correa, Kanvinde, Doshi and Bimal Patel answered state, climate, cost, institution, housing and national-symbol problems differently; precision on authorship and awards is essential.", [7, 8, 9, 10, 11, 13]),
        (20, "Examine the conservation politics of colonial and modern architecture.", "Built heritage can embody domination, craftsmanship and later public identity simultaneously; Mumbai's living ensembles and Hall of Nations expose different legal and urban pressures.", [4, 17, 18]),
    ],
    [
        plan("Portuguese authority in church and fort", [0], "Keep Baroque, Gothic and fortification functions distinct.", "Open the colonial sequence."),
        plan("French planning as architecture", [1], "The grid is the signature, not decorative anonymity alone.", "Read urban form as power."),
        plan("British Indo-Gothic hybridity", [2], "This is colonial revival, not medieval Indo-Islamic form.", "Identify devices and climate adaptations."),
        plan("New Delhi and imperial axis", [3, 4], "Neo-Classical capital planning is a separate phase.", "Connect style to authority."),
        plan("The colonial-hangover critique", [5, 16], "Continuity does not mean identity.", "Frame the post-1947 debate."),
        plan("Chandigarh's imported modernism", [6], "Foreign authorship does not erase Indian state purpose.", "Introduce the national-modernist paradox."),
        plan("First Indian state commissions", [7], "Use only the project and date supported by the owner.", "Add authorship precision."),
        plan("Laurie Baker's client shift", [8, 15], "Cost and climate are mechanisms, not slogans.", "Explain vernacular modernism."),
        plan("Correa and Kanvinde", [9, 10], "Their institutional modernisms are related but not identical.", "Compare named projects and design problems."),
        plan("Doshi's verified record", [11], "Keep Pritzker and three Padma classes exact.", "Use official-source precision."),
        plan("Raj Rewal and modern heritage", [12, 17], "No award is verified; do not add one.", "Turn a work into a conservation-policy case."),
        plan("Parliament old and new", [13, 14], "Mitaoli concerns the 1927 building and remains debated.", "Analyse continuity and replacement."),
        plan("Architecture as decolonisation", [15, 16], "A change of client can matter more than ornament.", "Build the core evaluative argument."),
        plan("Mumbai's living ensembles", [18], "Use the official page without inventing changing boundaries.", "Link style exchange to urban pressure."),
        plan("Zero-PYQ audit and answer spine", [19, 4], "Original practice must not be labelled PYQ.", "Close the topic transparently."),
    ],
    [
        panel("Colonial sequence", "timeline", ["PORTUGUESE -> church, Baroque and fort", "FRENCH -> Cartesian settlement grid", "BRITISH -> Indo-Gothic public monument", "POST-1911 -> Neo-Classical imperial capital"], ["Portuguese authority in church and fort", "French planning as architecture"]),
        panel("Architecture as power", "causal-system", ["SPONSOR -> church, company or colonial state", "PLAN -> grid, axis and segregated precinct", "MONUMENT -> authority made visible", "PUBLIC USE -> rule enters daily urban space"], ["New Delhi and imperial axis"]),
        panel("Indo-Gothic grammar", "comparison-table", ["GOTHIC -> pointed arch and ribbed vault", "INDIAN -> dome, jaali and turret", "CLIMATE -> balcony and veranda", "RESULT -> colonial revival hybrid"], ["British Indo-Gothic hybridity"]),
        panel("New Delhi axis", "spatial-map", ["PROCESSIONAL VISTA -> imperial approach", "SECRETARIAT -> administrative command", "VICEROY'S HOUSE -> elevated authority", "CAPITAL PLAN -> permanence staged in space"], ["New Delhi and imperial axis"]),
        panel("1947 continuity test", "comparison", ["CHANGE -> sovereign Indian patron", "CONTINUITY -> monumental civic planning", "CHANGE -> national programme and symbolism", "VERDICT -> uneven architectural decolonisation"], ["The colonial-hangover critique"]),
        panel("Postwar architect map", "hierarchy", ["LE CORBUSIER -> Chandigarh state capital", "DEOLALIKAR -> Supreme Court", "CORREA/KANVINDE -> institutions", "BAKER/DOSHI -> climate, housing and social use"], ["Chandigarh's imported modernism", "First Indian state commissions"]),
        panel("Baker mechanism", "process-flow", ["LOCAL MATERIAL -> lower embodied cost", "FILLER SLAB -> less steel and cement", "VENTILATION -> thermal comfort", "CLIENT -> affordable housing user"], ["Laurie Baker's client shift"]),
        panel("Institutional modernisms", "comparison-table", ["CORREA -> courtyard and open-to-sky space", "KANVINDE -> modern and Brutalist institutions", "DOSHI -> housing and campus urbanism", "COMMON TEST -> climate, use and public purpose"], ["Correa and Kanvinde", "Doshi's verified record"]),
        panel("Award precision rail", "timeline", ["DOSHI 1976 -> Padma Shri", "DOSHI 2018 -> Pritzker laureate", "DOSHI 2020 -> Padma Bhushan", "DOSHI 2023 -> Padma Vibhushan, posthumous"], ["Doshi's verified record"]),
        panel("Parliament continuity", "comparison", ["1927 BUILDING -> colonial-era legislature", "2023 BUILDING -> Bimal Patel, main workplace", "OLD BUILDING -> retained as Samvidhan Sadan", "MITAOLI -> debated link to 1927 design"], ["Parliament old and new"]),
        panel("Heritage pressure", "comparison-table", ["MUMBAI ENSEMBLES -> living urban heritage", "URBAN GROWTH -> pressure on setting", "HALL OF NATIONS -> modern-heritage loss", "POLICY -> age and value can diverge"], ["Raj Rewal and modern heritage", "Mumbai's living ensembles"]),
        panel("Modern architecture answer spine", "answer-spine", ["SEQUENCE -> coloniser and phase", "EVIDENCE -> building, architect and device", "ANALYSE -> power, climate, client and cost", "QUALIFY -> continuity, attribution and conservation"], ["Zero-PYQ audit and answer spine"]),
    ],
    ["Baroque", "Cartesian grid", "Indo-Gothic", "Indo-Saracenic", "Neo-Classical", "Edwin Lutyens", "Herbert Baker", "Le Corbusier", "G.B. Deolalikar", "Laurie Baker", "filler slab", "Charles Correa", "Achyut Kanvinde", "B.V. Doshi", "Raj Rewal", "Bimal Patel", "Samvidhan Sadan", "Mitaoli", "Victorian Gothic", "Art Deco"],
    "No direct GS-I Mains PYQ is verified as owned by colonial or post-Independence architecture in the audited repository routes. The package therefore presents a transparent zero-direct-PYQ audit and labels all six Mains questions as original practice.",
    [],
    live_sources=["https://whc.unesco.org/en/list/1480/"],
    current_note=("UNESCO's official Victorian Gothic and Art Deco Ensembles of Mumbai page was fetched on 2026-09-01. It verifies Indo-Gothic and Indo-Deco exchange, climate adaptations and pressure from urban development. No unsupported boundary or condition claim is added."),
)
