"""Authored content data for International Relations learner-v2 Topic 02."""

from __future__ import annotations

import generate_international_relations_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_02 = common.topic(
    2,
    "India and the Neighbourhood",
    "02_India-and-the-Neighbourhood",
    "02_India-and-the-Neighbourhood_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and how its scope is bounded", "This topic owns India's engagement with Bangladesh, Bhutan, Nepal, Sri Lanka, Myanmar, Pakistan and Afghanistan, together with the Neighbourhood First policy, the Gujral Doctrine, and the development, connectivity and people-to-people instruments that carry them, and its distinctive feature is that it is simultaneously doctrinal and heavily evidence-bound: one General Studies Paper II Mains demand from 2022 is routed to it in the audited ledgers alongside four objective demands from 2020, 2023 and 2026; Maldives is deliberately cross-linked to topic 04 because its salience is primarily maritime, the SAARC and BIMSTEC institutional comparison is reserved for topic 10, and the physical border and route geography belongs to the Geography owner."),
        ("India's eight bordering neighbours and Afghanistan as a near-neighbour", "Tharoor counts Pakistan, China, Nepal, Bhutan, Bangladesh, Myanmar, Sri Lanka and Maldives as sharing a land or maritime border with India, and adds Afghanistan as a near-neighbour because Pakistan's capture in 1948 of a strip of north-western Kashmir made Afghanistan territorially adjacent, and he separately records that of the eight bordering states there has been a history of problems, of varying degrees of difficulty, with six; the examinable consequence is that neighbourhood in Indian strategic practice is defined by security relevance and not only by strict territorial contiguity, and that friction is a structural feature rather than an aberration."),
        ("Neighbourhood First as a stated priority policy", "Neighbourhood First is India's stated policy priority of engaging South Asian neighbours ahead of more distant partners through connectivity, development assistance and people-to-people ties, delivered by prime-ministerial visits, policy statements, lines of credit, power-grid interlinkage, transit and transport protocols and river-water cooperation, with readiness for humanitarian assistance and disaster relief built in; the qualification the owners insist upon is that the doctrine is not applied identically to every neighbour, because its emphasis is calibrated by the partner's size, history and current politics."),
        ("The Gujral Doctrine and its five principles", "The Gujral Doctrine, associated with former Prime Minister I. K. Gujral, is a five-principle approach under which India does not seek reciprocity from smaller neighbours, does not interfere in their internal affairs, does not allow its territory to be used against them, respects their territorial integrity, and settles disputes bilaterally and peacefully, and it remains the standard doctrinal reference for South Asia policy; the defining feature that examiners test is non-reciprocal accommodation, so any statement that the doctrine demands reciprocity as a precondition for cooperation inverts its meaning exactly."),
        ("Asymmetric interdependence as the structural starting point", "India is larger in economy, population and military capacity than its entire immediate neighbourhood combined, and the owners treat this asymmetry as the structural condition that shapes how smaller states balance cooperation with India against anxiety about dependence, so the Gujral Doctrine is best read as a response to that anxiety rather than as generosity for its own sake; the analytical move that raises an answer is to treat asymmetry as a design problem to be converted into reliable public goods, instead of treating size disparity as inherently adversarial."),
        ("Sikri's regional-framework preference among smaller neighbours", "Sikri records that smaller neighbours like Bhutan, Nepal, Maldives and Sri Lanka have shown greater interest in economic integration with India than the larger ones like Pakistan and Bangladesh, and that they are more receptive to cooperation within a regional framework than on a bilateral basis because numbers give them a sense of greater security, which the owners treat as a structural rather than merely tactical preference; the necessary qualification is that this preference does not amount to rejecting bilateral engagement, because the substantive connectivity work still proceeds bilaterally while the regional overlay supplies political reassurance."),
        ("Regime-oriented against people-to-people engagement", "Sikri argues that India must move away from its excessive regime-oriented policies towards people-to-people relations on the reasoning that only neighbouring regimes which reflect their own people's interests are likely to sustain friendly relations with India, and the owners convert this into the operative test of Neighbourhood First, namely whether engagement survives a change of government in the partner state; the regime-orientation trap emerges when engagement depends too heavily on one incumbent, producing discontinuity whenever that incumbent changes, and the people-to-people reorientation is presented as a partial mitigation rather than a guarantee."),
        ("Domestic-political sensitivity and the historical-involvement tension", "Sikri states that India has no alternative but to closely follow and deeply analyze political trends in neighbouring countries because their domestic developments have an effect on India itself, and he cites India as the decisive factor in seeking a resolution of domestic political crises in Bangladesh in 1971, Sri Lanka in 1987 and Nepal in 1950-51 and subsequent crises; the owners require that these be treated as historical references rather than a standing doctrine of intervention, and that the resulting tension with the Gujral Doctrine's non-interference principle be acknowledged explicitly instead of being smoothed into one consistent posture."),
        ("Bangladesh connectivity and the BBIN subregional instrument", "The Akhaura-Agartala cross-border rail link was inaugurated on 1 November 2023, complementing restored rail, inland-waterway, road and power links, and the Bangladesh, Bhutan, India and Nepal Motor Vehicles Agreement was signed in 2015 to facilitate cross-border passenger and cargo movement; the owners attach a limitation to each, namely that customs, trans-shipment, domestic politics and last-mile infrastructure determine actual use of a rail link, and that Bhutan's non-ratification has constrained four-country implementation of the Motor Vehicles Agreement, so subregionalism progresses where SAARC-wide consensus is unavailable but does not by itself deliver seamless movement."),
        ("Bhutan hydropower and the current commitment set", "The 720 megawatt Mangdechhu project was commissioned in 2019 and handed over to Bhutan in 2022, illustrating joint project delivery and electricity trade that links Bhutanese revenue to Indian clean-power access, and the owners record India's commitment of one hundred billion Indian rupees, equivalently ten thousand crore rupees, for Bhutan's thirteenth Five Year Plan covering 2024 to 2029, a rail-link memorandum of understanding of 29 September 2025 for the Kokrajhar-Gelephu and Banarhat-Samtse links, and support for Gelephu Mindfulness City expressed on 12 November 2025; the evidentiary boundary is that these are a commitment, a memorandum and political support rather than commissioned rail links or an operating city, and that project delay, cost escalation, ecological effects and Bhutan's diversification concerns require balance."),
        ("Teesta and the federal constraint on neighbourhood diplomacy", "The unresolved Teesta water-sharing issue demonstrates how Indian state-level interests can constrain a bilateral agreement with Bangladesh, and the owners draw the general lesson that neighbourhood diplomacy is shaped by domestic federal and border stakeholders rather than by the external ministry alone; the qualification carried with it is equally examinable, namely that one dispute should not be allowed to erase the wider record of connectivity and security cooperation, so the correct treatment is to name the federal constraint as a specific limiting mechanism instead of generalising it into a verdict on the whole relationship."),
        ("Act East physical routes and the segment-against-corridor distinction", "The Kaladan Multi-Modal Transit Transport Project and the India-Myanmar-Thailand Trilateral Highway aim to connect India's Northeast with Myanmar and Southeast Asia, and the owners record that on Kaladan the waterway and Sittwe Port were operationalised in May 2023 while the road component lagged, with both sides still calling for completion on 1 June 2026; the recorded reading is that the real gap in neighbourhood infrastructure is typically between a segment delivered and a corridor completed rather than between announcement and total inaction, and that conflict, incomplete road segments and border procedures mean an announced corridor is not seamless connectivity."),
        ("Sri Lanka's current instrument set and its pre-delivery status", "During the Prime Minister's visit of 5 April 2025 seven memoranda of understanding were exchanged with Sri Lanka, covering high-voltage direct-current power interconnection, digital transformation, the India-Sri Lanka-United Arab Emirates Trincomalee energy hub, defence cooperation, Eastern Province grant assistance, health and medicine, and pharmacopoeial cooperation, and the Ministry of External Affairs bilateral brief on India-Sri Lanka was current to July 2026; the owners fix the evidentiary level precisely, recording that signed memoranda are not proof that each project is operational and that the 120 megawatt Sampur solar project had its ground-breaking rather than its commissioning, while the same visit inaugurated five thousand rooftop solar units and a warehouse."),
        ("Maldives instruments and the maritime cross-link", "The India-Maldives Joint Vision of 7 October 2024 records support of four hundred million United States dollars and thirty billion Indian rupees as a currency-swap arrangement, the Terms of Reference for a free trade agreement were signed and negotiations launched on 25 July 2025, a line of credit of 4,850 crore Indian rupees is recorded, and the Ministry of External Affairs bilateral brief on India-Maldives was current to June 2026; the owners state expressly that a vision document, terms of reference and a line of credit are pre-delivery instruments and that no free trade agreement has been concluded, and they route the deeper Maldives treatment to topic 04 because its geostrategic salience is primarily maritime and is addressed by the 2024 objective demand recorded there."),
        ("Sri Lanka's 2022 crisis as the first-responder evidence set", "By 3 May 2022 India's High Commission recorded more than three billion United States dollars in assistance during 2022, comprising a one billion dollar facility for food, medicines and essentials, a five hundred million dollar petroleum credit line, about one billion dollars in Asian Clearing Union payment deferment and a four hundred million dollar Reserve Bank of India currency swap, while the petroleum line had delivered close to four hundred thousand tonnes of fuel across all twenty-five districts and the essentials facility had supplied rice and other necessities with medical consignments providing a humanitarian component; the owners require the aggregate to be time-bounded, since full-year descriptions commonly place support at around four billion dollars over 2022, and they record the limitation that emergency financing did not remove Sri Lanka's structural debt, revenue, governance and external-financing problems, whose durable resolution required domestic adjustment and an International Monetary Fund-supported programme."),
        ("Bangladesh's political transition and the Ganga Waters Treaty horizon", "India engaged Bangladesh's interim government from 16 August 2024 and pressed for early inclusive elections on 20 August 2025, parliamentary elections were held on 12 February 2026, and the 1996 Ganga Waters Treaty expires in December 2026 with India stating on 13 February 2026 that renewal talks had not begun; the owners classify this evidence exactly as engagement plus an election fact plus a treaty-expiry fact and no renewed treaty, which makes it the cleanest available test of whether Neighbourhood First engagement attaches to a state rather than to an incumbent government."),
        ("Nepal's transition and the power-trade understanding", "India welcomed the interim government led by Sushila Karki on 12 September 2025 after the unrest of September 2025, elections were held on 5 March 2026, and the understanding on importing ten thousand megawatts over ten years dates from 2 June 2023; the owners classify this as political engagement plus an agreed power-trade target and record expressly that it is not a revised Treaty of 1950, so an answer must not convert an energy-trade understanding into a renegotiated foundational treaty, and must read the sequence alongside Bangladesh and Sri Lanka as three simultaneous transition tests inside a single cycle."),
        ("Afghanistan engagement and the presence-against-recognition distinction", "India engaged the Taliban administration through the Foreign Secretary's Dubai meeting of 8 January 2025 and the External Affairs Minister's New Delhi meeting of 10 October 2025, and restored its Kabul Technical Mission to Embassy status with immediate effect on 21 October 2025; the owners state explicitly that this is a change in the level of India's diplomatic presence and that the official record contains no recognition declaration, so the upgrade must never be reported as recognition of the administration, and the near-neighbour framing from Tharoor supplies the reason the relationship is treated as vital to national security despite the absence of a direct pre-1947 border."),
        ("Pakistan and the water-security linkage under adversarial conditions", "The Cabinet Committee on Security decided on 23 April 2025 that the Indus Waters Treaty of 1960 will be held in abeyance with immediate effect until Pakistan credibly and irrevocably abjures its support for cross-border terrorism, Operation Sindoor was described officially on 7 May 2025 as measured, non-escalatory, proportionate, and responsible, and on 10 May 2025 India recorded an understanding to stop all military activities, while India separately maintains that the Court of Arbitration seized of the matter is illegally constituted and its awards null and void, a position restated on 16 May 2026; the owners fix the classification as an executive decision plus an operation plus an understanding, expressly not treaty termination and not a formal ceasefire agreement, and they draw the doctrinal point that non-reciprocal accommodation is least stable where the shared resource is finite, since it can be withdrawn when linked to a security condition."),
        ("The implementation-credibility test, the outside-power variable and honest question ownership", "The owners state that neighbourhood policy success is not measured by the number of agreements signed but by whether connectivity and development commitments are delivered and sustained across changes of government in the partner state, and they add the outside-power variable through Sikri's period-specific critique that India's policy on Pakistan, Bangladesh, Nepal and Sri Lanka was being guided by the United States and that the government of the day seemed to have outsourced its South Asia policy, which must be cited as a dated author-specific argument about the risk of external-power involvement rather than as a description of current policy; on ownership the ledgers route one Mains demand from 2022 General Studies Paper II and four objective demands, namely 2020 Prelims General Studies Paper I question 64 on India's trade with Sri Lanka, Bangladesh and Nepal, 2023 Prelims General Studies Paper I question 10 on regional connectivity projects including the Trilateral Highway and the Bangladesh-China-India-Myanmar corridor, and 2026 Prelims General Studies Paper I questions 61 and 67 on cross-border bridges with Bangladesh, Myanmar and Nepal and on development-assistance projects matched with neighbouring partner countries and locations, with no option or answer recorded or inferred for any of them."),
    ],
    [
        "Do not treat India's neighbours as a uniform buffer bloc, because each has a distinct history, domestic politics and posture and the homogeneity gap corrects exactly this error.",
        "Do not state that the Gujral Doctrine demands reciprocity, because its defining feature is non-reciprocal accommodation of smaller neighbours.",
        "Do not apply Neighbourhood First identically to every neighbour, because its emphasis is calibrated by size, history and current politics.",
        "Do not treat Maldives as a purely bilateral neighbourhood question, because its geostrategic salience is primarily maritime and its dedicated treatment sits in topic 04.",
        "Do not convert Sikri's historical examples into a standing doctrine of intervention, because India's stated posture under the Gujral Doctrine is non-interference and the tension must be acknowledged rather than resolved by assertion.",
        "Do not say that India has terminated the Indus Waters Treaty, because the decision of 23 April 2025 is that the Treaty is held in abeyance pending a change in Pakistan's conduct.",
        "Do not merge India's separate positions on Pakistan into one claim, because the abeyance decision, the illegally-constituted Court of Arbitration position and the null-and-void characterisation of its awards are distinct and none of them is treaty termination.",
        "Do not describe the understanding of 10 May 2025 as a formal ceasefire agreement, because the owners classify it as a recorded understanding to stop all military activities.",
        "Do not report the Kabul mission upgrade of 21 October 2025 as recognition of the Taliban administration, because it changes the level of diplomatic presence and the official record carries no recognition declaration.",
        "Do not treat the seven Sri Lanka memoranda of 5 April 2025 as operational projects, because signed memoranda are not proof of operation and the 120 megawatt Sampur solar project had its ground-breaking rather than its commissioning.",
        "Do not describe the India-Maldives free trade agreement as concluded, because only the Terms of Reference were signed and negotiations launched on 25 July 2025.",
        "Do not present the Bhutan rail-link memorandum of 29 September 2025 or the Gelephu Mindfulness City support of 12 November 2025 as built infrastructure, because they are a memorandum and political support respectively.",
        "Do not describe the Kaladan project as a completed corridor, because the waterway and Sittwe Port were operationalised in May 2023 while the road component lagged and completion was still being called for on 1 June 2026.",
        "Do not quote Sri Lanka's 2022 assistance without its time period, because more than three billion United States dollars is the figure recorded by 3 May 2022 while around four billion dollars is the common full-year description.",
        "Do not claim that the Bangladesh, Bhutan, India and Nepal Motor Vehicles Agreement of 2015 is fully implemented, because Bhutan's non-ratification has constrained four-country implementation.",
        "Do not convert Nepal's power-import understanding of 2 June 2023 into a revised Treaty of 1950, because the owners record it as an agreed power-trade target and nothing more.",
        "Do not present Sikri's critique of external-power involvement in South Asia as a current description, because it is a dated author-specific argument from the book's period.",
        "Do not measure neighbourhood policy by the number of summits or agreements, because the recorded test is delivery sustained across changes of government in the partner state.",
        "Do not invent a treaty or joint-statement wording, a border or diplomatic status, a summit outcome, a connectivity figure, an assistance number, a policy position, a previous-year question, an answer key or a current claim for this topic.",
    ],
    [
        (10, "Explain the core principles of the Gujral Doctrine and show how they address the structural asymmetry between India and its smaller neighbours.", "The doctrine converts asymmetry from a source of dependence anxiety into a basis for cooperation by removing reciprocity as a precondition, so the answer must state the five principles precisely, connect each to the anxiety it addresses, and qualify the claim with the fiscal and political cost of sustained non-reciprocity.", [3, 4, 2, 5]),
        (10, "Examine why the durability of India's neighbourhood engagement is tested by political transitions in partner states rather than by the number of agreements signed.", "Durability is the real test because a regime-oriented relationship discontinues whenever the incumbent changes, so the examination must state Sikri's people-to-people prescription, use the Bangladesh, Nepal and Sri Lanka transitions of a single cycle as the dated evidence, and qualify the prescription as a partial mitigation rather than a guarantee.", [6, 15, 16, 19]),
        (15, "Examine the observation that regional-framework cooperation appeals more to India's smaller neighbours than purely bilateral engagement.", "The preference is structural rather than tactical because numbers supply reassurance against asymmetry, so the examination must state Sikri's finding, distinguish smaller from larger neighbours, and qualify it with the fact that substantive connectivity work still proceeds bilaterally while the regional overlay supplies political reassurance.", [5, 4, 1, 8]),
        (15, "Examine the implementation-credibility gap in India's neighbourhood connectivity and development commitments.", "The gap is typically between a segment delivered and a corridor completed rather than between announcement and inaction, so the examination must date the Akhaura-Agartala link, the Kaladan waterway and port, the Sri Lanka memoranda and the Bhutan commitments, and close by naming the specific mechanism that stalled each one.", [8, 11, 12, 9]),
        (20, "Assess how India's neighbourhood doctrine performs when water-sharing and security conditions are linked.", "Non-reciprocal accommodation is least stable where the shared resource is finite, so the assessment must separate the executive abeyance decision from treaty termination, date the Ganga Waters Treaty expiry and the state of renewal talks, add the Teesta federal constraint as the domestic mirror of the same problem, and end with a graded verdict rather than a prediction.", [18, 15, 10, 3]),
        (20, "Assess India's role in Sri Lanka's 2022 crisis as a test of first-responder credibility and durable partnership.", "Emergency credibility and durable partnership are different claims, so the assessment must itemise the dated 2022 assistance with its time period, separate it from the pre-delivery instruments of 2025, acknowledge Sri Lankan agency and the structural constraints that emergency financing could not remove, and close with the implementation-credibility test.", [14, 12, 19, 0]),
    ],
    [
        plan("What the neighbourhood owner holds and how its scope is bounded", [0], "Maldives depth belongs to topic 04, grouping comparison to topic 10 and route geography to the Geography owner.", "Open a neighbourhood demand by fixing the owner's boundary before naming any country or project."),
        plan("The eight bordering neighbours and Afghanistan as a near-neighbour", [1], "Neighbourhood is defined by security relevance, and friction with six of eight is structural rather than exceptional.", "Establish the geographic and analytical frame before any evaluative claim about regional primacy."),
        plan("Neighbourhood First and the Gujral Doctrine's five principles", [2, 3], "Non-reciprocal accommodation is the doctrine's defining feature and its emphasis is calibrated per neighbour.", "Supply the doctrinal spine that any South Asia answer is expected to name precisely."),
        plan("Asymmetry and the regional-framework preference of smaller neighbours", [4, 5], "The preference adds reassurance and does not amount to rejecting bilateral delivery.", "Convert size disparity into a design problem about reliable public goods rather than an adversarial claim."),
        plan("Regime orientation, society orientation and the involvement tension", [6, 7], "Historical involvement is cited as episode, not as a standing doctrine, and sits in tension with non-interference.", "Acknowledge an unresolved doctrinal tension explicitly, which examiners reward over a smoothed narrative."),
        plan("Bangladesh connectivity and the BBIN subregional instrument", [8], "Bhutan's non-ratification constrains four-country implementation and last-mile factors govern actual use.", "Cite a dated connectivity instrument with the exact limitation that bounds its effect."),
        plan("Bhutan hydropower and the current commitment set", [9], "A plan commitment, a rail memorandum and political support are not commissioned links or an operating city.", "Separate a financing commitment from a delivered asset inside one bilateral relationship."),
        plan("Federal constraint and the segment-against-corridor distinction", [10, 11], "One dispute must not erase wider cooperation, and an announced corridor is not seamless connectivity.", "Name the precise stalling mechanism instead of asserting general implementation failure."),
        plan("Sri Lanka's current instrument set and its pre-delivery status", [12], "Signed memoranda are not operational projects and a ground-breaking is not a commissioning.", "Cite a dated bilateral brief and instrument rather than an undated connectivity claim."),
        plan("Maldives instruments and the maritime cross-link", [13], "Terms of reference are not a concluded free trade agreement and deeper treatment sits in topic 04.", "Route a question to the correct owner while still citing the dated instrument accurately."),
        plan("Sri Lanka's 2022 crisis as the first-responder evidence set", [14], "Carry the aggregate with its time period and concede that emergency financing left structural problems intact.", "Distinguish emergency assistance from durable partnership when a crisis question is asked."),
        plan("Bangladesh's transition and the Ganga Waters Treaty horizon", [15], "The record is engagement plus an election fact plus a treaty-expiry fact, with no renewed treaty.", "Test whether engagement attaches to a state rather than to an incumbent government."),
        plan("Nepal's transition and Afghanistan's presence-against-recognition line", [16, 17], "A power-trade understanding is not a revised 1950 treaty and a mission upgrade is not recognition.", "Apply two precise status distinctions that decide close options in objective and written answers."),
        plan("Pakistan, water security and the limits of non-reciprocity", [18], "Abeyance is India's own stated position and is neither treaty termination nor a formal ceasefire agreement.", "Qualify the Gujral Doctrine by showing when accommodation is withdrawn under a security condition."),
        plan("Implementation credibility, the outside-power variable and honest ownership", [19], "Sikri's external-power critique is dated and author-specific, and no routed question may be force-fitted.", "Close with the measurement test, a named external constraint and an explicit ownership boundary."),
    ],
    [
        panel("Neighbourhood map and friction count", "hierarchy", [
            "LAND OR MARITIME BORDER -> Pakistan, China, Nepal, Bhutan, Bangladesh,",
            "Myanmar, Sri Lanka, Maldives",
            "NEAR-NEIGHBOUR -> Afghanistan, adjacent after Pakistan's 1948 capture of a strip",
            "of north-western Kashmir",
            "FRICTION RECORD -> a history of problems with six of the eight bordering states",
            "RULE -> neighbourhood is defined by security relevance, not only by contiguity",
        ], ["India's eight bordering neighbours and Afghanistan as a near-neighbour"]),
        panel("Gujral Doctrine card", "hierarchy", [
            "PRINCIPLE 1 -> no reciprocity sought from smaller neighbours",
            "PRINCIPLE 2 -> no interference in their internal affairs",
            "PRINCIPLE 3 -> Indian territory not to be used against them",
            "PRINCIPLE 4 -> respect for their territorial integrity",
            "PRINCIPLE 5 -> bilateral and peaceful settlement of disputes",
            "DEFINING FEATURE -> non-reciprocal accommodation, never reciprocity as a precondition",
        ], ["The Gujral Doctrine and its five principles"]),
        panel("Asymmetry to policy design", "process-flow", [
            "SIZE ASYMMETRY -> India larger than the entire immediate neighbourhood combined",
            "-> DEPENDENCE ANXIETY: smaller states prefer regional-framework engagement",
            "-> NON-RECIPROCAL ACCOMMODATION: the doctrine answers the anxiety directly",
            "-> CONNECTIVITY AND CREDIT: tangible public goods build confidence over time",
            "-> TRANSITION TEST: does the benefit survive a change of government",
        ], ["Asymmetric interdependence as the structural starting point", "Sikri's regional-framework preference among smaller neighbours", "Regime-oriented against people-to-people engagement"]),
        panel("Neighbour-type comparison", "comparison-table", [
            "SMALLER STATES -> Bhutan, Nepal, Maldives, Sri Lanka; greater interest in economic",
            "integration; regional framework preferred because numbers give a sense of security",
            "LARGER OR MORE COMPLEX -> Pakistan and Bangladesh; more bilateral posture; distinct",
            "security and historical dynamics",
            "QUALIFIER -> regional preference is reassurance, not a rejection of bilateral delivery",
        ], ["Sikri's regional-framework preference among smaller neighbours", "Asymmetric interdependence as the structural starting point"]),
        panel("Connectivity instrument ledger", "evidence-table", [
            "1 NOVEMBER 2023 -> Akhaura-Agartala cross-border rail link inaugurated",
            "2015 -> BBIN Motor Vehicles Agreement signed; Bhutan non-ratification constrains it",
            "2019 / 2022 -> 720 MW Mangdechhu commissioned, then handed over to Bhutan",
            "MAY 2023 -> Kaladan waterway and Sittwe Port operationalised; road component lagged",
            "1 JUNE 2026 -> both sides still calling for Kaladan completion",
            "RULE -> the gap is segment delivered against corridor completed",
        ], ["Bangladesh connectivity and the BBIN subregional instrument", "Bhutan hydropower and the current commitment set", "Act East physical routes and the segment-against-corridor distinction"]),
        panel("Dated bilateral instrument matrix", "matrix", [
            "SRI LANKA -> seven MoUs, 5 April 2025; brief current to July 2026; Sampur 120 MW",
            "had ground-breaking, not commissioning",
            "MALDIVES -> Joint Vision 7 October 2024; FTA Terms of Reference 25 July 2025;",
            "INR 4,850 crore line of credit; brief current to June 2026",
            "BHUTAN -> INR 100 billion for the 13th Five Year Plan 2024-29; rail MoU 29 September",
            "2025; Gelephu Mindfulness City support 12 November 2025",
            "LEVEL -> vision, terms of reference, memorandum and credit are pre-delivery instruments",
        ], ["Sri Lanka's current instrument set and its pre-delivery status", "Maldives instruments and the maritime cross-link", "Bhutan hydropower and the current commitment set"]),
        panel("Sri Lanka 2022 first-responder card", "evidence-table", [
            "BY 3 MAY 2022 -> more than USD 3 billion recorded in assistance during 2022",
            "USD 1 billion -> facility for food, medicines and essentials",
            "USD 500 million -> petroleum credit line; close to 400,000 tonnes of fuel delivered",
            "ABOUT USD 1 billion -> Asian Clearing Union payment deferment",
            "USD 400 million -> Reserve Bank of India currency swap; 25 districts covered",
            "LIMIT -> around USD 4 billion is the full-year description; structural problems remained",
        ], ["Sri Lanka's 2022 crisis as the first-responder evidence set"]),
        panel("Transition-test timeline", "timeline", [
            "16 AUGUST 2024 -> India engages Bangladesh's interim government",
            "12 SEPTEMBER 2025 -> India welcomes Nepal's interim government under Sushila Karki",
            "20 AUGUST 2025 -> India presses for early inclusive elections in Bangladesh",
            "12 FEBRUARY 2026 -> Bangladesh parliamentary elections held",
            "5 MARCH 2026 -> Nepal elections held",
            "READING -> India engaged the successor arrangement in each case, not the outgoing one",
        ], ["Bangladesh's political transition and the Ganga Waters Treaty horizon", "Nepal's transition and the power-trade understanding"]),
        panel("Water-security ledger", "path-consequence", [
            "23 APRIL 2025 -> Cabinet Committee on Security holds the Indus Waters Treaty in abeyance",
            "CONDITION -> until Pakistan credibly and irrevocably abjures cross-border terrorism support",
            "16 MAY 2026 -> India restates that the Court of Arbitration is illegally constituted",
            "DECEMBER 2026 -> the 1996 Ganga Waters Treaty expires",
            "13 FEBRUARY 2026 -> India states that renewal talks had not begun",
            "DOCTRINE TEST -> non-reciprocity is least stable where the shared resource is finite",
        ], ["Pakistan and the water-security linkage under adversarial conditions", "Bangladesh's political transition and the Ganga Waters Treaty horizon"]),
        panel("Status distinctions that decide close options", "comparison", [
            "ABEYANCE -> an executive decision on operation; expressly not treaty termination",
            "UNDERSTANDING OF 10 MAY 2025 -> to stop all military activities; not a ceasefire agreement",
            "EMBASSY UPGRADE OF 21 OCTOBER 2025 -> mission level changed; no recognition declaration",
            "TERMS OF REFERENCE -> negotiations launched; not a concluded free trade agreement",
        ], ["Pakistan and the water-security linkage under adversarial conditions", "Afghanistan engagement and the presence-against-recognition distinction", "Maldives instruments and the maritime cross-link"]),
        panel("Domestic and external constraint band", "root-axes", [
            "FEDERAL -> Teesta shows Indian state-level interests constraining a bilateral agreement",
            "PARTNER POLITICS -> India must closely follow neighbouring political trends",
            "NON-INTERFERENCE -> the Gujral principle sits in tension with that necessity",
            "OUTSIDE POWER -> Sikri's dated critique of external guidance of South Asia policy",
            "RULE -> cite the constraint with its date and its author, never as current fact",
        ], ["Teesta and the federal constraint on neighbourhood diplomacy", "Domestic-political sensitivity and the historical-involvement tension", "The implementation-credibility test, the outside-power variable and honest question ownership"]),
        panel("Answer spine for a neighbourhood demand", "answer-spine", [
            "OPEN -> establish structural asymmetry and the non-reciprocal doctrinal response",
            "BUILD -> distinguish smaller-state and larger-state engagement patterns by name",
            "TEST -> cite one dated instrument with its exact evidentiary level and its limitation",
            "CLOSE -> apply the implementation-credibility test across a change of government",
        ], ["The implementation-credibility test, the outside-power variable and honest question ownership", "What this owner holds and how its scope is bounded"]),
    ],
    [
        "Neighbourhood First",
        "Gujral Doctrine",
        "non-reciprocal",
        "near-neighbour",
        "asymmetric interdependence",
        "regional framework",
        "people-to-people",
        "Akhaura-Agartala",
        "1 November 2023",
        "BBIN Motor Vehicles Agreement",
        "Mangdechhu",
        "Teesta",
        "Kaladan",
        "Sittwe Port",
        "Trilateral Highway",
        "5 April 2025",
        "Sampur",
        "7 October 2024",
        "25 July 2025",
        "Indus Waters Treaty",
        "23 April 2025",
        "Operation Sindoor",
        "Ganga Waters Treaty",
        "21 October 2025",
        "Sushila Karki",
        "implementation-credibility",
    ],
    "One General Studies Paper II Mains demand is routed to this topic in the audited routing ledgers and it is reproduced below as a demand card with its printed year, paper, question number, directive, marks and word limit exactly as the ledger records them: 2022 General Studies Paper II question 9, on India's role in the recent crisis in Sri Lanka, a Discuss demand of 10 marks and 150 words, where the ledger records that the Core route supersedes the older Advanced ownership. Four objective demands are also routed to this owner and are carried as coverage requirements only: 2020 Prelims General Studies Paper I question 64 on India's trade with Sri Lanka, Bangladesh and Nepal, for which the official key is not held locally; 2023 Prelims General Studies Paper I question 10 on India's regional connectivity projects including the Trilateral Highway and the Bangladesh-China-India-Myanmar corridor, for which the official key is not held locally; and 2026 Prelims General Studies Paper I questions 61 and 67 on India's cross-border bridges with Bangladesh, Myanmar and Nepal and on Indian development-assistance projects matched with neighbouring partner countries and locations, for which only a provisional 2026 Set-A key is present locally. No option or answer letter is recorded or inferred for any objective demand, and the provisional status of the 2026 key is preserved exactly. The audited ledgers record no 2024-2025 Mains demand naming the wider South Asian neighbourhood, Maldives being separately addressed by the 2024 objective demand routed to topic 04, and that absence is stated honestly rather than filled by force-fitting an unrelated question. The locally held OCR-searchable official General Studies papers were read only to confirm the printed wording of the routed Mains demand; no question was invented from them, no stem was paraphrased into an apparent routing, and no marking scheme or page precision was imported. Every model solution below is original work written to the repository's examiner-grade standard using the claim, named evidence, analysis and qualification pattern, and none of them reproduces or claims an official answer.",
    [
        (
            "2022",
            "General Studies Paper II Question 9",
            "India is an age-old friend of Sri Lanka. Discuss India's role in the recent crisis in Sri Lanka in the light of the preceding statement, a Discuss demand of 10 marks and 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership and the word limit is taken from the instruction block. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: India converted an inherited friendship into measurable first-responder capacity in 2022, but first-responder credibility and durable partnership are different achievements and only the first was demonstrated inside the crisis window. Named evidence and example: India's High Commission recorded more than three billion United States dollars in assistance during 2022 by 3 May 2022, comprising a one billion dollar facility for food, medicines and essentials, a five hundred million dollar petroleum credit line that had delivered close to four hundred thousand tonnes of fuel across all twenty-five districts, about one billion dollars in Asian Clearing Union payment deferment and a four hundred million dollar Reserve Bank of India currency swap; the seven memoranda of understanding exchanged on 5 April 2025 covering high-voltage direct-current power interconnection, digital transformation, the Trincomalee energy hub, defence cooperation, Eastern Province grant assistance, health and medicine and pharmacopoeial cooperation; and the Ministry of External Affairs bilateral brief current to July 2026. Analysis: the speed and composition of the 2022 package mattered because a foreign-exchange crisis attacks fuel, food and medicine simultaneously, so a credit line, a currency swap and a payment deferment together bought macroeconomic space that a grant alone could not, which is precisely the reliable public good that the Gujral Doctrine's non-reciprocal logic is meant to supply; the later instrument set shows the relationship moving from emergency support toward connectivity and energy partnership, yet the 120 megawatt Sampur solar project had its ground-breaking rather than its commissioning, so the implementation-credibility test is still running. Qualification: the answer must not claim that Indian assistance resolved the crisis, because the owners record that emergency financing did not remove Sri Lanka's structural debt, revenue, governance and external-financing problems and that durable recovery required domestic adjustment and an International Monetary Fund-supported programme, and the aggregate must be time-bounded as more than three billion dollars by May against around four billion dollars over the full year. Why this earns marks: it answers the Discuss directive by weighing an itemised, dated evidence set against a stated limit, respects Sri Lankan agency, and closes on a measurement test instead of a declaration of friendship.",
        ),
    ],
)
