"""Authored content data for International Relations learner-v2 Topic 01."""

from __future__ import annotations

import generate_international_relations_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_01 = common.topic(
    1,
    "Foreign-Policy Foundations and Strategic Autonomy",
    "01_Foreign-Policy-Foundations-and-Strategic-Autonomy",
    "01_Foreign-Policy-Foundations-and-Strategic-Autonomy_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and why the whole International Relations folder depends on it", "This topic owns the vocabulary that every later topic in the folder borrows, namely national interest, non-alignment, strategic autonomy, multi-alignment, Panchsheel, hedging, the bilateral-regional-minilateral-multilateral instrument toolkit and the autonomy-dependence trade-off, and its distinctive feature is that it is simultaneously conceptual and structurally examinable: the owners record that no General Studies Paper II Mains demand in the audited 2024-2025 papers directly names strategic autonomy, non-alignment or multi-alignment, while one objective demand from 2024 Prelims General Studies Paper I is routed to it, so it must be learned as the structuring lens for adjacent questions rather than as a stand-alone question bank; the constitutional basis in Article 51 of the Directive Principles belongs to the Polity owner and the Cold-War chronology of the Non-Aligned Movement's founding belongs to the World History owner."),
        ("National interest as the fixed starting point of the results chain", "The Master Framework of this folder defines national interest as the set of security, economic-growth and resource, technology, diaspora-welfare, reputation and rule-shaping, and strategic-autonomy goals that guide external conduct, and it fixes the answer chain as interest, then external context or actor, then instrument chosen, then verified outcome, then constraint or trade-off, then calibrated way forward; the operational consequence is that an answer which opens with a country list or a summit list has skipped the only step that makes the rest of the analysis evaluable, because the instrument can only be judged against the interest it was chosen to serve."),
        ("Nehru's three-part formulation of non-alignment", "Non-alignment as Nehru described it had three stated elements, namely that India has no military alliances with countries of either bloc, that India has an independent approach to foreign policy, and that India attempts to maintain friendly relations with all countries, so the doctrine was a refusal to join a Cold-War bloc rather than passivity or abstention from world affairs; the examinable precision is that the first element is about alliance membership, the second about decision-making method and the third about relationship breadth, and collapsing the three into a vague idea of neutrality loses exactly the distinction the examiner is testing."),
        ("Bipan Chandra's characterisation of non-alignment as a method rather than a blueprint", "Bipan Chandra's assessment in India After Independence frames non-alignment as not a blueprint for policy but an approach, a framework, a method, not a straitjacket but a lodestar by which the young nation could steer its course, which explains why the doctrine could survive the disappearance of the bipolar order that produced it; the analytical payoff is that continuity in Indian foreign policy is continuity of method and not continuity of partner set, so a change of partners is evidence of the method working rather than evidence of the doctrine being abandoned."),
        ("Strategic autonomy as the multipolar-era successor label", "Strategic autonomy is recorded in the owners as the continuing successor concept to non-alignment in a multipolar, post-Cold-War world, defined as the retained capacity to decide each external issue by India's own interest calculus rather than by bloc discipline, and it is expressly distinguished from neutrality, which implies equidistance or non-participation, because autonomy permits active and asymmetric engagement with several actors at once; Rajiv Sikri's supporting formulation is that India has wisely diversified its foreign-policy options but must retain flexibility in order to be able to pursue an independent foreign policy, on which there is an overwhelming national consensus."),
        ("Multi-alignment as Shashi Tharoor's operational expression of the same principle", "Multi-alignment is Tharoor's term in Pax Indica for engaging every relevant platform on its own terms, textually pairing the United Nations with the G20, the Non-Aligned Movement with the Community of Democracies, the G77 with smaller organizations like IOR-ARC, and SAARC with ASEAN-linked processes, as simultaneous and non-exclusive commitments rather than membership of one bloc; the examinable qualification is that most of the bodies in that list are non-treaty platforms, so multi-alignment describes engagement breadth and not alliance proliferation."),
        ("Panchsheel of 1954 and its exact treaty context", "Panchsheel comprises the five principles of peaceful coexistence, namely mutual respect for sovereignty and territorial integrity, non-aggression, non-interference, equality and mutual benefit, and peaceful coexistence, and the owners fix its exact location as the preamble of the India-China Agreement on Trade and Intercourse with the Tibet Region of China signed on 29 April 1954, which remains a historical normative reference still invoked in India's diplomatic vocabulary and cited in joint statements; the precision that earns marks is that Panchsheel is a set of normative principles for interstate conduct while non-alignment is a bloc-avoidance posture, so the two are related but distinct and were not adopted at the same conference."),
        ("Hedging distinguished from neutrality, bandwagoning and balancing", "Bandwagoning means aligning with the stronger power, balancing means aligning against it, and hedging means pursuing both engagement and risk-mitigation with more than one power simultaneously, so hedging is the opposite of avoidance and is best described in the owners as India's posture toward the United States-China dynamic; the decisive analytical line is that hedging is not equidistance or fence-sitting, because it involves deepening several partnerships, often deeply and asymmetrically, on separate issue tracks rather than declining to commit on any of them."),
        ("Co-option against autonomous positioning as Sikri's central strategic choice", "Sikri frames the core strategic choice explicitly as whether India wants to be co-opted into the existing international structures while retaining flexibility in order to be able to pursue an independent foreign policy, and the owners record this as the operational test to apply to any specific bilateral or multilateral decision; the two options are not fully exclusive in practice, which is precisely why the distinction is analytically useful, because it converts an evaluative question about a partnership into a testable question about whether the engagement preserved India's freedom to decide the next issue independently."),
        ("Issue-based coalition against treaty alliance", "An issue-based coalition such as the Quad, I2U2 or the G4 is formed around one specific shared interest without a mutual-defence treaty obligation, whereas an alliance carries binding collective-defence commitments, and the owners record that India's minilateral engagements are consistently the former and not the latter; the trap this distinction defuses is the assumption that participation in a named grouping implies alliance membership, and the Master Framework reinforces it with the alliance-autonomy conflation gap, which corrects the description of a deepened partnership as bloc membership."),
        ("Principle and interest as complementary rather than opposed", "Indian diplomatic practice does not present normative commitments such as anti-colonialism, sovereign equality and Panchsheel as a trade-off against hard interests such as security, technology access and growth, and the owners note that principled language is frequently used to build coalition legitimacy for interest-based goals, for example in Global South leadership; the boundary case worth writing is that solidarity language and the interest goal of institutional voice are not separable in practice, and saying so explicitly is itself an analytical point rather than an evasion."),
        ("The five levels of engagement and the instrument toolkit", "The Master Framework fixes five levels, namely bilateral engagement through summit visits, joint statements and defence or trade agreements, regional engagement through neighbourhood or geographic groupings such as SAARC, BIMSTEC, IORA and the Central Asia Dialogue, minilateral engagement through small non-treaty issue coalitions such as the Quad, I2U2, RIC and IBSA, multilateral or global engagement through universal or near-universal bodies such as the United Nations, the World Trade Organization, the International Monetary Fund, the World Bank and the G20, and diaspora or people-to-people engagement through the Pravasi Bharatiya Divas, the Indian Technical and Economic Cooperation programme and consular welfare diplomacy; the framework also records that one issue is frequently worked at more than one level at the same time, so naming the level and justifying it is a scoring step rather than decoration."),
        ("Evidentiary levels and the legal-status gap", "The Master Framework's instrument table separates binding and non-binding outputs by naming the exact stage each one reaches, so a treaty or agreement binds once ratified, a charter binds member states once in force, a joint statement or vision document is a political commitment and not a treaty, a declaration is political or normative rather than legally binding, a memorandum of understanding is a statement of intent that is not self-executing, a corridor memorandum is a framework of intent rather than evidence of an operating segment, a dialogue mechanism produces no binding output by itself, and partner or observer status is participation without the rights and obligations of full membership; the framework's stated exam trap is that agreed, signed or in force, and delivered are three different claims that must never be upgraded into one another without a date."),
        ("SAGAR of 2015 and MAHASAGAR of 2025 as declared visions", "SAGAR, standing for Security and Growth for All in the Region, was articulated in Mauritius on 12 March 2015, and on 12 March 2025, again in Mauritius at Port Louis, the Prime Minister announced that India's vision for the Global South would be going beyond SAGAR and would be MAHASAGAR, standing for Mutual and Holistic Advancement for Security and Growth Across Regions, encompassing trade for development, capacity building for sustainable growth, and mutual security for a shared future, delivered through technology sharing, concessional loan and grants; the owners are explicit that both are declared visions and not treaties, that they create no obligations by themselves, and that the 2025 announcement extends scope while reaffirming that India is moving ahead with the SAGAR Vision in the Indian Ocean region, so MAHASAGAR did not replace or supersede SAGAR."),
        ("The Voice of Global South Summit as autonomous agenda-setting", "The Voice of Global South Summit has had three editions recorded in the owners, held on 12 to 13 January 2023, on 17 November 2023 and on 17 August 2024, all convened virtually by India, and the third edition of 17 August 2024 is referenced in a subsequent Ministry of External Affairs bilateral document dated January 2025; the owners further record that no fourth edition was officially recorded as of 3 August 2026, so the platform is the clearest verified example of India-led coalition convening under multi-alignment while any further edition or outcome requires its own dated verification before it may be cited."),
        ("The autonomy-dependence trade-off as the doctrine's real cost", "The owners state that hedging is not cost-free and that deepening any single partnership beyond a threshold can erode the very autonomy the portfolio approach is meant to protect, and Sikri's own caution is recorded directly, namely that it is highly debatable whether it is wise for India, which remains heavily dependent on Russian military equipment, to enmesh its military planning and systems with those of the United States without reciprocal technology-sharing; the answer-writing consequence is that a strong response must acknowledge the trade-off as a genuine limitation rather than assert autonomy as costless, because the acknowledgement is precisely what distinguishes analysis from advocacy."),
        ("The 2025-26 hedging stress test with dated, reversible measures", "The owners record a dated sequence that tests hedging directly: an additional United States duty linked to purchases of Russian oil took effect on 27 August 2025 and was removed from 7 February 2026, India officially called the action unjustified and unreasonable on 4 and 6 August 2025, the twenty-third India-Russia Annual Summit went ahead in New Delhi on 4 and 5 December 2025, and the ten-year Framework for the United States-India Major Defense Partnership was signed on 31 October 2025; the recorded reading is that hedging held but that its cost is real, priced and third-party imposed, and the Master Framework's sanctions-obligation gap adds the necessary precision that another state's unilateral measure is exposure and secondary risk rather than a binding international-law duty on India."),
        ("Gulf energy exposure as a simultaneous vulnerability and lever", "Sikri records that a Gulf diaspora of five million gives India vital interests in, and considerable influence over, this energy-rich region, and the owners pair that with the Petroleum Planning and Analysis Cell record of 88.2 per cent crude-oil import dependence in the financial year 2024-25 and about 88.7 per cent provisional in the financial year 2025-26, so energy dependence operates at the same time as a source of vulnerability and as a channel of diplomatic leverage through diaspora and investment ties; the boundary discipline is that each figure must be carried with its issuing body, financial year and provisional status, because a provisional figure that is later revised must not be quoted as a settled one."),
        ("NAM's narrowed salience and the limits of coalition leadership", "The owners record that continued membership of the Non-Aligned Movement is maintained as one platform among many under multi-alignment while the movement itself has far less contemporary relevance than during the Cold War era, and they separately record that convening or co-chairing platforms such as the Voice of Global South Summit or the G4 demonstrates agenda-setting intent without by itself guaranteeing institutional outcomes, the unresolved state of United Nations Security Council reform being the standing illustration; a further recorded constraint is that principled language can appear inconsistent if paired too visibly with an interest-driven partnership choice on the same issue, which makes sequencing and framing a real diplomatic limit rather than an academic one."),
        ("Honest question ownership and the recurring analytical gaps applied here", "The owners state plainly that no General Studies Paper II Mains question in the audited 2024-2025 papers directly names strategic autonomy, non-alignment or multi-alignment, and they instruct that this be stated honestly rather than force-fitted, while noting that adjacent demands such as the 2024 question on the West and China's supply chain and the 2025 question on waning globalisation and sovereign nationalism implicitly require this vocabulary as the underlying lens; the audited routing ledgers additionally route one objective demand from 2024 Prelims General Studies Paper I, question 86, on books authored by S. Jaishankar, namely The India Way and Why Bharat Matters, and the owners record that the official Set-A key is present locally but that no option or answer is recorded or inferred, so the objective route is carried as a coverage requirement and never as a solved answer."),
    ],
    [
        "Do not describe non-alignment as neutrality or passivity, because Nehru's formulation is expressly an independent and active foreign-policy approach with three stated elements.",
        "Do not treat strategic autonomy and multi-alignment as competing doctrines, because the owners record them as successive labels for one continuing principle of independent, interest-based decision-making.",
        "Do not read multi-alignment as treaty membership of every named grouping, because most of the bodies Tharoor lists are non-treaty platforms and the concept describes engagement breadth.",
        "Do not equate hedging with equidistance or fence-sitting, because hedging means deepening several partnerships simultaneously on separate issue tracks.",
        "Do not conflate Panchsheel with non-alignment, because Panchsheel is a five-principle statement of interstate conduct in the preamble of the India-China agreement of 29 April 1954 while non-alignment is a bloc-avoidance posture.",
        "Do not state that MAHASAGAR replaced or superseded SAGAR, because the announcement of 12 March 2025 presents it as going beyond SAGAR while reaffirming that India is moving ahead with the SAGAR Vision.",
        "Do not describe SAGAR or MAHASAGAR as a treaty, a funding commitment or a delivered programme, because the owners classify both as declared visions carrying a date.",
        "Do not upgrade a joint statement, vision document, declaration or memorandum of understanding into a binding treaty, because the Master Framework's instrument table assigns each one a different evidentiary level.",
        "Do not upgrade signature into ratification, participation into membership, or a corridor memorandum into an operating corridor, because the legal-status, membership-participation and corridor-conception gaps each correct a different upgrade.",
        "Do not treat another state's unilateral sanction or tariff as a legal obligation on India, because the sanctions-obligation gap distinguishes exposure and secondary risk from a binding international-law duty.",
        "Do not present the 2025-26 United States duty sequence as settled trade policy, because the additional Russian-oil-linked duty took effect on 27 August 2025 and was removed from 7 February 2026.",
        "Do not assert that autonomy is costless, because the owners record the autonomy-dependence trade-off and Sikri's explicit caution about enmeshing military planning while remaining heavily dependent on Russian equipment.",
        "Do not claim that convening a platform guarantees an institutional outcome, because United Nations Security Council reform remains unresolved in the owners' own record.",
        "Do not treat the Non-Aligned Movement as still central, because the owners record its contemporary salience as far narrower while membership continues as one platform among many.",
        "Do not quote a crude-oil import-dependence figure without its issuing body, financial year and provisional status, because the owners record 88.2 per cent for the financial year 2024-25 and about 88.7 per cent as provisional for the financial year 2025-26.",
        "Do not force-fit a previous-year question onto this topic, because the owners record that no audited 2024-2025 General Studies Paper II Mains demand names strategic autonomy, non-alignment or multi-alignment.",
        "Do not record or infer an option for the routed 2024 Prelims General Studies Paper I question 86, because the integration block states that no answer is recorded or inferred even where the official Set-A key is held locally.",
        "Do not invent a treaty or joint-statement wording, a summit outcome, a diplomatic status, a trade or supply-chain figure, an initiative membership, a military or security development, a policy position, a previous-year question, an answer key or a current claim for this topic.",
    ],
    [
        (10, "Distinguish non-alignment, strategic autonomy and multi-alignment as successive framings of one underlying foreign-policy principle.", "The three labels express one continuing principle of independent, interest-based decision-making, so the answer must define each label with its own source, show what changed in the external context rather than in the method, and close by testing any engagement against whether it preserved India's freedom to decide the next issue.", [2, 3, 4, 5]),
        (10, "Explain why Panchsheel and non-alignment are related but analytically distinct, and why the distinction matters for an answer on India's normative vocabulary.", "Panchsheel is a five-principle statement of interstate conduct located in the preamble of the India-China agreement of 29 April 1954, while non-alignment is a bloc-avoidance posture, so the answer must separate normative principle from strategic posture and show how principled language supports interest-based coalition building without collapsing into it.", [6, 10, 2, 0]),
        (15, "Examine the claim that strategic autonomy is best understood as a method of instrument selection rather than as a fixed alliance preference.", "Autonomy is a method because the owners fix a five-level instrument toolkit and an evidentiary hierarchy that force each interest to be routed to the level that suits it, so the examination must run the results chain, name the level, cite one dated instrument with its exact evidentiary level, and close with the constraint that bounds the claim.", [1, 11, 12, 8]),
        (15, "Examine hedging as India's operational method toward competing major powers, and state the conditions under which it becomes costly.", "Hedging is the simultaneous deepening of several partnerships on separate issue tracks rather than equidistance, so the examination must define it against bandwagoning and balancing, use the dated 2025-26 sequence as the stress test, and qualify it with the autonomy-dependence trade-off and the sanctions-obligation distinction.", [7, 9, 15, 16]),
        (20, "Assess whether India's declared Global South visions and convening platforms strengthen strategic autonomy or merely restate it.", "Declared visions and convened platforms strengthen autonomy only to the extent that they demonstrate independent agenda-setting while remaining honestly labelled as visions rather than treaties, so the assessment must date SAGAR and MAHASAGAR, date the three Voice of Global South Summit editions, and close with the recorded limit that convening does not by itself guarantee an institutional outcome.", [13, 14, 18, 10]),
        (20, "Assess the autonomy-dependence trade-off as the binding constraint on India's diversified foreign-policy portfolio.", "The trade-off binds because deepening any single partnership beyond a threshold narrows the freedom the portfolio was built to protect, so the assessment must state Sikri's caution, price the 2025-26 duty sequence as a dated and reversible third-party cost, carry the energy-dependence figures with their issuing body and financial year, and end with a calibrated diversification verdict rather than a prediction.", [15, 16, 17, 19]),
    ],
    [
        plan("What the foundations owner holds and why its vocabulary transfers", [0], "This owner supplies the lens; Article 51 doctrine belongs to Polity and Cold-War chronology to World History.", "Open any general foreign-policy demand by naming the interest and the doctrine label before listing any partner or summit."),
        plan("National interest and the results chain that every answer must trace", [1], "An answer that opens with a country list has skipped the step that makes the instrument evaluable.", "Structure a whole answer as interest, actor, level, instrument, outcome, constraint and calibrated way forward."),
        plan("Nehru's three elements and Bipan Chandra's method reading", [2, 3], "Non-alignment is bloc avoidance and independent method, not neutrality and not a fixed partner set.", "Show doctrinal continuity through changed partners instead of narrating a chronology of summits."),
        plan("Strategic autonomy as the multipolar successor label", [4], "Autonomy permits active and asymmetric engagement, so it is not equidistance or non-participation.", "Anchor an is-India-still-non-aligned demand in continuity of method rather than declaring the doctrine over."),
        plan("Multi-alignment as the operational expression of the same principle", [5], "Most platforms in the multi-alignment list are non-treaty, so breadth is not alliance proliferation.", "Cite paired simultaneous engagements to prove non-exclusivity instead of asserting balance."),
        plan("Panchsheel of 1954 and the exact agreement that carries it", [6], "Panchsheel is a normative-principles statement, not a bloc posture, and the two were not adopted together.", "Supply the precise normative citation that raises a general foreign-policy answer above description."),
        plan("Hedging against neutrality, bandwagoning and balancing", [7], "Hedging deepens several partnerships at once, so describing it as fence-sitting inverts its meaning.", "Name India's posture toward competing powers with the correct technical term and defend the choice."),
        plan("Co-option against autonomous positioning and the coalition-alliance line", [8, 9], "Co-option and autonomy are not fully exclusive, and a named grouping is not proof of alliance membership.", "Convert an evaluative question about a partnership into a testable question about retained freedom of choice."),
        plan("Principle and interest as complementary in Indian practice", [10], "Solidarity language and the interest goal of institutional voice are not separable in practice.", "Answer a principles-versus-interests demand by showing complementarity rather than choosing a side."),
        plan("The five levels of engagement and the instrument toolkit", [11], "One issue is frequently worked at more than one level at the same time.", "Name the level and justify it, because level selection is itself a scoring step."),
        plan("Evidentiary levels and the legal-status discipline", [12], "Agreed, signed or in force, and delivered are three different claims that need separate dates.", "Cite one instrument with its exact stage so the outcome claim cannot be inflated."),
        plan("SAGAR of 2015 and MAHASAGAR of 2025 as dated declared visions", [13], "Both are declared visions, not treaties, and the later one extends scope without superseding the earlier.", "Cite a doctrinal articulation with its date and status instead of an undated slogan."),
        plan("The Voice of Global South Summit as autonomous convening", [14], "Three editions are recorded and no fourth was officially recorded as of 3 August 2026.", "Prove independent agenda-setting with a dated, verified convening rather than an aspiration."),
        plan("The autonomy-dependence trade-off and the 2025-26 stress test", [15, 16], "Another state's unilateral measure is exposure and secondary risk, not a legal duty on India.", "Acknowledge the real, dated cost of hedging so the answer reads as analysis rather than advocacy."),
        plan("Energy exposure, the narrowed Non-Aligned Movement and honest question ownership", [17, 18, 19], "Carry each dependence figure with its issuing body, financial year and provisional status, and never force-fit a question.", "Close with a named constraint, an institutional limit and an explicit ownership and data boundary."),
    ],
    [
        panel("Results chain of every IR answer", "process-flow", [
            "INTEREST -> security, growth, resources, technology, diaspora, reputation, autonomy",
            "-> EXTERNAL CONTEXT / ACTOR: neighbour, major power, region, grouping, institution",
            "-> INSTRUMENT: bilateral visit, regional forum, minilateral coalition, multilateral platform",
            "-> VERIFIED OUTCOME: joint statement, agreement, charter, declaration, memorandum",
            "-> CONSTRAINT: asymmetry, rival-power competition, partner politics, capacity limits",
            "-> CALIBRATED WAY FORWARD: diversify, hedge, sequence, build alternative capacity",
        ], ["National interest as the fixed starting point of the results chain"]),
        panel("Three labels, one continuing principle", "process-flow", [
            "NON-ALIGNMENT -> no bloc alliance, independent approach, friendly relations with all",
            "-> STRATEGIC AUTONOMY: multipolar-era label for issue-by-issue freedom of choice",
            "-> MULTI-ALIGNMENT: every relevant platform engaged on its own terms, non-exclusively",
            "CONSTANT -> independent, interest-based decision-making survives every relabelling",
        ], ["Nehru's three-part formulation of non-alignment", "Strategic autonomy as the multipolar-era successor label", "Multi-alignment as Shashi Tharoor's operational expression of the same principle"]),
        panel("Posture vocabulary grid", "comparison-table", [
            "BANDWAGONING -> align with the stronger power and accept its agenda",
            "BALANCING -> align against the stronger power to check it",
            "HEDGING -> engage and mitigate risk with more than one power at the same time",
            "NEUTRALITY -> equidistance or non-participation; expressly not India's posture",
            "RULE -> hedging is active and asymmetric, so it is never fence-sitting",
        ], ["Hedging distinguished from neutrality, bandwagoning and balancing", "Strategic autonomy as the multipolar-era successor label"]),
        panel("Panchsheel card", "hierarchy", [
            "INSTRUMENT -> preamble of the India-China Agreement on Trade and Intercourse with",
            "the Tibet Region of China, signed 29 April 1954",
            "PRINCIPLE 1 -> mutual respect for sovereignty and territorial integrity",
            "PRINCIPLE 2 -> non-aggression   PRINCIPLE 3 -> non-interference",
            "PRINCIPLE 4 -> equality and mutual benefit   PRINCIPLE 5 -> peaceful coexistence",
            "BOUNDARY -> a normative-principles statement, not the non-alignment posture",
        ], ["Panchsheel of 1954 and its exact treaty context"]),
        panel("Five levels of engagement", "matrix", [
            "BILATERAL -> summit visit, joint statement, defence or trade agreement",
            "REGIONAL -> SAARC, BIMSTEC, IORA, India-Central Asia Dialogue",
            "MINILATERAL -> Quad, I2U2, RIC, IBSA; small, issue-specific, non-treaty",
            "MULTILATERAL -> United Nations, World Trade Organization, IMF, World Bank, G20",
            "DIASPORA -> Pravasi Bharatiya Divas, ITEC, consular and welfare diplomacy",
            "NOTE -> one issue is frequently worked at more than one level at the same time",
        ], ["The five levels of engagement and the instrument toolkit"]),
        panel("Evidentiary ladder of instruments", "evidence-table", [
            "TREATY / AGREEMENT -> binding once ratified",
            "CHARTER -> binding on member states once in force",
            "JOINT STATEMENT / VISION -> political commitment, not a treaty",
            "DECLARATION -> political or normative, not legally binding",
            "MEMORANDUM OF UNDERSTANDING -> statement of intent, not self-executing",
            "CORRIDOR MEMORANDUM -> framework of intent, not an operating segment",
            "PARTNER / OBSERVER STATUS -> participation without membership rights and duties",
        ], ["Evidentiary levels and the legal-status gap"]),
        panel("Declared-vision timeline", "timeline", [
            "12 MARCH 2015 -> SAGAR articulated in Mauritius: Security and Growth for All in the Region",
            "12-13 JANUARY 2023 -> first Voice of Global South Summit, convened virtually by India",
            "17 NOVEMBER 2023 -> second Voice of Global South Summit",
            "17 AUGUST 2024 -> third Voice of Global South Summit; no fourth recorded as of 3 August 2026",
            "12 MARCH 2025 -> MAHASAGAR announced at Port Louis as going beyond SAGAR",
            "STATUS -> declared visions and convened platforms, not treaties or delivered programmes",
        ], ["SAGAR of 2015 and MAHASAGAR of 2025 as declared visions", "The Voice of Global South Summit as autonomous agenda-setting"]),
        panel("Hedging stress test of 2025-26", "path-consequence", [
            "27 AUGUST 2025 -> additional Russian-oil-linked United States duty takes effect",
            "4 AND 6 AUGUST 2025 -> India officially calls the action unjustified and unreasonable",
            "31 OCTOBER 2025 -> ten-year Framework for the US-India Major Defense Partnership signed",
            "4-5 DECEMBER 2025 -> twenty-third India-Russia Annual Summit held in New Delhi",
            "7 FEBRUARY 2026 -> the additional duty is removed",
            "READING -> hedging held, but its cost was real, priced and third-party imposed",
        ], ["The 2025-26 hedging stress test with dated, reversible measures"]),
        panel("Autonomy-dependence trade-off", "root-axes", [
            "PORTFOLIO -> overlapping, non-exclusive ties with several powers protect choice",
            "THRESHOLD -> deepening any one tie too far narrows the choice it was meant to protect",
            "SIKRI CAUTION -> enmeshing military planning while heavily dependent on Russian equipment",
            "is called highly debatable absent reciprocal technology-sharing",
            "ANSWER RULE -> concede the trade-off; do not assert that autonomy is costless",
        ], ["The autonomy-dependence trade-off as the doctrine's real cost"]),
        panel("Energy exposure as vulnerability and lever", "comparison", [
            "LEVER -> a Gulf diaspora of five million gives vital interests and considerable influence",
            "VULNERABILITY -> crude-oil import dependence recorded at 88.2 per cent in FY2024-25",
            "PROVISIONAL -> about 88.7 per cent provisional for FY2025-26 per the same issuing body",
            "DISCIPLINE -> carry issuing body, financial year and provisional status with every figure",
        ], ["Gulf energy exposure as a simultaneous vulnerability and lever"]),
        panel("Recurring analytical gaps applied here", "path-consequence", [
            "ANNOUNCEMENT-DELIVERY -> a memorandum or vision treated as a completed outcome",
            "LEGAL-STATUS -> signature treated as ratification, or adoption as entry into force",
            "MEMBERSHIP-PARTICIPATION -> partner or observer status described as membership",
            "ALLIANCE-AUTONOMY -> a deepened partnership described as bloc membership",
            "SANCTIONS-OBLIGATION -> another state's unilateral measure treated as a duty on India",
            "FIX -> name the exact stage and its date before making any evaluative claim",
        ], ["Evidentiary levels and the legal-status gap", "The 2025-26 hedging stress test with dated, reversible measures"]),
        panel("Answer spine for a foundations demand", "answer-spine", [
            "OPEN -> state the continuing principle before naming any era-specific label",
            "BUILD -> trace anti-colonial formation, bloc avoidance, diversification, multi-alignment",
            "TEST -> cite one dated instrument with its exact evidentiary level and its actor",
            "CLOSE -> concede the autonomy-dependence trade-off and give a calibrated way forward",
        ], ["Honest question ownership and the recurring analytical gaps applied here", "The autonomy-dependence trade-off as the doctrine's real cost"]),
    ],
    [
        "national interest",
        "non-alignment",
        "strategic autonomy",
        "multi-alignment",
        "Panchsheel",
        "29 April 1954",
        "hedging",
        "bandwagoning",
        "balancing",
        "issue-based coalition",
        "minilateral",
        "SAGAR",
        "MAHASAGAR",
        "12 March 2015",
        "12 March 2025",
        "Voice of Global South Summit",
        "17 August 2024",
        "autonomy-dependence trade-off",
        "27 August 2025",
        "7 February 2026",
        "88.2 per cent",
        "Non-Aligned Movement",
        "Bipan Chandra",
        "Sikri",
        "Tharoor",
    ],
    "One objective demand is routed to this topic in the audited routing ledgers and it is reproduced here exactly as the ledger records it: 2024 Prelims General Studies Paper I, question 86, on books authored by S. Jaishankar, namely The India Way and Why Bharat Matters. The owner's own integration block records that the official 2024 Prelims Set-A key is present locally, yet it states expressly that no option or answer is recorded or inferred, and that rule is preserved here without exception, so no answer letter appears anywhere in this package. No General Studies Paper II Mains demand in the audited 2024-2025 papers directly names strategic autonomy, non-alignment or multi-alignment, and the owners instruct that this be stated honestly rather than force-fitted onto an unrelated question, so no Mains demand card is manufactured for this topic and no adjacent question is claimed as its property. The locally held OCR-searchable official General Studies papers were read only to confirm printed wording; no question was invented from them, no stem was paraphrased into an apparent routing, and no marking scheme or page precision was imported. Every model solution in the original practice section below is original work written to the repository's examiner-grade standard using the claim, named evidence, analysis and qualification pattern, and none of them reproduces or claims an official answer.",
    [],
    pyq_audit_heading="VERIFIED OBJECTIVE-ONLY PYQ OWNERSHIP AUDIT",
)
