"""Durable learner-v2 content and master-flow specification for Hegel."""

from __future__ import annotations


def visual(title: str, caption: str, *lines: str) -> dict[str, object]:
    return {"title": title, "caption": caption, "lines": list(lines)}


def session(
    title: str,
    plain: str,
    technical: str,
    answer: str,
    keywords: list[str],
    usage: str,
    mechanism: str,
    consequence: str,
    trap: str,
    objection: str,
    reply: str,
    limit: str,
    exam: str,
    revision: list[str],
    visuals: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "title": title,
        "plain": plain,
        "technical": technical,
        "answer": answer,
        "keywords": keywords,
        "usage": usage,
        "mechanism": mechanism,
        "consequence": consequence,
        "trap": trap,
        "objection": objection,
        "reply": reply,
        "limit": limit,
        "exam": exam,
        "revision": revision,
        "visuals": visuals,
    }


SESSION_SPECS = (
    session(
        "Kant's Residual Dualisms and Hegel's Immanent Project",
        "Hegel begins from Kant's achievement but refuses to leave reason permanently divided from reality.",
        "Hegel's post-Kantian project is an immanent critique of fixed oppositions: finite categories are tested by their own claims, disclose their own incompleteness, and develop toward an Absolute that is a self-relating rational whole or subject rather than a static substance or supernatural object.",
        "Hegel radicalises Kant's critical achievement by arguing that a limit reason can determinately think cannot remain an external barrier to reason, so subject and object must be reconciled through identity-in-difference rather than collapsed into featureless sameness.",
        [
            "post-Kantian idealism",
            "immanent critique",
            "phenomenon and noumenon",
            "subject and object",
            "identity-in-difference",
            "Absolute",
        ],
        "Frame Kant's residual dualisms, then present Hegel's immanent project: explain why the thing-in-itself cannot be a permanent external limit and how identity-in-difference preserves distinctions within a developing Absolute.",
        "Each opposition is taken on its own terms; when either pole claims self-sufficiency, its dependence on the other appears and forces a richer determination.",
        "Reason becomes self-critical without becoming agnostic: finite distinctions remain real, but no finite term is fully intelligible in isolation.",
        "Do not say Hegel simply abolishes every distinction or identifies thought and being as two names for an undifferentiated One.",
        "Kant can reply that the noumenon is a limiting concept required to restrain speculative reason, not an object Hegel may know.",
        "Hegel answers that an externally fixed limit is already a determination within thought and that critique must test categories immanently rather than prohibit their development in advance.",
        "The reply pressures Kant's dualisms but does not by itself prove every transition or the completeness of Hegel's system.",
        "Use the route Kant's achievement -> residual dualisms -> immanent critique -> identity-in-difference -> qualified Absolute.",
        [
            "Kant secures phenomenal objectivity but retains phenomenon/noumenon and freedom/nature splits.",
            "The Absolute is the result of development, not a ready-made supernatural entity.",
            "Identity-in-difference reconciles opposed terms without erasing their determinate difference.",
        ],
        [
            visual(
                "Kant's unresolved oppositions and Hegel's project",
                "Hegel converts fixed limits into internally mediated relations.",
                "KANT'S ACHIEVEMENT: objective experience has rational conditions",
                "                 |",
                "                 v",
                "RESIDUAL OPPOSITIONS",
                "phenomenon | noumenon    subject | object",
                "thought    | being       freedom | nature",
                "                 | fixed external limits?",
                "                 v",
                "HEGEL: test each distinction by IMMANENT CRITIQUE",
                "                 |",
                "                 v",
                "IDENTITY-IN-DIFFERENCE within a self-developing ABSOLUTE",
            ),
            visual(
                "The three logical moments",
                "The moments are functions of one movement, not a universal mechanical recipe.",
                "ABSTRACT / UNDERSTANDING",
                "fixes a determination as self-sufficient",
                "                 | internal insufficiency appears",
                "                 v",
                "DIALECTICAL / NEGATIVE",
                "the fixed term passes into its determinate opposite",
                "                 | opposition is grasped together",
                "                 v",
                "SPECULATIVE / POSITIVE",
                "a concrete unity preserves difference within a richer determination",
            ),
        ],
    ),
    session(
        "Determinate Negation, Sublation and Being-Nothing-Becoming",
        "Dialectic moves because a one-sided concept fails in a specific way and therefore yields a specific successor.",
        "Determinate negation is the content-bearing negation of a definite determination; sublation (Aufhebung) cancels its one-sided independence, preserves its partial truth, and elevates it into a richer unity, so negation of negation produces mediated immediacy rather than a return to the untouched starting point.",
        "Hegelian negation is productive only when the successor is generated by the precise defect of the earlier determination, and Aufhebung names the single act by which the earlier moment is cancelled, preserved and elevated.",
        [
            "dialectic",
            "contradiction",
            "determinate negation",
            "Aufhebung",
            "negation of negation",
            "mediated immediacy",
        ],
        "Define determinate negation before sublation, state all three senses of Aufhebung, and show why the next category must preserve the content whose one-sided claim it cancels.",
        "A finite determination claims independence, reveals a contradiction internal to that claim, is specifically negated, and returns as a new immediacy enriched by the mediation.",
        "Error becomes partial truth within a more concrete determination; dialectic is cumulative rather than arbitrary destruction.",
        "Do not treat contradiction as formal inconsistency that licenses anything, or sublation as compromise between externally supplied positions.",
        "Formal logicians object that accepting contradiction violates non-contradiction and makes every conclusion derivable.",
        "The strongest Hegelian reply distinguishes a self-undermining pair of opposed determinations from simply asserting P and not-P in the same respect.",
        "The distinction explains the intended movement but still leaves the necessity of each transition to be demonstrated rather than announced.",
        "Write a four-link argument: fixed determination -> internal contradiction -> determinate negation -> sublated mediated immediacy.",
        [
            "Determinate negation yields this successor, not an empty nothing or any convenient result.",
            "Aufhebung means cancellation, preservation and elevation in one operation.",
            "Negation of negation recovers immediacy only as mediated and conceptually richer.",
        ],
        [
            visual(
                "Determinate negation and the three meanings of sublation",
                "The higher determination retains content while cancelling one-sidedness.",
                "FINITE DETERMINATION claims to be self-sufficient",
                "                 | its own claim generates a specific tension",
                "                 v",
                "DETERMINATE NEGATION = negation OF THIS content",
                "                 |",
                "                 v",
                "+------------- AUFHEBUNG -------------+",
                "| CANCEL one-sidedness                 |",
                "| PRESERVE partial truth               |",
                "| ELEVATE into a richer determination  |",
                "+--------------------------------------+",
            ),
            visual(
                "Being, Nothing and Becoming",
                "The transition is logical and immanent, not a temporal creation story.",
                "PURE BEING: no predicate, contrast or determinate content",
                "       | therefore indistinguishable from",
                "       v",
                "PURE NOTHING: the same absence of determination",
                "       | neither can be held apart from the passing-over",
                "       v",
                "BECOMING: unity of coming-to-be and ceasing-to-be",
                "       |",
                "       v",
                "NEW IMMEDIACY, but now MEDIATED by the failed opposition",
            ),
        ],
    ),
    session(
        "Concrete Universal, Finite Moments and the Architecture of the Whole",
        "A real whole does not erase its parts; it makes each part intelligible through its relations to the others.",
        "The concrete universal is a universal that particularises itself and contains its differences; finite entities and categories are real but partial moments whose identity is internally related to a developing whole structured as Logic, Nature and Spirit, with Spirit differentiated into Subjective, Objective and Absolute Spirit.",
        "The Hegelian whole is concrete because it preserves determinate finite moments within their internal relations, so 'the true is the whole' means the whole is the result of its development rather than a ready-made totality that swallows its parts.",
        [
            "concrete universal",
            "finite moment",
            "mediation",
            "internal relations",
            "Logic-Nature-Spirit",
            "Absolute Spirit",
        ],
        "Contrast abstract and concrete universals, explain finite reality as partial rather than illusory, and map both the large system and the nested forms of Spirit.",
        "Finite moments gain determinate identity through relations; the whole develops from pure categories through externality to self-conscious institutional and cultural life.",
        "Nature and finite minds remain real, while philosophy comprehends their place within the self-developing rational whole.",
        "Do not tell a temporal story in which an Idea existed before nature and later manufactured the world.",
        "The system may appear circular because it judges each finite stage from the completed whole that the stages are supposed to generate.",
        "Hegel replies that the whole is the result together with the path, and retrospective intelligibility is the mode of philosophical comprehension.",
        "Retrospective coherence does not automatically establish strict deductive necessity or eliminate contingency.",
        "Use two nested diagrams: finite moment <-> internally related whole, then Logic -> Nature -> Spirit and its three subdivisions.",
        [
            "Abstract universals omit difference; concrete universals organise and preserve it.",
            "Finite things are real as mediated moments, not unreal appearances.",
            "Art, religion and philosophy are forms of Absolute Spirit; philosophy gives conceptual comprehension.",
        ],
        [
            visual(
                "Finite moment and internally related whole",
                "Identity-in-difference makes the finite both real and non-self-sufficient.",
                "FINITE MOMENT A <---- INTERNAL RELATIONS ----> FINITE MOMENT B",
                "        \\                                      /",
                "         \\                                    /",
                "          +------ CONCRETE UNIVERSAL --------+",
                "          | preserves determinate difference |",
                "          | organises reciprocal dependence  |",
                "          | is the RESULT of development      |",
                "          +-----------------------------------+",
                "REAL AS A MOMENT != ULTIMATE IN ISOLATION",
            ),
            visual(
                "Logic, Nature and Spirit architecture",
                "The architecture is logical, not a sequence of events before and after nature.",
                "LOGIC: Idea in-itself -> Being -> Essence -> Concept",
                "                 | logical externality, not temporal creation",
                "                 v",
                "NATURE: Idea in otherness -> space, time, matter, organism",
                "                 | return through living and social self-consciousness",
                "                 v",
                "SPIRIT: Idea returned-to-itself",
                "   SUBJECTIVE -> individual mind",
                "   OBJECTIVE  -> right, morality, ethical life, history",
                "   ABSOLUTE   -> art -> religion -> philosophy",
            ),
        ],
    ),
    session(
        "Recognition and Lordship-Bondage: Dependence, Fear and Labour",
        "Self-consciousness needs acknowledgement from another self-consciousness, so domination defeats its own purpose.",
        "Recognition (Anerkennung) is the intersubjective condition of self-consciousness; the lordship-bondage dialectic shows that one-sided recognition makes the lord dependent, while fear, service and formative labour (Bildung) allow the bondsman to acquire a mediated independence.",
        "The lordship-bondage episode demonstrates that unequal recognition is conceptually unstable: the lord depends on an acknowledgement he has devalued, whereas the bondsman's fear and labour form a more durable self-relation.",
        [
            "recognition",
            "self-consciousness",
            "lordship and bondage",
            "dependence",
            "fear",
            "labour and Bildung",
        ],
        "Begin with the need for recognition, trace the struggle and asymmetry, explain both directions of dependence, and end with labour as formative self-objectification.",
        "The lord consumes through the bondsman's work and receives recognition from an unfree other; the bondsman disciplines desire, shapes the object and encounters his own form in the worked world.",
        "Freedom is relational and mediated rather than possession by an isolated ego or the successful domination of another.",
        "Do not reduce all Hegel to a master-slave struggle or claim the passage predicts the rapid historical overthrow of every master.",
        "A recognition-centred interpretation can shrink Absolute Idealism into social psychology and overstate one episode of the Phenomenology.",
        "Used as a bounded illustration, the episode concretises the dependence of selfhood and freedom on mediated social relations without replacing the system.",
        "The passage establishes conceptual instability more securely than any timetable of historical emancipation.",
        "Use the dependence loop, the reversal through fear and labour, and a final qualification on the limited role of the episode.",
        [
            "Recognition from a devalued, unfree other cannot satisfy the lord's aim.",
            "Fear, service and labour educate desire and produce formative self-consciousness.",
            "The illustration is one stage of the Phenomenology, not a complete theory of Hegel.",
        ],
        [
            visual(
                "Recognition and the dependence loop",
                "The apparent independence of the lord conceals a twofold dependence.",
                "SELF A needs recognition <------------> SELF B needs recognition",
                "                 | life-and-death struggle",
                "                 v",
                "LORD ---------------------------- BONDMAN",
                " | recognition from an unfree other      | fear of death",
                " | depends on labour for enjoyment        | service disciplines desire",
                " +--------------- DEPENDENCE ------------+ labour shapes object",
                "                                             |",
                "                                             v",
                "                                 BILDUNG: self formed in the world",
                "RESULT: reciprocal recognition, not domination, is the stable norm",
            ),
        ],
    ),
    session(
        "Phenomenological Development: Consciousness, Self-Consciousness and Reason",
        "The Phenomenology follows forms of experience that fail by the standards they themselves claim to satisfy.",
        "A shape of consciousness (Gestalt) contains a criterion of knowledge and an object corresponding to it; experience is the immanent revision produced when the object fails that criterion, carrying consciousness through consciousness, self-consciousness and reason toward social and spiritual forms.",
        "The Phenomenology is a ladder of immanent failures: each shape discovers that its own criterion cannot secure the object it claims, so consciousness preserves the lesson and advances toward reason and Spirit.",
        [
            "Phenomenology",
            "shape of consciousness",
            "consciousness",
            "self-consciousness",
            "reason",
            "Spirit",
        ],
        "State the criterion-failure mechanism, use recognition and the Stoicism-Scepticism-Unhappy Consciousness sequence as bounded illustrations, and show the transition to reason.",
        "Sense-certainty and object-consciousness expose unstable immediacy; recognition makes self-consciousness relational; failed freedoms in thought make their contradiction explicit and open the standpoint of reason.",
        "Knowledge becomes a historical and social achievement in which the knower's standard is transformed with the known object.",
        "Do not present the sequence as a literal universal chronology or force every historical culture into a rigid three-step algorithm.",
        "Kierkegaard objects that the existing individual's relation to the eternal cannot be reduced to a stage that a universal system supersedes.",
        "Hegel can reply that a shape is overcome at the level of its claim to truth, not erased as a recurring possibility in individual life.",
        "The reply preserves phenomenological logic but may understate irreducible existential singularity.",
        "Use one criterion-failure cycle, then the main ladder, then one named objection and reply.",
        [
            "A shape fails by its own criterion; the philosopher does not impose an external test.",
            "Stoicism -> Scepticism -> Unhappy Consciousness shows determinate transitions in thought.",
            "Reason finds itself in the world and prepares the move to social Spirit.",
        ],
        [
            visual(
                "Phenomenological path through immanent failure",
                "Each transition preserves a lesson while revising both knower and known.",
                "CONSCIOUSNESS: object is taken as independent",
                "      | its own criterion fails to secure the object",
                "      v",
                "SELF-CONSCIOUSNESS: object is another self; recognition required",
                "      | unequal recognition and abstract freedom fail",
                "      v",
                "STOICISM -> SCEPTICISM -> UNHAPPY CONSCIOUSNESS",
                "      | contradiction becomes explicit and is worked through",
                "      v",
                "REASON: consciousness is certain of finding itself in reality",
                "      | develops socially and historically",
                "      v",
                "SPIRIT: shared practices, institutions and self-comprehension",
            ),
        ],
    ),
    session(
        "Absolute Idealism: Substance as Subject, Actuality and Thought-Being",
        "Absolute Idealism understands thought and being within a self-developing whole: substance is also subject, finite differences are real moments, and actuality is more than mere existence.",
        "Absolute Idealism holds that reality is internally related and self-developing, that substance must also be subject, and that thought and being are identical only as differentiated moments mediated within the whole; actuality (Wirklichkeit) is realised rational structure, not every item of mere existence (Dasein).",
        "Hegel's Absolute Idealism neither reduces reality to a private mind nor blesses every fact: it treats finite beings as real moments of a substance that is also subject and reserves actuality for existence that has realised its rational concept.",
        [
            "Absolute Idealism",
            "substance-as-subject",
            "thought and being",
            "Wirklichkeit",
            "Dasein",
            "actuality",
        ],
        "Define Absolute Idealism, explain substance as subject, distinguish mediated thought-being identity from collapse, and contrast actuality (Wirklichkeit) with mere existence (Dasein) before using the rational-actual formula.",
        "The Absolute differentiates itself in nature and finite spirit, relates those differences internally, and returns to conceptual self-comprehension without cancelling their reality.",
        "The phenomenal world is real as a mediated manifestation but not ultimate as an isolated collection of self-sufficient facts.",
        "Never translate 'the actual is rational' as 'whatever exists or whatever the state does is justified.'",
        "The formula can still be read conservatively because Hegel's retrospective philosophy may rationalise institutions after their victory.",
        "The Wirklichkeit-Dasein distinction blocks blanket endorsement, while immanent critique permits institutions to be judged by whether they realise their own rational norm of freedom.",
        "The distinction weakens the authoritarian reading but does not remove all tension between reconciliation and criticism.",
        "Use substance -> subject, finite moment <-> whole, Dasein vs Wirklichkeit, then a qualified political verdict.",
        [
            "The Absolute is a result that becomes what it is through self-differentiation.",
            "Thought and being are reconciled through mediation, not flattened into numerical identity.",
            "Actuality means realised rational essence; mere existence can remain irrational and defective.",
        ],
        [
            visual(
                "Substance becomes subject",
                "Hegel retains unity but makes it self-differentiating and self-knowing.",
                "STATIC SUBSTANCE",
                "undifferentiated unity | no internal history | finite modes accidental",
                "                 | Hegelian correction",
                "                 v",
                "SUBSTANCE ALSO AS SUBJECT",
                "self-differentiates -> externalises -> returns -> knows itself",
                "                 |",
                "                 v",
                "FINITE MINDS AND NATURE = REAL MOMENTS, NOT ILLUSIONS",
            ),
            visual(
                "Existence is not actuality",
                "The distinction prevents the rational-actual formula becoming a defence of every fact.",
                "DASEIN / MERE EXISTENCE",
                "a fact is present, but may fail its concept or rational norm",
                "                 | development, mediation, institutional testing",
                "                 v",
                "WIRKLICHKEIT / ACTUALITY",
                "existence has realised its rational concept in a durable form",
                "",
                "THEREFORE: existing injustice != rational actuality",
                "CRITICAL QUESTION: does the institution realise freedom in its own form?",
            ),
        ],
    ),
    session(
        "Hegel's Challenge to Kant: Limits, Noumena and Critical Idealism",
        "Hegel attacks a boundary that claims to separate thought permanently from what reality is in itself.",
        "Hegel's critique has three linked claims: the boundary is itself thought, the thing-in-itself is determined through categories whose use it supposedly excludes, and a relation between unknowable cause and appearance contradicts Kant's own limits; Absolute Idealism replaces the external boundary with immanent differentiation.",
        "Hegel's strongest objection is not that Kant distinguishes appearance from reality, but that Kant freezes this distinction into an unknowable beyond while still thinking and relating that beyond to experience.",
        [
            "critical idealism",
            "phenomena",
            "noumena",
            "thing-in-itself",
            "boundary",
            "Absolute Idealism",
        ],
        "Present Kant's critical idealism accurately, reconstruct Hegel's challenge to its limits and noumena in three prongs, distinguish a limiting-concept defence from a knowledge claim, and conclude with a bounded comparison.",
        "Thinking a boundary relates both sides; naming a thing-in-itself applies being and negation; invoking affection applies causal relation beyond possible experience.",
        "The subject-object opposition becomes an internal relation within experience and reality rather than an unbridgeable epistemic wall.",
        "Do not claim that Hegel's objection automatically gives direct knowledge of every object or makes finite perspectives infallible.",
        "Kant replies that noumenon negatively marks what sensible cognition cannot know and need not be a positively described supersensible cause.",
        "Hegel answers that a merely external restriction remains dogmatic unless the categories generate and justify their own limits through immanent critique.",
        "Hegel exposes the instability of a positive noumenal cause more decisively than he proves the completed Absolute.",
        "Use a split comparison card and end: Hegel wins against a positive two-world reading, Kant remains stronger as a warning against premature totality.",
        [
            "Kant limits categories to possible experience; Hegel asks whether the limit is itself coherent.",
            "The limit, the object beyond it and its affection of sensibility are all conceptually determined.",
            "The comparison is a dispute over how reason criticises itself, not reason versus irrationality.",
        ],
        [
            visual(
                "Kant and Hegel compared",
                "The disagreement concerns whether reason's limit is external or immanently generated.",
                "+----------------------+----------------------+",
                "| KANT                 | HEGEL                |",
                "+----------------------+----------------------+",
                "| phenomena knowable   | finite shapes real   |",
                "| noumenon limits      | fixed beyond unstable|",
                "| forms condition      | categories self-move |",
                "| reason restrains     | reason self-corrects |",
                "| dualism retained     | identity-in-difference|",
                "+----------------------+----------------------+",
                "VERDICT: critique of a positive noumenon is stronger than proof of totality",
            ),
        ],
    ),
    session(
        "The Logic-Nature Transition: Non-Temporal Release and Systemic Risk",
        "The hardest seam asks how a self-contained logic of categories can be followed by contingent nature.",
        "At the close of the Logic the Absolute Idea 'freely releases itself' as Nature, the Idea in otherness; this is offered as a logical relation of self-externality rather than a temporal creation or causal production, while the impotence of nature acknowledges contingency and imperfect embodiment of the Concept.",
        "The Logic-Nature transition is defensible only as a non-temporal claim that complete self-relation includes externality, not as the story of an Idea existing before nature and causing a world.",
        [
            "Absolute Idea",
            "free release",
            "Idea in otherness",
            "Logic to Nature",
            "impotence of nature",
            "contingency",
        ],
        "State the Logic to Nature category-to-existence problem, explain how the Absolute Idea's non-temporal free release yields the Idea in otherness, use the impotence of nature to locate contingency, and assess the systemic risk.",
        "Pure self-relating form is said to externalise as nature; nature's externality cannot perfectly hold the Concept, so contingent particulars are not deduced one by one.",
        "The system can include natural otherness without claiming that logic temporally preceded or mechanically produced nature.",
        "Do not personify the Idea as deciding to create, or claim Hegel deduces every scientific fact from pure thought.",
        "Schelling argues that logic can show what existence must be but cannot generate the sheer fact that something exists; Trendelenburg adds that movement is smuggled in.",
        "Hegel replies that Being was never a merely hypothetical essence and that conceptual instability is logical, not borrowed spatial motion.",
        "The replies make the transition coherent from within the system but do not make its necessity demonstrative to a critic outside it.",
        "Use problem -> Hegelian clarification -> four objections -> replies -> coherent-but-not-demonstrative verdict.",
        [
            "The release is non-temporal, non-causal and structural.",
            "Nature is the Idea in otherness, and its impotence leaves room for contingency.",
            "Schelling's essence-existence objection remains the deepest unresolved seam.",
        ],
        [
            visual(
                "Logic to Nature without a creation story",
                "The transition is structural; objections test whether structural coherence is enough.",
                "SCIENCE OF LOGIC",
                "Being -> Essence -> Concept -> Absolute Idea",
                "                 | 'freely releases itself'",
                "                 | NOT temporal | NOT causal | NOT personal choice",
                "                 v",
                "NATURE = IDEA IN OTHERNESS",
                "space | time | matter | organism | contingency",
                "                 |",
                "                 v",
                "IMPOTENCE OF NATURE: no deduction of every particular fact",
                "SEAM: can logical self-externality establish that nature exists?",
            ),
        ],
    ),
    session(
        "Objective Spirit, History and Freedom in Rational Institutions",
        "Freedom is not arbitrary choice but the capacity to recognise oneself in social relations that make rational agency possible.",
        "Objective Spirit is the institutional embodiment of freedom through abstract right, morality and ethical life; history is interpreted as the development of consciousness of freedom, while rational freedom means being at home with oneself in institutions whose necessity one can recognise.",
        "For Hegel, freedom becomes actual only when subjective willing is mediated by rights, practices and institutions that agents can recognise as their own rational life, though his historical teleology remains vulnerable to Eurocentrism and conservatism.",
        [
            "Objective Spirit",
            "freedom",
            "ethical life",
            "rational institutions",
            "history",
            "cunning of reason",
        ],
        "Define positive or institutional freedom, distinguish it from arbitrary choice, map subjective to objective freedom, and use history only to enrich the official Absolute-Idealism spine.",
        "Individual will enters relations of right and morality, finds fuller mediation in ethical institutions, and historically becomes conscious that freedom belongs in principle to all.",
        "Freedom is social self-recognition and recognised necessity, not submission to any institution simply because it exists.",
        "Do not let the One-Some-All history scheme displace the official dialectical-method and Absolute-Idealism syllabus.",
        "Kierkegaard fears the system subordinates the existing individual, Marx exposes material domination inside legal universality, and Popper attacks retrospective teleology.",
        "A Hegelian reply uses immanent critique: institutions are rational only insofar as they realise their own universal norm of freedom concretely.",
        "The reply preserves a critical institutional theory but does not vindicate Hegel's Eurocentric historical sequence or every claim about the State.",
        "Use freedom as mediated self-relation, one institutional ladder, one historical mechanism, and a qualification on teleology.",
        [
            "Freedom is being at home with oneself in an other, not absence of every constraint.",
            "Objective Spirit gives freedom institutional form in right, morality and ethical life.",
            "History can illustrate dialectical freedom, but teleology and Eurocentrism must be criticised.",
        ],
        [
            visual(
                "Freedom becomes institutional and self-conscious",
                "The path moves from isolated willing to recognised, socially mediated freedom.",
                "SUBJECTIVE WILL: capacity to choose",
                "        | without recognition and stable norms remains abstract",
                "        v",
                "ABSTRACT RIGHT -> MORALITY -> ETHICAL LIFE",
                "        | family | civil society | constitutional institutions",
                "        v",
                "OBJECTIVE FREEDOM: agents recognise rational norms as their own",
                "        | historical development of consciousness of freedom",
                "        v",
                "ONE FREE -> SOME FREE -> ALL FREE IN PRINCIPLE",
                "QUALIFICATION: immanent critique, not worship of every existing State",
            ),
        ],
    ),
    session(
        "Comparisons, Criticisms, Replies and the Philosophy Optional Answer Spine",
        "Hegelian comparisons, criticisms and replies test whether each transition is immanent and necessary, while a Philosophy Optional answer spine turns that evaluation into a structured exam response.",
        "A disciplined evaluation compares Kantian limits with Hegelian immanence, distinguishes subjective, objective and Absolute Idealism, treats Marx's material inversion as a bounded transformation, and stages Kierkegaardian, materialist, analytic and political objections against Hegelian replies based on determinate negation and concrete universality.",
        "Comparisons and criticisms reveal Hegel's strength in immanent critique, while the best replies still leave a Philosophy Optional answer to judge the gap between retrospective reconstruction and strict demonstration.",
        [
            "subjective idealism",
            "objective idealism",
            "Absolute Idealism",
            "Kierkegaard",
            "Marx",
            "analytic criticism",
        ],
        "Build the Philosophy Optional answer spine through subjective idealism, objective idealism and Absolute Idealism, then stage Kierkegaard, Marx and analytic criticism with replies, residual tensions and a graded verdict.",
        "Each critic targets a different joint: the individual's irreducibility, material conditions, logical obscurity, necessity of transition, or political reconciliation.",
        "The system remains significant in recognition theory, immanent social criticism, accounts of historical reason and debates over internal relations.",
        "Do not say Marx simply adopted Hegel, Popper conclusively refuted every dialectical use, or conservative readings are the only possible reading of actuality.",
        "Kierkegaard charges that the system loses existence; Marx that idealism inverts material relations; Schopenhauer and analytic critics challenge obscurity and contradiction; political critics fear authoritarian reconciliation.",
        "Hegelian replies distinguish conceptual from formal contradiction, appeal to determinate transition, preserve the finite in the concrete universal, and judge institutions by realised freedom rather than bare existence.",
        "The replies secure a powerful critical method more readily than the complete metaphysical and historical necessity of the system.",
        "Use thesis -> definitions -> immanent mechanism -> example -> objection -> reply -> residual -> qualified verdict.",
        [
            "Kant and Hegel differ over external limits versus immanently generated limits.",
            "Marx keeps dialectical transformation but relocates the driver in material social relations.",
            "The defensible Hegel is strongest as immanent critique and weakest as guaranteed total system.",
        ],
        [
            visual(
                "Three idealisms distinguished",
                "The axis is what grounds objectivity and the relation of finite mind to reality.",
                "SUBJECTIVE IDEALISM -> finite perceiver and its ideas; Berkeleyan dependence",
                "OBJECTIVE IDEALISM  -> intelligible objective order not reducible to one mind",
                "ABSOLUTE IDEALISM   -> subject and object are moments of one developing whole",
                "",
                "HEGEL: nature is real as self-externality; finite minds are real moments",
                "NOT: the world is my idea | NOT: thought and being lack all difference",
            ),
            visual(
                "Criticism and reply map",
                "A good answer identifies the exact joint under pressure and the reply's limit.",
                "KANT -> illegitimate totality | REPLY -> limits must justify themselves immanently",
                "KIERKEGAARD -> existing individual | REPLY -> finite life is preserved as a moment",
                "MARX -> idealist inversion | REPLY -> norms and meanings have objective force",
                "SCHOPENHAUER / ANALYTIC -> obscurity, contradiction, forced transitions",
                "REPLY -> determinate negation, not arbitrary inconsistency",
                "POLITICAL -> actuality justifies power | REPLY -> Wirklichkeit != mere existence",
                "RESIDUAL -> retrospective coherence does not always prove necessary progression",
            ),
            visual(
                "Philosophy Optional answer spine",
                "The structure protects doctrine, comparison and evaluation from slogan-based writing.",
                "DIRECTIVE -> precise thesis -> define technical terms",
                "          -> reconstruct immanent transition",
                "          -> Being/Nothing/Becoming or recognition illustration",
                "          -> link method to Absolute Idealism",
                "          -> named objection -> best Hegelian reply",
                "          -> residual tension -> graded verdict",
                "FINAL TEST: was the progression justified rather than merely asserted?",
            ),
        ],
    ),
)


ASCII_PANELS = (
    {
        "title": "Kantian dualisms and Hegel's immanent starting project",
        "structural_type": "opposition-bridge-and-moment-rail",
        "sessions": [1],
        "lines": [
            "START: Kant secures objective experience but retains fixed residual oppositions.",
            "PHENOMENON = knowable appearance; NOUMENON = unknowable thing-in-itself.",
            "SUBJECT supplies cognitive form; OBJECT names independently existing reality.",
            "THOUGHT versus BEING; FREEDOM versus NATURE remain externally divided.",
            "HEGEL'S CHARGE -> a limit determinately thought is already within thought.",
            "IMMANENT CRITIQUE -> test a category or form of life by its own criterion.",
            "FINITE CATEGORY -> its claim to self-sufficiency discloses dependence on its other.",
            "ABSTRACT/UNDERSTANDING -> NEGATIVE/DIALECTICAL -> SPECULATIVE/POSITIVE moment",
            "IDENTITY-IN-DIFFERENCE -> reconciliation preserves determinate distinctions.",
            "ABSOLUTE -> self-developing rational whole/subject, not a static supernatural thing.",
            "ANSWER LINE -> Hegel transforms Kantian limits into internally mediated relations.",
        ],
    },
    {
        "title": "Determinate negation, sublation and the opening logical movement",
        "structural_type": "sublation-triad-and-negation-spiral",
        "sessions": [2],
        "lines": [
            "DIALECTIC -> immanent self-movement through an internally generated tension.",
            "CONTRADICTION -> opposed determinations within a claim, not licence for formal chaos.",
            "DETERMINATE NEGATION -> negation of THIS content yields a SPECIFIC successor.",
            "AUFHEBUNG / SUBLATION -> CANCEL one-sidedness + PRESERVE truth + ELEVATE result.",
            "NEGATION OF NEGATION -> mediated recovery, not return to untouched immediacy.",
            "PURE BEING -> no determination; therefore indistinguishable from PURE NOTHING.",
            "BEING <-> NOTHING -> their truth is the passing-over named BECOMING.",
            "BECOMING -> first richer determination; Being and Nothing survive as moments.",
            "TRANSITION IS LOGICAL -> no temporal sequence and no magic formula.",
            "T-A-S -> loose teaching shorthand, not Hegel's standard fixed algorithm.",
            "TEST -> every progression must be justified from the prior term's precise failure.",
        ],
    },
    {
        "title": "Concrete universal, finite reality and nested system architecture",
        "structural_type": "whole-moment-system-architecture",
        "sessions": [3],
        "lines": [
            "ABSTRACT UNIVERSAL -> gains unity by omitting difference; Hegel calls it one-sided.",
            "CONCRETE UNIVERSAL -> particularises itself and contains organised differences.",
            "FINITE ENTITIES/CATEGORIES -> real as moments, partial when treated in isolation.",
            "INTERNAL RELATIONS -> a moment's identity depends on mediated relations to others.",
            "'THE TRUE IS THE WHOLE' -> whole is RESULT of development, not ready-made totality.",
            "LOGIC -> Idea in-itself; Being -> Essence -> Concept.",
            "NATURE -> Idea in otherness; space, time, matter, life; not created later in time.",
            "SPIRIT -> Idea returned-to-itself through rational self-conscious life.",
            "SUBJECTIVE SPIRIT -> mind; OBJECTIVE SPIRIT -> right, morality, ethical life, history",
            "ABSOLUTE SPIRIT -> art -> religion -> philosophy as conceptual comprehension.",
            "ANSWER LINE -> the whole preserves finite difference while making it intelligible.",
        ],
    },
    {
        "title": "Recognition and the lordship-bondage dependence reversal",
        "structural_type": "recognition-dependence-loop",
        "sessions": [4],
        "lines": [
            "SELF-CONSCIOUSNESS -> requires recognition from another self-consciousness.",
            "ENCOUNTER -> each seeks certainty of itself through the other's acknowledgement.",
            "STRUGGLE -> one becomes LORD; the other becomes BONDMAN through fear of death.",
            "LORD'S FAILURE -> recognition from a devalued unfree other is worthless.",
            "LORD'S DEPENDENCE -> enjoyment relies on the bondsman's labour and mediation.",
            "BONDMAN'S FEAR -> disrupts attachment to immediate natural desire.",
            "SERVICE -> disciplines desire; LABOUR shapes an enduring independent object.",
            "BILDUNG -> the bondsman sees his own form in the worked world and forms himself.",
            "REVERSAL -> apparent independence is dependent; servitude becomes formative.",
            "LIMIT -> unequal recognition is conceptually unstable, not historically brief.",
            "ROLE -> bounded illustration of dialectic; Hegel is not reducible to this episode.",
        ],
    },
    {
        "title": "Phenomenological ladder from consciousness to reason and Spirit",
        "structural_type": "phenomenology-failure-ladder",
        "sessions": [5],
        "lines": [
            "GESTALT / SHAPE -> a criterion of knowing plus the object it claims to know.",
            "EXPERIENCE -> the object fails the shape's own criterion; both standard and object shift.",
            "CONSCIOUSNESS -> treats the object as independent; immediacy proves unstable.",
            "SELF-CONSCIOUSNESS -> discovers that another self and recognition are necessary.",
            "LORDSHIP-BONDAGE -> unequal recognition fails and freedom withdraws into thought.",
            "STOICISM -> abstract inner freedom; empty because indifferent to determinate content.",
            "SCEPTICISM -> dissolves content but lives as a determinate self: performative conflict.",
            "UNHAPPY CONSCIOUSNESS -> knows the split between changeable self and beyond.",
            "DEVOTION -> WORK -> MEDIATOR -> self-renunciation reverses into universality.",
            "REASON -> finds itself in reality; SPIRIT -> shared historical and social life.",
            "RULE -> transitions are logical immanent failures, not a literal world chronology.",
        ],
    },
    {
        "title": "Absolute Idealism, substance-as-subject and actuality",
        "structural_type": "substance-subject-actuality-split",
        "sessions": [6],
        "lines": [
            "ABSOLUTE IDEALISM -> reality intelligible as one internally related developing whole.",
            "ABSOLUTE AS RESULT -> whole becomes what it is through differentiation and return.",
            "SUBSTANCE ALSO AS SUBJECT -> unity is active, self-differentiating and self-knowing.",
            "THOUGHT AND BEING -> identity through mediation, not undifferentiated sameness.",
            "NATURE + FINITE MINDS -> real moments of the Absolute, not unreal illusions.",
            "PHENOMENAL WORLD -> mediated manifestation: real as moment, not ultimate alone.",
            "DASEIN / MERE EXISTENCE -> a fact may fail its concept or norm.",
            "WIRKLICHKEIT / ACTUALITY -> existence that has realised its rational concept.",
            "'ACTUAL IS RATIONAL' -> NOT 'whatever exists or every injustice is justified.'",
            "INSTITUTIONAL TEST -> does the form concretely realise freedom?",
            "RESIDUAL -> reconciliation can still slide into retrospective conservatism.",
        ],
    },
    {
        "title": "Kant-Hegel comparison: noumenal limit and immanent reason",
        "structural_type": "kant-hegel-comparison-and-limit-test",
        "sessions": [7],
        "lines": [
            "KANT -> forms/categories secure phenomena; thing-in-itself limits theoretical knowledge.",
            "HEGEL PRONG 1 -> the boundary of thought is itself a thought and relates both sides.",
            "HEGEL PRONG 2 -> 'thing-in-itself' uses being, negation and determinacy.",
            "HEGEL PRONG 3 -> noumenal affection applies relation/causality beyond experience.",
            "RESULT -> fixed subject/object dualism is unstable and must be internally mediated.",
            "KANT'S REPLY -> noumenon is a negative limiting concept, not positive knowledge.",
            "HEGEL'S REJOINDER -> externally imposed limits remain dogmatic unless self-generated.",
            "KANT -> critical restraint; HEGEL -> reason develops its own criteria and limits.",
            "KANT -> phenomenal objectivity; HEGEL -> identity-in-difference of thought and being.",
            "VERDICT -> Hegel pressures positive noumenal causation more than he proves totality.",
            "ANSWER RULE -> present both systems accurately before ruling.",
        ],
    },
    {
        "title": "Logic-Nature seam: free release, contingency and objections",
        "structural_type": "logic-nature-seam-objection-stack",
        "sessions": [8],
        "lines": [
            "LOGIC -> Being -> Essence -> Concept -> Absolute Idea under claimed necessity.",
            "QUESTION -> how can pure categories be followed by existing contingent nature?",
            "'FREE RELEASE' -> Absolute Idea relates to itself as externality.",
            "NATURE -> Idea in otherness; NOT later in time, NOT caused by a thinking agent.",
            "IMPOTENCE OF NATURE -> externality cannot perfectly hold the Concept.",
            "CONSEQUENCE -> contingency and imprecision; no deduction of every natural fact.",
            "SCHELLING -> logic gives what existence must be, not THAT anything exists.",
            "TRENDELENBURG -> movement is smuggled into static categories.",
            "FEUERBACH -> disguised creation theology; ANALYTIC -> personification, no proof.",
            "REPLY -> conceptual instability is non-spatial and non-temporal self-undermining.",
            "VERDICT -> coherent within the system, but not strictly demonstrative to every critic.",
        ],
    },
    {
        "title": "Objective Spirit, institutional freedom and historical development",
        "structural_type": "freedom-institution-history-rail",
        "sessions": [9],
        "lines": [
            "FREEDOM -> being at home with oneself in an other, not arbitrary absence of limits.",
            "SUBJECTIVE WILL -> choice remains abstract without recognition and stable norms.",
            "ABSTRACT RIGHT -> persons and property; MORALITY -> intention and conscience",
            "ETHICAL LIFE -> family, civil society and constitutional institutions.",
            "OBJECTIVE SPIRIT -> freedom becomes durable, public and mutually recognisable.",
            "HISTORY -> development of consciousness that freedom belongs in principle to all.",
            "ONE FREE -> SOME FREE -> ALL FREE IN PRINCIPLE is Hegel's broad sequence.",
            "INTERNAL CONTRADICTION -> a society fails its own norm, such as freedom with slavery.",
            "CUNNING OF REASON -> passions produce outcomes beyond agents' intentions.",
            "CRITIQUE -> Eurocentrism, retrospective necessity, conservatism and material exclusion.",
            "DEFENSIBLE RESIDUE -> institutions can be criticised by their own norm of freedom.",
        ],
    },
    {
        "title": "Comparison, criticism-reply map and complete answer spine",
        "structural_type": "criticism-reply-answer-spine",
        "sessions": [10],
        "lines": [
            "SUBJECTIVE IDEALISM -> finite mind/ideas; OBJECTIVE -> mind-independent ideal order.",
            "ABSOLUTE IDEALISM -> finite subject and object are moments of one developing whole.",
            "KIERKEGAARD -> system loses existing individual; reply: finite is preserved as moment.",
            "MARX -> idealist inversion/material relations; bounded link keeps dialectical change.",
            "SCHOPENHAUER/ANALYTIC -> obscurity, contradiction and unproved transitions.",
            "REPLY -> determinate negation demands a specific successor, not arbitrary synthesis.",
            "POLITICAL OBJECTION -> actuality excuses power; reply: Wirklichkeit != mere existence.",
            "STRENGTH -> immanent critique, mediation, recognition and internal relations.",
            "TENSION -> retrospective coherence may fall short of demonstrative necessity.",
            "PYQS -> 2019 truth; 2020 phenomenal world; 2021/22 method-Absolute; 2023 history;",
            "PYQ -> 2025 Kant challenge; practice -> 36 MCQs + solved 10/15/20-mark originals.",
            "ANSWER SPINE -> thesis -> terms -> transition -> example -> objection/reply -> verdict.",
        ],
    },
)


REQUIRED_CORE_TERMS = (
    "dialectic",
    "immanent critique",
    "contradiction",
    "determinate negation",
    "Aufhebung",
    "sublation",
    "negation of negation",
    "mediated immediacy",
    "speculative",
    "concrete universal",
    "identity-in-difference",
    "recognition",
    "Absolute",
    "substance",
    "subject",
    "Wirklichkeit",
    "actuality",
    "Dasein",
    "Absolute Spirit",
    "Logic",
    "Nature",
    "Spirit",
    "Subjective Spirit",
    "Objective Spirit",
    "Being",
    "Nothing",
    "Becoming",
    "thesis-antithesis-synthesis",
    "thing-in-itself",
    "rational institutions",
)
