"""Durable learner-v2 content and master-flow specification for topic 06."""

from __future__ import annotations


def visual(title: str, caption: str, *lines: str) -> dict[str, object]:
    return {"title": title, "caption": caption, "lines": list(lines)}


def session(
    title: str,
    plain: str,
    technical: str,
    answer: str,
    keywords: list[str],
    usage: str,
    mechanism: str,
    consequence: str,
    trap: str,
    objection: str,
    reply: str,
    limit: str,
    exam: str,
    revision: list[str],
    visuals: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "title": title,
        "plain": plain,
        "technical": technical,
        "answer": answer,
        "keywords": keywords,
        "usage": usage,
        "mechanism": mechanism,
        "consequence": consequence,
        "trap": trap,
        "objection": objection,
        "reply": reply,
        "limit": limit,
        "exam": exam,
        "revision": revision,
        "visuals": visuals,
    }


SESSION_SPECS = (
    session(
        "The Analytic Turn: Three Programmes, One Revolt",
        "Moore, Russell and the early Wittgenstein all replace large speculative systems with analysis, but they analyse for different purposes.",
        "The early analytic movement rejects the British-idealist tendency to subordinate ordinary judgement to an all-embracing system: Moore protects common-sense propositions, Russell uncovers logical form and constructs problematic entities from safer bases, and the early Wittgenstein specifies the conditions and limits of meaningful representation.",
        "The unity of the analytic revolt lies in its demand for clarity, while its internal diversity lies in Moore's epistemic particularism, Russell's reductive logical analysis and Wittgenstein's transcendental delimitation of representation.",
        [
            "analytic revolt",
            "British idealism",
            "common-sense propositions",
            "logical analysis",
            "logical form",
            "limits of representation",
        ],
        "Open with the analytic revolt against British idealism, then map common-sense propositions -> logical analysis and logical form -> limits of representation.",
        "Speculative whole -> Moore tests it against what is better known -> Russell rewrites misleading grammar -> Wittgenstein asks what any proposition must share with a possible fact.",
        "Analysis becomes a family of methods rather than a single doctrine: epistemic defence, logical reconstruction and delimitation of sense.",
        "Do not collapse the trio into logical atomism, ordinary-language philosophy or logical positivism.",
        "The label 'analytic philosophy' may hide major disagreements about ontology, epistemology and the status of metaphysics.",
        "The shared movement is methodological rather than doctrinal: all three oppose obscurity and expose hidden structure without endorsing one identical theory.",
        "The comparison remains bounded because Moore does not accept the Tractarian limit of language and Wittgenstein does not ground simples in Russellian acquaintance.",
        "Use a three-column route: common sense -> logical form/construction -> representation/say-show, followed by one line on their common anti-idealist direction.",
        [
            "Moore asks what we know more certainly than a philosophical theory.",
            "Russell asks what a sentence really commits us to after logical analysis.",
            "Early Wittgenstein asks what makes representation possible and where saying ends.",
        ],
        [
            visual(
                "Three-stage analytic shift",
                "The common movement has three distinct destinations rather than one doctrine.",
                "SPECULATIVE IDEALIST SYSTEM",
                "             | revolt through analysis",
                "             v",
                "MOORE -> protect COMMON-SENSE KNOWLEDGE",
                "             | sharpen logical method",
                "             v",
                "RUSSELL -> reveal LOGICAL FORM and CONSTRUCT entities",
                "             | ask what representation presupposes",
                "             v",
                "EARLY WITTGENSTEIN -> delimit SAYING by what logical form SHOWS",
            ),
            visual(
                "Question-method-success matrix",
                "Each philosopher's method must be judged by the problem it is designed to solve.",
                "MOORE | Question: what is more certain? | Method: common sense + distinctions",
                "       | Success: idealist/sceptical argument loses priority",
                "RUSSELL| Question: what is the real logical form?",
                "       | Method: analysis + contextual definition | Success: lean ontology",
                "EARLY W.| Question: how can a proposition represent?",
                "       | Method: picture/truth-function boundary | Success: limits of sense",
            ),
        ],
    ),
    session(
        "Moore's Common Sense and the External-World Proof",
        "Moore argues that ordinary propositions such as 'I have a body' are often more certain than the philosophical premises used to deny them.",
        "Moorean common-sense realism distinguishes knowing a common-sense proposition from possessing its complete philosophical analysis; 'A Defence of Common Sense' lists qualified truisms about body, earth, other persons and temporal existence, while 'Proof of an External World' offers hands as known premises satisfying Moore's conditions for proof.",
        "Moore's hands prove an external world only if their premises are already known, so the argument forcefully compares certainties without supplying the sceptic an independent criterion of knowledge.",
        [
            "common-sense propositions",
            "A Defence of Common Sense",
            "external world",
            "knowing versus analysing",
            "standards of proof",
            "Moorean certainty",
        ],
        "Separate A Defence of Common Sense from the external-world proof, use knowing versus analysing, and test Moorean certainty against the standards of proof.",
        "Known hand-premises + premises distinct from conclusion + valid entailment -> at least two external objects -> an external world exists.",
        "Moore reverses the burden of proof: a sceptical premise must be more certain than the ordinary proposition it overturns.",
        "Do not say the hands proof completely answers dreams, brains-in-vats or every criterion-of-knowledge challenge.",
        "The sceptic charges question-begging because the disputed claim that Moore knows the premises is simply asserted.",
        "Moore replies that a proof need not prove every premise and that he knows the hands more certainly than any sceptical premise used against them.",
        "The reply secures Moorean entitlement within ordinary inquiry but may not persuade a sceptic who demands a non-question-begging criterion.",
        "Write: truisms -> knowing/analysis distinction -> hands proof -> three conditions -> sceptical objection -> Moorean burden-shift -> residual limit.",
        [
            "The common-sense list is not the single claim that everyone explicitly believes every truism.",
            "Knowing that one has a body need not wait for a complete analysis of 'body' or 'material object'.",
            "Formal proof and dialectical conversion are different standards of success.",
        ],
        [
            visual(
                "Common-sense knowledge and philosophical analysis",
                "Difficulty in analysing a proposition does not by itself cancel knowledge of it.",
                "LEVEL 1: KNOWING THAT P",
                "I have a body | the earth existed before this moment | other persons exist",
                "             | can be certain while",
                "             v",
                "LEVEL 2: ANALYSING P",
                "What is a body? material object? memory? time? other mind?",
                "             |",
                "             v",
                "ANALYTICAL DIFFICULTY != LOSS OF ORDINARY KNOWLEDGE",
            ),
            visual(
                "Hands proof, objection and reply",
                "The valid inference is not the same as a complete defeat of scepticism.",
                "P1 HERE IS ONE HAND + P2 HERE IS ANOTHER",
                "        | distinct premises + known premises + valid consequence",
                "        v",
                "AT LEAST TWO EXTERNAL OBJECTS -> EXTERNAL WORLD EXISTS",
                "        |",
                "SCEPTIC: you have assumed the disputed knowledge",
                "        |",
                "MOORE: the hand-premises are more certain than your denial",
                "        |",
                "RESIDUAL: certainty comparison does not supply a neutral criterion",
            ),
        ],
    ),
    session(
        "Moore's Refutation of Idealism: Awareness and Object",
        "Moore argues that experiencing blue contains both awareness and the blue presented, even though attention naturally passes through awareness to its object.",
        "In 'The Refutation of Idealism' Moore attacks the equation esse est percipi by distinguishing the act or consciousness of awareness from its object; the transparency or diaphanous character of sensation explains why awareness is easily overlooked without making it identical with blue, green or any other presented quality.",
        "Moore's decisive point is not that every idealism has been disproved, but that the object of awareness cannot simply be identified with awareness merely because consciousness is transparent to introspection.",
        [
            "esse est percipi",
            "object of awareness",
            "act of awareness",
            "transparency of sensation",
            "diaphanous consciousness",
            "Refutation of Idealism",
        ],
        "Quote or paraphrase the blue-green contrast, draw the act/object distinction, explain transparency, and state the argument's deliberately narrower anti-idealist result.",
        "Blue-awareness and green-awareness share awareness but differ in presented object -> common act and variable object are distinguishable -> esse cannot mean percipi by identity.",
        "The analysis blocks a direct move from the inseparability of awareness and object-in-experience to their identity or the object's mind-dependence.",
        "Do not claim Moore destroys Berkeley's entire philosophy or proves a complete direct-realist theory of perception.",
        "Critics argue that introspective attention reveals only the presented quality, so Moore has not established a separately discriminable act.",
        "Moore replies that transparency explains the elusiveness: awareness is common across distinct sensations and is noticed through its directed relation to different objects.",
        "Distinguishability in analysis does not by itself prove that every object exists unperceived or settle disputes about intentionality and sense-data.",
        "Answer in five moves: target -> blue/green example -> act/object distinction -> transparency -> narrow result, objection and limit.",
        [
            "The target is the identity claim linking existence with being perceived.",
            "Blue and green are different objects; awareness is the common relational element.",
            "The argument refutes an idealist route, not every premise of Berkeley or Hegel.",
        ],
        [
            visual(
                "Awareness-object distinction",
                "Different objects can be presented through the common relation of awareness.",
                "SENSATION OF BLUE              SENSATION OF GREEN",
                "AWARENESS -----> BLUE          AWARENESS -----> GREEN",
                "    |                              |",
                "    +------ COMMON RELATION -------+",
                "                    | objects differ",
                "                    v",
                "AWARENESS != BLUE and AWARENESS != GREEN",
            ),
            visual(
                "Transparency and the limited conclusion",
                "Transparency explains the temptation to identify consciousness with its object.",
                "INTROSPECTION",
                "    | attention passes THROUGH awareness",
                "    v",
                "PRESENTED OBJECT: blue / green / sound",
                "    | IDEALIST INFERENCE: only the object is found, so object = awareness",
                "    v",
                "MOORE: diaphanous awareness is overlooked, not identical",
                "RESULT: esse est percipi is not established by this conflation",
            ),
        ],
    ),
    session(
        "Russell's Analytic Programme and Logical Atomism",
        "Russell treats a sentence's grammar as a first draft: logical analysis may reveal a very different structure and a leaner world.",
        "Russellian logical atomism holds that the world is composed of facts rather than a mere inventory of things; particulars and universals or relations combine in atomic facts represented by atomic propositions, while molecular propositions are truth-functional constructions whose analysis should terminate in logical, not physical, simples.",
        "Russell's atomism is a conditional metaphysics of analysis: if a logically perfect language reaches independent atomic propositions, reality must contain corresponding atomic facts rather than microscopic physical particles.",
        [
            "logical analysis",
            "grammatical form",
            "logical form",
            "logical atomism",
            "atomic fact",
            "atomic proposition",
        ],
        "Begin with grammatical form versus logical form, define logical atomism through atomic fact and atomic proposition, then qualify molecular truth-functions and independence.",
        "Misleading surface sentence -> logical analysis -> atomic proposition with constituents -> corresponding fact when true -> molecular truth-functions built from atomic bases.",
        "Analysis exposes ontological commitment and explains why the world's basic units are fact-structures rather than isolated objects.",
        "Do not interpret logical atoms as tiny material particles or treat every ordinary sentence as already atomic.",
        "The programme never securely identifies a final logically perfect language or an uncontested stock of atomic facts.",
        "Russell can defend atomism as a regulative direction of analysis and as an explanation of how complex truth depends on simpler constituents.",
        "The defence makes the method valuable even if strict logical independence, private sense-data and final simples remain disputed.",
        "Use: analytic programme -> facts not things -> atomic correspondence -> molecular truth-functions -> independence qualification -> method survives stronger ontology.",
        [
            "A fact is an obtaining complex, not another thing alongside its constituents.",
            "An atomic proposition contains no truth-functional connective, but may include a relation.",
            "Logical simplicity concerns analysability, not physical size.",
        ],
        [
            visual(
                "Grammatical form versus logical form",
                "Logical analysis can remove an apparent subject and reveal quantified structure.",
                "GRAMMAR: 'The F is G' looks like SUBJECT + PREDICATE",
                "                | logical analysis",
                "                v",
                "LOGIC: EXISTENCE + UNIQUENESS + PREDICATION",
                "                |",
                "                v",
                "ONTOLOGY: no mysterious object is required merely by grammar",
            ),
            visual(
                "Fact and atomic proposition",
                "Correspondence relates structured proposition and structured obtaining fact.",
                "WORLD SIDE                       LANGUAGE SIDE",
                "particular a + relation R + b    name a + predicate R + name b",
                "              | combine                         | combine",
                "              v                                 v",
                "ATOMIC FACT: R(a,b)   <---- true iff ---- ATOMIC PROPOSITION",
                "              |                                 |",
                "obtains or fails                    true-functional molecules",
            ),
        ],
    ),
    session(
        "Acquaintance and Description: Russell's Epistemic Constraint",
        "Russell distinguishes direct presentation from indirect knowledge of an item as the unique thing satisfying a description.",
        "Knowledge by acquaintance is direct, non-inferential awareness of a constituent, whereas knowledge by description is propositional knowledge of the unique satisfier of a denoting phrase; the Principle of Acquaintance motivates analysis because an understood proposition must ultimately be composed of constituents with which the thinker is acquainted.",
        "The acquaintance-description distinction explains why Russell analyses ordinary names and descriptions: logical form must let us speak of Bismarck or an electron without making an unacquainted object a constituent of our thought.",
        [
            "acquaintance",
            "description",
            "Principle of Acquaintance",
            "logically proper name",
            "denoting phrase",
            "sense-data",
        ],
        "Define acquaintance and description, connect the Principle of Acquaintance to logically proper names and denoting phrases, then qualify the sense-data basis.",
        "Direct acquaintance supplies constituents -> descriptions quantify over a unique satisfier -> the described object disappears as a constituent -> understanding remains grounded in acquainted universals/data.",
        "Russell joins epistemology and logic: contextual analysis pays the epistemic debt created by discourse about what we have never met.",
        "Do not say a description is a weaker psychological image of an object or that every ordinary proper name is unquestionably a logically proper name.",
        "Private acquaintance and sense-data may not provide a public or conceptually neutral foundation for knowledge.",
        "Russell replies that acquaintance is presentation rather than a judgement and that description permits public propositions without direct presentation of their subject.",
        "The reply preserves the logical distinction but leaves the justificatory role of private givenness and the status of ordinary names contested.",
        "Draw two routes to the same subject: direct presentation versus unique-description analysis, then state why the second route needs the description theory.",
        [
            "Acquaintance concerns direct access to a constituent; description concerns truths identifying a satisfier.",
            "The description theory is not an isolated semantic trick but a device protecting the epistemology.",
            "Kripke pressures the description theory of ordinary names without destroying quantificational descriptions.",
        ],
        [
            visual(
                "Two epistemic routes",
                "Direct and indirect routes differ in logical structure, not merely vividness.",
                "ACQUAINTANCE                       DESCRIPTION",
                "direct presentation               'the unique F is G'",
                "no inference                       existence + uniqueness + predicate",
                "this sense-datum / universal       Bismarck / physical object / electron",
                "        |                                  |",
                "logically proper name              denoting phrase analysed in context",
            ),
            visual(
                "Why descriptions protect acquaintance",
                "The described object need not occur as an unacquainted constituent.",
                "I UNDERSTAND: 'The first Chancellor of the German Empire was diplomatic'",
                "             | but I am not acquainted with Bismarck",
                "             v",
                "ANALYSE DESCRIPTION -> there exists exactly one F, and that F is G",
                "             |",
                "             v",
                "CONSTITUENTS: logical apparatus + acquainted universals",
                "BISMARCK AS APPARENT CONSTITUENT DISAPPEARS",
            ),
        ],
    ),
    session(
        "Logical Constructions and Inferred Entities",
        "Russell prefers building a structure from less problematic data to postulating an extra entity merely because ordinary language names it.",
        "The maxim 'wherever possible, logical constructions are to be substituted for inferred entities' recommends contextual reconstruction of discourse about physical objects, numbers, classes or points from a more secure base; a logical construction is the structured replacement, an inferred entity is the avoided posit, and a logical fiction is useful shorthand rather than a separately denoting object.",
        "Russell's maxim is best read as disciplined ontological economy: construction replaces commitment to an inferred entity without making ordinary object-talk simply false or imaginary.",
        [
            "logical construction",
            "inferred entity",
            "logical fiction",
            "ontological economy",
            "contextual reconstruction",
            "sense-data construction",
        ],
        "State the maxim accurately, draw the replacement mechanism, give locally supported examples, and distinguish construction from atom, fiction and description.",
        "Questionable X -> identify truths involving X -> translate them into relations among safer data -> preserve explanatory work -> avoid X as an additional primitive.",
        "The method turns Occam's razor into a constructive programme and links ontology to the analysis of whole propositions.",
        "Do not say a logical construction is an atom, a hallucination, a mere falsehood or automatically identical with one definite description.",
        "Phenomenal constructions from actual and possible sense-data may be circular, private or insufficient for enduring public objects.",
        "Russell can answer that the maxim is methodological and wherever-possible, not a dogmatic claim that every scientific object has already been reduced.",
        "The weaker methodological reading survives better than a complete phenomenalist reduction of the physical world.",
        "Use a four-box distinction: atom/basic constituent; construction/derived structure; inferred entity/avoided posit; fiction/contextual shorthand.",
        [
            "Construction preserves the work of object-talk while altering its ontological analysis.",
            "Numbers and points are safer illustrations than claiming a finished reduction of every physical object.",
            "The maxim is explicitly qualified by 'wherever possible'.",
        ],
        [
            visual(
                "Construction versus inferred entity",
                "The replacement preserves explanatory relations while reducing primitive commitments.",
                "OLD ROUTE: appearances/data ---- inference ----> UNKNOWN ENTITY X",
                "                         | Russell's maxim rejects when avoidable",
                "                         v",
                "NEW ROUTE: DEFINE X-TALK AS A STRUCTURE OF KNOWN/SAFER ENTITIES",
                "                         |",
                "                         v",
                "SAME EXPLANATORY WORK, FEWER PRIMITIVE POSITS",
            ),
            visual(
                "Four notions kept distinct",
                "These expressions overlap in use but answer different questions.",
                "LOGICAL ATOM       = basic residue of analysis",
                "LOGICAL CONSTRUCTION= derived structure replacing an inferred entity",
                "INFERRED ENTITY    = extra posit the construction seeks to avoid",
                "LOGICAL FICTION    = convenient expression with no extra denoted object",
                "DEFINITE DESCRIPTION= one contextual-analysis mechanism, not the whole class",
            ),
        ],
    ),
    session(
        "Incomplete Symbols and the Theory of Descriptions",
        "A definite description contributes to a sentence without standing for an object on its own; analysis replaces it with a quantified claim.",
        "An incomplete symbol has no standalone denotation or independently assigned meaning but is defined contextually within propositions; Russell's theory of descriptions analyses 'the F is G' into existence, uniqueness and predication, with scope determining whether negation applies to the description or the whole quantified claim.",
        "The theory of descriptions shows that a grammatically complete subject can be logically incomplete, because its contribution is exhausted by a contextual definition of the proposition in which it occurs.",
        [
            "incomplete symbol",
            "contextual definition",
            "definite description",
            "existence",
            "uniqueness",
            "scope",
        ],
        "Define incomplete symbol and contextual definition, stage definite description through existence, uniqueness and scope, then distinguish denotation from contextual contribution.",
        "Surface 'the F is G' -> assert at least one F -> assert at most one F -> predicate G of that F -> evaluate the conjunction and its scope.",
        "Descriptions disappear as apparent constituents, solve negative-existential and identity puzzles, and reveal ontological commitment through quantification.",
        "Do not say the non-denoting description makes the whole sentence meaningless or denotes a shadowy non-existent object.",
        "Strawson argues that ordinary utterance presupposes rather than asserts the existence of the present King of France.",
        "Russell can reply that his logical analysis explains truth conditions and commitment even if conversational presupposition adds a pragmatic layer.",
        "The quantificational logic remains powerful, while its claim to capture every feature of ordinary referring practice is limited.",
        "Write the three stages in words, then one compact formula with a legend, followed by scope and Strawson's objection.",
        [
            "No standalone denotation does not mean no systematic contribution to sentence meaning.",
            "The present-King sentence is false on Russell's standard analysis because existence fails.",
            "Wide and narrow scope can change the truth value of a negated description sentence.",
        ],
        [
            visual(
                "Contextual-definition mechanism",
                "The apparent term disappears when the entire proposition is analysed.",
                "ISOLATED PHRASE: 'the present King of France' -> no standalone denotation",
                "                         | place inside a complete proposition",
                "                         v",
                "'The present King of France is bald'",
                "                         | contextual definition",
                "                         v",
                "EXISTENCE + UNIQUENESS + BALDNESS",
                "NO KING-LIKE OBJECT REMAINS AS A LOGICAL SUBJECT",
            ),
            visual(
                "Definite description in three readable stages",
                "The legend keeps the formal line attached to its three claims.",
                "STAGE 1 EXISTENCE: at least one x is presently King of France",
                "STAGE 2 UNIQUENESS: every y that is King of France is identical with x",
                "STAGE 3 PREDICATION: x is bald",
                "COMBINE: exists x [Kx AND every y(Ky -> y=x) AND Bx]",
                "LEGEND: K = present King of France | B = bald",
                "VERDICT: existence is false -> whole conjunction is false",
            ),
        ],
    ),
    session(
        "Early Wittgenstein: Facts, States of Affairs and Picture Theory",
        "The early Wittgenstein says language represents reality because the arrangement of names can model a possible arrangement of objects.",
        "In the Tractatus the world is the totality of facts, not things: simple objects combine into possible states of affairs, an obtaining state of affairs is a fact, names correspond to objects, and an elementary proposition represents a possible state of affairs by sharing logical form rather than visual resemblance.",
        "A Tractarian proposition pictures reality not by looking like it, but because names and objects possess a common possibility of arrangement that permits the proposition to be compared with how things stand.",
        [
            "object",
            "state of affairs",
            "obtaining fact",
            "name",
            "elementary proposition",
            "picture theory",
        ],
        "Build object -> state of affairs -> obtaining fact and name -> elementary proposition -> picture theory, joined by shared logical form.",
        "Objects combine possibly -> state of affairs; if it obtains -> fact. Names combine -> elementary proposition; shared logical form makes it a picture whose truth depends on reality.",
        "Sense belongs to a proposition representing a possible situation; both a true and a false proposition can have sense.",
        "Do not equate picture with mental image, diagram or visual resemblance, and do not import later meaning-as-use or language-games.",
        "Wittgenstein never gives an uncontested example of a simple object or a fully analysed elementary proposition.",
        "He replies at the transcendental level: determinate sense requires a stable substance and elementary base even if ordinary language conceals them.",
        "The necessity argument explains the role of simples but does not identify them or prove that actual analysis reaches them.",
        "Use a dual ladder: object -> state of affairs -> fact and name -> elementary proposition -> true/false picture, joined by logical form.",
        [
            "A state of affairs is possible; a fact is an obtaining state of affairs.",
            "Names correspond to objects, while propositions picture configurations rather than name facts.",
            "Truth is comparison with reality; sense is prior possession of truth-conditions.",
        ],
        [
            visual(
                "World and language architecture",
                "The two sides have corresponding elements and combinatorial structure.",
                "WORLD SIDE                         LANGUAGE SIDE",
                "OBJECTS                            NAMES",
                "   | possible combination            | syntactic combination",
                "   v                                 v",
                "STATE OF AFFAIRS  <--- logical ---> ELEMENTARY PROPOSITION",
                "   | obtains                         | agrees with reality",
                "   v                                 v",
                "FACT                                TRUE PROPOSITION",
            ),
            visual(
                "Picture Theory mapping",
                "Representation depends on common logical possibility, not sensory likeness.",
                "PROPOSITION: name-a ---- relation-R ---- name-b",
                "                    | correspondence",
                "REALITY:     object-a -- possible-R -- object-b",
                "                    |",
                "SHARED LOGICAL FORM = possibility of the same arrangement",
                "TRUE  -> pictured state obtains",
                "FALSE -> pictured state does not obtain, but remains possible and meaningful",
            ),
        ],
    ),
    session(
        "Sense, Truth-Functions and the Limits of Elementary Propositions",
        "Complex propositions are built from elementary propositions by truth-operations, while logic displays possibilities without describing an additional fact.",
        "A proposition has sense by determining truth-conditions in logical space; complex propositions are truth-functions of elementary propositions, logical constants do not name objects, and tautologies and contradictions are limiting cases that are senseless in the technical sense because they say nothing contingent, not ordinary gibberish.",
        "The Tractarian economy makes logical form the scaffolding of representation: truth-functions combine possible pictures without adding logical objects to the world.",
        [
            "sense",
            "truth-conditions",
            "truth-function",
            "elementary proposition",
            "tautology",
            "contradiction",
        ],
        "Distinguish sense and truth-conditions, construct a truth-function from elementary propositions, then separate tautology, contradiction and nonsense.",
        "Elementary p and q -> truth-operation selects combinations of truth-values -> complex proposition; logical connective changes conditions, not worldly constituents.",
        "Logic shows the formal possibilities shared by world and language and therefore cannot describe that form as one more contingent fact.",
        "Do not say a false proposition lacks sense, that tautologies are meaningless noise, or that elementary propositions have been concretely identified.",
        "Colour exclusion, belief contexts and modality challenge strict independence and universal truth-functionality.",
        "The Tractarian can treat the account as an ideal logical requirement and revise what counts as elementary rather than abandon the distinction immediately.",
        "The reply preserves the architecture only conditionally; the absence of specified elementary propositions and counterexamples weakens its completeness.",
        "Answer: sense/truth distinction -> elementary base -> truth-functional molecule -> logic shows form -> limiting cases -> independence objections.",
        [
            "A meaningful false proposition still pictures a possible state of affairs.",
            "Tautology and contradiction are well formed but describe no contingent arrangement.",
            "Logical constants operate on propositions; they do not stand for extra objects.",
        ],
        [
            visual(
                "Truth-functional construction",
                "Complex truth depends on component truth-values and the selected operation.",
                "ELEMENTARY p: a is red       ELEMENTARY q: b is round",
                "             \\                 /",
                "              \\ truth-operation",
                "               v",
                "MOLECULAR: p AND q | p OR q | NOT p | IF p THEN q",
                "               |",
                "NO EXTRA 'AND-OBJECT' IS ADDED TO THE WORLD",
            ),
            visual(
                "Sense and limiting cases",
                "Sense concerns possible truth and falsity, not actual truth alone.",
                "CONTINGENT PROPOSITION -> can be true or false -> HAS SENSE",
                "TAUTOLOGY              -> true under every assignment -> says nothing factual",
                "CONTRADICTION          -> false under every assignment -> says nothing factual",
                "PSEUDO-PROPOSITION     -> fails to picture a possible fact -> nonsense",
                "CAUTION: senseless logical limit != ungrammatical or trivial gibberish",
            ),
        ],
    ),
    session(
        "Saying and Showing, Criticism and the Comparative Answer Spine",
        "Facts can be stated, but the form that lets statements represent cannot itself be stated as one more fact; the Tractatus therefore ends by turning its own remarks into a ladder.",
        "Factual propositions say how things stand, whereas logical form, logical necessity and the limits of representation show themselves in meaningful symbolism; ethics, aesthetics and the mystical are not ordinary factual propositions, tautologies differ from nonsense, and the ladder metaphor marks the self-referential status of Tractarian elucidation.",
        "Saying and showing is the culmination and tension of the Tractatus: logical form cannot be represented without presupposing itself, yet the book must use elucidatory nonsense to lead the reader to that boundary.",
        [
            "saying and showing",
            "logical necessity",
            "limits of language",
            "ethics and the mystical",
            "nonsense",
            "ladder metaphor",
        ],
        "Derive saying and showing from logical necessity and limits of language, use the ladder metaphor, then classify ethics and the mystical before comparison.",
        "Proposition pictures a fact -> picturing presupposes logical form -> another proposition cannot picture that presupposition as a fact -> form is shown, not said -> elucidatory ladder is discarded.",
        "Wittgenstein delimits factual discourse without simply declaring ethics false; the method also exposes the book's self-referential vulnerability.",
        "Do not equate saying/showing with true/false, import the verification principle, or treat later language-games as the Tractatus solution.",
        "If the Tractatus's own remarks are nonsense, its distinction appears self-refuting and excessively excludes meaningful ethical, aesthetic or religious discourse.",
        "Wittgenstein openly anticipates the problem at 6.54: the remarks are elucidations to be used and discarded rather than factual theses competing with science.",
        "Calling self-undermining deliberate explains the method but leaves disagreement over whether illuminating nonsense can communicate what doctrine forbids.",
        "Close with comparison: Moore secures knowledge, Russell exposes/constructs form, Wittgenstein limits representation; add one criticism-reply for each.",
        [
            "Logical form is manifested by a proposition's working, not reported as another worldly fact.",
            "Ethics and the mystical are not rejected as false propositions; they lie outside factual saying.",
            "Logical positivism inherits anti-metaphysical pressure but adds verificationism not found as such in the Tractatus.",
        ],
        [
            visual(
                "Saying-showing boundary",
                "The boundary separates factual representation from its enabling form.",
                "CAN BE SAID: contingent facts -> propositions of natural science",
                "                         | every proposition presupposes",
                "                         v",
                "CAN ONLY BE SHOWN: logical form | logical necessity | limits of sense",
                "                         | not ordinary factual propositions",
                "ETHICS / AESTHETICS / MYSTICAL -> manifest value, not extra facts",
                "TRACTATUS REMARKS -> LADDER: use -> see boundary -> discard",
            ),
            visual(
                "Criticism-reply map and answer spine",
                "A high-scoring answer distinguishes success within a programme from residual limits.",
                "MOORE: begs question -> reply: compares certainties -> limit: neutral criterion",
                "RUSSELL: no final atoms/private base -> reply: analysis still clarifies commitment",
                "WITTGENSTEIN: no elementary examples/self-refutation",
                "             -> reply: transcendental role + ladder -> limit persists",
                "ANSWER SPINE: thesis -> define -> reconstruct -> example",
                "              -> objection/reply -> comparison -> graded verdict",
            ),
        ],
    ),
)


ASCII_PANELS = (
    {
        "title": "Analytic revolt and the distinct programmes of the trio",
        "structural_type": "three-programme-continuous-rail",
        "sessions": [1],
        "lines": [
            "START -> revolt against British idealist systems through disciplined analysis.",
            "COMMON DEMAND -> clarity, distinctions and refusal to let theory erase evident facts.",
            "MOORE -> protects common-sense propositions by comparing epistemic certainty.",
            "RUSSELL -> exposes logical form and replaces problematic entities by constructions.",
            "EARLY WITTGENSTEIN -> explains representation and draws the boundary of saying.",
            "UNITY -> analysis replaces speculative system-building as philosophy's main tool.",
            "DIFFERENCE -> epistemic defence | logical reduction | transcendental delimitation.",
            "NOT LOGICAL POSITIVISM -> verificationism is a later doctrine, not their common creed.",
            "NOT ONE ATOMISM -> Russell's acquaintance-based atoms differ from Tractarian objects.",
            "ANSWER LINE -> shared analytic direction does not erase distinct standards of success.",
        ],
    },
    {
        "title": "Moore's common-sense propositions and external-world proof",
        "structural_type": "certainty-proof-objection-reply-chain",
        "sessions": [2],
        "lines": [
            "1925 DEFENCE -> qualified truisms about body, earth, other persons and temporal life.",
            "KNOWING P != possessing a complete philosophical ANALYSIS of P.",
            "ANALYTICAL DIFFICULTY about body/material object does not cancel ordinary knowledge.",
            "1939 PROOF -> here is one hand + here is another -> external objects exist.",
            "PROOF TEST 1 -> premises differ from conclusion; TEST 2 -> premises are known.",
            "PROOF TEST 3 -> conclusion follows: hands are things met with in space.",
            "SCEPTIC -> you assume precisely what dream or deception scenarios place in doubt.",
            "MOORE -> hand-premises are more certain than any premise used to deny them.",
            "LIMIT -> formally valid proof does not provide a neutral criterion of knowledge.",
            "RESULT -> external-world proof shifts the burden; it is not total scepticism's end.",
        ],
    },
    {
        "title": "Moore's awareness-object distinction and transparency",
        "structural_type": "act-object-transparency-split",
        "sessions": [3],
        "lines": [
            "TARGET -> esse est percipi: the object's being is identified with being perceived.",
            "BLUE EXPERIENCE -> AWARENESS directed toward BLUE; green has the same relation.",
            "COMMON ELEMENT -> awareness/consciousness; VARIABLE ELEMENT -> presented object.",
            "THEREFORE -> awareness != blue and awareness != green.",
            "TRANSPARENCY / DIAPHANOUSNESS -> attention passes through awareness to its object.",
            "IDEALIST TEMPTATION -> because the act is elusive, identify sensation with its object.",
            "MOOREAN REPLY -> being overlooked does not make awareness identical with the object.",
            "NARROW RESULT -> the identity route from object to awareness is blocked.",
            "LIMIT -> distinguishability does not prove every object exists unperceived.",
            "BERKELEY CAUTION -> Moore does not refute Berkeley's entire philosophy in one stroke.",
        ],
    },
    {
        "title": "Russell's logical analysis, facts and atomic propositions",
        "structural_type": "grammar-logic-fact-correspondence-map",
        "sessions": [4],
        "lines": [
            "ANALYTIC PROGRAMME -> surface grammar may conceal the proposition's logical form.",
            "WORLD -> facts, not merely things; a fact is an obtaining structured complex.",
            "CONSTITUENTS -> particulars plus universals/relations combine in atomic facts.",
            "LANGUAGE -> names/predicates combine in atomic propositions without connectives.",
            "TRUE ATOMIC PROPOSITION <-> corresponding atomic fact obtains.",
            "MOLECULAR PROPOSITION -> truth-function of atomic propositions.",
            "LOGICAL INDEPENDENCE -> qualified ideal of the atomic base, not an easy empirical fact.",
            "ANALYSIS -> reaches simpler constituents; atoms are logical, not microscopic particles.",
            "LOGICALLY PERFECT LANGUAGE -> regulative model whose final vocabulary is disputed.",
            "VERDICT -> method clarifies commitment even if the final atomist ontology is unstable.",
        ],
    },
    {
        "title": "Acquaintance, description and the epistemic work of analysis",
        "structural_type": "two-route-epistemic-ladder",
        "sessions": [5],
        "lines": [
            "ACQUAINTANCE -> direct, presentational and non-inferential awareness of a constituent.",
            "DESCRIPTION -> indirect knowledge of the unique thing satisfying 'the F'.",
            "LOGICALLY PROPER NAME -> directly refers within acquaintance; ordinary names may not.",
            "DENOTING PHRASE -> analysed contextually rather than treated as a genuine name.",
            "PRINCIPLE -> understood propositions must reduce to acquainted constituents.",
            "BISMARCK ROUTE -> the first Chancellor of the German Empire, not direct acquaintance.",
            "DESCRIPTION THEORY -> removes Bismarck as an unacquainted logical constituent.",
            "PRIVATE-BASE OBJECTION -> sense-data may not ground public knowledge neutrally.",
            "KRIPKE LIMIT -> ordinary names need not be disguised descriptions.",
            "RESULT -> Russell's logical instrument outlives much of its original epistemology.",
        ],
    },
    {
        "title": "Logical constructions, inferred entities and logical fictions",
        "structural_type": "replacement-mechanism-and-distinction-matrix",
        "sessions": [6],
        "lines": [
            "MAXIM -> wherever possible, substitute logical constructions for inferred entities.",
            "OLD ROUTE -> data/appearances -> infer an additional unknown entity X.",
            "NEW ROUTE -> define X-talk as a structure of relations among safer entities.",
            "CONSTRUCTION -> derived structure preserving explanatory work.",
            "INFERRED ENTITY -> primitive posit avoided when a construction succeeds.",
            "LOGICAL FICTION -> useful contextual shorthand, not an additional denoted object.",
            "EXAMPLES -> physical objects/sense-data; numbers/classes; points/volumes, with caution.",
            "ATOM != CONSTRUCTION -> basic residue versus derived structure.",
            "OBJECTION -> private or possible sense-data may not reconstruct public endurance.",
            "LIMITED REPLY -> the wherever-possible maxim survives better than total reduction.",
        ],
    },
    {
        "title": "Incomplete symbols and definite-description analysis",
        "structural_type": "contextual-definition-quantifier-stages",
        "sessions": [7],
        "lines": [
            "INCOMPLETE SYMBOL -> no standalone denotation; defined only in proposition-context.",
            "DESCRIPTION -> 'the F' appears to name but disappears on logical analysis.",
            "STAGE 1 EXISTENCE -> at least one x is F.",
            "STAGE 2 UNIQUENESS -> every y that is F is identical with x.",
            "STAGE 3 PREDICATION -> that x is G.",
            "KING OF FRANCE -> existence fails, so the standard conjunction is false.",
            "GOLDEN MOUNTAIN -> no ghostly object; apparent subject is eliminated.",
            "SCOPE -> negation outside the whole claim differs from negating the predicate.",
            "STRAWSON -> ordinary use presupposes existence; Russell stresses truth conditions.",
            "RESULT -> grammatical completeness can conceal logical incompleteness.",
        ],
    },
    {
        "title": "Tractarian objects, states of affairs, facts and pictures",
        "structural_type": "world-language-dual-architecture",
        "sessions": [8],
        "lines": [
            "EARLY ONLY -> do not import later meaning-as-use, forms of life or language-games.",
            "WORLD -> totality of FACTS, not a mere list of things.",
            "OBJECTS -> simple combinatorial possibilities; their nature is not concretely specified.",
            "STATE OF AFFAIRS -> possible combination of objects; obtaining state -> FACT.",
            "NAME -> corresponds to object; names combine in an ELEMENTARY PROPOSITION.",
            "PROPOSITION -> pictures a possible state of affairs through shared LOGICAL FORM.",
            "PICTURE != VISUAL RESEMBLANCE -> medium may differ while possibility matches.",
            "TRUE -> pictured arrangement obtains; FALSE -> it does not, yet proposition has sense.",
            "SENSE -> possession of truth-conditions or a possible situation in logical space.",
            "LIMIT -> no uncontested examples of fully analysed elementary propositions are given.",
        ],
    },
    {
        "title": "Truth-functions, logical scaffolding and limiting cases",
        "structural_type": "truth-operation-and-sense-boundary",
        "sessions": [9],
        "lines": [
            "ELEMENTARY BASE -> propositions representing possible independent states of affairs.",
            "TRUTH-OPERATION -> builds complex propositions from truth-values of the base.",
            "MOLECULAR p AND q / p OR q / NOT p -> no extra logical object is represented.",
            "LOGICAL CONSTANTS -> operations, not names standing for entities.",
            "LOGIC -> shows the formal scaffolding of world and language; it states no facts.",
            "TAUTOLOGY -> always true, well formed, but says nothing contingent.",
            "CONTRADICTION -> always false, well formed, but says nothing contingent.",
            "NONSENSE -> fails to picture any possible fact; not identical with tautology.",
            "CRITICISM -> colour exclusion and belief contexts pressure independence/functionality.",
            "VERDICT -> architecture is powerful but its elementary base remains underspecified.",
        ],
    },
    {
        "title": "Saying-showing, comparative synthesis and answer spine",
        "structural_type": "boundary-criticism-answer-spine",
        "sessions": [10],
        "lines": [
            "SAYING -> factual propositions state how things contingently stand.",
            "SHOWING -> logical form, necessity and limits manifest in meaningful symbolism.",
            "ETHICS/AESTHETICS/MYSTICAL -> not ordinary facts and not simply dismissed as false.",
            "LADDER 6.54 -> use elucidatory remarks, see the boundary, then discard the rungs.",
            "SELF-REFERENCE -> the Tractatus's own remarks appear nonsensical by its criterion.",
            "REPLY -> self-consuming elucidation is deliberate; RESIDUAL -> communication remains hard.",
            "MOORE -> protect common-sense knowledge through analysis and certainty comparison.",
            "RUSSELL -> reveal logical form and construct/reduce problematic entities.",
            "EARLY WITTGENSTEIN -> delimit meaningful representation through say/show.",
            "POSITIVISM BOUND -> later verificationism must not be imported into the Tractatus.",
            "ANSWER SPINE -> thesis -> definitions -> argument -> example -> objection/reply -> verdict.",
        ],
    },
)


REQUIRED_CORE_TERMS = (
    "common-sense propositions",
    "external world",
    "transparency of sensation",
    "fact",
    "logical atomism",
    "acquaintance",
    "description",
    "logical construction",
    "inferred entity",
    "incomplete symbol",
    "contextual definition",
    "logical form",
    "state of affairs",
    "elementary proposition",
    "picture theory",
    "truth-function",
    "saying and showing",
    "Defence of Commonsense",
    "Refutation of Idealism",
    "Logical Constructions",
    "Incomplete Symbols",
    "Picture Theory of Meaning",
    "Sying and Showing",
)


GRAPHICAL_PILLS = (
    [
        {"text": "ANALYTIC REVOLT", "role": "primary"},
        {"text": "MOORE: COMMON-SENSE CERTAINTY", "role": "evidence"},
        {"text": "RUSSELL: LOGICAL FORM AND CONSTRUCTION", "role": "outcome"},
        {"text": "EARLY WITTGENSTEIN: LIMITS OF REPRESENTATION", "role": "comparison"},
        {"text": "SHARED METHOD, DISTINCT PROGRAMMES", "role": "caution"},
        {"text": "NOT A SINGLE ATOMISM OR POSITIVISM", "role": "comparison"},
    ],
    [
        {"text": "1925: QUALIFIED COMMON-SENSE TRUISMS", "role": "primary"},
        {"text": "KNOWING P != COMPLETE ANALYSIS OF P", "role": "comparison"},
        {"text": "1939: HERE IS ONE HAND; HERE IS ANOTHER", "role": "evidence"},
        {"text": "PREMISES KNOWN AND DISTINCT", "role": "outcome"},
        {"text": "VALID PROOF != NEUTRAL SCEPTICAL CRITERION", "role": "caution"},
    ],
    [
        {"text": "ESSE EST PERCIPI TARGETED", "role": "primary"},
        {"text": "AWARENESS != PRESENTED OBJECT", "role": "comparison"},
        {"text": "BLUE AND GREEN: OBJECTS DIFFER", "role": "evidence"},
        {"text": "CONSCIOUSNESS: COMMON RELATION", "role": "outcome"},
        {"text": "TRANSPARENCY EXPLAINS THE CONFLATION", "role": "caution"},
    ],
    [
        {"text": "GRAMMATICAL FORM != LOGICAL FORM", "role": "primary"},
        {"text": "WORLD AS OBTAINING FACTS", "role": "evidence"},
        {"text": "PARTICULARS + UNIVERSALS/RELATIONS", "role": "comparison"},
        {"text": "ATOMIC FACT <-> ATOMIC PROPOSITION", "role": "outcome"},
        {"text": "LOGICAL, NOT PHYSICAL, ATOMS", "role": "caution"},
    ],
    [
        {"text": "ACQUAINTANCE: DIRECT PRESENTATION", "role": "primary"},
        {"text": "DESCRIPTION: UNIQUE SATISFIER", "role": "comparison"},
        {"text": "PRINCIPLE OF ACQUAINTANCE", "role": "evidence"},
        {"text": "LOGICALLY PROPER NAME", "role": "outcome"},
        {"text": "DESCRIPTION THEORY REMOVES APPARENT SUBJECT", "role": "caution"},
    ],
    [
        {"text": "CONSTRUCTION REPLACES INFERRED ENTITY", "role": "primary"},
        {"text": "DERIVED STRUCTURE, NOT BASIC ATOM", "role": "comparison"},
        {"text": "LOGICAL FICTION: CONTEXTUAL SHORTHAND", "role": "evidence"},
        {"text": "WHEREVER POSSIBLE: QUALIFIED MAXIM", "role": "outcome"},
        {"text": "ONTOLOGICAL ECONOMY, NOT IMAGINARY OBJECTS", "role": "caution"},
    ],
    [
        {"text": "INCOMPLETE SYMBOL: NO STANDALONE DENOTATION", "role": "primary"},
        {"text": "CONTEXTUAL DEFINITION OF THE WHOLE SENTENCE", "role": "comparison"},
        {"text": "EXISTENCE + UNIQUENESS + PREDICATION", "role": "evidence"},
        {"text": "KING OF FRANCE: CONJUNCTION FALSE", "role": "outcome"},
        {"text": "SCOPE CHANGES NEGATION", "role": "caution"},
    ],
    [
        {"text": "EARLY WITTGENSTEIN ONLY", "role": "caution"},
        {"text": "OBJECT -> STATE OF AFFAIRS -> FACT", "role": "primary"},
        {"text": "NAME -> ELEMENTARY PROPOSITION", "role": "comparison"},
        {"text": "SHARED LOGICAL FORM", "role": "evidence"},
        {"text": "PICTURE != VISUAL RESEMBLANCE", "role": "outcome"},
    ],
    [
        {"text": "SENSE AS TRUTH-CONDITIONS", "role": "primary"},
        {"text": "COMPLEX PROPOSITIONS AS TRUTH-FUNCTIONS", "role": "comparison"},
        {"text": "LOGICAL CONSTANTS ARE NOT OBJECTS", "role": "evidence"},
        {"text": "TAUTOLOGY / CONTRADICTION: LIMITING CASES", "role": "outcome"},
        {"text": "NONSENSE != TAUTOLOGY", "role": "caution"},
    ],
    [
        {"text": "FACTUAL PROPOSITIONS SAY", "role": "primary"},
        {"text": "LOGICAL FORM AND NECESSITY SHOW", "role": "comparison"},
        {"text": "ETHICS AND THE MYSTICAL ARE NOT ORDINARY FACTS", "role": "evidence"},
        {"text": "6.54: USE AND DISCARD THE LADDER", "role": "outcome"},
        {"text": "SELF-REFERENCE REMAINS A REAL TENSION", "role": "caution"},
    ],
)


GRAPHICAL_STAGE_ZERO_GROUPS = [
    {
        "heading": "THREE QUESTIONS",
        "role": "evidence",
        "items": [
            "MOORE -> what common-sense propositions are more certain than theory?",
            "RUSSELL -> what logical form lies beneath misleading grammar?",
            "EARLY WITTGENSTEIN -> what makes representation possible?",
        ],
    },
    {
        "heading": "THREE METHODS",
        "role": "mechanism",
        "items": [
            "MOORE -> certainty comparison and act/object distinctions.",
            "RUSSELL -> analysis, contextual definition and logical construction.",
            "EARLY WITTGENSTEIN -> picture theory, truth-functions and say/show.",
        ],
    },
    {
        "heading": "BOUNDARIES",
        "role": "outcome",
        "items": [
            "UNITY -> analysis replaces speculative system-building.",
            "DIFFERENCE -> epistemic defence, logical reduction, delimitation of sense.",
            "CAUTION -> verificationism is later; the trio do not share one atomism.",
        ],
    },
]
