"""Durable learner-v2 content and master-flow specification for Logical Positivism."""

from __future__ import annotations


def visual(title: str, caption: str, *lines: str) -> dict[str, object]:
    return {"title": title, "caption": caption, "lines": list(lines)}


def session(
    title: str,
    plain: str,
    technical: str,
    answer: str,
    keywords: list[str],
    usage: str,
    mechanism: str,
    consequence: str,
    trap: str,
    objection: str,
    reply: str,
    limit: str,
    exam: str,
    revision: list[str],
    visuals: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "title": title,
        "plain": plain,
        "technical": technical,
        "answer": answer,
        "keywords": keywords,
        "usage": usage,
        "mechanism": mechanism,
        "consequence": consequence,
        "trap": trap,
        "objection": objection,
        "reply": reply,
        "limit": limit,
        "exam": exam,
        "revision": revision,
        "visuals": visuals,
    }


SESSION_SPECS = (
    session(
        "The Vienna Circle Programme: Experience, Logic and Clarification",
        "Logical positivism was a programme for clarifying knowledge claims by joining empiricism with modern logic, not the slogan that science is good and every other human concern is worthless.",
        "The Vienna Circle around Moritz Schlick, Rudolf Carnap and Otto Neurath promoted a scientific worldview influenced by empiricism, mathematical logic and the early Wittgenstein; A. J. Ayer later supplied an influential English exposition. Philosophy was assigned logical clarification rather than a rival power to discover factual truths. Cognitive meaning is the capacity of a sentence to make a truth-apt factual claim or to function as an analytic logical truth; analytic propositions are true by meanings or rules, while synthetic propositions depend on how the world is.",
        "Logical positivism is best read as a programme that divides meaningful discourse into analytic rules and empirically answerable claims, while assigning philosophy the task of clarifying their logical form rather than competing with science.",
        [
            "Vienna Circle",
            "scientific worldview",
            "cognitive meaning",
            "analytic",
            "synthetic",
            "logical clarification",
        ],
        "Build the answer as Vienna Circle -> scientific worldview -> logical clarification -> analytic/synthetic division -> Ayer's English exposition -> internal diversity.",
        "Empiricism supplies experiential control + mathematical logic supplies analysis -> philosophy clarifies propositions -> analytic rules and synthetic factual claims are separated.",
        "The programme seeks evidential discipline and scientific coordination without one unchanged doctrine shared uniformly by Schlick, Carnap, Neurath and Ayer.",
        "Do not say the positivists treated every meaningful utterance as scientifically true or every non-scientific utterance as humanly worthless.",
        "The analytic-synthetic division may oversimplify language, and the Circle's members differed over protocols, physicalism, reduction and confirmation.",
        "The programme can be defended as a shared direction of inquiry rather than a single frozen creed: public testing and logical clarification unite positions that otherwise evolved.",
        "The unity claim remains methodological, and later revisions make it difficult to identify one verification formula as the doctrine of every logical positivist.",
        "Use a programme map: context and influences -> role of philosophy -> analytic/synthetic division -> unity-of-science ambition -> explicit caution about internal diversity.",
        [
            "Schlick, Carnap and Neurath belong to the Vienna Circle; Ayer popularised the programme in English.",
            "Cognitive meaning concerns truth-apt factual or analytic-logical content, not total human significance.",
            "Philosophy clarifies the language of knowledge instead of producing a second stock of empirical facts.",
        ],
        [
            visual(
                "Programme map: experience plus logic",
                "The programme joins empirical control with logical analysis and ends in clarification, not speculative factual discovery.",
                "EMPIRICISM: claims answer to possible experience",
                "                    \\",
                "                     +--> LOGICAL POSITIVIST PROGRAMME",
                "                    /             |",
                "MODERN LOGIC: expose form         v",
                "                         PHILOSOPHY AS CLARIFICATION",
                "                                      |",
                "                    ANALYTIC RULES + SYNTHETIC FACTUAL CLAIMS",
            ),
            visual(
                "Analytic-synthetic meaning classification",
                "Both branches are meaningful, but only one branch asserts contingent facts.",
                "PROPOSITION",
                "   |",
                "   +--> ANALYTIC / TAUTOLOGICAL",
                "   |    true by meaning, definition or rule; necessary; non-factual",
                "   |",
                "   +--> SYNTHETIC / EMPIRICAL",
                "        true or false according to experience; contingent; factual",
                "CAUTION -> 'meaningful' does not mean 'already verified' or 'scientifically true'",
            ),
        ],
    ),
    session(
        "Verification: Meaning, Strong and Weak Tests, and In-Principle Access",
        "A factual sentence has cognitive meaning only when its truth or falsity would make some possible difference to experience; one need not actually perform the test now.",
        "Verifiability in principle means that relevant observations are specifiable even when they are technologically or practically unavailable. Strong verification requires conclusive establishment in experience; weak verification, especially in Ayer's revised exposition, requires possible experience to count for or against a proposition or make it probable. Confirmation is partial evidential support rather than conclusive proof. Actual verification must therefore be distinguished from possible testability, and practical difficulty from logical impossibility.",
        "The verification criterion tests whether a factual claim has experiential consequences, not whether it has already been checked, conclusively proved, or accepted as scientifically true.",
        [
            "verifiability in principle",
            "actual verification",
            "strong verification",
            "weak verification",
            "confirmation",
            "probability",
        ],
        "Define the criterion as one of cognitive factual meaning, draw the strong/weak fork, and keep actual checking separate from verifiability in principle.",
        "Candidate factual proposition -> identify possible experiential difference -> strong route seeks conclusive verification; weak route seeks relevant confirming or disconfirming evidence.",
        "The weaker test saves more science and ordinary discourse, but it converts verification into a less decisive relation of confirmation.",
        "Do not define weak verification as mere compatibility with experience or attribute Popper's falsifiability test to logical positivism.",
        "Strong verification excludes laws, past events and other minds; weak verification risks becoming so permissive that it no longer excludes metaphysics.",
        "A positivist can require a disciplined evidential connection rather than conclusive proof and can treat indirect observational consequences as relevant.",
        "No weak formulation fully preserves both a sharp meaning boundary and adequate coverage of actual scientific language.",
        "Answer in five steps: criterion -> in principle/actual -> strong/weak -> confirmation -> strong/weak dilemma and qualified verdict.",
        [
            "Possible experiential difference is the core idea; completed observation is not required.",
            "Conclusive verification and partial confirmation are different standards.",
            "Ayer's weak test is a repair designed to preserve scientific and ordinary factual discourse.",
        ],
        [
            visual(
                "Factual proposition to verification or confirmation",
                "The path asks what evidence would matter before asking whether the proposition is true.",
                "FACTUAL PROPOSITION P",
                "        | Would any possible experience count for or against P?",
                "        +--> NO -> fails the criterion of cognitive factual meaning",
                "        |",
                "        +--> YES",
                "              +--> conclusive experience possible -> STRONG verification",
                "              +--> evidence changes probability -> WEAK verification / confirmation",
            ),
            visual(
                "Strong versus weak verification",
                "The revision trades decisiveness for coverage.",
                "STRONG: truth conclusively established | sharp boundary | excludes too much",
                "WEAK: observations relevant/probabilifying | broader science | admits too much",
                "PRESSURE: universal laws, history, other minds, dispositions, theory terms",
                "DILEMMA: too strict for science <----------------> too loose for demarcation",
            ),
            visual(
                "Actual checking versus verifiability in principle",
                "Practical inaccessibility does not by itself destroy cognitive meaning.",
                "ACTUALLY CHECKED NOW -> evidence has been gathered",
                "CHECKABLE IN PRACTICE -> current means make the test feasible",
                "VERIFIABLE IN PRINCIPLE -> a relevant test can be specified",
                "NOT VERIFIABLE EVEN IN PRINCIPLE -> no experience could make a difference",
            ),
        ],
    ),
    session(
        "Why Verification Attracted Support and Where Scientific Language Resists",
        "The criterion promised to connect meaning with publicly assessable evidence, but the most important scientific statements are rarely simple observation reports.",
        "The positive case invokes operational clarity, intersubjective testing, anti-obscurantism and the unity of science. Yet universal laws cannot be verified by finitely many instances; dispositional statements concern unmanifested tendencies; past events and other minds are known indirectly; theoretical entities such as electrons enter through networks of predictions. Reduction to observation therefore gave way to indirect verification, probability, confirmation and rules connecting theoretical and observational vocabulary.",
        "Verificationism gained its force from the demand that factual language incur an evidential risk, but scientific laws and theoretical terms reveal that this risk is normally indirect and holistic rather than a one-sentence reduction to observation.",
        [
            "universal law",
            "dispositional statement",
            "indirect verification",
            "theoretical entity",
            "observation statement",
            "unity of science",
        ],
        "Build the answer as unity of science -> observation statements -> universal laws -> dispositional statements -> past events and other minds -> theoretical entities -> indirect verification.",
        "Law/theory + initial conditions + auxiliary assumptions -> observable prediction -> result confirms, weakens or revises the connected scientific system.",
        "Scientific meaning becomes tied to inferential and evidential roles rather than a simple translation of every theoretical sentence into one observation sentence.",
        "Do not say a universal law is conclusively verified by many positive instances or that an unobservable theoretical entity is automatically metaphysical.",
        "If indirect confirmation saves theoretical science, sophisticated metaphysical systems may also claim indirect experiential relevance.",
        "The positivist reply distinguishes systematic predictive integration, public testing and revisability from an unconstrained claim that merely coexists with experience.",
        "The reply marks an epistemic difference but weakens verification as a precise sentence-by-sentence criterion of meaning.",
        "Use a hard-cases table, explain indirect confirmation, and end with the cost: scientific adequacy increases as demarcating sharpness decreases.",
        [
            "Universal statements range beyond every finite observation set.",
            "Dispositions and theoretical entities are meaningful through test-linked inferential roles.",
            "Confirmation evaluates evidential support; it is not identical with meaning, truth or proof.",
        ],
        [
            visual(
                "Scientific hard cases",
                "Each case pressures a simple equation between meaning and direct observation.",
                "UNIVERSAL LAW -> infinitely many possible instances -> never conclusively verified",
                "DISPOSITION -> may be real though never manifested in the present case",
                "PAST EVENT -> evidence now consists of traces, records and testimony",
                "OTHER MIND -> behaviour and expression provide indirect public evidence",
                "THEORETICAL ENTITY -> predictions arise through a network, not direct inspection",
            ),
            visual(
                "Indirect confirmation route",
                "The theory reaches experience through auxiliaries and predicted observations.",
                "LAW / THEORY + INITIAL CONDITIONS + AUXILIARY ASSUMPTIONS",
                "                              | deduction",
                "                              v",
                "                    OBSERVABLE PREDICTION",
                "                              | test",
                "             CONFIRM / DISCONFIRM / REVISE THE SYSTEM",
            ),
        ],
    ),
    session(
        "Early Wittgenstein, Logical Analysis and the Step Added by Positivism",
        "The Vienna Circle learned from the Tractatus that meaningful propositions represent possible facts and that logic does not describe another realm, but it added an explicit verification criterion.",
        "The early Wittgenstein influenced the factual-proposition/tautology contrast and the idea that philosophy clarifies language. His tautologies show logical form without depicting contingent facts, while his saying/showing distinction cannot be identified wholesale with positivism. Logical positivists transformed this delimitation of sense into an empiricist test of factual meaning and used mathematical logic to expose grammatical disguise and logical syntax.",
        "The Circle inherited a distinction between factual saying and logical scaffolding from the early Wittgenstein, yet verificationism was its own empiricist addition rather than a doctrine stated wholesale in the Tractatus.",
        [
            "early Wittgenstein",
            "logical form",
            "tautology",
            "saying and showing",
            "logical syntax",
            "empiricist addition",
        ],
        "Build the answer as early Wittgenstein -> logical form -> tautology -> saying and showing -> logical syntax -> the positivist empiricist addition.",
        "Tractarian fact/tautology boundary + empiricist demand for experiential control -> verification criterion and anti-metaphysical logical diagnosis.",
        "The lineage explains the programme's logical sophistication without erasing the Tractatus's distinct treatment of ethics, the mystical and showing.",
        "Do not call the early Wittgenstein a straightforward member of the Vienna Circle or equate saying/showing with verification/falsification.",
        "The positivist appropriation may flatten aspects of the Tractatus that were not reducible to empirical science.",
        "The Circle can reply that it adopted analytical tools and a boundary problem, not every Tractarian thesis or intention.",
        "Historical influence does not establish doctrinal identity, and Ayer's exposition is further removed from the Circle's internal debates.",
        "Use a two-stage lineage: what was taken -> what was added -> what must not be identified.",
        [
            "Tautologies are non-factual logical limits, not verified empirical reports.",
            "Logical syntax reveals structure that ordinary grammar may conceal.",
            "Verificationism is the Circle's empiricist development, not simply Tractatus doctrine.",
        ],
        [
            visual(
                "Tractatus to verification: inheritance and addition",
                "The arrow preserves influence without collapsing two programmes.",
                "EARLY WITTGENSTEIN",
                "facts can be said | logic is tautological | philosophy clarifies",
                "                     | Vienna Circle appropriation",
                "                     v",
                "LOGICAL POSITIVISM",
                "adds: factual meaning requires possible experiential verification",
                "CAUTION: saying/showing and the mystical are not identical with this test",
            ),
            visual(
                "Logical clarification workflow",
                "Analysis asks whether surface grammar corresponds to genuine logical form.",
                "ORDINARY SENTENCE",
                "      | analyse logical syntax",
                "      +--> factual form with test conditions",
                "      +--> analytic/tautological rule",
                "      +--> grammatical disguise or malformed logical combination",
            ),
        ],
    ),
    session(
        "Rejection of Metaphysics: The Pseudo-Proposition Diagnostic",
        "Logical positivists reject a metaphysical sentence as cognitively meaningless when it looks like a factual assertion but supplies no possible experiential test or coherent logical role.",
        "A pseudo-proposition is an expression with assertion-like grammar but no cognitive factual content. Carnap diagnoses terms without criteria of application, grammatical disguise, category mistakes and violations or misuse of logical syntax; Ayer argues that an alleged factual claim is cognitively meaningful only when some possible experience is relevant. The verdict is not automatically that the sentence is false, emotionally worthless or literally ungrammatical.",
        "The positivist attack on metaphysics is primarily semantic: it denies that an unverifiable pseudo-proposition reaches the stage of truth or falsity, while leaving open its historical, expressive or existential significance.",
        [
            "pseudo-proposition",
            "criterion of application",
            "grammatical disguise",
            "category mistake",
            "logical syntax",
            "cognitive meaninglessness",
        ],
        "Build the answer as pseudo-proposition -> criterion of application -> grammatical disguise -> category mistake -> logical syntax -> cognitive meaninglessness, then distinguish false and worthless.",
        "Assertion-like sentence -> analytic? -> if no, specify possible experiential test -> if none, inspect term-use and logical syntax -> diagnose pseudo-proposition.",
        "The analysis converts a dispute about hidden reality into a prior question about whether a factual claim has been successfully made.",
        "Do not caricature religious or Indian philosophical traditions, and do not infer that every metaphysical sentence is nonsense in ordinary language or devoid of significance.",
        "Many metaphysical claims appear intelligible, guide inquiry and may challenge the positivist's narrow model of factual meaning.",
        "The positivist reply asks for conditions under which disagreement would be settled and warns that grammatical familiarity can create an illusion of factual content.",
        "The diagnostic is strongest against claims insulated from every possible counter-instance and weaker against systematic metaphysics with explanatory or experiential connections.",
        "Use a diagnostic flow and then evaluate the criterion on which the diagnosis depends.",
        [
            "Cognitive meaninglessness is not falsity because the sentence is denied truth-conditions.",
            "Carnap's target includes misuse of terms and logical syntax, not only absent laboratory tests.",
            "A fair example tests the form of the claim without dismissing a tradition or practice as worthless.",
        ],
        [
            visual(
                "Metaphysical pseudo-proposition diagnostic",
                "The flow distinguishes empirical failure from failure to formulate a factual claim.",
                "ASSERTION-LIKE SENTENCE",
                "        | analytic / tautological?",
                "        +--> YES -> meaningful non-factual rule",
                "        |",
                "        +--> NO -> possible experiential difference?",
                "                    +--> YES -> synthetic factual candidate",
                "                    +--> NO -> inspect term criteria, category and logical syntax",
                "                               -> PSEUDO-PROPOSITION diagnosis",
            ),
            visual(
                "Four verdicts kept distinct",
                "UPSC answers must not collapse semantic, epistemic and evaluative verdicts.",
                "FALSE -> meaningful proposition that does not match reality",
                "UNKNOWABLE -> meaningful question beyond available justification",
                "PSEUDO-PROPOSITION -> no cognitive factual claim successfully made",
                "WORTHLESS -> separate evaluative verdict; not entailed by positivism's criterion",
            ),
        ],
    ),
    session(
        "Religion, Ethics and Aesthetics: Cognitive Status and Human Significance",
        "A positivist may deny that a value or religious utterance states an empirically testable fact while still recognising that it expresses attitudes, recommends action or shapes a form of life.",
        "Emotive significance is the expressive force by which an utterance evinces or influences attitudes without describing a truth-apt fact. Ayer treats basic ethical judgements as non-cognitive expressions rather than reports of feeling; prescriptive, expressive and persuasive functions must be separated from factual assertion. Religious and aesthetic utterances require sentence-by-sentence analysis: some make historical or empirical claims, while others function devotionally, symbolically, evaluatively or expressively.",
        "Logical positivism narrows the cognitive factual status of ethical, religious and aesthetic utterances, but cognitive non-factuality does not erase their emotive, expressive, prescriptive or cultural significance.",
        [
            "emotive significance",
            "non-cognitive",
            "expressive",
            "prescriptive",
            "factual status",
            "attitude",
        ],
        "Build the answer as factual status -> non-cognitive use -> emotive significance -> expressive function -> prescriptive function -> attitude, followed by the reporting/expressing distinction.",
        "Utterance -> factual component? test it empirically; evaluative component? analyse expressive/prescriptive role -> cognitive status and practical significance are reported separately.",
        "The framework prevents value judgements from masquerading as empirical descriptions while preserving their motivational and social roles.",
        "Do not say 'cognitively meaningless' means 'emotionally meaningless,' and do not treat every religious sentence as having one identical function.",
        "Moral reasoning appears to involve consistency, reasons and disagreement that simple emotivism may not adequately explain.",
        "The positivist can distinguish factual premises from the attitude or prescription expressed in the final evaluative judgement and can analyse persuasive language dynamically.",
        "The reply does not fully explain moral objectivity, embedded ethical propositions or rational criticism of ultimate values.",
        "Use paired columns: cognitive factual status versus emotive/expressive/prescriptive significance, followed by one objection and qualified reply.",
        [
            "Expressing approval is not the same as reporting that one feels approval.",
            "Historical claims within religion may be factual even when devotional meaning is not exhausted by factual description.",
            "Non-cognitive classification does not establish social, aesthetic or existential worthlessness.",
        ],
        [
            visual(
                "Cognitive versus emotive or expressive significance",
                "One utterance may have different factual and practical dimensions.",
                "UTTERANCE",
                "   +--> FACTUAL/COGNITIVE QUESTION: what observation would bear on truth?",
                "   |",
                "   +--> EXPRESSIVE QUESTION: what attitude or commitment is evinced?",
                "   +--> PRESCRIPTIVE QUESTION: what action or stance is recommended?",
                "   +--> AESTHETIC/DEVOTIONAL QUESTION: what significance is enacted?",
                "VERDICT -> non-factual does not mean insignificant or valueless",
            ),
            visual(
                "Fair classification examples",
                "Analyse functions rather than caricaturing whole traditions.",
                "'This ritual occurred in year Y' -> historical and evidential component",
                "'Compassion is good' -> evaluative approval and guidance",
                "'This raga is sublime' -> aesthetic evaluation, not a measurement report",
                "'The sacred is present here' -> analyse factual, symbolic and devotional uses",
            ),
        ],
    ),
    session(
        "Necessary Propositions: Analyticity, Tautology and Linguistic Rules",
        "Logic and mathematics are necessary not because they describe invisible objects, but because their truths follow from definitions, conventions or rules governing symbols and inference.",
        "The linguistic theory of necessary propositions treats logical and mathematical necessity as analytic, tautological or true by virtue of linguistic conventions. A tautology is true under every admissible interpretation of its components and asserts no contingent fact. Conventionalism explains necessity through adopted rules or frameworks. Analytic propositions remain cognitively meaningful in a non-factual logical sense: they organise representation and inference without being empirically verified.",
        "For the positivist, necessary propositions do not report a supersensible reality; they articulate the linguistic and inferential framework within which factual propositions can be represented and tested.",
        [
            "necessary proposition",
            "analytic truth",
            "tautology",
            "conventionalism",
            "stipulative definition",
            "rule of inference",
        ],
        "Explain why necessary truths are meaningful yet non-factual, connect logic, mathematics, definitions and rules, and distinguish early Wittgenstein's influence from full doctrinal identity.",
        "Definitions and inferential conventions fix symbol-use -> analytic/tautological result follows -> the result organises reasoning but adds no contingent fact.",
        "The theory preserves empiricism by explaining a priori necessity without admitting synthetic knowledge of a supersensible order.",
        "Do not say analytic propositions are meaningless because they are not empirically verified or that mathematics is merely arbitrary notation.",
        "Kant's synthetic a priori challenges the reduction; Quine attacks the analytic-synthetic boundary; necessity may seem stronger than optional convention.",
        "A conventionalist replies that frameworks are chosen for practical and theoretical purposes, while consequences within an adopted system can be strict and non-arbitrary.",
        "The reply explains formal necessity better than why some rules are indispensable, fruitful or justified, and it may relocate rather than dissolve normativity.",
        "Answer: empiricist problem -> linguistic solution -> logic/mathematics examples -> non-factual function -> Kant/Quine/necessity objections -> graded defence.",
        [
            "Analytic propositions are meaningful by logical role even though no observation verifies them.",
            "Tautologies constrain representation and inference without describing how the world contingently is.",
            "Conventional choice of a framework does not make every consequence inside it optional.",
        ],
        [
            visual(
                "Necessary propositions as linguistic rules",
                "Necessity moves from a supersensible object to the rule-governed framework of expression.",
                "DEFINITIONS + SYMBOL RULES + RULES OF INFERENCE",
                "                        |",
                "                        v",
                "             ANALYTIC / TAUTOLOGICAL TRUTH",
                "                        |",
                "         ORGANISES INFERENCE AND REPRESENTATION",
                "                        |",
                "              ASSERTS NO CONTINGENT FACT",
            ),
            visual(
                "Logic and mathematics: factual versus non-factual",
                "The distinction concerns what makes the proposition true.",
                "2 + 2 = 4 -> follows within definitions/rules -> necessary, non-factual",
                "Either P or not-P -> tautological form -> no world-survey required",
                "This page is white -> observation decides -> contingent, factual",
                "CAUTION -> non-factual meaningfulness is not absence of logical importance",
            ),
        ],
    ),
    session(
        "Protocol Statements, Theory Relations and the Programme's Internal Shift",
        "Verification needs an evidential stopping point, but positivists disagreed over whether observation reports are private foundations or revisable public sentences within science.",
        "A protocol statement is a basic observation report proposed as an evidential checkpoint for testing other claims. Schlick defended a more foundational experiential role; Neurath rejected incorrigible private foundations and treated protocols as public, revisable parts of the scientific language. Carnap's physicalism and the unity-of-science project sought intersubjective coordination. Later work moved from strict reduction toward confirmation, probability, reduction sentences, logical syntax and semantics, and qualified acceptance of theoretical terms.",
        "The protocol-sentence debate shows verificationism revising itself from an imagined incorrigible observation base toward intersubjective, revisable confirmation inside a scientific language.",
        [
            "protocol statement",
            "foundationalism",
            "intersubjective testability",
            "physicalism",
            "reduction sentence",
            "theoretical term",
        ],
        "Build the answer as protocol statement -> Schlick's foundationalism -> Neurath's intersubjective testability -> physicalism -> reduction sentence -> theoretical term.",
        "Theory generates predictions -> protocol reports record public observations -> reports and theory are compared -> conflict may revise either report, auxiliary or theory.",
        "The programme becomes less reductionist and more concerned with public coordination, confirmation and the logical organisation of science.",
        "Do not describe protocol statements as infallible sense-data shared uniformly by the Circle or physicalism as crude denial of mental discourse.",
        "Theory-ladenness and revisability remove the neutral observation bedrock that verification appeared to require.",
        "Neurath's reply substitutes intersubjective criticism and coherent adjustment for private certainty; science needs public correction, not Cartesian foundations.",
        "Coherent revision may preserve scientific practice while abandoning the original hope for an unrevisable empirical foundation.",
        "Use a debate table: Schlick -> Neurath -> Carnap/physicalism -> later confirmation and theoretical-term toleration.",
        [
            "Protocol statements are evidential reports, not the verification principle itself.",
            "Neurath's public and revisable protocols challenge an incorrigible experiential foundation.",
            "The move toward confirmation and theory terms records development, not a timeless uniform doctrine.",
        ],
        [
            visual(
                "Protocol statement and theory relation",
                "Observation reports test theories but are themselves linguistically formulated and revisable.",
                "THEORY + AUXILIARIES",
                "        | predict",
                "        v",
                "OBSERVABLE EVENT -> PROTOCOL STATEMENT",
                "        | compare with prediction",
                "        v",
                "CONFIRM / REVISE THEORY / REVISE AUXILIARY / CHECK REPORT",
                "NO AUTOMATIC INCORRIGIBLE BEDROCK",
            ),
            visual(
                "Internal development of the programme",
                "The direction is from strict reduction toward more flexible evidential relations.",
                "STRICT VERIFICATION / REDUCTION",
                "            -> WEAK VERIFICATION AND PROBABILITY",
                "            -> CONFIRMATION AND REDUCTION SENTENCES",
                "            -> LOGICAL SYNTAX / SEMANTICS",
                "            -> CONTROLLED USE OF THEORETICAL TERMS",
            ),
        ],
    ),
    session(
        "Carnapian Frameworks, Tolerance and Conventionalist Refinement",
        "Carnapian tolerance treats a linguistic framework as an explicit rule-system whose analytic, factual and practical questions must be separated, thereby refining conventionalism without making framework choice arbitrary.",
        "The principle of tolerance permits alternative linguistic forms provided their rules are stated clearly. A linguistic framework supplies rules for forming and testing statements; internal questions are answered within those rules, while practical external questions concern whether adopting the framework is useful. This refinement connects conventionalism, logical syntax and semantics to the linguistic theory of necessity and softens an overly simple elimination of all theoretical vocabulary.",
        "Carnap's tolerance converts philosophy from policing one compulsory language into the explicit construction and comparison of frameworks, though practical framework choice cannot itself be reduced to an analytic truth.",
        [
            "principle of tolerance",
            "linguistic framework",
            "internal question",
            "external question",
            "logical syntax",
            "conventionalism",
        ],
        "Present tolerance as a refinement within Carnap's development, connect it to necessary propositions, and keep later internal/external language historically qualified.",
        "Choose explicit framework rules -> derive analytic consequences and test internal factual claims -> compare frameworks by clarity, fruitfulness and scientific utility.",
        "Metaphysical-looking disputes may be recast as framework proposals or practical choices rather than rival descriptions of a hidden reality.",
        "Do not claim every external question is meaningless in every Carnapian phase or that tolerance makes all languages equally useful.",
        "If framework choice is pragmatic, the rule that recommends tolerance and the values used to choose frameworks require justification outside pure syntax.",
        "Carnap can answer that a practical proposal need not masquerade as a factual discovery and can be assessed by consequences for inquiry.",
        "The refinement handles conceptual engineering well but does not settle whether ontology contains substantive questions irreducible to framework choice.",
        "Use tolerance after the core criterion, not as a replacement for it: rules -> internal questions -> practical choice -> objection about justification.",
        [
            "Tolerance permits plural rule systems, not careless ambiguity.",
            "Internal questions depend on a framework; adoption questions are practical and comparative.",
            "Framework choice makes conventionalism disciplined but leaves the values of choice open to debate.",
        ],
        [
            visual(
                "Carnapian framework choice",
                "Rules determine internal questions, while adoption is assessed pragmatically.",
                "PROPOSE A LINGUISTIC FRAMEWORK",
                "        | state syntax, semantics and test rules",
                "        +--> INTERNAL ANALYTIC QUESTIONS -> answered by rules",
                "        +--> INTERNAL FACTUAL QUESTIONS -> answered by evidence",
                "        +--> ADOPTION QUESTION -> clarity, fruitfulness, coordination, economy",
            ),
            visual(
                "Conventionalism with discipline",
                "Choice of rules and necessity within rules must not be confused.",
                "FRAMEWORK CHOICE -> conventional / pragmatic / revisable",
                "WITHIN FRAMEWORK -> consequences may be necessary and exact",
                "NOT ARBITRARY -> utility and inferential performance constrain adoption",
                "OPEN QUESTION -> what justifies the standards used to choose?",
            ),
        ],
    ),
    session(
        "Self-Application, Popper and Quine: Criticism, Replies and Legacy",
        "The programme's hardest question is whether its own meaning criterion satisfies the test it imposes, while later critics challenge both verification and the analytic-synthetic division.",
        "The self-application dilemma asks whether the verification principle is analytic or empirically verifiable; if neither, it appears cognitively meaningless by its own criterion. Ayer may treat it as a stipulative definition or methodological recommendation, but this weakens its authority. Popper's falsifiability is a rival criterion of scientific demarcation, not a logical positivist theory of meaning. Quine attacks analyticity and confirmation sentence by sentence, proposing holistic testing. Kant's synthetic a priori and meaningful metaphysics pressure the linguistic theory, while Hume supplies the empiricist fork that positivism radicalises.",
        "Logical positivism survives less as a successful final criterion of meaning than as a disciplined demand for clarity and evidence whose revisions, self-application problem and successor critiques expose the limits of any sharp linguistic tribunal.",
        [
            "self-application",
            "demarcation",
            "falsifiability",
            "confirmation holism",
            "analytic-synthetic critique",
            "qualified legacy",
        ],
        "Build the answer as self-application -> demarcation -> falsifiability -> confirmation holism -> analytic-synthetic critique -> qualified legacy, while separating meaning, truth, confirmation and significance.",
        "Verification principle applies to itself -> neither clear analytic truth nor empirical proposition -> stipulation/recommendation reply -> authority weakens; successor critiques target different components.",
        "The movement's enduring contribution lies in logical analysis, evidential responsibility and philosophy of science/language, not an undefeated universal test.",
        "Do not attribute falsifiability to logical positivism, treat Quine as merely proposing a weaker verification principle, or confuse human significance with cognitive factual meaning.",
        "The criterion is self-referentially unstable, scientific testing is theory-laden and holistic, and analyticity lacks the clean foundation the programme requires.",
        "The best positivist reply treats the principle as a clarificatory proposal, accepts revisability and retains evidential discipline without claiming incorrigible foundations.",
        "This reply preserves a methodological ethos but concedes that the original sharp elimination of metaphysics cannot be maintained unchanged.",
        "Close with a six-term distinction, criticism/reply matrix, comparison table, strengths/weaknesses and a complete answer spine.",
        [
            "Meaning asks whether a claim is truth-apt; truth asks whether it is correct.",
            "Verification is a proposed meaning test; confirmation is graded evidence; demarcation separates science from non-science.",
            "Popper rivals verification with falsifiability, while Quine attacks isolated testing and analyticity.",
        ],
        [
            visual(
                "Self-application dilemma",
                "Either route creates a cost for the principle's claimed authority.",
                "VERIFICATION PRINCIPLE",
                "        | analytic?",
                "        +--> YES -> stipulative rule, but why must every language accept it?",
                "        |",
                "        +--> NO -> empirically verifiable?",
                "                    +--> NO -> fails its own criterion",
                "REPLY -> methodological recommendation",
                "RESIDUAL -> useful proposal, not self-certifying truth",
            ),
            visual(
                "Criticism and reply matrix",
                "Each reply saves a narrower claim and leaves a residual cost.",
                "SELF-REFUTATION -> stipulation/recommendation -> loses universal authority",
                "LAWS/THEORY TERMS -> indirect confirmation -> boundary becomes permissive",
                "THEORY-LADEN OBSERVATION -> public revisability -> no neutral foundation",
                "QUINE ON ANALYTICITY -> framework practice -> circularity worry remains",
                "VALUE/METAPHYSICS -> significance conceded -> cognitive model remains narrow",
            ),
            visual(
                "Logical Positivism versus Popper versus Quine",
                "The comparison keeps meaning, demarcation and confirmation distinct.",
                "LOGICAL POSITIVISM -> criterion of cognitive meaning -> verification/confirmation",
                "POPPER -> criterion of scientific demarcation -> risky falsifiability",
                "QUINE -> web of belief -> holistic confrontation with experience",
                "CAUTION -> rival projects overlap historically but are not interchangeable",
            ),
            visual(
                "Complete Philosophy Optional answer spine",
                "The spine moves from fair reconstruction to qualified evaluation.",
                "CONTEXT AND THESIS",
                " -> DEFINE ANALYTIC / SYNTHETIC / VERIFICATION",
                " -> EXPLAIN STRONG, WEAK AND IN-PRINCIPLE TESTS",
                " -> APPLY TO METAPHYSICS AND NECESSARY TRUTHS",
                " -> TEST LAWS, THEORY TERMS, VALUES AND SELF-APPLICATION",
                " -> POPPER / QUINE COMPARISON",
                " -> REPLY, RESIDUAL LIMIT AND GRADED LEGACY",
            ),
        ],
    ),
)


ASCII_PANELS = (
    {
        "title": "Vienna Circle programme and the analytic-synthetic division",
        "structural_type": "programme-map-and-classification-tree",
        "sessions": [1],
        "lines": [
            "START -> Vienna Circle: Schlick, Carnap, Neurath; Ayer is the English expositor.",
            "INFLUENCES -> empiricism + mathematical logic + early Wittgenstein.",
            "PHILOSOPHY -> logical clarification, not a rival source of empirical facts.",
            "COGNITIVE MEANING -> truth-apt factual content or analytic logical function.",
            "ANALYTIC -> true by meanings/rules; necessary; non-factual yet meaningful.",
            "SYNTHETIC -> contingent; truth depends on experience; factual candidate.",
            "SCIENTIFIC WORLDVIEW -> public evidence, coordination and unity ambitions.",
            "DIVERSITY -> protocols, reduction, physicalism and confirmation remained disputed.",
            "TRAP -> meaningful != scientifically true; non-cognitive != worthless.",
            "ANSWER LINE -> one programme, evolving formulations and different internal routes.",
        ],
    },
    {
        "title": "Verification criterion, strong-weak fork and in-principle access",
        "structural_type": "criterion-fork-and-access-ladder",
        "sessions": [2],
        "lines": [
            "FACTUAL P -> cognitively meaningful only if experience could count for or against P.",
            "ACTUAL VERIFICATION -> the evidence has been gathered now.",
            "IN-PRACTICE TESTABILITY -> present technology and conditions make checking feasible.",
            "IN-PRINCIPLE VERIFIABILITY -> relevant observations can be specified in principle.",
            "STRONG -> experience could conclusively establish truth; sharp but over-exclusive.",
            "WEAK -> possible evidence raises/lowers probability; Ayer's broader repair.",
            "CONFIRMATION -> partial evidential support, not conclusive proof or truth itself.",
            "PRESSURE -> laws, past, other minds, dispositions and theory terms.",
            "TRAP -> falsifiability is Popper's rival demarcation rule, not this doctrine.",
            "DILEMMA -> strong kills science; weak risks readmitting metaphysics.",
        ],
    },
    {
        "title": "Positive case and scientific hard cases",
        "structural_type": "motivation-to-indirect-confirmation-chain",
        "sessions": [3],
        "lines": [
            "POSITIVE CASE -> evidence, operational clarity, public testing, anti-obscurantism.",
            "UNIVERSAL LAW -> finite observations never conclusively verify every instance.",
            "DISPOSITION -> meaningful tendency may remain unmanifested in the present case.",
            "PAST EVENT -> current traces, records and testimony provide indirect evidence.",
            "OTHER MIND -> behaviour/expression provide public but non-conclusive evidence.",
            "THEORETICAL ENTITY -> electron-talk belongs to a predictive theoretical network.",
            "ROUTE -> theory + conditions + auxiliaries -> prediction -> observation report.",
            "RESULT -> confirm, weaken or revise the connected system.",
            "REPLY -> public predictive integration differs from insulation from evidence.",
            "LIMIT -> science is saved as sentence-by-sentence demarcation becomes less sharp.",
        ],
    },
    {
        "title": "Early Wittgenstein's influence and the positivist addition",
        "structural_type": "inheritance-addition-boundary-map",
        "sessions": [4],
        "lines": [
            "TRACTATUS INFLUENCE -> facts can be said; logic is tautological; philosophy clarifies.",
            "TAUTOLOGY -> shows logical form but does not picture a contingent fact.",
            "SAYING/SHOWING -> cannot be identified wholesale with positivist verificationism.",
            "CIRCLE'S ADDITION -> factual meaning requires possible experiential verification.",
            "MODERN LOGIC -> analyse logical form beneath misleading surface grammar.",
            "LOGICAL SYNTAX -> reveals misuse of categories, terms and quantificational forms.",
            "PHILOSOPHY -> clarification of scientific language and limits of assertion.",
            "HISTORICAL CAUTION -> influence does not make Wittgenstein a uniform Circle member.",
            "AYER CAUTION -> English exposition is not identical with every Vienna doctrine.",
            "ANSWER LINE -> inherited logical boundary plus an original empiricist meaning test.",
        ],
    },
    {
        "title": "Metaphysical pseudo-proposition diagnostic",
        "structural_type": "diagnostic-decision-tree",
        "sessions": [5],
        "lines": [
            "ASSERTION-LIKE SENTENCE -> first ask: analytic or tautological?",
            "IF NO -> what possible experience would bear on truth or falsity?",
            "IF NONE -> inspect each term's criterion of application.",
            "CHECK -> grammatical disguise, category mistake and misuse of logical syntax.",
            "PSEUDO-PROPOSITION -> assertion-like form without cognitive factual content.",
            "CARNAP -> logical analysis diagnoses malformed or empty metaphysical constructions.",
            "AYER -> unverifiable factual pretence fails the cognitive-meaning criterion.",
            "NOT FALSE -> the positivist denies truth-conditions, not merely correspondence.",
            "NOT WORTHLESS -> expressive, historical or existential significance may remain.",
            "LIMIT -> the verdict is only as strong as the verification criterion itself.",
        ],
    },
    {
        "title": "Religion, ethics and aesthetics: status versus significance",
        "structural_type": "dual-status-function-classification",
        "sessions": [6],
        "lines": [
            "FIRST QUESTION -> does the utterance contain a factual, testable component?",
            "ETHICAL JUDGEMENT -> Ayer treats basic evaluation as non-cognitive expression.",
            "EMOTIVE SIGNIFICANCE -> evinces/influences attitudes; does not report a fact.",
            "REPORTING FEELING != EXPRESSING APPROVAL.",
            "PRESCRIPTIVE FUNCTION -> recommends conduct or commitment.",
            "RELIGIOUS LANGUAGE -> may mix historical claims, symbols and devotional practice.",
            "AESTHETIC LANGUAGE -> evaluation and response need not be measurement reports.",
            "FAIRNESS -> analyse sentence-functions; never caricature a whole tradition.",
            "OBJECTION -> reasons, consistency and embedded ethics pressure simple emotivism.",
            "VERDICT -> non-factual cognitive status does not erase human significance.",
        ],
    },
    {
        "title": "Linguistic theory of necessary propositions",
        "structural_type": "rule-tautology-nonfactual-function-map",
        "sessions": [7],
        "lines": [
            "EMPIRICIST PROBLEM -> how can logic and mathematics be necessary and a priori?",
            "ANSWER -> analytic/tautological truth by definitions, conventions and rules.",
            "TAUTOLOGY -> true under every admissible assignment; no contingent fact asserted.",
            "LOGIC/MATHEMATICS -> organise inference and representation within a framework.",
            "MEANINGFUL -> non-factual logical role; empirical verification is unnecessary.",
            "CONVENTIONALISM -> framework rules explain necessity without supersensible objects.",
            "EARLY WITTGENSTEIN -> tautology influence, not wholesale doctrinal identity.",
            "KANT -> synthetic a priori challenges reduction to analyticity.",
            "QUINE -> analytic-synthetic boundary appears circular and unstable.",
            "REPLY/LIMIT -> strict consequences within chosen rules; choice standards need defence.",
        ],
    },
    {
        "title": "Protocol statements and the internal shift toward confirmation",
        "structural_type": "foundation-debate-and-development-timeline",
        "sessions": [8],
        "lines": [
            "PROTOCOL STATEMENT -> basic observation report used as an evidential checkpoint.",
            "SCHLICK -> more foundational experiential role for observation reports.",
            "NEURATH -> public, revisable protocols; no private incorrigible foundation.",
            "THEORY -> predicts event; protocol records it; mismatch triggers distributed revision.",
            "PHYSICALISM -> public coordination language, not crude denial of mental discourse.",
            "UNITY OF SCIENCE -> intersubjective integration remained an ambition, not one formula.",
            "DEVELOPMENT -> strict reduction -> probability -> confirmation.",
            "FURTHER SHIFT -> reduction sentences, syntax/semantics and theoretical-term toleration.",
            "THEORY-LADENNESS -> observation is not a neutral language-free bedrock.",
            "VERDICT -> practice survives through revisability as foundational verification weakens.",
        ],
    },
    {
        "title": "Carnapian tolerance, frameworks and conventionalist refinement",
        "structural_type": "framework-choice-and-question-matrix",
        "sessions": [9],
        "lines": [
            "PRINCIPLE OF TOLERANCE -> state rules clearly; no single compulsory logical language.",
            "LINGUISTIC FRAMEWORK -> syntax, semantics and standards for internal questions.",
            "INTERNAL ANALYTIC QUESTION -> answered through framework rules.",
            "INTERNAL FACTUAL QUESTION -> answered through evidence inside the framework.",
            "ADOPTION QUESTION -> practical comparison: clarity, economy, fruitfulness, coordination.",
            "CONVENTIONAL CHOICE != arbitrary consequence inside an adopted system.",
            "ONTOLOGY -> some disputes can be recast as framework proposals rather than discoveries.",
            "THEORETICAL TERMS -> retained when disciplined by inferential and test relations.",
            "OBJECTION -> standards of framework choice themselves require justification.",
            "LIMIT -> conceptual engineering does not dissolve every substantive ontological issue.",
        ],
    },
    {
        "title": "Self-application, successor critiques, evaluation and answer spine",
        "structural_type": "dilemma-comparison-matrix-and-answer-spine",
        "sessions": [10],
        "lines": [
            "SELF-APPLICATION -> is the verification principle analytic or empirically verifiable?",
            "IF NEITHER -> it fails its own test; if stipulative -> its universal authority weakens.",
            "POPPER -> falsifiability demarcates science; it is not a positivist meaning criterion.",
            "QUINE -> attacks analyticity and isolated testing; experience meets a web of belief.",
            "KANT -> synthetic a priori challenges the linguistic reduction of necessity.",
            "STRENGTHS -> clarity, evidence, anti-obscurantism, philosophy of science/language.",
            "WEAKNESSES -> self-reference, laws, theory-ladenness, values, unstable analyticity.",
            "DISTINGUISH -> meaning | truth | verification | confirmation | demarcation | significance.",
            "ANSWER SPINE -> context -> definitions -> three doctrines -> objections/replies.",
            "CONCLUSION -> enduring method of clarification, unsuccessful final tribunal of meaning.",
        ],
    },
)


REQUIRED_CORE_TERMS = (
    "cognitive meaning",
    "verifiability in principle",
    "strong verification",
    "weak verification",
    "confirmation",
    "protocol statement",
    "analytic",
    "synthetic",
    "tautology",
    "pseudo-proposition",
    "logical syntax",
    "conventionalism",
    "emotive significance",
    "demarcation",
    "Vienna Circle",
    "Schlick",
    "Carnap",
    "Neurath",
    "Ayer",
    "Verification Theory of Meaning",
    "Rejection of Metaphysics",
    "Linguistic Theory of Necessary Propositions",
    "universal laws",
    "dispositional statements",
    "past events",
    "other minds",
    "theoretical entities",
    "falsifiability",
    "Quine",
)


GRAPHICAL_PILLS = (
    [
        {"text": "VIENNA CIRCLE: SCHLICK, CARNAP, NEURATH", "role": "primary"},
        {"text": "AYER: ENGLISH EXPOSITION", "role": "comparison"},
        {"text": "EXPERIENCE + MODERN LOGIC", "role": "evidence"},
        {"text": "PHILOSOPHY AS CLARIFICATION", "role": "outcome"},
        {"text": "ANALYTIC / SYNTHETIC DIVISION", "role": "caution"},
    ],
    [
        {"text": "POSSIBLE EXPERIENTIAL DIFFERENCE", "role": "primary"},
        {"text": "ACTUAL != IN-PRINCIPLE", "role": "comparison"},
        {"text": "STRONG: CONCLUSIVE", "role": "evidence"},
        {"text": "WEAK: PROBABILIFYING", "role": "outcome"},
        {"text": "CONFIRMATION != TRUTH OR PROOF", "role": "caution"},
    ],
    [
        {"text": "UNIVERSAL LAWS EXCEED FINITE DATA", "role": "primary"},
        {"text": "DISPOSITIONS AND PAST EVENTS", "role": "comparison"},
        {"text": "OTHER MINDS: INDIRECT EVIDENCE", "role": "evidence"},
        {"text": "THEORY TERMS VIA PREDICTIONS", "role": "outcome"},
        {"text": "SCIENCE SAVED, BOUNDARY SOFTENED", "role": "caution"},
    ],
    [
        {"text": "FACTUAL SAYING + TAUTOLOGICAL LOGIC", "role": "primary"},
        {"text": "EARLY WITTGENSTEIN INFLUENCE", "role": "comparison"},
        {"text": "LOGICAL SYNTAX EXPOSES FORM", "role": "evidence"},
        {"text": "VERIFICATION: POSITIVIST ADDITION", "role": "outcome"},
        {"text": "DO NOT IDENTIFY THE PROGRAMMES", "role": "caution"},
    ],
    [
        {"text": "PSEUDO-PROPOSITION", "role": "primary"},
        {"text": "NO CRITERION OF APPLICATION", "role": "comparison"},
        {"text": "GRAMMATICAL DISGUISE / CATEGORY ERROR", "role": "evidence"},
        {"text": "COGNITIVELY MEANINGLESS, NOT FALSE", "role": "outcome"},
        {"text": "SIGNIFICANCE MAY REMAIN", "role": "caution"},
    ],
    [
        {"text": "FACTUAL STATUS != HUMAN SIGNIFICANCE", "role": "primary"},
        {"text": "EMOTIVE: EXPRESS ATTITUDE", "role": "comparison"},
        {"text": "PRESCRIPTIVE / PERSUASIVE FORCE", "role": "evidence"},
        {"text": "RELIGIOUS AND AESTHETIC USES VARY", "role": "outcome"},
        {"text": "NO TRADITIONAL CARICATURE", "role": "caution"},
    ],
    [
        {"text": "NECESSITY BY RULE OR CONVENTION", "role": "primary"},
        {"text": "ANALYTIC / TAUTOLOGICAL", "role": "comparison"},
        {"text": "LOGIC AND MATHEMATICS NON-FACTUAL", "role": "evidence"},
        {"text": "ORGANISE INFERENCE AND REPRESENTATION", "role": "outcome"},
        {"text": "KANT AND QUINE PRESSURE", "role": "caution"},
    ],
    [
        {"text": "PROTOCOL STATEMENT", "role": "primary"},
        {"text": "SCHLICK: FOUNDATION", "role": "comparison"},
        {"text": "NEURATH: PUBLIC AND REVISABLE", "role": "evidence"},
        {"text": "PHYSICALISM / UNITY OF SCIENCE", "role": "outcome"},
        {"text": "REDUCTION -> CONFIRMATION SHIFT", "role": "caution"},
    ],
    [
        {"text": "PRINCIPLE OF TOLERANCE", "role": "primary"},
        {"text": "LINGUISTIC FRAMEWORK", "role": "comparison"},
        {"text": "INTERNAL ANALYTIC / FACTUAL QUESTIONS", "role": "evidence"},
        {"text": "PRACTICAL ADOPTION QUESTION", "role": "outcome"},
        {"text": "CHOICE STANDARDS NEED JUSTIFICATION", "role": "caution"},
    ],
    [
        {"text": "SELF-APPLICATION DILEMMA", "role": "primary"},
        {"text": "POPPER: FALSIFIABILITY", "role": "comparison"},
        {"text": "QUINE: HOLISM + ANTI-ANALYTICITY", "role": "evidence"},
        {"text": "CLARITY AND EVIDENCE: ENDURING LEGACY", "role": "outcome"},
        {"text": "METHOD SURVIVES; FINAL TRIBUNAL FAILS", "role": "caution"},
    ],
)


GRAPHICAL_STAGE_ZERO_GROUPS = [
    {
        "heading": "PROGRAMME",
        "role": "evidence",
        "items": [
            "Empiricism controls factual claims through possible experience.",
            "Modern logic exposes form concealed by ordinary grammar.",
            "Philosophy clarifies scientific language rather than adding rival facts.",
        ],
    },
    {
        "heading": "MEANING DIVISION",
        "role": "mechanism",
        "items": [
            "Analytic propositions are necessary and non-factual.",
            "Synthetic propositions are contingent and empirically answerable.",
            "Cognitive meaning is not the same as truth, proof or total significance.",
        ],
    },
    {
        "heading": "HISTORICAL CAUTIONS",
        "role": "outcome",
        "items": [
            "Schlick, Carnap and Neurath did not retain one unchanged formula.",
            "Ayer popularised and revised the doctrine in an English setting.",
            "Unity of science was an ambition with internal limits and disputes.",
        ],
    },
]
