"""Durable learner-v2 content and master-flow specification for Kant."""

from __future__ import annotations


def visual(title: str, caption: str, *lines: str) -> dict[str, object]:
    return {"title": title, "caption": caption, "lines": list(lines)}


def session(
    title: str,
    plain: str,
    technical: str,
    answer: str,
    keywords: list[str],
    usage: str,
    mechanism: str,
    consequence: str,
    trap: str,
    objection: str,
    reply: str,
    limit: str,
    exam: str,
    revision: list[str],
    visuals: list[dict[str, object]],
) -> dict[str, object]:
    return {
        "title": title,
        "plain": plain,
        "technical": technical,
        "answer": answer,
        "keywords": keywords,
        "usage": usage,
        "mechanism": mechanism,
        "consequence": consequence,
        "trap": trap,
        "objection": objection,
        "reply": reply,
        "limit": limit,
        "exam": exam,
        "revision": revision,
        "visuals": visuals,
    }


SESSION_SPECS = (
    session(
        "The Critical Project: From Rationalist Dogma and Humean Scepticism to Critique",
        "Kant asks how necessary knowledge can be informative without claiming access to reality beyond experience.",
        "Critical philosophy is transcendental inquiry into the a priori conditions that make possible experience and objective knowledge possible; it accepts sensory content from empiricism, a priori form from rationalism, and limits theoretical cognition to phenomena.",
        "Kant reconciles rationalism and empiricism by making a priori form the condition of experiential objectivity while denying that pure reason can convert those forms into knowledge of noumena.",
        [
            "critical philosophy",
            "transcendental inquiry",
            "Hume's challenge",
            "Copernican revolution",
            "possible experience",
            "phenomenal knowledge",
        ],
        "Begin with the rationalist claim to necessity and Hume's denial that experience yields necessity; then state Kant's transcendental solution and its phenomenal limit.",
        "Sensory matter is received under space and time, synthesised through categories, and pursued toward unity by reason.",
        "The system secures empirical objectivity while replacing dogmatic metaphysics with a critique of reason's powers and limits.",
        "Do not call Kant a half-rationalist, half-empiricist compromise or say that the private mind creates empirical objects.",
        "If objects conform to our cognitive conditions, Kant may appear to secure only a world-for-us and not reality itself.",
        "Kant replies that knowledge requires conditions of possible experience, not a God's-eye comparison with things as they are independently of every knower.",
        "The reply secures empirical realism but leaves the status and affection of things in themselves contested.",
        "Use the architecture sensibility -> understanding -> reason, then evaluate the gain in objectivity against the noumenal limit.",
        [
            "All cognition begins with experience, but not all arises from experience.",
            "Transcendental asks for conditions of possible experience; transcendent exceeds experience.",
            "Empirical realism and transcendental idealism are complementary, not contradictory.",
        ],
        [
            visual(
                "Rationalism-Empiricism problem and Kantian critical synthesis",
                "Kant preserves each predecessor's insight while rejecting its unrestricted claim.",
                "RATIONALISM                         EMPIRICISM / HUME",
                "necessity, universality             sensory content, no observed necessity",
                "dogmatic metaphysics                causality reduced to custom",
                "             \\                     /",
                "              \\                   /",
                "               v                 v",
                "                 KANTIAN CRITIQUE",
                "a priori forms + categories organise sensory matter",
                "necessity is valid for possible experience, not noumena",
            ),
            visual(
                "Single architecture of cognition",
                "Each faculty has a legitimate role and a characteristic danger.",
                "SENSIBILITY -> gives intuitions in SPACE and TIME",
                "      |",
                "      v",
                "UNDERSTANDING -> synthesises through CATEGORIES -> objective experience",
                "      |",
                "      v",
                "REASON -> seeks the UNCONDITIONED -> Soul / World / God",
                "      | legitimate: regulative unity",
                "      + illegitimate: constitutive metaphysics -> illusion",
            ),
            visual(
                "Full Philosophy Optional answer spine",
                "A high-scoring Kant answer reconstructs the argument before evaluating it.",
                "DIRECTIVE -> precise thesis -> definition -> numbered argument",
                "         -> named text/example -> scope condition -> objection",
                "         -> best Kantian reply -> residual tension -> graded verdict",
                "",
                "CRITICISM MAP",
                "Hume: necessity not sensed | Hegel: unknowable beyond unstable",
                "Strawson: deduction overreaches | Jacobi: affection tension",
                "KANTIAN REPLY: conditions of objectivity, not noumenal description",
            ),
        ],
    ),
    session(
        "Synthetic A Priori Judgments and the Copernican Revolution",
        "Kant's central puzzle is how a judgment can add knowledge yet be necessarily true before particular experience.",
        "A synthetic a priori judgment is ampliative because its predicate is not contained in its subject, yet necessary and universal because its warrant rests on a priori cognitive conditions rather than induction.",
        "Synthetic a priori judgments are possible because objects of possible experience must conform to the mind's a priori forms, so mathematics and fundamental natural principles articulate conditions under which anything can appear as an object for us.",
        [
            "analytic",
            "synthetic",
            "a priori",
            "a posteriori",
            "synthetic a priori",
            "Copernican revolution",
        ],
        "Define analytic and synthetic judgments, distinguish a priori from a posteriori warrant, identify the synthetic a priori class through mathematics and causality, explain the Copernican revolution, and end with its restriction to appearances.",
        "The knower supplies universal forms to sensory matter, making informative necessity possible for every object that can be experienced.",
        "Mathematics and principles such as every event has a cause become objectively valid without becoming truths about things in themselves.",
        "Do not treat every a priori claim as analytic or present 7 + 5 = 12 as an empirical generalisation.",
        "Non-Euclidean geometry and modern physics weaken Kant's chosen scientific examples.",
        "Kant's deeper claim concerns enabling forms of experience; it need not stand or fall with every eighteenth-century example.",
        "The revised defence preserves the transcendental strategy but weakens claims of unrevisable content.",
        "For 'how possible' questions, use the regressive form: given objective knowledge, identify its necessary a priori conditions.",
        [
            "Analytic concerns containment; synthetic concerns ampliation.",
            "A priori concerns warrant independent of particular experience, not temporal innateness.",
            "The revolution concerns objects of experience conforming to cognition.",
        ],
        [
            visual(
                "Judgment matrix: analytic/synthetic x a priori/a posteriori",
                "The central class is informative and necessary at once.",
                "+----------------+--------------------------+---------------------------+",
                "|                | A PRIORI                 | A POSTERIORI              |",
                "+----------------+--------------------------+---------------------------+",
                "| ANALYTIC       | predicate contained      | no genuine Kantian class  |",
                "|                | 'Bodies are extended'    |                           |",
                "+----------------+--------------------------+---------------------------+",
                "| SYNTHETIC      | 7 + 5 = 12               | 'This table is brown'     |",
                "|                | Every event has a cause  | informative, contingent   |",
                "+----------------+--------------------------+---------------------------+",
            ),
            visual(
                "Copernican revolution",
                "Kant reverses the assumed direction of fit to explain a priori knowledge.",
                "OLD ASSUMPTION",
                "mind must conform to independently structured objects",
                "                 | necessity cannot be read from experience",
                "                 v",
                "KANT'S REVERSAL",
                "objects AS EXPERIENCED conform to space, time and categories",
                "                 |",
                "                 v",
                "synthetic a priori validity within possible experience",
            ),
        ],
    ),
    session(
        "Space and Time: Pure Forms of Sensible Intuition",
        "Space and time are the unavoidable lenses through which sensory objects are given, not items discovered among those objects.",
        "In the Transcendental Aesthetic, space is the pure a priori form of outer sense and time the pure a priori form of inner sense and thereby of all representations; each is a singular intuition rather than a discursive concept.",
        "Space and time are empirically real because every appearance must be spatially or temporally ordered, yet transcendentally ideal because neither can be attributed to things as they are independently of our sensibility.",
        [
            "Transcendental Aesthetic",
            "form of intuition",
            "outer sense",
            "inner sense",
            "empirical reality",
            "transcendental ideality",
        ],
        "Define form of intuition, distinguish outer and inner sense, reconstruct the a priori and intuitive arguments, then state empirical reality plus transcendental ideality.",
        "Space and time precede and organise sensory relations, allowing geometry, arithmetic, motion and ordered experience.",
        "Kant rejects both their treatment as independent containers and their reduction to empirical abstractions.",
        "Do not call them innate images, empirical concepts, illusions or properties of things in themselves.",
        "Their subject-dependence appears to make experience merely subjective, while non-Euclidean geometry and relativity pressure Kant's scientific illustrations.",
        "The forms are intersubjective conditions of human experience, not private inventions; the historically informed defence separates the transcendental argument from the claim that physical geometry must be Euclidean.",
        "Kant does not independently prove that every possible rational sensibility must share our forms.",
        "For 15/20 marks, distinguish metaphysical exposition, transcendental exposition, and the two-sided verdict of ideality and reality.",
        [
            "Space: outer sense; time: inner sense and all representations.",
            "One space/time with parts within it indicates intuition, not a concept with instances.",
            "Empty space/time can be represented; objects without them cannot be represented.",
        ],
        [
            visual(
                "Space and time as forms of intuition",
                "The forms order what is given without describing things in themselves.",
                "SENSORY MATTER",
                "     |",
                "     +--> OUTER SENSE -> SPACE -> coexistence / geometry",
                "     |",
                "     +--> INNER SENSE -> TIME -> succession / arithmetic",
                "                              -> every representation is temporal",
                "",
                "EMPIRICALLY REAL: valid for every appearance",
                "TRANSCENDENTALLY IDEAL: not predicates of things in themselves",
            ),
            visual(
                "Why space and time are a priori intuitions",
                "Kant combines priority arguments with singular-whole arguments.",
                "A PRIORI",
                "1. outer/inner ordering presupposes space/time",
                "2. objects may be removed; the forms cannot be removed",
                "",
                "INTUITIVE, NOT CONCEPTUAL",
                "3. one space and one time; regions/periods are limitations within them",
                "4. infinite magnitude is represented as given, not built from instances",
            ),
        ],
    ),
    session(
        "Categories, Synthesis and the Transcendental Unity of Apperception",
        "Categories are the understanding's a priori rules for combining the sensory manifold into one objective experience unified by transcendental apperception.",
        "Categories are twelve pure concepts of the understanding derived from functions of judgment; synthesis combines the manifold, while transcendental apperception is the formal unity expressed by the 'I think' that must be able to accompany every representation.",
        "The Transcendental Deduction justifies categories by showing that unified self-conscious experience is possible only through rule-governed synthesis, so the categories constitute objects of experience without depicting noumenal things.",
        [
            "category",
            "function of judgment",
            "synthesis",
            "transcendental deduction",
            "apperception",
            "objective unity",
        ],
        "List all twelve categories in four triads, distinguish identification from justification, and reconstruct the manifold -> synthesis -> apperception -> object argument.",
        "The same rules that unite representations in one consciousness also establish an objective order distinguishable from private association.",
        "Categories are necessary conditions of experience, not innate pictures copied onto independent reality.",
        "Do not infer a substantial soul from the 'I think' or apply the categories to noumena.",
        "The Deduction is notoriously difficult and may seem to infer objective validity from a requirement of self-consciousness.",
        "Kant's reply is that objectivity is not added after representations are unified; objective synthesis and apperceptive unity are two aspects of one rule-governed act.",
        "The argument secures categories for experience only if Kant's account of judgment and self-consciousness is exhaustive.",
        "For an exam answer, separate the metaphysical deduction, transcendental deduction, and limitation to possible experience.",
        [
            "Intuitions without concepts are blind; concepts without intuitions are empty.",
            "Apperception is a formal condition, not Hume's empirical bundle or Descartes' substance.",
            "The Deduction answers quid juris: by what right do pure concepts apply?",
        ],
        [
            visual(
                "All twelve categories in four grouped cards",
                "Each group contains three complete category labels.",
                "+-- QUANTITY ----------------------+",
                "| Unity | Plurality | Totality      |",
                "+----------------------------------+",
                "+-- QUALITY -----------------------+",
                "| Reality | Negation | Limitation   |",
                "+----------------------------------+",
                "+-- RELATION ------------------------------------------------------+",
                "| Inherence and Subsistence (substance/accident)                   |",
                "| Causality and Dependence (cause/effect) | Community (reciprocity)|",
                "+------------------------------------------------------------------+",
                "+-- MODALITY ------------------------------------------------------+",
                "| Possibility-Impossibility | Existence-Non-existence             |",
                "| Necessity-Contingency                                           |",
                "+------------------------------------------------------------------+",
            ),
            visual(
                "Unity of apperception and objective synthesis",
                "The 'I think' requires, rather than observes, rule-governed unity.",
                "MANIFOLD OF INTUITION",
                "          | synthesis: apprehension / reproduction / recognition",
                "          v",
                "RULE-GOVERNED COMBINATION THROUGH CATEGORIES",
                "          |",
                "          v",
                "'I THINK' CAN ACCOMPANY ALL REPRESENTATIONS",
                "          |",
                "          v",
                "ONE OBJECTIVE EXPERIENCE FOR ONE SELF-CONSCIOUSNESS",
            ),
        ],
    ),
    session(
        "Schematism: How Pure Categories Apply to Temporal Appearances",
        "A pure category and a sensory appearance are unlike, so Kant introduces a temporal rule that can connect them.",
        "A transcendental schema is a rule of productive imagination that determines time in a manner homogeneous with a category as an a priori rule and with appearances because every representation occurs in time; it is a procedure, not a mental image.",
        "Schematism converts logical functions into rules of temporal application, explaining how the Deduction's entitlement becomes usable for appearances while leaving unschematised categories without objective sense.",
        [
            "schema",
            "productive imagination",
            "time-determination",
            "rule not image",
            "heterogeneity",
            "application",
        ],
        "State the heterogeneity problem, explain why time is the third thing, distinguish schema from image, and give the four time architectures.",
        "Time-series, time-content, time-order and time-scope mediate Quantity, Quality, Relation and Modality.",
        "Pure categories acquire objective use only as schematised rules for appearances.",
        "Do not call a schema a picture resembling both a concept and an object.",
        "The bridge appears as obscure as the gap, and Kant calls schematism an art concealed in the depths of the human soul.",
        "The chapter's functional role is clear: without time-rules the Analogies and other Principles could not apply categories to experience.",
        "Functional necessity does not fully exhibit how productive imagination performs the mediation.",
        "Keep Core to rule, time and one example; reserve detailed A/B textual disputes for Advanced.",
        [
            "Schema is a rule/procedure; image is a determinate product.",
            "Number schematises Quantity; degree schematises Quality.",
            "Relation becomes permanence, succession by rule and reciprocal coexistence.",
        ],
        [
            visual(
                "The schematism bridge",
                "Time is the shared medium because every representation is temporal.",
                "PURE CATEGORY                 APPEARANCE",
                "intellectual / universal      sensible / particular",
                "          \\                    /",
                "           \\                  /",
                "            v                v",
                "       TRANSCENDENTAL SCHEMA",
                "       rule of time-determination",
                "       category-side: a priori rule",
                "       intuition-side: every appearance is in time",
            ),
            visual(
                "Four time architectures",
                "The groups of categories become distinct modes of temporal determination.",
                "QUANTITY -> time-series -> NUMBER",
                "QUALITY  -> time-content -> DEGREE / intensive magnitude",
                "RELATION -> time-order -> permanence / succession / coexistence",
                "MODALITY -> time-scope -> some time / determinate time / all times",
            ),
        ],
    ),
    session(
        "Analogies of Experience: Substance, Causality and Community",
        "The Analogies of Experience are a priori principles that determine objective duration, succession and simultaneity through substance, causality and reciprocal community.",
        "The Analogies are principles that determine duration through permanence of substance, objective succession through causality, and simultaneity through reciprocal community; they constitute experience's temporal order without predicting particular empirical events.",
        "Kant answers Hume by arguing that causality is not inferred from repetition but presupposed in judging a succession as an objective event, though particular causal laws remain empirical.",
        [
            "Analogies of Experience",
            "permanence",
            "objective succession",
            "causal rule",
            "community",
            "time cannot be perceived",
        ],
        "Define the three Analogies of Experience through permanence of substance, causal succession and reciprocal community; use the house/ship contrast to explain objective order and then qualify Kant's response to Hume.",
        "Persistent substance, irreversible succession under a rule, and reciprocal interaction act as proxies for duration, succession and simultaneity.",
        "Experienced nature becomes a public temporal order rather than a private sequence of perceptions.",
        "Do not claim that Kant derives particular causal laws a priori or that every sequence of perceptions is an event.",
        "Strawson argues that an involuntary order of apprehension does not by itself establish natural causal necessity.",
        "The Kantian reply says objective temporal placement requires a rule stronger than subjective association, while empirical inquiry still discovers the particular cause.",
        "The reply establishes conceptual entitlement more securely than it proves any one law of nature.",
        "In Hume comparisons, locate the exact shift from observed conjunction to conditions of objective time-determination.",
        [
            "First Analogy: substance persists through alteration.",
            "Second Analogy: every event follows according to a causal rule.",
            "Third Analogy: simultaneous substances stand in reciprocal community.",
        ],
        [
            visual(
                "Three Analogies and the modes of time",
                "Each principle supplies a perceptible proxy for an unperceivable time-relation.",
                "TIME ITSELF CANNOT BE PERCEIVED",
                "        |",
                "        +--> DURATION -> permanence of SUBSTANCE",
                "        +--> SUCCESSION -> event ordered by CAUSAL RULE",
                "        +--> SIMULTANEITY -> reciprocal COMMUNITY",
            ),
            visual(
                "House and ship: subjective and objective succession",
                "The Second Analogy distinguishes chosen scanning from an event's fixed order.",
                "HOUSE",
                "roof -> door or door -> roof | reversible apprehension",
                "coexisting object; sequence belongs to my inspection",
                "",
                "SHIP DOWNSTREAM",
                "upstream -> downstream | irreversible objective succession",
                "an event must be located through a rule: cause and effect",
            ),
        ],
    ),
    session(
        "Phenomena, Noumena and Empirical Realism",
        "We know things only as they appear under our forms, while the notion of a thing apart from those forms marks a limit rather than a second object of science.",
        "A phenomenon is an object of possible experience structured by space, time and categories; a noumenon in the negative sense is a thing considered insofar as it is not an object of sensible intuition and functions as a limiting concept, not theoretical knowledge.",
        "Kant combines transcendental idealism with empirical realism: appearances are objective and public within experience, although categories cannot be extended to things in themselves.",
        [
            "phenomenon",
            "noumenon",
            "thing in itself",
            "negative limiting concept",
            "empirical realism",
            "transcendental idealism",
        ],
        "Define both sides, state the negative role of noumenon, explain empirical realism, and evaluate the two-world/two-aspect and affection tensions cautiously.",
        "Cognitive conditions establish the knowable phenomenal domain and simultaneously forbid constitutive claims beyond it.",
        "Science is secured, Cartesian inner-world priority is challenged, and speculative metaphysics is bounded.",
        "Do not identify noumena with Plato's knowable Forms or say that appearances are private illusions.",
        "Hegel asks how Kant can draw a boundary around what is unknowable, while Jacobi asks how unknown things can affect sensibility if causality applies only to appearances.",
        "Kant can treat noumenon negatively as a boundary concept and avoid claiming positive noumenal causation.",
        "The negative reading reduces contradiction but leaves the source of sensory matter under-described.",
        "Use 'two aspects' as a cautious interpretive option, not as uncontested Kantian doctrine.",
        [
            "Phenomena are appearances, not deceptive seeming.",
            "Noumenon is thinkable negatively but not knowable through theoretical reason.",
            "The Refutation of Idealism proves empirically external objects, not noumenal objects.",
        ],
        [
            visual(
                "Phenomenon-noumenon boundary",
                "The boundary limits category-use without denying empirical objectivity.",
                "KNOWABLE DOMAIN: POSSIBLE EXPERIENCE",
                "sensory matter -> space/time -> categories -> PHENOMENA",
                "science, causal law, public objects, empirical realism",
                "================ CRITICAL BOUNDARY ================",
                "THINKABLE LIMIT, NOT THEORETICAL KNOWLEDGE",
                "NOUMENON / THING IN ITSELF in the negative sense",
                "no legitimate spatial, temporal, causal or substantial predicates",
            ),
            visual(
                "Refutation of problematic idealism",
                "Kant reverses Descartes by making inner time-determination depend on outer permanence.",
                "DETERMINATE AWARENESS OF MY STATES IN TIME",
                "                    | needs something persistent",
                "                    v",
                "PERSISTENT CANNOT BE MERELY ANOTHER INNER STATE",
                "                    |",
                "                    v",
                "EMPIRICALLY EXTERNAL OBJECTS CONDITION INNER EXPERIENCE",
            ),
        ],
    ),
    session(
        "Ideas of Reason, Transcendental Illusion and the Paralogisms",
        "Understanding organises experience, whereas reason asks for a complete, unconditioned ground that experience can never present as an object.",
        "The transcendental Ideas of soul, world and God express reason's demand for the unconditioned unity of inner conditions, cosmological conditions and all conditions; their regulative use guides systematic inquiry, while constitutive use falsely treats them as known objects.",
        "Transcendental illusion is natural and persistent because reason cannot stop seeking completion, yet critique can prevent the slide from useful systematic unity to metaphysical claims about soul-substance, world-totality and God.",
        [
            "Ideas of Reason",
            "unconditioned",
            "regulative",
            "constitutive",
            "transcendental illusion",
            "paralogism",
        ],
        "Distinguish understanding from reason, map soul/world/God, define both uses, explain persistent illusion, and use the Paralogisms to show the soul error.",
        "Reason projects complete explanatory unity and then mistakes a methodological ideal for a constitutively given object.",
        "The Ideas organise inquiry fruitfully but generate paralogisms, antinomies and failed theology when reified.",
        "Do not say the Ideas are categories, empirical hypotheses or useless fictions.",
        "If regulative Ideas have no object known to correspond to them, their systematic authority may appear merely heuristic.",
        "Kant replies that reason's demand for unity is a necessary norm of inquiry even though it cannot certify transcendent objects.",
        "The norm guides discovery but cannot independently prove that nature forms one complete rational system.",
        "Use the soul's Paralogisms briefly unless the question directly asks rational psychology.",
        [
            "Understanding supplies rules to appearances; reason seeks principles and completion.",
            "Regulative means guide inquiry; constitutive means determine an object.",
            "The logical 'I think' cannot be converted into a simple immortal soul.",
        ],
        [
            visual(
                "Soul, world and God as Ideas of Reason",
                "Each Idea projects an unconditioned totality that cannot be given in experience.",
                "REASON SEEKS THE UNCONDITIONED",
                "        |",
                "        +--> SOUL -> complete unity of inner conditions",
                "        |             danger: 'I think' -> soul-substance",
                "        +--> WORLD -> complete series of cosmological conditions",
                "        |             danger: antinomies",
                "        +--> GOD -> complete ground of all conditions",
                "                      danger: speculative proofs",
            ),
            visual(
                "Regulative and constitutive uses",
                "The same Idea can guide inquiry legitimately or generate illusion when reified.",
                "REGULATIVE USE",
                "'Investigate AS IF nature formed maximal systematic unity'",
                "guide / heuristic / orientation -> legitimate",
                "",
                "CONSTITUTIVE USE",
                "'Soul, world-totality or God is known as an object'",
                "object-claim beyond intuition -> transcendental illusion",
            ),
        ],
    ),
    session(
        "The Four Antinomies and the Different Forms of Their Resolution",
        "Kant's four antinomies are thesis-antithesis conflicts generated when reason treats the complete world-series as a finished object beyond possible experience.",
        "An antinomy is a thesis-antithesis pair for which pure reason constructs apparently valid proofs after extending cosmological principles beyond possible experience; the first two are mathematical and the last two dynamical.",
        "Transcendental idealism resolves the mathematical antinomies by rejecting the shared assumption of a given world-whole, while it reconciles the dynamical antinomies by distinguishing phenomenal natural conditions from a merely intelligible standpoint.",
        [
            "antinomy",
            "thesis",
            "antithesis",
            "mathematical antinomies",
            "dynamical antinomies",
            "transcendental idealist resolution",
        ],
        "Define antinomy, state all four thesis-antithesis pairs, distinguish mathematical from dynamical antinomies, explain their different resolutions, and evaluate the room secured for freedom without claiming knowledge of noumena.",
        "Reason demands the unconditioned, turns a never-completed experiential series into a total object, and proves opposed predicates of that pseudo-object.",
        "The antinomies expose speculative metaphysics' limit and make freedom compatible with phenomenal natural causality at an intelligible boundary.",
        "Do not flatten all four into 'both false' or 'both true', and do not treat the fourth antinomy as a proof of God.",
        "The resolution may look like avoiding contradiction by assigning opposed claims to an unknowable domain.",
        "Kant answers that the contradiction arose from transcendental realism; once appearances are not things in themselves, the shared premise dissolves or the standpoints separate.",
        "The dynamical resolution makes freedom thinkable rather than theoretically known, leaving its positive content to practical philosophy.",
        "A 20-marker must spend more space on construction and resolution than on listing the pairs.",
        [
            "First: world beginning/limits versus no beginning/limits.",
            "Second: simple parts versus no simple parts.",
            "Third: freedom plus nature versus universal natural causality.",
            "Fourth: necessary being versus no necessary being.",
        ],
        [
            visual(
                "Antinomy 1: magnitude of the world",
                "Both sides assume the world-series is a completed object.",
                "THESIS: The world has a beginning in time and limits in space.",
                "ANTITHESIS: The world has no beginning or spatial limits; it is infinite.",
                "RESOLUTION: the world-whole is not given as finite or completed infinite.",
            ),
            visual(
                "Antinomy 2: composition of the world",
                "The dispute illegitimately treats appearances as a completed totality of parts.",
                "THESIS: Every composite consists ultimately of simple parts.",
                "ANTITHESIS: Nothing simple exists; every composite is further divisible.",
                "RESOLUTION: neither predicate describes a world-whole given in experience.",
            ),
            visual(
                "Antinomy 3: freedom and natural causality",
                "The dynamical opposition can be separated by standpoint.",
                "THESIS: Causality through freedom is required besides natural causality.",
                "ANTITHESIS: There is no freedom; every event occurs by laws of nature.",
                "RESOLUTION: natural determination for appearances; intelligible freedom is thinkable.",
            ),
            visual(
                "Antinomy 4: necessary being",
                "The resolution permits a thought-limit but supplies no theoretical proof.",
                "THESIS: An absolutely necessary being belongs to the world as part or cause.",
                "ANTITHESIS: No absolutely necessary being exists in or beyond the world.",
                "RESOLUTION: empirical contingency remains; a noumenal ground is merely thinkable.",
            ),
            visual(
                "Why the two resolutions differ",
                "Mathematical totalisation fails; dynamical predicates can be standpoint-qualified.",
                "ANTINOMIES 1-2: MATHEMATICAL",
                "same false presupposition -> no given finite/infinite or simple/composite whole",
                "",
                "ANTINOMIES 3-4: DYNAMICAL",
                "phenomenal conditions remain valid",
                "intelligible freedom/ground is possible but not theoretically known",
            ),
        ],
    ),
    session(
        "Critique of the Three Proofs for God and the Final Critical Balance",
        "Kant does not prove atheism; he argues that theoretical reason cannot demonstrate God by turning a concept, causal series or observed order into a necessary creator.",
        "The ontological proof fails because existence is not a real predicate adding content to a concept; the cosmological proof illicitly extends causal reasoning beyond experience and depends on the ontological identification of necessary being with the ens realissimum; the design proof reaches at most an architect and borrows the other proofs to reach a necessary creator.",
        "Kant's critique removes God from theoretical knowledge rather than from thought or practical faith, completing a system that secures phenomenal objectivity precisely by refusing constitutive claims beyond possible experience.",
        [
            "ontological proof",
            "existence is not a real predicate",
            "cosmological proof",
            "physico-theological proof",
            "architect not creator",
            "theoretical limit",
        ],
        "Treat each proof as argument -> Kantian objection -> residual value, then distinguish theoretical agnosticism from atheism and conclude with the critical balance.",
        "All three routes attempt to turn thought beyond experience into constitutive knowledge, and the latter two ultimately require the ontological step.",
        "Speculative theology is bounded, while practical philosophy may assign God a different postulatory role.",
        "Do not say Kant disproves God's existence or let the practical postulate become a Paper II detour.",
        "Modal ontological arguments dispute whether necessary existence can be analysed as an ordinary predicate, while design may retain probabilistic force.",
        "Kant's objection decisively blocks the classical concept-to-existence inference and correctly limits what finite order can establish.",
        "The critique is strongest against demonstration and weaker against non-demonstrative religious inference.",
        "For 'critically examine', reconstruct the classical proof accurately before presenting Kant, an objection, reply and graded verdict.",
        [
            "Existence posits an object; it does not enlarge its concept.",
            "Cosmological reasoning both overextends causality and covertly returns to ontology.",
            "Design suggests order at most; it cannot establish an infinite necessary creator.",
        ],
        [
            visual(
                "Ontological proof: concept cannot yield actuality",
                "Kant blocks the inference at the claim that existence is a perfection.",
                "PROOF: God = most perfect being -> existence is perfection -> God exists",
                "KANT: existence is not a content-adding real predicate",
                "100 possible thalers and 100 actual thalers have the same concept",
                "RESIDUAL: a concept may be coherent without being instantiated",
            ),
            visual(
                "Cosmological proof: causal overreach plus hidden ontology",
                "The proof cannot identify a necessary ground as God without the failed first proof.",
                "PROOF: contingent existence -> necessary ground -> God",
                "KANT 1: causality is valid only within possible experience",
                "KANT 2: necessary being = ens realissimum repeats ontological reasoning",
                "RESIDUAL: contingency can motivate inquiry, not theoretical demonstration",
            ),
            visual(
                "Physico-theological proof: architect, not necessary creator",
                "Observed order cannot carry the conclusion assigned to it.",
                "PROOF: purposive order -> intelligent designer -> creator God",
                "KANT: order supports at most a powerful architect of given material",
                "to reach creator/necessity it borrows cosmological and ontological steps",
                "RESIDUAL: limited analogical or heuristic force, not apodictic proof",
            ),
            visual(
                "Critical balance and comparison",
                "Kant's gain and cost can be stated on matched axes.",
                "RATIONALISM: a priori necessity, but transcendent dogma",
                "EMPIRICISM: sensory content, but necessity reduced to habit",
                "KANT: a priori conditions + sensory matter -> phenomenal objectivity",
                "GAIN: mathematics/science and empirical realism",
                "LIMIT: no theoretical knowledge of soul, world-whole or God",
                "TENSION: unknowable noumenon and the affection problem",
            ),
        ],
    ),
)


ASCII_PANELS = (
    {
        "title": "Critical starting problem and the rationalism-empiricism synthesis",
        "structural_type": "conflict-synthesis-and-faculty-rail",
        "sessions": [1],
        "lines": [
            "CENTRAL QUESTION: How can cognition be informative, necessary and objectively valid?",
            "RATIONALISM -> a priori necessity, but dogmatic claims about soul, world and God",
            "EMPIRICISM / HUME -> sensory content, but no experienced necessary connection",
            "KANTIAN CRITIQUE -> sensory matter + a priori form, restricted to possible experience",
            "COPERNICAN REVOLUTION -> objects AS EXPERIENCED conform to cognitive conditions",
            "SENSIBILITY -> intuitions in space/time -> UNDERSTANDING -> categories and objects",
            "UNDERSTANDING -> REASON -> Ideas of Soul, World and God; drive to the unconditioned",
            "TRANSCENDENTAL = conditions of possible experience; TRANSCENDENT = beyond experience",
            "RESULT -> empirical realism + transcendental idealism + limit on theoretical reason",
            "ANSWER LINE -> Kant secures objectivity by making its a priori conditions mind-given.",
        ],
    },
    {
        "title": "Synthetic a priori judgments and the Copernican explanation",
        "structural_type": "judgment-matrix-and-reversal-flow",
        "sessions": [2],
        "lines": [
            "ANALYTIC -> predicate contained in subject; denial contradicts the concept",
            "SYNTHETIC -> predicate adds content; denial is not self-contradictory",
            "A PRIORI -> necessary/universal warrant independent of particular experience",
            "A POSTERIORI -> empirical, informative and contingent warrant",
            "ANALYTIC A PRIORI -> 'Bodies are extended'; ANALYTIC A POSTERIORI -> no Kantian class",
            "SYNTHETIC A POSTERIORI -> 'This table is brown'; informative but contingent",
            "SYNTHETIC A PRIORI -> 7 + 5 = 12; every event has a cause; informative + necessary",
            "HOW POSSIBLE? -> the mind supplies space, time and categories to every appearance",
            "MATHEMATICS / FUNDAMENTAL SCIENCE -> valid for objects of possible experience",
            "LIMIT -> no inference from these forms to things in themselves or transcendent objects",
        ],
    },
    {
        "title": "Transcendental Aesthetic: space and time as forms of intuition",
        "structural_type": "outer-inner-sense-map-and-argument-ledger",
        "sessions": [3],
        "lines": [
            "FORM OF INTUITION -> a priori way in which sensory matter can be given",
            "SPACE -> pure form of OUTER sense; coexistence, externality and geometry",
            "TIME -> pure form of INNER sense; succession and all representations",
            "A PRIORI ARGUMENT -> spatial/temporal ordering presupposes, not produces, the forms",
            "NECESSITY ARGUMENT -> empty space/time is representable; objects without them are not",
            "INTUITION ARGUMENT -> one space/time; regions and periods are limitations within it",
            "INFINITY ARGUMENT -> magnitude is represented as a given whole, not instances under a concept",
            "EMPIRICALLY REAL -> objectively valid for every appearance and possible experience",
            "TRANSCENDENTALLY IDEAL -> not properties of things in themselves",
            "OBJECTION -> modern geometry/science pressures examples, not the whole transcendental strategy",
        ],
    },
    {
        "title": "Categories, synthesis and transcendental unity of apperception",
        "structural_type": "four-card-category-map-and-deduction-flow",
        "sessions": [4],
        "lines": [
            "QUANTITY -> Unity | Plurality | Totality",
            "QUALITY -> Reality | Negation | Limitation",
            "RELATION -> Inherence/Subsistence | Causality/Dependence | Community/Reciprocity",
            "MODALITY -> Possibility/Impossibility | Existence/Non-existence | Necessity/Contingency",
            "METAPHYSICAL DEDUCTION -> identifies categories from functions of judgment",
            "TRANSCENDENTAL DEDUCTION -> justifies their objective application",
            "MANIFOLD -> SYNTHESIS under rules -> 'I THINK' can accompany each representation",
            "APPERCEPTION -> formal unity of self-consciousness, not empirical ego or soul-substance",
            "OBJECTIVE UNITY -> the same rule unites representations as one experience of objects",
            "LIMIT -> categories constitute appearances only; they do not picture or determine noumena",
        ],
    },
    {
        "title": "Schematism: temporal bridge from pure category to appearance",
        "structural_type": "heterogeneity-bridge-and-time-architecture",
        "sessions": [5],
        "lines": [
            "PROBLEM -> pure intellectual category and sensible particular appearance are heterogeneous",
            "SCHEMA -> rule/procedure of productive imagination; never a determinate mental image",
            "WHY TIME? -> it is a priori like the category and contains every representation",
            "QUANTITY / time-series -> NUMBER through successive homogeneous addition",
            "QUALITY / time-content -> DEGREE or intensive magnitude",
            "RELATION / time-order -> permanence, succession by rule, reciprocal coexistence",
            "MODALITY / time-scope -> some time, determinate time, all times",
            "DEDUCTION proves THAT categories apply; SCHEMATISM explains HOW they apply",
            "UNSCHEMATISED CATEGORY -> logical function without objective sense for appearances",
            "RESIDUAL -> Kant calls the mediating operation an art concealed in the human soul",
        ],
    },
    {
        "title": "Analogies of Experience and Kant's precise answer to Hume",
        "structural_type": "three-proxy-time-map-and-house-ship-comparison",
        "sessions": [6],
        "lines": [
            "MASTER PREMISE -> time itself cannot be perceived; objective time needs proxies",
            "FIRST ANALOGY / duration -> substance persists while its states alter",
            "SECOND ANALOGY / succession -> every event follows according to a causal rule",
            "THIRD ANALOGY / simultaneity -> substances coexist through reciprocal community",
            "HOUSE -> viewing order is reversible; succession belongs to my apprehension",
            "SHIP DOWNSTREAM -> order is irreversible; an objective event requires a rule",
            "ANTI-HUME MOVE -> causality is a condition of judging objective succession, not habit",
            "QUALIFICATION -> particular causal laws remain empirical and require investigation",
            "STRAWSON OBJECTION -> involuntary order does not automatically prove natural necessity",
            "VERDICT -> Kant secures entitlement to causality more clearly than any particular law",
        ],
    },
    {
        "title": "Phenomena, noumena, empirical realism and the idealism boundary",
        "structural_type": "knowledge-boundary-and-refutation-flow",
        "sessions": [7],
        "lines": [
            "PHENOMENON -> object as given in space/time and thought through categories",
            "POSSIBLE EXPERIENCE -> knowable, public, causal and scientifically investigable domain",
            "NOUMENON NEGATIVELY -> thing considered apart from sensible intuition; limiting concept",
            "NOUMENON IS THINKABLE, NOT KNOWABLE -> no theoretical predicates from the categories",
            "TRANSCENDENTAL IDEALISM -> our forms condition appearances",
            "EMPIRICAL REALISM -> external objects are real within experience, not private illusions",
            "REFUTATION -> determinate inner time-awareness requires an empirically external permanent",
            "TWO-ASPECT READING -> one object considered as appearance and independently of our access",
            "HEGEL/JACOBI PRESSURE -> boundary knowledge and affection threaten internal consistency",
            "SAFE VERDICT -> negative limitation is defensible; positive noumenal causation is not",
        ],
    },
    {
        "title": "Ideas of Reason, regulative unity and natural transcendental illusion",
        "structural_type": "three-idea-tree-and-use-split",
        "sessions": [8],
        "lines": [
            "UNDERSTANDING -> supplies rules for appearances; REASON -> seeks the unconditioned",
            "SOUL -> projected complete unity of inner conditions",
            "WORLD -> projected complete totality of cosmological conditions",
            "GOD -> projected complete ground of all conditions and reality",
            "REGULATIVE USE -> guide inquiry toward systematic unity; legitimate 'as if'",
            "CONSTITUTIVE USE -> claim the Idea determines a known object; illegitimate",
            "TRANSCENDENTAL ILLUSION -> natural and persistent drive to reify completion",
            "PARALOGISM -> logical 'I think' is misread as simple, substantial, enduring soul",
            "VALUE -> systematic research and explanatory integration",
            "DANGER -> paralogisms, antinomies and speculative theology",
        ],
    },
    {
        "title": "Four cosmological antinomies and their differentiated resolutions",
        "structural_type": "four-pair-card-stack-and-resolution-split",
        "sessions": [9],
        "lines": [
            "1 THESIS -> beginning in time + spatial limit | ANTITHESIS -> infinite time/space",
            "2 THESIS -> composites end in simple parts | ANTITHESIS -> nothing simple exists",
            "3 THESIS -> freedom besides nature | ANTITHESIS -> universal natural causality",
            "4 THESIS -> absolutely necessary being | ANTITHESIS -> no necessary being",
            "SOURCE OF CONFLICT -> categories applied to the world-series as a completed whole",
            "MATHEMATICAL 1-2 -> reject shared assumption that a finite/infinite whole is given",
            "DYNAMICAL 3-4 -> phenomenal conditions and intelligible standpoint can be distinguished",
            "FREEDOM -> thinkable noumenally while every appearance remains naturally determined",
            "NECESSARY GROUND -> thinkable boundary, not theoretical proof of God",
            "SIGNIFICANCE -> indirect case for idealism and limit of speculative metaphysics",
        ],
    },
    {
        "title": "God-proof critique, evaluation ledger, traps, PYQs and answer spine",
        "structural_type": "stacked-proof-critique-and-exam-ledger",
        "sessions": [10],
        "lines": [
            "ONTOLOGICAL -> perfect concept includes existence | KANT -> existence adds no content",
            "100 possible/actual thalers -> same concept; actuality cannot be extracted analytically",
            "COSMOLOGICAL -> contingent exists, therefore necessary God | illicit causal extension",
            "COSMOLOGICAL DEPENDENCE -> necessary being = ens realissimum repeats ontological proof",
            "DESIGN -> order implies designer | at most an architect, not necessary creator",
            "DESIGN DEPENDENCE -> creator/necessity needs cosmological then ontological steps",
            "BOUNDARY -> theoretical proof fails; this is not a demonstration of atheism",
            "COMPARISON -> rationalist necessity + empiricist content under critical limitation",
            "PYQ ROUTES -> synthesis, space/time, apperception, antinomies, Hume and God proofs",
            "ANSWER SPINE -> thesis -> doctrine -> argument -> objection/reply -> qualified verdict",
            "FINAL VERDICT -> Kant gains phenomenal objectivity at the cost of noumenal agnosticism",
        ],
    },
)


REQUIRED_CORE_TERMS = (
    "synthetic a priori",
    "transcendental",
    "Copernican revolution",
    "analytic",
    "synthetic",
    "a priori",
    "a posteriori",
    "form of intuition",
    "outer sense",
    "inner sense",
    "empirical reality",
    "transcendental ideality",
    "category",
    "Unity",
    "Plurality",
    "Totality",
    "Reality",
    "Negation",
    "Limitation",
    "Inherence",
    "Causality",
    "Community",
    "Possibility",
    "Existence",
    "Necessity",
    "synthesis",
    "apperception",
    "schema",
    "phenomenon",
    "noumenon",
    "regulative",
    "constitutive",
    "transcendental illusion",
    "soul",
    "world",
    "God",
    "antinomies",
    "freedom",
    "necessary being",
    "existence is not a real predicate",
    "physico-theological",
)
