"""Authored learner-v2 data for Science and Technology Topics 01-05."""

from __future__ import annotations

import generate_science_and_technology_common as common
from science_and_technology_data_helpers import (
    FUSION_LIVE_ATTEMPTS,
    NUCLEAR_LIVE_ATTEMPTS,
    SPACE_LIVE_ATTEMPTS,
    panel,
)


def _topic_01() -> dict[str, object]:
    facts = [
        ("DoS-ISRO boundary", "The Department of Space is the Union-government policy umbrella, while ISRO is the public space agency that develops launch vehicles, spacecraft, applications and missions; the department and agency are not interchangeable."),
        ("Centre-function boundary", "VSSC leads launch-vehicle development, liquid-propulsion work is distributed across LPSC and IPRC, and SDSC-SHAR integrates and conducts launches; naming a centre does not transfer the mandate of the whole agency to it."),
        ("IN-SPACe boundary", "IN-SPACe is the single-window nodal agency under the Department of Space for promoting, authorising and supervising non-government space activity; it is not ISRO's commercial sales arm."),
        ("NSIL boundary", "NSIL is the public-sector commercial arm for launch, satellite, service and technology-transfer arrangements; commercial contracting is distinct from authorisation and supervision."),
        ("Policy-law boundary", "Indian Space Policy 2023 allocates institutional roles and opens participation, but it is executive policy rather than a comprehensive domestic space statute."),
        ("Launcher-spacecraft boundary", "A launch vehicle supplies propulsion to place a payload on a trajectory or into an orbit, whereas the spacecraft or satellite carries the mission payload and may use its own propulsion after separation."),
        ("Orbit-family boundary", "LEO, polar orbit, sun-synchronous orbit, geosynchronous orbit and geostationary orbit describe different geometry, altitude or timing properties; polar and sun-synchronous are not synonyms for every low orbit."),
        ("GTO-GEO boundary", "Geosynchronous Transfer Orbit is an elliptical intermediate orbit, while geostationary orbit is circular and equatorial; a launcher injection into GTO does not by itself place the spacecraft in its final geostationary slot."),
        ("PSLV role", "PSLV is the versatile operational workhorse used across Earth-observation, navigation and multi-payload missions; its name does not confine every mission to a polar orbit."),
        ("GSLV role", "GSLV uses an indigenous cryogenic upper stage for heavier communication-class missions to transfer orbit; cryogenic capability, orbit and payload class must be stated together."),
        ("LVM3 role", "LVM3 is India's heavier operational launcher and the base vehicle selected for human rating for Gaganyaan; an operational launcher and its human-rated configuration are distinct statuses."),
        ("SSLV role", "SSLV is a separate small-satellite launcher designed around smaller payloads and quicker, lower-infrastructure launch demand; it is not a PSLV variant."),
        ("Lineage-status boundary", "SLV-3 and ASLV are historical technology-learning vehicles, PSLV, GSLV and LVM3 are identified in the repository owner as operational, and approved future systems must not be placed in the same status column."),
        ("Propulsion-class boundary", "Solid, earth-storable liquid, cryogenic liquid-hydrogen and semi-cryogenic kerosene systems differ in propellants and operating role; a semi-cryogenic development programme is not a flying cryogenic stage."),
        ("Human-rating boundary", "Human rating adds margins, redundancy, health monitoring, benign failure behaviour and abort capability to a launcher system; it is a qualification process, not merely a strong flight record."),
        ("Launch-system boundary", "Sovereign access depends on vehicle reliability, manufacturing, integration bays, pads, range safety, propellant logistics and mission assurance; a rocket design alone does not establish launch cadence."),
        ("NGLV status boundary", "The Next Generation Launch Vehicle is a Cabinet-approved development programme with a planned reusable or recoverable first-stage architecture; approval is not a flight, operational service or demonstrated payload performance."),
        ("Infrastructure-status boundary", "The Third Launch Pad and Kulasekarapattinam launch complex belong to future capacity expansion; approved or under-construction infrastructure is not commissioned infrastructure."),
        ("Technology-transfer boundary", "Transfer of SSLV technology to HAL is an industrial production and commercialisation arrangement; it does not mean that ISRO, IN-SPACe, NSIL and the State's safety responsibilities disappear."),
        ("Volatile launch-data boundary", "Payload capacity, configuration, launch outcome, fleet status, project cost, schedule and anomaly findings require a dated official ISRO, Department of Space or Cabinet source and must never be carried forward without that date."),
    ]
    traps = [
        "Do not merge the Department of Space with ISRO.",
        "Do not assign IN-SPACe's authorisation role to NSIL.",
        "Do not assign NSIL's commercial role to IN-SPACe.",
        "Do not call Indian Space Policy 2023 a statute.",
        "Do not merge a launch vehicle with its payload spacecraft.",
        "Do not treat GTO as the final geostationary orbit.",
        "Do not infer PSLV mission orbit only from its name.",
        "Do not call SSLV a PSLV variant.",
        "Do not list retired, operational and future vehicles together.",
        "Do not merge cryogenic and semi-cryogenic propulsion.",
        "Do not infer human rating from an ordinary success record.",
        "Do not infer cadence from vehicle design alone.",
        "Do not turn NGLV approval into demonstrated capability.",
        "Do not turn a launch-pad approval into commissioning.",
        "Do not rewrite technology transfer as complete privatisation.",
        "Do not invent or stale-date payload, cost, schedule or anomaly claims.",
    ]
    titles = [
        "Department agency and centre architecture",
        "IN-SPACe authorisation and supervision",
        "NSIL commercialisation boundary",
        "Policy treaty and domestic-law layers",
        "Launch vehicle spacecraft and payload chain",
        "LEO polar sun-synchronous and geosynchronous geometry",
        "Transfer orbit and final geostationary slot",
        "PSLV mission versatility",
        "GSLV cryogenic transfer-orbit role",
        "LVM3 heavy lift and human-rating boundary",
        "SSLV small-launch market logic",
        "SLV ASLV operational fleet and future lineage",
        "Solid liquid cryogenic and semi-cryogenic propulsion",
        "Launch cadence infrastructure and mission assurance",
        "NGLV pads technology transfer and dated-status audit",
    ]
    routes = [
        "Map DoS, ISRO and centres before discussing capability.",
        "Define promotion, authorisation and continuing supervision precisely.",
        "Separate commercial execution from public regulation and R&D.",
        "Distinguish executive policy from treaty obligations and statute.",
        "Trace launcher, separation, spacecraft and mission payload.",
        "Classify orbit by altitude, inclination, period and solar geometry.",
        "Show GTO injection before spacecraft-led circularisation.",
        "Explain PSLV by mission flexibility rather than its label alone.",
        "Link GSLV's cryogenic upper stage to transfer-orbit missions.",
        "Separate operational LVM3 from the human-rating process.",
        "Explain why SSLV is a distinct vehicle and market architecture.",
        "Use a lineage with retired, operational and future status columns.",
        "Compare propellants and development status before claiming performance.",
        "Treat access to space as a vehicle-plus-infrastructure system.",
        "Close with approval, construction, transfer, flight and operation dates.",
    ]
    panels = [
        panel("Institutional command map", "hierarchy", [
            "DEPARTMENT OF SPACE -> policy umbrella and sovereign direction",
            "ISRO -> public R&D, launch vehicles, spacecraft and missions",
            "IN-SPACe -> promote, authorise and supervise non-government activity",
            "NSIL -> commercial contracts, services and technology transfer",
            "RULE -> institution names are not interchangeable",
        ], [facts[0][0], facts[2][0], facts[3][0]]),
        panel("Centre-to-launch chain", "process-flow", [
            "VSSC -> launch-vehicle design and development",
            "LPSC / IPRC -> liquid propulsion and propulsion testing roles",
            "SDSC-SHAR -> integration, range and launch operations",
            "MISSION CONTROL -> flight monitoring and decision chain",
            "RULE -> a centre function is not the whole ISRO mandate",
        ], [facts[1][0]]),
        panel("Policy and law stack", "layered-rail", [
            "OUTER-SPACE TREATIES -> international State obligations",
            "INDIAN SPACE POLICY 2023 -> executive role allocation",
            "IN-SPACe NORMS -> authorisation and supervision interface",
            "COMMERCIAL CONTRACT -> service and risk allocation",
            "GAP -> policy is not a comprehensive domestic space statute",
        ], [facts[4][0]]),
        panel("Launcher-payload separation", "process-flow", [
            "LAUNCH VEHICLE -> supplies ascent energy and guidance",
            "PAYLOAD FAIRING -> protects the mission payload",
            "SEPARATION -> launcher task and spacecraft task diverge",
            "SPACECRAFT -> carries payload and may raise or maintain orbit",
            "RULE -> rocket success and spacecraft service entry are separate",
        ], [facts[5][0]]),
        panel("Orbit vocabulary matrix", "comparison-table", [
            "LEO -> altitude class, often used by crew and Earth observation",
            "POLAR -> high-inclination ground-track geometry",
            "SUN-SYNCHRONOUS -> repeated local-solar-time crossing",
            "GSO -> orbital period tied to Earth's rotation",
            "GEO -> circular equatorial geosynchronous special case",
        ], [facts[6][0]]),
        panel("GTO-to-GEO rail", "process-flow", [
            "LAUNCHER ASCENT -> reaches transfer conditions",
            "GTO INJECTION -> elliptical intermediate orbit",
            "SPACECRAFT PROPULSION -> raises perigee and circularises",
            "GEO SLOT -> circular equatorial final service orbit",
            "TRAP -> GTO delivery is not direct GEO placement",
        ], [facts[7][0]]),
        panel("Operational launcher matrix", "comparison-table", [
            "PSLV -> versatile workhorse and mixed mission profiles",
            "GSLV -> cryogenic upper stage and transfer-orbit role",
            "LVM3 -> heavier operational class and human-rating base",
            "SSLV -> separate small-satellite launch architecture",
            "RULE -> role, propulsion, orbit and status must travel together",
        ], [facts[8][0], facts[9][0], facts[10][0], facts[11][0]]),
        panel("Lineage and status ladder", "timeline", [
            "SLV-3 -> experimental orbital-access learning",
            "ASLV -> intermediate technology-learning step",
            "PSLV / GSLV / LVM3 -> operational families in owner",
            "SSLV -> developed small-launch family with dated status needed",
            "NGLV -> approved future development, not an operational launcher",
        ], [facts[12][0], facts[16][0]]),
        panel("Propulsion comparison", "comparison-table", [
            "SOLID -> stored propellant and limited throttle control",
            "EARTH-STORABLE LIQUID -> ambient-temperature liquid pair",
            "CRYOGENIC -> liquid oxygen plus liquid hydrogen",
            "SEMI-CRYOGENIC -> liquid oxygen plus kerosene",
            "RULE -> propellant class does not prove flight status",
        ], [facts[13][0]]),
        panel("Human-rating gate", "causal-chain", [
            "RELIABLE LAUNCHER -> necessary but insufficient base",
            "MARGINS AND REDUNDANCY -> tolerate selected failures",
            "HEALTH MONITORING -> detect unsafe conditions",
            "ABORT CAPABILITY -> protect crew across ascent phases",
            "CERTIFICATION -> separate human-rated configuration",
        ], [facts[14][0]]),
        panel("Access-to-space system", "systems-map", [
            "VEHICLE -> propulsion, structure, avionics and guidance",
            "FACTORY -> repeatable stage and subsystem quality",
            "PAD / RANGE -> integration, safety and launch window",
            "MISSION ASSURANCE -> verification and anomaly closure",
            "OUTPUT -> cadence and customer confidence",
        ], [facts[15][0], facts[17][0]]),
        panel("Future-claim firewall", "answer-spine", [
            "DEFINE -> institution, vehicle, spacecraft, orbit and service",
            "CLASSIFY -> retired, operational, approved or under construction",
            "TRACE -> propulsion, infrastructure, integration and assurance",
            "SEPARATE -> technology transfer from authorisation and safety",
            "VERIFY -> dated official capacity, schedule and outcome source",
        ], [facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2018", "Prelims GS-I", "Compare PSLV and GSLV as Indian satellite launch vehicles.", "Verified routed objective concept; the official key was unavailable locally, so no answer letter is asserted.", [5, 7, 8, 9]),
        common.make_pyq_solution(facts, "2026", "Prelims GS-I", "Private-sector participation, IN-SPACe mandate and Indian space-startup achievements.", "Verified provisional routed concept; the local key is provisional and no answer letter is recorded or inferred.", [0, 2, 3, 4, 18]),
    ]
    return common.topic(
        1, "Space Programme: ISRO, Organisation and Launch Vehicles",
        "01_Space-Programme-ISRO-Launch-Vehicles", facts, traps,
        [
            (10, "Distinguish the roles of DoS, ISRO, IN-SPACe and NSIL.", [0, 1, 2, 3, 4]),
            (10, "Differentiate PSLV, GSLV, LVM3 and SSLV without reducing the comparison to payload size.", [5, 7, 8, 9, 10, 11]),
            (15, "Explain how propulsion and orbit requirements shape launcher choice.", [5, 6, 7, 8, 9, 10, 13]),
            (15, "Assess Indian space reform as institutional differentiation rather than privatisation.", [0, 2, 3, 4, 18]),
            (20, "Evaluate India's access-to-space ecosystem through vehicles, infrastructure, industry and mission assurance.", [8, 9, 10, 11, 15, 17, 18, 19]),
            (20, "Design a status-disciplined roadmap from the current fleet to future launch capacity.", [12, 13, 14, 15, 16, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "Department of Space", "ISRO", "IN-SPACe", "NSIL",
            "Indian Space Policy 2023", "launch vehicle", "spacecraft",
            "LEO", "sun-synchronous", "GTO", "GEO", "PSLV", "GSLV",
            "LVM3", "SSLV", "cryogenic", "semi-cryogenic", "human rating",
            "NGLV", "technology transfer",
        ],
        "Audited ledgers route the 2018 PSLV-GSLV objective concept and a provisional 2026 IN-SPACe/private-participation concept here. No unverified objective key or direct Mains demand is invented.",
        pyqs, SPACE_LIVE_ATTEMPTS,
        "ISRO launcher retrieval was title-only on 2026-09-03. The dated repository owners remain the source for fleet and programme status; every capacity, cost, schedule, launch result and anomaly requires fresh official verification.",
        extra=[
            "00_Master-Framework.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "MAP DOS ISRO CENTRES IN-SPACE AND NSIL",
            "SEPARATE LAUNCH VEHICLE SPACECRAFT PAYLOAD AND ORBIT",
            "CLASSIFY PSLV GSLV LVM3 SSLV BY ROLE PROPULSION AND STATUS",
            "TRACE FACTORY PAD RANGE INTEGRATION AND MISSION ASSURANCE",
            "SEPARATE POLICY AUTHORISATION COMMERCIALISATION AND LAW",
            "DATE-STAMP APPROVAL CONSTRUCTION TRANSFER FLIGHT AND OPERATION",
            "CONCLUDE ON SOVEREIGN ACCESS PLUS RELIABLE INDUSTRIAL SCALE",
        ],
        allow_existing_history=True,
    )


def _topic_02() -> dict[str, object]:
    facts = [
        ("Satellite-class boundary", "Earth-observation, communication, meteorological and navigation satellites are classified by payload and service, not merely by orbit or spacecraft name."),
        ("Orbit-service boundary", "A geostationary orbit supports continuous view of a region, while polar and sun-synchronous low orbits support repeated Earth coverage; orbit enables but does not uniquely determine a satellite's service."),
        ("Segment boundary", "A satellite service requires a space segment, ground control and data-processing segment, and user receivers or departments; a spacecraft in orbit is not the same as a delivered service."),
        ("Remote-sensing chain", "Earth-observation sensors collect reflected or emitted energy, ground systems process it, and users convert products into mapping, agriculture, water, disaster and planning decisions."),
        ("Communication chain", "A communication transponder receives, shifts, amplifies and retransmits signals; orbital hardware becomes a service only through terrestrial networks and user terminals."),
        ("Meteorology chain", "Meteorological satellites combine imaging, sounding, data relay and warning support; a weather picture is only one output of the observation system."),
        ("NavIC-system boundary", "NavIC or IRNSS is India's independent regional position, navigation and timing constellation, not India's name for GPS and not a global constellation."),
        ("NavIC-geometry boundary", "The nominal NavIC architecture uses geostationary and inclined geosynchronous satellites to cover India and the surrounding region; nominal design must not be quoted as current functional health."),
        ("NavIC-service boundary", "Standard Positioning Service is the open layer, while Restricted Service is encrypted and available to authorised users; open versus restricted is not safely reduced to civilian versus military."),
        ("Signal-band boundary", "NavIC's original L5 and S-band signals and the later civil L1 addition are signal and receiver-interoperability choices; a launched L1-capable spacecraft does not prove universal handset adoption."),
        ("Launch-health boundary", "Cumulative satellites launched, satellites in intended orbit, satellites operational, satellites broadcasting messages and satellites providing full PNT are different counts that require a dated source."),
        ("PNT-mechanism boundary", "A receiver derives position from signal travel time and known satellite positions, so precise timing and atomic-clock health are foundational to navigation service."),
        ("GAGAN-system boundary", "GAGAN is a Satellite Based Augmentation System that improves GPS accuracy and integrity for aviation; it is not an independent navigation constellation and does not replace NavIC."),
        ("SBAS architecture", "Reference stations measure GNSS errors, master control computes corrections and integrity, uplink stations send messages to geostationary payloads, and compatible aircraft receivers use the rebroadcast."),
        ("Integrity-accuracy boundary", "Accuracy concerns closeness to the true position, while integrity concerns timely warning that a signal should not be used; safety-critical aviation needs both."),
        ("SBAS-GBAS boundary", "SBAS provides wide-area satellite-broadcast augmentation, while GBAS provides local airport-area corrections by ground radio; neither is a sovereign navigation constellation."),
        ("Institution-role boundary", "ISRO and AAI jointly developed GAGAN, AAI owns the aviation operational side, and DGCA certifies aviation performance; developer, operator and regulator are distinct roles."),
        ("Application-outcome boundary", "Navigation, fisheries, transport, timing, weather warning, mapping and disaster support require standards, receivers, data access and departmental adoption; signal or data availability alone is not an outcome."),
        ("Privacy-resilience boundary", "Location services can improve logistics and emergency response while also raising surveillance, spoofing, jamming and critical-infrastructure resilience questions."),
        ("Volatile constellation boundary", "Constellation composition, satellite health, frequencies, coverage, accuracy, certification, service entry and adoption require dated ISRO, AAI, DGCA or Department of Space evidence."),
    ]
    traps = [
        "Do not classify every geostationary satellite as a communication satellite.",
        "Do not infer service delivery from orbital presence alone.",
        "Do not merge NavIC with GPS.",
        "Do not call NavIC global.",
        "Do not convert nominal constellation design into current health.",
        "Do not reduce SPS and RS to civilian and military labels.",
        "Do not infer handset adoption from an L1 payload.",
        "Do not equate launched, operational, messaging and PNT counts.",
        "Do not merge GAGAN with NavIC.",
        "Do not call GAGAN an independent GNSS.",
        "Do not replace integrity with raw accuracy.",
        "Do not merge SBAS and GBAS.",
        "Do not merge ISRO, AAI and DGCA roles.",
        "Do not infer outcomes without ground and user adoption.",
        "Do not ignore jamming, spoofing or privacy risks.",
        "Do not invent current constellation, signal or accuracy data.",
    ]
    titles = [
        "Satellite classes payloads and services",
        "Orbit geometry and service fit",
        "Space ground processing and user segments",
        "Remote-sensing data-to-decision chain",
        "Communication transponders and network delivery",
        "Meteorological observation and warning chain",
        "NavIC regional PNT architecture",
        "Nominal geometry versus functional constellation",
        "SPS RS signals and receiver interoperability",
        "Timing trilateration and atomic-clock dependence",
        "GAGAN as GPS augmentation",
        "Reference station correction and rebroadcast chain",
        "Accuracy integrity and time-to-alert",
        "SBAS GBAS and institutional roles",
        "Applications adoption resilience and dated-status audit",
    ]
    routes = [
        "Classify the payload and service before naming the orbit.",
        "Explain orbit geometry as an enabler rather than a service label.",
        "Trace the full space-ground-user chain.",
        "Move from sensor measurement to a named governance decision.",
        "Explain transponder and terrestrial-network roles separately.",
        "Separate imaging, sounding, relay and warning functions.",
        "Define regional sovereign PNT before comparing other systems.",
        "Separate design geometry from dated functional health.",
        "Link service layer and signal frequency to authorised use and receivers.",
        "Explain navigation as precision timing before positioning.",
        "State that GAGAN augments GPS and does not replace NavIC.",
        "Trace errors, correction, integrity, uplink and compatible receiver.",
        "Make integrity the safety warning layer, not a synonym for accuracy.",
        "Compare coverage scale, broadcast path and regulator/operator roles.",
        "Close with adoption, resilience, privacy and fresh official status.",
    ]
    panels = [
        panel("Satellite service taxonomy", "hierarchy", [
            "EARTH OBSERVATION -> sensed Earth data and derived products",
            "COMMUNICATION -> relay through transponders and ground networks",
            "METEOROLOGY -> imaging, sounding, relay and warning support",
            "NAVIGATION -> position, navigation and timing signals",
            "RULE -> payload and service define the class",
        ], [facts[0][0]]),
        panel("Orbit-service matrix", "comparison-table", [
            "GEO -> continuous regional view and fixed ground geometry",
            "IGSO / GSO -> daily-period geometry with changing sky position",
            "POLAR LEO -> repeated high-inclination Earth coverage",
            "SUN-SYNCHRONOUS LEO -> near-constant local-solar-time imaging",
            "RULE -> orbit enables service but does not name the payload",
        ], [facts[1][0]]),
        panel("End-to-end segment chain", "process-flow", [
            "SPACE SEGMENT -> satellite bus and mission payload",
            "CONTROL SEGMENT -> tracking, command and health management",
            "PROCESSING SEGMENT -> correction, calibration or data products",
            "USER SEGMENT -> receiver, department or operational workflow",
            "OUTCOME -> useful service only after all segments function",
        ], [facts[2][0]]),
        panel("Observation-to-decision rail", "process-flow", [
            "SENSOR -> records reflected or emitted energy",
            "DOWNLINK -> sends measurements to a ground station",
            "PROCESSING -> calibration, correction and product generation",
            "USER AGENCY -> interprets the product",
            "DECISION -> mapping, crop, water, warning or response action",
        ], [facts[3][0], facts[5][0]]),
        panel("Communication relay loop", "process-flow", [
            "UPLINK -> terrestrial station sends a signal",
            "TRANSPONDER -> receives, shifts, amplifies and retransmits",
            "DOWNLINK -> signal reaches a service footprint",
            "GROUND NETWORK -> routes content to final users",
            "RULE -> satellite capacity is not the same as delivered access",
        ], [facts[4][0]]),
        panel("NavIC system map", "systems-map", [
            "REGIONAL CONSTELLATION -> independent Indian PNT source",
            "GEO PLUS IGSO DESIGN -> nominal regional geometry",
            "CONTROL SEGMENT -> orbit and clock monitoring",
            "USER RECEIVER -> measures signal travel time",
            "RULE -> nominal design is not dated functional health",
        ], [facts[6][0], facts[7][0], facts[11][0]]),
        panel("NavIC service and signal stack", "layered-rail", [
            "SPS -> open positioning service",
            "RS -> encrypted service for authorised users",
            "L5 / S -> original signal layers in owner",
            "L1 -> mass-market interoperability direction",
            "RULE -> payload support does not prove device adoption",
        ], [facts[8][0], facts[9][0]]),
        panel("Constellation-health firewall", "comparison-table", [
            "LAUNCHED -> cumulative mission count",
            "INTENDED ORBIT -> orbit-raising completed",
            "OPERATIONAL -> spacecraft performing a stated function",
            "PNT CAPABLE -> full navigation service contribution",
            "MESSAGE BROADCAST -> useful but not equivalent to PNT",
        ], [facts[10][0]]),
        panel("GAGAN correction chain", "process-flow", [
            "REFERENCE STATIONS -> measure GNSS error",
            "MASTER CONTROL -> computes correction and integrity",
            "UPLINK STATIONS -> send augmentation message",
            "GEO PAYLOAD -> rebroadcasts over a wide area",
            "AIRCRAFT RECEIVER -> applies correction and checks integrity",
        ], [facts[12][0], facts[13][0]]),
        panel("Accuracy-integrity gate", "comparison-table", [
            "ACCURACY -> estimated position close to true position",
            "INTEGRITY -> warning when information must not be used",
            "TIME TO ALERT -> warning must arrive within a safe interval",
            "AVIATION USE -> certification governs operational acceptance",
            "RULE -> a precise signal without integrity is unsafe",
        ], [facts[14][0]]),
        panel("SBAS-GBAS institution map", "comparison-table", [
            "SBAS -> wide-area corrections rebroadcast from satellites",
            "GBAS -> local airport corrections broadcast from the ground",
            "ISRO + AAI -> GAGAN development partnership",
            "AAI -> aviation operational role",
            "DGCA -> aviation certification role",
        ], [facts[15][0], facts[16][0]]),
        panel("Public-value answer spine", "answer-spine", [
            "CLASSIFY -> observation communication meteorology PNT or augmentation",
            "TRACE -> space ground processing and user segments",
            "DISTINGUISH -> NavIC constellation from GAGAN SBAS",
            "TEST -> standards adoption integrity privacy jamming and spoofing",
            "VERIFY -> dated health frequency coverage accuracy and certification",
        ], [facts[17][0], facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2018", "GS-I", "Explain why India needs IRNSS and how it helps navigation.", "Verified routed Mains demand.", [6, 7, 8, 11, 17, 18]),
        common.make_pyq_solution(facts, "2025", "Prelims GS-I", "Identify the nature and function of GAGAN.", "Verified routed objective concept; the official Set-A key exists locally but no answer letter is reproduced here.", [12, 13, 14, 15, 16]),
        common.make_pyq_solution(facts, "2018-2023", "Prelims GS-I", "GPS applications, IRNSS geometry, remote-sensing uses, solar-flare effects and independent navigation systems.", "Verified routed concept family; unkeyed rows are not converted into answer letters.", [1, 3, 6, 7, 11, 18]),
    ]
    return common.topic(
        2, "Satellites, NavIC, GAGAN and Applications",
        "02_Satellites-NavIC-GAGAN-and-Applications", facts, traps,
        [
            (10, "Distinguish NavIC from GAGAN in architecture, purpose and strategic value.", [6, 7, 12, 13, 14, 16]),
            (10, "Explain why a satellite launch is not the same as a satellite service.", [0, 1, 2, 3, 4, 5]),
            (15, "Analyse the space-ground-user chain behind Indian satellite applications.", [2, 3, 4, 5, 17]),
            (15, "Assess constellation health and receiver adoption as constraints on NavIC.", [7, 8, 9, 10, 11, 17]),
            (20, "Evaluate satellite systems as public-service and strategic infrastructure.", [0, 2, 3, 4, 5, 6, 12, 17, 18]),
            (20, "Design a resilient PNT and aviation-augmentation strategy for India.", [6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19]),
        ],
        titles, routes, panels,
        [
            "Earth observation", "communication satellite", "meteorological",
            "space segment", "ground segment", "user segment", "NavIC",
            "IRNSS", "regional navigation", "SPS", "Restricted Service",
            "L5", "S-band", "L1", "atomic clock", "GAGAN", "SBAS",
            "GBAS", "integrity", "AAI", "DGCA",
        ],
        "Audited ledgers route the 2018 IRNSS Mains demand, 2025 GAGAN objective concept and related navigation, remote-sensing and space-weather objective concepts here. Objective keys are not inferred.",
        pyqs, SPACE_LIVE_ATTEMPTS,
        "The ISRO navigation page returned title-only on 2026-09-03. Repository owners therefore remain the bounded source; constellation health, signals, coverage, accuracy, certification and adoption must be date-stamped from ISRO, AAI, DGCA or DoS.",
        extra=[
            "00_Master-Framework.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "CLASSIFY THE SATELLITE BY PAYLOAD AND SERVICE",
            "MATCH ORBIT GEOMETRY WITHOUT TURNING IT INTO A SERVICE LABEL",
            "TRACE SPACE CONTROL PROCESSING AND USER SEGMENTS",
            "SEPARATE NAVIC REGIONAL PNT FROM GAGAN GPS AUGMENTATION",
            "SEPARATE ACCURACY INTEGRITY SBAS AND GBAS",
            "TEST RECEIVERS STANDARDS ADOPTION PRIVACY JAMMING AND SPOOFING",
            "DATE-STAMP FUNCTIONAL HEALTH SIGNALS COVERAGE AND CERTIFICATION",
        ],
    )


def _topic_03() -> dict[str, object]:
    facts = [
        ("Human-rating boundary", "Human rating is a system-level qualification of launcher margins, redundancy, health monitoring, failure response and abort capability; an ordinary launch record does not establish crew safety."),
        ("Orbital-module boundary", "Gaganyaan's Orbital Module combines a habitable, re-entry-capable Crew Module with a Service Module that supplies propulsion, power and other support; neither module alone is the complete flight element."),
        ("Crew-escape boundary", "The Crew Escape System is designed to pull the Crew Module away from a failing launcher during relevant ascent phases; an abort demonstration validates escape logic, not a full orbital mission."),
        ("Life-support boundary", "Environmental Control and Life Support maintains atmosphere, pressure, temperature, humidity and carbon-dioxide removal; it is a defining crewed-spacecraft system rather than a satellite payload."),
        ("Qualification-ladder boundary", "Component and ground tests, air-drop recovery tests, test-vehicle abort demonstrations, uncrewed orbital flights and crewed flights are separate qualification rungs that answer different safety questions."),
        ("Air-drop-test boundary", "An Integrated Air Drop Test or main-parachute air-drop test uses a module simulator released from an aircraft or helicopter to qualify deceleration and recovery; no orbital launch vehicle is involved."),
        ("Uncrewed-crewed boundary", "A Gaganyaan uncrewed orbital precursor tests integrated flight systems without accepting crew risk, while a crewed mission is a later and more demanding rung; a target date is not an achieved flight."),
        ("Recovery-chain boundary", "A crewed mission requires guided re-entry, parachute deployment, splashdown location, crew extraction and medical support; launch success alone cannot certify safe return."),
        ("Axiom-Gaganyaan boundary", "Axiom-4 gave an Indian astronaut experience on an international ISS mission using foreign launch and spacecraft systems; it did not demonstrate India's indigenous crewed launch, orbital module or recovery capability."),
        ("Mission-status boundary", "Announced, Cabinet-approved, under development, launched, inserted, operational, completed, partially successful, failed and concluded describe different mission states and must never be substituted."),
        ("Chandrayaan-1 boundary", "Chandrayaan-1 was an orbital lunar-science mission associated with evidence of lunar hydroxyl or water; its science result is distinct from a soft landing."),
        ("Chandrayaan-2 boundary", "Chandrayaan-2 achieved lunar-orbiter operations while its lander did not complete soft landing; the mission must not be labelled either total success or total failure."),
        ("Chandrayaan-3 boundary", "Chandrayaan-3 demonstrated a successful soft landing and surface operations; that achievement does not by itself establish lunar ascent, docking or sample return."),
        ("Chandrayaan-4 boundary", "Chandrayaan-4 is an approved lunar sample-return technology mission in the repository owner; approval and intended completion are not launch, landing or returned material."),
        ("Aditya-L1 boundary", "Aditya-L1 is a solar observatory operating in a halo orbit around Sun-Earth L1; it neither landed on the Sun nor belongs to the lunar or planetary-landing sequence."),
        ("Lagrange-station-keeping boundary", "A halo orbit around L1 provides sustained solar viewing but requires station-keeping and a propellant budget; a Lagrange-point mission is not a motionless spacecraft at a force-free point."),
        ("Mars-Venus boundary", "Mars Orbiter Mission is a concluded historic mission, whereas the Venus Orbiter Mission is an approved future comparative-planetology mission in the owner; legacy capability does not prove the future mission's outcome."),
        ("Capability-ladder boundary", "Human spaceflight, lunar orbit-landing-sample return, solar observation and planetary orbit missions follow different technical ladders; progress on one ladder cannot certify another."),
        ("Planetary-defence boundary", "Asteroid risk management links detection, orbit characterisation, warning time and possible deflection; a kinetic-impact demonstration such as DART is evidence of one technique, not a complete planetary shield."),
        ("Volatile mission boundary", "Crew, schedule, test completion, payload, mission finding, spacecraft health, target date and operational status require a dated official mission source; no later rung may be inferred from an earlier announcement or test."),
    ]
    traps = [
        "Do not infer human rating from launch reliability alone.",
        "Do not merge Crew Module and Service Module functions.",
        "Do not call an abort test an orbital mission.",
        "Do not omit life support from human-spaceflight architecture.",
        "Do not merge component, air-drop, abort and orbital tests.",
        "Do not call an air-drop test a rocket flight.",
        "Do not rewrite a target date as an achieved mission.",
        "Do not stop the human-spaceflight chain at launch.",
        "Do not call Axiom-4 an indigenous Gaganyaan flight.",
        "Do not merge approved, operational, completed and concluded.",
        "Do not equate lunar orbit science with soft landing.",
        "Do not call Chandrayaan-2 a total failure.",
        "Do not infer sample return from Chandrayaan-3.",
        "Do not treat Chandrayaan-4 approval as returned samples.",
        "Do not call Aditya-L1 a solar landing.",
        "Do not describe L1 as a completely stable fixed point.",
        "Do not infer Venus mission success from Mars legacy.",
        "Do not merge distinct mission-capability ladders.",
        "Do not describe one deflection test as full planetary defence.",
        "Do not invent crew, dates, payloads, findings or mission status.",
    ]
    titles = [
        "Human rating and crew-risk standard",
        "Crew Module Service Module and Orbital Module",
        "Crew Escape System and abort phases",
        "Life support habitability and crew survival",
        "Qualification ladder from components to crewed flight",
        "Air-drop recovery tests versus rocket tests",
        "Uncrewed orbital precursor and crewed mission",
        "Re-entry parachute splashdown and recovery",
        "Axiom-4 experience versus indigenous capability",
        "Mission-status vocabulary",
        "Chandrayaan-1 and orbital lunar science",
        "Chandrayaan-2 partial-success classification",
        "Chandrayaan-3 landing versus sample-return capability",
        "Aditya-L1 Mars Venus and parallel mission ladders",
        "Planetary defence and dated mission audit",
    ]
    routes = [
        "Open with probability-of-crew-loss logic rather than prestige.",
        "Map habitability, re-entry, propulsion and power functions.",
        "Explain escape as a phase-specific survivability system.",
        "Identify atmosphere, pressure, thermal and carbon-dioxide control.",
        "Order every test rung and state what it validates.",
        "Separate parachute recovery testing from orbital flight.",
        "Place uncrewed integration before any crewed capability claim.",
        "Trace safe return through re-entry, descent, splashdown and extraction.",
        "Use international exposure as experience, not sovereign capability.",
        "Attach one exact status verb and date to every mission.",
        "Separate science discovery from landing capability.",
        "Write orbiter success and lander failure in the same sentence.",
        "Separate landing, ascent, docking and Earth-return capabilities.",
        "Use distinct ladders for solar, lunar and planetary missions.",
        "Close with detect-characterise-warn-deflect and fresh official evidence.",
    ]
    panels = [
        panel("Human-rating pyramid", "hierarchy", [
            "LAUNCH RELIABILITY -> necessary starting condition",
            "MARGINS AND REDUNDANCY -> tolerate selected failures",
            "HEALTH MONITORING -> detect unsafe vehicle conditions",
            "ABORT MODES -> protect crew during ascent",
            "HUMAN RATING -> system qualification, not a success count",
        ], [facts[0][0]]),
        panel("Gaganyaan module map", "systems-map", [
            "CREW MODULE -> habitable and re-entry capable",
            "SERVICE MODULE -> propulsion, power and support",
            "ORBITAL MODULE -> Crew Module plus Service Module",
            "LAUNCH VEHICLE -> ascent platform, separate from spacecraft",
            "RULE -> module, spacecraft and launcher are different layers",
        ], [facts[1][0]]),
        panel("Crew-survival chain", "process-flow", [
            "ECLSS -> breathable and thermally controlled cabin",
            "CREW ESCAPE -> separation from a failing launcher",
            "RE-ENTRY -> controlled atmospheric return",
            "PARACHUTES -> staged deceleration",
            "RECOVERY -> splashdown, extraction and medical support",
        ], [facts[2][0], facts[3][0], facts[7][0]]),
        panel("Qualification ladder", "timeline", [
            "COMPONENT / GROUND TEST -> verify subsystem behaviour",
            "AIR-DROP TEST -> parachute and recovery sequence",
            "TEST-VEHICLE ABORT -> escape under a selected flight condition",
            "UNCREWED ORBITAL FLIGHT -> integrated mission without crew",
            "CREWED FLIGHT -> later accepted human risk",
        ], [facts[4][0], facts[5][0], facts[6][0]]),
        panel("International-exposure firewall", "comparison-table", [
            "AXIOM-4 -> international ISS mission experience",
            "FOREIGN LAUNCHER / SPACECRAFT -> external transport systems",
            "INDIAN EXPERIMENTS -> operational and scientific exposure",
            "GAGANYAAN -> indigenous launch, module and recovery objective",
            "RULE -> experience complements but does not certify capability",
        ], [facts[8][0]]),
        panel("Mission-status ladder", "hierarchy", [
            "ANNOUNCED / PROPOSED -> intent",
            "APPROVED -> authority and programme sanction",
            "UNDER DEVELOPMENT / TESTED -> work and evidence rung",
            "LAUNCHED / INSERTED / OPERATIONAL -> distinct flight milestones",
            "COMPLETED / PARTIAL / FAILED / CONCLUDED -> outcome vocabulary",
        ], [facts[9][0], facts[19][0]]),
        panel("Lunar capability ladder", "timeline", [
            "CHANDRAYAAN-1 -> orbital science and lunar-water evidence",
            "CHANDRAYAAN-2 -> orbiter success, lander setback",
            "CHANDRAYAAN-3 -> soft landing and surface operations",
            "CHANDRAYAAN-4 -> approved sample-return technology mission",
            "RULE -> landing does not prove ascent, docking or Earth return",
        ], [facts[10][0], facts[11][0], facts[12][0], facts[13][0]]),
        panel("Solar-observatory geometry", "process-flow", [
            "SUN-EARTH SYSTEM -> defines Lagrange-point geometry",
            "L1 REGION -> continuous solar-view advantage",
            "HALO ORBIT -> three-dimensional path around L1",
            "STATION KEEPING -> periodic correction and propellant use",
            "ADITYA-L1 -> solar observatory, not a landing mission",
        ], [facts[14][0], facts[15][0]]),
        panel("Planetary-status matrix", "comparison-table", [
            "MARS ORBITER MISSION -> historic mission, now concluded",
            "VENUS ORBITER MISSION -> approved future mission in owner",
            "LUNAR SAMPLE RETURN -> ascent and return architecture",
            "SOLAR OBSERVATORY -> remote sensing from L1 halo orbit",
            "RULE -> destination and status both control the description",
        ], [facts[16][0], facts[17][0]]),
        panel("Parallel capability ladders", "systems-map", [
            "HUMAN -> abort, life support, uncrewed, crewed, station",
            "LUNAR -> orbit, soft land, rove, sample return",
            "SOLAR -> transit, halo insertion, station keeping, observation",
            "PLANETARY -> cruise, insertion, science operations",
            "RULE -> one ladder cannot certify another",
        ], [facts[17][0]]),
        panel("Planetary-defence rail", "causal-chain", [
            "DETECTION -> discover potentially hazardous objects",
            "CHARACTERISATION -> refine orbit, size and composition",
            "WARNING TIME -> determines response feasibility",
            "DEFLECTION -> kinetic impact is one demonstrated concept",
            "RESIDUAL RISK -> one test is not a complete shield",
        ], [facts[18][0]]),
        panel("Mission answer spine", "answer-spine", [
            "CLASSIFY -> human lunar solar planetary or defence mission",
            "TRACE -> minimum technical and safety chain",
            "NAME -> one verified achievement or approved next rung",
            "SEPARATE -> test launch operation completion and outcome",
            "VERIFY -> dated crew schedule payload finding and status source",
        ], [facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2019", "GS-III", "Discuss India's space-station plan and its benefits for the space programme.", "Verified routed Mains demand.", [0, 3, 4, 6, 7, 8, 17, 19]),
        common.make_pyq_solution(facts, "2022", "GS-III", "Discuss the features, goals and human benefits of the James Webb Space Telescope.", "Verified routed Mains demand; this package carries the mission-class and scientific-observatory method, not invented telescope specifications.", [9, 17, 19]),
        common.make_pyq_solution(facts, "2023", "GS-III", "Explain Chandrayaan-3 mission tasks, subsystems and the Virtual Launch Control Centre.", "Verified routed Mains demand; only owner-supported lunar capability and subsystem distinctions are used.", [9, 12, 13, 17, 19]),
        common.make_pyq_solution(facts, "2024", "GS-III", "Discuss asteroids, extinction threat and prevention strategies.", "Verified routed Mains demand.", [18, 19]),
        common.make_pyq_solution(facts, "2024-2025", "Prelims GS-I", "RTG and microgravity-mission concept family.", "Verified routed objective concepts; official keys are not reproduced or inferred.", [8, 9, 17, 19]),
    ]
    return common.topic(
        3, "Human Spaceflight: Gaganyaan and Planetary Missions",
        "03_Human-Spaceflight-Gaganyaan-and-Planetary-Missions", facts, traps,
        [
            (10, "Explain why human rating is more than an ordinary launcher success record.", [0, 2, 3, 4]),
            (10, "Distinguish Axiom-4 experience from indigenous Gaganyaan capability.", [0, 1, 7, 8, 9]),
            (15, "Analyse the Gaganyaan qualification ladder before crewed flight.", [0, 1, 2, 3, 4, 5, 6, 7]),
            (15, "Explain India's lunar capability progression without overstating sample-return readiness.", [10, 11, 12, 13, 17]),
            (20, "Evaluate India's human-spaceflight and planetary roadmap through parallel capability ladders.", [0, 4, 7, 8, 9, 13, 14, 16, 17, 19]),
            (20, "Design a status-disciplined science and safety framework for crewed, planetary and asteroid missions.", [2, 3, 4, 7, 9, 15, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "human rating", "Crew Module", "Service Module", "Orbital Module",
            "Crew Escape System", "ECLSS", "air-drop test", "uncrewed",
            "crewed", "re-entry", "Axiom-4", "Gaganyaan", "Chandrayaan-1",
            "Chandrayaan-2", "Chandrayaan-3", "Chandrayaan-4", "Aditya-L1",
            "halo orbit", "station keeping", "planetary defence", "DART",
        ],
        "Audited ledgers route the 2019 space-station, 2022 JWST, 2023 Chandrayaan-3 and 2024 asteroid Mains demands plus RTG, LISA and microgravity objective concepts here. No answer key, telescope specification or mission outcome is invented.",
        pyqs, SPACE_LIVE_ATTEMPTS,
        "The ISRO Gaganyaan page returned title-only on 2026-09-03. Repository owners remain the bounded source; crew, schedule, tests, payloads, findings, spacecraft health and mission status require a dated official update.",
        extra=[
            "00_Master-Framework.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "CLASSIFY THE MISSION AND ITS CAPABILITY LADDER",
            "DEFINE HUMAN RATING MODULES ESCAPE LIFE SUPPORT AND RECOVERY",
            "ORDER COMPONENT AIR-DROP ABORT UNCREWED AND CREWED TESTS",
            "SEPARATE INTERNATIONAL EXPOSURE FROM INDIGENOUS CAPABILITY",
            "CLASSIFY LUNAR SOLAR MARS VENUS AND ASTEROID MISSIONS",
            "DATE-STAMP APPROVAL TEST LAUNCH OPERATION AND COMPLETION",
            "CONCLUDE ON SAFETY SCIENCE INDUSTRIAL LEARNING AND MATURITY",
        ],
    )


def _topic_04() -> dict[str, object]:
    facts = [
        ("Fission-power chain", "Nuclear fission splits a heavy nucleus, releases heat and neutrons, transfers heat through coolant, makes steam and drives a turbine-generator; installed reactor capacity is not electrical generation."),
        ("Criticality boundary", "Criticality means a self-sustaining controlled chain reaction with effective neutron multiplication near unity; first criticality is not grid synchronisation, rated power or commercial operation."),
        ("Control-safety boundary", "Control rods absorb neutrons to regulate the reaction, a moderator slows neutrons in thermal reactors, coolant removes heat, and containment limits release; these functions are not interchangeable."),
        ("Thermal-fast boundary", "Thermal reactors use moderated slower neutrons, whereas fast breeder reactors deliberately avoid a moderator and retain a fast-neutron spectrum; coolant choice does not itself make a reactor thermal or fast."),
        ("Fissile-fertile boundary", "U-235, Pu-239 and U-233 are fissile, while U-238 and Th-232 are fertile materials that can breed fissile nuclides; fertile material is not ready-to-use fissile fuel."),
        ("Stage-1 boundary", "Stage 1 centres on Pressurised Heavy Water Reactors using natural uranium and heavy water, producing electricity and plutonium-bearing spent fuel for the closed-cycle strategy."),
        ("Plutonium-stream boundary", "Plutonium used for the breeder bridge is recovered from irradiated Stage-1 fuel through reprocessing; spent fuel, separated fissile material and fresh reactor fuel are distinct material states."),
        ("Stage-2 boundary", "Stage 2 centres on fast breeder reactors using plutonium-bearing fuel and fertile blankets to expand fissile resources; one prototype milestone is not an operational breeder fleet."),
        ("PFBR-status boundary", "The 500 MWe PFBR at Kalpakkam was designed by IGCAR, built and commissioned by BHAVINI, and attained first criticality on 6 April 2026; the fetched DAE source did not establish grid or commercial operation."),
        ("Stage-3 boundary", "Stage 3 is the long-term thorium-U-233 utilisation horizon; it depends on prior fissile inventory, irradiation, reprocessing and fuel fabrication rather than direct burning of mined thorium."),
        ("Thorium-U233 boundary", "Th-232 absorbs a neutron and ultimately yields fissile U-233, while U-232 contamination complicates handling through intense gamma-emitting decay products; thorium abundance does not remove engineering constraints."),
        ("Closed-cycle boundary", "A closed fuel cycle links irradiation, cooling, reprocessing, remote fuel fabrication, reactor reuse and waste management; breeder scaling depends on the whole material loop."),
        ("DAE-BARC boundary", "DAE provides the governmental policy and strategic umbrella, while BARC performs reactor, fuel-cycle and advanced-concept R&D; policy direction and laboratory execution are distinct."),
        ("Operator-regulator boundary", "NPCIL develops and operates commercial civilian nuclear plants, while AERB performs safety review and regulatory oversight; operator and regulator must never be merged."),
        ("IGCAR-BHAVINI boundary", "IGCAR is the fast-reactor and sodium-technology R&D and design centre, while BHAVINI is the public-sector project execution and operating company for PFBR."),
        ("Fuel-chain boundary", "UCIL mines and mills uranium, NFC fabricates fuel and reactor components, and IREL processes monazite associated with thorium and rare earths; resource, fabrication and reactor operation are separate stages."),
        ("Reactor-type boundary", "PHWR, PWR, BWR, FBR, AHWR and small-reactor concepts differ in moderator, coolant, fuel, neutron spectrum and development status; a design concept is not an operating plant."),
        ("Capacity-generation boundary", "Installed megawatt capacity, first criticality, grid synchronisation, commercial operation and electricity generated over time are different measures and milestones."),
        ("Legal-status boundary", "Atomic-energy ownership, civil liability and safety regulation are different legal domains; an enacted replacement framework does not repeal existing law until its commencement provisions take effect."),
        ("Volatile nuclear boundary", "Fleet size, capacity, generation, fuel inventory, reactor status, legal commencement, cost and schedule require dated DAE, NPCIL, AERB or statutory evidence and must not be inferred from a milestone."),
    ]
    traps = [
        "Do not merge installed capacity with electricity generation.",
        "Do not call first criticality commercial operation.",
        "Do not merge control rods, moderator, coolant and containment.",
        "Do not put a moderator in a fast reactor.",
        "Do not call fertile thorium a ready fissile fuel.",
        "Do not omit plutonium production from Stage 1 logic.",
        "Do not merge spent fuel, separated plutonium and fresh fuel.",
        "Do not call one prototype an operational Stage-2 fleet.",
        "Do not turn PFBR criticality into grid supply.",
        "Do not claim Stage 3 is commercially deployed.",
        "Do not ignore U-233 fuel-fabrication constraints.",
        "Do not describe the fuel cycle as reactor physics alone.",
        "Do not merge DAE with BARC.",
        "Do not merge NPCIL with AERB.",
        "Do not merge IGCAR with BHAVINI.",
        "Do not merge mining, fabrication and operation.",
        "Do not treat every reactor design as operating.",
        "Do not merge capacity, criticality, grid and generation.",
        "Do not merge liability law with safety regulation.",
        "Do not invent current fleet, fuel, cost, schedule or law status.",
    ]
    titles = [
        "Fission heat steam and electricity chain",
        "Criticality multiplication and milestone vocabulary",
        "Control rods moderator coolant and containment",
        "Thermal versus fast neutron systems",
        "Fissile and fertile material roles",
        "Stage 1 PHWR and natural-uranium logic",
        "Spent fuel reprocessing and plutonium bridge",
        "Stage 2 breeder and fertile blanket logic",
        "PFBR institutions design and exact status",
        "Stage 3 thorium to U-233 pathway",
        "Thorium handling and remote-fabrication constraint",
        "Closed fuel cycle and breeder scaling",
        "DAE BARC NPCIL AERB institution map",
        "IGCAR BHAVINI UCIL NFC and IREL chain",
        "Reactor types legal status and dated nuclear audit",
    ]
    routes = [
        "Trace energy conversion before discussing policy benefits.",
        "Define criticality and separate each commissioning milestone.",
        "Give one exact function to every control and safety component.",
        "Explain neutron spectrum and the absence of a moderator.",
        "Classify nuclides before describing the three-stage sequence.",
        "Link natural uranium and heavy water to the Stage-1 choice.",
        "Show why reprocessing is necessary for the plutonium bridge.",
        "Explain breeding without claiming fleet deployment.",
        "Name IGCAR, BHAVINI, rating and first-criticality status precisely.",
        "Trace thorium conversion before invoking energy security.",
        "Add the U-232-linked remote-handling qualification.",
        "Treat irradiation, reprocessing and refabrication as one loop.",
        "Separate policy, R&D, operation and safety oversight.",
        "Map design, execution, mining, fabrication and monazite processing.",
        "Close with reactor taxonomy, legal commencement and dated evidence.",
    ]
    panels = [
        panel("Fission-to-grid chain", "process-flow", [
            "FISSION -> heavy nucleus splits and releases heat plus neutrons",
            "COOLANT -> removes core heat",
            "STEAM SYSTEM -> converts heat into working-fluid energy",
            "TURBINE-GENERATOR -> produces electricity",
            "RULE -> reactor capacity is not electricity generated",
        ], [facts[0][0], facts[17][0]]),
        panel("Criticality milestone ladder", "hierarchy", [
            "SUBCRITICAL -> chain reaction declines",
            "FIRST CRITICALITY -> controlled self-sustaining reaction begins",
            "POWER ASCENSION -> tested increase toward rated conditions",
            "GRID SYNCHRONISATION -> generator connects to grid",
            "COMMERCIAL OPERATION -> later declared operating status",
        ], [facts[1][0], facts[17][0]]),
        panel("Core-control function map", "comparison-table", [
            "CONTROL RODS -> absorb neutrons and regulate reactivity",
            "MODERATOR -> slows neutrons in a thermal reactor",
            "COOLANT -> transfers heat out of the core",
            "CONTAINMENT -> barrier against radioactive release",
            "RULE -> four functions, four different answers",
        ], [facts[2][0]]),
        panel("Thermal-fast comparison", "comparison-table", [
            "THERMAL REACTOR -> moderated slower-neutron spectrum",
            "FAST REACTOR -> no moderator and fast-neutron spectrum",
            "PHWR -> heavy-water moderated Stage-1 workhorse",
            "FBR -> breeding objective with fertile blanket",
            "RULE -> coolant alone does not define the spectrum",
        ], [facts[3][0], facts[5][0], facts[7][0]]),
        panel("Fissile-fertile conversion map", "process-flow", [
            "U-235 / PU-239 / U-233 -> fissile materials",
            "U-238 -> neutron capture -> PU-239 pathway",
            "TH-232 -> neutron capture and decay -> U-233 pathway",
            "FERTILE MATERIAL -> needs irradiation and conversion",
            "RULE -> resource abundance is not ready reactor fuel",
        ], [facts[4][0], facts[10][0]]),
        panel("Three-stage programme rail", "timeline", [
            "STAGE 1 -> PHWR, natural uranium and plutonium-bearing spent fuel",
            "REPROCESSING -> separates material for the breeder bridge",
            "STAGE 2 -> fast breeder and fissile-inventory multiplication",
            "THORIUM IRRADIATION -> prepares U-233 route",
            "STAGE 3 -> long-term thorium-U-233 utilisation horizon",
        ], [facts[5][0], facts[6][0], facts[7][0], facts[9][0]]),
        panel("PFBR status card", "status-ladder", [
            "DESIGN -> IGCAR fast-reactor and sodium expertise",
            "BUILD / COMMISSION -> BHAVINI project responsibility",
            "RATING -> 500 MWe design value in fetched DAE text",
            "6 APRIL 2026 -> first criticality achieved",
            "NOT ESTABLISHED -> grid synchronisation or commercial operation",
        ], [facts[8][0], facts[14][0]]),
        panel("Closed fuel-cycle loop", "cyclic-process", [
            "REACTOR IRRADIATION -> changes isotopic composition",
            "COOLING / HANDLING -> manages heat and radiation",
            "REPROCESSING -> separates reusable fissile material",
            "REMOTE FABRICATION -> prepares new fuel",
            "REUSE / WASTE -> closes material accounting loop",
        ], [facts[6][0], facts[10][0], facts[11][0]]),
        panel("Institutional separation", "hierarchy", [
            "DAE -> governmental policy and strategic umbrella",
            "BARC -> reactor and fuel-cycle R&D",
            "NPCIL -> commercial civilian plant developer and operator",
            "AERB -> safety review and regulatory oversight",
            "RULE -> promoter, laboratory, operator and regulator differ",
        ], [facts[12][0], facts[13][0]]),
        panel("Fuel-and-project chain", "process-flow", [
            "UCIL -> uranium mining and milling",
            "NFC -> fuel and reactor-component fabrication",
            "IREL -> monazite, thorium and rare-earth processing link",
            "IGCAR -> fast-reactor design and sodium R&D",
            "BHAVINI -> PFBR project execution and operation",
        ], [facts[14][0], facts[15][0]]),
        panel("Reactor taxonomy", "comparison-table", [
            "PHWR -> heavy water and natural-uranium Stage-1 role",
            "PWR / BWR -> light-water systems with different steam cycles",
            "FBR -> fast spectrum and breeding objective",
            "AHWR / SMALL-REACTOR LINES -> design or development status",
            "RULE -> type and deployment status must be stated together",
        ], [facts[16][0]]),
        panel("Nuclear answer spine", "answer-spine", [
            "DEFINE -> fission, criticality, fissile, fertile and fuel cycle",
            "TRACE -> Stage 1, plutonium bridge, Stage 2 and thorium horizon",
            "MAP -> DAE BARC NPCIL AERB IGCAR BHAVINI and fuel chain",
            "SEPARATE -> capacity criticality grid generation and legal status",
            "VERIFY -> dated fleet fuel reactor law cost and schedule evidence",
        ], [facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2020", "Prelims GS-I", "IAEA safeguards on domestic and imported nuclear reactors.", "Verified routed objective concept; no unavailable answer key is inferred.", [12, 13, 18, 19]),
    ]
    return common.topic(
        4, "Nuclear Power and the Three-Stage Programme",
        "04_Nuclear-Power-and-Three-Stage-Programme", facts, traps,
        [
            (10, "Distinguish first criticality, grid synchronisation, installed capacity and generation.", [0, 1, 8, 17]),
            (10, "Explain the fissile-fertile distinction in India's three-stage programme.", [4, 5, 7, 9, 10]),
            (15, "Explain how Stage 1 creates the material bridge to Stage 2.", [5, 6, 7, 11]),
            (15, "Assess PFBR as a Stage-2 milestone without overstating deployment.", [1, 3, 7, 8, 14, 17]),
            (20, "Evaluate India's three-stage programme as a closed fuel-cycle strategy.", [4, 5, 6, 7, 9, 10, 11, 15]),
            (20, "Analyse nuclear expansion through reactor choice, institutions, regulation and legal-status discipline.", [2, 3, 12, 13, 14, 16, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "nuclear fission", "criticality", "control rods", "moderator",
            "coolant", "containment", "thermal reactor", "fast breeder",
            "fissile", "fertile", "PHWR", "natural uranium", "plutonium",
            "thorium", "U-233", "closed fuel cycle", "PFBR", "IGCAR",
            "BHAVINI", "NPCIL", "AERB",
        ],
        "Audited ledgers route a 2020 IAEA-safeguards objective concept here. The package adds original practice but invents no direct Mains PYQ or objective key.",
        pyqs, NUCLEAR_LIVE_ATTEMPTS,
        "DAE substantive text fetched on 2026-09-03 confirms PFBR first criticality and its bounded technical/institutional claims. It does not establish grid synchronisation, commercial operation, breeder-fleet deployment or Stage-3 completion.",
        extra=[
            "00_Master-Framework.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "TRACE FISSION HEAT STEAM TURBINE AND ELECTRICITY",
            "SEPARATE CRITICALITY POWER ASCENSION GRID AND COMMERCIAL OPERATION",
            "DEFINE CONTROL MODERATION COOLING CONTAINMENT FISSILE AND FERTILE",
            "TRACE STAGE 1 REPROCESSING STAGE 2 AND THORIUM U-233 HORIZON",
            "MAP DAE BARC NPCIL AERB IGCAR BHAVINI UCIL NFC AND IREL",
            "SEPARATE REACTOR TYPE CAPACITY GENERATION LIABILITY AND SAFETY",
            "CONCLUDE WITH DATED DEPLOYMENT AND CLOSED-CYCLE REALISM",
        ],
    )


def _topic_05() -> dict[str, object]:
    facts = [
        ("Fusion-fission boundary", "Nuclear fusion combines light nuclei, while nuclear fission splits heavy nuclei; commercial nuclear electricity today is fission-based and fusion remains experimental."),
        ("DT-reaction boundary", "The deuterium-tritium reaction produces helium-4, a neutron and 17.6 MeV; the neutron carries most energy outward while the alpha particle supports plasma self-heating."),
        ("Temperature-plasma boundary", "Fusion fuel must become an ultra-hot ionised plasma to overcome electrostatic repulsion; a quoted temperature is a plasma condition, not proof of confinement, gain or plant readiness."),
        ("Lawson boundary", "The Lawson triple product links plasma density, temperature and energy-confinement time; improving one variable alone does not satisfy the fusion condition."),
        ("Magnetic-inertial boundary", "Magnetic confinement holds a lower-density plasma with magnetic fields, while inertial confinement rapidly compresses a small fuel target; the two approaches use different time and density regimes."),
        ("Tokamak-stellarator boundary", "A tokamak is a toroidal magnetic-confinement device using a strong plasma current, while a stellarator relies on externally shaped coils for steady confinement; neither term means a commercial power plant."),
        ("Q-plasma boundary", "Fusion gain Q compares fusion power produced in the plasma with external heating power injected into the plasma; Q above one is not plant-wide net electricity."),
        ("Engineering-breakeven boundary", "Engineering or electricity breakeven must include magnets, cryogenics, pumps, heating efficiency and thermal conversion; a machine can have favourable plasma Q while remaining a net electricity consumer."),
        ("Alpha-neutron boundary", "Charged alpha particles can remain magnetically confined and heat the plasma, whereas 14.1 MeV neutrons escape magnetic confinement, heat the blanket and damage or activate structures."),
        ("Tritium-breeding boundary", "Tritium is scarce and radioactive, so a future D-T plant must breed it from lithium-bearing blankets with losses and decay considered; ITER tests concepts rather than proving a closed commercial fuel cycle."),
        ("Materials boundary", "High-energy neutrons cause displacement damage, helium production and activation, while plasma-facing components face intense heat loads; material survival is separate from plasma confinement."),
        ("Divertor boundary", "A divertor extracts heat, impurities and helium ash from the plasma edge; successful core confinement does not solve exhaust and component-lifetime constraints."),
        ("ITER-purpose boundary", "ITER is an experimental tokamak under construction to study burning-plasma conditions and integrated fusion technologies; it has no turbine and is not a commercial electricity plant."),
        ("ITER-Q boundary", "ITER's official design objective is 500 MW of fusion power from 50 MW of injected plasma heating, Q=10; the official page explicitly says this heat will not be converted to electricity."),
        ("Membership-contribution boundary", "ITER has seven members, while India's participation is delivered substantially through specified in-kind procurement packages; membership share, cash cost and component delivery are different claims."),
        ("IPR-ITERIndia boundary", "IPR is a DAE-aided plasma-research institute, while ITER-India is the domestic agency organised as a project within IPR for procurement and delivery; research institute and project agency are not synonyms."),
        ("Domestic-device boundary", "ADITYA-U and SST-1 are Indian experimental tokamaks for plasma and long-pulse research; neither is a power reactor or evidence of commercial fusion generation."),
        ("Schedule-status boundary", "ITER's re-baselined research, magnetic-energy and deuterium-tritium milestones are future project targets; construction progress does not convert them into completed operations."),
        ("DEMO-commercial boundary", "A later DEMO-class system is intended to bridge experimentation toward electricity production, while commercial deployment additionally needs availability, licensing, fuel self-sufficiency and acceptable cost."),
        ("Volatile fusion boundary", "Temperature, gain, pulse duration, schedule, cost, member contribution, component status and milestone claims require dated ITER, IPR or ITER-India evidence and must retain plasma-versus-plant boundaries."),
    ]
    traps = [
        "Do not merge fusion with fission power.",
        "Do not quote temperature as proof of energy gain.",
        "Do not omit confinement time from fusion conditions.",
        "Do not merge magnetic and inertial confinement.",
        "Do not call every magnetic device a tokamak.",
        "Do not call a tokamak a power plant.",
        "Do not equate plasma Q with net electricity.",
        "Do not omit plant recirculating power.",
        "Do not treat alpha particles and neutrons identically.",
        "Do not assume tritium is freely available.",
        "Do not call fusion radiation-free or materials-free.",
        "Do not omit divertor and exhaust constraints.",
        "Do not call ITER a commercial reactor.",
        "Do not rewrite 500 MW fusion heat as electricity.",
        "Do not invent member shares, cost or contribution values.",
        "Do not merge IPR with ITER-India.",
        "Do not call ADITYA-U or SST-1 power reactors.",
        "Do not turn scheduled ITER milestones into completed status.",
        "Do not merge ITER, DEMO and commercial plants.",
        "Do not invent current gain, duration, schedule or cost claims.",
    ]
    titles = [
        "Fusion versus fission and present power status",
        "Deuterium tritium products and energy partition",
        "Plasma temperature and electrostatic barrier",
        "Lawson density temperature and confinement time",
        "Magnetic versus inertial confinement",
        "Tokamak and stellarator geometry",
        "Plasma Q and scientific breakeven",
        "Engineering and electricity breakeven",
        "Alpha heating neutron transport and activation",
        "Lithium blanket and tritium self-sufficiency",
        "Materials damage and plasma-facing components",
        "Divertor exhaust heat and helium ash",
        "ITER purpose Q target and no-turbine boundary",
        "India IPR ITER-India ADITYA-U and SST-1",
        "ITER schedule DEMO commercial ladder and dated audit",
    ]
    routes = [
        "Separate present fission electricity from experimental fusion.",
        "Trace energy between alpha particle and neutron.",
        "Explain why temperature is necessary but insufficient.",
        "Use the triple product to show simultaneous requirements.",
        "Compare density, confinement method and pulse duration.",
        "Separate device geometry from power-plant status.",
        "Define the numerator and denominator of plasma Q.",
        "Add all plant loads before discussing net electricity.",
        "Link alpha self-heating to neutron-driven blanket and damage.",
        "Explain why a breeding blanket is a fuel-system requirement.",
        "Treat material lifetime as an independent feasibility threshold.",
        "Show why exhaust handling limits sustained operation.",
        "State ITER's experimental purpose and no-electricity boundary.",
        "Separate research, domestic agency, devices and in-kind packages.",
        "Close with scheduled targets, DEMO prerequisites and dated evidence.",
    ]
    panels = [
        panel("Nuclear-process firewall", "comparison-table", [
            "FISSION -> splits heavy nuclei and powers current reactors",
            "FUSION -> combines light nuclei in experimental systems",
            "COMMERCIAL STATUS -> fission operating, fusion not deployed",
            "SHARED WORD NUCLEAR -> does not erase process differences",
            "RULE -> Topic 05 cannot substitute for Topic 04",
        ], [facts[0][0]]),
        panel("D-T energy map", "process-flow", [
            "DEUTERIUM + TRITIUM -> fusion reaction",
            "HELIUM-4 / ALPHA -> charged product retained for self-heating",
            "NEUTRON -> carries most energy out of plasma",
            "BLANKET -> captures heat and supports fuel functions",
            "RULE -> particle role controls engineering consequence",
        ], [facts[1][0], facts[8][0]]),
        panel("Fusion-condition triangle", "triangle", [
            "TEMPERATURE -> raises probability of overcoming repulsion",
            "DENSITY -> supplies reacting particles",
            "CONFINEMENT TIME -> retains energy long enough",
            "LAWSON TRIPLE PRODUCT -> all three must combine",
            "TRAP -> a temperature record alone proves little",
        ], [facts[2][0], facts[3][0]]),
        panel("Confinement comparison", "comparison-table", [
            "MAGNETIC -> lower density and longer confinement",
            "TOKAMAK -> torus with strong plasma current",
            "STELLARATOR -> externally shaped steady-field geometry",
            "INERTIAL -> dense target and extremely short confinement",
            "RULE -> approach and device name are not power status",
        ], [facts[4][0], facts[5][0]]),
        panel("Breakeven ladder", "hierarchy", [
            "PLASMA Q -> fusion power divided by injected heating",
            "Q ABOVE ONE -> plasma-level scientific threshold",
            "ENGINEERING Q -> includes recirculating plant loads",
            "NET ELECTRICITY -> includes thermal conversion and all consumption",
            "COMMERCIALITY -> adds availability, cost and licensing",
        ], [facts[6][0], facts[7][0], facts[18][0]]),
        panel("Neutron-to-material chain", "causal-chain", [
            "14.1 MeV NEUTRON -> escapes magnetic confinement",
            "BLANKET -> receives energy and may breed tritium",
            "STRUCTURE -> displacement damage and transmutation",
            "ACTIVATION -> radioactive material-management issue",
            "LIFETIME -> separate engineering feasibility constraint",
        ], [facts[8][0], facts[10][0]]),
        panel("Tritium fuel loop", "cyclic-process", [
            "D-T PLASMA -> consumes tritium",
            "FUSION NEUTRON -> enters lithium-bearing blanket",
            "LITHIUM REACTION -> produces new tritium",
            "EXTRACTION / PROCESSING -> returns usable fuel",
            "RULE -> a test blanket is not a closed commercial cycle",
        ], [facts[9][0]]),
        panel("Plasma exhaust path", "process-flow", [
            "CORE PLASMA -> creates heat and helium ash",
            "EDGE TRANSPORT -> moves particles and heat outward",
            "DIVERTOR -> exhausts impurities and helium",
            "PLASMA-FACING MATERIAL -> receives extreme heat load",
            "RULE -> confinement success does not solve exhaust lifetime",
        ], [facts[10][0], facts[11][0]]),
        panel("ITER mission card", "status-ladder", [
            "UNDER CONSTRUCTION -> experimental international tokamak",
            "BURNING-PLASMA STUDY -> core scientific purpose",
            "Q=10 DESIGN -> 500 MW fusion from 50 MW plasma heating",
            "NO TURBINE -> no conversion to grid electricity",
            "TEST TECHNOLOGIES -> bridge to later machines",
        ], [facts[12][0], facts[13][0]]),
        panel("India-in-ITER map", "hierarchy", [
            "INDIA -> one of seven ITER members",
            "IN-KIND PACKAGES -> specified hardware and systems",
            "IPR -> DAE-aided plasma-research institute",
            "ITER-INDIA -> domestic procurement and delivery agency in IPR",
            "RULE -> membership, institute, agency and package differ",
        ], [facts[14][0], facts[15][0]]),
        panel("Domestic research devices", "comparison-table", [
            "ADITYA-U -> experimental tokamak and plasma campaigns",
            "SST-1 -> superconducting long-pulse research platform",
            "RESEARCH OUTPUT -> diagnostics, control and operating knowledge",
            "NOT OUTPUT -> commercial fusion electricity",
            "RULE -> experimental operation is not power generation",
        ], [facts[16][0]]),
        panel("Fusion-readiness answer spine", "answer-spine", [
            "DEFINE -> D-T fusion plasma confinement Lawson and Q",
            "TRACE -> alpha heating neutron blanket tritium and materials",
            "SEPARATE -> plasma gain engineering gain and net electricity",
            "MAP -> ITER India IPR ITER-India ADITYA-U SST-1 and DEMO",
            "VERIFY -> dated schedule cost contribution and milestone evidence",
        ], [facts[17][0], facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2025", "GS-III", "Mention India's contributions to ITER and explain the implications of project success for global energy.", "Verified direct routed Mains demand.", [0, 6, 7, 9, 10, 12, 13, 14, 15, 16, 18, 19]),
    ]
    return common.topic(
        5, "Nuclear Fusion and ITER",
        "05_Nuclear-Fusion-and-ITER", facts, traps,
        [
            (10, "Explain why ITER must not be described as a commercial power plant.", [6, 7, 12, 13, 18]),
            (10, "Distinguish plasma Q from engineering and electricity breakeven.", [6, 7, 13]),
            (15, "Explain the D-T fusion chain and its tritium and materials constraints.", [1, 2, 3, 8, 9, 10, 11]),
            (15, "Assess India's domestic fusion ecosystem and ITER participation.", [14, 15, 16, 19]),
            (20, "Evaluate fusion through scientific, engineering and commercial feasibility thresholds.", [2, 3, 4, 5, 6, 7, 9, 10, 11, 18]),
            (20, "Analyse the implications of ITER success without overstating timelines or electricity output.", [6, 7, 9, 10, 12, 13, 14, 15, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "nuclear fusion", "nuclear fission", "deuterium", "tritium",
            "helium-4", "17.6 MeV", "plasma", "Lawson", "magnetic confinement",
            "inertial confinement", "tokamak", "stellarator", "fusion gain",
            "engineering breakeven", "alpha particle", "14.1 MeV neutron",
            "tritium breeding", "lithium blanket", "divertor", "ITER",
            "Q=10", "IPR", "ITER-India", "ADITYA-U", "SST-1", "DEMO",
        ],
        "Audited ledgers route the direct 2025 GS-III ITER contribution and future-energy demand here. No other direct PYQ or answer key is manufactured.",
        pyqs, FUSION_LIVE_ATTEMPTS,
        "Substantive ITER text fetched on 2026-09-03 confirms the experimental Q=10 objective, no-electricity boundary, technology-integration purpose and tritium-breeding test role. Schedule, cost and package-status claims remain date-bounded.",
        extra=[
            "00_Master-Framework.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "SEPARATE FUSION FROM FISSION AND RESEARCH FROM POWER DEPLOYMENT",
            "DEFINE D-T REACTION PLASMA LAWSON CONFINEMENT AND DEVICE TYPE",
            "SEPARATE PLASMA Q ENGINEERING BREAKEVEN AND NET ELECTRICITY",
            "TRACE ALPHA HEATING NEUTRON BLANKET TRITIUM MATERIALS AND DIVERTOR",
            "MAP ITER INDIA IPR ITER-INDIA ADITYA-U SST-1 AND DEMO",
            "DATE-STAMP RESEARCH CONSTRUCTION SCHEDULE CONTRIBUTION AND MILESTONE",
            "CONCLUDE ON LONG-HORIZON ENERGY PLUS PRESENT INDUSTRIAL LEARNING",
        ],
    )


TOPIC_01 = _topic_01()
TOPIC_02 = _topic_02()
TOPIC_03 = _topic_03()
TOPIC_04 = _topic_04()
TOPIC_05 = _topic_05()
