"""Authored learner-v2 data for Science and Technology Topics 06-10."""

from __future__ import annotations

import generate_science_and_technology_common as common
from science_and_technology_data_helpers import (
    AI_LIVE_ATTEMPTS,
    DEFENCE_PRODUCTION_LIVE_ATTEMPTS,
    DEFENCE_RD_LIVE_ATTEMPTS,
    DIGITAL_LIVE_ATTEMPTS,
    QUANTUM_LIVE_ATTEMPTS,
    panel,
)


def _topic_06() -> dict[str, object]:
    facts = [
        ("DRDO-developer boundary", "DRDO is the Ministry of Defence research-and-development organisation: it designs, develops, integrates and tests systems and facilitates production and induction; the armed services are users and production agencies manufacture at scale."),
        ("Requirement-user boundary", "The Army, Navy and Air Force articulate operational requirements, participate in user evaluation and decide service acceptance; a DRDO developmental result cannot be rewritten as service induction."),
        ("MSS-cluster boundary", "The Missiles and Strategic Systems cluster is responsible for missile and strategic-system design and development through DRDL, RCI, ASL, TBRL and ITR plus supporting test, integration and analysis centres."),
        ("Subsystem-chain boundary", "A missile system combines airframe, propulsion, navigation, guidance, homing or seeker, warhead, launch system and command-and-control; success of one subsystem is not proof of an integrated operational weapon."),
        ("Ballistic-cruise boundary", "A ballistic missile receives powered boost and then follows a largely ballistic trajectory, whereas a cruise missile sustains guided atmospheric flight using an air-breathing engine; range alone does not define either class."),
        ("Hypersonic-class boundary", "Hypersonic describes speed rather than one missile class: a boost-glide vehicle is rocket-boosted and manoeuvres while gliding, while a hypersonic cruise system uses sustained air-breathing propulsion such as a scramjet."),
        ("SAM-AAM boundary", "A surface-to-air missile is launched from the surface against aerial threats, while an air-to-air missile is launched from an aircraft; Akash and Astra therefore belong to different operational and launch-platform categories."),
        ("ATGM boundary", "An anti-tank guided missile is designed for armoured targets and uses a guidance and seeker logic distinct from strategic ballistic, cruise and air-defence systems; the Nag family belongs to this role."),
        ("Rocket-artillery boundary", "Pinaka is a multi-barrel rocket and guided-rocket artillery family for land fires; sharing rocket propulsion does not turn it into a strategic ballistic missile, cruise missile or space launch vehicle."),
        ("Missile-platform boundary", "A missile is the guided weapon, while an aircraft, ship, submarine, vehicle or launcher is the delivery platform; one missile may have multiple launch configurations without becoming the platform itself."),
        ("IGMDP-history boundary", "The Integrated Guided Missile Development Programme ran from 1983 to March 2012 and covered Prithvi, Trishul, Akash, Nag and the Agni technology demonstrator; later families are not automatically IGMDP products."),
        ("BrahMos-JV boundary", "BrahMos is a supersonic cruise-missile system developed and produced through BrahMos Aerospace, the DRDO-NPOM joint venture; it is neither a purely solo domestic programme nor a ballistic missile."),
        ("Test-status ladder", "Developmental trial, user evaluation, ready-for-induction language, contract, induction and deployment are separate rungs; a successful test proves only the proposition and configuration officially tested."),
        ("AoN-contract boundary", "Defence Acquisition Council Acceptance of Necessity is in-principle approval of a requirement and category, not a signed contract, delivery, induction or operational deployment."),
        ("Production-agency boundary", "DRDO-developed systems require production partners such as DPSUs, joint ventures or private firms; developer identity does not establish who manufactures, maintains or upgrades the fielded system."),
        ("Integrated-air-defence boundary", "Air and missile defence is a sensor, command-and-control and interceptor architecture; an announced integrated mission or one interceptor does not prove a nationwide deployed shield."),
        ("Stealth-detection boundary", "Stealth seeks lower observability through shaping, materials and operating tactics, but it does not mean invisibility; detection depends on sensors, frequency, geometry, processing and the operational environment."),
        ("Explosives-category boundary", "CL-20, HMX and LLM-105 are high-energy substances discussed as military explosives; a chemical-category fact supplies no handling, composition, warhead or deployment detail."),
        ("THAAD-FOBS boundary", "THAAD is a United States terminal high-altitude anti-ballistic-missile defence system, while a Fractional Orbital Bombardment System is a partial-orbit strike concept; neither is an Indian missile programme."),
        ("Volatile-capability boundary", "Missile range, speed, stages, guidance, warhead, payload, deployment, inventory and exact test outcome require a dated official source; qualitative role labels cannot be expanded into unaudited numbers."),
    ]
    traps = [
        "Do not make DRDO the user, mass producer or induction authority.",
        "Do not infer induction or deployment from a developmental test.",
        "Do not classify missiles by range alone.",
        "Do not treat hypersonic as one propulsion or trajectory class.",
        "Do not merge SAM, AAM, ATGM and rocket artillery.",
        "Do not merge the missile with its launch platform.",
        "Do not place every later missile inside IGMDP.",
        "Do not describe BrahMos as a solo Indian ballistic missile.",
        "Do not turn AoN into a contract or order.",
        "Do not convert an integrated-air-defence announcement into deployment.",
        "Do not describe stealth as invisibility.",
        "Do not invent sensitive performance, warhead or deployment data.",
    ]
    titles = [
        "DRDO armed services and production-agency map",
        "MSS laboratories and subsystem integration",
        "Ballistic and cruise flight logic",
        "Boost-glide and scramjet hypersonic distinction",
        "Surface-to-air and air-to-air systems",
        "Anti-tank guided missiles and seeker logic",
        "Pinaka and guided rocket artillery",
        "Missile delivery platform and launcher distinction",
        "IGMDP history and later programme boundary",
        "BrahMos joint-venture and cruise-system logic",
        "Developmental trial to deployment status ladder",
        "AoN contract production and induction chain",
        "Integrated air and missile defence architecture",
        "Stealth detection explosives and external-system PYQs",
        "Official-source capability and secrecy firewall",
    ]
    routes = [
        "Map developer, user and producer before naming a system.",
        "Trace subsystems from propulsion to command-and-control.",
        "Compare trajectory and sustained propulsion, not memorised range.",
        "Separate speed, propulsion and flight profile.",
        "Classify by launch point, target and operational role.",
        "Explain the target-seeker-guidance chain for anti-armour use.",
        "Keep artillery fires outside strategic-missile binaries.",
        "Separate the guided weapon from the carrier and launcher.",
        "Use a dated programme lineage and exclude later families.",
        "State the joint venture and the cruise-missile category.",
        "Quote only the exact officially verified status rung.",
        "Carry the chain from approval to production and service use.",
        "Show sensors, decision network and interceptors as one system.",
        "Answer routed PYQs without importing unsupported specifications.",
        "Close with a dated-source and classified-information qualification.",
    ]
    panels = [
        panel("Developer user producer map", "institution-map", [
            "SERVICES -> articulate requirement and conduct user evaluation",
            "DRDO -> design, develop, integrate and test",
            "PRODUCTION AGENCY -> manufacture and quality assurance",
            "SERVICES -> accept, induct, train and operate",
            "RULE -> one institution cannot be substituted for another",
        ], [facts[0][0], facts[1][0], facts[14][0]]),
        panel("MSS subsystem chain", "systems-map", [
            "DRDL / RCI / ASL / TBRL / ITR -> specialised roles",
            "AIRFRAME + PROPULSION -> controlled flight",
            "NAVIGATION + GUIDANCE + HOMING -> target solution",
            "WARHEAD + LAUNCH + COMMAND SYSTEM -> weapon integration",
            "RULE -> subsystem success is not integrated-system status",
        ], [facts[2][0], facts[3][0]]),
        panel("Ballistic versus cruise", "comparison-table", [
            "BALLISTIC -> powered boost then largely ballistic path",
            "CRUISE -> sustained powered and guided atmospheric flight",
            "BALLISTIC DRIVER -> rocket boost and trajectory",
            "CRUISE DRIVER -> air-breathing propulsion and aerodynamic control",
            "TRAP -> range alone never determines the class",
        ], [facts[4][0]]),
        panel("Hypersonic taxonomy", "branch-map", [
            "HYPERSONIC -> speed description, not one weapon class",
            "BOOST-GLIDE -> rocket boost then manoeuvring glide",
            "HYPERSONIC CRUISE -> sustained scramjet-type propulsion",
            "BALLISTIC RE-ENTRY -> may also be hypersonic",
            "RULE -> identify flight profile before status or capability",
        ], [facts[5][0]]),
        panel("Operational-role matrix", "comparison-table", [
            "SAM / AKASH -> surface launch against aerial threats",
            "AAM / ASTRA -> aircraft launch against aerial threats",
            "ATGM / NAG -> guided anti-armour role",
            "PINAKA -> rocket-artillery land fires",
            "RULE -> launch point, target and role travel together",
        ], [facts[6][0], facts[7][0], facts[8][0]]),
        panel("Weapon and platform split", "layered-rail", [
            "MISSILE -> guided weapon",
            "LAUNCHER -> ground or shipboard launch equipment",
            "AIRCRAFT / SHIP / SUBMARINE -> delivery platform",
            "MULTI-PLATFORM CONFIGURATION -> does not merge categories",
            "SPACE LAUNCH VEHICLE -> separate non-weapon function",
        ], [facts[9][0]]),
        panel("IGMDP lineage", "timeline", [
            "1983 -> IGMDP begins",
            "PRITHVI / TRISHUL / AKASH / NAG -> programme families",
            "AGNI -> technology-demonstrator lineage",
            "MARCH 2012 -> programme closure",
            "RULE -> later systems require their own programme provenance",
        ], [facts[10][0]]),
        panel("BrahMos institutional card", "institution-map", [
            "DRDO -> Indian joint-venture partner",
            "NPOM -> Russian joint-venture partner",
            "BRAHMOS AEROSPACE -> developer and producer entity",
            "SYSTEM CLASS -> supersonic cruise missile",
            "TRAP -> neither solo domestic nor ballistic",
        ], [facts[11][0]]),
        panel("Status ladder", "status-ladder", [
            "DEVELOPMENTAL TRIAL -> tested proposition",
            "USER EVALUATION -> service-oriented validation",
            "READY FOR INDUCTION -> recommendation, not induction",
            "CONTRACT / DELIVERY / INDUCTION -> separate evidence",
            "DEPLOYMENT -> requires its own official confirmation",
        ], [facts[12][0], facts[13][0]]),
        panel("Air-defence system rail", "systems-map", [
            "SENSORS -> detect and track",
            "COMMAND-AND-CONTROL -> fuse, classify and assign",
            "INTERCEPTORS -> engage selected threat classes",
            "LOGISTICS / READINESS -> sustain coverage",
            "TRAP -> announcement or one interceptor is not a shield",
        ], [facts[15][0]]),
        panel("Routed PYQ firewall", "comparison-table", [
            "STEALTH -> reduced observability, not invisibility",
            "EXPLOSIVES -> category fact, not warhead detail",
            "THAAD -> United States missile-defence system",
            "FOBS -> fractional-orbit strike concept",
            "RULE -> answer only the routed technical distinction",
        ], [facts[16][0], facts[17][0], facts[18][0]]),
        panel("Capability-claim firewall", "answer-spine", [
            "DEFINE -> weapon class and operational role",
            "MAP -> developer, user, producer and platform",
            "TRACE -> subsystem and test-to-service chain",
            "LABEL -> announced, tested, contracted, inducted or deployed",
            "VERIFY -> range, speed, stages, guidance and warhead officially",
        ], [facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2021", "GS-III", "Explain the technical superiority of the S-400 air-defence system over other systems.", "Verified routed Mains demand; the answer uses sensor-command-interceptor architecture and does not invent classified Indian deployment detail.", [6, 12, 15, 19]),
        common.make_pyq_solution(facts, "2023", "Prelims GS-I", "Distinguish Agni ballistic missiles from BrahMos cruise missiles.", "Verified routed objective concept; the local official answer key was unavailable, so no answer letter is asserted.", [4, 11, 19]),
        common.make_pyq_solution(facts, "2026", "Prelims GS-I", "Assess stealth, radar cross-section and detection statements.", "Provisional routed concept; no option letter is recorded or inferred.", [16, 19]),
    ]
    return common.topic(
        6, "Defence R&D: DRDO and Missile Systems",
        "06_Defence-RandD-DRDO-and-Missile-Systems", facts, traps,
        [
            (10, "Distinguish DRDO's role from the roles of the armed services and production agencies.", [0, 1, 2, 14]),
            (10, "Differentiate ballistic, cruise and guided rocket-artillery systems.", [4, 5, 8, 9]),
            (15, "Explain how subsystem integration and user evaluation convert research into a missile system.", [2, 3, 12, 14]),
            (15, "Analyse India's missile ecosystem through role-based families rather than range lists.", [4, 6, 7, 8, 10, 11]),
            (20, "Evaluate the development-to-deployment chain for indigenous missile and air-defence capability.", [0, 1, 3, 12, 13, 14, 15, 19]),
            (20, "Discuss strategic autonomy in defence R&D while preserving secrecy, status and institutional boundaries.", [2, 3, 11, 12, 15, 16, 19]),
        ],
        titles, routes, panels,
        [
            "DRDO", "armed services", "MSS cluster", "ballistic missile",
            "cruise missile", "hypersonic", "surface-to-air", "air-to-air",
            "anti-tank guided missile", "Pinaka", "IGMDP", "BrahMos Aerospace",
            "developmental trial", "user evaluation", "Acceptance of Necessity",
            "integrated air and missile defence", "stealth", "THAAD", "FOBS",
        ],
        "Audited ledgers route the 2021 S-400 Mains demand, the 2023 ballistic-versus-cruise objective concept and later provisional defence-technology concepts here. No objective key, sensitive specification or deployment fact is invented.",
        pyqs, DEFENCE_RD_LIVE_ATTEMPTS,
        "The DRDO MSS page was substantively retrieved on 2026-09-03 and supports only the cluster, laboratory and technology-area map. Every missile range, speed, stage, guidance, warhead, test outcome, induction or deployment claim remains date- and source-bounded.",
        extra=["00_Master-Framework.md", "ANSWER-WORTHINESS-AUDIT.md"],
        register_answer_spine=[
            "DEFINE MISSILE CLASS ROLE AND DELIVERY PLATFORM",
            "MAP SERVICES DRDO MSS LABS AND PRODUCTION AGENCY",
            "TRACE AIRFRAME PROPULSION GUIDANCE SEEKER LAUNCH AND COMMAND",
            "SEPARATE BALLISTIC CRUISE SAM AAM ATGM AND ROCKET ARTILLERY",
            "LABEL DEVELOPMENTAL USER-EVALUATED CONTRACTED INDUCTED DEPLOYED",
            "USE VERIFIED PYQ DISTINCTIONS WITHOUT CLASSIFIED SPECULATION",
            "CONCLUDE ON R&D PLUS PRODUCTION LIFECYCLE AND DOCTRINAL FIT",
        ],
    )


def _topic_07() -> dict[str, object]:
    facts = [
        ("R&D-procurement boundary", "Defence R&D creates and validates technology, while procurement selects a category, vendor and contract route and production converts the design into repeatable serviceable equipment; these are linked but distinct policy chains."),
        ("Design-manufacture-content boundary", "Indigenous design means control of system architecture and intellectual property, domestic manufacture means production in India, and indigenous content is a contract-value share; none automatically proves the other two."),
        ("DAP-procedure boundary", "Defence Acquisition Procedure 2020 structures capital-acquisition categories and process; it is a procurement rulebook, not a weapon programme, contract, budget appropriation or proof of delivery."),
        ("Buy-ladder boundary", "The DAP preference ladder includes Buy Indian-IDDM, Buy Indian, Buy and Make Indian, Buy Global-Manufacture in India and Buy Global; each category creates a different design, vendor and local-production pathway."),
        ("Indian-IDDM boundary", "Buy Indian-IDDM gives priority to an Indian vendor offering an indigenously designed, developed and manufactured product with prescribed indigenous content; the label must not be reduced to assembly in India."),
        ("Buy-Make boundary", "Buy and Make Indian uses an Indian vendor with production after transfer of technology from a foreign original-equipment manufacturer, while Buy Global-Manufacture in India begins with a global vendor and specified manufacture in India."),
        ("AoN-order boundary", "Acceptance of Necessity is Defence Acquisition Council in-principle approval of the requirement and categorisation; request for proposal, trials, negotiation, contract, delivery and induction remain later stages."),
        ("PIL-family boundary", "Services Positive Indigenisation Lists concern platforms and equipment restricted for import after notified dates, while DPSU lists concern components, subsystems and materials for domestic sourcing and are tracked through SRIJAN."),
        ("Notification-achievement boundary", "A positive-list notification creates a demand signal and item-specific deadline; it is not proof that every listed item has been indigenised, ordered, delivered or produced with complete domestic content."),
        ("SRIJAN-stage boundary", "SRIJAN is a public implementation portal for DPSU indigenisation items and stages such as expression of interest, request for proposal, trials and indigenised status; a portal stage is not a contract or service induction."),
        ("DPSU-private boundary", "DPSUs can provide sovereign integration and legacy production depth while private firms, startups and MSMEs add competition and specialised innovation; indigenisation is not an either-or choice between them."),
        ("OFB-corporatisation boundary", "The Ordnance Factory Board was corporatised in 2021 into seven DPSUs; organisational restructuring changes accountability architecture but does not by itself prove higher productivity, quality or order execution."),
        ("iDEX-TDF boundary", "iDEX and ADITI operate through the Defence Innovation Organisation for startups and deep-tech challenges, while the DRDO Technology Development Fund supports industry-led technology development; neither is a procurement category."),
        ("Corridor-category boundary", "The Uttar Pradesh and Tamil Nadu defence industrial corridors are place-based cluster and investment instruments, not DAP acquisition categories, positive lists or contracts."),
        ("FDI-route boundary", "Defence FDI policy distinguishes the automatic route up to 74 percent from government approval beyond 74 percent up to 100 percent under stated conditions; foreign investment does not automatically equal technology absorption."),
        ("Offsets-boundary", "Offsets are reciprocal industrial obligations on foreign vendors, but DAP 2020 narrowed their use for specified government-to-government, inter-governmental and single-vendor routes; offset discharge is not proof of critical technology transfer."),
        ("Lifecycle-indigenisation boundary", "Real self-reliance includes maintenance, repair, overhaul, spares, upgrades, testing standards and configuration control after delivery; domestic assembly without lifecycle capability leaves strategic dependence."),
        ("Export-scale boundary", "Defence exports can widen production runs, learning and diplomatic reach, but export value does not by itself prove indigenous design, imported-subsystem independence or lifecycle support quality."),
        ("Platform-status boundary", "An indigenous programme, domestic production line, signed contract, delivered unit and operational service fleet are different claims; fighter, tank and submarine examples must preserve design origin and status."),
        ("Volatile-number boundary", "Procurement values, delivery schedules, indigenous-content percentages, positive-list counts, production totals and export totals require dated official sources and cannot be carried forward from headlines."),
    ]
    traps = [
        "Do not merge defence R&D with acquisition or production.",
        "Do not equate indigenous content with indigenous design.",
        "Do not turn DAP into a contract or weapon programme.",
        "Do not omit the two technology-transfer manufacture categories.",
        "Do not turn AoN into an order, delivery or induction.",
        "Do not merge Services and DPSU positive lists.",
        "Do not turn a notified item into achieved indigenisation.",
        "Do not make SRIJAN a procurement authority.",
        "Do not frame DPSU and private industry as automatic substitutes.",
        "Do not treat corridors or innovation funds as DAP categories.",
        "Do not convert FDI or offsets into proven technology absorption.",
        "Do not invent current values, counts, timelines or content shares.",
    ]
    titles = [
        "R&D acquisition production and sustainment chain",
        "Indigenous design manufacture and content",
        "DAP 2020 purpose and acquisition schemes",
        "Five-rung Buy preference ladder",
        "Indian-IDDM and Indian-vendor logic",
        "Technology-transfer manufacture pathways",
        "AoN RFP trials contract delivery and induction",
        "Services and DPSU positive-list families",
        "SRIJAN stage tracking and evidence limits",
        "DPSU private prime MSME and startup ecosystem",
        "OFB corporatisation and seven DPSUs",
        "iDEX ADITI and Technology Development Fund",
        "Defence corridors and place-based clustering",
        "FDI offsets exports and technology absorption",
        "Lifecycle self-reliance and volatile-number audit",
    ]
    routes = [
        "Open with the develop-procure-produce-sustain distinction.",
        "Test design control, production location and value share separately.",
        "Define the rulebook before citing a category.",
        "Present all five Buy pathways in preference order.",
        "Explain why IDDM adds design ownership to Indian supply.",
        "Compare Indian-vendor and global-vendor manufacture routes.",
        "Trace every formal stage without status inflation.",
        "Separate platform embargoes from component localisation.",
        "Use portal stages only as implementation evidence.",
        "Build a mixed public-private supplier architecture.",
        "Judge restructuring by outcomes rather than announcement.",
        "Separate innovation support from acquisition procedure.",
        "Explain cluster economics without calling it procurement.",
        "Assess whether capital and obligations create absorption.",
        "Conclude with lifecycle control and dated metrics.",
    ]
    panels = [
        panel("Capability conversion chain", "process-flow", [
            "SERVICE REQUIREMENT -> operational need",
            "R&D / PROTOTYPE -> design and validation",
            "DAP ROUTE / AoN -> category and in-principle approval",
            "CONTRACT / PRODUCTION -> repeatable industrial output",
            "DELIVERY / INDUCTION / SUSTAINMENT -> usable capability",
        ], [facts[0][0], facts[6][0], facts[16][0]]),
        panel("Three meanings of indigenous", "comparison-table", [
            "DESIGN -> Indian control of architecture and intellectual property",
            "MANUFACTURE -> production occurs in India",
            "INDIGENOUS CONTENT -> Indian share of contract value",
            "LIFECYCLE CONTROL -> spares, repairs, upgrades and standards",
            "RULE -> test each dimension independently",
        ], [facts[1][0], facts[16][0]]),
        panel("DAP purpose map", "layered-rail", [
            "DAP 2020 -> capital-acquisition rulebook",
            "CATEGORY -> vendor and localisation pathway",
            "PROCEDURE -> RFP, evaluation and negotiation",
            "CONTRACT -> legally binding procurement event",
            "TRAP -> procedure is not purchase or delivery",
        ], [facts[2][0]]),
        panel("Five-rung Buy ladder", "status-ladder", [
            "1 BUY INDIAN-IDDM -> Indian design, development and manufacture",
            "2 BUY INDIAN -> Indian vendor with prescribed content",
            "3 BUY AND MAKE INDIAN -> Indian vendor plus foreign transfer",
            "4 BUY GLOBAL-MANUFACTURE IN INDIA -> global vendor plus local build",
            "5 BUY GLOBAL -> global procurement route",
        ], [facts[3][0], facts[4][0], facts[5][0]]),
        panel("Approval-to-service ladder", "status-ladder", [
            "SERVICES REQUIREMENT -> stated need",
            "DAC AoN -> in-principle approval and category",
            "RFP / TRIALS -> competition and technical evaluation",
            "CONTRACT / DELIVERY -> order and physical supply",
            "INDUCTION -> service acceptance, not inferred deployment scale",
        ], [facts[6][0]]),
        panel("Positive-list split", "comparison-table", [
            "SERVICES PIL -> platforms and equipment import restriction",
            "DPSU PIL -> components, subsystems and materials",
            "NOTIFIED DATE -> item-specific sourcing boundary",
            "SRIJAN -> DPSU implementation stage tracker",
            "TRAP -> list length is not achieved domestic depth",
        ], [facts[7][0], facts[8][0], facts[9][0]]),
        panel("Industrial actor map", "institution-map", [
            "DPSU -> sovereign integrator and legacy production base",
            "PRIVATE PRIME -> integration, competition and investment",
            "MSME / STARTUP -> specialised subsystem and rapid innovation",
            "USER / QA -> trials, standards and acceptance",
            "RULE -> ecosystem depth matters more than ownership slogan",
        ], [facts[10][0]]),
        panel("OFB restructuring card", "timeline", [
            "BEFORE 2021 -> departmental Ordnance Factory Board structure",
            "2021 -> corporatisation implemented",
            "SEVEN DPSUs -> corporate production entities",
            "TEST -> order books, quality, productivity and delivery",
            "TRAP -> restructuring itself is not performance proof",
        ], [facts[11][0]]),
        panel("Innovation instrument matrix", "comparison-table", [
            "iDEX -> challenge-based startup and MSME innovation",
            "ADITI -> deep-technology support within innovation ecosystem",
            "TDF -> DRDO-supported industry technology development",
            "DAP -> acquisition rulebook",
            "RULE -> funding route is not procurement category",
        ], [facts[12][0]]),
        panel("Corridor and FDI map", "systems-map", [
            "UP + TAMIL NADU CORRIDORS -> place-based supplier clustering",
            "FDI UP TO 74 PERCENT -> automatic route",
            "BEYOND 74 TO 100 PERCENT -> government route conditions",
            "OFFSETS -> reciprocal obligations with narrowed coverage",
            "TEST -> actual absorption, certification and supplier depth",
        ], [facts[13][0], facts[14][0], facts[15][0]]),
        panel("Lifecycle and export loop", "causal-chain", [
            "PREDICTABLE ORDERS -> investment and production learning",
            "MRO / SPARES -> availability after delivery",
            "UPGRADES / CONFIGURATION CONTROL -> design autonomy",
            "EXPORTS -> scale, learning and support obligations",
            "QUALIFICATION -> totals do not prove indigenous design",
        ], [facts[16][0], facts[17][0]]),
        panel("Procurement-claim firewall", "answer-spine", [
            "DEFINE -> design, manufacture, content and lifecycle",
            "CLASSIFY -> DAP route and positive-list family",
            "TRACE -> AoN, RFP, trial, contract, delivery and induction",
            "SEPARATE -> programme, production line and operational fleet",
            "VERIFY -> values, counts, timelines and content shares by date",
        ], [facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2024", "Prelims GS-I", "Assess claims that Rafale, MiG-29 and Tejas Mk1 are fifth-generation fighters.", "Verified routed objective concept; no answer letter is asserted in this package.", [18, 19]),
        common.make_pyq_solution(facts, "2025", "Prelims GS-I", "Match Dornier-228, IL-76 and C-17 with aircraft roles.", "Verified routed objective concept; the solution preserves role labels and does not invent payload figures.", [18, 19]),
        common.make_pyq_solution(facts, "2026", "Prelims GS-I", "Assess Indian manufacture of fighter aircraft, tanks and submarines.", "Provisional routed concept; no answer letter or platform-status claim is inferred.", [1, 16, 18, 19]),
    ]
    return common.topic(
        7, "Defence Indigenisation: Atmanirbhar and Procurement",
        "07_Defence-Indigenization-Atmanirbhar-and-Procurement", facts, traps,
        [
            (10, "Distinguish indigenous design, domestic manufacture and indigenous content.", [0, 1, 16]),
            (10, "Explain why Acceptance of Necessity is not a defence order.", [2, 6]),
            (15, "Compare the five DAP Buy pathways and their localisation logic.", [3, 4, 5]),
            (15, "Explain how positive lists and SRIJAN shape demand without proving achievement.", [7, 8, 9]),
            (20, "Evaluate India's defence-indigenisation ecosystem through procurement, firms, innovation and corridors.", [0, 3, 7, 10, 12, 13, 16]),
            (20, "Assess Atmanirbhar defence through design control, technology absorption, lifecycle support and exports.", [1, 5, 14, 15, 16, 17, 18, 19]),
        ],
        titles, routes, panels,
        [
            "Defence Acquisition Procedure 2020", "Buy (Indian-IDDM)",
            "Buy & Make (Indian)", "Buy (Global - Manufacture in India)",
            "Acceptance of Necessity", "Positive Indigenisation List",
            "SRIJAN", "DPSU", "OFB", "iDEX", "ADITI",
            "Technology Development Fund", "defence industrial corridors",
            "FDI", "offsets", "indigenous content", "lifecycle support",
        ],
        "Audited ledgers route recent fighter-generation, aircraft-role and Indian-manufacture objective concepts here. They are used to teach design, manufacture and status discrimination; no answer letter, production figure or operational claim is invented.",
        pyqs, DEFENCE_PRODUCTION_LIVE_ATTEMPTS,
        "The official DDP DAP node was attempted on 2026-09-03 but yielded a stylesheet-heavy body. Repository owners remain primary for category wording. Every procurement value, delivery schedule, indigenous-content percentage, positive-list count, production total and export total requires a fresh dated official source.",
        extra=["00_Master-Framework.md", "ANSWER-WORTHINESS-AUDIT.md"],
        register_answer_spine=[
            "SEPARATE R&D PROCUREMENT PRODUCTION INDUCTION AND SUSTAINMENT",
            "DEFINE INDIGENOUS DESIGN MANUFACTURE CONTENT AND LIFECYCLE",
            "PRESENT THE COMPLETE FIVE-RUNG DAP BUY LADDER",
            "TRACE REQUIREMENT AoN RFP TRIAL CONTRACT DELIVERY INDUCTION",
            "SEPARATE SERVICES PIL DPSU PIL SRIJAN AND ACHIEVEMENT",
            "MAP DPSUs PRIVATE FIRMS MSMEs STARTUPS CORRIDORS FDI AND OFFSETS",
            "CONCLUDE ON DESIGN CONTROL RELIABLE SCALE AND EXPORT SUPPORT",
        ],
    )


def _topic_08() -> dict[str, object]:
    facts = [
        ("Programme-DPI boundary", "Digital India is a government programme for digital infrastructure, governance and services, while digital public infrastructure describes reusable interoperable rails; neither term is a private app or one database."),
        ("India-Stack boundary", "India Stack is a layered architectural idea spanning identity, payments, consented data, documents and signatures through distinct institutions and laws; it is not one company, statute, ministry platform or government super-app."),
        ("DPI-app boundary", "Public digital infrastructure supplies shared protocols and trust rules on which public and private applications operate; a front-end app is a participant or interface, not the payment, identity or data rail itself."),
        ("Aadhaar-identity boundary", "Aadhaar is a 12-digit residency-linked identity and authentication ecosystem under the Aadhaar Act and UIDAI; it is not proof of citizenship, domicile, date of birth, entitlement or payment."),
        ("UIDAI-role boundary", "UIDAI is the statutory authority for Aadhaar enrolment, lifecycle management and authentication under MeitY; it does not regulate UPI, operate bank settlement or decide citizenship."),
        ("Aadhaar-workflow boundary", "Authentication returns a yes-or-no match against the identity system, e-KYC returns permitted demographic data with consent, and offline verification uses QR or XML without a live CIDR request; these are distinct workflows."),
        ("Identity-entitlement boundary", "A successful Aadhaar authentication establishes a match to identity data, not legal eligibility for a benefit, citizenship, ownership, income, age or any other substantive entitlement."),
        ("UPI-rail boundary", "UPI is an interoperable real-time retail-payment rail operated by NPCI under RBI's regulatory framework; it is not a currency, bank account, wallet, merchant app, credit decision or Aadhaar service."),
        ("UPI-instrument boundary", "UPI can carry payment instructions linked to bank accounts and permitted payment instruments such as full-KYC prepaid instruments, credit cards or pre-sanctioned credit lines under applicable rules; the rail and funding source remain distinct."),
        ("NPCI-RBI boundary", "NPCI operates retail-payment rails as a bank-owned not-for-profit company, while RBI regulates payment systems under the Payment and Settlement Systems Act; operator, regulator and participating bank are different actors."),
        ("Payment-rail boundary", "UPI, IMPS, NEFT, RTGS, AePS, BBPS and NACH have different addressing, settlement, use-case and institutional logics; digital payment is a family, not a synonym for UPI."),
        ("AePS-UPI boundary", "AePS is an Aadhaar-authenticated banking-correspondent rail for services such as cash withdrawal or balance enquiry, whereas UPI is an interoperable payment-instruction rail; biometric authentication does not make AePS a UPI feature."),
        ("AA-data-blind boundary", "An Account Aggregator is an RBI-regulated NBFC framework for consented transfer of financial information between regulated entities and must not retain or own the customer information it moves."),
        ("Consent-purpose boundary", "Formal consent in a data-sharing flow does not by itself guarantee comprehension, fairness or lawful downstream use; purpose limitation, revocation, audit and grievance mechanisms remain necessary."),
        ("DigiLocker-boundary", "DigiLocker is a trusted digital-document access, sharing and verification layer in the MeitY ecosystem; it is not an Aadhaar database, payment rail or mere photograph-storage folder."),
        ("eSign-boundary", "eSign is an API-based online electronic-signature service under the digital-signature trust framework; uploading a scanned handwritten signature is not the same legal and technical process."),
        ("ONDC-OCEN boundary", "ONDC is an open-network protocol for commerce and OCEN is an open-credit protocol connecting lending actors; both extend network unbundling but are not Aadhaar, UPI, AA or private marketplace apps."),
        ("FASTag-boundary", "FASTag uses RFID tag-reader interaction within the National Electronic Toll Collection architecture; barrierless ANPR combinations and GNSS distance-based tolling are separate pilot or proposed directions unless officially deployed."),
        ("Scale-safeguard boundary", "High authentication or payment volume demonstrates use, not universal inclusion, zero fraud, correct entitlement, informed consent, financial sustainability or adequate grievance redress."),
        ("Volatile-data boundary", "UPI volume and value, Aadhaar coverage and authentication totals, DigiLocker counts and deployment statistics require a month-specific official NPCI, UIDAI or MeitY source and must not be recalled from media headlines."),
    ]
    traps = [
        "Do not merge Digital India, India Stack, DPI and a private app.",
        "Do not make Aadhaar proof of citizenship or entitlement.",
        "Do not merge authentication, e-KYC and offline verification.",
        "Do not make UPI a currency, wallet, account or app.",
        "Do not make NPCI the regulator or RBI the rail operator.",
        "Do not call AePS a UPI feature.",
        "Do not make an Account Aggregator a data owner or repository.",
        "Do not reduce DigiLocker to Aadhaar storage.",
        "Do not treat a scanned signature as eSign.",
        "Do not call FASTag a GNSS distance-toll system.",
        "Do not infer inclusion or safety from scale alone.",
        "Do not invent current transaction, coverage or usage totals.",
    ]
    titles = [
        "Digital India India Stack DPI and app boundary",
        "Layered public infrastructure and private interfaces",
        "Aadhaar residence identity and UIDAI",
        "Authentication e-KYC and offline verification",
        "Identity entitlement citizenship and section-seven logic",
        "UPI payment rail and funding instruments",
        "NPCI operator RBI regulator and bank roles",
        "UPI IMPS NEFT RTGS AePS BBPS and NACH",
        "Account Aggregator consented data-sharing architecture",
        "Consent purpose limitation audit and grievance",
        "DigiLocker trusted-document layer",
        "eSign and electronic trust infrastructure",
        "ONDC OCEN and network unbundling",
        "FASTag RFID ANPR and GNSS status",
        "Scale inclusion fraud and volatile-data audit",
    ]
    routes = [
        "Define programme, stack, infrastructure and application separately.",
        "Trace reusable rails without inventing a super-database.",
        "Locate Aadhaar in residency identity and statute.",
        "Compare the three verification workflows precisely.",
        "Separate identity match from legal eligibility.",
        "Trace payment instruction, instrument, bank and settlement.",
        "Name operator, regulator and participant distinctly.",
        "Compare payment rails by mechanism and use case.",
        "Show consented transfer without data ownership.",
        "Add comprehension, purpose and remedy to formal consent.",
        "Treat documents as a separate trust layer.",
        "Explain cryptographic signing rather than image upload.",
        "Describe open protocols without platform conflation.",
        "Answer the toll PYQ with technology and status discipline.",
        "Date-stamp scale claims and pair them with safeguards.",
    ]
    panels = [
        panel("Digital ecosystem boundary", "layered-rail", [
            "DIGITAL INDIA -> programme for infrastructure, governance and services",
            "INDIA STACK -> layered architectural idea",
            "DPI -> reusable interoperable rails with public rules",
            "PRIVATE APP -> interface or participant on a rail",
            "RULE -> these labels cannot be substituted",
        ], [facts[0][0], facts[1][0], facts[2][0]]),
        panel("Modular stack map", "systems-map", [
            "IDENTITY -> Aadhaar / UIDAI",
            "PAYMENTS -> UPI / NPCI under RBI regulation",
            "FINANCIAL DATA -> Account Aggregator consent flow",
            "DOCUMENTS / SIGNATURES -> DigiLocker and eSign",
            "OUTPUT -> interoperable services without one super-database",
        ], [facts[1][0], facts[2][0]]),
        panel("Aadhaar legal identity card", "institution-map", [
            "AADHAAR -> 12-digit resident identity number",
            "UIDAI -> statutory authority under MeitY",
            "AADHAAR ACT -> legal foundation",
            "NOT PROOF -> citizenship, domicile, entitlement or payment",
            "RULE -> identity match answers only the identity question",
        ], [facts[3][0], facts[4][0], facts[6][0]]),
        panel("Three Aadhaar workflows", "comparison-table", [
            "AUTHENTICATION -> yes or no match against CIDR",
            "e-KYC -> permitted demographic return with consent",
            "OFFLINE VERIFICATION -> QR or XML without CIDR request",
            "ENTITLEMENT DECISION -> separate legal and administrative step",
            "TRAP -> one workflow cannot be relabelled as another",
        ], [facts[5][0], facts[6][0]]),
        panel("UPI transaction chain", "process-flow", [
            "USER APP -> initiates payment instruction",
            "UPI / NPCI -> interoperable messaging and switching rail",
            "BANK OR PERMITTED INSTRUMENT -> funding source",
            "RBI FRAMEWORK -> payment-system regulation",
            "RULE -> rail, app, account and regulator are distinct",
        ], [facts[7][0], facts[8][0], facts[9][0]]),
        panel("Payment-rail matrix", "comparison-table", [
            "UPI -> instant retail payment instruction",
            "IMPS / NEFT / RTGS -> distinct interbank settlement modes",
            "AePS -> Aadhaar-authenticated correspondent banking",
            "BBPS / NACH -> bills and recurring bulk mandates",
            "TRAP -> digital payment does not mean UPI alone",
        ], [facts[10][0], facts[11][0]]),
        panel("Operator regulator participant", "institution-map", [
            "NPCI -> operates specified retail rails",
            "RBI -> regulates payment systems",
            "BANK / PPI ISSUER -> holds or issues funding instrument",
            "APP PROVIDER -> customer interface",
            "UIDAI -> separate Aadhaar authority",
        ], [facts[4][0], facts[9][0]]),
        panel("Account Aggregator flow", "process-flow", [
            "CUSTOMER -> gives explicit consent",
            "FIP -> holds regulated financial information",
            "AA -> retrieves and transfers as a data blind",
            "FIU -> receives for consented purpose",
            "RULE -> AA does not own or retain the information",
        ], [facts[12][0], facts[13][0]]),
        panel("Trust layers", "comparison-table", [
            "DIGILOCKER -> access, share and verify trusted documents",
            "eSIGN -> online electronic signature under trust framework",
            "AADHAAR -> identity and authentication",
            "UPI -> payment instruction rail",
            "RULE -> document, signature, identity and payment stay separate",
        ], [facts[14][0], facts[15][0]]),
        panel("Open-network extensions", "branch-map", [
            "ONDC -> open commerce protocol",
            "OCEN -> open credit protocol",
            "NETWORK LOGIC -> unbundle front ends from shared rules",
            "APPLICATIONS -> compete on top of protocol",
            "TRAP -> protocol is not a private marketplace or lender",
        ], [facts[16][0]]),
        panel("Electronic toll status rail", "status-ladder", [
            "FASTag -> RFID tag-reader architecture",
            "NETC -> clearing and dispute framework",
            "ANPR-FASTag -> barrierless pilot combination",
            "GNSS DISTANCE TOLLING -> proposed or pilot direction",
            "RULE -> do not call a proposal nationwide deployment",
        ], [facts[17][0]]),
        panel("DPI claim firewall", "answer-spine", [
            "DEFINE -> programme, rail, app, operator and regulator",
            "TRACE -> identity, payment, consent, document or toll flow",
            "SEPARATE -> identity from citizenship and entitlement",
            "PAIR SCALE -> inclusion, fraud, privacy and grievance safeguards",
            "VERIFY -> monthly official transaction and coverage data",
        ], [facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2018", "Prelims GS-I", "Assess Aadhaar Open APIs and biometric-authentication statements.", "Verified routed objective concept; the official key was unavailable locally, so no answer letter is asserted.", [3, 4, 5, 6]),
        common.make_pyq_solution(facts, "2024", "GS-III", "Explain electronic toll-collection technology, benefits, limitations, proposed seamless change and risks.", "Verified routed Mains demand; FASTag is kept separate from ANPR and GNSS status.", [17, 18, 19]),
    ]
    return common.topic(
        8, "Digital India and India Stack: UPI, Aadhaar",
        "08_Digital-India-and-India-Stack-UPI-Aadhaar", facts, traps,
        [
            (10, "Distinguish Digital India, India Stack, digital public infrastructure and private applications.", [0, 1, 2]),
            (10, "Explain why Aadhaar identity does not establish citizenship or entitlement.", [3, 4, 5, 6]),
            (15, "Trace a UPI transaction while distinguishing the rail, instrument, operator and regulator.", [7, 8, 9, 10]),
            (15, "Compare Aadhaar, UPI, Account Aggregator, DigiLocker and eSign as modular layers.", [3, 7, 12, 14, 15]),
            (20, "Evaluate India's digital public infrastructure through interoperability, institutional accountability and inclusion.", [0, 1, 2, 9, 12, 13, 18]),
            (20, "Assess the governance challenges of identity, payments, consented data and trusted documents at scale.", [5, 6, 8, 12, 13, 14, 18, 19]),
        ],
        titles, routes, panels,
        [
            "Digital India", "India Stack", "digital public infrastructure",
            "Aadhaar", "UIDAI", "authentication", "e-KYC",
            "offline verification", "UPI", "NPCI", "RBI", "AePS",
            "Account Aggregator", "DigiLocker", "eSign", "ONDC", "OCEN",
            "FASTag", "RFID", "GNSS",
        ],
        "Audited ledgers route Aadhaar API/authentication concepts and the 2024 electronic-toll Mains demand here. Other computing concepts remain cross-owned with Topic 25. No objective answer letter, transaction total or nationwide toll-deployment claim is invented.",
        pyqs, DIGITAL_LIVE_ATTEMPTS,
        "UIDAI's older About URL returned 404 and the NPCI statistics page was located only through official-domain search on 2026-09-03. No UPI transaction figure, Aadhaar coverage or authentication total was imported. Every scale claim remains month-specific and official-source bounded.",
        extra=[
            "00_Master-Framework.md",
            "ANSWER-WORTHINESS-AUDIT.md",
            "REVISION-CHART_Principles-Applications-and-Distinctive-Features.md",
        ],
        register_answer_spine=[
            "DEFINE DIGITAL INDIA INDIA STACK DPI RAIL AND PRIVATE APP",
            "MAP UIDAI NPCI RBI AA DIGILOCKER eSIGN ONDC AND OCEN",
            "TRACE AUTHENTICATION e-KYC OFFLINE PAYMENT AND CONSENT FLOWS",
            "SEPARATE IDENTITY CITIZENSHIP ENTITLEMENT ACCOUNT WALLET AND RAIL",
            "NAME OPERATOR REGULATOR PARTICIPATING BANK AND FRONT-END APP",
            "PAIR SCALE WITH INCLUSION FRAUD PRIVACY CONSENT AND GRIEVANCE",
            "DATE-STAMP UPI AADHAAR AND DIGILOCKER STATISTICS",
        ],
    )


def _topic_09() -> dict[str, object]:
    facts = [
        ("AI-taxonomy boundary", "Artificial intelligence is the umbrella, machine learning learns patterns from data, deep learning uses multilayer neural networks and generative AI produces content; capability claims must identify the actual method and task."),
        ("Capability-deployment boundary", "A model that demonstrates a capability or performs well on a benchmark is not automatically a validated, integrated or accountable deployment in health, welfare, policing, credit or another high-impact setting."),
        ("Prediction-causation boundary", "AI systems often generate probabilistic predictions or outputs from learned patterns; confidence and correlation do not establish verified truth, causation, fairness or legal justification."),
        ("Foundation-model boundary", "A foundation model is pretrained for broad downstream adaptation, so data, licence, bias and safety failures can propagate to many applications; a model is not identical with every product built on it."),
        ("Hallucination-boundary", "Generative AI can produce fluent false content because it predicts plausible continuations rather than retrieving verified truth; grounding, citations, human review and outcome monitoring remain necessary."),
        ("IndiaAI-mission boundary", "IndiaAI is an ecosystem mission spanning compute, innovation, applications, AIKosh, startup finance, FutureSkills and Safe and Trusted AI; it is not a single model, company, subsidy or legal code."),
        ("Implementation-institution boundary", "MeitY anchors policy and the IndiaAI Mission is implemented through IndiaAI within Digital India Corporation; NITI Aayog's earlier strategy role is distinct from mission implementation and rule-making."),
        ("Pillar-status boundary", "A mission pillar identifies an implementation domain, not a completed output; approval, expression of interest, empanelment, procurement, model proposal, deployment and measured outcome require separate evidence."),
        ("Compute-measure boundary", "A GPU objective, empanelled capacity, affordable compute unit, booked service and physically deployed accelerator are different measures; no number can be converted into another without an official definition."),
        ("AIKosh-data boundary", "AIKosh is the mission's dataset and model-resource platform layer; platform availability does not prove dataset representativeness, lawful provenance, suitability, quality or complete access."),
        ("Use-case-model boundary", "An AI use case describes a problem and workflow, while a model is one component and deployment includes data pipelines, interfaces, human decisions, security, monitoring and grievance redress."),
        ("Decision-support boundary", "AI can assist a public official or clinician without lawfully replacing accountable judgement; automated adverse decisions affecting rights require reasons, human oversight, contestability and appeal."),
        ("Risk-lifecycle boundary", "AI risk enters through problem selection, data, training, evaluation, procurement, integration, use and post-deployment change; a generic ethics statement at the final stage cannot control the full lifecycle."),
        ("Bias-fairness boundary", "Bias may arise from representation, labels, proxies, optimisation or deployment context, and equal aggregate accuracy can conceal unequal group harm; fairness requires context-specific testing and remedy."),
        ("Privacy-security boundary", "Privacy governs lawful data use and purpose, while security protects systems and data from compromise; both matter, but neither alone resolves bias, opacity, safety, misinformation or accountability."),
        ("Deepfake-instrument boundary", "Synthetic-media harms may be addressed through intermediary rules, labelling, provenance and enforcement, but a rule on distribution is not the same as a comprehensive AI statute or model-safety regime."),
        ("Guideline-law boundary", "An advisory, consultation report or governance guideline is non-binding unless supported by enforceable law, while notified rules under a parent Act create subordinate legislation; India has no standalone AI Act in the owner record."),
        ("Procurement-accountability boundary", "Public procurement must specify data rights, evaluation, audit logs, human oversight, incident reporting, vendor change control and exit obligations; buying an AI service does not transfer constitutional accountability."),
        ("Sectoral-governance boundary", "AI risk differs across health, finance, education, policing, welfare and low-risk productivity tools, so proportionate governance should combine horizontal principles with sectoral law and regulators."),
        ("Volatile-mission boundary", "Mission outlay, compute count, model selection, model status, safety-institute status and summit outcomes require dated official IndiaAI or MeitY sources; announcements cannot be rewritten as deployed capability."),
    ]
    traps = [
        "Do not merge AI, machine learning, deep learning and generative AI.",
        "Do not convert a benchmark or prototype into deployment.",
        "Do not treat probabilistic output as verified truth or causation.",
        "Do not make IndiaAI a single model or AI law.",
        "Do not merge NITI strategy authorship with MeitY implementation.",
        "Do not turn a mission pillar into a completed output.",
        "Do not equate compute units, GPUs, empanelment and deployment.",
        "Do not make a model the whole operational use case.",
        "Do not remove human accountability from public decisions.",
        "Do not reduce AI governance to privacy alone.",
        "Do not call a consultation report binding law.",
        "Do not invent outlay, compute, model or summit claims.",
    ]
    titles = [
        "AI machine learning deep learning and generative AI",
        "Capability benchmark prototype and deployment",
        "Prediction probability truth and causation",
        "Foundation models downstream applications and hallucination",
        "IndiaAI mission and institutional architecture",
        "Seven mission pillars and status discipline",
        "Compute capacity measures and procurement rungs",
        "AIKosh data quality provenance and access",
        "Use case model workflow and human decision",
        "Public automated decisions reasons and contestability",
        "AI lifecycle risk and impact assessment",
        "Bias fairness privacy and security",
        "Deepfakes provenance labelling and intermediary rules",
        "Advisory guideline rule Act and sectoral governance",
        "Public procurement accountability and volatile claims",
    ]
    routes = [
        "Begin with the correct AI taxonomy and task.",
        "State the validated rung before discussing impact.",
        "Separate statistical prediction from factual and causal proof.",
        "Trace upstream model risk into downstream applications.",
        "Map MeitY, IndiaAI, Digital India Corporation and NITI Aayog.",
        "Present pillars as workstreams rather than achievements.",
        "Keep every compute measure and procurement status distinct.",
        "Assess provenance, quality and representativeness before access.",
        "Draw the whole socio-technical deployment workflow.",
        "Retain reasons, human review, appeal and remedy.",
        "Govern from problem selection through post-deployment monitoring.",
        "Separate distinct harms and their controls.",
        "Name the exact legal instrument and regulated conduct.",
        "Combine horizontal principles with sector-specific duties.",
        "Conclude with public accountability and dated mission evidence.",
    ]
    panels = [
        panel("AI taxonomy ladder", "hierarchy", [
            "ARTIFICIAL INTELLIGENCE -> broad task-performing systems",
            "MACHINE LEARNING -> patterns learned from data",
            "DEEP LEARNING -> multilayer neural networks",
            "GENERATIVE AI -> creates text, image, audio or code",
            "RULE -> identify method, task and evidence before impact",
        ], [facts[0][0]]),
        panel("Capability-to-deployment ladder", "status-ladder", [
            "RESEARCH CLAIM -> proposed method",
            "BENCHMARK RESULT -> bounded evaluation",
            "PROTOTYPE -> integrated demonstration",
            "DEPLOYMENT -> real workflow with users and monitoring",
            "OUTCOME -> measured benefit and harm after use",
        ], [facts[1][0], facts[2][0]]),
        panel("Foundation-model risk tree", "branch-map", [
            "PRETRAINED FOUNDATION MODEL -> broad downstream reuse",
            "DATA / LICENCE -> provenance constraints",
            "BIAS / SAFETY -> inherited application risk",
            "HALLUCINATION -> fluent output without verification",
            "CONTROL -> grounding, evaluation and human review",
        ], [facts[3][0], facts[4][0]]),
        panel("IndiaAI institution map", "institution-map", [
            "MeitY -> ministry policy and rule-making anchor",
            "INDIAAI / DIGITAL INDIA CORPORATION -> mission implementation",
            "NITI AAYOG -> earlier strategy and think-tank role",
            "SECTOR REGULATOR / DEPARTMENT -> deployment obligations",
            "RULE -> strategy, mission, regulator and law stay separate",
        ], [facts[5][0], facts[6][0]]),
        panel("Mission pillar wheel", "systems-map", [
            "COMPUTE + INNOVATION CENTRE + APPLICATIONS",
            "AIKOSH + STARTUP FINANCING + FUTURESKILLS",
            "SAFE AND TRUSTED AI -> governance tools and evaluation",
            "PILLAR -> implementation domain",
            "TRAP -> pillar name is not completed output",
        ], [facts[5][0], facts[7][0]]),
        panel("Compute measurement firewall", "comparison-table", [
            "GPU OBJECTIVE -> planned hardware measure",
            "EMPANELLED CAPACITY -> procurement availability",
            "COMPUTE UNIT -> provider-defined service measure",
            "BOOKED / USED CAPACITY -> actual access or consumption",
            "RULE -> never convert one measure into another",
        ], [facts[8][0]]),
        panel("AIKosh evidence gate", "process-flow", [
            "DATASET LISTING -> discoverability",
            "PROVENANCE / LICENCE -> lawful origin and permitted use",
            "QUALITY / REPRESENTATION -> fitness for Indian context",
            "ACCESS / SECURITY -> controlled use",
            "OUTCOME -> platform presence alone proves none of these",
        ], [facts[9][0]]),
        panel("Use-case deployment chain", "process-flow", [
            "PUBLIC PROBLEM -> define legitimate objective",
            "DATA + MODEL -> build or procure component",
            "INTERFACE + HUMAN WORKFLOW -> operational decision",
            "MONITORING + APPEAL -> accountability after output",
            "RULE -> model capability is not service outcome",
        ], [facts[10][0], facts[11][0]]),
        panel("Risk lifecycle", "causal-chain", [
            "PROBLEM SELECTION -> exclusion or mission creep",
            "DATA / TRAINING -> bias, privacy and provenance",
            "EVALUATION / PROCUREMENT -> hidden failure or lock-in",
            "DEPLOYMENT / UPDATE -> automation bias and drift",
            "CONTROL -> impact assessment, logs, incidents and review",
        ], [facts[12][0], facts[17][0]]),
        panel("Risk and control matrix", "comparison-table", [
            "BIAS -> representative tests and remedy",
            "PRIVACY -> lawful purpose and minimisation",
            "SECURITY -> access control and resilience",
            "SAFETY / OPACITY -> evaluation, explanation and escalation",
            "MISINFORMATION -> provenance, labelling and enforcement",
        ], [facts[13][0], facts[14][0], facts[15][0]]),
        panel("Instrument hierarchy", "status-ladder", [
            "ADVISORY -> persuasive communication",
            "CONSULTATION REPORT / GUIDELINE -> non-binding framework",
            "NOTIFIED RULE -> binding under parent Act",
            "ACT -> primary legislation",
            "SECTORAL LAW -> context-specific enforceable duty",
        ], [facts[16][0], facts[18][0]]),
        panel("AI governance answer spine", "answer-spine", [
            "DEFINE -> method, model, use case and deployment",
            "MAP -> mission pillar, ministry, implementer and regulator",
            "TRACE -> data, model, procurement, decision and monitoring",
            "RETAIN -> human reasons, contestability and remedy",
            "VERIFY -> outlay, compute, model and summit status officially",
        ], [facts[17][0], facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2020", "Prelims GS-I", "Assess current AI capabilities across industry and society.", "Verified routed objective concept; the official key was unavailable locally, so no answer letter is asserted.", [0, 1, 2, 10]),
        common.make_pyq_solution(facts, "2023", "GS-III", "Discuss AI in clinical diagnosis and threats to individual privacy.", "Verified routed Mains demand; the solution separates decision support, privacy, safety and clinician accountability.", [1, 10, 11, 14, 18]),
        common.make_pyq_solution(facts, "2025", "GS-I", "Discuss AI and drones with GIS and remote sensing in locational and areal planning.", "Verified routed Mains demand; the solution treats AI as decision support and retains validation, ground-truth and public-accountability limits.", [1, 2, 10, 11, 12]),
    ]
    return common.topic(
        9, "Artificial Intelligence Governance and IndiaAI",
        "09_Artificial-Intelligence-Governance-and-IndiaAI", facts, traps,
        [
            (10, "Distinguish AI, machine learning, deep learning and generative AI.", [0, 2, 3, 4]),
            (10, "Explain why model capability is not the same as accountable deployment.", [1, 10, 11]),
            (15, "Describe IndiaAI as a mission ecosystem while preserving pillar and implementation status.", [5, 6, 7, 8, 9]),
            (15, "Analyse lifecycle risks in public-sector AI and the controls needed at each stage.", [10, 11, 12, 13, 14]),
            (20, "Evaluate India's AI-governance approach through legal instruments, sectoral duties and mission capability.", [5, 6, 15, 16, 18, 19]),
            (20, "Design an accountable public procurement framework for high-impact AI systems.", [1, 9, 10, 11, 12, 13, 17, 18]),
        ],
        titles, routes, panels,
        [
            "artificial intelligence", "machine learning", "deep learning",
            "generative AI", "foundation model", "hallucination",
            "IndiaAI Mission", "Digital India Corporation", "NITI Aayog",
            "AIKosh", "Safe & Trusted AI", "compute capacity",
            "human oversight", "contestability", "bias", "privacy",
            "deepfake", "guideline", "notified rule", "sectoral governance",
        ],
        "Audited ledgers route the 2020 AI-capability objective concept, the 2023 clinical-diagnosis/privacy Mains demand and the 2025 AI-drones-GIS planning demand here. No objective key, model claim or summit outcome is invented.",
        pyqs, AI_LIVE_ATTEMPTS,
        "The IndiaAI governance-guidelines article was substantively fetched on 2026-09-03 and confirms the advisory-group, subcommittee and consultation process. It does not create an AI Act. Mission outlays, compute measures, model selections, model status and safety-institute status remain dated official-source claims.",
        extra=["00_Master-Framework.md", "ANSWER-WORTHINESS-AUDIT.md"],
        register_answer_spine=[
            "DEFINE AI ML DEEP LEARNING GENERATIVE AI MODEL AND USE CASE",
            "SEPARATE BENCHMARK PROTOTYPE DEPLOYMENT AND MEASURED OUTCOME",
            "MAP MeitY INDIAAI DIGITAL INDIA CORPORATION NITI AND REGULATORS",
            "TRACE DATA MODEL COMPUTE PROCUREMENT DECISION AND MONITORING",
            "RETAIN HUMAN OVERSIGHT REASONS CONTESTABILITY APPEAL AND REMEDY",
            "DISTINGUISH ADVISORY GUIDELINE NOTIFIED RULE ACT AND SECTORAL LAW",
            "DATE-STAMP OUTLAY COMPUTE MODEL AND SUMMIT CLAIMS",
        ],
    )


def _topic_10() -> dict[str, object]:
    facts = [
        ("Bit-qubit boundary", "A classical bit is recorded as 0 or 1, while a qubit is a quantum state described by amplitudes over basis states and yields a classical outcome on measurement; it is not simply a faster bit."),
        ("Superposition-boundary", "Superposition is a weighted combination of basis states before measurement; saying a qubit is two ordinary classical values at once obscures amplitudes, probability and measurement."),
        ("Entanglement-boundary", "Entanglement is a joint non-factorisable state of two or more quantum systems; a single qubit can be in superposition but cannot be entangled with itself, and entanglement enables no faster-than-light signalling."),
        ("No-cloning boundary", "The no-cloning principle forbids perfect copying of an arbitrary unknown quantum state; it helps explain quantum-communication security but does not prevent all copying of classical information or known basis states."),
        ("Interference-measurement boundary", "Quantum algorithms manipulate amplitudes so interference can suppress unwanted paths and reinforce useful outcomes before measurement; superposition alone does not test every answer and reveal all results."),
        ("Decoherence-boundary", "Decoherence is loss of usable quantum coherence through environmental interaction, making isolation, cryogenics, vacuum, shielding, control and materials central engineering constraints."),
        ("Physical-logical boundary", "A physical qubit is a hardware quantum system, while a logical qubit is error-corrected information encoded across many physical qubits; a physical-qubit count is not a fault-tolerant capability count."),
        ("Computing-boundary", "Quantum computing offers different algorithms for selected problem classes such as simulation, factoring, search or optimisation; it is not universally faster and does not replace ordinary classical computing."),
        ("Communication-boundary", "Quantum communication uses quantum states and protocols for tasks such as key distribution, while quantum computing processes information; a secure link is not a quantum computer."),
        ("QKD-boundary", "Quantum key distribution detects disturbance during quantum-state exchange for key establishment, but still needs authenticated endpoints, implementation security and a wider encryption system; QKD does not encrypt all data by itself."),
        ("QKD-PQC boundary", "QKD uses specialised quantum hardware and links, while post-quantum cryptography uses classical mathematical algorithms designed to resist quantum attack and can be deployed through software and standards migration."),
        ("Sensing-metrology boundary", "Quantum sensing and metrology exploit quantum sensitivity for precise measurement such as clocks, magnetic or gravitational fields; a quantum sensor is not a smaller general-purpose quantum computer."),
        ("Materials-devices boundary", "Quantum materials and devices provide sources, detectors, control components and hardware substrates for computing, communication and sensing; the vertical is not a synonym for quantum computing."),
        ("NQM-mission boundary", "The National Quantum Mission is a DST-led capability mission across computing, communication, sensing and metrology, and materials and devices; it is not one machine, laboratory or company product."),
        ("DST-ministry boundary", "The Department of Science and Technology is a department under the Ministry of Science and Technology and implements NQM; DST should not be called a separate ministry."),
        ("Four-hub boundary", "NQM uses four thematic hubs hosted at IISc Bengaluru, IIT Madras with C-DOT, IIT Bombay and IIT Delhi for the four distinct verticals; a hub is an ecosystem institution, not proof of an operational system."),
        ("Target-achievement boundary", "A mission target states intended capability within a period, while approved funding, a hub, a research prototype, a laboratory demonstration and an operational system are separate evidence rungs."),
        ("Qubit-target boundary", "The NQM physical-qubit target is a hardware-scaling objective, not a claim that logical error-corrected qubits, useful quantum advantage or fault-tolerant computing have been achieved."),
        ("Cryptographic-readiness boundary", "Quantum risk includes harvest-now-decrypt-later exposure, so cryptographic inventory and post-quantum migration are present governance tasks even before a cryptographically relevant quantum computer exists."),
        ("Volatile-claim boundary", "Mission outlay, dates, target qubits, communication distance, startup count, prototype performance and operational status require dated official DST or mission sources and cannot be upgraded from announcements."),
    ]
    traps = [
        "Do not call a qubit a faster classical bit or two stored bits.",
        "Do not merge superposition with entanglement.",
        "Do not use entanglement for faster-than-light signalling.",
        "Do not claim no-cloning prevents every form of copying.",
        "Do not infer useful computation from superposition alone.",
        "Do not merge physical and logical qubits.",
        "Do not claim quantum computers accelerate every problem.",
        "Do not merge computing, communication, sensing and materials.",
        "Do not claim QKD encrypts all data or replaces authentication.",
        "Do not merge QKD and post-quantum cryptography.",
        "Do not turn a mission target or hub into an achievement.",
        "Do not invent qubit, distance, prototype or operational claims.",
    ]
    titles = [
        "Classical bits qubits amplitudes and measurement",
        "Superposition entanglement and no-cloning",
        "Interference algorithms and measurement limits",
        "Decoherence coherence time and engineering stack",
        "Physical qubits logical qubits and error correction",
        "Quantum computing and problem-specific advantage",
        "Quantum communication and QKD architecture",
        "QKD authentication implementation and system limits",
        "Post-quantum cryptography and migration strategy",
        "Quantum sensing and metrology",
        "Quantum materials devices sources and detectors",
        "National Quantum Mission and DST",
        "Four thematic hubs and vertical ownership",
        "Mission target prototype and operational-status ladder",
        "Cryptographic readiness and volatile-claim audit",
    ]
    routes = [
        "Define state amplitudes and measurement before applications.",
        "Separate one-system superposition from multi-system entanglement.",
        "Explain interference without parallel-answer mythology.",
        "Show why control hardware and materials matter.",
        "Use logical qubits when discussing useful fault tolerance.",
        "Limit advantage claims to specific algorithms and tasks.",
        "Keep secure communication outside computing.",
        "Treat QKD as one component in a security system.",
        "Compare hardware links with classical algorithm migration.",
        "Explain precision measurement rather than computation.",
        "Place enabling hardware in its own mission vertical.",
        "Map the department, mission and four domains.",
        "Match each hub to one vertical without capability inflation.",
        "Label approval, target, prototype and operation separately.",
        "Conclude with PQC readiness and dated official evidence.",
    ]
    panels = [
        panel("Bit and qubit card", "comparison-table", [
            "CLASSICAL BIT -> recorded as 0 or 1",
            "QUBIT -> amplitudes over basis states",
            "MEASUREMENT -> one classical outcome with probability",
            "SPEED -> not the defining difference",
            "RULE -> state description is not two stored classical bits",
        ], [facts[0][0], facts[1][0]]),
        panel("Quantum principle split", "comparison-table", [
            "SUPERPOSITION -> one system in a combination of basis states",
            "ENTANGLEMENT -> joint state of two or more systems",
            "NO-CLONING -> arbitrary unknown state cannot be copied perfectly",
            "NO SIGNALLING -> entanglement does not transmit messages faster",
            "RULE -> each principle answers a different question",
        ], [facts[1][0], facts[2][0], facts[3][0]]),
        panel("Algorithm mechanism rail", "process-flow", [
            "PREPARE STATE -> initialise qubits",
            "QUANTUM GATES -> transform amplitudes",
            "INTERFERENCE -> suppress and reinforce paths",
            "MEASUREMENT -> obtain classical sample",
            "TRAP -> superposition does not reveal every answer",
        ], [facts[4][0]]),
        panel("Decoherence engineering stack", "causal-chain", [
            "ENVIRONMENTAL INTERACTION -> phase information degrades",
            "COHERENCE TIME -> finite computation window",
            "CRYOGENICS / VACUUM / SHIELDING -> reduce disturbance",
            "CONTROL ELECTRONICS / MATERIALS -> execute accurate gates",
            "OUTCOME -> engineering, not theory alone, limits scale",
        ], [facts[5][0], facts[12][0]]),
        panel("Physical-to-logical ladder", "status-ladder", [
            "PHYSICAL QUBIT -> noisy hardware element",
            "ERROR CHARACTERISATION -> measure failure channels",
            "ERROR-CORRECTING CODE -> redundant encoding",
            "LOGICAL QUBIT -> protected information unit",
            "RULE -> raw qubit count is not useful capability",
        ], [facts[6][0], facts[17][0]]),
        panel("Four technology families", "comparison-table", [
            "COMPUTING -> selected information-processing algorithms",
            "COMMUNICATION -> quantum-state links and key distribution",
            "SENSING / METROLOGY -> precision measurement",
            "MATERIALS / DEVICES -> enabling hardware substrate",
            "TRAP -> quantum technology is not computing alone",
        ], [facts[7][0], facts[8][0], facts[11][0], facts[12][0]]),
        panel("QKD security chain", "process-flow", [
            "QUANTUM STATES -> distribute key material",
            "DISTURBANCE TEST -> reveal possible interception",
            "AUTHENTICATED ENDPOINTS -> prevent impersonation",
            "CLASSICAL ENCRYPTION -> protects message content",
            "RULE -> QKD alone is not a complete secure network",
        ], [facts[9][0]]),
        panel("QKD versus PQC", "comparison-table", [
            "QKD -> quantum hardware and physical link",
            "PQC -> classical quantum-resistant algorithms",
            "QKD PURPOSE -> specialised key distribution",
            "PQC PURPOSE -> broad standards and software migration",
            "POLICY -> complementary tools with different timelines",
        ], [facts[10][0], facts[18][0]]),
        panel("NQM institution map", "institution-map", [
            "MINISTRY OF SCIENCE AND TECHNOLOGY -> ministerial umbrella",
            "DST -> implementing department",
            "NQM -> national capability mission",
            "T-HUBS -> four vertical ecosystem anchors",
            "RULE -> department, mission and hub are distinct",
        ], [facts[13][0], facts[14][0], facts[15][0]]),
        panel("Four T-Hub map", "comparison-table", [
            "IISc BENGALURU -> Quantum Computing",
            "IIT MADRAS WITH C-DOT -> Quantum Communication",
            "IIT BOMBAY -> Quantum Sensing and Metrology",
            "IIT DELHI -> Quantum Materials and Devices",
            "TRAP -> hub creation is not operational capability",
        ], [facts[15][0]]),
        panel("Readiness ladder", "status-ladder", [
            "CABINET APPROVAL -> mission authority and outlay",
            "TARGET -> intended future capability",
            "RESEARCH PROTOTYPE -> bounded demonstration",
            "VALIDATED SYSTEM -> repeatable performance evidence",
            "OPERATIONAL DEPLOYMENT -> field use with sustainment",
        ], [facts[16][0], facts[17][0]]),
        panel("Quantum claim firewall", "answer-spine", [
            "DEFINE -> qubit, superposition, entanglement and decoherence",
            "CLASSIFY -> computing, communication, sensing or materials",
            "SEPARATE -> physical and logical qubits; QKD and PQC",
            "LABEL -> approval, target, prototype, validation and operation",
            "VERIFY -> outlay, qubits, distance and startup claims officially",
        ], [facts[18][0], facts[19][0]]),
    ]
    pyqs = [
        common.make_pyq_solution(facts, "2022", "Prelims GS-I", "Identify the qubit concept in a quantum-computing context.", "Verified routed objective concept; the official key was unavailable locally, so no answer letter is asserted.", [0, 1, 2, 4]),
        common.make_pyq_solution(facts, "2025", "Prelims GS-I", "Assess claims about the Majorana 1 chip, quantum computing and deep learning.", "Verified routed objective concept; the package preserves company-claim and technology-taxonomy boundaries without asserting an answer letter.", [6, 7, 16, 19]),
        common.make_pyq_solution(facts, "2026", "Prelims GS-I", "Assess National Quantum Mission targets and thematic hubs.", "Provisional routed concept; no option letter, achieved qubit count or operational system is inferred.", [13, 14, 15, 16, 17, 19]),
    ]
    return common.topic(
        10, "National Quantum Mission and Quantum Technology",
        "10_National-Quantum-Mission-and-Quantum-Tech", facts, traps,
        [
            (10, "Distinguish a classical bit from a qubit and explain measurement.", [0, 1, 4]),
            (10, "Differentiate superposition, entanglement and no-cloning.", [1, 2, 3]),
            (15, "Explain why physical-qubit counts do not establish fault-tolerant quantum capability.", [5, 6, 17]),
            (15, "Compare quantum computing, communication, sensing and materials as separate technology families.", [7, 8, 11, 12]),
            (20, "Evaluate the National Quantum Mission through its four hubs, targets and readiness boundaries.", [13, 14, 15, 16, 17, 19]),
            (20, "Assess India's quantum-security strategy by distinguishing QKD, post-quantum cryptography and cryptographic readiness.", [3, 8, 9, 10, 18, 19]),
        ],
        titles, routes, panels,
        [
            "classical bit", "qubit", "superposition", "entanglement",
            "no-cloning", "interference", "measurement", "decoherence",
            "physical qubit", "logical qubit", "quantum error correction",
            "quantum computing", "quantum communication", "QKD",
            "post-quantum cryptography", "quantum sensing",
            "metrology", "quantum materials and devices",
            "National Quantum Mission", "DST", "thematic hubs",
        ],
        "Audited ledgers route the 2022 qubit concept, the 2025 Majorana-company-claim taxonomy and a provisional 2026 NQM-target concept here. No objective key, achieved qubit count, communication distance or operational capability is invented.",
        pyqs, QUANTUM_LIVE_ATTEMPTS,
        "The DST NQM page returned only its title on direct retrieval on 2026-09-03. Official-domain search confirmed the authoritative mission pages but supplied no new achievement claim. Mission targets, physical-qubit counts, communication distances, prototypes and deployment status remain dated DST-source facts.",
        extra=["00_Master-Framework.md", "ANSWER-WORTHINESS-AUDIT.md"],
        register_answer_spine=[
            "DEFINE BIT QUBIT AMPLITUDES MEASUREMENT AND INTERFERENCE",
            "SEPARATE SUPERPOSITION ENTANGLEMENT NO-CLONING AND NO-SIGNALLING",
            "TRACE DECOHERENCE PHYSICAL QUBITS ERROR CORRECTION AND LOGICAL QUBITS",
            "CLASSIFY COMPUTING COMMUNICATION SENSING METROLOGY MATERIALS DEVICES",
            "COMPARE QKD HARDWARE WITH PQC ALGORITHM MIGRATION",
            "MAP DST NQM FOUR T-HUBS TARGETS AND READINESS RUNGS",
            "DATE-STAMP OUTLAY QUBIT DISTANCE STARTUP AND PROTOTYPE CLAIMS",
        ],
    )


TOPIC_06 = _topic_06()
TOPIC_07 = _topic_07()
TOPIC_08 = _topic_08()
TOPIC_09 = _topic_09()
TOPIC_10 = _topic_10()
