"""Authored content data for Social Justice learner-v2 Topics 03-04."""

from __future__ import annotations

import generate_social_justice_common as common


def plan(
    title: str,
    indexes: list[int],
    caution: str,
    exam_use: str,
) -> tuple[str, list[int], str, str]:
    return title, indexes, caution, exam_use


def panel(
    title: str,
    kind: str,
    lines: list[str],
    references: list[str],
) -> tuple[str, str, str, list[str]]:
    return title, kind, "\n".join(lines), references


TOPIC_03 = common.topic(
    3,
    "Health Systems, Public Health and Universal Health Coverage",
    "03_Health-Systems-Public-Health-and-Universal-Health-Coverage",
    "03_Health-Systems-Public-Health-and-Universal-Health-Coverage_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and the demands routed to it", "This topic owns the health half of the capability argument, namely the universal-health-coverage standard, the policy vision, the mission that funds public delivery, the two pillars of the flagship health programme, the tiered public infrastructure and the financial-protection measure by which the whole system is judged, and its distinctive feature is the densest direct-question record in the folder: four General Studies Mains demands from 2018, 2020, 2021 and 2024 and three objective demands from 2023 and 2024 are routed to it in the audited ledgers; the macro economics of health financing belongs to the Economy owner, the elderly-care share of the 2020 demand is jointly owned with the senior-citizens topic, and this topic argues coverage, provision and protection."),
        ("Universal health coverage and its three dimensions", "Universal health coverage means ensuring that all people have access to the promotive, preventive, curative and rehabilitative health services they need, of sufficient quality, without suffering financial hardship, and it is analysed on three dimensions that the World Health Organization presents as a cube: population, which is the breadth of who is covered, services, which is the depth of what is covered, and financial protection, which is the height of how little the user pays at the point of service; the analytical value of the cube is that a system can expand on one dimension while contracting on another, so an answer that reports only beneficiary numbers has measured one edge of a three-dimensional claim."),
        ("The National Health Policy of 2017 and what it is not", "The National Health Policy, 2017 is India's guiding health-policy document, and the owners record its goals as raising public health expenditure to two and a half per cent of gross domestic product, strengthening primary care, achieving universal health coverage and reducing out-of-pocket expenditure; the examinable discipline is that it is a policy document and not an enacted statute, so its targets are commitments rather than justiciable entitlements, and describing them as legally binding is a status error of exactly the kind this folder is built to prevent."),
        ("The National Health Mission and its two sub-missions", "The National Health Mission's own official page, read on 2 September 2026, records that the National Rural Health Mission was launched by the Prime Minister on 12 April 2005 to provide accessible, affordable and quality health care to the rural population and especially to vulnerable groups, and that the Union Cabinet, by its decision dated 1 May 2013, approved the launch of the National Urban Health Mission as a sub-mission of an over-arching National Health Mission with the National Rural Health Mission being the other sub-mission; the same page records special focus on the Empowered Action Group States, the North Eastern States, Jammu and Kashmir and Himachal Pradesh, a thrust on a fully functional, community-owned, decentralised health delivery system with inter-sectoral convergence acting on determinants such as water, sanitation, education, nutrition and social and gender equality, and measurement of facilities against the Indian Public Health Standards, so the mission is urban as well as rural and treating it as rural-only is a factual error."),
        ("The primary-care pillar of Ayushman Bharat", "The first pillar of Ayushman Bharat upgrades sub-centres and primary health centres into Health and Wellness Centres, now carried as Ayushman Arogya Mandirs, which deliver comprehensive primary health care through twelve service packages that extend beyond reproductive and child health to non-communicable diseases, mental health, ear, nose and throat care, ophthalmology, oral health, geriatric and palliative care and emergency care, staffed by a community health officer or mid-level health provider; the design intent is to shift care-seeking from hospitals to a local first-contact layer, which is why describing this pillar as reproductive and child health alone understates it."),
        ("The hospitalisation pillar of Ayushman Bharat and its two enrolment routes", "The second pillar, Pradhan Mantri Jan Arogya Yojana, provides cashless secondary and tertiary hospitalisation cover of up to five lakh rupees per family per year at empanelled public and private hospitals for its core eligible households, which are identified through the deprivation criteria of the socio-economic and caste census, and the owners separately record a distinct expansion under which all citizens aged seventy years and above can enrol regardless of income or that census status; the discipline required is exact, because the core scheme is eligibility-based while the age-based expansion is universal only for the seventy-plus group, so an age-specific expansion must never be written up as universal coverage for every age."),
        ("The health authority and the health accounts must not be conflated", "The National Health Authority is the autonomous body that implements the hospitalisation pillar, maintaining the beneficiary database, empanelling hospitals and processing claims, while the National Health Accounts estimates are the official source for the breakdown of health expenditure between public, private and out-of-pocket spending and are prepared through the national health accounts system; the owners record expressly that these two must not be confused, because one is an implementing agency and the other is an accounting estimate, and citing an expenditure share to the implementing agency is a sourcing error."),
        ("Out-of-pocket expenditure and its dated official sequence", "Out-of-pocket expenditure is health spending paid directly by households at the point of service, and the owners record the National Health Accounts sequence as 47.1 per cent of total health expenditure in 2019-20, 44.4 per cent in 2020-21 and 39.4 per cent in 2021-22, with the latest cited official estimate being 39.4 per cent for the accounting year 2021-22; two disciplines follow, first that the publication date must never be confused with the accounting year, and second that a falling national share is a dated aggregate rather than evidence that every household faces a lighter burden, and high out-of-pocket expenditure indicates inadequate public provision rather than high utilisation."),
        ("Catastrophic health expenditure as the impoverishment mechanism", "Catastrophic health expenditure is health spending that exceeds a threshold share of household income or consumption, commonly stated in the range of ten to twenty-five per cent, and it pushes households into poverty or debt, with high out-of-pocket expenditure as its primary driver; this is the mechanism that makes health a social-justice question rather than only a service-delivery question, because a single hospitalisation can undo years of asset accumulation, and it is the bridge that connects this topic to the poverty and nutrition owner."),
        ("The tiered public delivery structure", "The public health system is tiered from the sub-centre through the primary health centre and the community health centre to the sub-district and district hospital, and this hierarchy is the referral spine on which the first pillar's upgrade and the second pillar's empanelment both sit; naming the tier at which a failure occurs is what converts a general complaint about public hospitals into a diagnosis, because a vacancy at the sub-centre, a diagnostic gap at the primary health centre and a specialist shortage at the community health centre call for three different corrections."),
        ("Primary, secondary and tertiary care", "Primary care is first-contact preventive, promotive and basic curative care delivered at the wellness centre and the primary health centre, secondary care is specialist outpatient and inpatient care at the community health centre and the district hospital, and tertiary care is super-specialty and advanced procedural care at medical colleges and referral centres; the flagship programme is deliberately split along this line, with the first pillar addressing primary care and the second addressing secondary and tertiary care, so confusing the pillars is simultaneously a factual error and a conceptual one."),
        ("Marketisation of health care and what it produces", "Marketisation refers to the dominance of private providers in curative care, often unregulated or under-regulated, and the owners record its consequences as high costs, unnecessary procedures, catastrophic spending and inequitable access; this is the exact concern raised by the 2024 demand, so an answer to it must define the phenomenon and its harms before proposing measures, and must avoid the two symmetrical errors of denying the private sector's real capacity contribution and of treating regulation as automatic once a statute exists."),
        ("The regulatory toolkit and its enforcement condition", "The regulatory instruments recorded by the owners are the Clinical Establishments Act, 2010, a Central Act providing for the registration and regulation of clinical establishments which States must adopt or replace with equivalent legislation, price capping of the kind exercised by the national pharmaceutical pricing authority over devices, and standard treatment guidelines that promote rational care and cost control; each carries a stated enforcement condition, because State adoption of the Central Act varies and some States have not adopted or notified equivalent rules, and adoption of treatment guidelines varies across public and empanelled private providers, so a recommendation to regulate must name the adoption gap it is closing."),
        ("Social health insurance against tax-funded provision", "Social health insurance pools contribution-linked cover, of which the employees' state insurance system is the Indian example, whereas tax-funded programmes draw on general revenue, which is how both the health mission and the hospitalisation pillar are financed, and the owners record that India uses a mixed and fragmented architecture rather than one comprehensive national pool; the standing objective-question trap is to describe the hospitalisation pillar as contribution-based social health insurance, which reverses the two financing families."),
        ("The health financing chain and what insurance cannot buy", "The financing chain runs from revenue collection through risk pooling and strategic purchasing to service provision, and the owners record the decisive consequence that insurance without public primary care leaves prevention, medicines and outpatient out-of-pocket expenditure unresolved; this is the analytical core of any question about financial protection, because hospitalisation cover addresses the catastrophic tail while the recurring outpatient and medicine burden, which is where most household health spending actually occurs, is addressed only by funded primary provision."),
        ("Community health and the Alma-Ata inheritance", "The owners route community health through the Alma-Ata commitments of equity, participation, inter-sectoral action and appropriate technology, and map them onto accredited social health activists, auxiliary nurse midwives, village health, sanitation and nutrition committees and the upgraded wellness centres; this mapping is what allows a community-health demand to be answered with named Indian institutions rather than with an abstract restatement of health for all, and it also explains why inter-sectoral determinants such as water, sanitation and nutrition sit inside a health answer rather than outside it."),
        ("System capacity, federalism and the workforce constraint", "The owners record that the health mission, free drugs and diagnostics initiatives and the health-infrastructure mission strengthen systems while uneven State capacity and workforce vacancies limit outcomes, and that Union financing and standards depend on State delivery capacity because health is delivered by the States; the answer consequence is that a national financing announcement is a necessary but not sufficient condition, and that a graded verdict on any national health programme must be conditioned on the delivery capacity of the State in question."),
        ("Mental health as a rights framework with a capacity gap", "The Mental Healthcare Act, 2017 supplies a rights framework and the national tele-mental-health service expands access, but the owners record expressly that neither replaces district-level professionals and continuity of care; this is the folder's standard illustration that a statutory right and a technology channel together still leave a human-resource gap, and it is directly usable in any answer that asks whether a legal entitlement has been converted into a service."),
        ("Delivery instruments and the State implementing layer", "The health mission is a centrally sponsored scheme with Centre-State cost sharing that supports accredited social health activists and auxiliary nurse midwives, free drugs and diagnostics, mobile medical units and maternal-health support of the kind delivered through the maternity protection scheme, while State health agencies implement the hospitalisation pillar at State level and may add State-funded top-up schemes; naming this two-layer arrangement is what allows an answer to explain why identical national schemes produce unequal outcomes across States."),
        ("The dashboard-output boundary and honest question ownership", "The owners record that cumulative card counts and cumulative claim counts are dashboard outputs and are not by themselves a measure of service quality or of financial protection, so this package asserts no card total, claim total, empanelment count, wellness-centre count, expenditure share beyond the dated national health accounts sequence, or state-level rank. On ownership, four General Studies Mains demands are routed to this topic in the audited ledgers, from 2018, 2020, 2021 and 2024, with the 2020 geriatric and maternal-care demand recorded as cross-cutting ownership shared with the senior-citizens topic, and three objective demands are routed, namely the 2023 maternal-health scheme question and the 2023 public-health-system question whose official keys the ledgers record as unavailable locally, and the 2024 maternal-health scheme question for which the ledger records that the official Set-A key is available locally but expressly states that no answer is recorded or inferred; this package therefore records no option for any of the three."),
    ],
    [
        "Do not describe the National Health Policy, 2017 as an enacted statute, because it is a policy document whose targets are commitments rather than justiciable entitlements.",
        "Do not treat the national health mission as rural-only, because the urban sub-mission was approved by the Union Cabinet decision dated 1 May 2013 under an over-arching mission.",
        "Do not describe the primary-care pillar as reproductive and child health alone, because it delivers twelve comprehensive primary health care service packages.",
        "Do not describe the hospitalisation pillar as universal for every age, because its core coverage is eligibility-based and only the seventy-plus expansion is age-universal.",
        "Do not swap the two pillars, because one is comprehensive primary care and the other is secondary and tertiary hospitalisation cover.",
        "Do not present the hospitalisation pillar as contribution-based social health insurance, because it is tax-funded while the employees' state insurance system is the contributory example.",
        "Do not confuse the implementing health authority with the national health accounts estimates, because one empanels and pays while the other measures expenditure.",
        "Do not confuse a publication date with an accounting year when citing the out-of-pocket expenditure share.",
        "Do not read high out-of-pocket expenditure as high utilisation, because it indicates inadequate public provision and weak financial protection.",
        "Do not treat a falling national expenditure share as evidence about any particular household, because it is a dated aggregate.",
        "Do not assume the Clinical Establishments Act, 2010 is uniformly enforced, because State adoption or equivalent notification varies.",
        "Do not offer hospitalisation insurance as an answer to outpatient and medicine costs, because insurance without funded primary care leaves prevention, medicines and outpatient spending unresolved.",
        "Do not treat a statutory mental-health right and a tele-service as a substitute for district professionals and continuity of care.",
        "Do not cite a cumulative card, claim, empanelment or facility count as evidence of service quality or financial protection.",
        "Do not attribute a delivery failure to national financing alone, because delivery capacity and workforce vacancies sit with the States.",
        "Do not record or infer an option for any routed objective demand, including the one whose official Set-A key the ledger reports as available locally.",
    ],
    [
        (10, "Distinguish the two pillars of Ayushman Bharat and explain how they jointly serve universal health coverage.", "The two pillars address different rungs of the care hierarchy and different edges of the coverage cube, so the answer must define each precisely, connect them through the referral spine and close by naming the dimension that remains weakest.", [4, 5, 1, 14]),
        (10, "Analyse why a functioning primary health structure is a precondition for sustainable development.", "Primary care is where prevention, early detection and continuity are produced, so the answer must show that hospital-led systems buy treatment without buying health, and must anchor the claim in named Indian primary-care institutions.", [15, 4, 9, 16]),
        (15, "Suggest measures through which the State can contain the adverse impact of marketisation and extend public healthcare to the grassroots level.", "Containment requires provision and regulation together, so the answer must define marketisation and its harms, propose expansion of comprehensive primary care and mission-funded public provision, and pair each regulatory instrument with the adoption gap it must close.", [11, 12, 3, 4]),
        (15, "Examine the claim that insurance-led financing alone can deliver financial protection in health.", "Insurance covers the catastrophic tail while most household spending is recurring and outpatient, so the examination must run the financing chain, use the dated expenditure sequence and end with a conditional rather than a categorical verdict.", [14, 7, 8, 13]),
        (20, "Assess India's progress towards universal health coverage across the population, service and financial-protection dimensions.", "Progress is uneven across the three dimensions, so the assessment must test each edge separately with dated evidence, state which edge the available evidence cannot settle and close with a graded verdict carrying an explicit data caveat.", [1, 5, 7, 19]),
        (20, "Assess the federal and capacity conditions under which national health financing produces measured health outcomes.", "National money becomes health only through State delivery capacity, so the assessment must connect financing, standards, workforce and inter-sectoral determinants, and must end by naming the condition on which the verdict would reverse.", [16, 3, 18, 17]),
    ],
    [
        plan("What the health owner holds and how it is examined", [0], "Health-financing macroeconomics belongs to Economy and elderly care is jointly owned.", "Open a health demand by naming the coverage dimension that the question actually tests."),
        plan("The universal health coverage cube", [1], "A system can expand one dimension while contracting another.", "Structure any health-system answer on three separable dimensions instead of a scheme list."),
        plan("The policy vision and its exact status", [2], "The policy is a document, not a statute, so its targets are commitments rather than entitlements.", "Cite the national target without upgrading a policy commitment into a legal right."),
        plan("The mission, its sub-missions and its official dates", [3], "The mission is urban as well as rural, with a Cabinet decision dated 1 May 2013 for the urban arm.", "Anchor public provision in a dated, correctly described national mission."),
        plan("The primary-care pillar and its twelve packages", [4], "Describing this pillar as reproductive and child health alone understates it.", "Show the first-contact layer that a grassroots-reach demand is actually asking about."),
        plan("The hospitalisation pillar and its two enrolment routes", [5], "The core route is eligibility-based; only the seventy-plus expansion is age-universal.", "State an entitlement precisely instead of converting an expansion into universality."),
        plan("The authority, the accounts and the expenditure sequence", [6, 7], "The implementing authority and the expenditure estimates are different sources.", "Attribute a financial-protection figure to the right body with its accounting year."),
        plan("Catastrophic expenditure as the impoverishment mechanism", [8], "A single hospitalisation can undo years of asset accumulation.", "Connect health financing to poverty rather than treating it as service delivery alone."),
        plan("The tiered structure and the three levels of care", [9, 10], "Naming the failing tier is what converts a complaint into a diagnosis.", "Locate a delivery failure at a named tier of the referral spine."),
        plan("Marketisation and what it produces", [11], "Neither deny private capacity nor assume regulation follows automatically from a statute.", "Define the phenomenon the 2024 demand names before proposing any measure."),
        plan("The regulatory toolkit and its adoption gap", [12], "State adoption of the central regulatory Act and of treatment guidelines varies.", "Recommend regulation with the adoption condition that makes it real."),
        plan("Financing families and the chain that insurance cannot complete", [13, 14], "Insurance without funded primary care leaves prevention, medicines and outpatient costs unresolved.", "Answer a financial-protection demand at the level of the financing chain."),
        plan("Community health and the Alma-Ata inheritance", [15], "Inter-sectoral determinants belong inside a health answer, not outside it.", "Answer a community-health demand with named Indian institutions."),
        plan("Capacity, federalism and the mental-health gap", [16, 17], "A statutory right and a tele-service still leave a district workforce gap.", "Condition a verdict on State delivery capacity rather than on national announcements."),
        plan("Delivery instruments, dashboards and honest ownership", [18, 19], "Cumulative counts are outputs and prove nothing about quality or protection.", "Close with the two-layer delivery arrangement and an explicit dashboard boundary."),
    ],
    [
        panel("Coverage cube", "root-axes", [
            "POPULATION -> breadth: who is covered, all citizens or identified beneficiaries",
            "SERVICES -> depth: promotive, preventive, curative and rehabilitative care",
            "FINANCIAL PROTECTION -> height: how little the household pays at the point of care",
            "RULE -> a system can widen one edge while narrowing another; test all three",
        ], ["Universal health coverage and its three dimensions"]),
        panel("Policy and mission card", "labelled-system", [
            "POLICY 2017 -> raise public health expenditure to 2.5 per cent of gross domestic product",
            "ITS STATUS -> a policy document, not an enacted statute; commitments, not entitlements",
            "RURAL MISSION -> launched 12 April 2005 for the rural population and vulnerable groups",
            "URBAN MISSION -> Union Cabinet decision dated 1 May 2013 created it as a sub-mission",
            "SPECIAL FOCUS -> Empowered Action Group States, North East, Jammu and Kashmir, Himachal",
            "BENCHMARK -> facilities measured against the Indian Public Health Standards",
        ], ["The National Health Policy of 2017 and what it is not", "The National Health Mission and its two sub-missions"]),
        panel("Two pillars kept apart", "comparison-table", [
            "PILLAR ONE -> wellness centres and health mandirs; comprehensive primary health care",
            "ITS PACKAGE -> twelve services including non-communicable disease and mental health",
            "ITS STAFF -> community health officer or mid-level health provider",
            "PILLAR TWO -> cashless secondary and tertiary hospitalisation cover",
            "ITS QUANTUM -> up to five lakh rupees per family per year at empanelled hospitals",
        ], ["The primary-care pillar of Ayushman Bharat", "The hospitalisation pillar of Ayushman Bharat and its two enrolment routes"]),
        panel("Two enrolment routes", "matrix", [
            "CORE ROUTE -> eligibility-based, identified through census deprivation criteria",
            "AGE ROUTE -> every citizen aged seventy and above may enrol regardless of income",
            "PRECISION -> the age route is universal only for that age group",
            "ERROR TO AVOID -> writing an age-specific expansion up as universal cover for all ages",
        ], ["The hospitalisation pillar of Ayushman Bharat and its two enrolment routes"]),
        panel("Source discipline card", "evidence-table", [
            "HEALTH AUTHORITY -> implements the hospitalisation pillar; empanels and pays claims",
            "HEALTH ACCOUNTS -> official estimates of public, private and out-of-pocket spending",
            "SEQUENCE -> 47.1 per cent in 2019-20; 44.4 per cent in 2020-21; 39.4 per cent in 2021-22",
            "RULE -> never confuse the publication date with the accounting year",
            "MEANING -> a high share signals weak public provision, not high utilisation",
        ], ["The health authority and the health accounts must not be conflated", "Out-of-pocket expenditure and its dated official sequence"]),
        panel("Impoverishment mechanism", "process-flow", [
            "ILLNESS -> care is sought from a provider outside the funded public layer",
            "-> OUT-OF-POCKET PAYMENT at the point of service",
            "-> CATASTROPHIC SPENDING: above a threshold share of household income or consumption",
            "-> ASSET SALE OR DEBT: years of accumulation are undone by one hospitalisation",
            "LINK -> this is where the health owner meets the poverty owner",
        ], ["Catastrophic health expenditure as the impoverishment mechanism"]),
        panel("Referral spine", "hierarchy", [
            "SUB-CENTRE -> first contact; outreach and community-level services",
            "PRIMARY HEALTH CENTRE -> preventive, promotive and basic curative care",
            "COMMUNITY HEALTH CENTRE -> specialist outpatient and inpatient care",
            "DISTRICT HOSPITAL -> secondary care and the gateway to tertiary referral",
            "USE -> name the failing tier; a vacancy, a diagnostic gap and a specialist shortage differ",
        ], ["The tiered public delivery structure", "Primary, secondary and tertiary care"]),
        panel("Marketisation and its harms", "path-consequence", [
            "PRIVATE DOMINANCE IN CURATIVE CARE -> often unregulated or under-regulated",
            "-> HIGH COSTS and unnecessary procedures",
            "-> CATASTROPHIC SPENDING and inequitable access",
            "BALANCE -> do not deny private capacity, and do not assume regulation is automatic",
        ], ["Marketisation of health care and what it produces"]),
        panel("Regulatory toolkit", "evidence-table", [
            "CLINICAL ESTABLISHMENTS ACT, 2010 -> registration and regulation of establishments",
            "ITS CONDITION -> States must adopt it or notify equivalent legislation; adoption varies",
            "PRICE CAPPING -> exercised over devices by the pharmaceutical pricing authority",
            "TREATMENT GUIDELINES -> promote rational care and cost control; uptake varies",
            "RULE -> name the adoption gap a regulatory recommendation is meant to close",
        ], ["The regulatory toolkit and its enforcement condition"]),
        panel("Financing families and chain", "comparison", [
            "SOCIAL HEALTH INSURANCE -> contribution-linked pooling, as in the employees system",
            "TAX-FUNDED -> general revenue, as in the health mission and the hospitalisation pillar",
            "CHAIN -> revenue collection to risk pooling to strategic purchasing to provision",
            "GAP -> insurance leaves prevention, medicines and outpatient spending unresolved",
            "TRAP -> calling the tax-funded pillar a contributory insurance scheme",
        ], ["Social health insurance against tax-funded provision", "The health financing chain and what insurance cannot buy"]),
        panel("Community health mapping", "matrix", [
            "EQUITY -> reach the underserved first rather than the easiest to reach",
            "PARTICIPATION -> village health, sanitation and nutrition committees",
            "INTER-SECTORAL ACTION -> water, sanitation, nutrition and gender equality",
            "APPROPRIATE TECHNOLOGY -> frontline health activists and auxiliary nurse midwives",
            "INSTITUTION -> the upgraded wellness centre as the named Indian delivery point",
        ], ["Community health and the Alma-Ata inheritance", "Delivery instruments and the State implementing layer"]),
        panel("Capacity limits and answer spine", "answer-spine", [
            "CONDITION -> Union financing and standards depend on State delivery capacity",
            "GAP -> workforce vacancies and uneven capacity limit identical national schemes",
            "MENTAL HEALTH -> a statutory right and a tele-service still need district professionals",
            "OPEN -> name the coverage dimension tested; BUILD -> provision plus regulation",
            "CLOSE -> graded verdict with a dashboard-count caveat and a reversal condition",
        ], ["System capacity, federalism and the workforce constraint", "Mental health as a rights framework with a capacity gap", "The dashboard-output boundary and honest question ownership"]),
    ],
    [
        "Universal Health Coverage",
        "National Health Policy",
        "2.5% of GDP",
        "National Health Mission",
        "12 April 2005",
        "1 May 2013",
        "Indian Public Health Standards",
        "Health and Wellness Centres",
        "Ayushman Arogya Mandir",
        "comprehensive primary health care",
        "PM-JAY",
        "5 lakh",
        "SECC",
        "National Health Authority",
        "National Health Accounts",
        "39.4%",
        "44.4%",
        "47.1%",
        "catastrophic",
        "sub-centre",
        "Clinical Establishments Act, 2010",
        "Standard Treatment Guidelines",
        "ESIC",
        "Alma-Ata",
        "Mental Healthcare Act, 2017",
        "Tele-MANAS",
        "PM-ABHIM",
        "State Health Agencies",
    ],
    "Four General Studies Mains demands and three objective demands are routed to this topic in the audited routing ledgers, and each Mains demand is reproduced below as a demand card with its printed year, paper, question number, directive, marks and word limit exactly as the ledgers record them: 2018 General Studies Paper II Question 7, 2020 General Studies Paper II Question 6, 2021 General Studies Paper II Question 6 and 2024 General Studies Paper II Question 17. The 2020 demand is recorded in the ledger as cross-cutting Core ownership shared with the senior-citizens topic, and that shared ownership is stated openly here rather than being claimed exclusively. Three objective demands are also routed, namely 2023 Prelims General Studies Paper I Question 51 on the maternal and neonatal mortality and institutional-delivery scheme, 2023 Prelims General Studies Paper I Question 75 on the curative, preventive and decentralised character of the Indian public health system, and 2024 Prelims General Studies Paper I Question 99 on the maternal-health abhiyan; the ledger records the official 2018-2023 Prelims keys as not held locally, and for the 2024 question it records that the official Set-A key is available locally while expressly stating that no answer is recorded or inferred, so this package records no option, key or inferred answer for any of the three and converts none of them into a solved question. The locally held OCR-searchable official General Studies papers were read only to confirm the printed wording of the routed Mains demands; no question was invented from them and no marking scheme or page precision was imported. Every model solution below is original work written to the repository's examiner-grade standard using the claim, named evidence, analysis and qualification pattern.",
    [
        (
            "2018",
            "General Studies Paper II Question 7",
            "Community-level healthcare intervention and Health for All. Explain, 10 marks, 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: health for all is achieved at the community level or not at all, because the determinants that decide health outcomes are produced outside the hospital. Named evidence and example: the Alma-Ata commitments of equity, participation, inter-sectoral action and appropriate technology; their Indian mapping onto accredited social health activists, auxiliary nurse midwives, village health, sanitation and nutrition committees and the upgraded wellness centres; the twelve comprehensive primary health care service packages delivered by a community health officer or mid-level health provider; and the national health mission's own recorded thrust, read on its official page on 2 September 2026, on a fully functional, community-owned, decentralised delivery system with inter-sectoral convergence on water, sanitation, education, nutrition and social and gender equality. Analysis: community-level intervention works because it converts an episodic curative contact into continuity, detects non-communicable disease and undernutrition before they become hospitalisations, and gives the village a participatory claim on the facility, which is why the same national financing produces different outcomes where the frontline layer is staffed and supervised. Qualification: the community layer is not a substitute for referral capacity, and no cumulative wellness-centre or worker count is asserted here because such counts are dashboard outputs rather than evidence of service quality. Why this earns marks: it explains a mechanism, names Indian institutions against a stated international standard and ends with a bounded claim.",
        ),
        (
            "2020",
            "General Studies Paper II Question 6",
            "Health policies for geriatric and maternal care. Discuss, 10 marks, 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger, where ownership is recorded as cross-cutting between this topic and the senior-citizens topic.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger as cross-cutting Core ownership shared with the senior-citizens topic, and that shared ownership is stated rather than claimed exclusively. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: geriatric and maternal care are the two life-cycle ends at which India's mixed health architecture is most exposed, because both need continuity rather than a single episode of treatment. Named evidence and example: the twelve comprehensive primary health care packages, which expressly include geriatric and palliative care alongside maternal services; the health mission's support for frontline workers, free drugs and diagnostics, mobile medical units and maternal-health protection; the hospitalisation pillar's age-based route allowing every citizen aged seventy and above to enrol regardless of income, distinct from its core eligibility-based route; and the tiered referral spine from the sub-centre to the district hospital. Analysis: maternal care is protected by a dense frontline and referral chain, so its failures are chiefly tier and transport failures, whereas geriatric care depends on chronic-disease management, medicines and palliative support that sit largely outside hospitalisation cover, which is why the outpatient and medicine burden is the binding constraint at the older end. Qualification: the age-based enrolment route must not be described as universal cover for every age, and no claim, card or facility count is cited as evidence of quality. Why this earns marks: it discusses two policy fields through one structural lens and separates two enrolment routes precisely.",
        ),
        (
            "2021",
            "General Studies Paper II Question 6",
            "Primary health structure as a precondition for sustainable development. Analyze, 10 marks, 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: a funded primary structure is the precondition because it is the only layer that produces prevention, early detection and continuity, which are the inputs sustainable development actually consumes. Named evidence and example: the universal health coverage cube with its population, service and financial-protection dimensions; the policy commitment to raise public health expenditure to two and a half per cent of gross domestic product and to build a primary-care-led model; the financing chain from revenue collection through risk pooling and strategic purchasing to service provision; and the national health accounts sequence recording out-of-pocket expenditure at 47.1 per cent of total health expenditure in 2019-20, 44.4 per cent in 2020-21 and 39.4 per cent in 2021-22. Analysis: hospital-led systems purchase treatment after the fact and leave the recurring outpatient and medicine burden with the household, so financial protection improves only as the primary layer absorbs first contact, and the same layer carries the inter-sectoral determinants of water, sanitation and nutrition on which every other development goal rests. Qualification: the expenditure sequence is a dated national aggregate that says nothing about a particular household, and the policy target is a commitment rather than a justiciable entitlement. Why this earns marks: it analyses a precondition through a financing mechanism with dated evidence and an explicit status caveat.",
        ),
        (
            "2024",
            "General Studies Paper II Question 17",
            "In a crucial domain like the public healthcare system the Indian State should play a vital role to contain the adverse impact of marketisation of the system. Suggest some measures through which the State can enhance the reach of public healthcare at the grassroots level, 15 marks, 250 words, exactly as recorded in the audited 2024-2025 Mains routing ledger and reproduced in the Basic owner.",
            "Routed to this owner in the audited 2024-2025 Mains routing ledger. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: marketisation is contained by provision and regulation together, and grassroots reach is a provision problem before it is a regulation problem. Named evidence and example: the recorded harms of marketisation, namely high costs, unnecessary procedures, catastrophic spending and inequitable access; the constitutional and policy basis for State intervention in the Directive Principle on public health and in the National Health Policy, 2017; the upgraded wellness centres delivering twelve comprehensive primary health care packages through a community health officer or mid-level health provider; the health mission's support for frontline workers, free drugs and diagnostics and mobile medical units, with its urban arm created by the Union Cabinet decision dated 1 May 2013; the hospitalisation pillar's cover of up to five lakh rupees per family per year; and the regulatory instruments of the Clinical Establishments Act, 2010, device price capping by the pharmaceutical pricing authority and standard treatment guidelines. Analysis: expanding the first-contact layer moves care-seeking away from the unregulated curative market, free drugs and diagnostics remove the two costs that push households into private provision, and financial protection shifts the catastrophic tail off the household, while regulation works only where the State has adopted the central Act or notified equivalent rules, so each measure must be paired with the adoption or staffing gap it closes. Qualification: the private sector's capacity contribution should not be denied, insurance cannot answer outpatient and medicine costs, and no cumulative card, claim or facility count is offered as proof of quality. Why this earns marks: it suggests measures that are institutionally specific, each attached to a named gap, and closes with a graded verdict rather than a wish list.",
        ),
    ],
    live_sources=["https://nhm.gov.in/index1.php?lang=1&level=1&sublinkid=969&lid=49"],
    current_note="One live official source was verified for this topic on 2026-09-02. The National Health Mission's own page was read successfully on that date and states that the National Rural Health Mission was launched by the Prime Minister on 12 April 2005 to provide accessible, affordable and quality health care to the rural population and especially to vulnerable groups, that the Union Cabinet by its decision dated 1 May 2013 approved the launch of the National Urban Health Mission as a sub-mission of an over-arching National Health Mission with the National Rural Health Mission being the other sub-mission, that under the rural mission the Empowered Action Group States as well as the North Eastern States, Jammu and Kashmir and Himachal Pradesh have been given special focus, and that the thrust of the mission is on establishing a fully functional, community-owned, decentralised health delivery system with inter-sectoral convergence at all levels to ensure simultaneous action on determinants of health such as water, sanitation, education, nutrition and social and gender equality, with institutional integration expected to provide a focus on outcomes measured against the Indian Public Health Standards for all health facilities. Only those statements of launch date, Cabinet decision, structure, focus States, thrust and benchmarking are used from that page. The achievement figures displayed on the same page are deliberately not imported, because they are programme-performance claims rather than the structural facts this package needs, and this package asserts no health achievement statistic of any kind. Two further official checks were attempted on the same date and did not yield usable content, namely the national health authority landing page, which returned no readable text, and a scheme portal that failed at the transport level, so nothing was read or used from either and no secondary summary has been treated as an official source. The remaining dated elements used are those already carried by the repository owners with their status checks, namely the National Health Policy, 2017 and its target of raising public health expenditure to two and a half per cent of gross domestic product, the two pillars of the flagship health programme with twelve comprehensive primary health care packages and hospitalisation cover of up to five lakh rupees per family per year, the eligibility-based core route identified through census deprivation criteria alongside the distinct enrolment route for all citizens aged seventy and above, the national health accounts out-of-pocket expenditure sequence of 47.1 per cent for 2019-20, 44.4 per cent for 2020-21 and 39.4 per cent for 2021-22, the Clinical Establishments Act, 2010 with its State-adoption condition, and the Mental Healthcare Act, 2017 with the national tele-mental-health service. Every one of those values is accounting-year-specific or programme-design-specific and is cited with that status. No cumulative card count, claim count, empanelment count or facility count is asserted, no State rank or score is asserted, no health outcome, mortality, morbidity or coverage indicator is asserted, no budget or expenditure number beyond the dated national health accounts sequence is asserted, no scheme eligibility rule beyond the two recorded enrolment routes is asserted, and no previous-year question, official answer key or option is asserted or inferred.",
)


TOPIC_04 = common.topic(
    4,
    "Education and Human-Resource Development",
    "04_Education-and-Human-Resource-Development",
    "04_Education-and-Human-Resource-Development_Learner-V2-Complete-Topic-Package.md",
    [
        ("What this owner holds and the demands routed to it", "This topic owns the education and skills half of human-resource development, namely the constitutional and statutory entitlement to elementary education, the policy restructuring that surrounds it, the umbrella scheme that funds school education, the foundational-learning mission that answers the learning crisis, the higher-education access measure and the skills ecosystem that converts schooling into employability, and its distinctive feature is that six General Studies Mains demands from 2020, 2021, 2022 and 2023 and one objective demand from 2018 are routed to it in the audited ledgers, which is the heaviest Mains load in the folder; the macro labour-market and demographic-dividend framing belongs to the Economy owner, and the audited ledger routes the 2024 public-examination-integrity demand to the Governance owner even though this owner discusses that Act, so no demand card is manufactured for it here."),
        ("Education as the second capability-conversion pillar", "Education is the second capability-conversion pillar after health, and the owner's conversion frame runs from input, meaning access and resources, through process, meaning curriculum, pedagogy, teachers and infrastructure, to outcome, meaning foundational literacy and numeracy, higher-order skills and employability; the analytical consequence is that entitlement, quality and skills must all hold for schooling to become capability, so an answer that reports enrolment has reported an input and has not yet reached the question."),
        ("Article 21-A and the Eighty-sixth Amendment", "Article 21-A is the constitutional basis of the education entitlement and was inserted by the Eighty-sixth Amendment of 2002, making free and compulsory education a fundamental right for children aged six to fourteen, and the doctrinal detail of that article belongs to the Polity owner while this topic applies the entitlement lens; the point that earns marks is that the fundamental right is age-bounded, so every claim about early childhood or secondary education must be located in policy rather than in the fundamental right."),
        ("The Right to Education Act, 2009 and its private-school obligation", "The Right of Children to Free and Compulsory Education Act, 2009 is the statutory framework for free and compulsory elementary education for ages six to fourteen, providing free schooling through the public system and a twenty-five per cent entry-level obligation for children from weaker and disadvantaged groups in private unaided non-minority schools, subject to the Act and to judicial interpretation; the owners record the implementation challenges of that obligation as delayed reimbursement to schools, documentation barriers for beneficiaries and uneven enforcement across States, which is the concrete evidence any answer about awareness or access should use."),
        ("The 2019 amendment and the detention question", "The Act originally prohibited detention and expulsion until Grade 8, and the owners record that the 2019 amendment restored State discretion for regular examinations in Classes V and VIII and permitted detention after instruction and a re-examination, so the position is not a simple return to detention but a conditional discretion exercisable by a State; the debate is genuinely two-sided, with motivation and accountability on one side and the risk of exclusion and dropout on the other, and stating the amendment's exact mechanism is what allows an answer to take a position without misstating the law."),
        ("The National Education Policy, 2020 and its status", "The National Education Policy, 2020 is a policy document and not a statute, and it restructures school education into a five plus three plus three plus four design covering the foundational stage for ages three to eight, the preparatory stage for ages eight to eleven, the middle stage for ages eleven to fourteen and the secondary stage for ages fourteen to eighteen, while emphasising foundational literacy and numeracy, mother-tongue instruction, multidisciplinary higher education, multiple entry and exit and vocational integration; because it is policy rather than statute, its extension of focus to early childhood care and education creates no statutory entitlement, and saying otherwise is a status error."),
        ("Samagra Shiksha as the umbrella school scheme", "Samagra Shiksha is the integrated centrally sponsored scheme of the education ministry that merges the earlier elementary and secondary programmes together with teacher education into a single umbrella, with Centre-State cost sharing covering infrastructure, the State quota of teacher salaries, training, information and communication technology, girls' hostels and inclusive education; two errors follow from misreading it, namely treating it as elementary-only when it covers elementary, secondary and teacher education, and treating it as a replacement for the Act when it is the scheme that implements the Act and the policy."),
        ("NIPUN Bharat and the foundational-learning target", "The National Initiative for Proficiency in Reading with Understanding and Numeracy is the mission launched under the policy in 2021 that targets foundational literacy and numeracy by the end of Grade 3, with a national target year of 2026-27, and it sets learning-outcome goals and competencies for which States prepare implementation plans with annual targets; it is a mission and not a scholarship, and its importance in an answer is that it is the first national instrument to make a learning outcome, rather than an enrolment count, the stated object of school policy."),
        ("Foundational literacy and numeracy and learning poverty", "Foundational literacy and numeracy denotes the basic reading, writing and arithmetic competencies expected by Grade 3, and the owners record that survey evidence has documented large gaps in these competencies, which is why the policy and the mission treat foundational learning as the learning crisis rather than as one objective among many; the related global concept recorded in the Advanced owner is learning poverty, the share of ten-year-olds unable to read and understand a simple text, which adds an international benchmark to the same idea."),
        ("Gross enrolment ratio and its dated higher-education values", "The gross enrolment ratio is total enrolment at a level of education, regardless of age, as a percentage of the official school-age population for that level, so it measures access and not completion or quality and can exceed one hundred where over-age enrolment is common, and the owners record the all-India survey on higher education for 2021-22 reporting an all-India ratio of 28.4 for the eighteen to twenty-three age group, up from 27.3 in 2020-21, with a female ratio of 28.5; the recorded discipline is to retain the survey year because later rounds update the figure, and the owners state expressly that the durable fact is the rising but unequal trend across region, gender and social group rather than any one year's percentage."),
        ("The learning survey and its scope discipline", "The owners record the 2024 round of the annual status of education report, a non-government rural household survey, as finding recovery from the 2022 learning shock alongside a continuing foundational deficit, with 23.4 per cent of government-school Standard III children able to read a Standard II text, and record it as the latest national foundational-learning round of that survey as of July 2026; the discipline attached is unusually strict and is itself examinable, namely that the round, the rural scope, the school type and the competency must all be cited together, that it is not an administrative dataset and that it must not be silently generalised to urban India."),
        ("The conversion chain and the three measurement systems", "The owner's conversion chain runs from enrolment to attendance, transition, completion, competency, higher education or skill and finally employment, and it records that the administrative school data system, the household learning survey and the higher-education survey measure different links in that chain; this is the structural device for any human-resource-development answer, because it forces the writer to say which link is failing and to cite the instrument that can actually observe that link, instead of asserting a general education crisis."),
        ("The twenty-five per cent obligation as an implementation test case", "The twenty-five per cent entry-level obligation in private unaided non-minority schools is the folder's standard test case for the gap between an enforceable entitlement and realised access, because the owners record its difficulties as delayed reimbursement to schools, documentation barriers for beneficiaries and uneven enforcement across States; it is therefore the natural evidence for the 2022 demand on awareness about schooling, since a right that families do not know about, cannot document and cannot enforce produces exactly the pattern the demand describes."),
        ("Digital education, its instruments and its access qualifications", "The owners record the national digital infrastructure for school content and teachers and the national online-course platform for higher education as the two named digital instruments, and they record the qualifications on digital access as devices, connectivity, language, disability and study space; the answer consequence is that digital education is neither a solution nor a distraction but a channel whose effect depends entirely on those five conditions, so a digital-education answer must argue conditional effect rather than declare transformation."),
        ("The policy against the fourth sustainable development goal", "The owners record the fourth sustainable development goal as inclusive and equitable quality education and lifelong learning for all, and record that the policy's early childhood, foundational-learning, multidisciplinary and vocational reforms are aligned with that goal but depend on finance and teachers; the critical-examination route is therefore to accept the alignment of stated objectives and to test delivery conditions, because the gap in this demand is not one of intention but one of financing, teacher supply and State capacity."),
        ("The skills ecosystem and its regulator", "The skills ecosystem recorded by the owners consists of the national skill mission for training, the National Council for Vocational Education and Training as the unified regulator of skill qualifications, awarding bodies and assessment agencies under the skill-development ministry, replacing earlier fragmented regulators, the National Apprenticeship Promotion Scheme which provides stipend support to employers hiring apprentices in order to bridge classroom training and workplace learning, and the national skills qualification framework, a competency-based hierarchy of ten levels enabling recognition, certification and mobility across formal and non-formal training."),
        ("Vocational integration and the constraints on it", "The policy proposes vocational exposure from Grade 6 and mandatory internship or skill courses in higher education in order to bridge the academic and vocational divide, and the owners record the constraints on this integration as stigma attached to vocational streams, employer participation, career counselling and the quality of matching between trainee and job; naming these four constraints is what turns an earn-while-you-learn answer into an argument, because the design is not contested while the conditions for its success are."),
        ("Credit portability and multiple entry and exit", "The academic bank of credits is the policy reform that enables students to accumulate credits from multiple institutions and redeem them for a degree, and it is the instrument that makes multiple entry and exit and lifelong learning operationally possible rather than merely aspirational; its examinable value is that it converts a stated principle into an administrative mechanism, and its limitation is that portability depends on institutions actually recognising and depositing credit."),
        ("The higher-education regulatory position as of mid-2026", "The owners record that a single higher-education regulator was proposed under the policy, that the relevant Bill was approved by the Cabinet in December 2025 and introduced in Parliament, and that as of mid-2026 it has not been enacted, so the existing regulators for universities, technical education and teacher education continue to function; this is a status fact rather than a design fact, and stating a proposed regulator as an existing one is exactly the policy-status error this package is built to prevent."),
        ("Ministry ownership, measurement boundary and honest question ownership", "The education ministry is the nodal ministry for the entitlement statute, the policy, the umbrella scheme, the foundational-learning mission and higher education, while the skill-qualification regulator sits under the skill-development ministry, and the owners record expressly that no dynamic dashboard figure is asserted for this topic because education indicators are published periodically by the administrative school data system, the higher-education survey and the household learning survey, so the durable fact is the policy and scheme architecture rather than a continuously changing coverage count. On ownership, six General Studies Mains demands are routed to this topic in the audited ledgers, from 2020, 2021, 2022 and 2023, with the 2023 skill-education and employment demand recorded as terminating in answer-complete Core across two subject routes shared with the Economy owner, and one objective demand from 2018 on teacher-qualification eligibility under the entitlement statute is routed with its official key recorded as unavailable locally, so no option is recorded or inferred; the audited ledger routes the 2024 public-examination-integrity demand to the Governance owner, and that routing is stated here rather than being annexed."),
    ],
    [
        "Do not describe the National Education Policy, 2020 as an enacted statute, because the statutory entitlement is the Right to Education Act, 2009 while the policy is a policy document.",
        "Do not extend the fundamental right under Article 21-A beyond ages six to fourteen, because early childhood and secondary coverage are policy rather than fundamental right.",
        "Do not describe the 2019 amendment as a simple return to detention, because it restored State discretion for regular examinations in Classes V and VIII with detention only after instruction and re-examination.",
        "Do not call the foundational-learning mission a scholarship scheme, because it is a mission setting learning-outcome goals and competencies.",
        "Do not treat the umbrella school scheme as elementary-only, because it covers elementary, secondary and teacher education.",
        "Do not say the umbrella scheme replaced the entitlement statute, because it is the scheme that implements the statute and the policy.",
        "Do not treat the gross enrolment ratio as a measure of completion or quality, because it measures access and can exceed the age cohort.",
        "Do not cite a higher-education enrolment ratio without its survey year, because later rounds update the figure.",
        "Do not generalise the rural household learning survey to urban India, and do not cite its value without the round, scope, school type and competency.",
        "Do not treat the household learning survey as an administrative dataset, because it is a non-government sample survey.",
        "Do not assert a general education crisis, because the marks lie in naming the failing link of the enrolment-to-employment chain and the instrument that observes it.",
        "Do not present digital education as transformative without the device, connectivity, language, disability and study-space qualifications.",
        "Do not state the proposed single higher-education regulator as already existing, because as of mid-2026 the Bill has not been enacted and the existing regulators continue to function.",
        "Do not attribute the skill-qualification regulator to the education ministry, because it sits under the skill-development ministry.",
        "Do not manufacture a demand card for the 2024 public-examination-integrity question, because the audited ledger routes it to the Governance owner.",
        "Do not record or infer an option for the routed objective demand on teacher-qualification eligibility, because the ledger records its official key as unavailable locally.",
    ],
    [
        (10, "Comment on the earn-while-you-learn approach and its contribution to meaningful vocational education and skilling.", "The design is not contested while its conditions are, so the comment must name the apprenticeship and qualification instruments, then argue stigma, employer participation, counselling and matching as the binding constraints.", [15, 16, 17, 11]),
        (10, "Suggest measures to remedy the inadequate attention given to human-resource development in India.", "Human-resource development fails at identifiable links rather than everywhere, so the answer must run the conversion chain, attach a measure to each failing link and end with a measurable safeguard rather than a general call for investment.", [1, 11, 14, 19]),
        (15, "Elaborate on the effect of digital initiatives on the functioning of the education system.", "Digital channels change reach without changing conversion by themselves, so the elaboration must name the two national instruments, argue effect conditional on five access constraints and test the claim against measured foundational learning.", [13, 10, 11, 12]),
        (15, "Critically examine the National Education Policy, 2020 against the fourth Sustainable Development Goal.", "Alignment of objectives is not the contested question, so the critical examination must accept the stated alignment, test finance, teachers and State capacity, and separate what is statutory from what is policy.", [5, 14, 7, 18]),
        (20, "Analyse the linkages between skill-development programmes and employment outcomes.", "The linkage is a chain with several breakable joints, so the analysis must run from training and certification through recognition and apprenticeship to matching and employment, and must state which joint the available evidence can and cannot observe.", [15, 16, 11, 9]),
        (20, "Assess whether the statutory right to elementary education has been converted into a right to learning.", "Access has been converted far more completely than learning, so the assessment must separate entitlement, process and outcome, use the dated foundational-learning evidence with its scope discipline and close with a graded verdict.", [3, 4, 7, 10]),
    ],
    [
        plan("What the education owner holds and how it is examined", [0], "Labour-market macroeconomics belongs to Economy and the 2024 examination-integrity demand to Governance.", "Open an education demand by naming the link of the conversion chain that the question tests."),
        plan("Education as the second capability pillar", [1], "Reporting enrolment reports an input and has not yet reached the question.", "Convert an education answer from access description into capability analysis."),
        plan("The constitutional right and the statutory entitlement", [2, 3], "The fundamental right is age-bounded to six to fourteen.", "Anchor the entitlement precisely before discussing any policy extension."),
        plan("The 2019 amendment and the detention question", [4], "The amendment restored conditional State discretion, not automatic detention.", "Take a position on a contested reform without misstating the law."),
        plan("The policy, its structure and its status", [5], "It is a policy document, so its early childhood focus creates no statutory entitlement.", "Separate what is statutory from what is policy in every education answer."),
        plan("The umbrella scheme and what it covers", [6], "It covers elementary, secondary and teacher education and does not replace the statute.", "Attribute funding and training correctly instead of naming a scheme loosely."),
        plan("The foundational-learning mission and the learning crisis", [7, 8], "It is a mission with outcome targets, not a scholarship.", "Show the first national instrument that makes learning rather than enrolment the object."),
        plan("The access measure and its dated values", [9], "The ratio measures access and must carry its survey year.", "Cite higher-education access with the discipline that keeps it from going stale."),
        plan("The learning survey and its scope discipline", [10], "The round, rural scope, school type and competency must be cited together.", "Use the strongest learning evidence without over-generalising it."),
        plan("The conversion chain and the three measurement systems", [11], "Different instruments observe different links, so name the link before naming the fix.", "Replace a general education-crisis claim with a located diagnosis."),
        plan("The private-school obligation as an implementation test case", [12], "Reimbursement delay, documentation and uneven enforcement are the recorded difficulties.", "Answer an awareness-and-access demand with concrete implementation evidence."),
        plan("Digital instruments and their five access conditions", [13, 14], "Digital effect is conditional on devices, connectivity, language, disability and study space.", "Argue conditional effect instead of declaring digital transformation."),
        plan("The skills ecosystem, its regulator and its constraints", [15, 16], "Stigma, employer participation, counselling and matching are the binding constraints.", "Turn a skilling answer into an argument about conditions rather than design."),
        plan("Credit portability and multiple entry and exit", [17], "Portability depends on institutions actually recognising and depositing credit.", "Convert a stated policy principle into a named administrative mechanism."),
        plan("Higher-education regulatory status and honest ownership", [18, 19], "The proposed single regulator is not enacted as of mid-2026 and no option is inferred for the routed objective demand.", "Close with a status-accurate regulatory picture and an explicit data boundary."),
    ],
    [
        panel("Conversion frame", "process-flow", [
            "INPUT -> access and resources: statutory entitlement, schools, teachers, materials",
            "-> PROCESS: curriculum, pedagogy, teacher capacity and infrastructure",
            "-> OUTCOME: foundational literacy and numeracy, higher-order skill, employability",
            "TEST -> enrolment is an input; the question begins at process and outcome",
        ], ["Education as the second capability-conversion pillar"]),
        panel("Entitlement anchor", "labelled-system", [
            "ARTICLE 21-A -> inserted by the Eighty-sixth Amendment of 2002",
            "AGE BAND -> free and compulsory education as a fundamental right for ages six to fourteen",
            "STATUTE -> the Right to Education Act, 2009 concretises the right",
            "PRIVATE OBLIGATION -> 25 per cent entry-level places for weaker and disadvantaged groups",
            "SCOPE -> private unaided non-minority schools, subject to the Act and judicial reading",
        ], ["Article 21-A and the Eighty-sixth Amendment", "The Right to Education Act, 2009 and its private-school obligation"]),
        panel("Detention position", "comparison", [
            "ORIGINAL POSITION -> no detention or expulsion until Grade 8",
            "AFTER 2019 -> State discretion restored for regular examinations in Classes V and VIII",
            "CONDITION -> detention only after instruction and a re-examination",
            "TWO-SIDED -> motivation and accountability against exclusion and dropout risk",
        ], ["The 2019 amendment and the detention question"]),
        panel("Policy structure", "hierarchy", [
            "FOUNDATIONAL -> ages three to eight; early childhood care plus Grades 1 and 2",
            "PREPARATORY -> ages eight to eleven; Grades 3 to 5",
            "MIDDLE -> ages eleven to fourteen; Grades 6 to 8",
            "SECONDARY -> ages fourteen to eighteen; Grades 9 to 12",
            "STATUS -> a policy document; the early childhood focus creates no statutory right",
        ], ["The National Education Policy, 2020 and its status"]),
        panel("Scheme and mission card", "evidence-table", [
            "UMBRELLA SCHEME -> merges elementary, secondary and teacher education under one head",
            "IT FUNDS -> infrastructure, training, technology, girls hostels, inclusive education",
            "FOUNDATIONAL MISSION -> launched 2021; literacy and numeracy by the end of Grade 3",
            "TARGET YEAR -> the national target year recorded by the owners is 2026-27",
            "RULE -> the scheme implements the statute and the policy; it replaces neither",
        ], ["Samagra Shiksha as the umbrella school scheme", "NIPUN Bharat and the foundational-learning target"]),
        panel("Measurement discipline", "matrix", [
            "ENROLMENT RATIO -> access only; not completion and not quality",
            "HIGHER EDUCATION 2021-22 -> all-India ratio 28.4 for ages eighteen to twenty-three",
            "PRIOR YEAR -> 27.3 in 2020-21; female ratio recorded at 28.5",
            "LEARNING SURVEY 2024 -> 23.4 per cent of government-school Standard III children",
            "ITS COMPETENCY -> able to read a Standard II text; rural household survey, not admin data",
        ], ["Gross enrolment ratio and its dated higher-education values", "The learning survey and its scope discipline"]),
        panel("Conversion chain and instruments", "process-flow", [
            "ENROLMENT -> ATTENDANCE -> TRANSITION -> COMPLETION",
            "-> COMPETENCY -> HIGHER EDUCATION OR SKILL -> EMPLOYMENT",
            "ADMINISTRATIVE SCHOOL DATA -> observes enrolment, transition and completion",
            "HOUSEHOLD LEARNING SURVEY -> observes competency in rural households",
            "HIGHER EDUCATION SURVEY -> observes access at the tertiary level",
            "RULE -> name the failing link and the instrument that can see it",
        ], ["The conversion chain and the three measurement systems"]),
        panel("Implementation test case", "path-consequence", [
            "OBLIGATION -> 25 per cent entry-level places in private unaided non-minority schools",
            "-> DELAYED REIMBURSEMENT to schools weakens compliance incentives",
            "-> DOCUMENTATION BARRIERS exclude the very households the clause names",
            "-> UNEVEN ENFORCEMENT across States produces unequal realised access",
            "USE -> the concrete evidence for a demand about awareness and schooling",
        ], ["The twenty-five per cent obligation as an implementation test case"]),
        panel("Digital channel conditions", "root-axes", [
            "SCHOOL PLATFORM -> national digital infrastructure for content and teachers",
            "HIGHER EDUCATION PLATFORM -> national online-course platform",
            "CONDITIONS -> devices, connectivity, language of instruction",
            "FURTHER CONDITIONS -> disability accessibility and a place at home to study",
            "RULE -> argue conditional effect, never declare transformation",
        ], ["Digital education, its instruments and its access qualifications"]),
        panel("Goal alignment test", "comparison-table", [
            "GOAL FOUR -> inclusive and equitable quality education and lifelong learning for all",
            "POLICY ALIGNMENT -> early childhood, foundational learning, multidisciplinary reform",
            "ALSO -> vocational integration and multiple entry and exit",
            "DEPENDENCY -> delivery depends on finance, teacher supply and State capacity",
            "ROUTE -> accept the stated alignment and test the delivery conditions",
        ], ["The policy against the fourth sustainable development goal"]),
        panel("Skills ecosystem", "evidence-table", [
            "TRAINING -> the national skill mission delivers and funds skill training",
            "REGULATION -> the vocational education and training council under the skills ministry",
            "APPRENTICESHIP -> stipend support to employers hiring apprentices",
            "FRAMEWORK -> a competency-based hierarchy of ten skill levels for recognition",
            "CONSTRAINTS -> stigma, employer participation, counselling and quality of matching",
        ], ["The skills ecosystem and its regulator", "Vocational integration and the constraints on it"]),
        panel("Status card and answer spine", "answer-spine", [
            "CREDIT BANK -> accumulate credit across institutions and redeem it for a degree",
            "REGULATORY STATUS -> the single higher-education regulator Bill is not enacted by mid-2026",
            "CONSEQUENCE -> the existing university, technical and teacher-education regulators continue",
            "OPEN -> name the failing link; BUILD -> entitlement, process and outcome separately",
            "CLOSE -> graded verdict with the survey round, scope and year attached",
        ], ["Credit portability and multiple entry and exit", "The higher-education regulatory position as of mid-2026", "Ministry ownership, measurement boundary and honest question ownership"]),
    ],
    [
        "RTE Act, 2009",
        "Article 21-A",
        "86th Amendment",
        "25%",
        "NEP 2020",
        "5+3+3+4",
        "Samagra Shiksha",
        "NIPUN Bharat",
        "foundational literacy and numeracy",
        "Grade 3",
        "2026-27",
        "Gross Enrolment Ratio",
        "28.4",
        "27.3",
        "23.4%",
        "ASER",
        "AISHE",
        "UDISE+",
        "DIKSHA",
        "SWAYAM",
        "NCVET",
        "NAPS",
        "NSQF",
        "Academic Bank of Credits",
        "learning poverty",
        "Viksit Bharat Shiksha Adhishthan Bill, 2025",
    ],
    "Six General Studies Mains demands and one objective demand are routed to this topic in the audited routing ledgers, and each Mains demand is reproduced below as a demand card with its printed year, paper, question number, directive, marks and word limit exactly as the ledgers record them: 2020 General Studies Paper I Question 20, 2020 General Studies Paper II Question 18, 2021 General Studies Paper II Question 7, 2022 General Studies Paper II Question 18, 2023 General Studies Paper II Question 6 and 2023 General Studies Paper II Question 18. The ledger records the 2023 skill-education and employment demand as one whose two subject routes terminate in answer-complete Core, shared with the Economy owner, and that shared ownership is stated openly rather than claimed exclusively. One objective demand is also routed, namely 2018 Prelims General Studies Paper I Question 21 on teacher-qualification eligibility provisions under the entitlement statute, and the ledger records the official 2018-2023 Prelims keys as not held locally, so no option, key or inferred answer is recorded for it and it is not converted into a solved question. The Basic owner separately discusses the 2024 public-examination-integrity Act, but the audited 2024-2025 Mains routing ledger routes that question to the Governance owner, so no demand card is manufactured for it here and no ownership is claimed over it. The locally held OCR-searchable official General Studies papers were read only to confirm the printed wording of the routed Mains demands; no question was invented from them and no marking scheme or page precision was imported. Every model solution below is original work written to the repository's examiner-grade standard using the claim, named evidence, analysis and qualification pattern.",
    [
        (
            "2020",
            "General Studies Paper I Question 20",
            "Digital initiatives and the functioning of the education system, asked with the instruction to elaborate your answer, 15 marks, 250 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: digital initiatives have changed the reach and the administration of Indian education far more than they have changed its conversion of schooling into learning. Named evidence and example: the national digital infrastructure for school content and teacher support and the national online-course platform for higher education; the five recorded access qualifications of devices, connectivity, language, disability and study space; the conversion chain from enrolment through attendance, transition, completion and competency to employment; and the 2024 round of the annual status of education report, a non-government rural household survey, recording 23.4 per cent of government-school Standard III children able to read a Standard II text. Analysis: a digital channel multiplies the supply of content and the visibility of administrative data, which is why school-data systems and teacher training scaled quickly, but competency is produced by instruction time, teacher capacity and feedback, so where a household lacks a device, a connection, instruction in a familiar language, accessible material or a quiet place to study, the channel widens rather than narrows the gap. Qualification: the survey value must be carried with its round, rural scope, school type and competency and must not be generalised to urban India, and no coverage, download or enrolment count is asserted for either platform because such counts are periodic dashboard outputs. Why this earns marks: it elaborates a conditional effect with named instruments, named constraints and dated evidence carrying its own scope limit.",
        ),
        (
            "2020",
            "General Studies Paper II Question 18",
            "National Education Policy 2020 and Sustainable Development Goal 4. Critically examine, 15 marks, 250 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: the policy is well aligned with the goal at the level of objectives and is under-specified at the level of delivery conditions, so the critical question is finance and teachers rather than intent. Named evidence and example: the fourth goal's commitment to inclusive and equitable quality education and lifelong learning for all; the policy's five plus three plus three plus four restructuring covering ages three to eight, eight to eleven, eleven to fourteen and fourteen to eighteen; its extension of focus to early childhood care and education, which remains policy and not statutory entitlement because Article 21-A is bounded to ages six to fourteen; the foundational-learning mission launched in 2021 with its Grade 3 target and recorded national target year of 2026-27; and the recorded dependency of delivery on finance, teacher supply and State capacity. Analysis: alignment is genuine because the policy adopts a learning outcome rather than an enrolment count as its object, and the mission is the first national instrument to do so, but a goal that is inclusive and equitable requires the two things the policy cannot itself supply, namely funded teacher posts and State implementation capacity, which is why an aligned policy can coexist with a persistent foundational deficit. Qualification: the policy is not a statute and must not be described as creating enforceable claims, and no expenditure share or teacher-vacancy figure is asserted here. Why this earns marks: it examines critically by conceding alignment, locating the real contest in delivery and keeping statutory and policy status apart.",
        ),
        (
            "2021",
            "General Studies Paper II Question 7",
            "Earn while you learn and meaningful vocational education and skilling. Comment, 10 marks, 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: earning while learning is a sound design whose value depends on four conditions that India has only partly met. Named evidence and example: the apprenticeship promotion scheme providing stipend support to employers hiring apprentices in order to bridge classroom training and workplace learning; the vocational education and training council as the unified regulator of skill qualifications, awarding bodies and assessment agencies under the skills ministry; the ten-level national skills qualification framework enabling recognition and mobility across formal and non-formal training; the policy proposal of vocational exposure from Grade 6 and internship or skill courses in higher education; and the recorded constraints of stigma, employer participation, career counselling and quality of matching. Analysis: the model works where the workplace supplies real tasks and the framework converts them into portable certification, so employer participation and recognition are the joints on which the whole design turns, while stigma and weak counselling determine who enters the stream at all, which is why supply-side training targets alone do not produce meaningful skilling. Qualification: no enrolment, placement or apprenticeship figure is asserted because those are periodic dashboard outputs, and the schooling-to-work claim must be located on the conversion chain rather than assumed. Why this earns marks: it comments with a stated design logic and four named constraints instead of endorsing the slogan.",
        ),
        (
            "2022",
            "General Studies Paper II Question 18",
            "Right to Education Act 2009 and awareness about schooling. Analyse, 15 marks, 250 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: awareness is not a soft supplement to the statutory right but the condition on which its enforceable parts actually operate. Named evidence and example: Article 21-A inserted by the Eighty-sixth Amendment of 2002 and the Right to Education Act, 2009 covering ages six to fourteen; the twenty-five per cent entry-level obligation in private unaided non-minority schools, with its recorded difficulties of delayed reimbursement to schools, documentation barriers for beneficiaries and uneven enforcement across States; the 2019 amendment restoring State discretion for regular examinations in Classes V and VIII with detention only after instruction and re-examination; and the umbrella school scheme through which infrastructure, teacher training and inclusive-education support are funded. Analysis: the parts of the Act that operate automatically, such as free schooling in the public system, do not depend on a household knowing the law, whereas the parts that require a claim, such as the private-school entry obligation, a grievance about denial or an objection to detention, are activated only by a household that knows the entitlement, holds the documents and can approach the authority, so low awareness converts a justiciable clause into a dormant one and produces the uneven access pattern the demand describes. Qualification: awareness alone cannot cure reimbursement delay or enforcement weakness, and no admission, awareness or grievance figure is asserted here. Why this earns marks: it analyses by separating self-executing from claim-dependent provisions and evidencing the difference.",
        ),
        (
            "2023",
            "General Studies Paper II Question 6",
            "Inadequate attention to Human Resource Development in India, asked with the instruction to suggest measures, 10 marks, 150 words, exactly as recorded in the audited 2018-2023 Mains routing ledger.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger, where the Core route is recorded as superseding the older Advanced ownership. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: attention has been adequate at the entitlement end and inadequate at the conversion end, so the measures must be attached to named links rather than to education in general. Named evidence and example: the conversion chain from enrolment through attendance, transition, completion and competency to higher education or skill and employment; the three measurement systems, namely the administrative school data system, the rural household learning survey and the higher-education survey, each of which observes a different link; the foundational-learning mission with its Grade 3 target and recorded national target year of 2026-27; the fourth goal's dependency on finance, teacher supply and State capacity; and the skills ecosystem of training, qualification regulation and apprenticeship. Analysis: the enrolment link is the best measured and the most nearly solved, competency is measured only by a rural sample survey and remains the weakest link, and the skill-to-employment joint is measured least well of all, so the measures that follow are a funded teacher and instructional-time guarantee at the foundational stage, competency reporting at the school level rather than only at the sample level, and employer-linked certification at the skilling end. Qualification: no expenditure, vacancy or placement figure is asserted, and each survey value used elsewhere is carried with its round and scope. Why this earns marks: it suggests measures that are link-specific and measurable rather than exhortations to invest more.",
        ),
        (
            "2023",
            "General Studies Paper II Question 18",
            "Skill development programmes and the linkages between skill education and employment, asked with the instruction to analyse the linkages, 15 marks, 250 words, exactly as recorded in the audited 2018-2023 Mains routing ledger, where both subject routes are recorded as terminating in answer-complete Core shared with the Economy owner.",
            "Routed to this owner in the audited 2018-2023 Mains routing ledger with shared subject routing recorded alongside the Economy owner, and that shared ownership is stated rather than claimed exclusively. No official answer key exists for a Mains demand and none is claimed.",
            "Claim: the linkage between skilling and employment is a chain with four breakable joints, and Indian policy has built the first two far more completely than the last two. Named evidence and example: the national skill mission for training delivery; the vocational education and training council as the unified regulator of skill qualifications, awarding bodies and assessment agencies under the skills ministry, replacing earlier fragmented regulators; the ten-level national skills qualification framework enabling recognition and mobility across formal and non-formal training; the apprenticeship promotion scheme providing stipend support to employers; the policy's vocational exposure from Grade 6 and higher-education internship requirement; and the recorded constraints of stigma, employer participation, counselling and matching. Analysis: joint one is training capacity and joint two is certification, both of which a regulator and a framework can deliver administratively, whereas joint three is employer recognition of that certificate and joint four is the matching of a certified trainee to an actual vacancy, and neither can be produced by regulation alone, which is why apprenticeship, employer participation in curriculum and counselling infrastructure are the decisive instruments; the demand is jointly owned with the Economy owner precisely because the fourth joint is a labour-demand question rather than an education question. Qualification: no training, certification or placement figure is asserted, and the analysis does not claim that certification causes employment where labour demand is absent. Why this earns marks: it analyses a linkage joint by joint, states what each instrument can and cannot do, and closes with an honest boundary between education and labour demand.",
        ),
    ],
    live_sources=[],
    current_note="No live official page was verified for this topic on 2026-09-02. Three official checks were attempted on that date and all three were refused with an access error, namely the education ministry's foundational-learning mission page, the department of school education page for the same mission and the national portal's education-policy spotlight page, so nothing was read or used from any of them and no secondary summary, coaching site or news report has been treated as an official source. The package therefore uses only the dated official anchors already carried by the repository owners with their status checks, and each is cited with its issuing instrument, edition or survey round: Article 21-A inserted by the Eighty-sixth Amendment of 2002 with the fundamental right bounded to ages six to fourteen; the Right of Children to Free and Compulsory Education Act, 2009 with its twenty-five per cent entry-level obligation in private unaided non-minority schools subject to the Act and judicial interpretation; the 2019 amendment restoring State discretion for regular examinations in Classes V and VIII with detention permitted only after instruction and a re-examination; the National Education Policy, 2020 as a policy document with its five plus three plus three plus four structure across ages three to eight, eight to eleven, eleven to fourteen and fourteen to eighteen; the umbrella school scheme merging elementary, secondary and teacher education; the foundational-learning mission launched in 2021 with its end-of-Grade-3 target and recorded national target year of 2026-27; the all-India higher-education survey for 2021-22 reporting a gross enrolment ratio of 28.4 for ages eighteen to twenty-three, up from 27.3 in 2020-21, with a female ratio of 28.5; the 2024 round of the non-government rural household learning survey recording 23.4 per cent of government-school Standard III children able to read a Standard II text, recorded by the owners as the latest national foundational-learning round of that survey as of July 2026; and the recorded regulatory status that the proposed single higher-education regulator remains unenacted as of mid-2026 while the existing university, technical-education and teacher-education regulators continue to function, with the relevant Bill recorded as Cabinet-approved in December 2025 and introduced in Parliament. Every one of those values is round-specific, survey-year-specific or status-specific and is cited with that status, and the package states expressly that the higher-education ratio must carry its survey year and that the household learning value must carry its round, rural scope, school type and competency and must not be generalised to urban India. No enrolment, dropout, teacher-vacancy, training, certification, apprenticeship or placement count is asserted, no budget or expenditure share is asserted, no Periodic Labour Force Survey, National Sample Survey, NITI Aayog or Sustainable Development Goal index figure is asserted, no scheme eligibility rule beyond the recorded statutory provisions is asserted, and no previous-year question, official answer key or option is asserted or inferred.",
)
