"""Focused tests for the Qualifying English subject-wide deep review."""

from __future__ import annotations

import inspect
import json
import re
import unittest
from pathlib import Path

import regenerate_qualifying_english_deep_review as deep


class QualifyingEnglishDeepReviewTests(unittest.TestCase):
    def test_authoritative_structure_is_subject_wide_and_exact(self) -> None:
        paths = deep.source_inventory()
        self.assertEqual(len(deep.EXPECTED_SOURCE_FILES), len(paths))
        self.assertEqual(7, len(list((deep.SOURCE_ROOT / "basic").glob("*.md"))))
        self.assertEqual(3, len(list((deep.SOURCE_ROOT / "practice").glob("*.md"))))
        self.assertEqual(
            3, len(list((deep.SOURCE_ROOT / "answer-keys").glob("*.md")))
        )
        self.assertEqual(
            "qualifying-language-subject-package-v1", deep.CONTRACT
        )

    def test_official_scope_and_threshold_discipline_are_explicit(self) -> None:
        text = "\n".join(
            (deep.SOURCE_ROOT / name).read_text(encoding="utf-8")
            for name in (
                "README.md",
                "00_Master-Framework.md",
                "OFFICIAL-UPSC-SYLLABUS-MAPPING.md",
            )
        ).casefold()
        for phrase in (
            "serious discursive prose",
            "matriculation or equivalent",
            "qualifying",
            "not counted for ranking",
            "comprehension of given passages",
            "precis writing",
            "usage and vocabulary",
            "short essays",
        ):
            self.assertIn(phrase, text)
        self.assertIn("do not rely on an unsourced", text)
        self.assertIn("non-official", text)

    def test_2019_ocr_anomaly_is_preserved_and_visually_reconciled(self) -> None:
        text = (deep.SOURCE_ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("Text extraction says **800**", text)
        self.assertIn("visual inspection of page 1 shows printed **300**", text)
        self.assertIn("100+75+75+25+25=300", text)

    def test_workbook_is_question_only_and_has_space_instructions(self) -> None:
        generator = __import__("generate_language_master_packages")
        generator.build_subject(
            deep.SUBJECT, generator.CONFIGS[deep.SUBJECT]
        )
        metrics = deep.validate_markdown()
        self.assertEqual(0, metrics["answer_leakage_matches"])
        self.assertEqual(3, metrics["practice_papers"])
        workbook = deep.package_sources()[1].read_text(encoding="utf-8")
        self.assertIn("at least six ruled A4 sides", workbook)
        self.assertEqual(2, workbook.count("at least fourteen A4 sides"))

    def test_solutions_have_eight_exam_length_models_and_matching_keys(self) -> None:
        generator = __import__("generate_language_master_packages")
        generator.build_subject(
            deep.SUBJECT, generator.CONFIGS[deep.SUBJECT]
        )
        metrics = deep.validate_markdown()
        self.assertEqual(3, metrics["matching_solution_keys"])
        self.assertEqual(8, len(metrics["full_essay_models"]))
        for count in metrics["full_essay_models"].values():
            self.assertGreaterEqual(count, 520)
            self.assertLessEqual(count, 680)
        coverage = metrics["solution_coverage"]
        for section in coverage["foundation"].values():
            self.assertEqual(section["questions"], section["answers"])
        for mock in coverage["mocks"].values():
            for key, value in mock.items():
                if key.endswith("_questions") and key != "precis_questions":
                    self.assertEqual(value, mock[key.replace("_questions", "_answers")])
            self.assertEqual(mock["essay_options"], mock["essay_models"])
            self.assertEqual(mock["precis_questions"], mock["precis_models"])

    def test_g2_record_and_pdfs_pass_when_generated(self) -> None:
        if not deep.G2_RECORD.is_file():
            self.skipTest("g2 is generated by the review driver")
        record = json.loads(deep.G2_RECORD.read_text(encoding="utf-8"))
        self.assertEqual(
            "qualifying-english-subject-master:learner-v2:g2",
            record["record_id"],
        )
        self.assertEqual(
            "qualifying-english-subject-master:learner-v2:g1",
            record["supersedes"],
        )
        self.assertFalse(record["approved"])
        for field in ("main_pdf", "workbook", "solutions_pdf"):
            path = deep.ROOT / record[field].replace("\\", "/")
            metrics = deep.pdf_metrics(path)
            self.assertGreater(metrics["bookmarks"], 0)
            self.assertEqual([], metrics["blank_pages"])
            self.assertEqual([], metrics["replacement_glyph_pages"])
            self.assertEqual([], metrics["raw_html_entity_pages"])

    def test_special_package_is_not_registered_as_a_gs_topic(self) -> None:
        self.assertEqual(
            {
                "EXPORT-PDF-STATUS.json": 0,
                "MASTER-TRACKER.json": 0,
                "REVIEW-TRACKER.json": 0,
            },
            deep.tracker_mentions(),
        )

    def test_driver_uses_direct_tests_and_nul_inventory(self) -> None:
        source = inspect.getsource(deep)
        self.assertIn(
            '[sys.executable, "-m", "unittest", "-v", module]',
            source,
        )
        self.assertIn('path.encode("utf-8") + b"\\0"', source)
        self.assertIn('payload.endswith(b"\\0")', source)
        self.assertNotIn("exec(compile(", source)
        self.assertNotIn("_prior_main", source)
        self.assertNotIn("def load_tests(", source)
        inventory_body = source[
            source.index("def write_inventory(") : source.index(
                "def main()", source.index("def write_inventory(")
            )
        ]
        self.assertNotIn("rglob(", inventory_body)


if __name__ == "__main__":
    unittest.main()
