"""Focused tests for the Qualifying Hindi subject-wide deep review."""

from __future__ import annotations

import inspect
import json
import unittest

import generate_language_master_packages as generator
import regenerate_qualifying_hindi_deep_review as deep


class QualifyingHindiDeepReviewTests(unittest.TestCase):
    def test_authoritative_structure_is_subject_wide_and_exact(self) -> None:
        paths = deep.source_inventory()
        self.assertEqual(len(deep.EXPECTED_SOURCE_FILES), len(paths))
        self.assertEqual(6, len(list((deep.SOURCE_ROOT / "basic").glob("*.md"))))
        self.assertEqual(3, len(list((deep.SOURCE_ROOT / "practice").glob("*.md"))))
        self.assertEqual(
            3, len(list((deep.SOURCE_ROOT / "answer-keys").glob("*.md")))
        )
        self.assertEqual("qualifying-language-subject-package-v1", deep.CONTRACT)

    def test_official_scope_and_threshold_discipline_are_explicit(self) -> None:
        text = "\n".join(
            (deep.SOURCE_ROOT / name).read_text(encoding="utf-8")
            for name in (
                "README.md",
                "00_Master-Framework.md",
                "OFFICIAL-UPSC-SYLLABUS-MAPPING.md",
            )
        ).casefold()
        for phrase in (
            "comprehension of given passages",
            "precis writing",
            "usage and vocabulary",
            "short essays",
            "translation english↔indian language",
            "मैट्रिक",
            "अर्हकारी",
            "मेरिट में नहीं",
        ):
            self.assertIn(phrase, text)
        self.assertIn("non-official", text)
        self.assertIn("official section-mark", text)

    def test_workbook_is_question_only_independent_and_space_controlled(self) -> None:
        generator.build_subject(deep.SUBJECT, generator.CONFIGS[deep.SUBJECT])
        metrics = deep.validate_markdown()
        self.assertEqual([], metrics["answer_leakage_matches"])
        self.assertEqual([], metrics["duplicate_prompts_or_passages"])
        self.assertEqual(3, metrics["practice_papers"])
        workbook = deep.package_sources()[1].read_text(encoding="utf-8")
        self.assertIn("Candidate record", workbook)
        self.assertIn("6 ruled A4 sides", workbook)
        self.assertEqual(2, workbook.count("14 ruled A4 sides"))

    def test_solutions_are_one_to_one_and_have_eight_full_models(self) -> None:
        generator.build_subject(deep.SUBJECT, generator.CONFIGS[deep.SUBJECT])
        metrics = deep.validate_markdown()
        self.assertEqual(3, metrics["matching_solution_keys"])
        self.assertEqual(8, len(metrics["full_essay_models"]))
        for count in metrics["full_essay_models"].values():
            self.assertGreaterEqual(count, 520)
            self.assertLessEqual(count, 680)
        self.assertEqual([362, 256], metrics["precis_source_counts"])
        self.assertEqual([122, 93], metrics["precis_model_counts"])
        coverage = metrics["solution_coverage"]
        for group in coverage["foundation"].values():
            self.assertEqual(group["questions"], group["answers"])
        for mock in coverage["mocks"].values():
            for question_key, answer_key in (
                ("essay_options", "essay_models"),
                ("comprehension_questions", "comprehension_answers"),
                ("precis_questions", "precis_models"),
                ("hindi_to_english_questions", "hindi_to_english_models"),
                ("english_to_hindi_questions", "english_to_hindi_models"),
                ("usage_items", "usage_answers"),
            ):
                self.assertEqual(mock[question_key], mock[answer_key])

    def test_g2_record_and_pdfs_pass_when_generated(self) -> None:
        if not deep.G2_RECORD.is_file():
            self.skipTest("g2 is generated by the review driver")
        record = json.loads(deep.G2_RECORD.read_text(encoding="utf-8"))
        self.assertEqual(
            "qualifying-hindi-subject-master:learner-v2:g2",
            record["record_id"],
        )
        self.assertEqual(
            "qualifying-hindi-subject-master:learner-v2:g1",
            record["supersedes"],
        )
        self.assertFalse(record["approved"])
        for field in ("main_pdf", "workbook", "solutions_pdf"):
            path = deep.ROOT / record[field].replace("\\", "/")
            metrics = deep.pdf_metrics(path, workbook=field == "workbook")
            self.assertGreater(metrics["bookmarks"], 0)
            self.assertEqual([], metrics["blank_pages"])
            self.assertEqual([], metrics["replacement_glyph_pages"])
            self.assertEqual([], metrics["raw_html_entity_pages"])
            self.assertTrue(metrics["page_number_footer"])

    def test_unicode_sources_are_normalized_and_clean(self) -> None:
        results = deep.unicode_audit(deep.source_inventory())
        self.assertTrue(results)
        for metrics in results.values():
            self.assertTrue(metrics["nfc"])
            self.assertEqual([], metrics["zero_width"])
            self.assertEqual(0, metrics["replacement_glyphs"])
            self.assertEqual([], metrics["raw_html_entities"])

    def test_special_package_is_not_registered_as_a_gs_topic(self) -> None:
        self.assertEqual(
            {
                "EXPORT-PDF-STATUS.json": 0,
                "MASTER-TRACKER.json": 0,
                "REVIEW-TRACKER.json": 0,
            },
            deep.tracker_mentions(),
        )

    def test_driver_uses_direct_tests_and_direct_nul_inventory(self) -> None:
        source = inspect.getsource(deep)
        self.assertIn(
            '[sys.executable, "-m", "unittest", "-v", module]',
            source,
        )
        self.assertIn('path.encode("utf-8") + b"\\0"', source)
        self.assertIn('payload.endswith(b"\\0")', source)
        self.assertNotIn("exec(compile(", source)
        self.assertNotIn("_prior_main", source)
        self.assertNotIn("def load_tests(", source)
        inventory_body = source[
            source.index("def write_inventory(") : source.index(
                "def main()", source.index("def write_inventory(")
            )
        ]
        self.assertNotIn("rglob(", inventory_body)


if __name__ == "__main__":
    unittest.main()
