"""Authored content data for World History learner-v2 Topics 06-10."""

from __future__ import annotations

import generate_world_history_common as common
from world_history_01_05_data import panel, plan


TOPIC_06 = common.topic(
    6,
    "Unification of Italy and Germany",
    "06_Unification-of-Italy-and-Germany",
    "06_Unification-of-Italy-and-Germany_Complete-Topic-Package.md",
    [
        ("Vienna's divided map, 1815", "The Vienna settlement left Italy divided under extensive Austrian control or influence and Germany inside a thirty-nine-state Confederation dominated by Austria."),
        ("Young Italy, 1831", "Giuseppe Mazzini founded Young Italy in 1831 and gave republican, unitary nationalism an organised ideological voice."),
        ("Failure of 1848", "The revolutions of 1848 put national unity on the agenda but failed, redirecting both movements from liberal idealism toward statecraft, diplomacy and war."),
        ("Piedmont-Sardinia as nucleus", "Piedmont-Sardinia, strengthened at Vienna by Genoa, became the functioning state nucleus of Italian unification."),
        ("Cavour and France, 1859", "Cavour used diplomacy and French military help in 1859 to defeat Austria and secure Lombardy for Piedmont-Sardinia."),
        ("Garibaldi and the Red Shirts, 1860", "Garibaldi's Red Shirts conquered Sicily and Naples in 1860, supplying the popular-military force that elite diplomacy alone lacked."),
        ("Kingdom of Italy, 1861", "The Kingdom of Italy was proclaimed in 1861 under Victor Emmanuel II, absorbing republican and popular gains into a monarchy."),
        ("Venetia, 1866", "Venetia joined Italy in 1866 after Austria's defeat by Prussia."),
        ("Rome, 1870", "Rome joined Italy in 1870 after French troops withdrew, completing territorial unification while leaving a long conflict with the papacy."),
        ("Italy's incomplete integration", "Political unification did not erase the north-south divide, the church-state conflict or the defeat of Mazzini's republican programme."),
        ("Bismarck becomes minister-president, 1862", "Otto von Bismarck became Prussia's minister-president in 1862 and used Realpolitik, practical state interest rather than abstract principle, to direct unification."),
        ("Danish War, 1864", "Prussia and Austria defeated Denmark in 1864 over Schleswig-Holstein, opening Bismarck's three-war sequence."),
        ("Seven Weeks' War, 1866", "Prussia defeated Austria in the Seven Weeks' War of 1866, excluded Austria from German affairs and established the North German Confederation."),
        ("Franco-German War, 1870-71", "War against France in 1870-71 rallied the south German states to Prussia and completed the military-diplomatic unification sequence."),
        ("German Empire, January 1871", "The German Empire was proclaimed at Versailles in January 1871 under William I of Prussia."),
        ("Small-German solution", "Austria's exclusion produced a small-German state dominated by Prussia rather than a union of all German-speaking lands."),
        ("German federal-authoritarian form", "The new Empire combined a parliament and federal institutions with Prussian dominance and monarchical control of the army and foreign policy."),
        ("Alsace-Lorraine consequence", "France's loss of Alsace-Lorraine in 1871 created revanchist grievance that later formed one source of friction before 1914."),
        ("Above and below compared", "Italian unification combined Mazzini's ideas, Garibaldi's mobilisation and Cavour's monarchy-led diplomacy; German unification was much more decisively state-led and military."),
        ("European balance transformed", "A unified Germany became the leading continental military-economic power, altering Europe's balance far more sharply than the creation of the weaker Italian state."),
    ],
    [
        "Do not date Rome's accession to 1861; Rome joined in 1870.",
        "Do not say Mazzini completed Italian unification.",
        "Do not omit Piedmont-Sardinia as Italy's state nucleus.",
        "Do not treat Garibaldi and Cavour as performing the same function.",
        "Do not describe Italian unification as purely republican.",
        "Do not say Austria led German unification.",
        "Do not say Germany was unified by popular assemblies alone.",
        "Do not confuse the Danish, Austro-Prussian and Franco-German wars.",
        "Do not quote Bismarck's blood-and-iron phrase without a verified text.",
        "Do not equate Realpolitik with absence of nationalism.",
        "Do not describe the German Empire as simply democratic or simply absolutist.",
        "Do not ignore minorities and regional incompleteness after proclamation.",
        "Do not claim Italy and Germany altered Europe to the same degree.",
        "Do not convert probable questions into claimed UPSC PYQs.",
    ],
    [
        (10, "Why was Piedmont-Sardinia decisive in Italian unification?", "It supplied the diplomatic, administrative and military state frame that converted Mazzini's legitimacy and Garibaldi's mobilisation into a recognised monarchy.", [1, 3, 4, 5, 6]),
        (10, "Explain the significance of the Seven Weeks' War for German unification.", "The 1866 victory excluded Austria, created the North German Confederation and settled the small-German, Prussian-led path.", [12, 15]),
        (15, "Compare the roles of Mazzini, Cavour and Garibaldi.", "Mazzini supplied republican-national legitimacy, Cavour supplied statecraft and alliance, and Garibaldi supplied popular military conquest; monarchy absorbed all three.", [1, 4, 5, 6]),
        (15, "German unification was a revolution from above. Discuss.", "Popular nationalism created legitimacy, but Prussian institutions, Bismarck's diplomacy and three wars determined timing, boundaries and the authoritarian form of unity.", [2, 10, 11, 12, 13, 14, 16]),
        (20, "Compare the unification of Italy and Germany.", "Both overturned Vienna through a strong core state and war against Austria, but Italy required a popular campaign and external ally while Germany concentrated power in Prussia.", [0, 3, 4, 5, 10, 12, 18, 19]),
        (20, "How did Italian and German unification transform the European balance of power?", "The settlements created nation-states but also minority, church and territorial grievances; Germany's strength and Alsace-Lorraine changed the continental balance most dramatically.", [9, 16, 17, 19]),
    ],
    [
        plan("Vienna's unresolved national map", [0], "Vienna created neither Italian nor German nation-states.", "Begin with dynastic fragmentation and Austrian influence."),
        plan("Mazzini and republican nationalism", [1], "Ideological authorship did not equal political completion.", "Use Mazzini as the source of legitimacy and programme."),
        plan("Why 1848 changed the method", [2], "Failure redirected nationalism; it did not extinguish it.", "Bridge liberal revolt to monarchy-led statecraft."),
        plan("Piedmont-Sardinia and Cavour", [3, 4], "French help mattered in Italy's 1859 breakthrough.", "Explain why a functioning core state was indispensable."),
        plan("Garibaldi's southern campaign", [5], "Popular conquest and elite diplomacy must remain distinct.", "Show the from-below component of Italian unity."),
        plan("The Italian kingdom and staggered completion", [6, 7, 8], "Kingdom, Venetia and Rome belong to 1861, 1866 and 1870.", "Build the exact territorial sequence."),
        plan("Limits of Italian unification", [9], "Political boundaries did not create social homogeneity.", "Extend the answer past proclamation."),
        plan("Bismarck and Realpolitik", [10], "Realpolitik means practical state interest, not ideological emptiness.", "Define the strategist's method without biography."),
        plan("The Danish opening, 1864", [11], "The first war opened the sequence but did not exclude Austria.", "Place Schleswig-Holstein inside the three-war logic."),
        plan("Austria excluded, 1866", [12, 15], "The small-German solution deliberately excluded Austria.", "Explain the decisive constitutional and power shift."),
        plan("France defeated and empire proclaimed", [13, 14], "War and proclamation belong to 1870-71 and January 1871.", "Show how external war rallied southern states."),
        plan("The new German state's political form", [16], "Federal institutions coexisted with Prussian-monarchical control.", "Avoid binary democratic-versus-autocratic labels."),
        plan("Alsace-Lorraine and the 1914 bridge", [17], "Later friction does not make 1914 mechanically inevitable.", "Link unification to French revanchism."),
        plan("Italy and Germany on common axes", [18], "Use agency, alliance, popular mobilisation and state power as common axes.", "Compare rather than narrate twice."),
        plan("European balance and qualified verdict", [19, 9, 16], "Unity was political before it was socially complete.", "Conclude with unequal power effects and incomplete integration."),
    ],
    [
        panel("Vienna's unfinished map", "root-axes", ["ITALY -> divided; Austria controls Lombardy-Venetia and influence", "GERMANY -> 39-state Confederation under Austrian influence", "1848 -> liberal-national attempts fail", "RESULT -> nationalism shifts toward states, diplomacy and war"], ["Vienna's unresolved national map", "Why 1848 changed the method"]),
        panel("Italian leadership chain", "path-consequence", ["MAZZINI -> Young Italy, 1831; republican legitimacy", "CAVOUR -> Piedmont diplomacy and French alliance", "GARIBALDI -> Red Shirts conquer Sicily and Naples", "VICTOR EMMANUEL II -> monarchy absorbs the national gain"], ["Mazzini and republican nationalism", "Piedmont-Sardinia and Cavour", "Garibaldi's southern campaign"]),
        panel("Italian territorial sequence", "timeline", ["1859 -> Austria defeated; Lombardy gained", "1860 -> Garibaldi takes Sicily and Naples", "1861 -> Kingdom of Italy proclaimed", "1866 -> Venetia; 1870 -> Rome"], ["The Italian kingdom and staggered completion"]),
        panel("Italy's incomplete unity", "comparison-table", ["NORTH-SOUTH -> political union without equal integration", "CHURCH-STATE -> Rome's accession leaves papal hostility", "REPUBLICANISM -> Mazzini's programme displaced by monarchy", "VERDICT -> a state was unified before a society"], ["Limits of Italian unification"]),
        panel("Bismarck's three-war sequence", "timeline", ["1864 -> Denmark defeated over Schleswig-Holstein", "1866 -> Austria defeated in Seven Weeks' War", "1870-71 -> France defeated; southern states rally", "JAN 1871 -> German Empire proclaimed at Versailles"], ["The Danish opening, 1864", "Austria excluded, 1866", "France defeated and empire proclaimed"]),
        panel("Realpolitik mechanism", "causal-system", ["GOAL -> Prussian-led German unity", "METHOD -> isolate one opponent at a time", "INSTRUMENT -> diplomacy backed by military force", "OUTCOME -> nationalism serves the Prussian state"], ["Bismarck and Realpolitik"]),
        panel("Small-German settlement", "comparison", ["INCLUDED -> Prussia and German states north and south", "EXCLUDED -> Austria after 1866", "FORM -> North German Confederation, then Empire", "POWER CENTRE -> Prussian monarchy and army"], ["Austria excluded, 1866", "The new German state's political form"]),
        panel("Italy versus Germany: agency", "comparison-table", ["ITALY -> ideology + diplomacy + volunteer campaign", "GERMANY -> bureaucracy + diplomacy + three wars", "ITALY -> French alliance crucial in 1859", "GERMANY -> Prussia isolates and defeats rivals"], ["Italy and Germany on common axes"]),
        panel("Italy versus Germany: outcome", "comparison-table", ["ITALY -> weaker state with regional and church divisions", "GERMANY -> strongest continental military-economic power", "ITALY -> staggered completion, 1861-70", "GERMANY -> concentrated completion, 1864-71"], ["European balance and qualified verdict"]),
        panel("Alsace-Lorraine consequence chain", "path-consequence", ["1871 -> France loses Alsace-Lorraine", "REVANCHISM -> territorial grievance persists", "GERMAN POWER -> continental balance shifts", "1914 LINK -> one source of tension, not a sole cause"], ["Alsace-Lorraine and the 1914 bridge"]),
        panel("Above and below matrix", "comparison", ["FROM BELOW -> Mazzini, 1848, Garibaldi, popular feeling", "FROM ABOVE -> Cavour, Victor Emmanuel II, Bismarck, Prussia", "ITALY -> both streams visibly combine", "GERMANY -> state power decisively dominates"], ["Italy and Germany on common axes"]),
        panel("Unification answer spine", "answer-spine", ["START -> Vienna fragmentation and failed 1848", "SEQUENCE -> core state + strategist + war + proclamation", "COMPARE -> agency, allies, popular force and state form", "QUALIFY -> minorities, regional divides and power imbalance"], ["European balance and qualified verdict"]),
    ],
    ["Mazzini", "Young Italy", "Cavour", "Garibaldi", "Red Shirts", "Victor Emmanuel II", "Piedmont-Sardinia", "Venetia", "Rome", "Bismarck", "Realpolitik", "Seven Weeks' War", "North German Confederation", "Versailles", "Alsace-Lorraine"],
    "No direct UPSC PYQ is verified as owned solely by this topic in the local 2018-2025 routing blocks. Probable comparison questions remain original practice.",
    [],
    extra=["basic/05_Congress-of-Vienna-and-Concert-of-Europe.md", "basic/09_World-in-1914-and-Outbreak-of-WWI.md"],
)


TOPIC_07 = common.topic(
    7,
    "New Imperialism and Scramble for Africa",
    "07_New-Imperialism-and-Scramble-for-Africa",
    "07_New-Imperialism-and-Scramble-for-Africa_Complete-Topic-Package.md",
    [
        ("New Imperialism", "New Imperialism was the late-nineteenth-century shift from limited coastal influence toward aggressive direct political control of inland territory by industrial powers."),
        ("Ten to ninety per cent transformation", "Britannica's figures place about ten per cent of African territory under European control in the 1870s and about ninety per cent by 1914."),
        ("Suez Canal, 1869", "The Suez Canal opened in 1869 and increased the strategic value of Egypt, African routes and access to Asia."),
        ("British occupation of Egypt, 1882", "Britain occupied Egypt in 1882, showing how financial and strategic entanglement could become direct imperial control."),
        ("Economic driver", "Industrial powers sought raw materials, markets and investment opportunities, while actual metropolitan profit remained uneven and concentrated."),
        ("Prestige and rivalry", "National prestige and great-power rivalry accelerated the scramble, especially as recently unified Germany and Italy sought colonial status."),
        ("Technology as permissive cause", "Steam transport, improved weapons and medicines increased European reach; technology supplied capability, not motive."),
        ("Civilising mission and racial ideology", "Civilising rhetoric and racial superiority supplied domestic legitimation while coexisting with coercion, extraction and atrocity."),
        ("Berlin Conference, 1884-85", "The Berlin Conference met from 15 November 1884 to 26 February 1885 with representatives of fourteen countries."),
        ("Effective occupation", "The Berlin General Act required effective occupation for recognition, standardising the rules of competition rather than drawing every African border at one meeting."),
        ("Congo Free State and Leopold II", "The Conference recognised the Congo Free State under Leopold II, illustrating the overlap of private profit, sovereignty and imperial violence."),
        ("Partition pattern", "Britain, France, Belgium, Germany, Portugal and Italy acquired major African zones through conquest and negotiated delimitation after Berlin."),
        ("Ethiopia and Liberia in 1914", "By 1914 Ethiopia and Liberia remained independent while most of Africa had been partitioned."),
        ("Adwa, 1896", "Ethiopia defeated Italy at Adwa in 1896, proving that European conquest was contingent rather than automatic."),
        ("Zulu and Samori Ture resistance", "Zulu resistance and Samori Ture's prolonged West African campaigns demonstrate organised African military agency."),
        ("Herero and Nama genocide, 1904-08", "German suppression in South West Africa became the genocide of the Herero and Nama between 1904 and 1908."),
        ("Maji Maji, 1905-07", "The Maji Maji uprising in German East Africa from 1905 to 1907 showed mass resistance continuing after formal conquest."),
        ("Extraction and labour restructuring", "Cash taxation, mines, plantations and labour obligations reorganised economies for export and altered migration, households and gendered work."),
        ("Colonial borders and authority", "Boundaries rarely followed existing political realities, while colonial administrations hardened identities and reshaped authority through selected chiefs and intermediaries."),
        ("African agency and the Berlin verdict", "African societies resisted, negotiated, collaborated and adapted; Berlin was a legitimising rulebook and accelerator, not a complete cartographic act."),
    ],
    [
        "Do not say the Berlin Conference drew every African border in one sitting.",
        "Do not describe Africans as passive recipients of conquest.",
        "Do not explain imperialism through one economic cause alone.",
        "Do not treat technology as an intention.",
        "Do not present the civilising mission as purely humanitarian.",
        "Do not claim all colonies were equally profitable.",
        "Do not omit strategic control of Suez and Egypt.",
        "Do not confuse the Congo Free State with a humanitarian project.",
        "Do not generalise genocide terminology to every case of colonial violence.",
        "Do not give unsourced casualty figures for resistance.",
        "Do not treat collaboration as a simple moral category.",
        "Do not claim arbitrary borders mechanically caused every later conflict.",
        "Do not infer African consent from administrative intermediaries.",
        "Do not convert probable questions into claimed UPSC PYQs.",
    ],
    [
        (10, "What made late-nineteenth-century imperialism new?", "Its speed, inland territorial reach, industrial-strategic drivers and formal rules of effective occupation distinguished it from earlier coastal influence.", [0, 1, 4, 9]),
        (10, "How far was the Berlin Conference responsible for partition?", "Berlin legitimised claims and standardised effective occupation, accelerating conquest, but actual borders emerged through later force and bargaining.", [8, 9, 10, 19]),
        (15, "Explain the causes of the Scramble for Africa.", "Industrial demand and strategy supplied structural incentives, prestige set the pace, technology enabled conquest and racial ideology legitimised it.", [2, 3, 4, 5, 6, 7]),
        (15, "Assess African agency during the Scramble.", "African states and communities resisted, negotiated and adapted under unequal conditions; Adwa proves contingency while later revolts show conquest never ended opposition.", [13, 14, 16, 19]),
        (20, "Analyse the social and economic consequences of New Imperialism in Africa.", "Extraction, migrant labour, gendered household change, remade authority, hardened identities and imposed borders outlasted colonial rule.", [15, 16, 17, 18]),
        (20, "The civilising mission concealed a coercive political economy. Critically examine.", "Ideology performed real legitimising work, but Congo, forced labour, Herero-Nama genocide and Maji Maji expose the extraction and violence beneath it.", [7, 10, 15, 16, 17]),
    ],
    [
        plan("Defining New Imperialism", [0, 1], "Use the ten-to-ninety figures only with their stated periods.", "Establish direct inland rule and exceptional speed."),
        plan("Suez, Egypt and strategic empire", [2, 3], "Strategy and finance interacted; neither alone is sufficient.", "Show why routes shaped territorial priorities."),
        plan("Industrial capitalism and colonial demand", [4], "Not every colony yielded equal metropolitan profit.", "Treat economics as central but not exclusive."),
        plan("Prestige, rivalry and the timing of the rush", [5], "Prestige explains pace better than economic restructuring.", "Link new nation-states to status competition."),
        plan("Technology and ideology", [6, 7], "Capability and legitimation are different causal roles.", "Separate means of conquest from moral permission."),
        plan("Berlin's conference facts", [8], "Retain exact dates and fourteen participating countries.", "Fix chronology before interpretation."),
        plan("Effective occupation and what Berlin did", [9], "Berlin made rules; conquest and delimitation followed.", "Answer how-far questions through rule versus cartography."),
        plan("Congo and partition patterns", [10, 11], "Private and state interests overlapped without forming one uniform model.", "Illustrate different mechanisms of control."),
        plan("The partition endpoint in 1914", [12], "Ethiopia and Liberia were the independent exceptions.", "Use the endpoint to prove the scramble's scale."),
        plan("Adwa and successful resistance", [13], "Adwa was exceptional but disproves inevitability.", "Use contingency and leadership rather than technological determinism."),
        plan("Organised African resistance", [14], "Different African polities resisted for different reasons.", "Restore African political and military agency."),
        plan("Herero-Nama and Maji Maji", [15, 16], "Keep genocide and mass uprising categories precise.", "Show violence and resistance after conquest."),
        plan("Extraction, labour and gender", [17], "Use qualitative effects; no unsupported figures.", "Move from resources to household and migration change."),
        plan("Borders, chiefs and administrative identity", [18], "Avoid deterministic claims about every post-colonial conflict.", "Explain how rule remade territory and authority."),
        plan("Agency and the qualified imperialism verdict", [19, 4, 7], "Imperial imposition and African action must appear together.", "Conclude with multi-causality, coercion and agency."),
    ],
    [
        panel("What made imperialism new", "comparison", ["EARLIER -> coastal forts, trade influence and limited enclaves", "NEW -> direct inland territorial rule by industrial powers", "1870s -> about 10% of Africa under European control", "1914 -> about 90% under European control"], ["Defining New Imperialism"]),
        panel("Five-driver system", "causal-system", ["ECONOMY -> raw materials, markets and investment", "STRATEGY -> Suez, sea routes and rival positions", "PRESTIGE -> colonies become great-power status symbols", "TECHNOLOGY + IDEOLOGY -> capability plus permission"], ["Suez, Egypt and strategic empire", "Industrial capitalism and colonial demand", "Prestige, rivalry and the timing of the rush", "Technology and ideology"]),
        panel("Berlin: facts and function", "timeline", ["15 NOV 1884 -> conference opens", "14 COUNTRIES -> European and other powers represented", "26 FEB 1885 -> conference closes", "GENERAL ACT -> effective occupation becomes recognition rule"], ["Berlin's conference facts", "Effective occupation and what Berlin did"]),
        panel("Berlin did and did not", "comparison", ["DID -> standardise claims and legitimate competition", "DID -> recognise Congo Free State under Leopold II", "DID NOT -> include African voices in rule-making", "DID NOT -> draw every later border at one meeting"], ["Effective occupation and what Berlin did", "Congo and partition patterns"]),
        panel("Partition pattern", "comparison-table", ["BRITAIN/FRANCE -> largest strategic and territorial zones", "BELGIUM -> Congo; PORTUGAL -> Angola and Mozambique", "GERMANY -> east, south-west, Togo and Cameroon", "ITALY -> Eritrea and Somalia; defeated in Ethiopia"], ["Congo and partition patterns"]),
        panel("African resistance spectrum", "hierarchy", ["ADWA 1896 -> Ethiopia defeats Italy", "ZULU + SAMORI TURE -> organised prolonged resistance", "MAJI MAJI 1905-07 -> mass revolt under colonial rule", "NEGOTIATION/ADAPTATION -> constrained agency beyond war"], ["Adwa and successful resistance", "Organised African resistance", "Herero-Nama and Maji Maji"]),
        panel("Colonial violence ledger", "comparison-table", ["CONGO -> private-imperial extraction and coercion", "HERERO AND NAMA 1904-08 -> genocide", "MAJI MAJI 1905-07 -> mass uprising and repression", "VERDICT -> civilising rhetoric tested against conduct"], ["Congo and partition patterns", "Herero-Nama and Maji Maji"]),
        panel("Extraction mechanism", "path-consequence", ["CASH TAX -> households need colonial currency", "MINES/PLANTATIONS -> migrant and coerced labour expands", "EXPORT INFRASTRUCTURE -> production points toward ports", "RESULT -> commodity dependence and household disruption"], ["Extraction, labour and gender"]),
        panel("Authority and identity remade", "causal-system", ["THIN COLONIAL STATE -> relies on chiefs and intermediaries", "ADMINISTRATIVE CATEGORIES -> fluid identities become fixed", "LAW AND SCHOOLING -> new routes to status and exclusion", "LEGACY -> political identities carry colonial institutional marks"], ["Borders, chiefs and administrative identity"]),
        panel("Border legacy without determinism", "argument-tree", ["LINES -> rarely match prior political realities", "SUCCESSOR STATES -> inherit colonial territorial units", "PRESERVATION -> reopening one frontier threatens all", "CAUTION -> borders condition conflict; they do not mechanically cause it"], ["Borders, chiefs and administrative identity"]),
        panel("African agency correction", "comparison", ["WRONG FRAME -> Europe acts; Africa receives", "BETTER FRAME -> imposition meets resistance and negotiation", "UNEQUAL POWER -> weapons and logistics constrain choices", "OUTCOME -> colonial rule is shaped by African responses"], ["Agency and the qualified imperialism verdict"]),
        panel("Imperialism answer spine", "answer-spine", ["DEFINE -> direct territorial New Imperialism", "CAUSE -> economy + strategy + prestige + technology + ideology", "MECHANISM -> Berlin rules, conquest and administrative control", "VERDICT -> extraction and borders plus persistent African agency"], ["Agency and the qualified imperialism verdict"]),
    ],
    ["New Imperialism", "Scramble for Africa", "Suez Canal", "Berlin Conference", "effective occupation", "Leopold II", "Congo Free State", "Ethiopia", "Liberia", "Adwa", "Samori Ture", "Herero and Nama", "Maji Maji", "civilising mission", "colonial borders"],
    "No direct UPSC PYQ is verified as owned solely by this topic in the local 2018-2025 routing blocks. Owner probable questions remain original practice.",
    [],
    live_sources=[
        "https://au.int/en/pressreleases/20260525/au-leaders-issue-joint-africa-day-call-unity-reform-and-renewed-commitment"
    ],
    current_note=(
        "The official African Union Africa Day 2026 release marks 63 years "
        "since the founding of the Organization of African Unity. It records "
        "AU leaders' calls for accelerated integration and global governance "
        "reform and explicitly references reparatory justice and the enduring "
        "legacy of slavery and colonialism. This supplies a narrow current "
        "link to the continuing legacy of imperialism and decolonisation; the "
        "page does not directly discuss the Berlin Conference or the Scramble "
        "for Africa."
    ),
    extra=["basic/04_Industrial-Revolution.md", "basic/18_Decolonization-of-Africa-and-Asia.md"],
)


TOPIC_08 = common.topic(
    8,
    "Latin American Independence Movements",
    "08_Latin-American-Independence-Movements",
    "08_Latin-American-Independence-Movements_Complete-Topic-Package.md",
    [
        ("Colonial social hierarchy", "Peninsulares monopolised top offices, creoles possessed wealth but faced political restriction, and mestizos, Indigenous peoples and enslaved Africans remained subordinate."),
        ("Trade restrictions and ideas", "Colonial monopoly bred economic resentment while Enlightenment, American, French and Haitian examples widened the imaginable alternatives."),
        ("Haitian Revolution begins, 1791", "The Haitian Revolution began in 1791 as an anti-colonial and anti-slavery social revolution."),
        ("Haiti independent, 1804", "Haiti became independent in 1804 as the first free Black republic of the modern era and the region's most socially radical revolution."),
        ("Iberian crisis, 1808", "Napoleon invaded Spain in 1808 while the Portuguese court shifted to Brazil, destabilising metropolitan legitimacy and encouraging colonial juntas."),
        ("Mexico's Grito, 1810", "Hidalgo issued the Grito de Dolores in 1810, beginning a popular Mexican phase later continued by Morelos and converted into a conservative settlement under Iturbide."),
        ("San Martin crosses the Andes, 1817", "Jose de San Martin crossed the Andes into Chile in 1817, making Argentina, Chile and Peru the southern liberation theatre."),
        ("Bolivar and Gran Colombia, 1819", "Simon Bolivar secured New Granada in 1819 and built Gran Colombia as the political-military centre of northern liberation."),
        ("Mexico independent, 1821", "Mexico became independent in 1821 after a movement that began as popular revolt ended under a conservative former royalist officer."),
        ("Brazil under Pedro I, 1822", "Brazil became independent under Pedro I in 1822 through a monarchical path distinct from Spanish-American republican wars."),
        ("Ayacucho, 1824", "The victory at Ayacucho in 1824 broke major Spanish royalist power in South America."),
        ("Bolivia, 1825", "Bolivia emerged as an independent state in 1825, symbolically completing Bolivar's northern campaign."),
        ("Five distinct paths", "Northern South America, southern South America, Mexico, Brazil and Haiti followed five distinct political and social routes."),
        ("Creole elite transfer", "Across much of mainland Latin America, independence displaced peninsular officials while confirming creole landholding and political dominance."),
        ("Haiti as control case", "Haiti shows the different outcome produced when enslaved people rather than creole elites led independence: emancipation and political rupture occurred together."),
        ("Gran Colombia and fragmentation", "Bolivar's continental project did not endure as geography, regional elite interests and weak communications fragmented larger unions."),
        ("Caudillismo", "Caudillismo described personalist strongman rule resting on military reputation, armed clientage and weak institutions after prolonged wars of liberation."),
        ("Political independence without equality", "Imperial sovereignty ended, but land concentration, racial hierarchy and unequal citizenship survived in many new states."),
        ("Comparison with later decolonisation", "Latin American independence was often creole-led settler-descended secession, unlike many later Asian and African mass nationalist transfers."),
        ("States before nations", "Independence created states and armies before stable institutions and shared national political communities, contributing to oligarchy and recurring coups."),
    ],
    [
        "Do not date Haitian independence to 1791; the revolution began then.",
        "Do not treat all Latin American movements as identical republics.",
        "Do not present Bolivar and San Martin as operating identically.",
        "Do not omit Mexico's popular-to-conservative reversal.",
        "Do not say Brazil followed the Spanish-American republican path.",
        "Do not claim independence abolished slavery across the region.",
        "Do not describe Haiti as a minor side story.",
        "Do not claim Bolivar permanently united Spanish America.",
        "Do not reduce post-independence instability to culture.",
        "Do not name individual caudillos not sourced by the owners.",
        "Do not describe the five paths as four or six.",
        "Do not claim political independence produced immediate equality.",
        "Do not flatten Latin American and later Afro-Asian decolonisation.",
        "Do not convert probable questions into claimed UPSC PYQs.",
    ],
    [
        (10, "Why was the Iberian crisis of 1808 decisive?", "It broke metropolitan legitimacy and opened space for juntas, allowing long-standing creole, trade and ideological grievances to become independence movements.", [0, 1, 4]),
        (10, "Why is Haiti central to Latin American independence history?", "Haiti fused anti-colonial independence with anti-slavery social revolution, revealing the social limits of creole-led mainland movements.", [2, 3, 14]),
        (15, "Compare Bolivar and San Martin.", "They were complementary liberators in different theatres: Bolivar combined army and continental political project in the north, while San Martin advanced regular armies from the south.", [6, 7, 10, 11, 15]),
        (15, "Why did political independence not produce social equality?", "The creole class that led most movements benefited from existing land and racial hierarchies, so sovereignty changed faster than social power.", [0, 13, 17]),
        (20, "Explain the causes, course and varied paths of Latin American independence.", "Colonial hierarchy and trade restriction met the 1808 imperial collapse, but Haiti, Mexico, Brazil and the two South American theatres produced distinct outcomes.", [0, 1, 4, 5, 6, 7, 9, 12]),
        (20, "Assess the post-independence problems of Latin American state-building.", "War-made military authority, creole oligarchy, regional fragmentation and weak institutions created states before nations and encouraged caudillismo.", [13, 15, 16, 17, 19]),
    ],
    [
        plan("Colonial hierarchy and economic grievance", [0, 1], "Creoles opposed exclusion while benefiting from hierarchy.", "Begin with who led, who fought and who retained power."),
        plan("Haiti's anti-slavery revolution", [2, 3], "Separate the revolution's 1791 start from 1804 independence.", "Use Haiti as the social-revolution control case."),
        plan("The Iberian legitimacy collapse", [4], "The external crisis opened the door; it did not create every grievance.", "Explain why independence accelerated after 1808."),
        plan("Mexico's reversed revolutionary path", [5, 8], "Popular revolt and conservative independence belong to one changing sequence.", "Show how leadership and social content shifted."),
        plan("San Martin's southern theatre", [6], "Do not merge his route with Bolivar's northern campaign.", "Fix Argentina-Chile-Peru geography."),
        plan("Bolivar and northern liberation", [7, 11], "Continental ambition did not ensure durable federation.", "Connect military liberation to political project."),
        plan("Brazil's monarchical separation", [9], "Brazil was neither Haitian social revolution nor Spanish-American republic.", "Use Brazil to disprove a single regional model."),
        plan("Ayacucho and the military collapse of Spanish rule", [10], "Ayacucho belongs to 1824, not the beginning of revolt.", "Close the main South American military sequence."),
        plan("The five-path comparison", [12], "Count exactly five paths and compare their social character.", "Organise diversity before evaluation."),
        plan("Creole leadership and elite transfer", [13], "Political decolonisation can coexist with social continuity.", "Explain why office changed faster than land and status."),
        plan("Haiti versus mainland outcomes", [14], "Do not treat Haiti's radicalism as representative of all cases.", "Use leadership composition to explain social depth."),
        plan("Gran Colombia and failed continental unity", [15], "Failure reflects institutions, geography and regional interests.", "Move from liberation to fragmentation."),
        plan("Caudillismo's institutional mechanism", [16], "Name the category without inventing individual biographies.", "Trace war authority becoming personal rule."),
        plan("Independence, hierarchy and later decolonisation", [17, 18], "Comparison requires different colonial types and social bases.", "Distinguish sovereignty transfer from social transformation."),
        plan("States before nations: final verdict", [19, 13, 16], "Avoid cultural explanations for structural state weakness.", "Conclude with oligarchy, armies and fragile institutions."),
    ],
    [
        panel("Colonial hierarchy", "hierarchy", ["PENINSULARES -> top imperial offices", "CREOLES -> wealth without equal political access", "MESTIZOS/INDIGENOUS/ENSLAVED -> subordinate mass base", "CONFLICT -> elite grievance rests on unequal society"], ["Colonial hierarchy and economic grievance"]),
        panel("Ideas meet imperial collapse", "causal-system", ["TRADE MONOPOLY -> economic resentment", "ATLANTIC REVOLUTIONS -> alternative political vocabulary", "1808 NAPOLEONIC SHOCK -> metropolitan legitimacy collapses", "JUNTAS -> autonomy claims move toward independence"], ["Colonial hierarchy and economic grievance", "The Iberian legitimacy collapse"]),
        panel("Haiti's distinct sequence", "timeline", ["1791 -> slave revolution begins", "ANTI-COLONIAL + ANTI-SLAVERY -> one social struggle", "1804 -> independent Haiti", "RESULT -> first free Black republic of modern era"], ["Haiti's anti-slavery revolution"]),
        panel("Northern and southern liberators", "comparison", ["BOLIVAR -> New Granada 1819; Gran Colombia; northern project", "SAN MARTIN -> Andes crossing 1817; Chile and Peru", "MEETING POINT -> royalist power broken in Peru", "DIFFERENCE -> continental political project versus southern army route"], ["San Martin's southern theatre", "Bolivar and northern liberation"]),
        panel("Mexico's reversal", "path-consequence", ["1810 -> Hidalgo's Grito de Dolores", "POPULAR PHASE -> Indigenous and lower-class mobilisation", "MORELOS -> struggle continues", "1821 -> conservative settlement under Iturbide"], ["Mexico's reversed revolutionary path"]),
        panel("Brazil's separate route", "comparison", ["1808 -> Portuguese court moves to Brazil", "1822 -> independence under Pedro I", "FORM -> monarchy, not a new republic", "LIMIT -> slavery and hierarchy survive"], ["Brazil's monarchical separation"]),
        panel("Five paths, one region", "comparison-table", ["NORTH -> Bolivar and Gran Colombia", "SOUTH -> San Martin, Andes and Peru", "MEXICO -> popular revolt to conservative settlement", "BRAZIL + HAITI -> monarchy versus social revolution"], ["The five-path comparison"]),
        panel("Military completion sequence", "timeline", ["1819 -> New Granada and Gran Colombia", "1821 -> Mexican independence", "1824 -> Ayacucho breaks major royalist power", "1825 -> Bolivia emerges"], ["Bolivar and northern liberation", "Ayacucho and the military collapse of Spanish rule"]),
        panel("Elite transfer mechanism", "causal-system", ["PENINSULAR OFFICIAL -> displaced", "CREOLE LANDOWNER -> becomes ruling elite", "SOCIAL HIERARCHY -> land and racial power remain", "VERDICT -> sovereignty changes faster than society"], ["Creole leadership and elite transfer"]),
        panel("Caudillismo mechanism", "path-consequence", ["LONG WAR -> military commanders gain legitimacy", "WEAK INSTITUTIONS -> civilian authority remains fragile", "ARMED CLIENTAGE -> personal loyalty substitutes for law", "CAUDILLISMO -> strongman politics recurs"], ["Caudillismo's institutional mechanism"]),
        panel("Fragmentation after liberation", "causal-system", ["GRAN COLOMBIA -> continental federation attempted", "DISTANCE + WEAK COMMUNICATION -> administration fragments", "REGIONAL ELITES -> resist central authority", "RESULT -> states emerge before shared nations"], ["Gran Colombia and failed continental unity", "States before nations: final verdict"]),
        panel("Latin America answer spine", "answer-spine", ["CAUSE -> hierarchy + trade restriction + Atlantic ideas", "TRIGGER -> Iberian collapse in 1808", "COURSE -> five distinct regional paths", "VERDICT -> independence without equal social transformation"], ["States before nations: final verdict"]),
    ],
    ["peninsulares", "creoles", "Haitian Revolution", "Haiti", "Grito de Dolores", "Hidalgo", "Simon Bolivar", "Gran Colombia", "Jose de San Martin", "Pedro I", "Ayacucho", "Bolivia", "caudillismo", "political independence", "social hierarchy"],
    "No direct UPSC PYQ is verified as owned solely by this topic in the local 2018-2025 routing blocks. Probable questions remain original practice.",
    [],
    live_sources=[
        "https://usoas.usmission.gov/u-s-addresses-commemoration-of-bicentennial-of-the-amphictyonic-congress-of-panama/"
    ],
    current_note=(
        "The official U.S. Mission to the Organization of American States "
        "page commemorates in 2026 the bicentennial of the 1826 Amphictyonic "
        "Congress of Panama. This bounded linkage renews attention to "
        "Bolivar's post-independence regional cooperation project; no "
        "decorative event detail or broader present-day claim is imported."
    ),
    extra=["basic/02_American-Revolution.md", "basic/03_French-Revolution-and-Napoleon.md", "basic/18_Decolonization-of-Africa-and-Asia.md"],
)


TOPIC_09 = common.topic(
    9,
    "World in 1914 and Outbreak of WWI",
    "09_World-in-1914-and-Outbreak-of-WWI",
    "09_World-in-1914-and-Outbreak-of-WWI_Complete-Topic-Package.md",
    [
        ("Triple Alliance, 1882", "The Triple Alliance of 1882 joined Germany, Austria-Hungary and Italy, though Italy did not fight with them at the war's opening and entered on the Allied side in 1915."),
        ("Franco-Russian alliance, 1894", "The 1894 Franco-Russian alliance helped organise Europe into counterweighted blocs and intensified German fear of encirclement."),
        ("Entente Cordiale, 1904", "Britain and France reached the Entente Cordiale in 1904, resolving colonial disputes and enabling closer strategic cooperation."),
        ("Anglo-Russian agreement, 1907", "The 1907 British-Russian agreement completed the alignment commonly called the Triple Entente of Britain, France and Russia."),
        ("Anglo-German naval rivalry", "Germany's naval rise directly challenged Britain's relative sea power and strategic security more than colonial rivalry alone did."),
        ("Alsace-Lorraine and revanchism", "French resentment over Alsace-Lorraine, lost in 1871, remained a national-territorial source of tension."),
        ("Bosnia Crisis, 1908", "Austria-Hungary annexed Bosnia in 1908, deepening Serbian hostility and convincing Russia not to accept another humiliating retreat."),
        ("Agadir Crisis, 1911", "The Agadir Crisis of 1911 strengthened British support for France and deepened German mistrust."),
        ("Balkan Wars, 1912-13", "The Balkan Wars strengthened Serbia and alarmed Austria-Hungary, which saw South Slav nationalism as a threat to imperial survival."),
        ("Sarajevo, 28 June 1914", "Gavrilo Princip assassinated Archduke Franz Ferdinand at Sarajevo on 28 June 1914; the assassination was the trigger, not the complete cause."),
        ("Austria declares war, 28 July 1914", "Austria-Hungary used the assassination and ultimatum crisis to declare war on Serbia on 28 July 1914."),
        ("German blank cheque", "German backing enabled Austria-Hungary's hard line and is central to arguments assigning heavy responsibility to Berlin and Vienna."),
        ("Russian mobilisation", "Russian mobilisation for Serbia transformed the Austro-Serb conflict into a direct great-power confrontation and compressed German decision time."),
        ("Germany declares war, 1 and 3 August", "Germany declared war on Russia on 1 August and France on 3 August 1914."),
        ("Belgium and British entry, 4 August", "German mobilisation planning required an attack through Belgium, and violation of Belgian neutrality brought Britain into war on 4 August 1914."),
        ("Balkan nationalism", "Serbian and South Slav nationalism aimed at political unification while Austria-Hungary fought to preserve a multinational empire."),
        ("Balance-of-power structure", "Alliance blocs, encirclement fears, naval ratios and Balkan shifts made local conflict a test of great-power standing."),
        ("Mobilisation rigidity and miscalculation", "Military timetables shortened diplomacy while leaders misjudged Russian, British and German responses; likelihood increased without making war inevitable."),
        ("Responsibility at two levels", "Immediate responsibility centres on Vienna's decision for war and Berlin's support, while systemic responsibility lies in militarised blocs, nationalism and prestige politics."),
        ("Balance-of-power verdict", "Balance of power explains the structure and Britain's strategic concern, but not the full motives: Habsburg survival, South Slav nationalism, revanchism and preventive calculation also mattered."),
    ],
    [
        "Do not treat Sarajevo as the complete cause of war.",
        "Do not say alliances mechanically obliged every member to fight.",
        "Do not say Italy fought with the Triple Alliance from August 1914.",
        "Do not reduce Anglo-German tension to colonies alone.",
        "Do not omit Serbian nationalism and Habsburg survival.",
        "Do not describe Britain as bound by a formal alliance to France.",
        "Do not present the Schlieffen Plan as an uncontested fixed blueprint.",
        "Do not say balance of power explains every belligerent motive.",
        "Do not confuse the Bosnia, Agadir and Balkan crises.",
        "Do not claim war was inevitable.",
        "Do not assign responsibility only to the abstract system.",
        "Do not assign responsibility only to one state in one sentence.",
        "Do not invent arms, casualty or dreadnought figures.",
        "Do not quote historians beyond owner-verified positions.",
    ],
    [
        (10, "Why did the Balkans become the ignition zone of the First World War?", "Serbian national expansion threatened Habsburg imperial survival while Russia and Germany converted the regional dispute into a great-power test.", [6, 8, 15, 16]),
        (10, "How did mobilisation planning widen the July Crisis?", "Russian mobilisation and German planning through Belgium compressed diplomacy and drew France and Britain into a local Austro-Serb war.", [12, 13, 14, 17]),
        (15, "How far did alliances cause the First World War?", "Alliances structured escalation and encirclement fears but did not compel war; specific July decisions, nationalism and imperial insecurity remained decisive.", [0, 1, 2, 3, 11, 17]),
        (15, "Who bears responsibility for the outbreak of war?", "Vienna chose war against Serbia and Berlin enabled it, while Russian mobilisation and a militarised alliance system widened responsibility without erasing agency.", [10, 11, 12, 18]),
        (20, "How far was the First World War fought for preservation of balance of power?", "Balance of power organised the blocs and Britain's intervention but cannot absorb national, imperial and preventive motives; it was the transmission system, not the complete purpose.", [4, 6, 15, 16, 19]),
        (20, "Why did a Balkan crisis become a world war in 1914?", "A local assassination activated Austro-Serb hostility, German support, Russian mobilisation, operational rigidity and Belgian intervention inside a mistrustful imperial system.", [8, 9, 10, 11, 12, 13, 14, 17]),
    ],
    [
        plan("Europe's two alliance alignments", [0, 1, 2, 3], "Alignment did not mechanically compel every signatory to fight.", "Map the blocs and their gradual formation."),
        plan("Naval rivalry and Alsace-Lorraine", [4, 5], "Relative power and national grievance are distinct causal categories.", "Separate Anglo-German and Franco-German tensions."),
        plan("Bosnia and the Austro-Serb conflict", [6, 15], "The threat was to Habsburg survival, not only prestige.", "Place South Slav nationalism at the regional core."),
        plan("Agadir and diplomatic mistrust", [7], "Agadir sharpened alignments without making war inevitable.", "Use earlier containment to qualify inevitability."),
        plan("Balkan Wars and Serbian strength", [8], "Use 1912-13 exactly and avoid battle detail not owned.", "Explain why Austria's risk tolerance rose."),
        plan("Sarajevo as trigger", [9], "Trigger and structural cause must remain separate.", "Open chronology without reducing causation."),
        plan("Austria's ultimatum and declaration", [10], "Vienna retained decision-making agency.", "Identify the immediate choice for war."),
        plan("Germany's enabling support", [11], "Heavy responsibility does not require sole responsibility.", "Explain the blank cheque as escalation permission."),
        plan("Russian mobilisation and counter-mobilisation", [12], "Mobilisation was a strategic act, not a neutral precaution.", "Show the shift from Balkan to continental war."),
        plan("Germany, Belgium and British entry", [13, 14], "Britain's immediate legal-political trigger was Belgian neutrality.", "Trace operational planning into wider war."),
        plan("Balance of power: what it explains", [16], "Concede bloc structure, ratios and strategic fear first.", "Answer the strongest part of the 2024 demand."),
        plan("Balance of power: what it misses", [15, 19], "National and imperial motives cannot be collapsed into equilibrium.", "Build the graded how-far qualification."),
        plan("Mobilisation rigidity and miscalculation", [17], "High likelihood is not inevitability.", "Use operational time and mistaken assumptions."),
        plan("Responsibility: agents and system", [18], "Keep immediate decisions and structural conditions on separate levels.", "Produce a nuanced blame paragraph."),
        plan("The complete escalation verdict", [9, 10, 11, 12, 14, 19], "Do not substitute chronology for causal weighting.", "Conclude from trigger through system to contingent decisions."),
    ],
    [
        panel("Alliance system formation", "timeline", ["1882 -> Triple Alliance: Germany, Austria-Hungary, Italy", "1894 -> France and Russia ally", "1904 -> Entente Cordiale", "1907 -> Britain and Russia complete the Entente alignment"], ["Europe's two alliance alignments"]),
        panel("Four structural tensions", "causal-system", ["NAVAL RACE -> Britain fears relative German sea power", "ALSACE-LORRAINE -> French revanchist grievance", "ENCIRCLEMENT -> Germany reads Entente as strategic pressure", "BALKANS -> Austria and Russia compete through Serbia"], ["Naval rivalry and Alsace-Lorraine", "Bosnia and the Austro-Serb conflict"]),
        panel("Balkan crisis ladder", "timeline", ["1908 -> Austria-Hungary annexes Bosnia", "1911 -> Agadir sharpens Anglo-German mistrust", "1912-13 -> Balkan Wars strengthen Serbia", "1914 -> Austria seeks to curb Serbian nationalism"], ["Bosnia and the Austro-Serb conflict", "Agadir and diplomatic mistrust", "Balkan Wars and Serbian strength"]),
        panel("July trigger and first decision", "timeline", ["28 JUNE -> Princip assassinates Franz Ferdinand at Sarajevo", "ULTIMATUM -> Austria frames demands Serbia cannot fully accept", "28 JULY -> Austria-Hungary declares war on Serbia", "RULE -> assassination triggers; Vienna chooses war"], ["Sarajevo as trigger", "Austria's ultimatum and declaration"]),
        panel("Escalation chain", "path-consequence", ["GERMAN SUPPORT -> Austria takes hard line", "RUSSIAN MOBILISATION -> conflict becomes great-power crisis", "1/3 AUG -> Germany declares war on Russia and France", "4 AUG -> Belgium violated; Britain enters"], ["Germany's enabling support", "Russian mobilisation and counter-mobilisation", "Germany, Belgium and British entry"]),
        panel("Balance-of-power case", "argument-tree", ["BLOCS -> Europe divided into counterweights", "ENCIRCLEMENT -> Germany fears relative decline", "NAVAL RATIO -> Britain watches Channel and fleet balance", "BALKANS -> each crisis scored as a power transfer"], ["Balance of power: what it explains"]),
        panel("Motives balance cannot absorb", "comparison-table", ["AUSTRIA -> multinational empire's survival", "SERBIA -> South Slav national unification", "FRANCE -> Alsace-Lorraine revanchism", "GERMANY/RUSSIA -> preventive timing and prestige"], ["Balance of power: what it misses"]),
        panel("Mobilisation as mechanism", "causal-system", ["RUSSIA MOBILISES -> Germany sees narrowing time", "GERMAN PLAN -> attack France through Belgium", "TIMETABLES -> military sequence compresses diplomacy", "RESULT -> strategic plans widen a regional war"], ["Mobilisation rigidity and miscalculation"]),
        panel("Likelihood versus inevitability", "comparison", ["LIKELY -> blocs, arms, Balkan crises and mistrust", "NOT INEVITABLE -> 1905-06, 1908 and 1911 were contained", "BREAK -> July leaders make specific risky choices", "VERDICT -> structure raises danger; agency starts war"], ["Mobilisation rigidity and miscalculation"]),
        panel("Responsibility at two levels", "hierarchy", ["IMMEDIATE -> Vienna's decision to attack Serbia", "ENABLING -> Berlin's support and preventive calculation", "ESCALATORY -> Russian mobilisation and German plan", "SYSTEMIC -> alliances, nationalism, prestige and militarisation"], ["Responsibility: agents and system"]),
        panel("Italy and Britain traps", "comparison", ["ITALY -> Alliance member but neutral in 1914; Allies in 1915", "BRITAIN -> no binding French alliance obligation", "BELGIUM -> immediate legal-political trigger", "RULE -> alignment, obligation and entry cause are different"], ["Europe's two alliance alignments", "Germany, Belgium and British entry"]),
        panel("Outbreak answer spine", "answer-spine", ["TRIGGER -> Sarajevo, 28 June", "REGIONAL -> Austro-Serb nationality conflict", "ESCALATION -> support, mobilisation, Belgium", "VERDICT -> balance structure plus distinct motives and choices"], ["The complete escalation verdict"]),
    ],
    ["Triple Alliance", "Triple Entente", "naval rivalry", "Alsace-Lorraine", "Bosnia Crisis", "Agadir Crisis", "Balkan Wars", "Gavrilo Princip", "Franz Ferdinand", "Sarajevo", "blank cheque", "Russian mobilisation", "Belgian neutrality", "balance of power", "miscalculation"],
    "The local owners verify the 2024 GS-I demand asking how far the First World War was fought essentially for preservation of balance of power.",
    [
        (
            "2024",
            "GS-I · 15 marks · 250 words",
            "How far is it correct to say that the First World War was fought essentially for the preservation of balance of power?",
            "Exact wording verified in the local owner.",
            "Balance of power explains the framework: two counterweighted "
            "alignments, German encirclement fears, Anglo-German naval ratios, "
            "Russian-Austrian rivalry and Britain's concern over Belgium. Yet "
            "it does not fully explain purpose or timing. Austria-Hungary "
            "sought imperial survival against South Slav nationalism; Serbia "
            "sought national expansion; France retained the Alsace-Lorraine "
            "grievance; Germany considered preventive advantage; and Russian "
            "mobilisation, German operational planning and specific July "
            "decisions converted danger into war. Thus balance of power was "
            "the structure through which competing motives were transmitted, "
            "not the essential motive shared by every belligerent.",
        )
    ],
    extra=["basic/06_Unification-of-Italy-and-Germany.md", "basic/10_First-World-War-and-Aftermath.md"],
)


TOPIC_10 = common.topic(
    10,
    "First World War and Aftermath",
    "10_First-World-War-and-Aftermath",
    "10_First-World-War-and-Aftermath_Complete-Topic-Package.md",
    [
        ("Marne, September 1914", "The Battle of the Marne in September 1914 stopped a quick German victory and helped lock the western front into trench stalemate."),
        ("Gallipoli, 1915", "The Gallipoli campaign failed in 1915 while trench stalemate continued and Bulgaria joined the Central Powers."),
        ("Verdun and Somme, 1916", "Verdun and the Somme in 1916 became symbols of industrial attrition: enormous human cost, limited territorial gain and cumulative exhaustion."),
        ("Defensive firepower and trench deadlock", "Machine-guns, heavy artillery and fixed defences outmatched movement and communication, preventing tactical success from becoming strategic breakthrough."),
        ("British blockade and Jutland", "British sea power and blockade strangled Central Power supplies; Jutland was tactically indecisive but did not break British naval control."),
        ("Unrestricted submarine warfare, January 1917", "Germany resumed unrestricted submarine warfare in January 1917, a tactical gamble that threatened shipping but helped bring the United States into war."),
        ("United States enters, April 1917", "The United States entered in April 1917, contributing finance, food, shipping, morale and eventually troops."),
        ("Russia exits and Brest-Litovsk, 1917-18", "Bolshevik armistice was followed by the Treaty of Brest-Litovsk in March 1918, formally removing Russia from the war."),
        ("Ludendorff offensive and Allied counterattack, 1918", "The Ludendorff offensive failed in spring 1918, while Allied unity under Foch and coordinated counterattack broke the Hindenburg Line."),
        ("Central allies collapse", "Bulgaria, Austria-Hungary and the Ottoman Empire collapsed before Germany, exposing the weakest-member problem in coalition warfare."),
        ("Armistice, 11 November 1918", "Germany sought an armistice before deep occupation of German soil, and fighting ended on 11 November 1918."),
        ("Total war", "The war mobilised whole populations, modern industry, state controls, women workers, propaganda, blockade and imperial manpower, making civilians part of strategy."),
        ("Political and global effects", "The war destroyed the Habsburg, Ottoman, Russian and German imperial orders, produced Weimar and Bolshevik regimes, and strengthened the relative position of the United States and Japan."),
        ("League of Nations and mandates", "The peace created the League of Nations while German colonies and former Ottoman lands became mandates, preserving imperial control under conditional trusteeship language."),
        ("Treaty cluster", "The postwar settlement comprised Versailles for Germany, St Germain for Austria, Trianon for Hungary, Neuilly for Bulgaria and Sevres later revised by Lausanne for Turkey."),
        ("Versailles territorial terms", "Alsace-Lorraine returned to France; West Prussia and Posen went to Poland; Danzig became a free city; the Saar entered League administration; union with Austria was forbidden."),
        ("Versailles military terms", "Germany's army was limited to one hundred thousand, conscription, tanks, submarines and military aircraft were prohibited, and the Rhineland was demilitarised."),
        ("Article 231 and reparations", "Article 231 established liability for Allied loss and damage and became politically known as the war-guilt clause; reparations were fixed in 1921 at six thousand six hundred million pounds."),
        ("Sevres revised by Lausanne", "Turkish nationalist resistance under Mustafa Kemal rejected Sevres, and Lausanne in 1923 recognised Turkish sovereignty over eastern Thrace and Anatolia including Smyrna or Izmir."),
        ("Unstable-peace verdict", "The settlement mixed self-determination with minorities, mandates and revisionist grievances; it was harsh enough to embitter Germany but insufficiently enforced to prevent revision."),
    ],
    [
        "Do not treat every theatre as western-front trench warfare.",
        "Do not say Jutland destroyed British naval control.",
        "Do not explain United States impact through troop numbers alone.",
        "Do not claim unrestricted submarine warfare succeeded strategically.",
        "Do not say Russia remained in the war through 1918.",
        "Do not claim one battle alone defeated the Central Powers.",
        "Do not describe total war merely as a very large war.",
        "Do not treat Versailles as the whole peace settlement.",
        "Do not say Germany was deeply occupied before the armistice.",
        "Do not describe Article 231 only as a moral statement.",
        "Do not claim the settlement applied self-determination consistently.",
        "Do not say Turkey accepted Sevres unchanged.",
        "Do not claim Versailles alone caused the Second World War.",
        "Do not invent casualty totals beyond owner evidence.",
    ],
    [
        (10, "Why did the western front become a war of attrition?", "The Marne prevented quick victory while defensive firepower outran movement and communication, turning industrial capacity and endurance into the decisive tests.", [0, 2, 3]),
        (10, "Why did unrestricted submarine warfare fail strategically?", "It could not defeat the convoy-protected maritime system and helped bring American finance, shipping, food, morale and troops against Germany.", [4, 5, 6]),
        (15, "Why did the Central Powers lose?", "Two-front strain, blockade, failed submarine gamble, American resources, improved Allied unity and collapse of Germany's allies exhausted the coalition as a system.", [4, 5, 6, 7, 8, 9]),
        (15, "Explain the First World War as total war.", "Industry, state control, women workers, propaganda, civilian blockade and imperial manpower erased the boundary between battlefront and home front.", [11, 12, 13]),
        (20, "Critically evaluate the post-1919 peace settlement.", "The treaty cluster redrew boundaries and built the League but applied self-determination unevenly, preserved empire through mandates and created grievance without durable enforcement.", [13, 14, 15, 16, 17, 18, 19]),
        (20, "How did the First World War transform Europe and the wider world?", "It destroyed empires, created new regimes and states, enlarged interventionist government, mobilised women and colonies, weakened Europe and shifted relative power toward the United States and Japan.", [11, 12, 13, 19]),
    ],
    [
        plan("Marne and the failure of quick victory", [0], "Do not generalise western trench deadlock to every front.", "Explain why the expected short war failed."),
        plan("Gallipoli and global fronts", [1], "A failed side campaign did not by itself decide the war.", "Show the war extending beyond France and Belgium."),
        plan("Verdun, Somme and attrition", [2, 3], "Avoid unsupported casualty totals.", "Connect battle method to technological deadlock."),
        plan("Sea power, blockade and Jutland", [4], "Jutland was tactically indecisive but strategically preserved British control.", "Treat sea power as economic warfare."),
        plan("The submarine gamble and American entry", [5, 6], "American impact included resources and morale as well as troops.", "Show tactical action producing strategic reversal."),
        plan("Russia's exit and the 1918 opportunity", [7], "Brest-Litovsk belongs to March 1918 after the armistice process.", "Explain Germany's temporary relief."),
        plan("Ludendorff fails and Allied unity improves", [8], "Do not reduce victory to American entry alone.", "Trace operational failure and coalition coordination."),
        plan("Coalition collapse and armistice", [9, 10], "Germany sought armistice before deep occupation.", "Explain cumulative defeat and the exact endpoint."),
        plan("Total war and society", [11], "Totality means mobilisation of society, economy and civilians.", "Move beyond battlefield scale."),
        plan("Revolutions, empires and global power", [12], "Separate institutional change from social consequence.", "Map the political earthquake after 1918."),
        plan("League and mandate ambiguity", [13], "Mandates were conditional in principle yet preserved imperial rule.", "Link peace machinery to imperial continuity."),
        plan("The settlement as five treaty routes", [14], "Never use Versailles as shorthand for every defeated state.", "Fix treaty-to-state matching."),
        plan("Versailles territory and military limits", [15, 16], "Territorial and military terms perform different functions.", "Explain containment through borders and force limits."),
        plan("Article 231, reparations and Turkey", [17, 18], "Keep legal liability, political war guilt and Turkish revision distinct.", "Compare grievance with successful armed revision."),
        plan("Why the peace remained unstable", [19, 13, 17], "Versailles grievance required later depression and political choices to become catastrophe.", "Conclude with grievance, enforcement and inconsistent principle."),
    ],
    [
        panel("Why quick war failed", "causal-system", ["MARNE, SEPT 1914 -> German advance halted", "DEFENSIVE FIREPOWER -> movement cannot exploit success", "TRENCHES -> western front hardens", "RESULT -> strategy shifts from manoeuvre to endurance"], ["Marne and the failure of quick victory"]),
        panel("Attrition battlefield", "comparison-table", ["VERDUN 1916 -> prolonged exhaustion", "SOMME 1916 -> huge cost and limited ground", "DEFENCE -> machine-guns and artillery dominate", "STRATEGIC TEST -> manpower, industry and morale"], ["Verdun, Somme and attrition"]),
        panel("Sea-war mechanism", "path-consequence", ["BRITISH FLEET -> blockade Central Powers", "JUTLAND -> no decisive tactical resolution", "GERMAN U-BOATS -> unrestricted campaign", "CONVOYS -> shipping losses reduced; British control survives"], ["Sea power, blockade and Jutland", "The submarine gamble and American entry"]),
        panel("1917 strategic exchange", "comparison", ["RUSSIA -> revolution and exit reduce Germany's eastern burden", "USA -> entry adds finance, food, shipping, morale and troops", "GERMAN GAMBLE -> submarine warfare helps trigger US entry", "NET EFFECT -> American resources offset Russian withdrawal"], ["The submarine gamble and American entry", "Russia's exit and the 1918 opportunity"]),
        panel("How the Central Powers lost", "causal-system", ["TWO FRONTS -> Germany's structural burden", "BLOCKADE -> supplies and civilian endurance weaken", "1918 OFFENSIVE -> Ludendorff fails", "ALLIES COLLAPSE -> Bulgaria, Habsburg and Ottoman systems fall"], ["Ludendorff fails and Allied unity improves", "Coalition collapse and armistice"]),
        panel("Total-war society", "hierarchy", ["STATE -> controls industry, transport and food", "WOMEN -> enter expanded wartime production roles", "CIVILIANS -> blockade and propaganda make home front strategic", "EMPIRE -> colonial manpower and territory globalise the war"], ["Total war and society"]),
        panel("Political earthquake", "comparison-table", ["RUSSIA -> Bolshevik rule", "GERMANY -> revolution and Weimar Republic", "HABSBURG/OTTOMAN -> empires collapse into new arrangements", "GLOBAL POWER -> USA and Japan gain as Europe weakens"], ["Revolutions, empires and global power"]),
        panel("Five-treaty matching", "comparison-table", ["VERSAILLES -> Germany; ST GERMAIN -> Austria", "TRIANON -> Hungary; NEUILLY -> Bulgaria", "SEVRES -> Ottoman Turkey, rejected", "LAUSANNE 1923 -> revised Turkish settlement"], ["The settlement as five treaty routes"]),
        panel("Versailles containment", "comparison", ["TERRITORY -> Alsace-Lorraine, Poland, Danzig, Saar", "MILITARY -> 100,000 army; no conscription or key weapons", "RHINELAND -> demilitarised", "AUSTRIA -> union with Germany forbidden"], ["Versailles territory and military limits"]),
        panel("Article 231 and reparations", "path-consequence", ["ARTICLE 231 -> legal liability for Allied loss and damage", "POLITICS -> read in Germany as war-guilt clause", "1921 -> reparations fixed at £6600 million", "EFFECT -> revisionist grievance plus enforcement problem"], ["Article 231, reparations and Turkey"]),
        panel("Mandates: change and continuity", "comparison", ["OLD LANGUAGE -> conquest and annexation", "NEW LANGUAGE -> League trusteeship and preparation for independence", "PRACTICE -> Britain and France retain imperial control", "VERDICT -> empire survives under conditional justification"], ["League and mandate ambiguity"]),
        panel("War-and-peace answer spine", "answer-spine", ["COURSE -> failed quick war, attrition, blockade and coalition collapse", "TOTAL WAR -> state, society, women, civilians and empire", "SETTLEMENT -> treaty cluster, League, mandates and minorities", "VERDICT -> political earthquake followed by unstable peace"], ["Why the peace remained unstable"]),
    ],
    ["Battle of the Marne", "Gallipoli", "Verdun", "Somme", "Jutland", "unrestricted submarine warfare", "United States", "Brest-Litovsk", "Ludendorff", "Armistice", "total war", "League of Nations", "Treaty of Versailles", "Article 231", "Treaty of Lausanne"],
    "No direct UPSC PYQ is verified as owned solely by this topic in the local 2018-2025 routing blocks. The exact 2024 balance-of-power demand belongs to Topic 09, not to this course-and-aftermath owner.",
    [],
    extra=["basic/09_World-in-1914-and-Outbreak-of-WWI.md", "basic/11_International-Relations-1919-39.md"],
)


ALL_TOPICS = [TOPIC_06, TOPIC_07, TOPIC_08, TOPIC_09, TOPIC_10]
